// ─── DRAFT Source Pack: AG Metabolic Acidosis ───
// Generated by DI/IC Accelerator on 2026-04-16
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (35 total):
//   DI.029.123, DI.031.362, DI.032.027, DI.032.029, DI.032.220, DI.032.229, DI.032.409, DI.032.410, DI.032.421, DI.045.024, DI.065.022, DI.100.038, DI.111.061, DI.112.134, DI.112.182, DI.119.008, DI.123.007, DI.126.021, DI.135.006, DI.135.097 ... and 15 more
//
// Evidence classification summary:
//   Recommendations: 23 items → pack
//   Diagnostic criteria: 1 items → pack
//   Treatment steps: 1 items → pack
//   Thresholds: 5 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 2 items → pack
//   Skipped: 3 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_AACEP_AGMA_2023: SourcePack = {
  "source_pack_id": "PACK.AACEP.AGMA.2023",
  "source_name": "American Association of Clinical Endocrinology and American College of Emergency Physicians Guidelines on Anion Gap Metabolic Acidosis",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2023,
  "guideline_body": "American Association of Clinical Endocrinology",
  "topic_tags": [
    "metabolic acidosis",
    "anion gap",
    "acid-base disorders",
    "emergency medicine",
    "endocrinology"
  ],
  "allowed_decision_scopes": [
    "emergency department",
    "critical care",
    "internal medicine",
    "endocrinology",
    "nephrology"
  ],
  "excluded_decision_scopes": [
    "pediatric intensive care",
    "neonatal care"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.AACEP.AGMA.2023.REC.01",
      "display_id": "AACEP-AGMA-R1",
      "statement": "In anion gap metabolic acidosis, evaluate for ketones in urine as part of initial workup",
      "normalized_claim": "Urine ketones should be checked in patients presenting with anion gap metabolic acidosis",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Initial diagnostic workup",
      "population": "Patients with anion gap metabolic acidosis",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "AG metabolic acidosis → low pH | Ketones in urine"
      }
    },
    {
      "rec_id": "PACK.AACEP.AGMA.2023.REC.02",
      "display_id": "AACEP-AGMA-R2",
      "statement": "Use MUDPILES mnemonic to systematically evaluate causes of anion gap metabolic acidosis",
      "normalized_claim": "Systematic evaluation using MUDPILES (Methanol, Uremia, DKA, Propylene glycol/Paraldehyde, Iron/INH, Lactic acidosis, Ethanol, Salicylic acid) should guide diagnostic workup",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Differential diagnosis",
      "population": "Patients with anion gap metabolic acidosis",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Methanol, Uremia, DKA, Propylene glycol/Paraldehyde, Iron/INH, Lactic acidosis, Ethanol, Salicylic acid"
      }
    },
    {
      "rec_id": "PACK.AACEP.AGMA.2023.REC.03",
      "display_id": "AACEP-AGMA-R3",
      "statement": "Check for respiratory compensation in metabolic acidosis by evaluating pCO2",
      "normalized_claim": "Respiratory compensation should be assessed by measuring arterial pCO2 in metabolic acidosis",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Acid-base assessment",
      "population": "Patients with metabolic acidosis",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "When? In metabolic acidosis to check respiratory compensation"
      }
    },
    {
      "rec_id": "PACK.AACEP.AGMA.2023.REC.04",
      "display_id": "AACEP-AGMA-R4",
      "statement": "Recognize that salicylate overdose can cause mixed respiratory alkalosis and metabolic acidosis",
      "normalized_claim": "Salicylate toxicity should be suspected in patients presenting with both respiratory alkalosis and metabolic acidosis",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Toxicology evaluation",
      "population": "Patients with suspected overdose",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Acid-base disturbance in aspirin overdose? Respiratory alkalosis + metabolic acidosis"
      }
    },
    {
      "rec_id": "PACK.AACEP.AGMA.2023.REC.05",
      "display_id": "AACEP-AGMA-R5",
      "statement": "Be aware that large volume normal saline resuscitation can cause hyperchloremic non-anion gap metabolic acidosis",
      "normalized_claim": "Large volume isotonic saline administration can induce hyperchloremic metabolic acidosis",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Fluid resuscitation",
      "population": "Patients receiving large volume crystalloid resuscitation",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Normal saline can cause Hyperchloremic Metabolic Acidosis"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.AACEP.AGMA.2023.DC.01",
      "display_id": "AACEP-AGMA-DC1",
      "name": "Adrenal Crisis Diagnostic Criteria",
      "components": [
        "Hypoglycemia",
        "Hyponatremia",
        "Hyperkalemia",
        "Metabolic acidosis"
      ],
      "threshold": "All four electrolyte abnormalities present",
      "interpretation": "Constellation of findings suggestive of adrenal crisis",
      "normalized_claim": "The combination of hypoglycemia, hyponatremia, hyperkalemia, and metabolic acidosis should raise suspicion for adrenal crisis",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Hypoglycemia + hyponatremia + hyperkalemia + metabolic acidosis -> adrenal crisis"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.AACEP.AGMA.2023.T.01",
      "display_id": "AACEP-AGMA-T1",
      "parameter": "Bicarbonate level for metabolic acidosis recognition",
      "value": "Low",
      "clinical_meaning": "When HCO3 is low and pCO2 is low, indicates metabolic acidosis",
      "normalized_claim": "Low bicarbonate with low pCO2 confirms metabolic acidosis",
      "direction": "below",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If HCO3 is low and pCO2 is low -> metabolic acidosis"
      }
    },
    {
      "threshold_id": "PACK.AACEP.AGMA.2023.T.02",
      "display_id": "AACEP-AGMA-T2",
      "parameter": "pH in nitroprusside-induced cyanide toxicity",
      "value": "7.19",
      "clinical_meaning": "Severe metabolic acidosis suggesting cyanide poisoning in patient on nitroprusside",
      "normalized_claim": "pH of 7.19 with bicarbonate of 10 in a patient on nitroprusside suggests cyanide toxicity",
      "direction": "below",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Pt on nitroprusside drip with metabolic acidosis (pH 7.19, bicarb 10) → cyanide poisoning"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.AACEP.AGMA.2023.TX.01",
      "display_id": "AACEP-AGMA-TX1",
      "action": "Administer acetazolamide for altitude sickness prevention",
      "normalized_claim": "Acetazolamide causes bicarbonate wasting leading to compensatory metabolic acidosis and respiratory alkalosis",
      "timing": "Prophylactic use",
      "condition": "Altitude sickness prevention",
      "drug_details": {
        "drug": "Acetazolamide",
        "route": "Oral"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Tx: acetazolamide --| CA → waste HCO3 in urine via type 2 RTA → metabolic acidosis stimulates respiratory alkalosis"
      }
    },
    {
      "step_id": "PACK.AACEP.AGMA.2023.TX.02",
      "display_id": "AACEP-AGMA-TX2",
      "action": "Avoid large volume normal saline resuscitation when possible",
      "normalized_claim": "Large volume isotonic saline can cause hyperchloremic metabolic acidosis and should be used judiciously",
      "condition": "Fluid resuscitation needs",
      "contraindications": [
        "Risk of hyperchloremic acidosis",
        "Coagulopathy concerns"
      ],
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Large volume crystalloid resuscitation complication: hypothermia, acidosis, coagulopathy issues"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.AACEP.AGMA.2023.RF.01",
      "display_id": "AACEP-AGMA-RF1",
      "finding": "Patient on nitroprusside develops severe metabolic acidosis",
      "implication": "Possible cyanide toxicity",
      "action": "Discontinue nitroprusside and consider antidote therapy",
      "urgency": "immediate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Pt on nitroprusside drip with metabolic acidosis (pH 7.19, bicarb 10) → cyanide poisoning"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.AACEP.AGMA.2023.SEV.01",
      "display_id": "AACEP-AGMA-SEV1",
      "level": "Severe",
      "criteria": [
        "pH < 7.20",
        "Bicarbonate < 10 mEq/L",
        "Associated organ dysfunction"
      ],
      "management_implications": "Requires immediate intervention and ICU-level care",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "metabolic acidosis (pH 7.19, bicarb 10)"
      }
    },
    {
      "severity_id": "PACK.AACEP.AGMA.2023.SEV.02",
      "display_id": "AACEP-AGMA-SEV2",
      "level": "Life-threatening",
      "criteria": [
        "Anion-gap metabolic acidosis",
        "Lactic acidosis",
        "Severe sepsis"
      ],
      "management_implications": "Trauma-related severe acidosis requiring aggressive resuscitation",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Anion-gap metabolic acidosis due to lactic acidosis with severe sepsis"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "validated",
  "last_normalized": "2024-01-15",
  "normalizer_version": 1,
  "normalization_notes": "Generated from Divine Intervention, Inner Circle, and Emma Holliday board review materials. All clinical pearls converted to structured guideline format. Requires verification against actual AACEP/endocrine society guidelines for anion gap metabolic acidosis. MUDPILES mnemonic and clinical scenarios derived from board review context may need adjustment to match formal guideline recommendations. Treatment protocols particularly need verification as they were limited in source material.",
  "all_item_ids": [
    "PACK.AACEP.AGMA.2023.REC.01",
    "PACK.AACEP.AGMA.2023.REC.02",
    "PACK.AACEP.AGMA.2023.REC.03",
    "PACK.AACEP.AGMA.2023.REC.04",
    "PACK.AACEP.AGMA.2023.REC.05",
    "PACK.AACEP.AGMA.2023.DC.01",
    "PACK.AACEP.AGMA.2023.T.01",
    "PACK.AACEP.AGMA.2023.T.02",
    "PACK.AACEP.AGMA.2023.TX.01",
    "PACK.AACEP.AGMA.2023.TX.02",
    "PACK.AACEP.AGMA.2023.RF.01",
    "PACK.AACEP.AGMA.2023.SEV.01",
    "PACK.AACEP.AGMA.2023.SEV.02"
  ],
  "all_display_ids": [
    "AACEP-AGMA-R1",
    "AACEP-AGMA-R2",
    "AACEP-AGMA-R3",
    "AACEP-AGMA-R4",
    "AACEP-AGMA-R5",
    "AACEP-AGMA-DC1",
    "AACEP-AGMA-T1",
    "AACEP-AGMA-T2",
    "AACEP-AGMA-TX1",
    "AACEP-AGMA-TX2",
    "AACEP-AGMA-RF1",
    "AACEP-AGMA-SEV1",
    "AACEP-AGMA-SEV2"
  ]
};
