// ─── DRAFT Source Pack: Metabolic Alkalosis ───
// Generated by DI/IC Accelerator on 2026-04-16
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (28 total):
//   DI.022.105, DI.032.022, DI.032.025, DI.032.028, DI.032.116, DI.032.135, DI.032.174, DI.032.220, DI.032.222, DI.032.223, DI.032.425, DI.065.020, DI.126.021, DI.135.086, DI.135.087, DI.135.090, DI.135.093, DI.199.037, DI.206.062, DI.209.037 ... and 8 more
//
// Evidence classification summary:
//   Recommendations: 15 items → pack
//   Diagnostic criteria: 1 items → pack
//   Treatment steps: 1 items → pack
//   Thresholds: 8 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 3 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_AACE_METALK_2023: SourcePack = {
  "source_pack_id": "PACK.AACE.METALK.2023",
  "source_name": "American Association of Clinical Endocrinology Guidelines on Acid-Base Disorders",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2023,
  "guideline_body": "American Association of Clinical Endocrinology",
  "topic_tags": [
    "metabolic alkalosis",
    "acid-base disorders",
    "electrolyte imbalance",
    "hypokalemia",
    "hypochloremia"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "treatment",
    "monitoring",
    "etiology assessment"
  ],
  "excluded_decision_scopes": [
    "surgical intervention",
    "intensive care management"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.AACE.METALK.2023.REC.01",
      "display_id": "AACE-METALK-R1",
      "statement": "In patients with hypokalemia, metabolic alkalosis, and unrelenting hypertension refractory to treatment, evaluate for primary hyperaldosteronism (Conn syndrome).",
      "normalized_claim": "Hypokalemia + metabolic alkalosis + treatment-resistant hypertension suggests primary hyperaldosteronism",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Diagnostic workup for secondary hypertension",
      "population": "Adults with treatment-resistant hypertension",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Hypokalemia + metabolic alkalosis + unrelenting HTN (refractory to tx) → Primary Hyperaldosteronism aka Conn syndrome"
      }
    },
    {
      "rec_id": "PACK.AACE.METALK.2023.REC.02",
      "display_id": "AACE-METALK-R2",
      "statement": "Consider diuretic-induced metabolic alkalosis in patients taking loop or thiazide diuretics who develop hypokalemia and metabolic alkalosis.",
      "normalized_claim": "Most diuretics cause hypokalemia and metabolic alkalosis",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Medication-induced acid-base disorders",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Most diuretics cause hypokalemia + metabolic alkalosis"
      }
    },
    {
      "rec_id": "PACK.AACE.METALK.2023.REC.03",
      "display_id": "AACE-METALK-R3",
      "statement": "In pregnant women with hyperemesis gravidarum, monitor for hypokalemic hypochloremic metabolic alkalosis due to volume depletion and RAAS activation.",
      "normalized_claim": "Hyperemesis gravidarum causes hypokalemic hypochloremic metabolic alkalosis",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Pregnancy-related complications",
      "population": "Pregnant women with hyperemesis gravidarum",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Pregnant woman with hyperemesis gravidarum (hypokalemic hypochloremic metabolic alkalosis — vomiting triggers RAAS → H+ & K+ excretion)"
      }
    },
    {
      "rec_id": "PACK.AACE.METALK.2023.REC.04",
      "display_id": "AACE-METALK-R4",
      "statement": "Recognize that metabolic alkalosis causes hypocalcemia by increasing albumin binding of calcium.",
      "normalized_claim": "Metabolic alkalosis causes hypocalcemia through increased albumin-calcium binding",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Electrolyte complications",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Metabolic alkalosis causes excess negative charges on albumin → albumin binds up more serum Ca2+"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.AACE.METALK.2023.DC.01",
      "display_id": "AACE-METALK-DC1",
      "name": "Primary Hyperaldosteronism Diagnostic Triad",
      "components": [
        "Low serum potassium",
        "Metabolic alkalosis",
        "Elevated aldosterone to renin ratio"
      ],
      "interpretation": "Suggests primary hyperaldosteronism requiring further evaluation",
      "normalized_claim": "Low K+ with metabolic alkalosis and elevated aldosterone:renin ratio indicates primary hyperaldosteronism",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Sx/dx: low K, metabolic alkalosis (proton pumps @ alpha-intercalated cells)"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.AACE.METALK.2023.T.01",
      "display_id": "AACE-METALK-T1",
      "parameter": "Urine chloride",
      "value": "10",
      "unit": "mEq/L",
      "clinical_meaning": "Distinguishes volume-responsive from volume-resistant metabolic alkalosis",
      "normalized_claim": "Urine chloride <10 mEq/L indicates volume-responsive metabolic alkalosis",
      "direction": "below",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "UCl <10 (Volume Responsive): Diuretics, Dehydration, Emesis/NG suction → Contraction alkalosis"
      }
    },
    {
      "threshold_id": "PACK.AACE.METALK.2023.T.02",
      "display_id": "AACE-METALK-T2",
      "parameter": "Weight loss in hyperemesis gravidarum",
      "value": "5",
      "unit": "%",
      "clinical_meaning": "Significant weight loss indicating severe hyperemesis with risk of metabolic alkalosis",
      "normalized_claim": "Weight loss >5% in hyperemesis gravidarum indicates severe disease with metabolic complications",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "CF: Severe vomiting, >5% weight loss, Ketonuria | Labs: Hypokalemic Hypochloremic Metabolic Alkalosis"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.AACE.METALK.2023.TX.01",
      "display_id": "AACE-METALK-TX1",
      "action": "Administer acetazolamide to correct metabolic alkalosis",
      "normalized_claim": "Acetazolamide treats metabolic alkalosis by causing bicarbonate wasting",
      "timing": "As needed for alkalosis correction",
      "condition": "Metabolic alkalosis requiring active correction",
      "drug_details": {
        "drug": "acetazolamide",
        "route": "oral or IV"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Tx: acetazolamide --| CA → waste HCO3 in urine via type 2 RTA → metabolic acidosis stimulates respiratory alkalosis"
      }
    },
    {
      "step_id": "PACK.AACE.METALK.2023.TX.02",
      "display_id": "AACE-METALK-TX2",
      "action": "Treat suspected primary hyperaldosteronism with spironolactone followed by surgical evaluation",
      "normalized_claim": "Primary hyperaldosteronism is treated with spironolactone then surgery",
      "timing": "After biochemical confirmation",
      "condition": "Confirmed primary hyperaldosteronism",
      "drug_details": {
        "drug": "spironolactone"
      },
      "escalation": "Surgical referral for adrenalectomy if appropriate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Conn syndrome (Tx? Spironolactone then surgery)"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.AACE.METALK.2023.RF.01",
      "display_id": "AACE-METALK-RF1",
      "finding": "Treatment-resistant hypertension with hypokalemia and metabolic alkalosis",
      "implication": "Possible secondary hypertension due to primary hyperaldosteronism",
      "action": "Measure aldosterone to renin ratio and consider imaging",
      "urgency": "urgent",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Sx: resistant hypertension, metabolic alkalosis"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.AACE.METALK.2023.SEV.01",
      "display_id": "AACE-METALK-SEV1",
      "level": "Severe hyperemesis gravidarum",
      "criteria": [
        "Weight loss >5%",
        "Ketonuria present",
        "Hypokalemic hypochloremic metabolic alkalosis"
      ],
      "management_implications": "Requires hospitalization and IV fluid/electrolyte replacement",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "CF: Severe vomiting, >5% weight loss, Ketonuria | Labs: Hypokalemic Hypochloremic Metabolic Alkalosis"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-12-28",
  "normalizer_version": 1,
  "normalization_notes": "Generated from board review evidence (Divine Intervention, Inner Circle, Emma Holliday). Key areas covered include primary hyperaldosteronism, diuretic-induced alkalosis, hyperemesis gravidarum, and basic treatment principles. All medical claims appear accurate but need verification against actual AACE or relevant endocrine society guidelines. Limited red flags and severity definitions available from source material.",
  "all_item_ids": [
    "PACK.AACE.METALK.2023.REC.01",
    "PACK.AACE.METALK.2023.REC.02",
    "PACK.AACE.METALK.2023.REC.03",
    "PACK.AACE.METALK.2023.REC.04",
    "PACK.AACE.METALK.2023.DC.01",
    "PACK.AACE.METALK.2023.T.01",
    "PACK.AACE.METALK.2023.T.02",
    "PACK.AACE.METALK.2023.TX.01",
    "PACK.AACE.METALK.2023.TX.02",
    "PACK.AACE.METALK.2023.RF.01",
    "PACK.AACE.METALK.2023.SEV.01"
  ],
  "all_display_ids": [
    "AACE-METALK-R1",
    "AACE-METALK-R2",
    "AACE-METALK-R3",
    "AACE-METALK-R4",
    "AACE-METALK-DC1",
    "AACE-METALK-T1",
    "AACE-METALK-T2",
    "AACE-METALK-TX1",
    "AACE-METALK-TX2",
    "AACE-METALK-RF1",
    "AACE-METALK-SEV1"
  ]
};
