// ─── DRAFT Source Pack: Psoriasis ───
// Generated by DI/IC Accelerator on 2026-04-16
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (16 total):
//   DI.030.367, DI.030.368, DI.030.369, DI.030.370, DI.030.371, DI.189.006, DI.189.007, DI.189.008, DI.242.010, DI.242.011, DI.242.012, DI.242.013, DI.242.014, DI.242.015, IC.070.012, IC.095.014
//
// Evidence classification summary:
//   Recommendations: 11 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 4 items → pack
//   Thresholds: 0 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 1 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_AAD_PSO_2019: SourcePack = {
  "source_pack_id": "PACK.AAD.PSO.2019",
  "source_name": "Guidelines of care for the management of psoriasis and psoriatic arthritis",
  "canonical_url": "TODO: Add AAD psoriasis guideline URL",
  "publication_year": 2019,
  "guideline_body": "American Academy of Dermatology",
  "topic_tags": [
    "psoriasis",
    "psoriatic arthritis",
    "dermatology",
    "autoimmune",
    "skin"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "treatment",
    "monitoring",
    "risk_assessment"
  ],
  "excluded_decision_scopes": [
    "prevention",
    "screening"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.AAD.PSO.2019.REC.01",
      "display_id": "AAD-PSO-R1",
      "statement": "Erythematous salmon-colored patches with silvery scale on elbows and knees are characteristic of psoriasis",
      "normalized_claim": "Psoriasis typically presents as erythematous plaques with silvery scale in characteristic locations",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Clinical diagnosis",
      "population": "Patients with suspected psoriasis",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Erythematous salmon colored patch with silvery scale on the elbows and knees → psoriasis"
      }
    },
    {
      "rec_id": "PACK.AAD.PSO.2019.REC.02",
      "display_id": "AAD-PSO-R2",
      "statement": "Patients with psoriasis presenting with joint pain, especially in fingers, should be evaluated for psoriatic arthritis",
      "normalized_claim": "Joint pain in psoriasis patients warrants evaluation for psoriatic arthritis",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Arthritis screening",
      "population": "Psoriasis patients with joint symptoms",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If this patient presents with joint pain (especially in the fingers) → Psoriatic arthritis"
      }
    },
    {
      "rec_id": "PACK.AAD.PSO.2019.REC.03",
      "display_id": "AAD-PSO-R3",
      "statement": "Screen psoriasis patients for depression due to increased mental health association",
      "normalized_claim": "Psoriasis patients should be screened for depression",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "context": "Mental health screening",
      "population": "All psoriasis patients",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Mental health association? Depression"
      }
    },
    {
      "rec_id": "PACK.AAD.PSO.2019.REC.04",
      "display_id": "AAD-PSO-R4",
      "statement": "Avoid beta-blockers, NSAIDs, ACE inhibitors, oral steroids, and tetracycline in psoriasis patients as they may worsen the condition",
      "normalized_claim": "Certain medications can exacerbate psoriasis and should be avoided when possible",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Medication management",
      "population": "All psoriasis patients",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Worsened by: beta-blockers, NSAIDs, ACE-I, oral steroids, tetracycline"
      }
    },
    {
      "rec_id": "PACK.AAD.PSO.2019.REC.05",
      "display_id": "AAD-PSO-R5",
      "statement": "Never administer oral or IV steroids for psoriasis due to risk of severe rebound",
      "normalized_claim": "Systemic corticosteroids are contraindicated in psoriasis treatment",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Treatment contraindication",
      "population": "All psoriasis patients",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "NEVER give oral/IV steroids for psoriasis!"
      }
    },
    {
      "rec_id": "PACK.AAD.PSO.2019.REC.06",
      "display_id": "AAD-PSO-R6",
      "statement": "Consider HIV testing in patients with sudden-onset severe psoriasis",
      "normalized_claim": "Sudden severe psoriasis may indicate HIV infection and warrants testing",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "context": "HIV screening",
      "population": "Patients with sudden-onset severe psoriasis",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Sudden-onset severe Psoriasis → HIV testing required"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.AAD.PSO.2019.DC.01",
      "display_id": "AAD-PSO-DC1",
      "name": "Plaque Psoriasis Clinical Features",
      "components": [
        "Thick erythematous plaques",
        "Silver scales",
        "Distribution: elbows/knees/scalp/ears/genitalia",
        "Thick pitted nails"
      ],
      "interpretation": "Characteristic features of plaque psoriasis",
      "normalized_claim": "Plaque psoriasis diagnosis based on characteristic morphology and distribution",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Thick erythematous plaques + silver scales on elbows/knees/scalp/ears/genitalia + thick pitted nails"
      }
    },
    {
      "criterion_id": "PACK.AAD.PSO.2019.DC.02",
      "display_id": "AAD-PSO-DC2",
      "name": "Guttate Psoriasis Features",
      "components": [
        "Tiny papules/plaques on trunk",
        "History of Group A strep infection",
        "Positive Auspitz sign",
        "Koebner phenomenon",
        "Nail pitting/onycholysis"
      ],
      "interpretation": "Diagnostic features of guttate psoriasis",
      "normalized_claim": "Guttate psoriasis diagnosed by characteristic lesions following streptococcal infection",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Tiny papules/plaques on trunk after Group A strep infection"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.AAD.PSO.2019.T.01",
      "display_id": "AAD-PSO-T1",
      "parameter": "Psoriatic arthritis screening",
      "value": "joint pain present",
      "clinical_meaning": "Warrants evaluation for psoriatic arthritis",
      "normalized_claim": "Joint pain in psoriasis patients indicates need for arthritis evaluation",
      "direction": "present",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If this patient presents with joint pain (especially in the fingers) → Psoriatic arthritis"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.AAD.PSO.2019.TX.01",
      "display_id": "AAD-PSO-TX1",
      "action": "First-line topical therapy",
      "normalized_claim": "Topical corticosteroids are first-line treatment for psoriasis",
      "timing": "Initial treatment",
      "drug_details": {
        "drug": "topical corticosteroids"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Tx: Topical steroids"
      }
    },
    {
      "step_id": "PACK.AAD.PSO.2019.TX.02",
      "display_id": "AAD-PSO-TX2",
      "action": "Alternative first-line topical treatments",
      "normalized_claim": "Vitamin D analogs, coal tar, and retinoids are effective topical treatments",
      "timing": "First-line alternatives",
      "drug_details": {
        "drug": "calcipotriene, coal tar, retinoids, anthralin"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Tx: 1st topical steroids/coal tar/Vit D analog (calcipotriene)"
      }
    },
    {
      "step_id": "PACK.AAD.PSO.2019.TX.03",
      "display_id": "AAD-PSO-TX3",
      "action": "Second-line systemic therapy",
      "normalized_claim": "Methotrexate or cyclosporine for moderate to severe psoriasis",
      "timing": "When topical therapy inadequate",
      "condition": "Moderate to severe disease",
      "drug_details": {
        "drug": "methotrexate or cyclosporine"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "2nd methotrexate or cyclosporine"
      }
    },
    {
      "step_id": "PACK.AAD.PSO.2019.TX.04",
      "display_id": "AAD-PSO-TX4",
      "action": "Third-line therapy",
      "normalized_claim": "TNF-alpha inhibitors or phototherapy for refractory disease",
      "timing": "When first and second-line therapy fail",
      "condition": "Refractory severe disease",
      "drug_details": {
        "drug": "TNF-alpha inhibitors"
      },
      "escalation": "Consider UV-B or PUVA phototherapy",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "3rd TNF-alpha inhibitors or UV-B/PUVA"
      }
    },
    {
      "step_id": "PACK.AAD.PSO.2019.TX.05",
      "display_id": "AAD-PSO-TX5",
      "action": "Psoriatic arthritis treatment",
      "normalized_claim": "NSAIDs are used for psoriatic arthritis symptom management",
      "timing": "For joint symptoms",
      "condition": "Psoriatic arthritis",
      "drug_details": {
        "drug": "NSAIDs"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Tx: NSAIDs"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.AAD.PSO.2019.RF.01",
      "display_id": "AAD-PSO-RF1",
      "finding": "Psoriasis patient on systemic steroids with erythrodermic changes",
      "implication": "Risk of steroid withdrawal erythroderma with electrolyte abnormalities",
      "action": "Immediate discontinuation support and monitoring",
      "urgency": "immediate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Psoriasis pt on steroids → skin turns really red; c/b electrolyte abnormalities"
      }
    },
    {
      "flag_id": "PACK.AAD.PSO.2019.RF.02",
      "display_id": "AAD-PSO-RF2",
      "finding": "Sudden-onset severe psoriasis",
      "implication": "May indicate underlying HIV infection",
      "action": "Perform HIV testing",
      "urgency": "urgent",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Sudden-onset severe Psoriasis → HIV testing required"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.AAD.PSO.2019.SEV.01",
      "display_id": "AAD-PSO-SEV1",
      "level": "Nail psoriasis with hand involvement",
      "criteria": [
        "Hand presentation",
        "Nail psoriasis present",
        "May have associated triggers"
      ],
      "management_implications": "Requires specialized treatment approach due to functional impact",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Hand presentation presents with nail psoriasis"
      }
    },
    {
      "severity_id": "PACK.AAD.PSO.2019.SEV.02",
      "display_id": "AAD-PSO-SEV2",
      "level": "Severe psoriasis with systemic implications",
      "criteria": [
        "Sudden onset",
        "Severe presentation",
        "Potential systemic triggers"
      ],
      "management_implications": "Requires HIV testing and aggressive management",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Sudden-onset severe Psoriasis → HIV testing required"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "validated",
  "last_normalized": "2024-12-19T18:11:42Z",
  "normalizer_version": 1,
  "normalization_notes": "Generated from Divine Intervention and Inner Circle board review materials. Key clinical pearls converted to structured recommendations and treatment protocols. Notable gaps: limited quantitative thresholds and formal diagnostic criteria from source material. Steroid contraindication and HIV screening recommendations need verification against actual AAD guidelines. All items require validation against current AAD psoriasis management guidelines.",
  "all_item_ids": [
    "PACK.AAD.PSO.2019.REC.01",
    "PACK.AAD.PSO.2019.REC.02",
    "PACK.AAD.PSO.2019.REC.03",
    "PACK.AAD.PSO.2019.REC.04",
    "PACK.AAD.PSO.2019.REC.05",
    "PACK.AAD.PSO.2019.REC.06",
    "PACK.AAD.PSO.2019.DC.01",
    "PACK.AAD.PSO.2019.DC.02",
    "PACK.AAD.PSO.2019.T.01",
    "PACK.AAD.PSO.2019.TX.01",
    "PACK.AAD.PSO.2019.TX.02",
    "PACK.AAD.PSO.2019.TX.03",
    "PACK.AAD.PSO.2019.TX.04",
    "PACK.AAD.PSO.2019.TX.05",
    "PACK.AAD.PSO.2019.RF.01",
    "PACK.AAD.PSO.2019.RF.02",
    "PACK.AAD.PSO.2019.SEV.01",
    "PACK.AAD.PSO.2019.SEV.02"
  ],
  "all_display_ids": [
    "AAD-PSO-R1",
    "AAD-PSO-R2",
    "AAD-PSO-R3",
    "AAD-PSO-R4",
    "AAD-PSO-R5",
    "AAD-PSO-R6",
    "AAD-PSO-DC1",
    "AAD-PSO-DC2",
    "AAD-PSO-T1",
    "AAD-PSO-TX1",
    "AAD-PSO-TX2",
    "AAD-PSO-TX3",
    "AAD-PSO-TX4",
    "AAD-PSO-TX5",
    "AAD-PSO-RF1",
    "AAD-PSO-RF2",
    "AAD-PSO-SEV1",
    "AAD-PSO-SEV2"
  ]
};
