import type { SourcePack } from './types';

export const PACK_AAN_EPIL_2018: SourcePack = {
  source_pack_id: 'PACK.AAN.EPIL.2018',
  source_name: 'AAN/AES 2016 Guideline on Treatment of New-Onset Epilepsy & AAN 2016 Status Epilepticus Guideline',
  source_registry_id: 'REG.AAN.EPIL',
  canonical_url: 'https://doi.org/10.1212/WNL.0000000000004480',
  publication_year: 2018,
  guideline_body: 'AAN/AES',

  topic_tags: ['Epilepsy', 'Seizures', 'Status Epilepticus', 'AED Selection', 'Neurology'],
  allowed_decision_scopes: [
    'seizure classification',
    'first seizure workup',
    'AED selection by seizure type',
    'status epilepticus management',
    'AED teratogenicity counseling',
    'breakthrough seizure management',
    'EEG interpretation in seizure evaluation',
    'neuroimaging in new-onset seizure',
  ],
  excluded_decision_scopes: [
    'epilepsy surgery candidacy',
    'vagus nerve stimulation programming',
    'ketogenic diet management',
    'neonatal seizures',
    'pediatric epilepsy syndromes',
  ],

  recommendations: [
    {
      rec_id: 'PACK.AAN.EPIL.2018.REC.01',
      display_id: 'AAN-EPIL-R1',
      statement: 'All patients with a first unprovoked seizure should undergo EEG. An abnormal EEG with epileptiform discharges significantly increases recurrence risk and supports initiation of AED therapy.',
      normalized_claim: 'EEG is indicated after first unprovoked seizure; epileptiform discharges predict recurrence and guide AED initiation.',
      strength: 'strong',
      evidence_quality: 'moderate',
      context: 'Applies to adults presenting with a first unprovoked seizure',
      provenance: { section: 'First Seizure Evaluation', page_or_location: 'Section 2.1' },
    },
    {
      rec_id: 'PACK.AAN.EPIL.2018.REC.02',
      display_id: 'AAN-EPIL-R2',
      statement: 'MRI of the brain is recommended for all patients with new-onset seizures to identify structural lesions. CT is appropriate only in the acute/emergency setting.',
      normalized_claim: 'Brain MRI recommended for new-onset seizures; CT acceptable only in emergency setting.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Neuroimaging', page_or_location: 'Section 2.2' },
    },
    {
      rec_id: 'PACK.AAN.EPIL.2018.REC.03',
      display_id: 'AAN-EPIL-R3',
      statement: 'Levetiracetam and lamotrigine are preferred first-line AEDs for focal epilepsy due to broad efficacy, favorable side-effect profiles, and minimal drug interactions.',
      normalized_claim: 'Levetiracetam and lamotrigine are first-line for focal epilepsy based on efficacy and tolerability.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'AED Selection', page_or_location: 'Section 3.1' },
    },
    {
      rec_id: 'PACK.AAN.EPIL.2018.REC.04',
      display_id: 'AAN-EPIL-R4',
      statement: 'Valproate is first-line for generalized epilepsy (including absence and myoclonic seizures) but must be avoided in women of childbearing potential due to high teratogenic risk.',
      normalized_claim: 'Valproate is first-line for generalized epilepsy but contraindicated in women of childbearing potential due to teratogenicity.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'AED Selection — Generalized', page_or_location: 'Section 3.2' },
    },
    {
      rec_id: 'PACK.AAN.EPIL.2018.REC.05',
      display_id: 'AAN-EPIL-R5',
      statement: 'Benzodiazepines (IV lorazepam 0.1 mg/kg, max 4 mg per dose) are first-line treatment for status epilepticus and should be administered within 5 minutes of seizure onset.',
      normalized_claim: 'IV lorazepam 0.1 mg/kg (max 4 mg) is first-line for status epilepticus; administer within 5 minutes.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Status Epilepticus — Initial Therapy', page_or_location: 'Section 5.1' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.AAN.EPIL.2018.DC.01',
      display_id: 'AAN-EPIL-DC1',
      name: 'Seizure Classification (ILAE 2017)',
      components: [
        'Focal onset: awareness preserved (simple) or impaired (complex); motor or non-motor features',
        'Generalized onset: motor (tonic-clonic, myoclonic, atonic) or non-motor (absence)',
        'Unknown onset: insufficient information to classify',
        'Focal to bilateral tonic-clonic: focal onset with secondary generalization',
      ],
      interpretation: 'Classification determines AED selection. Focal seizures respond to carbamazepine, lamotrigine, levetiracetam. Generalized respond to valproate, levetiracetam, lamotrigine.',
      normalized_claim: 'Seizure classification (focal vs generalized) drives AED selection; misclassification leads to treatment failure.',
      provenance: { section: 'Classification', page_or_location: 'Section 1.1' },
    },
    {
      criterion_id: 'PACK.AAN.EPIL.2018.DC.02',
      display_id: 'AAN-EPIL-DC2',
      name: 'Status Epilepticus Definition',
      components: [
        'Continuous seizure activity lasting >5 minutes',
        'Two or more discrete seizures without full recovery of consciousness between them',
        'Refractory SE: seizure persists despite adequate doses of initial benzodiazepine and one second-line agent',
        'Super-refractory SE: seizure continues >=24 hours after onset of anesthetic therapy',
      ],
      interpretation: 'Status epilepticus is a neurological emergency. The 5-minute operational definition replaces the historical 30-minute threshold to prompt earlier treatment.',
      normalized_claim: 'Status epilepticus = seizure >5 min or >=2 seizures without recovery; refractory SE = failure of benzo + second-line agent.',
      provenance: { section: 'Status Epilepticus — Definition', page_or_location: 'Section 5.0' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.AAN.EPIL.2018.T.01',
      display_id: 'AAN-EPIL-T1',
      parameter: 'Seizure duration defining status epilepticus',
      value: '5',
      unit: 'minutes',
      clinical_meaning: 'Seizure lasting >5 minutes is unlikely to stop spontaneously and constitutes status epilepticus requiring emergent treatment.',
      normalized_claim: 'Seizure >5 minutes = status epilepticus; requires emergent benzodiazepine therapy.',
      direction: 'above',
      provenance: { section: 'Status Epilepticus', page_or_location: 'Section 5.0' },
    },
    {
      threshold_id: 'PACK.AAN.EPIL.2018.T.02',
      display_id: 'AAN-EPIL-T2',
      parameter: 'Recurrence risk after first unprovoked seizure with abnormal EEG',
      value: '60',
      unit: '%',
      clinical_meaning: 'Patients with a first unprovoked seizure and abnormal EEG have approximately 60% risk of recurrence within 2 years, supporting AED initiation.',
      normalized_claim: 'First seizure with abnormal EEG carries ~60% 2-year recurrence risk; AED therapy is warranted.',
      direction: 'above',
      provenance: { section: 'Risk of Recurrence', page_or_location: 'Section 2.3' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.AAN.EPIL.2018.TX.01',
      display_id: 'AAN-EPIL-TX1',
      action: 'Status epilepticus: First-line benzodiazepine therapy',
      normalized_claim: 'IV lorazepam 0.1 mg/kg (max 4 mg) is first-line for status epilepticus. IM midazolam 10 mg is an alternative when IV access is unavailable.',
      timing: 'Within 5 minutes of seizure onset (0-5 min phase)',
      condition: 'Seizure lasting >5 minutes or recurrent seizures without recovery',
      drug_details: { drug: 'Lorazepam', dose: '0.1 mg/kg (max 4 mg per dose)', route: 'IV push' },
      contraindications: ['Severe respiratory depression without airway management available'],
      escalation: 'If seizure persists after 2 doses of lorazepam, proceed to second-line agent',
      provenance: { section: 'SE Initial Therapy', page_or_location: 'Section 5.1' },
    },
    {
      step_id: 'PACK.AAN.EPIL.2018.TX.02',
      display_id: 'AAN-EPIL-TX2',
      action: 'Status epilepticus: Second-line AED loading',
      normalized_claim: 'Fosphenytoin 20 mg PE/kg IV or levetiracetam 60 mg/kg IV (max 4500 mg) as second-line agents for benzodiazepine-refractory status epilepticus.',
      timing: '5-20 minutes after seizure onset if benzodiazepines fail',
      condition: 'Seizure persists after adequate benzodiazepine dosing',
      drug_details: { drug: 'Fosphenytoin', dose: '20 mg PE/kg', route: 'IV infusion' },
      contraindications: ['Phenytoin: heart block, sinus bradycardia'],
      escalation: 'If seizure continues, proceed to continuous infusion (third-line)',
      provenance: { section: 'SE Urgent Control', page_or_location: 'Section 5.2' },
    },
    {
      step_id: 'PACK.AAN.EPIL.2018.TX.03',
      display_id: 'AAN-EPIL-TX3',
      action: 'Status epilepticus: Third-line continuous infusion',
      normalized_claim: 'Refractory SE requires continuous IV infusion of midazolam, propofol, or pentobarbital with continuous EEG monitoring targeting burst suppression.',
      timing: 'When seizure persists despite benzodiazepine + second-line AED (>20-30 min)',
      condition: 'Refractory status epilepticus — failure of first- and second-line agents',
      drug_details: { drug: 'Midazolam', dose: '0.2 mg/kg bolus then 0.05-2 mg/kg/hr infusion', route: 'IV continuous' },
      escalation: 'Super-refractory SE: consider ketamine, additional anesthetic agents',
      provenance: { section: 'SE Refractory', page_or_location: 'Section 5.3' },
    },
    {
      step_id: 'PACK.AAN.EPIL.2018.TX.04',
      display_id: 'AAN-EPIL-TX4',
      action: 'AED initiation for new-onset focal epilepsy',
      normalized_claim: 'Levetiracetam or lamotrigine first-line for focal epilepsy. Carbamazepine and oxcarbazepine are alternatives. Avoid valproate in women of childbearing potential.',
      condition: 'Confirmed focal epilepsy requiring chronic AED therapy',
      drug_details: { drug: 'Levetiracetam', dose: '500 mg BID, titrate to 1000-1500 mg BID', route: 'PO' },
      contraindications: ['Levetiracetam: significant psychiatric comorbidity (behavioral side effects)'],
      provenance: { section: 'AED Selection', page_or_location: 'Section 3.1' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.AAN.EPIL.2018.RF.01',
      display_id: 'AAN-EPIL-RF1',
      finding: 'New-onset seizure with focal neurological deficit, papilledema, or fever',
      implication: 'Suggests structural lesion (mass, abscess), elevated ICP, or CNS infection rather than idiopathic epilepsy.',
      action: 'Emergent CT head, consider LP if meningitis/encephalitis suspected. Do not delay neuroimaging.',
      urgency: 'immediate',
      provenance: { section: 'First Seizure Red Flags', page_or_location: 'Section 2.4' },
    },
    {
      flag_id: 'PACK.AAN.EPIL.2018.RF.02',
      display_id: 'AAN-EPIL-RF2',
      finding: 'Seizure in pregnancy on valproate',
      implication: 'Valproate carries highest teratogenic risk of all AEDs: neural tube defects (1-2%), decreased IQ, autism spectrum disorder.',
      action: 'Urgent neurology consultation. Switch to safer AED (levetiracetam, lamotrigine) with appropriate cross-titration. Ensure high-dose folic acid (4 mg/day).',
      urgency: 'urgent',
      provenance: { section: 'AED Teratogenicity', page_or_location: 'Section 4.1' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.AAN.EPIL.2018.SEV.01',
      display_id: 'AAN-EPIL-SEV1',
      level: 'Convulsive status epilepticus',
      criteria: [
        'Continuous generalized tonic-clonic seizure >5 minutes',
        'Two or more seizures without return to baseline consciousness',
        'Ongoing rhythmic jerking with impaired awareness',
      ],
      management_implications:
        'Neurological emergency with mortality of 10-20%. Requires immediate benzodiazepine (lorazepam 0.1 mg/kg IV), escalation to fosphenytoin/levetiracetam if refractory, and ICU admission. Continuous EEG monitoring mandatory if seizure does not terminate after second-line agent.',
      provenance: { section: 'SE Severity', page_or_location: 'Section 5.0' },
    },
    {
      severity_id: 'PACK.AAN.EPIL.2018.SEV.02',
      display_id: 'AAN-EPIL-SEV2',
      level: 'Refractory status epilepticus',
      criteria: [
        'Seizure persists despite adequate doses of initial benzodiazepine',
        'Failure of at least one second-line agent (fosphenytoin, levetiracetam, or valproate)',
        'Typically >30-60 minutes of ongoing seizure activity',
      ],
      management_implications:
        'Requires ICU admission, intubation, and continuous IV anesthetic infusion (midazolam, propofol, or pentobarbital). Continuous EEG monitoring targeting burst suppression. Mortality 20-40%. Search for underlying etiology (infection, metabolic, structural).',
      provenance: { section: 'SE Refractory', page_or_location: 'Section 5.3' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 neurology pack for epilepsy and status epilepticus. Covers seizure classification, first-seizure workup, AED selection, and SE stepwise management.',

  all_item_ids: [
    'PACK.AAN.EPIL.2018.REC.01', 'PACK.AAN.EPIL.2018.REC.02', 'PACK.AAN.EPIL.2018.REC.03',
    'PACK.AAN.EPIL.2018.REC.04', 'PACK.AAN.EPIL.2018.REC.05',
    'PACK.AAN.EPIL.2018.DC.01', 'PACK.AAN.EPIL.2018.DC.02',
    'PACK.AAN.EPIL.2018.T.01', 'PACK.AAN.EPIL.2018.T.02',
    'PACK.AAN.EPIL.2018.TX.01', 'PACK.AAN.EPIL.2018.TX.02', 'PACK.AAN.EPIL.2018.TX.03', 'PACK.AAN.EPIL.2018.TX.04',
    'PACK.AAN.EPIL.2018.RF.01', 'PACK.AAN.EPIL.2018.RF.02',
    'PACK.AAN.EPIL.2018.SEV.01', 'PACK.AAN.EPIL.2018.SEV.02',
  ],
  all_display_ids: [
    'AAN-EPIL-R1', 'AAN-EPIL-R2', 'AAN-EPIL-R3', 'AAN-EPIL-R4', 'AAN-EPIL-R5',
    'AAN-EPIL-DC1', 'AAN-EPIL-DC2',
    'AAN-EPIL-T1', 'AAN-EPIL-T2',
    'AAN-EPIL-TX1', 'AAN-EPIL-TX2', 'AAN-EPIL-TX3', 'AAN-EPIL-TX4',
    'AAN-EPIL-RF1', 'AAN-EPIL-RF2',
    'AAN-EPIL-SEV1', 'AAN-EPIL-SEV2',
  ],
};
