import type { SourcePack } from './types';

export const PACK_AAN_HA_2021: SourcePack = {
  source_pack_id: 'PACK.AAN.HA.2021',
  source_name: 'AHS/AAN 2021 Consensus Statement on Migraine Prevention & Acute Treatment',
  source_registry_id: 'REG.AAN.HA',
  canonical_url: 'https://doi.org/10.1111/head.14153',
  publication_year: 2021,
  guideline_body: 'AHS/AAN',

  topic_tags: ['Headache', 'Migraine', 'Tension Headache', 'Cluster Headache', 'SAH', 'Neurology'],
  allowed_decision_scopes: [
    'migraine diagnosis (ICHD-3)',
    'acute migraine treatment',
    'migraine preventive therapy',
    'medication overuse headache',
    'thunderclap headache workup',
    'headache red flags (SNOOP)',
    'CGRP monoclonal antibody selection',
    'triptan selection and contraindications',
  ],
  excluded_decision_scopes: [
    'trigeminal neuralgia management',
    'post-traumatic headache',
    'idiopathic intracranial hypertension management',
    'pediatric migraine',
    'Botox injection technique',
  ],

  recommendations: [
    {
      rec_id: 'PACK.AAN.HA.2021.REC.01',
      display_id: 'AAN-HA-R1',
      statement: 'Triptans are first-line for acute treatment of moderate-to-severe migraine attacks. Sumatriptan 6 mg SC has the fastest onset; oral triptans are preferred for mild-moderate attacks.',
      normalized_claim: 'Triptans are first-line acute treatment for moderate-severe migraine; sumatriptan SC for fastest onset.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Acute Treatment', page_or_location: 'Section 3.1' },
    },
    {
      rec_id: 'PACK.AAN.HA.2021.REC.02',
      display_id: 'AAN-HA-R2',
      statement: 'Preventive therapy should be offered to patients with >=4 migraine days per month, significant disability despite acute treatment, contraindication to or failure of acute therapies, or medication overuse.',
      normalized_claim: 'Migraine preventive therapy indicated when >=4 attacks/month, significant disability, acute treatment failure, or medication overuse.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Prevention Indications', page_or_location: 'Section 4.1' },
    },
    {
      rec_id: 'PACK.AAN.HA.2021.REC.03',
      display_id: 'AAN-HA-R3',
      statement: 'First-line oral preventive agents include beta-blockers (propranolol, metoprolol), topiramate, and valproate (Level A evidence). Amitriptyline and venlafaxine are also effective (Level B).',
      normalized_claim: 'First-line migraine prophylaxis: propranolol, topiramate, or valproate (Level A). Amitriptyline and venlafaxine are second-line (Level B).',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Preventive Medications', page_or_location: 'Section 4.2' },
    },
    {
      rec_id: 'PACK.AAN.HA.2021.REC.04',
      display_id: 'AAN-HA-R4',
      statement: 'CGRP monoclonal antibodies (erenumab, fremanezumab, galcanezumab) are effective for episodic and chronic migraine prevention and should be considered when oral preventives fail or are contraindicated.',
      normalized_claim: 'CGRP mAbs (erenumab, fremanezumab, galcanezumab) are effective preventives; use when oral agents fail or are contraindicated.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'CGRP Antibodies', page_or_location: 'Section 4.4' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.AAN.HA.2021.DC.01',
      display_id: 'AAN-HA-DC1',
      name: 'Migraine Without Aura (ICHD-3)',
      components: [
        '>=5 attacks fulfilling criteria',
        'Headache duration 4-72 hours (untreated)',
        'At least 2 of: unilateral, pulsating, moderate-severe intensity, aggravated by routine physical activity',
        'At least 1 of: nausea/vomiting, photophobia AND phonophobia',
        'Not better accounted for by another diagnosis',
      ],
      interpretation: 'ICHD-3 criteria are the gold standard for migraine diagnosis. All 5 components must be met. Duration <4h or >72h should prompt alternative diagnoses.',
      normalized_claim: 'Migraine without aura (ICHD-3): >=5 attacks, 4-72h, >=2 headache features, >=1 associated symptom, no better diagnosis.',
      provenance: { section: 'Diagnosis', page_or_location: 'Section 1.1' },
    },
    {
      criterion_id: 'PACK.AAN.HA.2021.DC.02',
      display_id: 'AAN-HA-DC2',
      name: 'Medication Overuse Headache (MOH)',
      components: [
        'Headache >=15 days/month in a patient with a pre-existing headache disorder',
        'Regular overuse of acute headache medication for >3 months',
        'Triptans, ergots, opioids, or combination analgesics >=10 days/month',
        'Simple analgesics (NSAIDs, acetaminophen) >=15 days/month',
        'Not better accounted for by another diagnosis',
      ],
      interpretation: 'MOH is the third most common headache disorder. Treatment requires withdrawal of the overused medication with bridging therapy, plus initiation of preventive therapy.',
      normalized_claim: 'MOH: headache >=15 days/month + acute medication overuse >3 months. Treatment = withdrawal + preventive initiation.',
      provenance: { section: 'MOH Criteria', page_or_location: 'Section 5.1' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.AAN.HA.2021.T.01',
      display_id: 'AAN-HA-T1',
      parameter: 'Migraine days per month threshold for preventive therapy',
      value: '4',
      unit: 'days/month',
      clinical_meaning: 'Patients with >=4 migraine days per month benefit from preventive therapy in addition to acute treatment.',
      normalized_claim: '>=4 migraine days/month is the threshold for initiating preventive therapy.',
      direction: 'above',
      provenance: { section: 'Prevention Indications', page_or_location: 'Section 4.1' },
    },
    {
      threshold_id: 'PACK.AAN.HA.2021.T.02',
      display_id: 'AAN-HA-T2',
      parameter: 'Headache days per month defining chronic migraine',
      value: '15',
      unit: 'days/month',
      clinical_meaning: 'Chronic migraine = headache >=15 days/month for >=3 months, with migraine features on >=8 days. Qualifies for onabotulinumtoxinA and CGRP mAbs.',
      normalized_claim: 'Chronic migraine = >=15 headache days/month for >=3 months with migraine features on >=8 days.',
      direction: 'above',
      provenance: { section: 'Chronic Migraine Definition', page_or_location: 'Section 1.3' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.AAN.HA.2021.TX.01',
      display_id: 'AAN-HA-TX1',
      action: 'Acute migraine: triptan therapy',
      normalized_claim: 'Oral triptans (sumatriptan 50-100 mg) are first-line for moderate-severe acute migraine. Take early in attack. Contraindicated in uncontrolled HTN, CAD, stroke history.',
      timing: 'At onset of migraine or when pain is still mild',
      condition: 'Moderate-to-severe migraine attack',
      drug_details: { drug: 'Sumatriptan', dose: '50-100 mg', route: 'PO' },
      contraindications: ['Coronary artery disease', 'Uncontrolled hypertension', 'History of stroke or TIA', 'Hemiplegic or basilar migraine', 'Concurrent MAOI or ergotamine use'],
      provenance: { section: 'Acute Treatment', page_or_location: 'Section 3.1' },
    },
    {
      step_id: 'PACK.AAN.HA.2021.TX.02',
      display_id: 'AAN-HA-TX2',
      action: 'Acute migraine: NSAID therapy',
      normalized_claim: 'NSAIDs (ibuprofen 400-600 mg, naproxen 500 mg) are first-line for mild-moderate migraine and can be combined with triptans for severe attacks.',
      timing: 'At onset of migraine',
      condition: 'Mild-to-moderate migraine attack, or as adjunct to triptans',
      drug_details: { drug: 'Ibuprofen', dose: '400-600 mg', route: 'PO' },
      contraindications: ['Active peptic ulcer disease', 'Renal insufficiency', 'Aspirin-exacerbated respiratory disease'],
      provenance: { section: 'Acute Treatment', page_or_location: 'Section 3.2' },
    },
    {
      step_id: 'PACK.AAN.HA.2021.TX.03',
      display_id: 'AAN-HA-TX3',
      action: 'Preventive therapy: oral beta-blocker or topiramate',
      normalized_claim: 'Propranolol 80-240 mg/day or topiramate 50-100 mg/day are first-line oral migraine preventives. Assess efficacy after 2-3 months at target dose.',
      condition: '>=4 migraine days/month or significant migraine-related disability',
      drug_details: { drug: 'Propranolol', dose: '80-240 mg/day', route: 'PO' },
      contraindications: ['Propranolol: asthma, heart block, decompensated HF', 'Topiramate: nephrolithiasis, pregnancy (teratogenic)'],
      escalation: 'If inadequate response after 2-3 months at target dose, switch to alternative class or consider CGRP mAb',
      provenance: { section: 'Preventive Medications', page_or_location: 'Section 4.2' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.AAN.HA.2021.RF.01',
      display_id: 'AAN-HA-RF1',
      finding: 'Thunderclap headache: sudden-onset, severe headache reaching maximal intensity within seconds to 1 minute',
      implication: 'Subarachnoid hemorrhage (SAH) until proven otherwise. Also consider cerebral venous sinus thrombosis, cervical artery dissection, pituitary apoplexy, RCVS.',
      action: 'Non-contrast CT head immediately. If CT negative and <6 hours, high sensitivity. If CT negative and >=6 hours, perform LP for xanthochromia. CTA/MRA for vascular etiology.',
      urgency: 'immediate',
      provenance: { section: 'Red Flags', page_or_location: 'Section 2.1' },
    },
    {
      flag_id: 'PACK.AAN.HA.2021.RF.02',
      display_id: 'AAN-HA-RF2',
      finding: 'SNOOP red flags: Systemic symptoms (fever, weight loss, cancer, HIV), Neurological deficits, Onset sudden (thunderclap), Older age (>50 new-onset), Progressive or positional headache',
      implication: 'Any SNOOP criterion warrants further investigation to exclude secondary headache: malignancy, infection, vascular event, elevated ICP.',
      action: 'Neuroimaging (MRI preferred for most; CT for acute thunderclap). Targeted workup based on specific red flag (e.g., ESR/CRP for temporal arteritis if >50).',
      urgency: 'urgent',
      provenance: { section: 'Secondary Headache Evaluation', page_or_location: 'Section 2.2' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.AAN.HA.2021.SEV.01',
      display_id: 'AAN-HA-SEV1',
      level: 'Status migrainosus',
      criteria: [
        'Debilitating migraine lasting >72 hours continuously',
        'Brief pain-free periods may occur with sleep or medication but headache recurs',
        'Not attributable to medication overuse or another disorder',
      ],
      management_implications:
        'Requires urgent treatment. IV fluids, IV ketorolac 30 mg, IV metoclopramide 10 mg, or IV prochlorperazine 10 mg. Consider IV dexamethasone 4-8 mg to prevent recurrence. May require ED evaluation to exclude secondary cause. Avoid opioids.',
      provenance: { section: 'Status Migrainosus', page_or_location: 'Section 3.5' },
    },
    {
      severity_id: 'PACK.AAN.HA.2021.SEV.02',
      display_id: 'AAN-HA-SEV2',
      level: 'Chronic migraine',
      criteria: [
        'Headache on >=15 days/month for >=3 consecutive months',
        'Migraine features on >=8 of those days',
        'Not better explained by another headache diagnosis',
        'May coexist with medication overuse headache',
      ],
      management_implications:
        'Preventive therapy is mandatory. First-line: topiramate, propranolol, or amitriptyline. If oral preventives fail, consider CGRP mAbs or onabotulinumtoxinA. Screen for and treat comorbid medication overuse headache. Assess for psychiatric comorbidities (depression, anxiety).',
      provenance: { section: 'Chronic Migraine', page_or_location: 'Section 1.3' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 neurology pack for headache/migraine. Covers ICHD-3 diagnosis, acute treatment, preventive therapy, SNOOP red flags, and medication overuse headache.',

  all_item_ids: [
    'PACK.AAN.HA.2021.REC.01', 'PACK.AAN.HA.2021.REC.02', 'PACK.AAN.HA.2021.REC.03',
    'PACK.AAN.HA.2021.REC.04',
    'PACK.AAN.HA.2021.DC.01', 'PACK.AAN.HA.2021.DC.02',
    'PACK.AAN.HA.2021.T.01', 'PACK.AAN.HA.2021.T.02',
    'PACK.AAN.HA.2021.TX.01', 'PACK.AAN.HA.2021.TX.02', 'PACK.AAN.HA.2021.TX.03',
    'PACK.AAN.HA.2021.RF.01', 'PACK.AAN.HA.2021.RF.02',
    'PACK.AAN.HA.2021.SEV.01', 'PACK.AAN.HA.2021.SEV.02',
  ],
  all_display_ids: [
    'AAN-HA-R1', 'AAN-HA-R2', 'AAN-HA-R3', 'AAN-HA-R4',
    'AAN-HA-DC1', 'AAN-HA-DC2',
    'AAN-HA-T1', 'AAN-HA-T2',
    'AAN-HA-TX1', 'AAN-HA-TX2', 'AAN-HA-TX3',
    'AAN-HA-RF1', 'AAN-HA-RF2',
    'AAN-HA-SEV1', 'AAN-HA-SEV2',
  ],
};
