// ─── DRAFT Source Pack: Bell Palsy ───
// Generated by DI/IC Accelerator on 2026-04-17
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (14 total):
//   DI.031.169, DI.058.036, DI.058.037, DI.058.038, DI.058.039, DI.058.040, DI.183.078, EH.004.040, EH.PEDS.010.008, IC.058.057, IC.058.058, IC.058.059, IC.058.060, IC.058.061
//
// Evidence classification summary:
//   Recommendations: 8 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 2 items → pack
//   Thresholds: 2 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 1 items → pack
//   Skipped: 1 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_AAN_BP_2012: SourcePack = {
  "source_pack_id": "PACK.AAN.BP.2012",
  "source_name": "American Academy of Neurology Practice Parameter: Steroids, acyclovir, and surgery for Bell's palsy",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2012,
  "guideline_body": "American Academy of Neurology",
  "topic_tags": [
    "neurology",
    "cranial_nerve_palsy",
    "facial_paralysis",
    "bells_palsy",
    "peripheral_neuropathy"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "treatment",
    "differential_diagnosis",
    "prognosis"
  ],
  "excluded_decision_scopes": [
    "surgical_management",
    "pediatric_specific_care"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.AAN.BP.2012.REC.01",
      "display_id": "AAN-BP-R1",
      "statement": "Bell's palsy should be diagnosed clinically when patient presents with inability to close mouth or eye on one side",
      "normalized_claim": "Bell's palsy presents with unilateral facial weakness affecting mouth closure and eye closure",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "provenance": {
        "section": "Clinical presentation",
        "quote_snippet": "Can't close mouth / can't close eye on one side"
      }
    },
    {
      "rec_id": "PACK.AAN.BP.2012.REC.02",
      "display_id": "AAN-BP-R2",
      "statement": "Consider Lyme disease, HSV, multiple sclerosis, and sarcoidosis in the differential diagnosis of facial palsy",
      "normalized_claim": "Lyme disease, HSV, MS, and sarcoidosis are important causes of facial palsy to consider",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "provenance": {
        "section": "Differential diagnosis",
        "quote_snippet": "Causes? Lyme disease (Borrelia burgdorferi, Ixodes tick), HSV, MS, Sarcoid"
      }
    },
    {
      "rec_id": "PACK.AAN.BP.2012.REC.03",
      "display_id": "AAN-BP-R3",
      "statement": "Young patients with new bilateral Bell's palsy require investigation for underlying systemic causes",
      "normalized_claim": "Bilateral Bell's palsy in young patients warrants investigation for systemic etiology",
      "strength": "strong",
      "evidence_quality": "moderate",
      "population": "young patients",
      "provenance": {
        "section": "Special populations",
        "quote_snippet": "A young patient with new/bilateral Bell's Palsy"
      }
    },
    {
      "rec_id": "PACK.AAN.BP.2012.REC.04",
      "display_id": "AAN-BP-R4",
      "statement": "Peripheral CN VII palsy results from HSV reactivation causing inflammation, edema, nerve compression, and myelin degeneration",
      "normalized_claim": "Bell's palsy pathophysiology involves HSV reactivation leading to facial nerve inflammation and compression",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "provenance": {
        "section": "Pathophysiology",
        "quote_snippet": "Peripheral CN VII palsy — reactivation of HSV → inflammation, edema, nerve compression, myelin degeneration"
      }
    },
    {
      "rec_id": "PACK.AAN.BP.2012.REC.05",
      "display_id": "AAN-BP-R5",
      "statement": "Upper facial weakness distinguishes peripheral facial palsy from central (UMN) causes which spare the upper face",
      "normalized_claim": "Upper face involvement (eye closure, eyebrow raising weakness) distinguishes peripheral from central facial palsy",
      "strength": "strong",
      "evidence_quality": "high",
      "provenance": {
        "section": "Clinical diagnosis",
        "quote_snippet": "Upper face involvement (weakness closing eye/raising eyebrow) → distinguishes from UMN stroke (which spares upper face)"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.AAN.BP.2012.DC.01",
      "display_id": "AAN-BP-DC1",
      "name": "Bell's Palsy Clinical Diagnosis",
      "components": [
        "Unilateral mouth droop with disappearance of nasolabial fold",
        "Upper face weakness (inability to close eye or raise eyebrow)",
        "Ipsilateral decreased lacrimation",
        "Hyperacusis on affected side",
        "Decreased taste sensation anterior 2/3 of tongue"
      ],
      "interpretation": "Acute unilateral peripheral facial nerve palsy",
      "normalized_claim": "Bell's palsy diagnosis requires unilateral facial weakness affecting both upper and lower face with associated cranial nerve VII branch symptoms",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Unilateral mouth droop + disappearance of nasolabial fold; Ipsilateral decreased lacrimation, hyperacusis, decreased taste anterior 2/3 tongue"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.AAN.BP.2012.T.01",
      "display_id": "AAN-BP-T1",
      "parameter": "Age for doxycycline treatment in Lyme-associated facial palsy",
      "value": "8",
      "unit": "years",
      "clinical_meaning": "Minimum age for doxycycline use in Lyme disease treatment",
      "normalized_claim": "Doxycycline is preferred for Lyme disease in patients 8 years and older; amoxicillin for younger children",
      "direction": "above",
      "provenance": {
        "section": "Treatment protocols",
        "quote_snippet": "Age 8+ -> doxy. <8 -> amoxicillin"
      }
    },
    {
      "threshold_id": "PACK.AAN.BP.2012.T.02",
      "display_id": "AAN-BP-T2",
      "parameter": "Geographic risk area for Lyme disease",
      "value": "Northeast US",
      "clinical_meaning": "Primary endemic region for Lyme disease and associated facial palsy",
      "normalized_claim": "Northeast US represents highest risk geographic area for Lyme disease-associated Bell's palsy",
      "direction": "present",
      "provenance": {
        "section": "Epidemiology",
        "quote_snippet": "Geographic: Northeast US"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.AAN.BP.2012.TX.01",
      "display_id": "AAN-BP-TX1",
      "action": "Initiate corticosteroids as primary treatment",
      "normalized_claim": "Corticosteroids are first-line treatment for Bell's palsy",
      "timing": "As soon as possible after symptom onset",
      "drug_details": {
        "drug": "corticosteroids (prednisone)"
      },
      "provenance": {
        "section": "Treatment recommendations",
        "quote_snippet": "Tx: glucocorticoids + valacyclovir; Steroids"
      }
    },
    {
      "step_id": "PACK.AAN.BP.2012.TX.02",
      "display_id": "AAN-BP-TX2",
      "action": "Add antiviral therapy when HSV etiology suspected",
      "normalized_claim": "Antiviral therapy should be considered in addition to steroids when HSV is suspected cause",
      "condition": "When HSV etiology is suspected",
      "drug_details": {
        "drug": "valacyclovir or acyclovir"
      },
      "provenance": {
        "section": "Treatment recommendations",
        "quote_snippet": "Acyclovir if presumed 2/2 HSV; glucocorticoids + valacyclovir"
      }
    },
    {
      "step_id": "PACK.AAN.BP.2012.TX.03",
      "display_id": "AAN-BP-TX3",
      "action": "Provide eye protection with artificial tears",
      "normalized_claim": "Eye protection with drops is essential supportive care for Bell's palsy",
      "condition": "For all patients with eye closure weakness",
      "drug_details": {
        "drug": "artificial tears/eye drops"
      },
      "provenance": {
        "section": "Supportive care",
        "quote_snippet": "Eye drops for affected eye"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.AAN.BP.2012.RF.01",
      "display_id": "AAN-BP-RF1",
      "finding": "Bilateral facial palsy in young patient",
      "implication": "Suggests systemic cause rather than typical Bell's palsy",
      "action": "Urgent investigation for underlying systemic disease including Lyme disease, sarcoidosis, or other causes",
      "urgency": "urgent",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "A young patient with new/bilateral Bell's Palsy"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.AAN.BP.2012.SEV.01",
      "display_id": "AAN-BP-SEV1",
      "level": "Stage 2 Lyme Disease",
      "criteria": [
        "Bilateral Bell's palsy",
        "Heart block",
        "Disseminated rash",
        "Arthralgias"
      ],
      "management_implications": "Requires IV antibiotic therapy with ceftriaxone or cefotaxime",
      "provenance": {
        "section": "Lyme disease staging",
        "quote_snippet": "Stage 2: Heart block, bilateral Bell's palsy, disseminated rash, arthralgias. Tx: Ceftriaxone/cefotaxime"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-12-28",
  "normalizer_version": 1,
  "normalization_notes": "Generated from board review evidence (Divine Intervention, Inner Circle, Emma Holliday). Key gaps: formal diagnostic criteria from AAN guidelines, specific steroid dosing protocols, timeline for treatment initiation, formal severity grading systems. Lyme disease content integrated as relevant differential. Needs verification against actual AAN practice parameters for Bell's palsy management.",
  "all_item_ids": [
    "PACK.AAN.BP.2012.REC.01",
    "PACK.AAN.BP.2012.REC.02",
    "PACK.AAN.BP.2012.REC.03",
    "PACK.AAN.BP.2012.REC.04",
    "PACK.AAN.BP.2012.REC.05",
    "PACK.AAN.BP.2012.DC.01",
    "PACK.AAN.BP.2012.T.01",
    "PACK.AAN.BP.2012.T.02",
    "PACK.AAN.BP.2012.TX.01",
    "PACK.AAN.BP.2012.TX.02",
    "PACK.AAN.BP.2012.TX.03",
    "PACK.AAN.BP.2012.RF.01",
    "PACK.AAN.BP.2012.SEV.01"
  ],
  "all_display_ids": [
    "AAN-BP-R1",
    "AAN-BP-R2",
    "AAN-BP-R3",
    "AAN-BP-R4",
    "AAN-BP-R5",
    "AAN-BP-DC1",
    "AAN-BP-T1",
    "AAN-BP-T2",
    "AAN-BP-TX1",
    "AAN-BP-TX2",
    "AAN-BP-TX3",
    "AAN-BP-RF1",
    "AAN-BP-SEV1"
  ]
};
