import type { SourcePack } from './types';

export const PACK_AAN_MS_2018: SourcePack = {
  source_pack_id: 'PACK.AAN.MS.2018',
  source_name: 'AAN 2018 Practice Guideline on Disease-Modifying Therapies in Multiple Sclerosis',
  source_registry_id: 'REG.AAN.MS',
  canonical_url: 'https://doi.org/10.1212/WNL.0000000000005347',
  publication_year: 2018,
  guideline_body: 'AAN',

  topic_tags: ['Multiple Sclerosis', 'MS', 'Demyelinating Disease', 'CIS', 'DMT', 'Neurology'],
  allowed_decision_scopes: [
    'MS diagnosis (McDonald criteria)',
    'clinically isolated syndrome evaluation',
    'acute MS relapse management',
    'DMT initiation and selection',
    'JC virus risk stratification with natalizumab',
    'MRI monitoring on DMT',
    'pregnancy planning in MS',
    'progressive MS management',
  ],
  excluded_decision_scopes: [
    'neuromyelitis optica spectrum disorder',
    'MOG antibody disease',
    'acute disseminated encephalomyelitis',
    'MS rehabilitation specifics',
    'spasticity management',
  ],

  recommendations: [
    {
      rec_id: 'PACK.AAN.MS.2018.REC.01',
      display_id: 'AAN-MS-R1',
      statement: 'Clinicians should offer DMT to patients with relapsing forms of MS who have had recent relapses or MRI activity. Early initiation of DMT improves long-term outcomes.',
      normalized_claim: 'DMT should be offered to relapsing MS patients with recent relapses or MRI activity; early treatment improves outcomes.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Starting DMT', page_or_location: 'Recommendation 1' },
    },
    {
      rec_id: 'PACK.AAN.MS.2018.REC.02',
      display_id: 'AAN-MS-R2',
      statement: 'Clinicians should offer DMT to patients with a single clinical demyelinating event (CIS) and >=2 brain lesions characteristic of MS.',
      normalized_claim: 'CIS with >=2 characteristic MRI brain lesions warrants DMT initiation to delay conversion to clinically definite MS.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'Applies to CIS patients meeting partial McDonald criteria',
      provenance: { section: 'CIS Management', page_or_location: 'Recommendation 2' },
    },
    {
      rec_id: 'PACK.AAN.MS.2018.REC.03',
      display_id: 'AAN-MS-R3',
      statement: 'IV methylprednisolone 1g/day for 3-5 days is the standard treatment for acute MS relapses causing functional impairment.',
      normalized_claim: 'Acute MS relapse with functional impairment: treat with IV methylprednisolone 1g/day x 3-5 days.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Relapse Management', page_or_location: 'Section 4.1' },
    },
    {
      rec_id: 'PACK.AAN.MS.2018.REC.04',
      display_id: 'AAN-MS-R4',
      statement: 'Clinicians should assess JC virus antibody status before starting natalizumab and every 6 months during therapy. JCV antibody index >1.5 with prior immunosuppressant use confers highest PML risk.',
      normalized_claim: 'JCV antibody testing required before and every 6 months during natalizumab; index >1.5 with prior immunosuppression = high PML risk.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Natalizumab Safety', page_or_location: 'Recommendation 15' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.AAN.MS.2018.DC.01',
      display_id: 'AAN-MS-DC1',
      name: 'McDonald Criteria for MS Diagnosis (2017 Revision)',
      components: [
        'Dissemination in space (DIS): >=1 T2 lesion in >=2 of 4 CNS regions (periventricular, cortical/juxtacortical, infratentorial, spinal cord)',
        'Dissemination in time (DIT): simultaneous gadolinium-enhancing and non-enhancing lesions, OR new T2/enhancing lesion on follow-up MRI, OR CSF-specific oligoclonal bands',
        'Clinical: >=2 clinical attacks involving different CNS regions can substitute for MRI criteria',
        'CSF oligoclonal bands can substitute for DIT (2017 revision)',
      ],
      interpretation: 'MS diagnosis requires demonstration of dissemination in both space and time, with exclusion of alternative diagnoses. CSF OCBs now accepted as DIT substitute.',
      normalized_claim: 'MS diagnosis requires dissemination in space + time (McDonald 2017); CSF OCBs can substitute for DIT.',
      provenance: { section: 'Diagnosis', page_or_location: 'Section 2.1' },
    },
    {
      criterion_id: 'PACK.AAN.MS.2018.DC.02',
      display_id: 'AAN-MS-DC2',
      name: 'Clinically Isolated Syndrome (CIS)',
      components: [
        'First clinical episode of CNS demyelination (optic neuritis, transverse myelitis, brainstem syndrome)',
        'Objective clinical evidence of a CNS lesion',
        'Does not yet meet full McDonald criteria for MS',
        'No better explanation by another diagnosis',
      ],
      interpretation: 'CIS may be the first presentation of MS. MRI and CSF findings guide risk stratification for conversion to clinically definite MS.',
      normalized_claim: 'CIS = first demyelinating event not yet meeting MS criteria; MRI lesion burden and CSF OCBs predict conversion risk.',
      provenance: { section: 'CIS Definition', page_or_location: 'Section 1.2' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.AAN.MS.2018.T.01',
      display_id: 'AAN-MS-T1',
      parameter: 'JC virus antibody index for PML risk stratification',
      value: '1.5',
      clinical_meaning: 'JCV antibody index >1.5 combined with prior immunosuppressant use and natalizumab duration >24 months places patients in highest PML risk category (~1/90).',
      normalized_claim: 'JCV antibody index >1.5 + prior immunosuppression + >24 months natalizumab = highest PML risk (~1:90).',
      direction: 'above',
      provenance: { section: 'PML Risk', page_or_location: 'Section 6.2' },
    },
    {
      threshold_id: 'PACK.AAN.MS.2018.T.02',
      display_id: 'AAN-MS-T2',
      parameter: 'MRI lesion count for CIS risk stratification',
      value: '2',
      unit: 'T2 lesions',
      clinical_meaning: 'CIS patients with >=2 characteristic brain MRI lesions have >60% risk of developing clinically definite MS within 20 years.',
      normalized_claim: 'CIS with >=2 brain MRI lesions: >60% conversion risk to MS; supports early DMT initiation.',
      direction: 'above',
      provenance: { section: 'CIS Prognosis', page_or_location: 'Section 1.3' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.AAN.MS.2018.TX.01',
      display_id: 'AAN-MS-TX1',
      action: 'Acute relapse: IV high-dose corticosteroids',
      normalized_claim: 'Acute MS relapse causing functional impairment: IV methylprednisolone 1g/day x 3-5 days. Shortens relapse duration but does not alter long-term disability.',
      timing: 'Within days of relapse onset',
      condition: 'Acute MS relapse with new or worsening neurological deficit causing functional impairment',
      drug_details: { drug: 'Methylprednisolone', dose: '1g/day', route: 'IV', duration: '3-5 days' },
      contraindications: ['Active systemic infection', 'Uncontrolled diabetes (relative)'],
      provenance: { section: 'Relapse Treatment', page_or_location: 'Section 4.1' },
    },
    {
      step_id: 'PACK.AAN.MS.2018.TX.02',
      display_id: 'AAN-MS-TX2',
      action: 'DMT initiation: moderate-efficacy platform therapy',
      normalized_claim: 'First-line DMTs include interferon beta, glatiramer acetate, dimethyl fumarate, and teriflunomide. Selection based on efficacy, side-effect profile, route, and patient preference.',
      condition: 'Relapsing MS or CIS with high conversion risk',
      drug_details: { drug: 'Dimethyl fumarate', dose: '240 mg BID', route: 'PO' },
      contraindications: ['Lymphopenia (monitor ALC; hold if <500)'],
      escalation: 'If breakthrough activity on moderate-efficacy DMT, escalate to high-efficacy therapy',
      provenance: { section: 'DMT Selection', page_or_location: 'Recommendation 5' },
    },
    {
      step_id: 'PACK.AAN.MS.2018.TX.03',
      display_id: 'AAN-MS-TX3',
      action: 'DMT escalation: high-efficacy therapy',
      normalized_claim: 'Natalizumab, ocrelizumab, and fingolimod are high-efficacy DMTs for patients with breakthrough disease on platform therapy or highly active MS at onset.',
      condition: 'Breakthrough disease activity on first-line DMT or highly active MS at presentation',
      drug_details: { drug: 'Ocrelizumab', dose: '600 mg IV every 6 months', route: 'IV infusion' },
      contraindications: ['Active hepatitis B (ocrelizumab)', 'JCV Ab+ with high index (natalizumab)'],
      provenance: { section: 'High-Efficacy DMT', page_or_location: 'Recommendation 8' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.AAN.MS.2018.RF.01',
      display_id: 'AAN-MS-RF1',
      finding: 'Progressive cognitive decline, new focal deficits, or atypical MRI changes on natalizumab (non-enhancing progressive lesions)',
      implication: 'Suggests progressive multifocal leukoencephalopathy (PML) — JC virus reactivation with mortality up to 25% and severe disability in survivors.',
      action: 'Immediately discontinue natalizumab. Urgent brain MRI with contrast. Send CSF for JCV PCR. Neurology emergency consultation.',
      urgency: 'immediate',
      provenance: { section: 'PML Surveillance', page_or_location: 'Section 6.3' },
    },
    {
      flag_id: 'PACK.AAN.MS.2018.RF.02',
      display_id: 'AAN-MS-RF2',
      finding: 'Bilateral optic neuritis, longitudinally extensive transverse myelitis (>=3 vertebral segments), or area postrema syndrome',
      implication: 'These presentations are more characteristic of neuromyelitis optica spectrum disorder (NMOSD) than MS. Misdiagnosis as MS and treatment with certain DMTs (fingolimod, natalizumab) can worsen NMOSD.',
      action: 'Test for aquaporin-4 (AQP4) and MOG antibodies before starting MS-specific DMT. Treat with IV steroids acutely.',
      urgency: 'urgent',
      provenance: { section: 'Differential Diagnosis', page_or_location: 'Section 2.3' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.AAN.MS.2018.SEV.01',
      display_id: 'AAN-MS-SEV1',
      level: 'Highly active relapsing MS',
      criteria: [
        '>=2 relapses in the past year with disability accumulation',
        'Multiple gadolinium-enhancing lesions on MRI',
        'Incomplete recovery from relapses',
        'Rapidly accumulating disability (EDSS increase >=1 point sustained 6 months)',
      ],
      management_implications:
        'Consider initiating high-efficacy DMT (natalizumab, ocrelizumab, alemtuzumab) rather than starting with moderate-efficacy platform therapy. More frequent MRI monitoring (every 3-6 months initially). Aggressive relapse treatment.',
      provenance: { section: 'Disease Activity Assessment', page_or_location: 'Section 3.3' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 neurology pack for MS. Covers McDonald criteria diagnosis, relapse management, DMT selection/escalation, and PML risk stratification.',

  all_item_ids: [
    'PACK.AAN.MS.2018.REC.01', 'PACK.AAN.MS.2018.REC.02', 'PACK.AAN.MS.2018.REC.03',
    'PACK.AAN.MS.2018.REC.04',
    'PACK.AAN.MS.2018.DC.01', 'PACK.AAN.MS.2018.DC.02',
    'PACK.AAN.MS.2018.T.01', 'PACK.AAN.MS.2018.T.02',
    'PACK.AAN.MS.2018.TX.01', 'PACK.AAN.MS.2018.TX.02', 'PACK.AAN.MS.2018.TX.03',
    'PACK.AAN.MS.2018.RF.01', 'PACK.AAN.MS.2018.RF.02',
    'PACK.AAN.MS.2018.SEV.01',
  ],
  all_display_ids: [
    'AAN-MS-R1', 'AAN-MS-R2', 'AAN-MS-R3', 'AAN-MS-R4',
    'AAN-MS-DC1', 'AAN-MS-DC2',
    'AAN-MS-T1', 'AAN-MS-T2',
    'AAN-MS-TX1', 'AAN-MS-TX2', 'AAN-MS-TX3',
    'AAN-MS-RF1', 'AAN-MS-RF2',
    'AAN-MS-SEV1',
  ],
};
