import type { SourcePack } from './types';

export const PACK_AAN_NM_2016: SourcePack = {
  source_pack_id: 'PACK.AAN.NM.2016',
  source_name: 'AAN 2012 Guideline on GBS & 2016 International Consensus on MG Management',
  source_registry_id: 'REG.AAN.NM',
  canonical_url: 'https://doi.org/10.1212/WNL.0000000000002790',
  publication_year: 2016,
  guideline_body: 'AAN',

  topic_tags: ['Guillain-Barre Syndrome', 'GBS', 'Myasthenia Gravis', 'MG', 'Myasthenic Crisis', 'Neuromuscular', 'Neurology'],
  allowed_decision_scopes: [
    'GBS diagnosis and treatment',
    'GBS respiratory monitoring',
    'myasthenia gravis diagnosis',
    'MG pharmacotherapy',
    'myasthenic crisis management',
    'thymectomy indications',
    'cholinergic vs myasthenic crisis differentiation',
    'neuromuscular junction disorder evaluation',
  ],
  excluded_decision_scopes: [
    'chronic inflammatory demyelinating polyneuropathy (CIDP)',
    'Lambert-Eaton myasthenic syndrome',
    'botulism management',
    'amyotrophic lateral sclerosis',
    'muscular dystrophies',
  ],

  recommendations: [
    {
      rec_id: 'PACK.AAN.NM.2016.REC.01',
      display_id: 'AAN-NM-R1',
      statement: 'IVIG (0.4 g/kg/day x 5 days) or plasmapheresis (5 exchanges over 1-2 weeks) should be offered to patients with GBS who are unable to walk independently. Both are equally effective.',
      normalized_claim: 'GBS treatment: IVIG 0.4 g/kg/day x 5 days OR plasmapheresis (5 exchanges). Equally effective. Indicated when patient cannot walk independently.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'GBS Treatment', page_or_location: 'Section 3.1' },
    },
    {
      rec_id: 'PACK.AAN.NM.2016.REC.02',
      display_id: 'AAN-NM-R2',
      statement: 'Corticosteroids are NOT effective in GBS and should not be used. Unlike other autoimmune conditions, steroids do not improve outcomes and may prolong recovery.',
      normalized_claim: 'Corticosteroids are NOT effective in GBS; do not use. IVIG or plasmapheresis are the only proven immunomodulatory treatments.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'GBS Treatment', page_or_location: 'Section 3.2' },
    },
    {
      rec_id: 'PACK.AAN.NM.2016.REC.03',
      display_id: 'AAN-NM-R3',
      statement: 'Pyridostigmine is first-line symptomatic therapy for myasthenia gravis. Dose is titrated to symptom control. It provides symptomatic relief but does not alter disease course.',
      normalized_claim: 'Pyridostigmine is first-line symptomatic MG therapy; titrate to symptom control. Does not modify disease course — immunosuppression needed for long-term control.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'MG Symptomatic Treatment', page_or_location: 'Section 5.1' },
    },
    {
      rec_id: 'PACK.AAN.NM.2016.REC.04',
      display_id: 'AAN-NM-R4',
      statement: 'Thymectomy should be considered in all patients with generalized MG aged 18-65 with anti-AChR antibodies, regardless of thymoma presence. MGTX trial showed improved outcomes at 3 years.',
      normalized_claim: 'Thymectomy recommended for generalized AChR-positive MG (age 18-65) to improve outcomes; benefit shown in MGTX trial regardless of thymoma.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'MGTX trial: thymectomy + prednisone vs prednisone alone',
      provenance: { section: 'Thymectomy', page_or_location: 'Section 5.4' },
    },
    {
      rec_id: 'PACK.AAN.NM.2016.REC.05',
      display_id: 'AAN-NM-R5',
      statement: 'Serial monitoring of forced vital capacity (FVC) and negative inspiratory force (NIF) is essential in GBS and myasthenic crisis. Intubate when FVC <20 mL/kg, NIF weaker than -30 cmH2O, or vital capacity declining >30% from baseline.',
      normalized_claim: 'Monitor FVC and NIF serially in GBS and MG crisis. Intubate if FVC <20 mL/kg or NIF weaker than -30 cmH2O (20/30/40 rule).',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Respiratory Monitoring', page_or_location: 'Section 3.3' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.AAN.NM.2016.DC.01',
      display_id: 'AAN-NM-DC1',
      name: 'Guillain-Barre Syndrome Diagnostic Criteria',
      components: [
        'Progressive bilateral and relatively symmetric weakness of the limbs',
        'Hyporeflexia or areflexia',
        'Progression over days to 4 weeks (monophasic)',
        'CSF: albuminocytologic dissociation (elevated protein with normal cell count) — may be normal in first week',
        'Nerve conduction studies: demyelinating pattern (prolonged distal latencies, conduction block, temporal dispersion) or axonal pattern',
        'Preceding infection (Campylobacter jejuni, CMV, EBV, Mycoplasma) in 60-70% of cases',
      ],
      interpretation: 'GBS is a clinical diagnosis supported by CSF and electrodiagnostic findings. CSF protein may be normal in the first week. NCS pattern distinguishes AIDP (demyelinating) from AMAN/AMSAN (axonal).',
      normalized_claim: 'GBS: ascending weakness + areflexia + CSF albuminocytologic dissociation + demyelinating NCS. Often post-infectious (Campylobacter most common).',
      provenance: { section: 'GBS Diagnosis', page_or_location: 'Section 2.1' },
    },
    {
      criterion_id: 'PACK.AAN.NM.2016.DC.02',
      display_id: 'AAN-NM-DC2',
      name: 'Myasthenia Gravis Diagnostic Criteria',
      components: [
        'Fatigable weakness: worsens with repeated use, improves with rest',
        'Distribution: ocular (ptosis, diplopia), bulbar (dysarthria, dysphagia), or generalized',
        'Anti-AChR antibodies positive in 85% of generalized MG and 50% of ocular MG',
        'Anti-MuSK antibodies in ~40% of AChR-seronegative generalized MG',
        'Electrodiagnostic: decremental response on repetitive nerve stimulation (RNS) at 2-3 Hz; increased jitter on single-fiber EMG',
        'Edrophonium (Tensilon) test: transient improvement of weakness with IV edrophonium (high sensitivity but limited availability)',
      ],
      interpretation: 'MG is diagnosed by fatigable weakness pattern + serological (AChR/MuSK Ab) and/or electrodiagnostic confirmation. Single-fiber EMG is the most sensitive test.',
      normalized_claim: 'MG: fatigable weakness + anti-AChR Ab (85%) or anti-MuSK Ab. Confirm with RNS (decremental response) or single-fiber EMG (most sensitive).',
      provenance: { section: 'MG Diagnosis', page_or_location: 'Section 4.1' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.AAN.NM.2016.T.01',
      display_id: 'AAN-NM-T1',
      parameter: 'Forced vital capacity (FVC) for intubation in neuromuscular respiratory failure',
      value: '20',
      unit: 'mL/kg',
      clinical_meaning: 'FVC <20 mL/kg indicates impending respiratory failure in GBS or myasthenic crisis and is an indication for elective intubation.',
      normalized_claim: 'FVC <20 mL/kg = intubation threshold in GBS/MG crisis. Part of the 20/30/40 rule for neuromuscular respiratory failure.',
      direction: 'below',
      provenance: { section: 'Respiratory Monitoring', page_or_location: 'Section 3.3' },
    },
    {
      threshold_id: 'PACK.AAN.NM.2016.T.02',
      display_id: 'AAN-NM-T2',
      parameter: 'Negative inspiratory force (NIF) for intubation',
      value: '-30',
      unit: 'cmH2O',
      clinical_meaning: 'NIF weaker than -30 cmH2O (i.e., closer to zero, such as -20 or -15) indicates inability to generate adequate inspiratory pressure and warrants intubation.',
      normalized_claim: 'NIF weaker than -30 cmH2O = intubation threshold. Combined with FVC <20 mL/kg, guides timing of elective intubation.',
      direction: 'above',
      provenance: { section: 'Respiratory Monitoring', page_or_location: 'Section 3.3' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.AAN.NM.2016.TX.01',
      display_id: 'AAN-NM-TX1',
      action: 'GBS: Immunomodulatory therapy',
      normalized_claim: 'GBS: IVIG 0.4 g/kg/day x 5 days (total 2 g/kg) OR plasmapheresis (5 exchanges). Start within 2-4 weeks of symptom onset. Do NOT use corticosteroids.',
      timing: 'Within 2-4 weeks of symptom onset for maximum benefit',
      condition: 'GBS with inability to walk independently or progressive weakness',
      drug_details: { drug: 'IVIG', dose: '0.4 g/kg/day x 5 days (total 2 g/kg)', route: 'IV infusion' },
      contraindications: ['IVIG: IgA deficiency (anaphylaxis risk)', 'IVIG: recent thromboembolic event'],
      provenance: { section: 'GBS Treatment', page_or_location: 'Section 3.1' },
    },
    {
      step_id: 'PACK.AAN.NM.2016.TX.02',
      display_id: 'AAN-NM-TX2',
      action: 'MG: Symptomatic treatment with pyridostigmine',
      normalized_claim: 'Pyridostigmine 60 mg PO q4-6h, titrate to symptom control (max ~120 mg q4h). First-line symptomatic therapy for MG.',
      condition: 'Confirmed myasthenia gravis — all subtypes',
      drug_details: { drug: 'Pyridostigmine', dose: '60 mg q4-6h, titrate to effect', route: 'PO' },
      contraindications: ['Mechanical bowel or urinary obstruction'],
      escalation: 'Add immunosuppression (prednisone, azathioprine, mycophenolate) if symptomatic therapy insufficient',
      provenance: { section: 'MG Treatment', page_or_location: 'Section 5.1' },
    },
    {
      step_id: 'PACK.AAN.NM.2016.TX.03',
      display_id: 'AAN-NM-TX3',
      action: 'MG: Long-term immunosuppression',
      normalized_claim: 'Prednisone is first-line immunosuppressive for MG; start low and increase gradually to avoid exacerbation. Steroid-sparing agents: azathioprine, mycophenolate mofetil.',
      condition: 'MG inadequately controlled with pyridostigmine alone',
      drug_details: { drug: 'Prednisone', dose: 'Start 10-20 mg/day, increase by 5-10 mg every 3-5 days to target', route: 'PO' },
      contraindications: ['Active untreated infection'],
      escalation: 'Refractory MG: rituximab (especially MuSK-positive MG), eculizumab, or chronic IVIG/PLEX',
      provenance: { section: 'MG Immunosuppression', page_or_location: 'Section 5.3' },
    },
    {
      step_id: 'PACK.AAN.NM.2016.TX.04',
      display_id: 'AAN-NM-TX4',
      action: 'Myasthenic crisis: Emergency management',
      normalized_claim: 'Myasthenic crisis: intubate for airway protection (FVC <20 mL/kg), hold cholinesterase inhibitors (to avoid cholinergic crisis confusion), start IVIG or PLEX.',
      timing: 'Emergent — within hours',
      condition: 'Myasthenic crisis with respiratory failure or impending respiratory failure',
      drug_details: { drug: 'IVIG', dose: '0.4 g/kg/day x 5 days', route: 'IV infusion' },
      contraindications: ['Do NOT give cholinesterase inhibitors during crisis (masks monitoring, risk of cholinergic crisis)'],
      provenance: { section: 'Myasthenic Crisis', page_or_location: 'Section 6.1' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.AAN.NM.2016.RF.01',
      display_id: 'AAN-NM-RF1',
      finding: 'Rapidly ascending weakness with areflexia and declining FVC in days',
      implication: 'GBS with impending respiratory failure. 25-30% of GBS patients require mechanical ventilation. Respiratory arrest can occur without warning if FVC is not monitored serially.',
      action: 'ICU admission. Monitor FVC and NIF every 4-6 hours. Intubate electively if FVC <20 mL/kg or NIF <-30 cmH2O or >30% decline. Start IVIG or plasmapheresis immediately.',
      urgency: 'immediate',
      provenance: { section: 'GBS Respiratory Failure', page_or_location: 'Section 3.3' },
    },
    {
      flag_id: 'PACK.AAN.NM.2016.RF.02',
      display_id: 'AAN-NM-RF2',
      finding: 'MG patient with acute worsening after starting aminoglycoside, fluoroquinolone, beta-blocker, or magnesium',
      implication: 'These medications impair neuromuscular transmission and can precipitate myasthenic crisis. Aminoglycosides and magnesium are the most dangerous.',
      action: 'Discontinue offending medication immediately. Monitor FVC. Treat as impending myasthenic crisis if weakness is progressing. ICU admission if respiratory muscles involved.',
      urgency: 'urgent',
      provenance: { section: 'MG Drug Interactions', page_or_location: 'Section 5.5' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.AAN.NM.2016.SEV.01',
      display_id: 'AAN-NM-SEV1',
      level: 'Myasthenic crisis',
      criteria: [
        'MG exacerbation severe enough to require intubation or postpone extubation',
        'FVC <20 mL/kg or NIF weaker than -30 cmH2O',
        'Inability to handle secretions or maintain airway',
        'Often precipitated by infection, surgery, medication changes, or medication non-adherence',
      ],
      management_implications:
        'Neurological emergency. ICU admission mandatory. Intubate for airway protection. Hold cholinesterase inhibitors initially to differentiate from cholinergic crisis. Start IVIG (0.4 g/kg/day x 5 days) or plasmapheresis (5 exchanges). Identify and treat precipitant (infection most common). Mortality 4-8% with modern ICU care.',
      provenance: { section: 'Myasthenic Crisis', page_or_location: 'Section 6.1' },
    },
    {
      severity_id: 'PACK.AAN.NM.2016.SEV.02',
      display_id: 'AAN-NM-SEV2',
      level: 'GBS requiring ICU admission',
      criteria: [
        'Unable to walk independently (Hughes grade >=3)',
        'FVC <20 mL/kg or rapidly declining',
        'Bulbar weakness with aspiration risk',
        'Autonomic instability (labile BP, cardiac arrhythmias, urinary retention)',
      ],
      management_implications:
        'ICU admission with continuous cardiac monitoring. Serial FVC/NIF every 4-6 hours. IVIG or plasmapheresis urgently. DVT prophylaxis. Pain management (neuropathic pain is common). Autonomic dysfunction can cause fatal arrhythmias — continuous telemetry required. Average ICU stay 1-2 weeks; rehabilitation often months.',
      provenance: { section: 'GBS Severity', page_or_location: 'Section 3.4' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 neurology pack for neuromuscular diseases. Covers GBS (diagnosis, IVIG/PLEX, respiratory monitoring) and MG (diagnosis, pyridostigmine, thymectomy, myasthenic crisis).',

  all_item_ids: [
    'PACK.AAN.NM.2016.REC.01', 'PACK.AAN.NM.2016.REC.02', 'PACK.AAN.NM.2016.REC.03',
    'PACK.AAN.NM.2016.REC.04', 'PACK.AAN.NM.2016.REC.05',
    'PACK.AAN.NM.2016.DC.01', 'PACK.AAN.NM.2016.DC.02',
    'PACK.AAN.NM.2016.T.01', 'PACK.AAN.NM.2016.T.02',
    'PACK.AAN.NM.2016.TX.01', 'PACK.AAN.NM.2016.TX.02', 'PACK.AAN.NM.2016.TX.03', 'PACK.AAN.NM.2016.TX.04',
    'PACK.AAN.NM.2016.RF.01', 'PACK.AAN.NM.2016.RF.02',
    'PACK.AAN.NM.2016.SEV.01', 'PACK.AAN.NM.2016.SEV.02',
  ],
  all_display_ids: [
    'AAN-NM-R1', 'AAN-NM-R2', 'AAN-NM-R3', 'AAN-NM-R4', 'AAN-NM-R5',
    'AAN-NM-DC1', 'AAN-NM-DC2',
    'AAN-NM-T1', 'AAN-NM-T2',
    'AAN-NM-TX1', 'AAN-NM-TX2', 'AAN-NM-TX3', 'AAN-NM-TX4',
    'AAN-NM-RF1', 'AAN-NM-RF2',
    'AAN-NM-SEV1', 'AAN-NM-SEV2',
  ],
};
