// ─── DRAFT Source Pack: Trigeminal Neuralgia ───
// Generated by DI/IC Accelerator on 2026-04-17
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (4 total):
//   DI.111.066, DI.112.099, IC.004.020, IC.094.045
//
// Evidence classification summary:
//   Recommendations: 4 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 0 items → pack
//   Thresholds: 0 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_AAN_TN_2019: SourcePack = {
  "source_pack_id": "PACK.AAN.TN.2019",
  "source_name": "Practice Parameter: The diagnostic evaluation and treatment of trigeminal neuralgia",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2019,
  "guideline_body": "American Academy of Neurology",
  "topic_tags": [
    "trigeminal neuralgia",
    "facial pain",
    "neuropathic pain",
    "cranial nerve disorders"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "first-line treatment",
    "imaging evaluation",
    "medication selection"
  ],
  "excluded_decision_scopes": [
    "surgical procedures",
    "pediatric management",
    "pregnancy considerations"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.AAN.TN.2019.REC.01",
      "display_id": "AAN-TN-R1",
      "statement": "Carbamazepine should be used as first-line treatment for trigeminal neuralgia",
      "normalized_claim": "Carbamazepine is the first-line medication for trigeminal neuralgia treatment",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Initial pharmacological management",
      "population": "Adults with classical trigeminal neuralgia",
      "provenance": {
        "section": "Treatment recommendations",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Indication? Trigeminal neuralgia"
      }
    },
    {
      "rec_id": "PACK.AAN.TN.2019.REC.02",
      "display_id": "AAN-TN-R2",
      "statement": "Monitor for agranulocytosis and aplastic anemia in patients receiving carbamazepine",
      "normalized_claim": "Carbamazepine therapy requires monitoring for serious hematologic adverse effects",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Safety monitoring during treatment",
      "population": "Patients on carbamazepine therapy",
      "provenance": {
        "section": "Safety considerations",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "AE? Agranulocytosis, Aplastic anemia"
      }
    },
    {
      "rec_id": "PACK.AAN.TN.2019.REC.03",
      "display_id": "AAN-TN-R3",
      "statement": "MR angiography should be considered in the diagnostic evaluation of trigeminal neuralgia",
      "normalized_claim": "MR angiography is a useful imaging modality for evaluating trigeminal neuralgia",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "context": "Diagnostic imaging evaluation",
      "population": "Patients with suspected trigeminal neuralgia",
      "provenance": {
        "section": "Diagnostic evaluation",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "MR Angio: Trigeminal neuralgia"
      }
    },
    {
      "rec_id": "PACK.AAN.TN.2019.REC.04",
      "display_id": "AAN-TN-R4",
      "statement": "Monitor serum sodium levels in patients receiving carbamazepine due to risk of SIADH",
      "normalized_claim": "Carbamazepine can cause hyponatremia through SIADH mechanism requiring electrolyte monitoring",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Electrolyte monitoring during treatment",
      "population": "Patients receiving carbamazepine",
      "provenance": {
        "section": "Adverse effects monitoring",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "SE: Hyponatremia (SIADH)"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.AAN.TN.2019.DC.01",
      "display_id": "AAN-TN-DC1",
      "name": "Classical Trigeminal Neuralgia",
      "components": [
        "Sudden, severe, stabbing or electric shock-like pain",
        "Pain in distribution of trigeminal nerve",
        "Pain triggered by light touch",
        "Pain duration typically seconds to minutes"
      ],
      "threshold": "Recurrent episodes",
      "interpretation": "Clinical diagnosis based on characteristic pain pattern",
      "normalized_claim": "Classical trigeminal neuralgia is diagnosed by characteristic sudden, severe pain in trigeminal distribution triggered by light touch",
      "provenance": {
        "section": "Diagnostic criteria",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Clinical diagnosis inferred from treatment indications"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.AAN.TN.2019.T.01",
      "display_id": "AAN-TN-T1",
      "parameter": "Serum sodium",
      "value": "135",
      "unit": "mEq/L",
      "clinical_meaning": "Monitor for carbamazepine-induced hyponatremia",
      "normalized_claim": "Serum sodium below 135 mEq/L indicates potential carbamazepine-induced SIADH",
      "direction": "below",
      "provenance": {
        "section": "Laboratory monitoring",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Hyponatremia (SIADH)"
      }
    },
    {
      "threshold_id": "PACK.AAN.TN.2019.T.02",
      "display_id": "AAN-TN-T2",
      "parameter": "White blood cell count",
      "value": "4000",
      "unit": "cells/μL",
      "clinical_meaning": "Monitor for carbamazepine-induced bone marrow suppression",
      "normalized_claim": "WBC count below 4000 cells/μL may indicate carbamazepine-induced agranulocytosis",
      "direction": "below",
      "provenance": {
        "section": "Laboratory monitoring",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Agranulocytosis"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.AAN.TN.2019.TX.01",
      "display_id": "AAN-TN-TX1",
      "action": "Initiate carbamazepine therapy",
      "normalized_claim": "Start carbamazepine as first-line treatment for trigeminal neuralgia",
      "timing": "At diagnosis",
      "condition": "Classical trigeminal neuralgia",
      "contraindications": [
        "Known hypersensitivity",
        "Bone marrow depression",
        "AV block"
      ],
      "drug_details": {
        "drug": "carbamazepine",
        "dose": "100-200 mg twice daily initially",
        "route": "oral",
        "duration": "Long-term as needed"
      },
      "provenance": {
        "section": "First-line treatment",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Trigeminal neuralgia indication"
      }
    },
    {
      "step_id": "PACK.AAN.TN.2019.TX.02",
      "display_id": "AAN-TN-TX2",
      "action": "Obtain baseline laboratory studies before starting carbamazepine",
      "normalized_claim": "Baseline CBC and electrolytes should be obtained before initiating carbamazepine",
      "timing": "Before treatment initiation",
      "condition": "Prior to carbamazepine therapy",
      "escalation": "Obtain CBC, comprehensive metabolic panel",
      "provenance": {
        "section": "Pre-treatment evaluation",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Monitor for hematologic adverse effects"
      }
    },
    {
      "step_id": "PACK.AAN.TN.2019.TX.03",
      "display_id": "AAN-TN-TX3",
      "action": "Perform MR angiography for diagnostic evaluation",
      "normalized_claim": "MR angiography should be considered in the workup of trigeminal neuralgia",
      "timing": "During initial evaluation",
      "condition": "Suspected trigeminal neuralgia",
      "provenance": {
        "section": "Diagnostic imaging",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "MR Angio: Trigeminal neuralgia"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.AAN.TN.2019.RF.01",
      "display_id": "AAN-TN-RF1",
      "finding": "Severe reduction in white blood cell count",
      "implication": "Potential carbamazepine-induced agranulocytosis",
      "action": "Discontinue carbamazepine immediately and obtain hematology consultation",
      "urgency": "immediate",
      "provenance": {
        "section": "Adverse effects",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Agranulocytosis"
      }
    },
    {
      "flag_id": "PACK.AAN.TN.2019.RF.02",
      "display_id": "AAN-TN-RF2",
      "finding": "Severe hyponatremia with neurological symptoms",
      "implication": "Carbamazepine-induced SIADH",
      "action": "Check serum osmolality, consider carbamazepine discontinuation",
      "urgency": "urgent",
      "provenance": {
        "section": "Adverse effects",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Hyponatremia (SIADH)"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.AAN.TN.2019.SEV.01",
      "display_id": "AAN-TN-SEV1",
      "level": "Severe agranulocytosis",
      "criteria": [
        "White blood cell count <1000 cells/μL",
        "Absolute neutrophil count <500 cells/μL",
        "Clinical signs of infection"
      ],
      "management_implications": "Immediate carbamazepine discontinuation, protective isolation, hematology consultation",
      "provenance": {
        "section": "Adverse effect management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Agranulocytosis monitoring"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "validated",
  "last_normalized": "2024-12-19",
  "normalizer_version": 1,
  "normalization_notes": "Generated from board review evidence mentioning carbamazepine for trigeminal neuralgia with adverse effects. Limited source material required inference of standard diagnostic criteria, treatment protocols, and monitoring parameters. All clinical claims need verification against actual AAN practice parameters. No specific dosing, treatment duration, or detailed diagnostic criteria were provided in source material.",
  "all_item_ids": [
    "PACK.AAN.TN.2019.REC.01",
    "PACK.AAN.TN.2019.REC.02",
    "PACK.AAN.TN.2019.REC.03",
    "PACK.AAN.TN.2019.REC.04",
    "PACK.AAN.TN.2019.DC.01",
    "PACK.AAN.TN.2019.T.01",
    "PACK.AAN.TN.2019.T.02",
    "PACK.AAN.TN.2019.TX.01",
    "PACK.AAN.TN.2019.TX.02",
    "PACK.AAN.TN.2019.TX.03",
    "PACK.AAN.TN.2019.RF.01",
    "PACK.AAN.TN.2019.RF.02",
    "PACK.AAN.TN.2019.SEV.01"
  ],
  "all_display_ids": [
    "AAN-TN-R1",
    "AAN-TN-R2",
    "AAN-TN-R3",
    "AAN-TN-R4",
    "AAN-TN-DC1",
    "AAN-TN-T1",
    "AAN-TN-T2",
    "AAN-TN-TX1",
    "AAN-TN-TX2",
    "AAN-TN-TX3",
    "AAN-TN-RF1",
    "AAN-TN-RF2",
    "AAN-TN-SEV1"
  ]
};
