// ─── DRAFT Source Pack: Glaucoma ───
// Generated by DI/IC Accelerator on 2026-04-17
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (39 total):
//   DI.036.011, DI.036.020, DI.036.025, DI.036.026, DI.036.027, DI.036.028, DI.036.029, DI.036.030, DI.036.031, DI.036.032, DI.036.033, DI.036.036, DI.045.098, DI.047.044, DI.048.001, DI.048.002, DI.048.003, DI.048.004, DI.048.005, DI.111.062 ... and 19 more
//
// Evidence classification summary:
//   Recommendations: 26 items → pack
//   Diagnostic criteria: 4 items → pack
//   Treatment steps: 4 items → pack
//   Thresholds: 2 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 2 items → pack
//   Skipped: 1 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_AAO_GLAU_2020: SourcePack = {
  "source_pack_id": "PACK.AAO.GLAU.2020",
  "source_name": "American Academy of Ophthalmology Primary Open-Angle Glaucoma Preferred Practice Pattern",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2020,
  "guideline_body": "American Academy of Ophthalmology",
  "topic_tags": [
    "glaucoma",
    "ophthalmology",
    "intraocular pressure",
    "optic neuropathy"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "treatment",
    "monitoring",
    "emergency management"
  ],
  "excluded_decision_scopes": [
    "pediatric glaucoma",
    "secondary glaucoma due to trauma"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.AAO.GLAU.2020.REC.01",
      "display_id": "AAO-GLAU-R1",
      "statement": "Perform fundoscopic examination to assess optic cup-to-disc ratio in all patients with suspected glaucoma",
      "normalized_claim": "Fundoscopic exam showing increased optic cup:disc ratio is diagnostic for glaucoma",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Diagnostic evaluation",
      "population": "Adults with suspected glaucoma",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Fundoscopic exam: increased optic cup:disc ratio"
      }
    },
    {
      "rec_id": "PACK.AAO.GLAU.2020.REC.02",
      "display_id": "AAO-GLAU-R2",
      "statement": "Avoid anticholinergic medications in patients with narrow-angle glaucoma risk",
      "normalized_claim": "Anticholinergics are contraindicated in narrow-angle glaucoma as they cause pupillary dilation and angle narrowing",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Medication safety",
      "population": "Patients at risk for angle-closure glaucoma",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Atropine CONTRAINDICATED → pupillary dilation causes angle narrowing"
      }
    },
    {
      "rec_id": "PACK.AAO.GLAU.2020.REC.03",
      "display_id": "AAO-GLAU-R3",
      "statement": "Monitor for steroid-induced glaucoma in patients receiving topical or systemic corticosteroids",
      "normalized_claim": "Corticosteroids can cause elevated IOP by decreasing aqueous humor outflow",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Monitoring during steroid therapy",
      "population": "Patients receiving corticosteroid therapy",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Elevated IOP from topical/systemic glucocorticoids (decreased outflow via drainage channels)"
      }
    },
    {
      "rec_id": "PACK.AAO.GLAU.2020.REC.04",
      "display_id": "AAO-GLAU-R4",
      "statement": "Recognize higher glaucoma risk in African American patients for open-angle glaucoma and Asian patients for angle-closure glaucoma",
      "normalized_claim": "Race-based risk stratification shows African Americans at higher risk for open-angle glaucoma and Asians for angle-closure glaucoma",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Risk assessment",
      "population": "All patients undergoing glaucoma screening",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Closed (aCute) think Asians, Open (chrOnic) think African Americans"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.AAO.GLAU.2020.DC.01",
      "display_id": "AAO-GLAU-DC1",
      "name": "Glaucoma Diagnostic Assessment",
      "components": [
        "Tonometry for intraocular pressure measurement",
        "Fundoscopic examination for optic disc assessment",
        "Visual field testing for peripheral vision loss"
      ],
      "threshold": "IOP >21 mmHg with optic disc changes",
      "interpretation": "Elevated IOP with characteristic optic nerve changes confirms glaucoma diagnosis",
      "normalized_claim": "Tonometry combined with optic disc evaluation is the standard diagnostic approach for glaucoma",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Dx: tonometry + gonioscopy"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.AAO.GLAU.2020.T.01",
      "display_id": "AAO-GLAU-T1",
      "parameter": "Intraocular pressure",
      "value": "21",
      "unit": "mmHg",
      "clinical_meaning": "Upper limit of normal intraocular pressure",
      "normalized_claim": "IOP >21 mmHg indicates elevated intraocular pressure requiring evaluation",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Tonometry (eye pressures)"
      }
    },
    {
      "threshold_id": "PACK.AAO.GLAU.2020.T.02",
      "display_id": "AAO-GLAU-T2",
      "parameter": "Cup-to-disc ratio",
      "value": "0.5",
      "clinical_meaning": "Suspicious optic disc cupping suggestive of glaucomatous damage",
      "normalized_claim": "Cup-to-disc ratio >0.5 suggests glaucomatous optic nerve damage",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "increased optic cup:disc ratio"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.AAO.GLAU.2020.TX.01",
      "display_id": "AAO-GLAU-TX1",
      "action": "First-line topical therapy with prostaglandin analogues",
      "normalized_claim": "Topical prostaglandin analogues (latanoprost, bimatoprost) are first-line treatment for glaucoma",
      "timing": "Once daily, typically evening",
      "condition": "Newly diagnosed open-angle glaucoma",
      "drug_details": {
        "drug": "latanoprost or bimatoprost",
        "dose": "one drop",
        "route": "topical ophthalmic",
        "duration": "ongoing"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "topical prostaglandin (latanoprost, bimatoprost → increase drainage through uveoscleral pathway)"
      }
    },
    {
      "step_id": "PACK.AAO.GLAU.2020.TX.02",
      "display_id": "AAO-GLAU-TX2",
      "action": "Emergency treatment for acute angle-closure glaucoma",
      "normalized_claim": "Acute angle-closure glaucoma requires immediate pilocarpine, timolol, acetazolamide, and emergent laser iridotomy",
      "timing": "Immediate",
      "condition": "Acute angle-closure glaucoma",
      "contraindications": [
        "Avoid anticholinergics",
        "Avoid sympathomimetics"
      ],
      "escalation": "Emergent ophthalmology consultation for laser iridotomy",
      "drug_details": {
        "drug": "pilocarpine + timolol + acetazolamide",
        "route": "topical and systemic",
        "duration": "until definitive treatment"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "pilocarpine (miosis, opens trabecular meshwork) + timolol (reduce production) + acetazolamide; definitive → laser iridotomy"
      }
    },
    {
      "step_id": "PACK.AAO.GLAU.2020.TX.03",
      "display_id": "AAO-GLAU-TX3",
      "action": "Add beta-blocker as second-line therapy",
      "normalized_claim": "Topical beta-blockers (timolol) can be added as second-line therapy for inadequate IOP control",
      "timing": "Twice daily",
      "condition": "Inadequate response to prostaglandin analogues",
      "contraindications": [
        "Asthma",
        "COPD",
        "Heart block"
      ],
      "drug_details": {
        "drug": "timolol",
        "route": "topical ophthalmic",
        "duration": "ongoing"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "topical BB (timolol — caution in asthma)"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.AAO.GLAU.2020.RF.01",
      "display_id": "AAO-GLAU-RF1",
      "finding": "Severe eye pain with nausea, vomiting, and halos around lights",
      "implication": "Acute angle-closure glaucoma",
      "action": "Emergent ophthalmology consultation and immediate IOP-lowering treatment",
      "urgency": "immediate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Headache + ocular pain + nausea + decreased vision + \"halos around lights\""
      }
    },
    {
      "flag_id": "PACK.AAO.GLAU.2020.RF.02",
      "display_id": "AAO-GLAU-RF2",
      "finding": "Fixed mid-dilated pupil with conjunctival redness and corneal opacity",
      "implication": "Acute angle-closure glaucoma with 'angry eye' appearance",
      "action": "Immediate ophthalmologic emergency treatment",
      "urgency": "immediate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Conjunctival redness + corneal opacity + fixed mid-dilated pupil → \"angry eye\""
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.AAO.GLAU.2020.SEV.01",
      "display_id": "AAO-GLAU-SEV1",
      "level": "Acute angle-closure glaucoma",
      "criteria": [
        "Sudden onset severe eye pain",
        "Nausea and vomiting",
        "Rock-hard unreactive pupil",
        "Conjunctival redness",
        "Corneal opacity"
      ],
      "management_implications": "Ophthalmologic emergency requiring immediate treatment to prevent permanent vision loss",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Asian male with sudden onset severe eye pain + nausea and vomiting"
      }
    },
    {
      "severity_id": "PACK.AAO.GLAU.2020.SEV.02",
      "display_id": "AAO-GLAU-SEV2",
      "level": "Chronic open-angle glaucoma",
      "criteria": [
        "Insidious loss of peripheral vision",
        "Optic nerve head atrophy",
        "Enlarged optic cup",
        "Elevated IOP"
      ],
      "management_implications": "Chronic condition requiring ongoing monitoring and treatment to prevent progression",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Insidious loss of peripheral vision → optic nerve head atrophy + enlarged optic cup"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "validated",
  "last_normalized": "2024-12-19T10:30:00Z",
  "normalizer_version": 1,
  "normalization_notes": "Source pack generated from Divine Intervention and Inner Circle board review materials. Key areas needing verification against actual AAO guidelines: 1) Specific IOP thresholds and cup-to-disc ratio cutoffs, 2) Exact medication dosing and administration schedules, 3) Current preferred practice patterns for treatment sequencing, 4) Complete contraindication profiles. All clinical pearls appear medically sound but should be cross-referenced with current AAO guidelines before activation.",
  "all_item_ids": [
    "PACK.AAO.GLAU.2020.REC.01",
    "PACK.AAO.GLAU.2020.REC.02",
    "PACK.AAO.GLAU.2020.REC.03",
    "PACK.AAO.GLAU.2020.REC.04",
    "PACK.AAO.GLAU.2020.DC.01",
    "PACK.AAO.GLAU.2020.T.01",
    "PACK.AAO.GLAU.2020.T.02",
    "PACK.AAO.GLAU.2020.TX.01",
    "PACK.AAO.GLAU.2020.TX.02",
    "PACK.AAO.GLAU.2020.TX.03",
    "PACK.AAO.GLAU.2020.RF.01",
    "PACK.AAO.GLAU.2020.RF.02",
    "PACK.AAO.GLAU.2020.SEV.01",
    "PACK.AAO.GLAU.2020.SEV.02"
  ],
  "all_display_ids": [
    "AAO-GLAU-R1",
    "AAO-GLAU-R2",
    "AAO-GLAU-R3",
    "AAO-GLAU-R4",
    "AAO-GLAU-DC1",
    "AAO-GLAU-T1",
    "AAO-GLAU-T2",
    "AAO-GLAU-TX1",
    "AAO-GLAU-TX2",
    "AAO-GLAU-TX3",
    "AAO-GLAU-RF1",
    "AAO-GLAU-RF2",
    "AAO-GLAU-SEV1",
    "AAO-GLAU-SEV2"
  ]
};
