// ─── DRAFT Source Pack: Retinal Detachment ───
// Generated by DI/IC Accelerator on 2026-04-17
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (15 total):
//   DI.036.012, DI.036.013, DI.036.014, DI.036.015, DI.058.049, DI.097.001, IC.028.041, IC.058.179, IC.058.180, IC.058.181, IC.058.182, IC.058.183, IC.058.184, IC.058.217, IC.062.144
//
// Evidence classification summary:
//   Recommendations: 11 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 1 items → pack
//   Thresholds: 2 items → pack
//   Red flags: 1 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_AAO_RD_2019: SourcePack = {
  "source_pack_id": "PACK.AAO.RD.2019",
  "source_name": "American Academy of Ophthalmology Retinal Detachment Guidelines",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2019,
  "guideline_body": "American Academy of Ophthalmology",
  "topic_tags": [
    "retinal detachment",
    "ophthalmology",
    "emergency medicine",
    "vitreoretinal disease"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "emergency_management",
    "surgical_timing",
    "risk_assessment"
  ],
  "excluded_decision_scopes": [
    "specific_surgical_techniques",
    "post_operative_care",
    "pediatric_management"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.AAO.RD.2019.REC.01",
      "display_id": "AAO-RD-R1",
      "statement": "Patients presenting with eye trauma, floaters, and bright streaks of light should be evaluated for retinal detachment",
      "normalized_claim": "Eye trauma with floaters and photopsia suggests retinal detachment",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Emergency presentation",
      "population": "Patients with acute visual symptoms",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Punched in eye + floaters and bright streaks of light → retinal detachment"
      }
    },
    {
      "rec_id": "PACK.AAO.RD.2019.REC.02",
      "display_id": "AAO-RD-R2",
      "statement": "Risk factors for retinal detachment include trauma, cataract surgery, metabolic disorders, myopia, degenerative diseases, and vascular disorders",
      "normalized_claim": "Multiple risk factors predispose to retinal detachment",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "RFs: trauma, cataract surgery, metabolic disorders, myopia, degenerative diseases, vascular disorders"
      }
    },
    {
      "rec_id": "PACK.AAO.RD.2019.REC.03",
      "display_id": "AAO-RD-R3",
      "statement": "Time to surgical intervention is the most important prognostic factor in retinal detachment",
      "normalized_claim": "Urgent surgical repair improves outcomes in retinal detachment",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Surgical management",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "MIPF in retinal detachment → time to surgical intervention to fix"
      }
    },
    {
      "rec_id": "PACK.AAO.RD.2019.REC.04",
      "display_id": "AAO-RD-R4",
      "statement": "Avoid fluoroquinolones in patients at risk for retinal detachment due to increased risk of collagen degradation",
      "normalized_claim": "Fluoroquinolones increase retinal detachment risk",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "context": "Drug safety",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Avoid Fluoroquinolones (risk of increased collagen degradation — Achilles tendon rupture, retinal detachment, aortic aneurysm rupture)"
      }
    },
    {
      "rec_id": "PACK.AAO.RD.2019.REC.05",
      "display_id": "AAO-RD-R5",
      "statement": "Retinal detachment should be managed as an ophthalmologic emergency",
      "normalized_claim": "Retinal detachment requires emergency ophthalmologic intervention",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Emergency management",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Ophtho emergency"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.AAO.RD.2019.DC.01",
      "display_id": "AAO-RD-DC1",
      "name": "Clinical Diagnosis of Retinal Detachment",
      "components": [
        "Progressive peripheral visual field defect progressing centrally",
        "\"Curtain descending\" visual symptoms that do not resolve",
        "Gray elevated retina with wrinkled appearance on fundoscopy",
        "May have relative afferent pupillary defect"
      ],
      "interpretation": "Clinical constellation consistent with retinal detachment",
      "normalized_claim": "Retinal detachment presents with progressive visual field defects and characteristic fundoscopic findings",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Begins peripherally → peripheral visual defect → eventually central → \"curtain descending\""
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.AAO.RD.2019.T.01",
      "display_id": "AAO-RD-T1",
      "parameter": "Age for increased risk",
      "value": "65",
      "unit": "years",
      "clinical_meaning": "Increased risk of retinal detachment in elderly patients with diabetes",
      "normalized_claim": "Elderly diabetic patients have increased retinal detachment risk",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "65 yo M with past history of DM and CAD presents with 5 day hx of decreased vision/floaters"
      }
    },
    {
      "threshold_id": "PACK.AAO.RD.2019.T.02",
      "display_id": "AAO-RD-T2",
      "parameter": "Symptom duration requiring urgent evaluation",
      "value": "5",
      "unit": "days",
      "clinical_meaning": "Visual symptoms persisting for days warrant urgent ophthalmologic evaluation",
      "normalized_claim": "Visual symptoms lasting multiple days require urgent evaluation",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "5 day hx of decreased vision/floaters in R eye"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.AAO.RD.2019.TX.01",
      "display_id": "AAO-RD-TX1",
      "action": "Perform laser photocoagulation for retinal detachment repair",
      "normalized_claim": "Laser photocoagulation is a treatment option for retinal detachment",
      "timing": "Urgent",
      "condition": "Confirmed retinal detachment",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Tx: Laser photocoagulation (buzzword)"
      }
    },
    {
      "step_id": "PACK.AAO.RD.2019.TX.02",
      "display_id": "AAO-RD-TX2",
      "action": "Arrange urgent ophthalmologic consultation for surgical intervention",
      "normalized_claim": "Urgent surgical consultation is required for retinal detachment",
      "timing": "Immediate",
      "condition": "Suspected or confirmed retinal detachment",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "time to surgical intervention to fix"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.AAO.RD.2019.RF.01",
      "display_id": "AAO-RD-RF1",
      "finding": "Progressive visual field defect with \"curtain descending\" sensation",
      "implication": "Likely retinal detachment requiring emergency intervention",
      "action": "Immediate ophthalmologic consultation",
      "urgency": "immediate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Ophtho emergency"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.AAO.RD.2019.SEV.01",
      "display_id": "AAO-RD-SEV1",
      "level": "Ophthalmologic Emergency",
      "criteria": [
        "Progressive visual field loss",
        "Gray elevated retina on fundoscopy",
        "Non-resolving visual symptoms"
      ],
      "management_implications": "Requires immediate ophthalmologic consultation and urgent surgical repair",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Ophtho emergency"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "validated",
  "last_normalized": "2024-12-28",
  "normalizer_version": 1,
  "normalization_notes": "Generated from board review evidence (Divine Intervention + Inner Circle). All clinical claims appear medically accurate but require verification against actual AAO guidelines. Limited treatment detail available - may need expansion of surgical options and post-operative care. Risk factor list comprehensive. Emergency nature well-established. Needs verification of specific guideline recommendations and treatment algorithms.",
  "all_item_ids": [
    "PACK.AAO.RD.2019.REC.01",
    "PACK.AAO.RD.2019.REC.02",
    "PACK.AAO.RD.2019.REC.03",
    "PACK.AAO.RD.2019.REC.04",
    "PACK.AAO.RD.2019.REC.05",
    "PACK.AAO.RD.2019.DC.01",
    "PACK.AAO.RD.2019.T.01",
    "PACK.AAO.RD.2019.T.02",
    "PACK.AAO.RD.2019.TX.01",
    "PACK.AAO.RD.2019.TX.02",
    "PACK.AAO.RD.2019.RF.01",
    "PACK.AAO.RD.2019.SEV.01"
  ],
  "all_display_ids": [
    "AAO-RD-R1",
    "AAO-RD-R2",
    "AAO-RD-R3",
    "AAO-RD-R4",
    "AAO-RD-R5",
    "AAO-RD-DC1",
    "AAO-RD-T1",
    "AAO-RD-T2",
    "AAO-RD-TX1",
    "AAO-RD-TX2",
    "AAO-RD-RF1",
    "AAO-RD-SEV1"
  ]
};
