// ─── DRAFT Source Pack: Hepatocellular Carcinoma ───
// Generated by DI/IC Accelerator on 2026-04-17
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (14 total):
//   DI.022.373, DI.031.726, DI.102.038, DI.102.039, DI.102.040, DI.102.041, IC.052.047, IC.053.074, IC.053.090, IC.053.091, IC.053.092, IC.053.093, IC.053.097, IC.061.111
//
// Evidence classification summary:
//   Recommendations: 12 items → pack
//   Diagnostic criteria: 1 items → pack
//   Treatment steps: 0 items → pack
//   Thresholds: 1 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_AASLD_HCC_2022: SourcePack = {
  "source_pack_id": "PACK.AASLD.HCC.2022",
  "source_name": "AASLD Practice Guidance on Prevention, Diagnosis, and Treatment of Hepatocellular Carcinoma",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2022,
  "guideline_body": "American Association for the Study of Liver Diseases (AASLD)",
  "topic_tags": [
    "hepatocellular carcinoma",
    "liver cancer",
    "cirrhosis",
    "hepatitis B",
    "hepatitis C",
    "AFP",
    "liver transplant"
  ],
  "allowed_decision_scopes": [
    "screening",
    "diagnosis",
    "risk stratification",
    "prevention",
    "tumor markers",
    "imaging"
  ],
  "excluded_decision_scopes": [
    "surgical planning",
    "chemotherapy protocols",
    "liver transplant allocation"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.AASLD.HCC.2022.REC.01",
      "display_id": "AASLD-HCC-R1",
      "statement": "Hepatitis B vaccination should be used as the primary prevention strategy for hepatocellular carcinoma",
      "normalized_claim": "Hepatitis B vaccination is the most effective primary prevention for hepatocellular carcinoma",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Primary prevention of HCC",
      "population": "All appropriate candidates for hepatitis B vaccination",
      "provenance": {
        "section": "Prevention",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "#1 prevention of Hepatocellular carcinoma --> Hep B vaccination"
      }
    },
    {
      "rec_id": "PACK.AASLD.HCC.2022.REC.02",
      "display_id": "AASLD-HCC-R2",
      "statement": "Patients with cirrhosis should undergo abdominal ultrasound screening every 6 months for hepatocellular carcinoma",
      "normalized_claim": "Biannual ultrasound screening is recommended for cirrhotic patients to detect early HCC",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Surveillance in cirrhotic patients",
      "population": "Patients with cirrhosis",
      "provenance": {
        "section": "Surveillance",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Screening with Abdominal US every 6 months since patients may be initially asymptomatic"
      }
    },
    {
      "rec_id": "PACK.AASLD.HCC.2022.REC.03",
      "display_id": "AASLD-HCC-R3",
      "statement": "Alpha-fetoprotein (AFP) should be used as a tumor marker for hepatocellular carcinoma diagnosis and monitoring",
      "normalized_claim": "AFP is the primary tumor marker for hepatocellular carcinoma",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Diagnostic workup and monitoring",
      "population": "Patients with suspected or confirmed HCC",
      "provenance": {
        "section": "Diagnosis",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Tumor marker? AFP"
      }
    },
    {
      "rec_id": "PACK.AASLD.HCC.2022.REC.04",
      "display_id": "AASLD-HCC-R4",
      "statement": "Triple-phase arterial contrast CT should be used for diagnosis of hepatocellular carcinoma",
      "normalized_claim": "Triple-phase contrast CT is the preferred imaging modality for HCC diagnosis",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Diagnostic imaging",
      "population": "Patients with suspected HCC",
      "provenance": {
        "section": "Diagnosis",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Triple phase arterial contrast CT"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.AASLD.HCC.2022.DC.01",
      "display_id": "AASLD-HCC-DC1",
      "name": "HCC Tumor Marker Profile",
      "components": [
        "Elevated AFP (alpha-fetoprotein)",
        "Normal CEA",
        "Normal CA 19-9"
      ],
      "threshold": "AFP elevation with normal CEA/CA 19-9",
      "interpretation": "Distinguishes HCC from cholangiocarcinoma",
      "normalized_claim": "HCC is characterized by elevated AFP with normal CEA and CA 19-9, unlike cholangiocarcinoma",
      "provenance": {
        "section": "Diagnosis",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "HCC: Normal CEA and CA-19, Elevated AFP"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.AASLD.HCC.2022.T.01",
      "display_id": "AASLD-HCC-T1",
      "parameter": "Surveillance interval for cirrhotic patients",
      "value": "6",
      "unit": "months",
      "clinical_meaning": "Screening frequency for early HCC detection in cirrhosis",
      "normalized_claim": "Cirrhotic patients should be screened every 6 months with ultrasound",
      "direction": "range",
      "provenance": {
        "section": "Surveillance",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Screening with Abdominal US every 6 months"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.AASLD.HCC.2022.TX.01",
      "display_id": "AASLD-HCC-TX1",
      "action": "Administer hepatitis B vaccination for primary prevention",
      "normalized_claim": "Hepatitis B vaccination should be given to prevent HCC development",
      "timing": "Before exposure or early in course",
      "condition": "Appropriate candidates without contraindications",
      "contraindications": [
        "Severe acute illness",
        "Previous severe allergic reaction to vaccine"
      ],
      "escalation": "Monitor for seroconversion",
      "drug_details": {
        "drug": "Hepatitis B vaccine",
        "dose": "Standard series",
        "route": "Intramuscular",
        "duration": "3-dose series over 6 months"
      },
      "provenance": {
        "section": "Prevention",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "#1 prevention of Hepatocellular carcinoma --> Hep B vaccination"
      }
    },
    {
      "step_id": "PACK.AASLD.HCC.2022.TX.02",
      "display_id": "AASLD-HCC-TX2",
      "action": "Perform biannual ultrasound surveillance in cirrhotic patients",
      "normalized_claim": "Ultrasound every 6 months detects early HCC in cirrhosis",
      "timing": "Every 6 months",
      "condition": "Established cirrhosis diagnosis",
      "contraindications": [
        "Patient not candidate for treatment"
      ],
      "escalation": "Further imaging if suspicious lesions detected",
      "provenance": {
        "section": "Surveillance",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Screening with Abdominal US every 6 months"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.AASLD.HCC.2022.RF.01",
      "display_id": "AASLD-HCC-RF1",
      "finding": "Persistently bloody ascites in cirrhotic patient",
      "implication": "High suspicion for hepatocellular carcinoma",
      "action": "Urgent imaging and oncology consultation",
      "urgency": "urgent",
      "provenance": {
        "section": "Clinical Features",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Bloody: trauma, malignancy (MC is Hepatocellular Carcinoma) *HCC is repeatedly bloody"
      }
    },
    {
      "flag_id": "PACK.AASLD.HCC.2022.RF.02",
      "display_id": "AASLD-HCC-RF2",
      "finding": "Temporal muscle wasting (cachexia) with liver disease",
      "implication": "Advanced hepatocellular carcinoma with poor prognosis",
      "action": "Palliative care consultation and staging workup",
      "urgency": "urgent",
      "provenance": {
        "section": "Clinical Features",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Cachexia 'temporal wasting'"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.AASLD.HCC.2022.SEV.01",
      "display_id": "AASLD-HCC-SEV1",
      "level": "Advanced HCC with decompensated cirrhosis",
      "criteria": [
        "Ascites (persistently bloody)",
        "Jaundice",
        "Hypoalbuminemia",
        "Cachexia with temporal wasting",
        "Thrombocytopenia",
        "Coagulopathy (elevated PT/INR)",
        "Hyperbilirubinemia"
      ],
      "management_implications": "Palliative care focus, limited treatment options, poor prognosis",
      "provenance": {
        "section": "Staging and Prognosis",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Decompensated liver failure: Ascites (persistently bloody), Jaundice, Hypoalbuminemia"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-12-28",
  "normalizer_version": 1,
  "normalization_notes": "Generated from board review sources (Divine Intervention, Inner Circle). Key content includes HCC risk factors (Hep B/C, cirrhosis), primary prevention via Hep B vaccination, surveillance protocols for cirrhotic patients, diagnostic approach with AFP and imaging, and clinical features of advanced disease. Several treatment protocols and specific management guidelines need verification against current AASLD guidelines. Red flags focused on bloody ascites and cachexia as markers of advanced disease.",
  "all_item_ids": [
    "PACK.AASLD.HCC.2022.REC.01",
    "PACK.AASLD.HCC.2022.REC.02",
    "PACK.AASLD.HCC.2022.REC.03",
    "PACK.AASLD.HCC.2022.REC.04",
    "PACK.AASLD.HCC.2022.DC.01",
    "PACK.AASLD.HCC.2022.T.01",
    "PACK.AASLD.HCC.2022.TX.01",
    "PACK.AASLD.HCC.2022.TX.02",
    "PACK.AASLD.HCC.2022.RF.01",
    "PACK.AASLD.HCC.2022.RF.02",
    "PACK.AASLD.HCC.2022.SEV.01"
  ],
  "all_display_ids": [
    "AASLD-HCC-R1",
    "AASLD-HCC-R2",
    "AASLD-HCC-R3",
    "AASLD-HCC-R4",
    "AASLD-HCC-DC1",
    "AASLD-HCC-T1",
    "AASLD-HCC-TX1",
    "AASLD-HCC-TX2",
    "AASLD-HCC-RF1",
    "AASLD-HCC-RF2",
    "AASLD-HCC-SEV1"
  ]
};
