import type { SourcePack } from './types';

export const PACK_AASLD_HEPB_2018: SourcePack = {
  source_pack_id: 'PACK.AASLD.HEPB.2018',
  source_name: 'AASLD 2018 Hepatitis B Guidance: Update on Prevention, Diagnosis, and Treatment of Chronic Hepatitis B',
  canonical_url: 'https://doi.org/10.1002/hep.29800',
  publication_year: 2018,
  guideline_body: 'AASLD',

  topic_tags: ['Hepatitis B', 'HBV', 'Chronic Liver Disease', 'HCC Screening', 'Gastroenterology', 'Infectious Disease'],
  allowed_decision_scopes: [
    'HBV serology interpretation',
    'chronic HBV phase classification',
    'treatment indications for chronic HBV',
    'antiviral selection (entecavir vs tenofovir)',
    'HCC screening in chronic HBV',
    'HBV reactivation prevention',
    'perinatal HBV prophylaxis',
  ],
  excluded_decision_scopes: [
    'hepatitis D coinfection management',
    'liver transplant for HBV cirrhosis',
    'HBV vaccine development',
    'acute hepatitis B management in detail',
  ],

  recommendations: [
    {
      rec_id: 'PACK.AASLD.HEPB.2018.REC.01',
      display_id: 'AASLD-HEPB-R1',
      statement: 'Entecavir and tenofovir (TDF or TAF) are recommended as preferred first-line antiviral therapies for chronic hepatitis B. Lamivudine, adefovir, and telbivudine are no longer recommended due to high resistance rates.',
      normalized_claim: 'Entecavir or tenofovir (TDF/TAF) are first-line for chronic HBV; older agents (lamivudine, adefovir) avoided due to resistance.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Antiviral Therapy', page_or_location: 'Section 5.1' },
    },
    {
      rec_id: 'PACK.AASLD.HEPB.2018.REC.02',
      display_id: 'AASLD-HEPB-R2',
      statement: 'Treatment is recommended for immune-active chronic HBV: HBeAg-positive patients with ALT >2x ULN and HBV DNA >20,000 IU/mL, or HBeAg-negative patients with ALT >2x ULN and HBV DNA >2,000 IU/mL.',
      normalized_claim: 'Treat immune-active HBV: HBeAg+ with ALT >2x ULN and DNA >20,000; HBeAg- with ALT >2x ULN and DNA >2,000.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Treatment Indications', page_or_location: 'Section 4.2' },
    },
    {
      rec_id: 'PACK.AASLD.HEPB.2018.REC.03',
      display_id: 'AASLD-HEPB-R3',
      statement: 'HCC surveillance with abdominal ultrasound with or without AFP every 6 months is recommended for all chronic HBV patients at increased risk: Asian males >40, Asian females >50, Africans >20, cirrhotics of any age, and those with family history of HCC.',
      normalized_claim: 'HCC screening: US +/- AFP every 6 months for at-risk chronic HBV patients (Asian M >40, F >50, cirrhotics, African >20, FHx HCC).',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'HCC Surveillance', page_or_location: 'Section 7.1' },
    },
    {
      rec_id: 'PACK.AASLD.HEPB.2018.REC.04',
      display_id: 'AASLD-HEPB-R4',
      statement: 'All patients receiving immunosuppressive therapy should be screened for HBV (HBsAg and anti-HBc) before treatment initiation. HBsAg-positive patients should receive antiviral prophylaxis.',
      normalized_claim: 'Screen for HBV before immunosuppression; HBsAg+ patients need antiviral prophylaxis to prevent reactivation.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'HBV Reactivation', page_or_location: 'Section 6.1' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.AASLD.HEPB.2018.DC.01',
      display_id: 'AASLD-HEPB-DC1',
      name: 'HBV Serology Interpretation',
      components: [
        'Acute HBV: HBsAg+, anti-HBc IgM+, HBeAg+, HBV DNA high',
        'Chronic HBV (immune tolerant): HBsAg+, HBeAg+, HBV DNA very high (>1M), ALT normal',
        'Chronic HBV (immune active): HBsAg+, HBeAg+/-, HBV DNA elevated, ALT elevated',
        'Inactive carrier: HBsAg+, HBeAg-, anti-HBe+, HBV DNA <2,000, ALT normal',
        'Resolved HBV: HBsAg-, anti-HBs+, anti-HBc IgG+',
        'Vaccinated: anti-HBs+ only (no anti-HBc)',
        'Isolated anti-HBc: anti-HBc+ only — may represent resolved, false positive, or occult HBV',
      ],
      interpretation: 'HBsAg defines active infection. Anti-HBs indicates immunity. Anti-HBc indicates prior exposure. HBeAg reflects high viral replication. Phase determines treatment eligibility.',
      normalized_claim: 'HBV serology: HBsAg = active infection, anti-HBs = immunity, anti-HBc = prior exposure. Phase classification (tolerant, active, inactive, resolved) guides management.',
      provenance: { section: 'Serology', page_or_location: 'Table 1' },
    },
    {
      criterion_id: 'PACK.AASLD.HEPB.2018.DC.02',
      display_id: 'AASLD-HEPB-DC2',
      name: 'Phases of Chronic HBV Infection',
      components: [
        'Phase 1 — Immune tolerant: HBeAg+, HBV DNA >1M IU/mL, ALT normal, minimal inflammation',
        'Phase 2 — Immune active (HBeAg+): HBeAg+, HBV DNA >20,000, ALT elevated, liver inflammation',
        'Phase 3 — Inactive carrier: HBeAg-, anti-HBe+, HBV DNA <2,000, ALT normal',
        'Phase 4 — Reactivation (HBeAg-): HBeAg-, HBV DNA >2,000, ALT elevated, precore/core promoter mutants',
      ],
      interpretation: 'Phase 2 and Phase 4 are the immune-active phases requiring antiviral treatment. Phase 1 and Phase 3 are monitored without treatment unless progression occurs.',
      normalized_claim: 'Treat immune-active phases (2 and 4) with antiviral therapy. Monitor immune-tolerant (1) and inactive carrier (3) phases.',
      provenance: { section: 'Natural History', page_or_location: 'Figure 1' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.AASLD.HEPB.2018.T.01',
      display_id: 'AASLD-HEPB-T1',
      parameter: 'HBV DNA for treatment (HBeAg-positive)',
      value: '20000',
      unit: 'IU/mL',
      clinical_meaning: 'HBV DNA >20,000 IU/mL in HBeAg-positive patients with ALT >2x ULN indicates immune-active disease requiring treatment.',
      normalized_claim: 'HBV DNA >20,000 IU/mL + ALT >2x ULN in HBeAg+ patient = treatment indicated.',
      direction: 'above',
      provenance: { section: 'Treatment Indications', page_or_location: 'Section 4.2' },
    },
    {
      threshold_id: 'PACK.AASLD.HEPB.2018.T.02',
      display_id: 'AASLD-HEPB-T2',
      parameter: 'HBV DNA for treatment (HBeAg-negative)',
      value: '2000',
      unit: 'IU/mL',
      clinical_meaning: 'HBV DNA >2,000 IU/mL in HBeAg-negative patients with ALT >2x ULN indicates reactivation phase requiring treatment.',
      normalized_claim: 'HBV DNA >2,000 IU/mL + ALT >2x ULN in HBeAg- patient = reactivation phase, treatment indicated.',
      direction: 'above',
      provenance: { section: 'Treatment Indications', page_or_location: 'Section 4.2' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.AASLD.HEPB.2018.TX.01',
      display_id: 'AASLD-HEPB-TX1',
      action: 'Immune-active chronic HBV: Start first-line antiviral',
      normalized_claim: 'Entecavir 0.5mg daily (1mg if lamivudine-experienced) or tenofovir TDF 300mg daily as first-line. Treatment is long-term, often indefinite.',
      timing: 'At confirmation of immune-active phase',
      condition: 'Immune-active HBV (Phase 2 or Phase 4)',
      drug_details: { drug: 'Entecavir', dose: '0.5mg daily', route: 'PO', duration: 'Indefinite in most cases' },
      contraindications: ['Entecavir: avoid if prior lamivudine resistance (use tenofovir)', 'TDF: caution in renal impairment or osteoporosis (prefer TAF)'],
      provenance: { section: 'Antiviral Therapy', page_or_location: 'Section 5.1' },
    },
    {
      step_id: 'PACK.AASLD.HEPB.2018.TX.02',
      display_id: 'AASLD-HEPB-TX2',
      action: 'HBV reactivation prophylaxis before immunosuppression',
      normalized_claim: 'HBsAg+ patients: start antiviral before immunosuppression and continue >=12 months after completion. Anti-HBc+/HBsAg- patients on high-risk regimens (rituximab): monitor or prophylax.',
      timing: 'Before initiating immunosuppressive therapy',
      condition: 'HBsAg-positive patient starting chemotherapy, biologic therapy, or immunosuppression',
      drug_details: { drug: 'Entecavir or tenofovir', dose: 'Standard dosing', route: 'PO' },
      provenance: { section: 'HBV Reactivation Prevention', page_or_location: 'Section 6.1' },
    },
    {
      step_id: 'PACK.AASLD.HEPB.2018.TX.03',
      display_id: 'AASLD-HEPB-TX3',
      action: 'Perinatal prophylaxis: Tenofovir in third trimester for high viral load',
      normalized_claim: 'Pregnant women with HBV DNA >200,000 IU/mL should start tenofovir TDF in weeks 28-32 to reduce perinatal transmission, in addition to neonatal HBIg + vaccine.',
      timing: 'Third trimester (28-32 weeks gestation)',
      condition: 'Pregnant HBsAg+ woman with HBV DNA >200,000 IU/mL',
      drug_details: { drug: 'Tenofovir TDF', dose: '300mg daily', route: 'PO', duration: 'Through delivery, can stop postpartum' },
      provenance: { section: 'Perinatal Transmission', page_or_location: 'Section 8.1' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.AASLD.HEPB.2018.RF.01',
      display_id: 'AASLD-HEPB-RF1',
      finding: 'HBV reactivation during immunosuppression: rising HBV DNA, ALT flare, jaundice in patient on chemotherapy or biologics (especially rituximab, anti-TNF)',
      implication: 'Can progress to fulminant hepatic failure and death. Risk highest with rituximab, stem cell transplant, and high-dose corticosteroids.',
      action: 'Start entecavir or tenofovir immediately. Consider reducing immunosuppression if possible. Monitor LFTs closely.',
      urgency: 'urgent',
      provenance: { section: 'HBV Reactivation', page_or_location: 'Section 6.2' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.AASLD.HEPB.2018.SEV.01',
      display_id: 'AASLD-HEPB-SEV1',
      level: 'Chronic HBV with compensated cirrhosis',
      criteria: [
        'HBsAg+ with cirrhosis on imaging/biopsy (F4 fibrosis)',
        'Preserved synthetic function (normal albumin, INR, no ascites)',
        'Any detectable HBV DNA',
        'Child-Pugh A',
      ],
      management_implications:
        'Treat with antiviral regardless of ALT or HBV DNA level (lower threshold than non-cirrhotic). HCC surveillance q6 months mandatory. Monitor for decompensation. Entecavir or tenofovir; avoid interferon in cirrhosis.',
      provenance: { section: 'Cirrhosis Management', page_or_location: 'Section 5.3' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for hepatitis B. Covers serology interpretation, chronic HBV phases, treatment indications, HCC screening, and reactivation prevention.',

  all_item_ids: [
    'PACK.AASLD.HEPB.2018.REC.01', 'PACK.AASLD.HEPB.2018.REC.02', 'PACK.AASLD.HEPB.2018.REC.03',
    'PACK.AASLD.HEPB.2018.REC.04',
    'PACK.AASLD.HEPB.2018.DC.01', 'PACK.AASLD.HEPB.2018.DC.02',
    'PACK.AASLD.HEPB.2018.T.01', 'PACK.AASLD.HEPB.2018.T.02',
    'PACK.AASLD.HEPB.2018.TX.01', 'PACK.AASLD.HEPB.2018.TX.02', 'PACK.AASLD.HEPB.2018.TX.03',
    'PACK.AASLD.HEPB.2018.RF.01',
    'PACK.AASLD.HEPB.2018.SEV.01',
  ],
  all_display_ids: [
    'AASLD-HEPB-R1', 'AASLD-HEPB-R2', 'AASLD-HEPB-R3', 'AASLD-HEPB-R4',
    'AASLD-HEPB-DC1', 'AASLD-HEPB-DC2',
    'AASLD-HEPB-T1', 'AASLD-HEPB-T2',
    'AASLD-HEPB-TX1', 'AASLD-HEPB-TX2', 'AASLD-HEPB-TX3',
    'AASLD-HEPB-RF1',
    'AASLD-HEPB-SEV1',
  ],
};
