import type { SourcePack } from './types';

export const pack: SourcePack = {
  source_pack_id: 'PACK.AASLD.CSBP.2021',
  source_name: 'AASLD Practice Guidance on Portal Hypertension and Ascites 2022',
  source_registry_id: 'REG.AASLD.CSBP',
  canonical_url: 'https://doi.org/10.1002/hep.32Portal',
  publication_year: 2021,
  guideline_body: 'American Association for the Study of Liver Diseases',

  topic_tags: ['Cirrhosis', 'SBP', 'Portal Hypertension', 'Ascites', 'Variceal Bleeding', 'Hepatic Encephalopathy', 'Hepatorenal Syndrome', 'Gastroenterology'],
  allowed_decision_scopes: [
    'SBP diagnosis and treatment',
    'SBP primary and secondary prophylaxis',
    'variceal screening and surveillance',
    'variceal bleeding acute management',
    'beta-blocker therapy for portal hypertension',
    'ascites management and paracentesis',
    'hepatic encephalopathy treatment',
    'hepatorenal syndrome diagnosis and management',
    'Child-Pugh and MELD scoring',
    'TIPS indications',
    'albumin use in cirrhosis',
  ],
  excluded_decision_scopes: [
    'liver transplant evaluation criteria',
    'hepatocellular carcinoma screening protocols',
    'NASH/NAFLD management',
    'autoimmune hepatitis treatment',
    'chronic hepatitis B/C antiviral therapy',
  ],

  recommendations: [
    {
      rec_id: 'PACK.AASLD.CSBP.2021.REC.01',
      display_id: 'AASLD-CSBP-R1',
      statement: 'Empiric antibiotics should be initiated immediately in patients with ascitic fluid PMN count >=250 cells/mm3, without waiting for culture results.',
      normalized_claim: 'SBP diagnosed by ascitic fluid PMN >=250 cells/mm3; start empiric antibiotics immediately without awaiting cultures.',
      strength: 'strong',
      evidence_quality: 'moderate',
      context: 'Delay in treatment increases mortality; cultures are negative in up to 40% of SBP cases',
      provenance: { section: 'SBP Diagnosis and Treatment', page_or_location: 'Section 8.2' },
    },
    {
      rec_id: 'PACK.AASLD.CSBP.2021.REC.02',
      display_id: 'AASLD-CSBP-R2',
      statement: 'IV cefotaxime (2g q8h) is the preferred empiric antibiotic for community-acquired SBP. Ceftriaxone (2g IV daily) is an acceptable alternative.',
      normalized_claim: 'Community-acquired SBP: IV cefotaxime 2g q8h (preferred) or ceftriaxone 2g IV daily for 5 days.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'SBP Treatment', page_or_location: 'Section 8.3' },
    },
    {
      rec_id: 'PACK.AASLD.CSBP.2021.REC.03',
      display_id: 'AASLD-CSBP-R3',
      statement: 'IV albumin (1.5 g/kg on day 1, 1 g/kg on day 3) should be administered with antibiotics for SBP to reduce the incidence of hepatorenal syndrome and improve survival.',
      normalized_claim: 'Albumin with SBP antibiotics: 1.5 g/kg day 1, 1 g/kg day 3 — reduces HRS and mortality.',
      strength: 'strong',
      evidence_quality: 'high',
      population: 'Patients with SBP, especially those with BUN >30, Cr >1.0, or bilirubin >4',
      provenance: { section: 'SBP Adjunctive Therapy', page_or_location: 'Section 8.4', quote_snippet: 'Albumin significantly decreased HRS incidence from 33% to 10% and mortality from 29% to 10%' },
    },
    {
      rec_id: 'PACK.AASLD.CSBP.2021.REC.04',
      display_id: 'AASLD-CSBP-R4',
      statement: 'Non-selective beta-blockers (NSBB: propranolol, nadolol, or carvedilol) are recommended for primary prophylaxis of variceal hemorrhage in patients with medium/large varices.',
      normalized_claim: 'NSBB (propranolol, nadolol, or carvedilol) for primary prophylaxis of variceal bleeding with medium/large varices.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'Target resting heart rate 55-60 bpm; carvedilol 6.25mg BID is an alternative',
      provenance: { section: 'Variceal Bleeding Prophylaxis', page_or_location: 'Section 6.1' },
    },
    {
      rec_id: 'PACK.AASLD.CSBP.2021.REC.05',
      display_id: 'AASLD-CSBP-R5',
      statement: 'Endoscopic variceal ligation (EVL) is recommended for primary prophylaxis when NSBB are contraindicated or not tolerated, and is the preferred endoscopic therapy for acute variceal bleeding.',
      normalized_claim: 'EVL for primary prophylaxis if NSBB contraindicated; EVL is first-line endoscopic therapy for acute variceal bleed.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Variceal Bleeding Management', page_or_location: 'Section 6.2' },
    },
    {
      rec_id: 'PACK.AASLD.CSBP.2021.REC.06',
      display_id: 'AASLD-CSBP-R6',
      statement: 'Lactulose is the first-line treatment for hepatic encephalopathy. Dose should be titrated to achieve 2-3 soft bowel movements per day.',
      normalized_claim: 'Lactulose first-line for hepatic encephalopathy; titrate to 2-3 soft stools/day.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Hepatic Encephalopathy', page_or_location: 'Section 9.1' },
    },
    {
      rec_id: 'PACK.AASLD.CSBP.2021.REC.07',
      display_id: 'AASLD-CSBP-R7',
      statement: 'Rifaximin (550mg BID) should be added to lactulose for prevention of recurrent hepatic encephalopathy after the first episode.',
      normalized_claim: 'Rifaximin 550mg BID added to lactulose for secondary prophylaxis of hepatic encephalopathy.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Hepatic Encephalopathy Prevention', page_or_location: 'Section 9.2' },
    },
    {
      rec_id: 'PACK.AASLD.CSBP.2021.REC.08',
      display_id: 'AASLD-CSBP-R8',
      statement: 'Daily norfloxacin (400mg) or weekly ciprofloxacin (750mg) is recommended for SBP secondary prophylaxis in patients who have recovered from a prior SBP episode.',
      normalized_claim: 'SBP secondary prophylaxis: norfloxacin 400mg daily or ciprofloxacin 750mg weekly.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'SBP Prophylaxis', page_or_location: 'Section 8.6' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.AASLD.CSBP.2021.DC.01',
      display_id: 'AASLD-CSBP-DC1',
      name: 'SBP Diagnostic Criteria',
      components: [
        'Ascitic fluid polymorphonuclear (PMN) leukocyte count >=250 cells/mm3',
        'No surgically treatable intra-abdominal source of infection',
        'Positive ascitic fluid culture supports but is not required for diagnosis',
      ],
      threshold: 'PMN >=250 cells/mm3',
      interpretation: 'PMN >=250 cells/mm3 in ascitic fluid is diagnostic of SBP regardless of culture results. Culture-negative SBP (culture-negative neutrocytic ascites) is treated identically to culture-positive SBP.',
      normalized_claim: 'SBP = ascitic fluid PMN >=250 cells/mm3 without surgical abdomen. Treat regardless of culture results.',
      provenance: { section: 'SBP Diagnosis', page_or_location: 'Section 8.1' },
    },
    {
      criterion_id: 'PACK.AASLD.CSBP.2021.DC.02',
      display_id: 'AASLD-CSBP-DC2',
      name: 'Child-Pugh Classification',
      components: [
        'Encephalopathy grade (none=1, grade 1-2=2, grade 3-4=3)',
        'Ascites (absent=1, slight=2, moderate=3)',
        'Bilirubin (<2=1, 2-3=2, >3=3 mg/dL)',
        'Albumin (>3.5=1, 2.8-3.5=2, <2.8=3 g/dL)',
        'INR (<1.7=1, 1.7-2.3=2, >2.3=3)',
      ],
      threshold: 'Class A: 5-6 points, Class B: 7-9 points, Class C: 10-15 points',
      interpretation: 'Child-Pugh stratifies cirrhosis severity. Class A = compensated, Class B = significant functional compromise, Class C = decompensated. Guides transplant referral and operative risk.',
      normalized_claim: 'Child-Pugh score: A (5-6), B (7-9), C (10-15). Uses encephalopathy, ascites, bilirubin, albumin, INR. Class C = decompensated cirrhosis.',
      provenance: { section: 'Severity Assessment', page_or_location: 'Section 2.1' },
    },
    {
      criterion_id: 'PACK.AASLD.CSBP.2021.DC.03',
      display_id: 'AASLD-CSBP-DC3',
      name: 'Hepatorenal Syndrome (HRS-AKI) Criteria',
      components: [
        'Cirrhosis with ascites',
        'Increase in serum creatinine >=0.3 mg/dL within 48h or >=50% from baseline within 7 days',
        'No improvement of serum creatinine after 2 days of diuretic withdrawal and volume expansion with albumin (1 g/kg/day)',
        'Absence of shock',
        'No current or recent use of nephrotoxic drugs',
        'No parenchymal kidney disease (proteinuria <500 mg/day, no hematuria, normal renal ultrasound)',
      ],
      interpretation: 'HRS-AKI is a functional renal failure in advanced cirrhosis. Diagnosis requires exclusion of other causes of AKI. First-line treatment is IV albumin + vasoconstrictors (terlipressin or norepinephrine).',
      normalized_claim: 'HRS-AKI: Cr rise >=0.3 in 48h in cirrhosis with ascites, unresponsive to albumin challenge, no shock/nephrotoxins/parenchymal disease.',
      provenance: { section: 'Hepatorenal Syndrome', page_or_location: 'Section 10.1' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.AASLD.CSBP.2021.T.01',
      display_id: 'AASLD-CSBP-T1',
      parameter: 'Ascitic fluid PMN count',
      value: '250',
      unit: 'cells/mm3',
      clinical_meaning: 'PMN count >=250 cells/mm3 is diagnostic of SBP and mandates empiric antibiotic therapy.',
      normalized_claim: 'Ascitic fluid PMN >=250 cells/mm3 = SBP; treat empirically.',
      direction: 'above',
      provenance: { section: 'SBP Diagnosis', page_or_location: 'Section 8.1' },
    },
    {
      threshold_id: 'PACK.AASLD.CSBP.2021.T.02',
      display_id: 'AASLD-CSBP-T2',
      parameter: 'Serum-ascites albumin gradient (SAAG)',
      value: '1.1',
      unit: 'g/dL',
      clinical_meaning: 'SAAG >=1.1 g/dL indicates portal hypertension as the cause of ascites (97% accuracy). SAAG <1.1 suggests non-portal hypertensive cause (malignancy, TB peritonitis, nephrotic syndrome).',
      normalized_claim: 'SAAG >=1.1 g/dL = portal hypertension (97% accuracy). SAAG <1.1 = non-portal hypertensive cause.',
      direction: 'above',
      provenance: { section: 'Ascites Evaluation', page_or_location: 'Section 4.1' },
    },
    {
      threshold_id: 'PACK.AASLD.CSBP.2021.T.03',
      display_id: 'AASLD-CSBP-T3',
      parameter: 'MELD score for transplant listing',
      value: '15',
      unit: 'points',
      clinical_meaning: 'MELD >=15 identifies patients who benefit from liver transplant listing. MELD uses bilirubin, INR, and creatinine. Higher MELD = higher 90-day mortality without transplant.',
      normalized_claim: 'MELD >=15: refer for liver transplant evaluation. MELD uses bilirubin, INR, creatinine.',
      direction: 'above',
      provenance: { section: 'Transplant Referral', page_or_location: 'Section 2.3' },
    },
    {
      threshold_id: 'PACK.AASLD.CSBP.2021.T.04',
      display_id: 'AASLD-CSBP-T4',
      parameter: 'Ascitic fluid total protein for SBP prophylaxis',
      value: '1.5',
      unit: 'g/dL',
      clinical_meaning: 'Ascitic fluid total protein <1.5 g/dL indicates reduced opsonic activity and increased risk of SBP. Primary prophylaxis with norfloxacin considered when combined with advanced liver disease (Child-Pugh >=9 with bilirubin >=3 or renal impairment).',
      normalized_claim: 'Ascitic fluid protein <1.5 g/dL + advanced liver disease = consider SBP primary prophylaxis with norfloxacin.',
      direction: 'below',
      provenance: { section: 'SBP Primary Prophylaxis', page_or_location: 'Section 8.5' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.AASLD.CSBP.2021.TX.01',
      display_id: 'AASLD-CSBP-TX1',
      action: 'SBP: Empiric antibiotics and albumin',
      normalized_claim: 'SBP treatment: cefotaxime 2g IV q8h x5 days + albumin 1.5 g/kg day 1 and 1 g/kg day 3.',
      timing: 'Immediately upon diagnosis (PMN >=250)',
      condition: 'Spontaneous bacterial peritonitis',
      drug_details: { drug: 'Cefotaxime', dose: '2g IV q8h', route: 'IV', duration: '5 days' },
      contraindications: ['Severe cephalosporin allergy (use fluoroquinolone alternative)'],
      escalation: 'If no clinical improvement at 48h, repeat paracentesis. If PMN has not decreased by >=25%, broaden antibiotic coverage for nosocomial or resistant organisms.',
      provenance: { section: 'SBP Treatment', page_or_location: 'Section 8.3' },
    },
    {
      step_id: 'PACK.AASLD.CSBP.2021.TX.02',
      display_id: 'AASLD-CSBP-TX2',
      action: 'Acute variceal bleeding: Octreotide + antibiotics + endoscopy',
      normalized_claim: 'Acute variceal bleed: IV octreotide bolus 50mcg then 50mcg/hr + ceftriaxone 1g IV daily + EVL within 12h. Restrictive transfusion (Hgb target 7-8 g/dL).',
      timing: 'Within 12 hours of presentation',
      condition: 'Acute variceal hemorrhage',
      drug_details: { drug: 'Octreotide', dose: '50mcg IV bolus, then 50mcg/hr infusion', route: 'IV', duration: '2-5 days' },
      contraindications: ['Octreotide hypersensitivity'],
      escalation: 'If EVL fails to control bleeding, consider balloon tamponade (Blakemore tube) as bridge to TIPS. Early TIPS (within 72h) for Child-Pugh C or B with active bleeding at endoscopy.',
      provenance: { section: 'Acute Variceal Hemorrhage', page_or_location: 'Section 6.3' },
    },
    {
      step_id: 'PACK.AASLD.CSBP.2021.TX.03',
      display_id: 'AASLD-CSBP-TX3',
      action: 'Hepatic encephalopathy: Lactulose titration + rifaximin',
      normalized_claim: 'HE treatment: lactulose 20-30g PO q1-2h until bowel movement, then titrate to 2-3 stools/day. Add rifaximin 550mg BID for recurrence prevention.',
      timing: 'Immediately upon recognition of encephalopathy',
      condition: 'Hepatic encephalopathy (acute or recurrent)',
      drug_details: { drug: 'Lactulose', dose: '20-30g (30-45mL) PO', route: 'PO or per rectum', duration: 'Ongoing' },
      escalation: 'If lactulose alone insufficient, add rifaximin. Identify and treat precipitants: infection, GI bleed, constipation, electrolyte abnormalities, sedatives.',
      provenance: { section: 'Hepatic Encephalopathy Treatment', page_or_location: 'Section 9.1' },
    },
    {
      step_id: 'PACK.AASLD.CSBP.2021.TX.04',
      display_id: 'AASLD-CSBP-TX4',
      action: 'Hepatorenal syndrome: Albumin + vasoconstrictors',
      normalized_claim: 'HRS-AKI treatment: discontinue diuretics, IV albumin 1 g/kg/day (max 100g) x2 days. If no response, add midodrine + octreotide (or norepinephrine in ICU). Terlipressin where available.',
      timing: 'Upon diagnosis of HRS-AKI after albumin challenge fails',
      condition: 'Hepatorenal syndrome - acute kidney injury',
      drug_details: { drug: 'Albumin', dose: '1 g/kg/day (max 100g)', route: 'IV', duration: 'Until Cr improves or transplant' },
      escalation: 'If midodrine/octreotide fails, norepinephrine drip in ICU. Consider TIPS in select patients. Liver transplant is definitive treatment.',
      provenance: { section: 'Hepatorenal Syndrome Management', page_or_location: 'Section 10.2' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.AASLD.CSBP.2021.RF.01',
      display_id: 'AASLD-CSBP-RF1',
      finding: 'Refractory ascites: Ascites unresponsive to sodium restriction and maximum-dose diuretics (spironolactone 400mg + furosemide 160mg) or diuretic-related complications preventing adequate dosing',
      implication: 'Indicates severe portal hypertension. Median survival approximately 6 months. Evaluate for TIPS or liver transplant.',
      action: 'Serial large-volume paracentesis with albumin replacement (6-8g per liter removed). Refer for TIPS evaluation. Expedite transplant workup.',
      urgency: 'urgent',
      provenance: { section: 'Refractory Ascites', page_or_location: 'Section 5.3' },
    },
    {
      flag_id: 'PACK.AASLD.CSBP.2021.RF.02',
      display_id: 'AASLD-CSBP-RF2',
      finding: 'Acute variceal hemorrhage with hemodynamic instability (SBP <90, HR >120, hematemesis with altered mental status)',
      implication: 'High mortality (15-20% at 6 weeks). Requires aggressive resuscitation and emergent endoscopy.',
      action: 'Airway protection (intubation if needed), IV access x2, restrictive transfusion (target Hgb 7-8), IV octreotide, IV ceftriaxone, emergent EGD within 12h. Consider early TIPS if Child-Pugh C.',
      urgency: 'immediate',
      provenance: { section: 'Acute Variceal Hemorrhage', page_or_location: 'Section 6.3' },
    },
    {
      flag_id: 'PACK.AASLD.CSBP.2021.RF.03',
      display_id: 'AASLD-CSBP-RF3',
      finding: 'Rising creatinine in cirrhotic patient with ascites despite volume expansion with albumin',
      implication: 'Suggests hepatorenal syndrome (HRS-AKI). High mortality without treatment. Must exclude other causes of AKI (ATN, obstruction, nephrotoxins).',
      action: 'Discontinue diuretics and nephrotoxic drugs. Albumin challenge 1 g/kg x2 days. If no improvement, initiate vasoconstrictor therapy. Urgent transplant evaluation.',
      urgency: 'urgent',
      provenance: { section: 'Hepatorenal Syndrome', page_or_location: 'Section 10.1' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.AASLD.CSBP.2021.SEV.01',
      display_id: 'AASLD-CSBP-SEV1',
      level: 'Child-Pugh A (compensated cirrhosis)',
      criteria: [
        'Child-Pugh score 5-6 points',
        'No or minimal ascites',
        'No encephalopathy',
        'Bilirubin <2 mg/dL',
        'Albumin >3.5 g/dL',
        'INR <1.7',
      ],
      management_implications: 'Compensated disease. Screen for varices at diagnosis. Initiate beta-blocker if varices present. Hepatocellular carcinoma surveillance every 6 months. Avoid hepatotoxins. 1-year survival approximately 95%.',
      provenance: { section: 'Severity Assessment', page_or_location: 'Section 2.1' },
    },
    {
      severity_id: 'PACK.AASLD.CSBP.2021.SEV.02',
      display_id: 'AASLD-CSBP-SEV2',
      level: 'Child-Pugh B (significant hepatic compromise)',
      criteria: [
        'Child-Pugh score 7-9 points',
        'Moderate ascites',
        'Mild-to-moderate encephalopathy possible',
        'Bilirubin 2-3 mg/dL',
        'Albumin 2.8-3.5 g/dL',
        'INR 1.7-2.3',
      ],
      management_implications: 'Decompensation features present or imminent. Diuretics for ascites (spironolactone + furosemide). Variceal prophylaxis mandatory. Transplant evaluation should be initiated. Avoid elective surgery. 1-year survival approximately 80%.',
      provenance: { section: 'Severity Assessment', page_or_location: 'Section 2.1' },
    },
    {
      severity_id: 'PACK.AASLD.CSBP.2021.SEV.03',
      display_id: 'AASLD-CSBP-SEV3',
      level: 'Child-Pugh C (decompensated cirrhosis)',
      criteria: [
        'Child-Pugh score 10-15 points',
        'Tense ascites or refractory ascites',
        'Moderate-to-severe encephalopathy',
        'Bilirubin >3 mg/dL',
        'Albumin <2.8 g/dL',
        'INR >2.3',
      ],
      management_implications: 'Decompensated cirrhosis with high short-term mortality. Aggressive management of complications (SBP prophylaxis, HE treatment, variceal surveillance). Expedite transplant listing. Consider early TIPS for refractory ascites or recurrent variceal bleeding. 1-year survival approximately 45%. NSBB should be held if SBP <90 or MAP <65.',
      provenance: { section: 'Severity Assessment', page_or_location: 'Section 2.1' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for cirrhosis/SBP. Covers SBP diagnosis and treatment, variceal bleeding, hepatic encephalopathy, hepatorenal syndrome, and Child-Pugh classification for question generation.',

  all_item_ids: [
    'PACK.AASLD.CSBP.2021.REC.01', 'PACK.AASLD.CSBP.2021.REC.02', 'PACK.AASLD.CSBP.2021.REC.03',
    'PACK.AASLD.CSBP.2021.REC.04', 'PACK.AASLD.CSBP.2021.REC.05', 'PACK.AASLD.CSBP.2021.REC.06',
    'PACK.AASLD.CSBP.2021.REC.07', 'PACK.AASLD.CSBP.2021.REC.08',
    'PACK.AASLD.CSBP.2021.DC.01', 'PACK.AASLD.CSBP.2021.DC.02', 'PACK.AASLD.CSBP.2021.DC.03',
    'PACK.AASLD.CSBP.2021.T.01', 'PACK.AASLD.CSBP.2021.T.02', 'PACK.AASLD.CSBP.2021.T.03', 'PACK.AASLD.CSBP.2021.T.04',
    'PACK.AASLD.CSBP.2021.TX.01', 'PACK.AASLD.CSBP.2021.TX.02', 'PACK.AASLD.CSBP.2021.TX.03', 'PACK.AASLD.CSBP.2021.TX.04',
    'PACK.AASLD.CSBP.2021.RF.01', 'PACK.AASLD.CSBP.2021.RF.02', 'PACK.AASLD.CSBP.2021.RF.03',
    'PACK.AASLD.CSBP.2021.SEV.01', 'PACK.AASLD.CSBP.2021.SEV.02', 'PACK.AASLD.CSBP.2021.SEV.03',
  ],
  all_display_ids: [
    'AASLD-CSBP-R1', 'AASLD-CSBP-R2', 'AASLD-CSBP-R3', 'AASLD-CSBP-R4', 'AASLD-CSBP-R5', 'AASLD-CSBP-R6', 'AASLD-CSBP-R7', 'AASLD-CSBP-R8',
    'AASLD-CSBP-DC1', 'AASLD-CSBP-DC2', 'AASLD-CSBP-DC3',
    'AASLD-CSBP-T1', 'AASLD-CSBP-T2', 'AASLD-CSBP-T3', 'AASLD-CSBP-T4',
    'AASLD-CSBP-TX1', 'AASLD-CSBP-TX2', 'AASLD-CSBP-TX3', 'AASLD-CSBP-TX4',
    'AASLD-CSBP-RF1', 'AASLD-CSBP-RF2', 'AASLD-CSBP-RF3',
    'AASLD-CSBP-SEV1', 'AASLD-CSBP-SEV2', 'AASLD-CSBP-SEV3',
  ],
};
