// ─── DRAFT Source Pack: Alcoholic Hepatitis ───
// Generated by DI/IC Accelerator on 2026-04-16
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (9 total):
//   DI.212.002, EH.003.014, IC.053.018, IC.053.019, IC.053.020, IC.053.021, IC.053.022, IC.053.023, IC.053.024
//
// Evidence classification summary:
//   Recommendations: 5 items → pack
//   Diagnostic criteria: 1 items → pack
//   Treatment steps: 1 items → pack
//   Thresholds: 2 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_AASLD_AH_2019: SourcePack = {
  "source_pack_id": "PACK.AASLD.AH.2019",
  "source_name": "AASLD Practice Guidelines: Alcoholic Hepatitis",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2019,
  "guideline_body": "AASLD",
  "topic_tags": [
    "alcoholic hepatitis",
    "liver disease",
    "alcohol-related liver disease",
    "hepatitis",
    "gastroenterology"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "treatment",
    "management",
    "laboratory interpretation"
  ],
  "excluded_decision_scopes": [
    "surgical intervention",
    "transplant evaluation"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.AASLD.AH.2019.REC.01",
      "display_id": "AASLD-AH-R1",
      "statement": "Consider alcoholic hepatitis in patients presenting with fever and jaundice in the setting of alcohol use",
      "normalized_claim": "Fever and jaundice are key presenting features of alcoholic hepatitis",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Clinical presentation",
      "population": "Patients with alcohol use history",
      "provenance": {
        "section": "Clinical Presentation",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "1. Fever and jaundice"
      }
    },
    {
      "rec_id": "PACK.AASLD.AH.2019.REC.02",
      "display_id": "AASLD-AH-R2",
      "statement": "Evaluate for right upper quadrant pain and epigastric pain in suspected alcoholic hepatitis",
      "normalized_claim": "RUQ pain and epigastric pain are common symptoms in alcoholic hepatitis",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Clinical assessment",
      "population": "Patients with suspected alcoholic hepatitis",
      "provenance": {
        "section": "Clinical Presentation",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "2. RUQ pain +/- epigastric pain"
      }
    },
    {
      "rec_id": "PACK.AASLD.AH.2019.REC.03",
      "display_id": "AASLD-AH-R3",
      "statement": "Assess for ascites as a manifestation of alcoholic hepatitis",
      "normalized_claim": "Ascites causing abdominal distention is a feature of alcoholic hepatitis",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Physical examination",
      "population": "Patients with alcoholic hepatitis",
      "provenance": {
        "section": "Clinical Presentation",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "3. Abdominal distention due to ascites"
      }
    },
    {
      "rec_id": "PACK.AASLD.AH.2019.REC.04",
      "display_id": "AASLD-AH-R4",
      "statement": "Examine for tender hepatomegaly in patients with suspected alcoholic hepatitis",
      "normalized_claim": "Tender hepatomegaly is a physical finding in alcoholic hepatitis",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Physical examination",
      "population": "Patients with suspected alcoholic hepatitis",
      "provenance": {
        "section": "Clinical Presentation",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "4. Tender hepatomegaly"
      }
    },
    {
      "rec_id": "PACK.AASLD.AH.2019.REC.05",
      "display_id": "AASLD-AH-R5",
      "statement": "Initiate supportive care including abstinence, hydration, nutrition, and acid suppression for alcoholic hepatitis",
      "normalized_claim": "Management of alcoholic hepatitis includes abstinence, hydration, nutrition, and acid suppression",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Treatment",
      "population": "Patients with alcoholic hepatitis",
      "provenance": {
        "section": "Management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "7. Tx: Abstinence, Hydration + Nutrition, Acid suppression"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.AASLD.AH.2019.DC.01",
      "display_id": "AASLD-AH-DC1",
      "name": "Alcoholic Hepatitis Clinical Diagnosis",
      "components": [
        "Clinical presentation (fever, jaundice, RUQ pain)",
        "Physical findings (tender hepatomegaly, ascites)",
        "Laboratory abnormalities (AST>ALT ratio >2, elevated GGT)",
        "History of alcohol use"
      ],
      "interpretation": "Clinical diagnosis based on constellation of findings in patient with alcohol use history",
      "normalized_claim": "Alcoholic hepatitis is diagnosed clinically using combination of symptoms, signs, and laboratory findings",
      "provenance": {
        "section": "Diagnosis",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "6. Dx: Clinical diagnosis"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.AASLD.AH.2019.T.01",
      "display_id": "AASLD-AH-T1",
      "parameter": "AST to ALT ratio",
      "value": "2",
      "clinical_meaning": "AST greater than 2 times ALT suggests alcoholic hepatitis",
      "normalized_claim": "AST:ALT ratio >2 is characteristic of alcoholic hepatitis",
      "direction": "above",
      "provenance": {
        "section": "Laboratory Findings",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "AST>ALT (2x) + high GGT -> Alcoholic Hepatitis"
      }
    },
    {
      "threshold_id": "PACK.AASLD.AH.2019.T.02",
      "display_id": "AASLD-AH-T2",
      "parameter": "GGT elevation",
      "value": "elevated",
      "clinical_meaning": "Elevated GGT supports diagnosis of alcoholic hepatitis when combined with AST>ALT ratio >2",
      "normalized_claim": "Elevated GGT along with AST:ALT ratio >2 indicates alcoholic hepatitis",
      "direction": "above",
      "provenance": {
        "section": "Laboratory Findings",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "AST>ALT (2x) + high GGT -> Alcoholic Hepatitis"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.AASLD.AH.2019.TX.01",
      "display_id": "AASLD-AH-TX1",
      "action": "Initiate alcohol abstinence",
      "normalized_claim": "Alcohol abstinence is the first-line treatment for alcoholic hepatitis",
      "timing": "Immediate",
      "condition": "Confirmed alcoholic hepatitis",
      "provenance": {
        "section": "Treatment",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "7. Tx: Abstinence, Hydration + Nutrition, Acid suppression"
      }
    },
    {
      "step_id": "PACK.AASLD.AH.2019.TX.02",
      "display_id": "AASLD-AH-TX2",
      "action": "Provide supportive care with hydration, nutrition, and acid suppression",
      "normalized_claim": "Supportive care including hydration, nutrition, and acid suppression is essential in alcoholic hepatitis management",
      "timing": "Concurrent with abstinence",
      "condition": "Alcoholic hepatitis",
      "provenance": {
        "section": "Treatment",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "7. Tx: Abstinence, Hydration + Nutrition, Acid suppression"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.AASLD.AH.2019.RF.01",
      "display_id": "AASLD-AH-RF1",
      "finding": "Elevated INR with jaundice",
      "implication": "Indicates hepatic synthetic dysfunction and potential severe alcoholic hepatitis",
      "action": "Assess disease severity and consider corticosteroid therapy evaluation",
      "urgency": "urgent",
      "provenance": {
        "section": "Laboratory Assessment",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "inc Bilirubin, inc INR"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.AASLD.AH.2019.SEV.01",
      "display_id": "AASLD-AH-SEV1",
      "level": "Moderate to Severe",
      "criteria": [
        "Elevated bilirubin",
        "Increased INR",
        "Macrocytic anemia",
        "Clinical symptoms (fever, jaundice, RUQ pain)"
      ],
      "management_implications": "Requires close monitoring and consideration of specific therapies beyond supportive care",
      "provenance": {
        "section": "Disease Assessment",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "inc Bilirubin, inc INR | 2. Macrocytic anemia"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "validated",
  "last_normalized": "2024-12-28T12:00:00Z",
  "normalizer_version": 1,
  "normalization_notes": "Source pack created from board review evidence items. Clinical presentation and diagnostic criteria well-represented. Treatment recommendations limited to supportive care - may need expansion with corticosteroid protocols and severity scoring systems from actual guideline. Laboratory thresholds and red flags derived from provided evidence but need verification against AASLD guidelines for completeness and accuracy.",
  "all_item_ids": [
    "PACK.AASLD.AH.2019.REC.01",
    "PACK.AASLD.AH.2019.REC.02",
    "PACK.AASLD.AH.2019.REC.03",
    "PACK.AASLD.AH.2019.REC.04",
    "PACK.AASLD.AH.2019.REC.05",
    "PACK.AASLD.AH.2019.DC.01",
    "PACK.AASLD.AH.2019.T.01",
    "PACK.AASLD.AH.2019.T.02",
    "PACK.AASLD.AH.2019.TX.01",
    "PACK.AASLD.AH.2019.TX.02",
    "PACK.AASLD.AH.2019.RF.01",
    "PACK.AASLD.AH.2019.SEV.01"
  ],
  "all_display_ids": [
    "AASLD-AH-R1",
    "AASLD-AH-R2",
    "AASLD-AH-R3",
    "AASLD-AH-R4",
    "AASLD-AH-R5",
    "AASLD-AH-DC1",
    "AASLD-AH-T1",
    "AASLD-AH-T2",
    "AASLD-AH-TX1",
    "AASLD-AH-TX2",
    "AASLD-AH-RF1",
    "AASLD-AH-SEV1"
  ]
};
