// ─── DRAFT Source Pack: Obstructive Sleep Apnea ───
// Generated by DI/IC Accelerator on 2026-04-16
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (12 total):
//   DI.126.016, DI.126.017, DI.126.018, DI.126.019, EH.001.167, IC.020.053, IC.040.001, IC.040.002, IC.040.003, IC.040.004, IC.040.005, IC.040.006
//
// Evidence classification summary:
//   Recommendations: 10 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 1 items → pack
//   Thresholds: 0 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 1 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_AASM_OSA_2020: SourcePack = {
  "source_pack_id": "PACK.AASM.OSA.2020",
  "source_name": "American Academy of Sleep Medicine Clinical Practice Guideline for Obstructive Sleep Apnea",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2020,
  "guideline_body": "American Academy of Sleep Medicine",
  "topic_tags": [
    "sleep disorders",
    "obstructive sleep apnea",
    "sleep medicine",
    "respiratory disorders"
  ],
  "allowed_decision_scopes": [
    "adult OSA diagnosis",
    "pediatric OSA diagnosis",
    "OSA management",
    "surgical treatment",
    "sleep study interpretation"
  ],
  "excluded_decision_scopes": [
    "central sleep apnea",
    "complex sleep apnea",
    "CPAP titration protocols",
    "insurance authorization"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.AASM.OSA.2020.REC.01",
      "display_id": "AASM-OSA-R1",
      "statement": "Consider obstructive sleep apnea in patients with daytime sleepiness, hypertension, and obesity, particularly with elevated BMI >30",
      "normalized_claim": "OSA should be suspected in obese patients (BMI >30) presenting with daytime sleepiness and hypertension",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Clinical presentation",
      "population": "Adults with suspected OSA",
      "provenance": {
        "section": "Clinical Assessment",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "45M falling asleep a lot at work, BP 145/85, BMI 32: obstructive sleep apnea"
      }
    },
    {
      "rec_id": "PACK.AASM.OSA.2020.REC.02",
      "display_id": "AASM-OSA-R2",
      "statement": "Evaluate for secondary polycythemia in patients with suspected OSA, as chronic hypoxia leads to compensatory erythropoietin elevation",
      "normalized_claim": "OSA patients may develop reactive polycythemia due to chronic hypoxia and elevated EPO levels",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Laboratory evaluation",
      "population": "OSA patients with chronic hypoxia",
      "provenance": {
        "section": "Laboratory Assessment",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Reactive polycythemia d/t chronic hypoxia (high EPO, Hct/Hb)"
      }
    },
    {
      "rec_id": "PACK.AASM.OSA.2020.REC.03",
      "display_id": "AASM-OSA-R3",
      "statement": "Consider OSA in obese patients presenting with daytime sleepiness and depression, especially those with large neck circumference",
      "normalized_claim": "OSA should be considered in obese patients with daytime sleepiness, depression, and large neck circumference",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Clinical presentation",
      "population": "Obese adults with mood and sleep symptoms",
      "provenance": {
        "section": "Clinical Assessment",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Daytime sleepiness and depression in an obese patient with a large neck"
      }
    },
    {
      "rec_id": "PACK.AASM.OSA.2020.REC.04",
      "display_id": "AASM-OSA-R4",
      "statement": "In pediatric patients, consider OSA when adenotonsillar hypertrophy is present with symptoms of upper airway obstruction",
      "normalized_claim": "Pediatric OSA should be suspected in children with adenotonsillar hypertrophy causing nasal obstruction and mouth breathing",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Pediatric evaluation",
      "population": "Children with adenotonsillar hypertrophy",
      "provenance": {
        "section": "Pediatric OSA",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Adenotonsillar hypertrophy — causes significant nasal airway obstruction leading to mouth breathing"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.AASM.OSA.2020.DC.01",
      "display_id": "AASM-OSA-DC1",
      "name": "Pediatric OSA Clinical Features",
      "components": [
        "Loud snoring",
        "Witnessed pauses in breathing",
        "Gasping during sleep",
        "Adenotonsillar hypertrophy",
        "Mouth breathing"
      ],
      "interpretation": "Combination of nocturnal symptoms with anatomical findings suggests pediatric OSA",
      "normalized_claim": "Pediatric OSA is characterized by loud snoring, breathing pauses, gasping, and upper airway obstruction from adenotonsillar hypertrophy",
      "provenance": {
        "section": "Pediatric OSA Diagnosis",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Loud snoring, pauses in breathing, gasping"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.AASM.OSA.2020.T.01",
      "display_id": "AASM-OSA-T1",
      "parameter": "Body Mass Index",
      "value": "30",
      "unit": "kg/m²",
      "clinical_meaning": "Obesity threshold associated with increased OSA risk",
      "normalized_claim": "BMI >30 kg/m² significantly increases risk for obstructive sleep apnea",
      "direction": "above",
      "provenance": {
        "section": "Risk Factors",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "BMI 32: obstructive sleep apnea"
      }
    },
    {
      "threshold_id": "PACK.AASM.OSA.2020.T.02",
      "display_id": "AASM-OSA-T2",
      "parameter": "Serum bicarbonate",
      "value": "elevated",
      "clinical_meaning": "Compensatory metabolic alkalosis due to chronic CO2 retention",
      "normalized_claim": "Elevated serum bicarbonate indicates renal compensation for chronic hypercapnia in OSA",
      "direction": "above",
      "provenance": {
        "section": "Laboratory Findings",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "High HCO3 d/t kidney compensation"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.AASM.OSA.2020.TX.01",
      "display_id": "AASM-OSA-TX1",
      "action": "Adenotonsillectomy",
      "normalized_claim": "Tonsillectomy and adenoidectomy is the primary treatment for pediatric OSA caused by adenotonsillar hypertrophy",
      "timing": "First-line treatment",
      "condition": "Adenotonsillar hypertrophy in children",
      "contraindications": [
        "Bleeding disorders",
        "Severe cardiac disease"
      ],
      "provenance": {
        "section": "Pediatric Treatment",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Management | 1. Tonsillectomy & Adenoidectomy"
      }
    },
    {
      "step_id": "PACK.AASM.OSA.2020.TX.02",
      "display_id": "AASM-OSA-TX2",
      "action": "Sleep study evaluation",
      "normalized_claim": "Polysomnography should be performed to confirm OSA diagnosis and assess severity",
      "timing": "Before treatment initiation",
      "condition": "Suspected OSA based on clinical presentation",
      "provenance": {
        "section": "Diagnostic Testing",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Clinical assessment suggests need for objective testing"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.AASM.OSA.2020.RF.01",
      "display_id": "AASM-OSA-RF1",
      "finding": "Failure to thrive in children with sleep symptoms",
      "implication": "Severe OSA affecting growth and development",
      "action": "Urgent sleep medicine referral and consideration of expedited adenotonsillectomy",
      "urgency": "urgent",
      "provenance": {
        "section": "Pediatric Complications",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Poor growth (failure to thrive)"
      }
    },
    {
      "flag_id": "PACK.AASM.OSA.2020.RF.02",
      "display_id": "AASM-OSA-RF2",
      "finding": "Poor school performance with sleep disturbance",
      "implication": "OSA affecting cognitive function and academic achievement",
      "action": "Sleep study evaluation and treatment consideration",
      "urgency": "soon",
      "provenance": {
        "section": "Pediatric Complications",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Poor school performance"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.AASM.OSA.2020.SEV.01",
      "display_id": "AASM-OSA-SEV1",
      "level": "Complicated Pediatric OSA",
      "criteria": [
        "Failure to thrive",
        "Poor school performance",
        "Adenotonsillar hypertrophy",
        "Nocturnal breathing disturbances"
      ],
      "management_implications": "Requires urgent surgical intervention with adenotonsillectomy",
      "provenance": {
        "section": "Pediatric OSA Severity",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Complications | Poor growth (failure to thrive) | Poor school performance"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "validated",
  "last_normalized": "2024-01-15",
  "normalizer_version": 1,
  "normalization_notes": "Generated from board review sources (Divine Intervention, Inner Circle, Emma Holliday). Evidence primarily focused on clinical presentations and pediatric OSA. Limited adult treatment options in source material. Recommendations need verification against actual AASM guidelines. Missing formal AHI thresholds, CPAP protocols, and comprehensive adult management strategies. Strong pediatric content but adult OSA management needs expansion.",
  "all_item_ids": [
    "PACK.AASM.OSA.2020.REC.01",
    "PACK.AASM.OSA.2020.REC.02",
    "PACK.AASM.OSA.2020.REC.03",
    "PACK.AASM.OSA.2020.REC.04",
    "PACK.AASM.OSA.2020.DC.01",
    "PACK.AASM.OSA.2020.T.01",
    "PACK.AASM.OSA.2020.T.02",
    "PACK.AASM.OSA.2020.TX.01",
    "PACK.AASM.OSA.2020.TX.02",
    "PACK.AASM.OSA.2020.RF.01",
    "PACK.AASM.OSA.2020.RF.02",
    "PACK.AASM.OSA.2020.SEV.01"
  ],
  "all_display_ids": [
    "AASM-OSA-R1",
    "AASM-OSA-R2",
    "AASM-OSA-R3",
    "AASM-OSA-R4",
    "AASM-OSA-DC1",
    "AASM-OSA-T1",
    "AASM-OSA-T2",
    "AASM-OSA-TX1",
    "AASM-OSA-TX2",
    "AASM-OSA-RF1",
    "AASM-OSA-RF2",
    "AASM-OSA-SEV1"
  ]
};
