import type { SourcePack } from './types';

export const PACK_ABA_BURNS_2016: SourcePack = {
  source_pack_id: 'PACK.ABA.BURNS.2016',
  source_name: 'ABA 2016 Guidelines for Burn Care — Classification, Resuscitation, and Referral',
  canonical_url: 'https://ameriburn.org/resources/burn-center-referral-criteria/',
  publication_year: 2016,
  guideline_body: 'ABA',

  topic_tags: ['Burns', 'Burn Resuscitation', 'Parkland Formula', 'Inhalation Injury', 'Escharotomy', 'Surgery'],
  allowed_decision_scopes: [
    'burn depth classification',
    'TBSA estimation (rule of 9s)',
    'fluid resuscitation (Parkland formula)',
    'burn center referral criteria',
    'escharotomy indications',
    'inhalation injury recognition and management',
    'carbon monoxide poisoning treatment',
  ],
  excluded_decision_scopes: [
    'long-term burn rehabilitation',
    'scar management and reconstruction',
    'burn wound infection microbiology details',
    'psychological care after burns',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ABA.BURNS.2016.REC.01',
      display_id: 'ABA-R1',
      statement: 'Fluid resuscitation using the Parkland formula (4 mL x body weight in kg x % TBSA burned) with lactated Ringer solution is recommended for burns ≥20% TBSA. Half of the calculated volume is given in the first 8 hours from time of burn (not time of arrival), and the remaining half over the next 16 hours.',
      normalized_claim: 'Parkland formula: 4 mL/kg/% TBSA of LR. Half in first 8h from TIME OF BURN (not arrival), half over next 16h. For burns ≥20% TBSA.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Fluid Resuscitation', page_or_location: 'Chapter 4' },
    },
    {
      rec_id: 'PACK.ABA.BURNS.2016.REC.02',
      display_id: 'ABA-R2',
      statement: 'Patients meeting burn center referral criteria should be transferred: >20% TBSA partial thickness, any full thickness >5%, burns to face/hands/feet/genitalia/perineum/major joints, inhalation injury, electrical/chemical burns, circumferential burns, pre-existing medical conditions.',
      normalized_claim: 'Burn center referral: >20% TBSA partial-thickness, full-thickness >5%, face/hands/feet/genitalia/joints, inhalation injury, electrical/chemical, circumferential burns.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Referral Criteria', page_or_location: 'ABA Guidelines' },
    },
    {
      rec_id: 'PACK.ABA.BURNS.2016.REC.03',
      display_id: 'ABA-R3',
      statement: 'Carbon monoxide poisoning should be treated with 100% FiO2 via non-rebreather mask. Carboxyhemoglobin (COHb) levels should be measured in all patients with suspected inhalation injury. Hyperbaric oxygen is considered for COHb >25%, neurologic symptoms, or pregnancy.',
      normalized_claim: 'CO poisoning: 100% O2 via NRB. Check COHb levels. Hyperbaric O2 for COHb >25%, neurologic symptoms, or pregnancy.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Inhalation Injury', page_or_location: 'Chapter 6' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ABA.BURNS.2016.DC.01',
      display_id: 'ABA-DC1',
      name: 'Burn Depth Classification',
      components: [
        'Superficial (1st degree): epidermis only, erythema, painful, no blisters (e.g., sunburn). NOT included in TBSA calculation.',
        'Superficial partial-thickness (2nd degree): epidermis + superficial dermis, blisters, moist/weeping, very painful, blanches with pressure',
        'Deep partial-thickness (2nd degree): epidermis + deep dermis, blisters, mottled pink/white, decreased sensation, may not blanch',
        'Full-thickness (3rd degree): entire dermis destroyed, leathery/waxy/white/charred, painless, does not blanch',
        'Fourth-degree: extends through skin into underlying fat, muscle, tendon, or bone',
      ],
      interpretation: 'Superficial burns are excluded from TBSA. Partial-thickness burns heal without grafting (superficial) or may need grafting (deep). Full-thickness always requires excision and grafting.',
      normalized_claim: 'Burn classification: superficial (not in TBSA), partial-thickness (blisters, painful), full-thickness (painless, leathery, requires grafting), 4th degree (deeper structures).',
      provenance: { section: 'Burn Assessment', page_or_location: 'Chapter 2' },
    },
    {
      criterion_id: 'PACK.ABA.BURNS.2016.DC.02',
      display_id: 'ABA-DC2',
      name: 'Rule of 9s for TBSA Estimation (Adults)',
      components: [
        'Head and neck: 9%',
        'Each upper extremity: 9%',
        'Anterior trunk: 18%',
        'Posterior trunk: 18%',
        'Each lower extremity: 18%',
        'Perineum/genitalia: 1%',
        'Patient palm (including fingers) ≈ 1% TBSA',
      ],
      interpretation: 'Used to rapidly estimate TBSA for fluid resuscitation calculations. Only partial-thickness and full-thickness burns are included. Superficial (1st degree) burns are excluded.',
      normalized_claim: 'Rule of 9s: head 9%, each arm 9%, each leg 18%, anterior trunk 18%, posterior trunk 18%, perineum 1%. Palm = 1%. Exclude superficial burns from TBSA.',
      provenance: { section: 'Burn Assessment', page_or_location: 'Chapter 2' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ABA.BURNS.2016.T.01',
      display_id: 'ABA-T1',
      parameter: 'TBSA threshold for formal fluid resuscitation',
      value: '20',
      unit: '% TBSA',
      clinical_meaning: 'Burns ≥20% TBSA in adults require IV fluid resuscitation using the Parkland formula. Smaller burns can typically be managed with oral hydration.',
      normalized_claim: 'Burns ≥20% TBSA require Parkland formula IV resuscitation. Smaller burns managed with oral hydration.',
      direction: 'above',
      provenance: { section: 'Fluid Resuscitation', page_or_location: 'Chapter 4' },
    },
    {
      threshold_id: 'PACK.ABA.BURNS.2016.T.02',
      display_id: 'ABA-T2',
      parameter: 'Carboxyhemoglobin level for hyperbaric oxygen consideration',
      value: '25',
      unit: '%',
      clinical_meaning: 'COHb >25% is an indication for hyperbaric oxygen therapy in carbon monoxide poisoning. Also indicated for neurologic symptoms at any level.',
      normalized_claim: 'COHb >25% warrants hyperbaric oxygen therapy. Also indicated for neurologic symptoms regardless of level.',
      direction: 'above',
      provenance: { section: 'Inhalation Injury', page_or_location: 'Chapter 6' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ABA.BURNS.2016.TX.01',
      display_id: 'ABA-TX1',
      action: 'Parkland formula fluid resuscitation',
      normalized_claim: 'Burns ≥20% TBSA: 4 mL/kg/% TBSA of LR. Give half in first 8 hours from time of burn, remaining half over next 16 hours. Titrate to urine output 0.5-1 mL/kg/h.',
      timing: 'Begin immediately; first 8 hours calculated from time of burn injury',
      condition: 'Partial or full-thickness burns ≥20% TBSA',
      drug_details: { drug: 'Lactated Ringer solution', dose: '4 mL/kg/% TBSA', route: 'IV' },
      provenance: { section: 'Fluid Resuscitation', page_or_location: 'Chapter 4' },
    },
    {
      step_id: 'PACK.ABA.BURNS.2016.TX.02',
      display_id: 'ABA-TX2',
      action: 'Escharotomy for circumferential full-thickness burns',
      normalized_claim: 'Circumferential full-thickness burns of extremities or chest: escharotomy to relieve compartment syndrome or respiratory compromise. Incision through eschar to subcutaneous fat along medial/lateral aspects.',
      timing: 'Urgent — when compartment pressures rise or respiratory compromise develops',
      condition: 'Circumferential full-thickness burns with vascular compromise or respiratory restriction',
      provenance: { section: 'Escharotomy', page_or_location: 'Chapter 5' },
    },
    {
      step_id: 'PACK.ABA.BURNS.2016.TX.03',
      display_id: 'ABA-TX3',
      action: 'Carbon monoxide poisoning management',
      normalized_claim: 'CO poisoning: immediate 100% FiO2 via non-rebreather mask. Half-life of COHb: 4-6h on room air, 60-90 min on 100% O2, 20-30 min with hyperbaric O2.',
      timing: 'Immediately upon suspicion',
      condition: 'Suspected carbon monoxide exposure or inhalation injury',
      drug_details: { drug: 'Oxygen', dose: '100% FiO2', route: 'Non-rebreather mask' },
      provenance: { section: 'Inhalation Injury', page_or_location: 'Chapter 6' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ABA.BURNS.2016.RF.01',
      display_id: 'ABA-RF1',
      finding: 'Circumferential full-thickness burn of extremity with diminished distal pulses, paresthesias, or increasing pain',
      implication: 'Developing compartment syndrome from burn eschar constriction. Will progress to limb ischemia without intervention.',
      action: 'Emergent escharotomy. Incise through eschar along medial and lateral aspects of extremity. Assess distal perfusion post-procedure.',
      urgency: 'immediate',
      provenance: { section: 'Escharotomy', page_or_location: 'Chapter 5' },
    },
    {
      flag_id: 'PACK.ABA.BURNS.2016.RF.02',
      display_id: 'ABA-RF2',
      finding: 'Soot in oropharynx, singed nasal hairs, hoarseness, or stridor after burn/fire exposure',
      implication: 'Inhalation injury with progressive upper airway edema. Airway may become unmanageable within hours.',
      action: 'Early endotracheal intubation before airway edema progresses. Do not wait for respiratory failure. Check COHb. Begin 100% O2.',
      urgency: 'immediate',
      provenance: { section: 'Inhalation Injury', page_or_location: 'Chapter 6' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ABA.BURNS.2016.SEV.01',
      display_id: 'ABA-SEV1',
      level: 'Minor Burn',
      criteria: [
        'Partial-thickness <10% TBSA in adults (or <5% in very young/elderly)',
        'Full-thickness <2% TBSA',
        'No involvement of face, hands, feet, genitalia, or major joints',
        'No inhalation injury, electrical injury, or significant comorbidities',
      ],
      management_implications:
        'Outpatient management. Wound care with topical antimicrobials. Pain management. Tetanus prophylaxis. Follow-up in 24-48 hours.',
      provenance: { section: 'Classification', page_or_location: 'Chapter 2' },
    },
    {
      severity_id: 'PACK.ABA.BURNS.2016.SEV.02',
      display_id: 'ABA-SEV2',
      level: 'Major Burn',
      criteria: [
        'Partial-thickness >20% TBSA',
        'Full-thickness >5% TBSA',
        'Burns to face, hands, feet, genitalia, perineum, or major joints',
        'Inhalation injury',
        'Electrical or chemical burns',
        'Circumferential burns',
        'Significant comorbidities',
      ],
      management_implications:
        'Burn center referral required. Parkland formula resuscitation (4 mL/kg/% TBSA). Airway management for inhalation injury. Escharotomy for circumferential burns. Early excision and grafting for full-thickness burns.',
      provenance: { section: 'Referral Criteria', page_or_location: 'ABA Guidelines' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Surgery pack: Burns. Covers burn classification, TBSA rule of 9s, Parkland formula, burn center referral, escharotomy, inhalation injury, CO poisoning.',

  all_item_ids: [
    'PACK.ABA.BURNS.2016.REC.01', 'PACK.ABA.BURNS.2016.REC.02', 'PACK.ABA.BURNS.2016.REC.03',
    'PACK.ABA.BURNS.2016.DC.01', 'PACK.ABA.BURNS.2016.DC.02',
    'PACK.ABA.BURNS.2016.T.01', 'PACK.ABA.BURNS.2016.T.02',
    'PACK.ABA.BURNS.2016.TX.01', 'PACK.ABA.BURNS.2016.TX.02', 'PACK.ABA.BURNS.2016.TX.03',
    'PACK.ABA.BURNS.2016.RF.01', 'PACK.ABA.BURNS.2016.RF.02',
    'PACK.ABA.BURNS.2016.SEV.01', 'PACK.ABA.BURNS.2016.SEV.02',
  ],
  all_display_ids: [
    'ABA-R1', 'ABA-R2', 'ABA-R3',
    'ABA-DC1', 'ABA-DC2',
    'ABA-T1', 'ABA-T2',
    'ABA-TX1', 'ABA-TX2', 'ABA-TX3',
    'ABA-RF1', 'ABA-RF2',
    'ABA-SEV1', 'ABA-SEV2',
  ],
};
