import type { SourcePack } from './types';

export const PACK_ACCAHA_PAD_2016: SourcePack = {
  source_pack_id: 'PACK.ACCAHA.PAD.2016',
  source_name: 'AHA/ACC 2016 Guideline on the Management of Patients with Lower Extremity Peripheral Artery Disease',
  source_registry_id: 'REG.ACCAHA.PAD',
  canonical_url: 'https://doi.org/10.1161/CIR.0000000000000471',
  publication_year: 2016,
  guideline_body: 'AHA/ACC',

  topic_tags: ['Peripheral Artery Disease', 'Claudication', 'Critical Limb Ischemia', 'Acute Limb Ischemia', 'Vascular Surgery'],
  allowed_decision_scopes: [
    'PAD diagnosis with ABI',
    'claudication management (exercise, pharmacotherapy)',
    'critical limb ischemia recognition and revascularization',
    'acute limb ischemia classification and management',
    'PAD risk factor modification',
    'antiplatelet therapy for PAD',
  ],
  excluded_decision_scopes: [
    'carotid artery disease management',
    'renal artery stenosis',
    'mesenteric ischemia',
    'aortic aneurysm management',
    'venous disease',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ACCAHA.PAD.2016.REC.01',
      display_id: 'ACCAHA-PAD-R1',
      statement: 'Ankle-brachial index (ABI) is recommended as the first-line noninvasive test for diagnosis of PAD in patients with exertional leg symptoms or non-healing wounds.',
      normalized_claim: 'ABI is the first-line diagnostic test for PAD. ABI <=0.90 confirms PAD diagnosis.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Diagnosis', page_or_location: 'Section 3.1' },
    },
    {
      rec_id: 'PACK.ACCAHA.PAD.2016.REC.02',
      display_id: 'ACCAHA-PAD-R2',
      statement: 'Supervised exercise therapy (SET) is recommended as first-line treatment for claudication. Sessions should be >=30 minutes, >=3 times per week, for >=12 weeks.',
      normalized_claim: 'Supervised exercise therapy is first-line for claudication: >=30min sessions, >=3x/week, >=12 weeks.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Claudication — Exercise', page_or_location: 'Section 4.1' },
    },
    {
      rec_id: 'PACK.ACCAHA.PAD.2016.REC.03',
      display_id: 'ACCAHA-PAD-R3',
      statement: 'Cilostazol (100mg BID) is recommended to improve symptoms and walking distance in patients with claudication who do not have heart failure.',
      normalized_claim: 'Cilostazol 100mg BID improves claudication symptoms. Contraindicated in heart failure (PDE3 inhibitor).',
      strength: 'strong',
      evidence_quality: 'moderate',
      context: 'Contraindicated in heart failure of any severity (PDE3 inhibitor)',
      provenance: { section: 'Claudication — Pharmacotherapy', page_or_location: 'Section 4.2' },
    },
    {
      rec_id: 'PACK.ACCAHA.PAD.2016.REC.04',
      display_id: 'ACCAHA-PAD-R4',
      statement: 'Antiplatelet therapy with aspirin (75-325mg daily) or clopidogrel (75mg daily) is recommended for patients with symptomatic PAD to reduce cardiovascular events.',
      normalized_claim: 'Symptomatic PAD: antiplatelet therapy (aspirin or clopidogrel) to reduce MI, stroke, and vascular death.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Medical Therapy', page_or_location: 'Section 3.3' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ACCAHA.PAD.2016.DC.01',
      display_id: 'ACCAHA-PAD-DC1',
      name: 'ABI Interpretation for PAD',
      components: [
        'Normal: ABI 1.00-1.40',
        'Borderline: ABI 0.91-0.99',
        'Abnormal (PAD): ABI <=0.90',
        'Non-compressible (calcified): ABI >1.40 — obtain toe-brachial index (TBI)',
        'TBI <0.70 is abnormal and suggests PAD despite elevated ABI',
      ],
      threshold: 'ABI <=0.90 diagnostic of PAD',
      interpretation: 'Resting ABI <=0.90 has sensitivity ~95% and specificity ~99% for angiographically confirmed PAD. If resting ABI is normal but suspicion remains, exercise ABI is recommended.',
      normalized_claim: 'ABI <=0.90 diagnoses PAD (sensitivity 95%, specificity 99%). ABI >1.40 = non-compressible, use TBI.',
      provenance: { section: 'Diagnosis — ABI', page_or_location: 'Table 2' },
    },
    {
      criterion_id: 'PACK.ACCAHA.PAD.2016.DC.02',
      display_id: 'ACCAHA-PAD-DC2',
      name: 'Acute Limb Ischemia (Rutherford Classification)',
      components: [
        'Class I (Viable): no sensory loss, no muscle weakness, audible arterial and venous Doppler — not immediately threatened',
        'Class IIa (Marginally threatened): minimal sensory loss (toes), no muscle weakness, often inaudible arterial Doppler, audible venous Doppler — salvageable with prompt treatment',
        'Class IIb (Immediately threatened): sensory loss beyond toes, mild-moderate muscle weakness, usually inaudible arterial Doppler, audible venous Doppler — salvageable with immediate revascularization',
        'Class III (Irreversible): profound sensory loss, paralysis, inaudible arterial and venous Doppler — major tissue loss or amputation inevitable',
      ],
      interpretation: 'Class I: observe, anticoagulate. Class IIa: urgent revascularization. Class IIb: emergent revascularization. Class III: amputation, revascularization futile.',
      normalized_claim: 'ALI classification: I (viable, non-urgent), IIa (marginally threatened, urgent revasc), IIb (immediately threatened, emergent revasc), III (irreversible, amputation).',
      provenance: { section: 'Acute Limb Ischemia', page_or_location: 'Table 6' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ACCAHA.PAD.2016.T.01',
      display_id: 'ACCAHA-PAD-T1',
      parameter: 'ABI diagnostic cutoff for PAD',
      value: '0.90',
      clinical_meaning: 'ABI <=0.90 confirms the diagnosis of peripheral artery disease. Lower ABI values correlate with more severe disease and higher cardiovascular mortality.',
      normalized_claim: 'ABI <=0.90 = PAD. Lower ABI = more severe disease and higher CV mortality.',
      direction: 'below',
      provenance: { section: 'Diagnosis', page_or_location: 'Section 3.1' },
    },
    {
      threshold_id: 'PACK.ACCAHA.PAD.2016.T.02',
      display_id: 'ACCAHA-PAD-T2',
      parameter: 'ABI cutoff for non-compressible arteries',
      value: '1.40',
      clinical_meaning: 'ABI >1.40 indicates non-compressible, calcified arteries (common in diabetes and CKD). Toe-brachial index (TBI) should be used instead.',
      normalized_claim: 'ABI >1.40 = non-compressible arteries. Use toe-brachial index (TBI <0.70 abnormal) in diabetes/CKD.',
      direction: 'above',
      provenance: { section: 'Diagnosis', page_or_location: 'Section 3.1' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ACCAHA.PAD.2016.TX.01',
      display_id: 'ACCAHA-PAD-TX1',
      action: 'Medical management of claudication: exercise + cilostazol + risk factor modification',
      normalized_claim: 'Claudication first-line: supervised exercise therapy + cilostazol 100mg BID + statin + antiplatelet + smoking cessation.',
      timing: 'At diagnosis of symptomatic PAD',
      condition: 'Intermittent claudication (Fontaine II / Rutherford 1-3)',
      drug_details: { drug: 'Cilostazol', dose: '100mg BID', route: 'PO' },
      contraindications: ['Heart failure (cilostazol contraindicated)'],
      escalation: 'Revascularization if disabling claudication despite medical therapy',
      provenance: { section: 'Claudication Management', page_or_location: 'Section 4' },
    },
    {
      step_id: 'PACK.ACCAHA.PAD.2016.TX.02',
      display_id: 'ACCAHA-PAD-TX2',
      action: 'Revascularization for critical limb ischemia (CLI)',
      normalized_claim: 'CLI (rest pain, tissue loss, gangrene): revascularization is first-line. Endovascular preferred for short-segment disease; surgical bypass for long-segment or failed endovascular.',
      timing: 'Urgent upon diagnosis of CLI',
      condition: 'Critical limb ischemia (Fontaine III-IV / Rutherford 4-6)',
      escalation: 'Amputation if revascularization not feasible or failed',
      provenance: { section: 'Critical Limb Ischemia', page_or_location: 'Section 5' },
    },
    {
      step_id: 'PACK.ACCAHA.PAD.2016.TX.03',
      display_id: 'ACCAHA-PAD-TX3',
      action: 'Emergent management of acute limb ischemia',
      normalized_claim: 'Acute limb ischemia (6 P\'s: Pain, Pallor, Pulselessness, Paresthesias, Paralysis, Poikilothermia): immediate anticoagulation with heparin + emergent revascularization (surgical embolectomy or catheter-directed thrombolysis).',
      timing: 'Emergent — within hours to prevent limb loss',
      condition: 'Acute limb ischemia (Rutherford class IIa or IIb)',
      drug_details: { drug: 'Unfractionated heparin', dose: 'IV bolus + infusion', route: 'IV' },
      provenance: { section: 'Acute Limb Ischemia', page_or_location: 'Section 6' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ACCAHA.PAD.2016.RF.01',
      display_id: 'ACCAHA-PAD-RF1',
      finding: 'Acute onset of the 6 P\'s: Pain, Pallor, Pulselessness, Paresthesias, Paralysis, Poikilothermia in a limb',
      implication: 'Acute limb ischemia — limb viability threatened. Without emergent revascularization, irreversible tissue death within 6 hours.',
      action: 'Immediate systemic anticoagulation with IV heparin. Emergent vascular surgery consultation. Determine Rutherford class to guide intervention.',
      urgency: 'immediate',
      provenance: { section: 'Acute Limb Ischemia', page_or_location: 'Section 6.1' },
    },
    {
      flag_id: 'PACK.ACCAHA.PAD.2016.RF.02',
      display_id: 'ACCAHA-PAD-RF2',
      finding: 'Rest pain in the forefoot/toes, worse when supine, improved by dependency (dangling leg over bedside)',
      implication: 'Rest pain indicates critical limb ischemia (Fontaine Stage III). High risk of tissue loss and amputation without revascularization.',
      action: 'Urgent vascular evaluation with ABI, duplex ultrasound, and angiography. Plan for revascularization.',
      urgency: 'urgent',
      provenance: { section: 'Critical Limb Ischemia', page_or_location: 'Section 5.1' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ACCAHA.PAD.2016.SEV.01',
      display_id: 'ACCAHA-PAD-SEV1',
      level: 'Intermittent claudication (Fontaine II)',
      criteria: [
        'Exertional calf, thigh, or buttock pain that occurs with walking',
        'Pain relieved by rest within 2-5 minutes',
        'No rest pain, no tissue loss',
        'ABI typically 0.40-0.90',
      ],
      management_implications:
        'Medical management first: supervised exercise, cilostazol, risk factor modification (statin, antiplatelet, smoking cessation). Revascularization reserved for lifestyle-limiting claudication despite optimal medical therapy.',
      provenance: { section: 'Claudication', page_or_location: 'Section 4' },
    },
    {
      severity_id: 'PACK.ACCAHA.PAD.2016.SEV.02',
      display_id: 'ACCAHA-PAD-SEV2',
      level: 'Critical limb ischemia (Fontaine III-IV)',
      criteria: [
        'Rest pain (Fontaine III / Rutherford 4): ischemic pain at rest, worse with elevation, improved with dependency',
        'Tissue loss (Fontaine IV / Rutherford 5-6): non-healing ulcers or gangrene',
        'ABI typically <0.40 or absolute ankle pressure <50mmHg',
      ],
      management_implications:
        'Limb-threatening condition. Urgent revascularization (endovascular or surgical bypass) is primary treatment. Amputation if revascularization not feasible. 1-year amputation rate ~25% and mortality ~25% without intervention.',
      provenance: { section: 'Critical Limb Ischemia', page_or_location: 'Section 5' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for PAD. Covers ABI diagnosis, claudication management, CLI revascularization, and acute limb ischemia classification.',

  all_item_ids: [
    'PACK.ACCAHA.PAD.2016.REC.01', 'PACK.ACCAHA.PAD.2016.REC.02', 'PACK.ACCAHA.PAD.2016.REC.03',
    'PACK.ACCAHA.PAD.2016.REC.04',
    'PACK.ACCAHA.PAD.2016.DC.01', 'PACK.ACCAHA.PAD.2016.DC.02',
    'PACK.ACCAHA.PAD.2016.T.01', 'PACK.ACCAHA.PAD.2016.T.02',
    'PACK.ACCAHA.PAD.2016.TX.01', 'PACK.ACCAHA.PAD.2016.TX.02', 'PACK.ACCAHA.PAD.2016.TX.03',
    'PACK.ACCAHA.PAD.2016.RF.01', 'PACK.ACCAHA.PAD.2016.RF.02',
    'PACK.ACCAHA.PAD.2016.SEV.01', 'PACK.ACCAHA.PAD.2016.SEV.02',
  ],
  all_display_ids: [
    'ACCAHA-PAD-R1', 'ACCAHA-PAD-R2', 'ACCAHA-PAD-R3', 'ACCAHA-PAD-R4',
    'ACCAHA-PAD-DC1', 'ACCAHA-PAD-DC2',
    'ACCAHA-PAD-T1', 'ACCAHA-PAD-T2',
    'ACCAHA-PAD-TX1', 'ACCAHA-PAD-TX2', 'ACCAHA-PAD-TX3',
    'ACCAHA-PAD-RF1', 'ACCAHA-PAD-RF2',
    'ACCAHA-PAD-SEV1', 'ACCAHA-PAD-SEV2',
  ],
};
