import type { SourcePack } from './types';

export const PACK_ACCAHA_HF_2022: SourcePack = {
  source_pack_id: 'PACK.ACCAHA.HF.2022',
  source_name: '2022 AHA/ACC/HFSA Guideline for Management of Heart Failure',
  canonical_url: 'https://doi.org/10.1161/CIR.0000000000001063',
  publication_year: 2022,
  guideline_body: 'ACC/AHA/HFSA',

  topic_tags: ['Heart Failure', 'HFrEF', 'HFpEF', 'HFmrEF', 'GDMT', 'Acute Decompensated HF', 'Cardiology'],
  allowed_decision_scopes: [
    'HFrEF GDMT initiation and titration',
    'ARNi vs ACEi selection',
    'diuretic management for congestion',
    'ICD primary prevention in HFrEF',
    'CRT device selection',
    'acute decompensated HF management',
    'hemodynamic profile-guided therapy',
    'SGLT2i initiation in HF',
    'MRA initiation in HFrEF',
    'NYHA classification and staging',
  ],
  excluded_decision_scopes: [
    'valvular heart disease management',
    'congenital heart disease',
    'cardiac transplant evaluation',
    'LVAD management',
    'ACS management',
    'pulmonary hypertension treatment',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ACCAHA.HF.2022.REC.01',
      display_id: 'ACCAHA-HF-R1',
      statement: 'In patients with HFrEF (LVEF <=40%), GDMT should include an ARNi (or ACEi/ARB if ARNi not tolerated), evidence-based beta-blocker, MRA, and SGLT2 inhibitor to reduce morbidity and mortality.',
      normalized_claim: 'HFrEF quadruple therapy: ARNi (or ACEi/ARB) + beta-blocker + MRA + SGLT2i for all patients with LVEF <=40%.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'Applies to all HFrEF patients regardless of etiology',
      population: 'Adults with HFrEF (LVEF <=40%)',
      provenance: { section: 'Pharmacological Treatment of HFrEF', page_or_location: 'Section 7.3.2' },
    },
    {
      rec_id: 'PACK.ACCAHA.HF.2022.REC.02',
      display_id: 'ACCAHA-HF-R2',
      statement: 'In patients with HFrEF, ARNi is recommended in preference to ACEi or ARB to further reduce morbidity and mortality.',
      normalized_claim: 'ARNi (sacubitril-valsartan) preferred over ACEi/ARB in HFrEF. Requires 36h ACEi washout before starting ARNi.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'RAAS Inhibition', page_or_location: 'Section 7.3.2.1' },
    },
    {
      rec_id: 'PACK.ACCAHA.HF.2022.REC.03',
      display_id: 'ACCAHA-HF-R3',
      statement: 'Diuretics are recommended in patients with HF and fluid overload to relieve congestion, improve symptoms, and prevent worsening HF.',
      normalized_claim: 'Loop diuretics (furosemide, bumetanide, torsemide) for volume management in HF. Titrate to euvolemia; not mortality-reducing agents.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Diuretic Therapy', page_or_location: 'Section 7.3.1' },
    },
    {
      rec_id: 'PACK.ACCAHA.HF.2022.REC.04',
      display_id: 'ACCAHA-HF-R4',
      statement: 'ICD therapy is recommended for primary prevention of sudden cardiac death in patients with HFrEF (LVEF <=35%) who are on optimal GDMT for at least 3 months and have a life expectancy >1 year.',
      normalized_claim: 'ICD for primary prevention when LVEF <=35% on >=3 months optimal GDMT, NYHA II-III, life expectancy >1 year.',
      strength: 'strong',
      evidence_quality: 'high',
      population: 'HFrEF patients with LVEF <=35%, NYHA class II-III',
      provenance: { section: 'Device Therapy', page_or_location: 'Section 7.4.1' },
    },
    {
      rec_id: 'PACK.ACCAHA.HF.2022.REC.05',
      display_id: 'ACCAHA-HF-R5',
      statement: 'CRT is recommended for patients with HFrEF (LVEF <=35%), sinus rhythm, LBBB with QRS duration >=150ms, and NYHA class II-IV symptoms on optimal GDMT.',
      normalized_claim: 'CRT indicated for LVEF <=35% + LBBB + QRS >=150ms + sinus rhythm + NYHA II-IV on GDMT. Greatest benefit with LBBB and QRS >=150ms.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'CRT Therapy', page_or_location: 'Section 7.4.2' },
    },
    {
      rec_id: 'PACK.ACCAHA.HF.2022.REC.06',
      display_id: 'ACCAHA-HF-R6',
      statement: 'In patients with HFpEF, SGLT2 inhibitors are recommended to decrease HF hospitalizations and cardiovascular mortality.',
      normalized_claim: 'SGLT2i (dapagliflozin or empagliflozin) recommended for HFpEF to reduce HF hospitalization and CV mortality.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Treatment of HFpEF', page_or_location: 'Section 7.5' },
    },
    {
      rec_id: 'PACK.ACCAHA.HF.2022.REC.07',
      display_id: 'ACCAHA-HF-R7',
      statement: 'In patients with HFrEF, the combination of hydralazine and isosorbide dinitrate is recommended to reduce morbidity and mortality in self-identified African Americans already on optimal GDMT.',
      normalized_claim: 'Hydralazine-isosorbide dinitrate added to GDMT in self-identified African American patients with HFrEF NYHA III-IV.',
      strength: 'strong',
      evidence_quality: 'moderate',
      population: 'Self-identified African American patients with HFrEF',
      provenance: { section: 'Vasodilator Therapy', page_or_location: 'Section 7.3.2.5' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ACCAHA.HF.2022.DC.01',
      display_id: 'ACCAHA-HF-DC1',
      name: 'Heart Failure Classification by LVEF',
      components: [
        'HFrEF: LVEF <=40% (heart failure with reduced ejection fraction)',
        'HFmrEF: LVEF 41-49% (heart failure with mildly reduced ejection fraction)',
        'HFpEF: LVEF >=50% (heart failure with preserved ejection fraction)',
        'HFimpEF: Previous LVEF <=40% with follow-up LVEF >40% (improved EF)',
      ],
      interpretation: 'LVEF classification determines GDMT eligibility. HFrEF has strongest evidence for quadruple therapy. HFpEF and HFmrEF benefit from SGLT2i.',
      normalized_claim: 'HF classified by LVEF: HFrEF <=40%, HFmrEF 41-49%, HFpEF >=50%. Classification drives therapy selection.',
      provenance: { section: 'Definition and Classification', page_or_location: 'Section 2' },
    },
    {
      criterion_id: 'PACK.ACCAHA.HF.2022.DC.02',
      display_id: 'ACCAHA-HF-DC2',
      name: 'NYHA Functional Classification',
      components: [
        'Class I: No limitation of physical activity; ordinary activity does not cause symptoms',
        'Class II: Slight limitation; comfortable at rest, ordinary activity causes symptoms',
        'Class III: Marked limitation; comfortable at rest, less than ordinary activity causes symptoms',
        'Class IV: Unable to carry on any physical activity without discomfort; symptoms at rest',
      ],
      interpretation: 'NYHA class guides device therapy eligibility and prognosis. Class III-IV indicates advanced HF requiring escalation of care.',
      normalized_claim: 'NYHA I-IV classification grades functional limitation. Class II-III required for ICD. Class III-IV associated with highest mortality.',
      provenance: { section: 'Classification', page_or_location: 'Section 2.2' },
    },
    {
      criterion_id: 'PACK.ACCAHA.HF.2022.DC.03',
      display_id: 'ACCAHA-HF-DC3',
      name: 'Stevenson Hemodynamic Profiles',
      components: [
        'Warm-Dry (Profile A): Adequate perfusion, no congestion — goal of therapy',
        'Warm-Wet (Profile B): Adequate perfusion + congestion — most common ADHF presentation',
        'Cold-Dry (Profile L): Hypoperfusion without congestion — may need volume + inotropes',
        'Cold-Wet (Profile C): Hypoperfusion + congestion — worst prognosis, consider inotropes + diuretics',
      ],
      interpretation: 'Hemodynamic profiles guide acute HF management. "Warm" vs "Cold" = perfusion status. "Dry" vs "Wet" = congestion status.',
      normalized_claim: 'Stevenson profiles classify ADHF by perfusion (warm/cold) and congestion (dry/wet). Warm-wet most common; cold-wet worst prognosis.',
      provenance: { section: 'Acute Decompensated Heart Failure', page_or_location: 'Section 8.1' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ACCAHA.HF.2022.T.01',
      display_id: 'ACCAHA-HF-T1',
      parameter: 'LVEF for HFrEF diagnosis',
      value: '40',
      unit: '%',
      clinical_meaning: 'LVEF <=40% defines HFrEF and qualifies patient for full quadruple GDMT therapy.',
      normalized_claim: 'LVEF <=40% = HFrEF, qualifying for ARNi + beta-blocker + MRA + SGLT2i.',
      direction: 'below',
      provenance: { section: 'Definition', page_or_location: 'Section 2' },
    },
    {
      threshold_id: 'PACK.ACCAHA.HF.2022.T.02',
      display_id: 'ACCAHA-HF-T2',
      parameter: 'LVEF for ICD primary prevention',
      value: '35',
      unit: '%',
      clinical_meaning: 'LVEF <=35% after >=3 months of optimal GDMT is the threshold for ICD implantation for primary prevention of sudden cardiac death.',
      normalized_claim: 'LVEF <=35% on >=3 months GDMT triggers ICD evaluation for primary SCD prevention.',
      direction: 'below',
      provenance: { section: 'Device Therapy', page_or_location: 'Section 7.4.1' },
    },
    {
      threshold_id: 'PACK.ACCAHA.HF.2022.T.03',
      display_id: 'ACCAHA-HF-T3',
      parameter: 'BNP for HF diagnosis',
      value: '100',
      unit: 'pg/mL',
      clinical_meaning: 'BNP >100 pg/mL supports diagnosis of heart failure in acute dyspnea. NT-proBNP >300 pg/mL is the equivalent threshold.',
      normalized_claim: 'BNP >100 pg/mL or NT-proBNP >300 pg/mL supports HF diagnosis in acute dyspnea. Age-adjusted cutoffs for NT-proBNP.',
      direction: 'above',
      provenance: { section: 'Biomarkers', page_or_location: 'Section 4.3' },
    },
    {
      threshold_id: 'PACK.ACCAHA.HF.2022.T.04',
      display_id: 'ACCAHA-HF-T4',
      parameter: 'QRS duration for CRT',
      value: '150',
      unit: 'ms',
      clinical_meaning: 'QRS >=150ms with LBBB morphology is the strongest indication for CRT. QRS 120-149ms with LBBB is a weaker indication.',
      normalized_claim: 'QRS >=150ms + LBBB = strongest CRT indication (Class I). QRS 120-149ms + LBBB = Class IIa.',
      direction: 'above',
      provenance: { section: 'CRT Indications', page_or_location: 'Section 7.4.2' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ACCAHA.HF.2022.TX.01',
      display_id: 'ACCAHA-HF-TX1',
      action: 'Initiate quadruple GDMT for HFrEF',
      normalized_claim: 'Start all 4 pillars simultaneously or in rapid sequence: ARNi + beta-blocker + MRA + SGLT2i. Do not wait to titrate one before starting another.',
      timing: 'At diagnosis of HFrEF; initiate all 4 agents simultaneously or within 1-2 weeks',
      condition: 'HFrEF (LVEF <=40%)',
      contraindications: ['Hyperkalemia (K >5.0 for MRA)', 'eGFR <20 for MRA', 'SBP <100 for ARNi initiation', 'Severe bronchospasm for beta-blocker'],
      escalation: 'Titrate each agent to target dose over 2-4 weeks as tolerated',
      provenance: { section: 'GDMT Initiation', page_or_location: 'Section 7.3.2' },
    },
    {
      step_id: 'PACK.ACCAHA.HF.2022.TX.02',
      display_id: 'ACCAHA-HF-TX2',
      action: 'Acute decompensated HF: Warm-Wet (Profile B) management',
      normalized_claim: 'Warm-wet profile: IV loop diuretics first-line. Add IV vasodilators (nitroprusside, nitroglycerin) if persistent HTN. Target net negative fluid balance.',
      timing: 'Immediate upon admission',
      condition: 'Hemodynamic profile: warm and wet (adequate perfusion + congestion)',
      drug_details: { drug: 'Furosemide', dose: 'IV bolus: 1-2.5x home oral dose or 40mg if diuretic-naive', route: 'IV' },
      escalation: 'If inadequate response: double IV dose, add metolazone 2.5-5mg PO, or continuous drip',
      provenance: { section: 'Acute HF Management', page_or_location: 'Section 8.2' },
    },
    {
      step_id: 'PACK.ACCAHA.HF.2022.TX.03',
      display_id: 'ACCAHA-HF-TX3',
      action: 'Acute decompensated HF: Cold-Wet (Profile C) management',
      normalized_claim: 'Cold-wet profile: IV inotropes (dobutamine or milrinone) for perfusion support + cautious diuresis. Consider mechanical circulatory support if refractory.',
      timing: 'Immediate upon recognition of cold-wet hemodynamics',
      condition: 'Hemodynamic profile: cold and wet (hypoperfusion + congestion)',
      drug_details: { drug: 'Dobutamine', dose: '2-20 mcg/kg/min', route: 'IV continuous infusion' },
      contraindications: ['Milrinone use with caution in renal failure'],
      escalation: 'Mechanical circulatory support (IABP, Impella) if inotrope-refractory',
      provenance: { section: 'Cardiogenic Shock in HF', page_or_location: 'Section 8.3' },
    },
    {
      step_id: 'PACK.ACCAHA.HF.2022.TX.04',
      display_id: 'ACCAHA-HF-TX4',
      action: 'Transition from ACEi to ARNi',
      normalized_claim: 'Mandatory 36-hour washout from ACEi before starting ARNi (sacubitril-valsartan) to avoid angioedema risk. No washout needed from ARB.',
      timing: 'After hemodynamic stabilization; 36h washout from last ACEi dose',
      condition: 'Patient on ACEi tolerating therapy, transitioning to ARNi for superior outcomes',
      contraindications: ['History of angioedema', 'Pregnancy', 'Concurrent ACEi use'],
      drug_details: { drug: 'Sacubitril-valsartan', dose: 'Start 24/26mg BID if on low-dose ACEi; 49/51mg BID if on high-dose', route: 'PO' },
      provenance: { section: 'ARNi Therapy', page_or_location: 'Section 7.3.2.1' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ACCAHA.HF.2022.RF.01',
      display_id: 'ACCAHA-HF-RF1',
      finding: 'Cardiogenic shock (cold-wet profile): SBP <90mmHg, altered mental status, cool extremities, oliguria, elevated lactate with pulmonary congestion',
      implication: 'Highest mortality hemodynamic profile in ADHF. Requires ICU-level care and invasive hemodynamic monitoring.',
      action: 'IV inotropes (dobutamine first-line), vasopressors if persistent hypotension (norepinephrine), consider mechanical circulatory support. Urgent cardiology/cardiac surgery consultation.',
      urgency: 'immediate',
      provenance: { section: 'Cardiogenic Shock', page_or_location: 'Section 8.3' },
    },
    {
      flag_id: 'PACK.ACCAHA.HF.2022.RF.02',
      display_id: 'ACCAHA-HF-RF2',
      finding: 'Refractory volume overload: Persistent congestion despite high-dose IV diuretics (furosemide >=160mg IV or equivalent)',
      implication: 'Diuretic resistance suggests cardiorenal syndrome or right heart failure. Associated with poor prognosis.',
      action: 'Add sequential nephron blockade (metolazone or chlorothiazide), consider continuous furosemide infusion, ultrafiltration for refractory cases.',
      urgency: 'urgent',
      provenance: { section: 'Diuretic Resistance', page_or_location: 'Section 8.2.3' },
    },
    {
      flag_id: 'PACK.ACCAHA.HF.2022.RF.03',
      display_id: 'ACCAHA-HF-RF3',
      finding: 'Worsening renal function on diuretics: Creatinine rise >0.3 mg/dL with persistent congestion',
      implication: 'Cardiorenal syndrome type 1. Do NOT stop diuretics if patient remains congested — persistent congestion is more harmful than transient creatinine rise.',
      action: 'Continue diuresis if congested (hemoconcentration-associated creatinine rise is acceptable). Reduce diuretics only if hypovolemic. Monitor potassium and electrolytes closely.',
      urgency: 'urgent',
      provenance: { section: 'Cardiorenal Syndrome', page_or_location: 'Section 8.4' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ACCAHA.HF.2022.SEV.01',
      display_id: 'ACCAHA-HF-SEV1',
      level: 'NYHA Class I-II (Mild)',
      criteria: [
        'No or slight limitation of physical activity',
        'Comfortable at rest',
        'Ordinary physical activity causes fatigue, dyspnea, or palpitations (Class II)',
        'No symptoms with ordinary activity (Class I)',
      ],
      management_implications:
        'Initiate and titrate GDMT to target doses. ICD evaluation if LVEF <=35% on >=3 months of GDMT. Regular follow-up every 3-6 months. Cardiac rehabilitation. Sodium restriction <1500mg/day.',
      provenance: { section: 'NYHA Classification', page_or_location: 'Section 2.2' },
    },
    {
      severity_id: 'PACK.ACCAHA.HF.2022.SEV.02',
      display_id: 'ACCAHA-HF-SEV2',
      level: 'NYHA Class III-IV (Severe/Advanced)',
      criteria: [
        'Marked limitation of activity (Class III) or symptoms at rest (Class IV)',
        'Less than ordinary activity causes symptoms',
        'Recurrent hospitalizations for HF',
        'Inability to tolerate GDMT due to hypotension or renal dysfunction',
      ],
      management_implications:
        'Maximize GDMT if tolerated. Evaluate for advanced therapies: CRT, LVAD, or cardiac transplantation. Consider palliative care consultation. Add hydralazine-isosorbide dinitrate in African American patients. More frequent monitoring (every 1-3 months).',
      provenance: { section: 'Advanced Heart Failure', page_or_location: 'Section 9' },
    },
    {
      severity_id: 'PACK.ACCAHA.HF.2022.SEV.03',
      display_id: 'ACCAHA-HF-SEV3',
      level: 'Stevenson Profile C (Cold-Wet)',
      criteria: [
        'Signs of hypoperfusion: cool extremities, altered mentation, narrow pulse pressure, oliguria',
        'Signs of congestion: JVD, peripheral edema, pulmonary rales, hepatomegaly',
        'Low cardiac index (<2.2 L/min/m2)',
        'Elevated PCWP (>18 mmHg)',
      ],
      management_implications:
        'ICU admission. Inotropic support (dobutamine or milrinone). Cautious diuresis — avoid volume depletion. Consider PA catheter for hemodynamic monitoring. Evaluate for mechanical circulatory support. Highest in-hospital mortality of all profiles.',
      provenance: { section: 'Hemodynamic Profiles', page_or_location: 'Section 8.1' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for Heart Failure. Covers HFrEF GDMT, LVEF-based classification, hemodynamic profiles, acute decompensated HF management, and device therapy indications.',

  all_item_ids: [
    'PACK.ACCAHA.HF.2022.REC.01', 'PACK.ACCAHA.HF.2022.REC.02', 'PACK.ACCAHA.HF.2022.REC.03',
    'PACK.ACCAHA.HF.2022.REC.04', 'PACK.ACCAHA.HF.2022.REC.05', 'PACK.ACCAHA.HF.2022.REC.06',
    'PACK.ACCAHA.HF.2022.REC.07', 'PACK.ACCAHA.HF.2022.DC.01', 'PACK.ACCAHA.HF.2022.DC.02',
    'PACK.ACCAHA.HF.2022.DC.03', 'PACK.ACCAHA.HF.2022.T.01', 'PACK.ACCAHA.HF.2022.T.02',
    'PACK.ACCAHA.HF.2022.T.03', 'PACK.ACCAHA.HF.2022.T.04', 'PACK.ACCAHA.HF.2022.TX.01',
    'PACK.ACCAHA.HF.2022.TX.02', 'PACK.ACCAHA.HF.2022.TX.03', 'PACK.ACCAHA.HF.2022.TX.04',
    'PACK.ACCAHA.HF.2022.RF.01', 'PACK.ACCAHA.HF.2022.RF.02', 'PACK.ACCAHA.HF.2022.RF.03',
    'PACK.ACCAHA.HF.2022.SEV.01', 'PACK.ACCAHA.HF.2022.SEV.02', 'PACK.ACCAHA.HF.2022.SEV.03',
  ],
  all_display_ids: [
    'ACCAHA-HF-R1', 'ACCAHA-HF-R2', 'ACCAHA-HF-R3', 'ACCAHA-HF-R4', 'ACCAHA-HF-R5', 'ACCAHA-HF-R6', 'ACCAHA-HF-R7',
    'ACCAHA-HF-DC1', 'ACCAHA-HF-DC2', 'ACCAHA-HF-DC3',
    'ACCAHA-HF-T1', 'ACCAHA-HF-T2', 'ACCAHA-HF-T3', 'ACCAHA-HF-T4',
    'ACCAHA-HF-TX1', 'ACCAHA-HF-TX2', 'ACCAHA-HF-TX3', 'ACCAHA-HF-TX4',
    'ACCAHA-HF-RF1', 'ACCAHA-HF-RF2', 'ACCAHA-HF-RF3',
    'ACCAHA-HF-SEV1', 'ACCAHA-HF-SEV2', 'ACCAHA-HF-SEV3',
  ],
};
