import type { SourcePack } from './types';

export const PACK_ACCAHA_SYNC_2017: SourcePack = {
  source_pack_id: 'PACK.ACCAHA.SYNC.2017',
  source_name: '2017 ACC/AHA/HRS Guideline for the Evaluation and Management of Patients with Syncope',
  canonical_url: 'https://doi.org/10.1161/CIR.0000000000000499',
  publication_year: 2017,
  guideline_body: 'ACC/AHA/HRS',

  topic_tags: ['Syncope', 'Vasovagal Syncope', 'Cardiac Syncope', 'Orthostatic Hypotension', 'Risk Stratification', 'Cardiology', 'Emergency Medicine'],
  allowed_decision_scopes: [
    'syncope initial evaluation',
    'syncope risk stratification',
    'vasovagal syncope diagnosis and management',
    'orthostatic hypotension diagnosis and management',
    'cardiac syncope workup',
    'tilt table testing indications',
    'syncope disposition (admit vs discharge)',
    'ECG interpretation in syncope',
    'implantable loop recorder indications',
  ],
  excluded_decision_scopes: [
    'seizure evaluation and management',
    'arrhythmia-specific drug therapy',
    'pacemaker/ICD programming',
    'structural heart disease treatment beyond syncope evaluation',
    'psychogenic pseudosyncope management',
    'autonomic neuropathy treatment beyond orthostatic management',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ACCAHA.SYNC.2017.REC.01',
      display_id: 'ACCAHA-SYNC-R1',
      statement: 'Initial evaluation of syncope should include a detailed history, physical examination (including orthostatic vital signs), and 12-lead ECG. These three components are sufficient to establish a diagnosis or guide further testing in the majority of patients.',
      normalized_claim: 'Syncope initial workup = focused history + physical exam + orthostatic vitals + 12-lead ECG. This identifies the cause in most patients.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Initial Evaluation', page_or_location: 'Section 5.1' },
    },
    {
      rec_id: 'PACK.ACCAHA.SYNC.2017.REC.02',
      display_id: 'ACCAHA-SYNC-R2',
      statement: 'Risk stratification should be performed in all patients with syncope to identify those at risk for serious adverse events. High-risk features include syncope during exertion, abnormal ECG, structural heart disease, family history of sudden cardiac death, and absence of prodrome.',
      normalized_claim: 'All syncope patients require risk stratification. High-risk: exertional syncope, abnormal ECG, structural heart disease, family hx SCD, no prodrome.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 6.1' },
    },
    {
      rec_id: 'PACK.ACCAHA.SYNC.2017.REC.03',
      display_id: 'ACCAHA-SYNC-R3',
      statement: 'Echocardiography is recommended when cardiac syncope is suspected based on history, examination, or ECG findings. It is not recommended as a routine test for all syncope patients.',
      normalized_claim: 'Echocardiogram for suspected cardiac syncope (abnormal ECG, murmur, exertional syncope). Not routine for all syncope.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Cardiac Evaluation', page_or_location: 'Section 7.2' },
    },
    {
      rec_id: 'PACK.ACCAHA.SYNC.2017.REC.04',
      display_id: 'ACCAHA-SYNC-R4',
      statement: 'Tilt table testing can be useful for patients with suspected vasovagal syncope when the diagnosis is uncertain after initial evaluation, particularly for recurrent episodes impacting quality of life.',
      normalized_claim: 'Tilt table testing for recurrent suspected vasovagal syncope when diagnosis remains uncertain after initial evaluation.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      provenance: { section: 'Tilt Table Testing', page_or_location: 'Section 7.4' },
    },
    {
      rec_id: 'PACK.ACCAHA.SYNC.2017.REC.05',
      display_id: 'ACCAHA-SYNC-R5',
      statement: 'Routine head CT, carotid imaging, and EEG are not recommended in the evaluation of typical syncope without focal neurological findings. These tests have extremely low diagnostic yield and should not be ordered reflexively.',
      normalized_claim: 'Do NOT routinely order head CT, carotid imaging, or EEG for syncope without focal neurological deficits. Low yield, high cost.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Tests of Low Yield', page_or_location: 'Section 7.6' },
    },
    {
      rec_id: 'PACK.ACCAHA.SYNC.2017.REC.06',
      display_id: 'ACCAHA-SYNC-R6',
      statement: 'An implantable loop recorder (ILR) should be considered for patients with recurrent unexplained syncope when initial evaluation, ECG monitoring, and echocardiography have been nondiagnostic.',
      normalized_claim: 'ILR for recurrent unexplained syncope after nondiagnostic initial workup, ECG monitoring, and echo.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      provenance: { section: 'Prolonged Monitoring', page_or_location: 'Section 7.3' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ACCAHA.SYNC.2017.DC.01',
      display_id: 'ACCAHA-SYNC-DC1',
      name: 'Syncope Definition',
      components: [
        'Transient loss of consciousness (TLOC)',
        'Due to transient global cerebral hypoperfusion',
        'Rapid onset',
        'Brief duration (typically <20 seconds, rarely >5 minutes)',
        'Spontaneous and complete recovery without intervention',
      ],
      interpretation: 'Syncope is specifically TLOC from cerebral hypoperfusion. Differentiates from seizure (postictal state, tongue biting, tonic-clonic movements), hypoglycemia (gradual onset, no full spontaneous recovery), and psychogenic pseudosyncope (prolonged episodes, eyes closed).',
      normalized_claim: 'Syncope = transient LOC from cerebral hypoperfusion with rapid onset, brief duration, and spontaneous complete recovery.',
      provenance: { section: 'Definition and Classification', page_or_location: 'Section 3.1' },
    },
    {
      criterion_id: 'PACK.ACCAHA.SYNC.2017.DC.02',
      display_id: 'ACCAHA-SYNC-DC2',
      name: 'Vasovagal Syncope Features',
      components: [
        'Prodrome present: lightheadedness, warmth, diaphoresis, nausea, tunnel vision, pallor',
        'Identifiable trigger: prolonged standing, emotional stress, pain, heat exposure, crowded environment',
        'Brief LOC with rapid recovery',
        'No structural heart disease',
        'Normal ECG',
        'Typically younger patient (<60 years)',
      ],
      interpretation: 'Most common cause of syncope (21-35% of cases). Benign prognosis. Diagnosis is primarily clinical based on characteristic history. Tilt table confirms if uncertain.',
      normalized_claim: 'Vasovagal syncope: prodrome (lightheadedness, diaphoresis, nausea) + trigger (standing, pain, stress) + rapid recovery + normal ECG + no structural heart disease. Benign.',
      provenance: { section: 'Reflex Syncope', page_or_location: 'Section 4.1' },
    },
    {
      criterion_id: 'PACK.ACCAHA.SYNC.2017.DC.03',
      display_id: 'ACCAHA-SYNC-DC3',
      name: 'Cardiac Syncope Features',
      components: [
        'Syncope during exertion or while supine',
        'Sudden onset without prodrome',
        'Associated palpitations preceding syncope',
        'Abnormal ECG (prolonged QT, Brugada pattern, WPW, AV block, bundle branch block)',
        'Known structural heart disease (HCM, ARVC, severe AS, reduced LVEF)',
        'Family history of sudden cardiac death at young age',
      ],
      interpretation: 'Cardiac syncope carries the highest mortality risk among syncope causes. Requires urgent evaluation with echocardiography, continuous monitoring, and possible electrophysiology study.',
      normalized_claim: 'Cardiac syncope: exertional or supine syncope, no prodrome, palpitations, abnormal ECG, structural heart disease, or family hx SCD. Highest mortality risk.',
      provenance: { section: 'Cardiac Syncope', page_or_location: 'Section 4.3' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ACCAHA.SYNC.2017.T.01',
      display_id: 'ACCAHA-SYNC-T1',
      parameter: 'Orthostatic hypotension',
      value: 'SBP drop >=20 mmHg or DBP drop >=10 mmHg',
      clinical_meaning: 'Measured within 3 minutes of standing from supine position. Confirms orthostatic mechanism. May be symptomatic (lightheadedness, syncope) or asymptomatic. Common in elderly and those on antihypertensives, vasodilators, or diuretics.',
      normalized_claim: 'Orthostatic hypotension = SBP drop >=20 or DBP drop >=10 within 3 min of standing. Check on all syncope patients.',
      direction: 'above',
      provenance: { section: 'Orthostatic Hypotension', page_or_location: 'Section 4.2' },
    },
    {
      threshold_id: 'PACK.ACCAHA.SYNC.2017.T.02',
      display_id: 'ACCAHA-SYNC-T2',
      parameter: 'QTc interval',
      value: '500',
      unit: 'ms',
      clinical_meaning: 'QTc >500 ms is associated with significant risk of torsades de pointes and sudden cardiac death. Requires medication review (stop QT-prolonging drugs), electrolyte correction, cardiology referral, and possible ICD consideration.',
      normalized_claim: 'QTc >500 ms in syncope: high risk for torsades/SCD. Stop QT-prolonging drugs, correct electrolytes, cardiology referral.',
      direction: 'above',
      provenance: { section: 'ECG Findings', page_or_location: 'Section 5.3' },
    },
    {
      threshold_id: 'PACK.ACCAHA.SYNC.2017.T.03',
      display_id: 'ACCAHA-SYNC-T3',
      parameter: 'Age threshold for higher-risk syncope',
      value: '60',
      unit: 'years',
      clinical_meaning: 'Syncope in patients >60 years old without a clear vasovagal trigger warrants more extensive cardiac evaluation. Prevalence of cardiac syncope increases with age. Lower threshold for admission and monitoring.',
      normalized_claim: 'Age >60 with unexplained syncope: higher suspicion for cardiac cause. Lower threshold for admission and cardiac workup.',
      direction: 'above',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 6.1' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ACCAHA.SYNC.2017.TX.01',
      display_id: 'ACCAHA-SYNC-TX1',
      action: 'Vasovagal syncope: Patient education and non-pharmacologic management',
      normalized_claim: 'Vasovagal syncope treatment: education on triggers/avoidance, adequate hydration (2-3L/day), increased salt intake, counter-pressure maneuvers (leg crossing, hand grip, squatting) at onset of prodrome.',
      timing: 'At diagnosis; ongoing',
      condition: 'Confirmed or strongly suspected vasovagal syncope',
      provenance: { section: 'Reflex Syncope Management', page_or_location: 'Section 9.1' },
    },
    {
      step_id: 'PACK.ACCAHA.SYNC.2017.TX.02',
      display_id: 'ACCAHA-SYNC-TX2',
      action: 'Orthostatic hypotension: Volume expansion and pharmacotherapy',
      normalized_claim: 'Orthostatic syncope: discontinue/reduce offending meds, increase fluid/salt intake, compression stockings, sleep with head elevated. If refractory: midodrine 2.5-10 mg TID (alpha-1 agonist) or fludrocortisone 0.1-0.2 mg daily.',
      timing: 'At diagnosis; stepwise escalation',
      condition: 'Orthostatic hypotension confirmed by vital signs with symptoms',
      drug_details: { drug: 'Midodrine', dose: '2.5-10 mg TID', route: 'PO' },
      contraindications: ['Supine hypertension', 'Urinary retention', 'Severe organic heart disease (for midodrine)', 'Heart failure (for fludrocortisone)'],
      escalation: 'If midodrine insufficient, consider droxidopa (norepinephrine prodrug) 100-600 mg TID',
      provenance: { section: 'Orthostatic Hypotension Management', page_or_location: 'Section 9.2' },
    },
    {
      step_id: 'PACK.ACCAHA.SYNC.2017.TX.03',
      display_id: 'ACCAHA-SYNC-TX3',
      action: 'Cardiac syncope: Device therapy and antiarrhythmic management',
      normalized_claim: 'Cardiac syncope treatment: bradyarrhythmia (pacemaker), tachyarrhythmia (ICD or antiarrhythmic), structural (treat underlying lesion — e.g., AVR for severe AS, myectomy for obstructive HCM). EP study for unexplained cardiac syncope with reduced LVEF.',
      timing: 'After cardiac workup confirms arrhythmic or structural cause',
      condition: 'Cardiac syncope confirmed by monitoring, EP study, or echocardiography',
      provenance: { section: 'Cardiac Syncope Management', page_or_location: 'Section 9.3' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ACCAHA.SYNC.2017.RF.01',
      display_id: 'ACCAHA-SYNC-RF1',
      finding: 'Syncope during exertion (running, climbing stairs, swimming) rather than after exertion',
      implication: 'Suggests cardiac outflow obstruction (severe aortic stenosis, HCM), exercise-induced arrhythmia (CPVT, long QT), or coronary artery anomaly. Risk of sudden cardiac death.',
      action: 'Restrict exercise until evaluated. Echocardiography. Exercise stress testing (supervised, with resuscitation equipment). Cardiology referral. Consider genetic testing if channelopathy suspected.',
      urgency: 'urgent',
      provenance: { section: 'High-Risk Features', page_or_location: 'Section 6.2' },
    },
    {
      flag_id: 'PACK.ACCAHA.SYNC.2017.RF.02',
      display_id: 'ACCAHA-SYNC-RF2',
      finding: 'Family history of sudden cardiac death <50 years old or known inherited cardiac condition (HCM, ARVC, long QT, Brugada)',
      implication: 'Raises suspicion for inherited channelopathy or cardiomyopathy. Syncope may be a sentinel event before cardiac arrest.',
      action: 'Detailed family pedigree. ECG looking for specific patterns (long QT, Brugada, epsilon wave). Echocardiography. Cardiology/electrophysiology referral. Genetic counseling and possible testing.',
      urgency: 'urgent',
      provenance: { section: 'Inherited Conditions', page_or_location: 'Section 6.3' },
    },
    {
      flag_id: 'PACK.ACCAHA.SYNC.2017.RF.03',
      display_id: 'ACCAHA-SYNC-RF3',
      finding: 'Structural heart disease (known cardiomyopathy, reduced LVEF, prior MI, moderate-severe valvular disease) with new syncope',
      implication: 'High risk for ventricular tachycardia as cause of syncope. Sudden cardiac death risk elevated. May warrant ICD.',
      action: 'Admit for telemetry monitoring. Echocardiography if not recent. Electrophysiology study. Evaluate ICD candidacy if LVEF <=35%. Antiarrhythmic therapy if VT documented.',
      urgency: 'urgent',
      provenance: { section: 'Cardiac Syncope', page_or_location: 'Section 4.3' },
    },
    {
      flag_id: 'PACK.ACCAHA.SYNC.2017.RF.04',
      display_id: 'ACCAHA-SYNC-RF4',
      finding: 'Abnormal ECG: prolonged QTc >500 ms, Brugada pattern, WPW (delta wave + short PR), high-degree AV block, wide QRS, or pathologic Q waves',
      implication: 'ECG abnormalities in syncope suggest arrhythmic etiology. Each pattern has specific management implications and sudden death risk.',
      action: 'Admit for continuous monitoring. Cardiology consultation. Specific management per ECG finding (e.g., stop QT-prolonging drugs, EP study for WPW, pacemaker for high-degree AV block).',
      urgency: 'urgent',
      provenance: { section: 'ECG Evaluation', page_or_location: 'Section 5.3' },
    },
    {
      flag_id: 'PACK.ACCAHA.SYNC.2017.RF.05',
      display_id: 'ACCAHA-SYNC-RF5',
      finding: 'Syncope in patient >60 years with no prodrome (sudden, without warning)',
      implication: 'Absence of prodrome in older adults strongly suggests cardiac arrhythmia rather than vasovagal cause. Higher risk for adverse events.',
      action: 'Admit for telemetry. ECG, echocardiography, extended cardiac monitoring. Evaluate for bradyarrhythmia (sick sinus syndrome, AV block) and tachyarrhythmia (VT). Consider ILR if inpatient monitoring nondiagnostic.',
      urgency: 'urgent',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 6.1' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ACCAHA.SYNC.2017.SEV.01',
      display_id: 'ACCAHA-SYNC-SEV1',
      level: 'Low-risk syncope',
      criteria: [
        'Classic vasovagal features: identifiable trigger + prodrome + rapid recovery',
        'Young patient (<60 years)',
        'Normal ECG (normal QRS, QT, no pre-excitation, no conduction disease)',
        'No structural heart disease by history or exam',
        'No family history of sudden cardiac death',
        'No syncope during exertion',
      ],
      management_implications:
        'Safe for ED discharge with outpatient follow-up. Reassurance and patient education. Behavioral measures (hydration, salt, counter-pressure maneuvers). Tilt table testing only if recurrent and impacting quality of life. No need for echocardiography, cardiac monitoring, or CT head.',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 6.1' },
    },
    {
      severity_id: 'PACK.ACCAHA.SYNC.2017.SEV.02',
      display_id: 'ACCAHA-SYNC-SEV2',
      level: 'High-risk syncope',
      criteria: [
        'Syncope during exertion',
        'Syncope while supine',
        'Sudden onset without prodrome (especially age >60)',
        'Abnormal ECG (prolonged QT, Brugada, WPW, AV block, wide QRS)',
        'Known structural heart disease or reduced LVEF',
        'Family history of sudden cardiac death at young age',
        'New or unexplained dyspnea or chest pain',
        'Significant injury from syncope suggesting no warning',
      ],
      management_implications:
        'Admit for inpatient evaluation. Continuous telemetry. Echocardiography. Consider electrophysiology study if structural heart disease with reduced LVEF. Evaluate for ICD candidacy. Restrict driving per guidelines until etiology established and treated. Exercise restriction if exertional syncope. Cardiology consultation.',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 6.1' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 lightweight pack for syncope evaluation. Covers risk stratification, vasovagal vs cardiac differentiation, orthostatic diagnosis, and disposition decision-making for question generation.',

  all_item_ids: [
    'PACK.ACCAHA.SYNC.2017.REC.01', 'PACK.ACCAHA.SYNC.2017.REC.02', 'PACK.ACCAHA.SYNC.2017.REC.03',
    'PACK.ACCAHA.SYNC.2017.REC.04', 'PACK.ACCAHA.SYNC.2017.REC.05', 'PACK.ACCAHA.SYNC.2017.REC.06',
    'PACK.ACCAHA.SYNC.2017.DC.01', 'PACK.ACCAHA.SYNC.2017.DC.02', 'PACK.ACCAHA.SYNC.2017.DC.03',
    'PACK.ACCAHA.SYNC.2017.T.01', 'PACK.ACCAHA.SYNC.2017.T.02', 'PACK.ACCAHA.SYNC.2017.T.03',
    'PACK.ACCAHA.SYNC.2017.TX.01', 'PACK.ACCAHA.SYNC.2017.TX.02', 'PACK.ACCAHA.SYNC.2017.TX.03',
    'PACK.ACCAHA.SYNC.2017.RF.01', 'PACK.ACCAHA.SYNC.2017.RF.02', 'PACK.ACCAHA.SYNC.2017.RF.03',
    'PACK.ACCAHA.SYNC.2017.RF.04', 'PACK.ACCAHA.SYNC.2017.RF.05',
    'PACK.ACCAHA.SYNC.2017.SEV.01', 'PACK.ACCAHA.SYNC.2017.SEV.02',
  ],
  all_display_ids: [
    'ACCAHA-SYNC-R1', 'ACCAHA-SYNC-R2', 'ACCAHA-SYNC-R3', 'ACCAHA-SYNC-R4', 'ACCAHA-SYNC-R5', 'ACCAHA-SYNC-R6',
    'ACCAHA-SYNC-DC1', 'ACCAHA-SYNC-DC2', 'ACCAHA-SYNC-DC3',
    'ACCAHA-SYNC-T1', 'ACCAHA-SYNC-T2', 'ACCAHA-SYNC-T3',
    'ACCAHA-SYNC-TX1', 'ACCAHA-SYNC-TX2', 'ACCAHA-SYNC-TX3',
    'ACCAHA-SYNC-RF1', 'ACCAHA-SYNC-RF2', 'ACCAHA-SYNC-RF3', 'ACCAHA-SYNC-RF4', 'ACCAHA-SYNC-RF5',
    'ACCAHA-SYNC-SEV1', 'ACCAHA-SYNC-SEV2',
  ],
};
