import type { SourcePack } from './types';

export const PACK_ACCAHA_HTN_2017: SourcePack = {
  source_pack_id: 'PACK.ACCAHA.HTN.2017',
  source_name: '2017 ACC/AHA Guideline for Prevention, Detection, Evaluation, and Management of High Blood Pressure in Adults',
  canonical_url: 'https://doi.org/10.1161/HYP.0000000000000065',
  publication_year: 2017,
  guideline_body: 'ACC/AHA',

  topic_tags: ['Hypertension', 'Blood Pressure', 'Hypertensive Emergency', 'Resistant HTN', 'Secondary HTN', 'Cardiology'],
  allowed_decision_scopes: [
    'HTN staging and diagnosis',
    'initial antihypertensive therapy selection',
    'combination therapy initiation',
    'ACEi/ARB for DM or CKD with HTN',
    'hypertensive emergency management',
    'hypertensive urgency management',
    'resistant HTN evaluation',
    'secondary HTN screening',
    'BP targets by comorbidity',
    'aortic dissection BP management',
  ],
  excluded_decision_scopes: [
    'pediatric hypertension',
    'pregnancy-induced hypertension (see ACOG guidelines)',
    'pulmonary hypertension',
    'intracranial hypertension',
    'white-coat hypertension management beyond diagnosis',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ACCAHA.HTN.2017.REC.01',
      display_id: 'ACCAHA-HTN-R1',
      statement: 'Lifestyle modifications are recommended for all adults with elevated BP or hypertension, including weight loss, DASH diet, sodium reduction (<1500mg/day), physical activity (90-150 min/week), and moderation of alcohol.',
      normalized_claim: 'Lifestyle modification for all patients with BP >=120/80: DASH diet, Na <1500mg/d, exercise, weight loss, limit alcohol. Can reduce SBP 4-11 mmHg.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Nonpharmacological Interventions', page_or_location: 'Section 6' },
    },
    {
      rec_id: 'PACK.ACCAHA.HTN.2017.REC.02',
      display_id: 'ACCAHA-HTN-R2',
      statement: 'First-line antihypertensive agents include thiazide diuretics, CCBs, ACE inhibitors, or ARBs. Initial drug choice should be based on comorbidities.',
      normalized_claim: 'First-line agents: thiazide (chlorthalidone preferred), CCB (amlodipine), ACEi, or ARB. All have equivalent efficacy for BP lowering in general population.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Pharmacological Treatment', page_or_location: 'Section 8.1' },
    },
    {
      rec_id: 'PACK.ACCAHA.HTN.2017.REC.03',
      display_id: 'ACCAHA-HTN-R3',
      statement: 'ACEi or ARB therapy is recommended as first-line treatment for hypertension in patients with diabetes mellitus or chronic kidney disease to provide additional renal protection.',
      normalized_claim: 'ACEi or ARB preferred first-line in HTN + DM or CKD (with albuminuria). Do not combine ACEi + ARB. Add CCB or thiazide if needed.',
      strength: 'strong',
      evidence_quality: 'high',
      population: 'Adults with HTN and DM or CKD',
      provenance: { section: 'Compelling Indications', page_or_location: 'Section 9.1' },
    },
    {
      rec_id: 'PACK.ACCAHA.HTN.2017.REC.04',
      display_id: 'ACCAHA-HTN-R4',
      statement: 'A BP target of <130/80 mmHg is recommended for all adults with confirmed hypertension and known CVD or 10-year ASCVD risk >=10%.',
      normalized_claim: 'BP target <130/80 for patients with known CVD or 10-year ASCVD risk >=10%. Based on SPRINT trial results.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'BP Targets', page_or_location: 'Section 8.1.5' },
    },
    {
      rec_id: 'PACK.ACCAHA.HTN.2017.REC.05',
      display_id: 'ACCAHA-HTN-R5',
      statement: 'Initial combination therapy with 2 first-line agents of different classes is recommended when BP is >=20/10 mmHg above target.',
      normalized_claim: 'Start dual therapy when BP >=20/10 above goal (e.g., SBP >=150 or DBP >=90 if target <130/80). Single-pill combinations improve adherence.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Combination Therapy', page_or_location: 'Section 8.1.4' },
    },
    {
      rec_id: 'PACK.ACCAHA.HTN.2017.REC.06',
      display_id: 'ACCAHA-HTN-R6',
      statement: 'In black adults without CKD or HF, initial treatment should include a thiazide-type diuretic or CCB, as these classes show superior efficacy in this population.',
      normalized_claim: 'Thiazide or CCB preferred first-line in black patients without CKD/HF. Based on ALLHAT showing superior outcomes vs ACEi in this population.',
      strength: 'strong',
      evidence_quality: 'moderate',
      population: 'Black adults with hypertension',
      provenance: { section: 'Special Populations', page_or_location: 'Section 9.4' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ACCAHA.HTN.2017.DC.01',
      display_id: 'ACCAHA-HTN-DC1',
      name: 'Blood Pressure Staging',
      components: [
        'Normal: SBP <120 AND DBP <80 mmHg',
        'Elevated: SBP 120-129 AND DBP <80 mmHg',
        'Stage 1 HTN: SBP 130-139 OR DBP 80-89 mmHg',
        'Stage 2 HTN: SBP >=140 OR DBP >=90 mmHg',
      ],
      threshold: 'HTN defined as >=130/80 mmHg (lowered from 140/90 in JNC 7)',
      interpretation: 'Staging determines intervention. Elevated = lifestyle only. Stage 1 = lifestyle + medication if ASCVD risk >=10% or known CVD. Stage 2 = lifestyle + medication for all.',
      normalized_claim: 'HTN staging: Normal <120/80, Elevated 120-129/<80, Stage 1 130-139/80-89, Stage 2 >=140/90. Threshold lowered from JNC 7 (140/90).',
      provenance: { section: 'Classification', page_or_location: 'Section 4' },
    },
    {
      criterion_id: 'PACK.ACCAHA.HTN.2017.DC.02',
      display_id: 'ACCAHA-HTN-DC2',
      name: 'Hypertensive Emergency Definition',
      components: [
        'SBP >180 and/or DBP >120 mmHg',
        'Evidence of acute end-organ damage: hypertensive encephalopathy, intracranial hemorrhage, acute MI, acute HF/pulmonary edema, aortic dissection, eclampsia, acute renal failure',
        'Requires IV antihypertensive therapy and ICU admission',
      ],
      interpretation: 'Hypertensive emergency = severely elevated BP + acute end-organ damage. Distinct from hypertensive urgency (elevated BP without end-organ damage).',
      normalized_claim: 'Hypertensive emergency: BP >180/120 + end-organ damage (encephalopathy, AKI, ACS, aortic dissection, pulmonary edema). Requires IV therapy.',
      provenance: { section: 'Hypertensive Crises', page_or_location: 'Section 11.1' },
    },
    {
      criterion_id: 'PACK.ACCAHA.HTN.2017.DC.03',
      display_id: 'ACCAHA-HTN-DC3',
      name: 'Resistant Hypertension',
      components: [
        'BP above goal despite 3 antihypertensives at optimal doses (including a diuretic)',
        'OR BP controlled on 4 or more antihypertensive agents',
        'Pseudoresistance excluded: confirmed adherence, proper measurement technique, no white-coat effect',
      ],
      interpretation: 'True resistant HTN requires ruling out pseudoresistance (non-adherence, white-coat HTN, improper measurement) and screening for secondary causes.',
      normalized_claim: 'Resistant HTN: uncontrolled on 3 drugs including diuretic, or controlled on >=4 drugs. Exclude pseudoresistance before workup for secondary causes.',
      provenance: { section: 'Resistant Hypertension', page_or_location: 'Section 10' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ACCAHA.HTN.2017.T.01',
      display_id: 'ACCAHA-HTN-T1',
      parameter: 'BP for HTN diagnosis',
      value: '130/80',
      unit: 'mmHg',
      clinical_meaning: 'BP >=130/80 defines hypertension under ACC/AHA 2017 guidelines. Stage 1 begins at 130/80.',
      normalized_claim: 'HTN diagnosis at BP >=130/80 mmHg (ACC/AHA 2017). Lower than JNC 7 threshold of 140/90.',
      direction: 'above',
      provenance: { section: 'Definition', page_or_location: 'Section 4' },
    },
    {
      threshold_id: 'PACK.ACCAHA.HTN.2017.T.02',
      display_id: 'ACCAHA-HTN-T2',
      parameter: 'BP for hypertensive crisis',
      value: '180/120',
      unit: 'mmHg',
      clinical_meaning: 'BP >180/120 defines hypertensive crisis. Presence or absence of end-organ damage distinguishes emergency from urgency.',
      normalized_claim: 'BP >180/120 = hypertensive crisis. With end-organ damage = emergency (IV therapy). Without = urgency (oral therapy, outpatient).',
      direction: 'above',
      provenance: { section: 'Hypertensive Crises', page_or_location: 'Section 11' },
    },
    {
      threshold_id: 'PACK.ACCAHA.HTN.2017.T.03',
      display_id: 'ACCAHA-HTN-T3',
      parameter: 'BP reduction target in first hour of hypertensive emergency',
      value: '25',
      unit: '% reduction from presenting MAP',
      clinical_meaning: 'Reduce BP by no more than 25% in the first hour to avoid cerebral hypoperfusion. Then target 160/100 over next 2-6 hours.',
      normalized_claim: 'Hypertensive emergency: reduce BP by <=25% in first hour, then to 160/100-110 over 2-6h, then to normal over 24-48h. Avoid precipitous drops.',
      direction: 'below',
      provenance: { section: 'Emergency Management', page_or_location: 'Section 11.1' },
    },
    {
      threshold_id: 'PACK.ACCAHA.HTN.2017.T.04',
      display_id: 'ACCAHA-HTN-T4',
      parameter: 'SBP target in aortic dissection',
      value: '120',
      unit: 'mmHg',
      clinical_meaning: 'In acute aortic dissection, SBP target <120 mmHg AND HR <60 bpm should be achieved within 20 minutes. Exception to the gradual BP reduction rule.',
      normalized_claim: 'Aortic dissection: SBP <120 and HR <60 within 20 minutes. Use IV esmolol first (reduce HR), then add vasodilator. Most aggressive BP target.',
      direction: 'below',
      provenance: { section: 'Aortic Dissection', page_or_location: 'Section 11.2' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ACCAHA.HTN.2017.TX.01',
      display_id: 'ACCAHA-HTN-TX1',
      action: 'Outpatient: Stepwise antihypertensive therapy',
      normalized_claim: 'Step 1: Single agent (thiazide, CCB, ACEi, or ARB). Step 2: Add second agent from different class. Step 3: Add third agent. If uncontrolled on 3: screen for secondary HTN.',
      timing: 'Reassess at 1-month intervals; titrate to target <130/80',
      condition: 'Stage 1 HTN with ASCVD risk >=10%, or Stage 2 HTN',
      escalation: 'If BP >=20/10 above goal: start with 2 agents. If uncontrolled on 3 agents (including diuretic): evaluate for resistant HTN.',
      provenance: { section: 'Treatment Algorithm', page_or_location: 'Section 8.1' },
    },
    {
      step_id: 'PACK.ACCAHA.HTN.2017.TX.02',
      display_id: 'ACCAHA-HTN-TX2',
      action: 'Hypertensive emergency: IV antihypertensive therapy',
      normalized_claim: 'IV labetalol, nicardipine, or nitroprusside for hypertensive emergency. Target 25% MAP reduction in first hour, then 160/100-110 over 2-6h.',
      timing: 'Immediate upon diagnosis of hypertensive emergency',
      condition: 'BP >180/120 with evidence of end-organ damage',
      drug_details: { drug: 'Nicardipine', dose: '5-15 mg/hr IV infusion, titrate by 2.5 mg/hr every 5-15 min', route: 'IV continuous infusion' },
      contraindications: ['Nitroprusside: hepatic/renal failure (cyanide/thiocyanate toxicity), use >48-72h'],
      provenance: { section: 'Emergency Management', page_or_location: 'Section 11.1' },
    },
    {
      step_id: 'PACK.ACCAHA.HTN.2017.TX.03',
      display_id: 'ACCAHA-HTN-TX3',
      action: 'Aortic dissection: Emergent HR and BP control',
      normalized_claim: 'Aortic dissection: IV esmolol (or labetalol) FIRST to reduce HR <60 and dP/dt, THEN add vasodilator (nicardipine or nitroprusside) for SBP <120. Beta-blocker before vasodilator to prevent reflex tachycardia.',
      timing: 'Within 20 minutes of diagnosis',
      condition: 'Acute aortic dissection (Type A or Type B)',
      drug_details: { drug: 'Esmolol', dose: '500 mcg/kg IV bolus, then 50-200 mcg/kg/min infusion', route: 'IV' },
      contraindications: ['Vasodilator without prior beta-blocker (reflex tachycardia increases aortic shear stress)'],
      escalation: 'If beta-blocker contraindicated: IV diltiazem as alternative. Emergent surgical consultation for Type A dissection.',
      provenance: { section: 'Aortic Dissection', page_or_location: 'Section 11.2' },
    },
    {
      step_id: 'PACK.ACCAHA.HTN.2017.TX.04',
      display_id: 'ACCAHA-HTN-TX4',
      action: 'Hypertensive urgency: Oral antihypertensive management',
      normalized_claim: 'Hypertensive urgency (BP >180/120 without end-organ damage): oral agents, not IV. Reinstate/adjust home medications. Target gradual reduction over 24-48h. No ER admission required if follow-up assured.',
      timing: 'Over 24-48 hours',
      condition: 'BP >180/120 without end-organ damage',
      drug_details: { drug: 'Captopril', dose: '25mg PO, repeat in 30-60 min if needed', route: 'PO' },
      contraindications: ['Avoid sublingual nifedipine (unpredictable precipitous drops)'],
      provenance: { section: 'Hypertensive Urgency', page_or_location: 'Section 11.3' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ACCAHA.HTN.2017.RF.01',
      display_id: 'ACCAHA-HTN-RF1',
      finding: 'Hypertensive encephalopathy: Severely elevated BP with headache, altered mental status, visual disturbances, nausea/vomiting, seizures',
      implication: 'Cerebral autoregulation failure with vasogenic edema. Can progress to hemorrhagic stroke or death without treatment.',
      action: 'IV nicardipine or labetalol. Reduce MAP by 20-25% in first hour. CT/MRI to exclude stroke. ICU admission.',
      urgency: 'immediate',
      provenance: { section: 'Hypertensive Encephalopathy', page_or_location: 'Section 11.1.1' },
    },
    {
      flag_id: 'PACK.ACCAHA.HTN.2017.RF.02',
      display_id: 'ACCAHA-HTN-RF2',
      finding: 'Acute aortic dissection: Tearing chest/back pain, BP differential between arms >20 mmHg, widened mediastinum, new aortic regurgitation murmur',
      implication: 'Type A dissection requires emergent surgery. Type B managed medically unless complicated. Mortality increases 1-2% per hour untreated for Type A.',
      action: 'IV esmolol to HR <60, then vasodilator to SBP <120. STAT CT angiography. Emergent cardiac surgery consultation for Type A.',
      urgency: 'immediate',
      provenance: { section: 'Aortic Dissection', page_or_location: 'Section 11.2' },
    },
    {
      flag_id: 'PACK.ACCAHA.HTN.2017.RF.03',
      display_id: 'ACCAHA-HTN-RF3',
      finding: 'Eclampsia: Seizures in pregnant/postpartum woman with hypertension and proteinuria',
      implication: 'Life-threatening for mother and fetus. Distinct from other hypertensive emergencies — treatment differs.',
      action: 'IV magnesium sulfate (4-6g loading, then 1-2g/hr) for seizure treatment and prevention. IV labetalol or hydralazine for BP control. Emergent delivery is definitive treatment.',
      urgency: 'immediate',
      provenance: { section: 'Pregnancy-related HTN Emergencies', page_or_location: 'Section 11.4' },
    },
    {
      flag_id: 'PACK.ACCAHA.HTN.2017.RF.04',
      display_id: 'ACCAHA-HTN-RF4',
      finding: 'Acute kidney injury with malignant hypertension: Severely elevated BP, AKI (rising creatinine), microangiopathic hemolytic anemia (schistocytes), thrombocytopenia',
      implication: 'Malignant HTN with thrombotic microangiopathy. Can cause irreversible renal damage if BP not controlled promptly.',
      action: 'IV nicardipine or fenoldopam for gradual BP reduction. Avoid precipitous drops (risk of renal cortical necrosis). Monitor renal function, LDH, haptoglobin, platelet count.',
      urgency: 'immediate',
      provenance: { section: 'Renal Complications', page_or_location: 'Section 11.1.3' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ACCAHA.HTN.2017.SEV.01',
      display_id: 'ACCAHA-HTN-SEV1',
      level: 'Hypertensive Urgency',
      criteria: [
        'SBP >180 and/or DBP >120 mmHg',
        'NO evidence of acute end-organ damage',
        'Patient may be asymptomatic or have headache',
        'Often due to medication non-adherence',
      ],
      management_implications:
        'Oral antihypertensives (reinstate/intensify home regimen). No IV therapy required. Gradual BP reduction over 24-48 hours. Can be managed in ED observation or outpatient with close follow-up within 1 week. Do NOT use sublingual nifedipine.',
      provenance: { section: 'Hypertensive Urgency', page_or_location: 'Section 11.3' },
    },
    {
      severity_id: 'PACK.ACCAHA.HTN.2017.SEV.02',
      display_id: 'ACCAHA-HTN-SEV2',
      level: 'Hypertensive Emergency',
      criteria: [
        'SBP >180 and/or DBP >120 mmHg',
        'Acute end-organ damage present (brain, heart, kidney, aorta, eyes)',
        'Evidence: encephalopathy, ACS, pulmonary edema, AKI, aortic dissection, retinal hemorrhages/papilledema',
      ],
      management_implications:
        'ICU admission with continuous arterial BP monitoring. IV antihypertensive (nicardipine, labetalol, or nitroprusside). Target 25% MAP reduction in first hour, then 160/100-110 over 2-6h, then gradual normalization over 24-48h. Organ-specific targets apply (aortic dissection: SBP <120 in 20 min).',
      provenance: { section: 'Hypertensive Emergency', page_or_location: 'Section 11.1' },
    },
    {
      severity_id: 'PACK.ACCAHA.HTN.2017.SEV.03',
      display_id: 'ACCAHA-HTN-SEV3',
      level: 'Resistant Hypertension',
      criteria: [
        'BP above goal on 3 optimally dosed antihypertensives including a diuretic',
        'OR controlled BP requiring 4 or more agents',
        'Confirmed by ambulatory or home BP monitoring (excludes white-coat effect)',
        'Medication adherence verified',
      ],
      management_implications:
        'Screen for secondary causes: primary aldosteronism (most common, check aldosterone/renin ratio), renal artery stenosis, pheochromocytoma, Cushing syndrome, obstructive sleep apnea. Add spironolactone 25-50mg as 4th agent (PATHWAY-2 trial). Optimize diuretic therapy. Refer to HTN specialist.',
      provenance: { section: 'Resistant Hypertension', page_or_location: 'Section 10' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for Hypertension. Covers BP staging, first-line therapy, compelling indications, hypertensive emergency vs urgency, aortic dissection management, and resistant HTN workup.',

  all_item_ids: [
    'PACK.ACCAHA.HTN.2017.REC.01', 'PACK.ACCAHA.HTN.2017.REC.02', 'PACK.ACCAHA.HTN.2017.REC.03',
    'PACK.ACCAHA.HTN.2017.REC.04', 'PACK.ACCAHA.HTN.2017.REC.05', 'PACK.ACCAHA.HTN.2017.REC.06',
    'PACK.ACCAHA.HTN.2017.DC.01', 'PACK.ACCAHA.HTN.2017.DC.02', 'PACK.ACCAHA.HTN.2017.DC.03',
    'PACK.ACCAHA.HTN.2017.T.01', 'PACK.ACCAHA.HTN.2017.T.02', 'PACK.ACCAHA.HTN.2017.T.03',
    'PACK.ACCAHA.HTN.2017.T.04', 'PACK.ACCAHA.HTN.2017.TX.01', 'PACK.ACCAHA.HTN.2017.TX.02',
    'PACK.ACCAHA.HTN.2017.TX.03', 'PACK.ACCAHA.HTN.2017.TX.04', 'PACK.ACCAHA.HTN.2017.RF.01',
    'PACK.ACCAHA.HTN.2017.RF.02', 'PACK.ACCAHA.HTN.2017.RF.03', 'PACK.ACCAHA.HTN.2017.RF.04',
    'PACK.ACCAHA.HTN.2017.SEV.01', 'PACK.ACCAHA.HTN.2017.SEV.02', 'PACK.ACCAHA.HTN.2017.SEV.03',
  ],
  all_display_ids: [
    'ACCAHA-HTN-R1', 'ACCAHA-HTN-R2', 'ACCAHA-HTN-R3', 'ACCAHA-HTN-R4', 'ACCAHA-HTN-R5', 'ACCAHA-HTN-R6',
    'ACCAHA-HTN-DC1', 'ACCAHA-HTN-DC2', 'ACCAHA-HTN-DC3',
    'ACCAHA-HTN-T1', 'ACCAHA-HTN-T2', 'ACCAHA-HTN-T3', 'ACCAHA-HTN-T4',
    'ACCAHA-HTN-TX1', 'ACCAHA-HTN-TX2', 'ACCAHA-HTN-TX3', 'ACCAHA-HTN-TX4',
    'ACCAHA-HTN-RF1', 'ACCAHA-HTN-RF2', 'ACCAHA-HTN-RF3', 'ACCAHA-HTN-RF4',
    'ACCAHA-HTN-SEV1', 'ACCAHA-HTN-SEV2', 'ACCAHA-HTN-SEV3',
  ],
};
