import type { SourcePack } from './types';

export const PACK_ACCAHA_CHOL_2018: SourcePack = {
  source_pack_id: 'PACK.ACCAHA.CHOL.2018',
  source_name: 'ACC/AHA 2018 Guideline on the Management of Blood Cholesterol',
  source_registry_id: 'REG.ACCAHA.CHOL',
  canonical_url: 'https://doi.org/10.1161/CIR.0000000000000625',
  publication_year: 2018,
  guideline_body: 'ACC/AHA',

  topic_tags: ['Dyslipidemia', 'Hyperlipidemia', 'Statin Therapy', 'ASCVD', 'LDL', 'PCSK9 Inhibitor', 'Preventive Cardiology'],
  allowed_decision_scopes: [
    'statin benefit group identification',
    'high-intensity vs moderate-intensity statin selection',
    'LDL-C threshold for add-on therapy',
    'ASCVD risk calculation and risk-enhancing factors',
    'ezetimibe add-on therapy decision',
    'PCSK9 inhibitor indications',
    'statin intolerance management',
  ],
  excluded_decision_scopes: [
    'familial hypercholesterolemia genetic testing',
    'pediatric lipid management',
    'triglyceride-specific therapy (fibrates, omega-3)',
    'secondary causes of dyslipidemia workup',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ACCAHA.CHOL.2018.REC.01',
      display_id: 'ACCAHA-CHOL-R1',
      statement: 'In patients with clinical ASCVD, high-intensity statin therapy should be initiated or continued, aiming for >=50% LDL-C reduction.',
      normalized_claim: 'Clinical ASCVD: high-intensity statin (atorvastatin 40-80mg or rosuvastatin 20-40mg) targeting >=50% LDL reduction.',
      strength: 'strong',
      evidence_quality: 'high',
      population: 'Adults <=75 years with clinical ASCVD',
      provenance: { section: 'Secondary Prevention', page_or_location: 'Section 4.1' },
    },
    {
      rec_id: 'PACK.ACCAHA.CHOL.2018.REC.02',
      display_id: 'ACCAHA-CHOL-R2',
      statement: 'In patients with LDL-C >=190 mg/dL, high-intensity statin therapy should be initiated without requiring risk calculation.',
      normalized_claim: 'LDL >=190mg/dL: high-intensity statin without ASCVD risk calculation. Consider familial hypercholesterolemia.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Primary Prevention — Severe Hypercholesterolemia', page_or_location: 'Section 4.2' },
    },
    {
      rec_id: 'PACK.ACCAHA.CHOL.2018.REC.03',
      display_id: 'ACCAHA-CHOL-R3',
      statement: 'In patients aged 40-75 with diabetes and LDL-C >=70 mg/dL, moderate-intensity statin therapy is recommended. High-intensity statin is reasonable if multiple risk factors or 10-year ASCVD risk >=7.5%.',
      normalized_claim: 'Diabetes age 40-75: moderate-intensity statin. Escalate to high-intensity if multiple risk factors or ASCVD risk >=7.5%.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Primary Prevention — Diabetes', page_or_location: 'Section 4.3' },
    },
    {
      rec_id: 'PACK.ACCAHA.CHOL.2018.REC.04',
      display_id: 'ACCAHA-CHOL-R4',
      statement: 'In adults 40-75 without diabetes and 10-year ASCVD risk >=7.5%, moderate-to-high intensity statin therapy is recommended after clinician-patient risk discussion.',
      normalized_claim: '10-year ASCVD risk >=7.5% (age 40-75, no DM): moderate-to-high intensity statin after shared decision-making.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Primary Prevention — Intermediate Risk', page_or_location: 'Section 4.4' },
    },
    {
      rec_id: 'PACK.ACCAHA.CHOL.2018.REC.05',
      display_id: 'ACCAHA-CHOL-R5',
      statement: 'In very high-risk ASCVD patients on maximally tolerated statin with LDL-C >=70 mg/dL, adding ezetimibe is reasonable. If LDL-C remains >=70 mg/dL, a PCSK9 inhibitor may be considered.',
      normalized_claim: 'Very high-risk ASCVD + LDL >=70 on max statin: add ezetimibe. If still >=70, consider PCSK9 inhibitor.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      provenance: { section: 'Add-On Therapy', page_or_location: 'Section 4.5' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ACCAHA.CHOL.2018.DC.01',
      display_id: 'ACCAHA-CHOL-DC1',
      name: 'Four Statin Benefit Groups',
      components: [
        'Group 1: Clinical ASCVD (ACS, prior MI, stable angina, prior stroke/TIA, PAD)',
        'Group 2: Primary elevation of LDL-C >=190 mg/dL',
        'Group 3: Diabetes mellitus, age 40-75, LDL-C 70-189 mg/dL',
        'Group 4: Age 40-75, LDL-C 70-189 mg/dL, 10-year ASCVD risk >=7.5%',
      ],
      interpretation: 'These four groups have the strongest evidence for statin benefit. Group 1 and 2 receive high-intensity statin. Group 3 receives at least moderate-intensity. Group 4 requires shared decision-making.',
      normalized_claim: 'Four statin benefit groups: (1) clinical ASCVD, (2) LDL >=190, (3) DM age 40-75, (4) 10-year risk >=7.5%. Groups 1-2: high-intensity; Group 3: moderate+; Group 4: shared decision.',
      provenance: { section: 'Statin Benefit Groups', page_or_location: 'Table 6' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ACCAHA.CHOL.2018.T.01',
      display_id: 'ACCAHA-CHOL-T1',
      parameter: 'LDL-C for statin without risk calculation',
      value: '190',
      unit: 'mg/dL',
      clinical_meaning: 'LDL-C >=190 mg/dL is an automatic indication for high-intensity statin regardless of calculated ASCVD risk. Suggests possible familial hypercholesterolemia.',
      normalized_claim: 'LDL >=190mg/dL triggers high-intensity statin without risk calculation. Screen for familial hypercholesterolemia.',
      direction: 'above',
      provenance: { section: 'Severe Hypercholesterolemia', page_or_location: 'Section 4.2' },
    },
    {
      threshold_id: 'PACK.ACCAHA.CHOL.2018.T.02',
      display_id: 'ACCAHA-CHOL-T2',
      parameter: 'LDL-C threshold for add-on therapy in ASCVD',
      value: '70',
      unit: 'mg/dL',
      clinical_meaning: 'In very high-risk ASCVD patients on maximally tolerated statin, LDL-C >=70 mg/dL is the threshold to add ezetimibe, and if still elevated, a PCSK9 inhibitor.',
      normalized_claim: 'Very high-risk ASCVD: LDL >=70 on max statin → add ezetimibe → if still >=70, add PCSK9i.',
      direction: 'above',
      provenance: { section: 'Add-On Therapy', page_or_location: 'Section 4.5' },
    },
    {
      threshold_id: 'PACK.ACCAHA.CHOL.2018.T.03',
      display_id: 'ACCAHA-CHOL-T3',
      parameter: '10-year ASCVD risk threshold for statin initiation',
      value: '7.5',
      unit: '%',
      clinical_meaning: '10-year ASCVD risk >=7.5% (using Pooled Cohort Equations) is the threshold for statin initiation in adults 40-75 without diabetes after clinician-patient discussion.',
      normalized_claim: '10-year ASCVD risk >=7.5% in ages 40-75: initiate statin therapy after shared decision-making.',
      direction: 'above',
      provenance: { section: 'Risk Assessment', page_or_location: 'Section 3.2' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ACCAHA.CHOL.2018.TX.01',
      display_id: 'ACCAHA-CHOL-TX1',
      action: 'Initiate high-intensity statin for clinical ASCVD',
      normalized_claim: 'Clinical ASCVD: atorvastatin 40-80mg or rosuvastatin 20-40mg. Target >=50% LDL reduction.',
      timing: 'At diagnosis or as secondary prevention',
      condition: 'Clinical ASCVD (prior MI, stroke, PAD, stable angina)',
      drug_details: { drug: 'Atorvastatin', dose: '40-80mg daily', route: 'PO' },
      contraindications: ['Active liver disease', 'Pregnancy', 'Nursing'],
      escalation: 'Add ezetimibe if LDL remains >=70 on max statin',
      provenance: { section: 'Secondary Prevention', page_or_location: 'Section 4.1' },
    },
    {
      step_id: 'PACK.ACCAHA.CHOL.2018.TX.02',
      display_id: 'ACCAHA-CHOL-TX2',
      action: 'Add ezetimibe to maximally tolerated statin in very high-risk ASCVD',
      normalized_claim: 'Very high-risk ASCVD with LDL >=70 on max statin: add ezetimibe 10mg daily. Reduces LDL additional 15-20%.',
      timing: 'After maximally tolerated statin fails to achieve LDL <70',
      condition: 'Very high-risk ASCVD with LDL >=70 despite max statin',
      drug_details: { drug: 'Ezetimibe', dose: '10mg daily', route: 'PO' },
      escalation: 'Add PCSK9 inhibitor if LDL still >=70',
      provenance: { section: 'Add-On Therapy', page_or_location: 'Section 4.5' },
    },
    {
      step_id: 'PACK.ACCAHA.CHOL.2018.TX.03',
      display_id: 'ACCAHA-CHOL-TX3',
      action: 'Add PCSK9 inhibitor for persistently elevated LDL in very high-risk ASCVD',
      normalized_claim: 'Very high-risk ASCVD with LDL >=70 on max statin + ezetimibe: consider PCSK9i (evolocumab or alirocumab). Can reduce LDL by 50-60%.',
      timing: 'After ezetimibe add-on fails to achieve LDL <70',
      condition: 'Very high-risk ASCVD with LDL >=70 on max statin + ezetimibe',
      drug_details: { drug: 'Evolocumab or Alirocumab', dose: 'Evolocumab 140mg q2wk or alirocumab 75mg q2wk', route: 'SC injection' },
      provenance: { section: 'PCSK9 Inhibitors', page_or_location: 'Section 4.6' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ACCAHA.CHOL.2018.RF.01',
      display_id: 'ACCAHA-CHOL-RF1',
      finding: 'LDL-C >=190 mg/dL in a young adult (especially with tendon xanthomas or family history of premature ASCVD)',
      implication: 'Strongly suggests familial hypercholesterolemia (FH). Heterozygous FH affects ~1:250 people. 20-fold increased ASCVD risk without treatment.',
      action: 'High-intensity statin immediately. Cascade screening of first-degree relatives. Consider early add-on therapy (ezetimibe, PCSK9i). Lipid specialist referral.',
      urgency: 'soon',
      provenance: { section: 'Severe Hypercholesterolemia', page_or_location: 'Section 4.2' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ACCAHA.CHOL.2018.SEV.01',
      display_id: 'ACCAHA-CHOL-SEV1',
      level: 'Very high-risk ASCVD',
      criteria: [
        'History of multiple major ASCVD events (>=2 of: recent ACS within 12 months, prior MI, ischemic stroke, symptomatic PAD)',
        'OR: 1 major ASCVD event + multiple high-risk conditions (age >=65, heterozygous FH, prior CABG/PCI, diabetes, HTN, CKD stage 3-4, current smoking, persistently elevated LDL >=100 despite max statin, history of CHF)',
      ],
      management_implications:
        'Maximally tolerated high-intensity statin PLUS ezetimibe. If LDL remains >=70, add PCSK9 inhibitor. Aggressive cardiovascular risk factor management. Target LDL <70mg/dL (some guidelines suggest <55).',
      provenance: { section: 'Very High-Risk ASCVD', page_or_location: 'Section 4.5' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for cholesterol management. Covers 4 statin benefit groups, intensity selection, add-on therapy ladder (ezetimibe → PCSK9i).',

  all_item_ids: [
    'PACK.ACCAHA.CHOL.2018.REC.01', 'PACK.ACCAHA.CHOL.2018.REC.02', 'PACK.ACCAHA.CHOL.2018.REC.03',
    'PACK.ACCAHA.CHOL.2018.REC.04', 'PACK.ACCAHA.CHOL.2018.REC.05',
    'PACK.ACCAHA.CHOL.2018.DC.01',
    'PACK.ACCAHA.CHOL.2018.T.01', 'PACK.ACCAHA.CHOL.2018.T.02', 'PACK.ACCAHA.CHOL.2018.T.03',
    'PACK.ACCAHA.CHOL.2018.TX.01', 'PACK.ACCAHA.CHOL.2018.TX.02', 'PACK.ACCAHA.CHOL.2018.TX.03',
    'PACK.ACCAHA.CHOL.2018.RF.01',
    'PACK.ACCAHA.CHOL.2018.SEV.01',
  ],
  all_display_ids: [
    'ACCAHA-CHOL-R1', 'ACCAHA-CHOL-R2', 'ACCAHA-CHOL-R3', 'ACCAHA-CHOL-R4', 'ACCAHA-CHOL-R5',
    'ACCAHA-CHOL-DC1',
    'ACCAHA-CHOL-T1', 'ACCAHA-CHOL-T2', 'ACCAHA-CHOL-T3',
    'ACCAHA-CHOL-TX1', 'ACCAHA-CHOL-TX2', 'ACCAHA-CHOL-TX3',
    'ACCAHA-CHOL-RF1',
    'ACCAHA-CHOL-SEV1',
  ],
};
