import type { SourcePack } from './types';

export const PACK_ACCAHA_AFIB_2023: SourcePack = {
  source_pack_id: 'PACK.ACCAHA.AFIB.2023',
  source_name: '2023 ACC/AHA/ACCP/HRS Guideline for Diagnosis and Management of Atrial Fibrillation',
  canonical_url: 'https://doi.org/10.1161/CIR.0000000000001193',
  publication_year: 2023,
  guideline_body: 'ACC/AHA/ACCP/HRS',

  topic_tags: ['Atrial Fibrillation', 'Anticoagulation', 'Rate Control', 'Rhythm Control', 'CHA2DS2-VASc', 'Cardiology'],
  allowed_decision_scopes: [
    'AFib classification and staging',
    'anticoagulation decision-making with CHA2DS2-VASc',
    'DOAC vs warfarin selection',
    'rate control strategy',
    'rhythm control strategy',
    'catheter ablation candidacy',
    'cardioversion management',
    'AFib with rapid ventricular response',
    'AFib in WPW management',
    'AFib with hemodynamic instability',
  ],
  excluded_decision_scopes: [
    'atrial flutter ablation specifics',
    'cardiac surgery for AFib (maze procedure)',
    'pacemaker management',
    'anticoagulation in mechanical heart valves',
    'pediatric AFib management',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ACCAHA.AFIB.2023.REC.01',
      display_id: 'ACCAHA-AFIB-R1',
      statement: 'DOACs are recommended over warfarin for stroke prevention in AFib patients eligible for oral anticoagulation, except in those with moderate-to-severe mitral stenosis or mechanical heart valves.',
      normalized_claim: 'DOACs preferred over warfarin for AFib anticoagulation. Exceptions: mechanical valves and moderate-severe mitral stenosis require warfarin.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Anticoagulation', page_or_location: 'Section 6.2' },
    },
    {
      rec_id: 'PACK.ACCAHA.AFIB.2023.REC.02',
      display_id: 'ACCAHA-AFIB-R2',
      statement: 'Anticoagulation for stroke prevention is recommended in AFib patients with CHA2DS2-VASc score >=2 in men or >=3 in women.',
      normalized_claim: 'Anticoagulate when CHA2DS2-VASc >=2 (men) or >=3 (women). Score of 1 (men) or 2 (women) = may consider anticoagulation.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Stroke Risk Assessment', page_or_location: 'Section 6.1' },
    },
    {
      rec_id: 'PACK.ACCAHA.AFIB.2023.REC.03',
      display_id: 'ACCAHA-AFIB-R3',
      statement: 'A lenient rate-control strategy (resting HR <110 bpm) is reasonable for most patients with AFib who remain asymptomatic at higher rates.',
      normalized_claim: 'Lenient rate control target HR <110 bpm at rest is acceptable for asymptomatic AFib. Strict control (HR <80) if persistent symptoms.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      provenance: { section: 'Rate Control', page_or_location: 'Section 7.1' },
    },
    {
      rec_id: 'PACK.ACCAHA.AFIB.2023.REC.04',
      display_id: 'ACCAHA-AFIB-R4',
      statement: 'Early rhythm control is recommended for patients with AFib duration <1 year, particularly those with symptomatic AFib and few comorbidities.',
      normalized_claim: 'Early rhythm control preferred when AFib <1 year duration. EAST-AFNET 4 trial showed CV benefit with early rhythm control.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Rhythm Control', page_or_location: 'Section 7.2' },
    },
    {
      rec_id: 'PACK.ACCAHA.AFIB.2023.REC.05',
      display_id: 'ACCAHA-AFIB-R5',
      statement: 'Catheter ablation is recommended as a rhythm control strategy for symptomatic AFib refractory to or intolerant of at least one antiarrhythmic drug.',
      normalized_claim: 'Catheter ablation (pulmonary vein isolation) for symptomatic AFib after AAD failure. Can be first-line in select patients.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Catheter Ablation', page_or_location: 'Section 7.3' },
    },
    {
      rec_id: 'PACK.ACCAHA.AFIB.2023.REC.06',
      display_id: 'ACCAHA-AFIB-R6',
      statement: 'In patients with AFib and HFrEF, catheter ablation may be considered as first-line rhythm control to improve ventricular function and reduce HF hospitalization.',
      normalized_claim: 'Catheter ablation as first-line rhythm control in AFib + HFrEF. CASTLE-AF showed mortality benefit in this population.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      provenance: { section: 'AFib and Heart Failure', page_or_location: 'Section 9.1' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ACCAHA.AFIB.2023.DC.01',
      display_id: 'ACCAHA-AFIB-DC1',
      name: 'Atrial Fibrillation ECG Criteria',
      components: [
        'Irregularly irregular R-R intervals',
        'Absence of distinct repeating P waves',
        'Fibrillatory baseline (irregular atrial activity)',
        'Variable ventricular rate (typically 100-180 bpm if untreated)',
      ],
      interpretation: 'AFib diagnosis requires ECG documentation. Single-lead ECG or wearable devices can detect but 12-lead ECG is gold standard for confirmation.',
      normalized_claim: 'AFib diagnosed by irregular R-R intervals + absent P waves on ECG. 12-lead ECG is gold standard for confirmation.',
      provenance: { section: 'Diagnosis', page_or_location: 'Section 4.1' },
    },
    {
      criterion_id: 'PACK.ACCAHA.AFIB.2023.DC.02',
      display_id: 'ACCAHA-AFIB-DC2',
      name: 'Atrial Fibrillation Classification',
      components: [
        'Paroxysmal: Terminates spontaneously or with intervention within 7 days',
        'Persistent: Continuous AFib lasting >7 days, including episodes terminated by cardioversion after >=7 days',
        'Long-standing persistent: Continuous AFib >12 months when rhythm control strategy is pursued',
        'Permanent: AFib accepted by patient and clinician; no further rhythm control attempts',
      ],
      interpretation: 'Classification guides treatment strategy. Paroxysmal and early persistent AFib are most amenable to rhythm control. Permanent AFib = rate control only.',
      normalized_claim: 'AFib classified by duration and management intent: paroxysmal (<7d), persistent (>7d), long-standing persistent (>12mo), permanent (no rhythm control).',
      provenance: { section: 'Classification', page_or_location: 'Section 3' },
    },
    {
      criterion_id: 'PACK.ACCAHA.AFIB.2023.DC.03',
      display_id: 'ACCAHA-AFIB-DC3',
      name: 'CHA2DS2-VASc Score Components',
      components: [
        'C: Congestive heart failure (1 point)',
        'H: Hypertension (1 point)',
        'A2: Age >=75 years (2 points)',
        'D: Diabetes mellitus (1 point)',
        'S2: Prior Stroke/TIA/thromboembolism (2 points)',
        'V: Vascular disease — prior MI, PAD, aortic plaque (1 point)',
        'A: Age 65-74 years (1 point)',
        'Sc: Sex category — female (1 point)',
      ],
      threshold: '>=2 in men, >=3 in women for anticoagulation',
      interpretation: 'Score determines stroke risk and anticoagulation indication. Female sex is a risk modifier (only adds risk in presence of other factors).',
      normalized_claim: 'CHA2DS2-VASc: 9-point scale. Anticoagulate at >=2 (men) or >=3 (women). Female sex alone does not warrant anticoagulation.',
      provenance: { section: 'Stroke Risk Assessment', page_or_location: 'Section 6.1' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ACCAHA.AFIB.2023.T.01',
      display_id: 'ACCAHA-AFIB-T1',
      parameter: 'CHA2DS2-VASc for anticoagulation (men)',
      value: '2',
      clinical_meaning: 'Score >=2 in men indicates sufficient stroke risk to recommend oral anticoagulation.',
      normalized_claim: 'CHA2DS2-VASc >=2 in men = anticoagulate. Score of 1 = consider anticoagulation based on individual risk-benefit.',
      direction: 'above',
      provenance: { section: 'Stroke Prevention', page_or_location: 'Section 6.1' },
    },
    {
      threshold_id: 'PACK.ACCAHA.AFIB.2023.T.02',
      display_id: 'ACCAHA-AFIB-T2',
      parameter: 'CHA2DS2-VASc for anticoagulation (women)',
      value: '3',
      clinical_meaning: 'Score >=3 in women indicates sufficient stroke risk to recommend oral anticoagulation (1 point is from female sex category).',
      normalized_claim: 'CHA2DS2-VASc >=3 in women = anticoagulate. Effectively same threshold as men (>=2 non-sex points).',
      direction: 'above',
      provenance: { section: 'Stroke Prevention', page_or_location: 'Section 6.1' },
    },
    {
      threshold_id: 'PACK.ACCAHA.AFIB.2023.T.03',
      display_id: 'ACCAHA-AFIB-T3',
      parameter: 'Heart rate for lenient rate control',
      value: '110',
      unit: 'bpm',
      clinical_meaning: 'Resting HR <110 bpm is the target for lenient rate control strategy. Acceptable if patient remains asymptomatic.',
      normalized_claim: 'Lenient rate control: resting HR <110 bpm. Based on RACE II trial showing non-inferiority to strict control.',
      direction: 'below',
      provenance: { section: 'Rate Control Targets', page_or_location: 'Section 7.1' },
    },
    {
      threshold_id: 'PACK.ACCAHA.AFIB.2023.T.04',
      display_id: 'ACCAHA-AFIB-T4',
      parameter: 'Heart rate for strict rate control',
      value: '80',
      unit: 'bpm',
      clinical_meaning: 'Resting HR <80 bpm is the target for strict rate control, used in patients with persistent symptoms despite lenient control.',
      normalized_claim: 'Strict rate control: resting HR <80 bpm. Reserved for patients symptomatic despite lenient control.',
      direction: 'below',
      provenance: { section: 'Rate Control Targets', page_or_location: 'Section 7.1' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ACCAHA.AFIB.2023.TX.01',
      display_id: 'ACCAHA-AFIB-TX1',
      action: 'Rate control: First-line agents',
      normalized_claim: 'Beta-blockers (metoprolol, atenolol) or non-dihydropyridine CCBs (diltiazem, verapamil) first-line for rate control. Avoid CCBs in HFrEF.',
      timing: 'At diagnosis of AFib requiring rate control',
      condition: 'Hemodynamically stable AFib with rapid ventricular response',
      drug_details: { drug: 'Metoprolol', dose: '25-200mg BID (tartrate) or 25-400mg daily (succinate)', route: 'PO or IV 5mg q5min x3' },
      contraindications: ['Non-DHP CCBs contraindicated in HFrEF', 'Beta-blockers: severe bronchospasm, decompensated HF', 'Both: pre-excitation (WPW)'],
      provenance: { section: 'Rate Control', page_or_location: 'Section 7.1.1' },
    },
    {
      step_id: 'PACK.ACCAHA.AFIB.2023.TX.02',
      display_id: 'ACCAHA-AFIB-TX2',
      action: 'Rate control in HF: Digoxin or amiodarone',
      normalized_claim: 'Digoxin for rate control in AFib + HFrEF when beta-blockers insufficient. Amiodarone as last-line rate control agent. Monitor digoxin levels (target 0.5-0.9 ng/mL).',
      timing: 'After beta-blocker optimization in HFrEF',
      condition: 'AFib with HFrEF, inadequate rate control on beta-blocker alone',
      drug_details: { drug: 'Digoxin', dose: '0.125-0.25mg daily, target level 0.5-0.9 ng/mL', route: 'PO' },
      contraindications: ['Hypokalemia (increases digoxin toxicity)', 'Renal failure (reduce dose)', 'WPW (can increase accessory pathway conduction)'],
      provenance: { section: 'Rate Control in HF', page_or_location: 'Section 7.1.2' },
    },
    {
      step_id: 'PACK.ACCAHA.AFIB.2023.TX.03',
      display_id: 'ACCAHA-AFIB-TX3',
      action: 'Rhythm control: Antiarrhythmic drug therapy',
      normalized_claim: 'Flecainide or propafenone for AFib without structural heart disease (pill-in-pocket or daily). Amiodarone for AFib with structural heart disease or HF. Dofetilide or sotalol as alternatives.',
      timing: 'After decision for rhythm control strategy',
      condition: 'Symptomatic AFib amenable to rhythm control',
      drug_details: { drug: 'Flecainide', dose: '50-150mg BID', route: 'PO' },
      contraindications: ['Flecainide/propafenone: contraindicated in structural heart disease, CAD, HFrEF', 'Amiodarone: thyroid disease (relative), pulmonary fibrosis'],
      escalation: 'If AAD fails: refer for catheter ablation',
      provenance: { section: 'Antiarrhythmic Drugs', page_or_location: 'Section 7.2.1' },
    },
    {
      step_id: 'PACK.ACCAHA.AFIB.2023.TX.04',
      display_id: 'ACCAHA-AFIB-TX4',
      action: 'Anticoagulation: DOAC selection',
      normalized_claim: 'Apixaban 5mg BID, rivaroxaban 20mg daily, edoxaban 60mg daily, or dabigatran 150mg BID. Dose-reduce per CrCl and weight criteria. Continue anticoagulation regardless of rhythm control success.',
      timing: 'At diagnosis when CHA2DS2-VASc threshold met',
      condition: 'AFib with CHA2DS2-VASc >=2 (men) or >=3 (women)',
      drug_details: { drug: 'Apixaban', dose: '5mg BID (2.5mg BID if >=2 of: age >=80, weight <=60kg, Cr >=1.5)', route: 'PO' },
      contraindications: ['Mechanical heart valve', 'Moderate-severe mitral stenosis', 'Severe renal failure (agent-specific CrCl cutoffs)'],
      provenance: { section: 'Anticoagulation Therapy', page_or_location: 'Section 6.2.1' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ACCAHA.AFIB.2023.RF.01',
      display_id: 'ACCAHA-AFIB-RF1',
      finding: 'Hemodynamically unstable AFib: Hypotension (SBP <90), altered mental status, chest pain, acute pulmonary edema, or signs of shock',
      implication: 'Rapid ventricular response causing hemodynamic compromise. Medical management is too slow.',
      action: 'Emergent synchronized cardioversion (biphasic 120-200J). Anticoagulation status does NOT delay cardioversion in emergent setting.',
      urgency: 'immediate',
      provenance: { section: 'Acute Management', page_or_location: 'Section 5.1' },
    },
    {
      flag_id: 'PACK.ACCAHA.AFIB.2023.RF.02',
      display_id: 'ACCAHA-AFIB-RF2',
      finding: 'AFib with WPW (pre-excitation): Wide-complex irregular tachycardia, delta waves on baseline ECG, very rapid rate (often >200 bpm)',
      implication: 'AV nodal blockers (beta-blockers, CCBs, digoxin, adenosine) are CONTRAINDICATED — they can cause unopposed accessory pathway conduction leading to VFib.',
      action: 'IV procainamide (first-line) or ibutilide. If hemodynamically unstable: emergent cardioversion. NEVER give AV nodal blockers.',
      urgency: 'immediate',
      provenance: { section: 'Pre-excitation Syndromes', page_or_location: 'Section 5.3' },
    },
    {
      flag_id: 'PACK.ACCAHA.AFIB.2023.RF.03',
      display_id: 'ACCAHA-AFIB-RF3',
      finding: 'New-onset AFib with acute heart failure or acute coronary syndrome',
      implication: 'AFib may be the cause or consequence of acute cardiac decompensation. Rapid ventricular rate worsens hemodynamics.',
      action: 'Treat underlying condition concurrently. Rate control with beta-blocker (if no decompensated HF) or amiodarone. Assess need for anticoagulation. Consider cardioversion after stabilization.',
      urgency: 'urgent',
      provenance: { section: 'AFib in Acute Settings', page_or_location: 'Section 9' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ACCAHA.AFIB.2023.SEV.01',
      display_id: 'ACCAHA-AFIB-SEV1',
      level: 'Hemodynamically Unstable AFib',
      criteria: [
        'SBP <90 mmHg or signs of shock',
        'Altered mental status',
        'Active chest pain or acute coronary ischemia',
        'Acute pulmonary edema',
        'Heart rate typically >150 bpm',
      ],
      management_implications:
        'Emergent synchronized cardioversion regardless of anticoagulation status or AFib duration. Post-cardioversion: initiate anticoagulation and assess for underlying cause. ICU admission for monitoring.',
      provenance: { section: 'Acute AFib Management', page_or_location: 'Section 5.1' },
    },
    {
      severity_id: 'PACK.ACCAHA.AFIB.2023.SEV.02',
      display_id: 'ACCAHA-AFIB-SEV2',
      level: 'Hemodynamically Stable AFib with RVR',
      criteria: [
        'Heart rate >100 bpm (typically 110-180 bpm)',
        'Stable blood pressure',
        'No signs of end-organ hypoperfusion',
        'May have mild symptoms (palpitations, mild dyspnea)',
      ],
      management_implications:
        'Rate control with IV beta-blocker or diltiazem. Target HR <110 initially. Assess CHA2DS2-VASc and initiate anticoagulation. If onset <48h and patient anticoagulated, consider elective cardioversion. If onset >48h or unknown: TEE before cardioversion or anticoagulate for 3 weeks first.',
      provenance: { section: 'Acute AFib Management', page_or_location: 'Section 5.2' },
    },
    {
      severity_id: 'PACK.ACCAHA.AFIB.2023.SEV.03',
      display_id: 'ACCAHA-AFIB-SEV3',
      level: 'Chronic/Permanent AFib',
      criteria: [
        'AFib accepted by patient and physician',
        'No further attempts at rhythm control',
        'Rate control as primary strategy',
        'Ongoing anticoagulation per CHA2DS2-VASc',
      ],
      management_implications:
        'Lifelong rate control therapy. Lifelong anticoagulation if indicated by CHA2DS2-VASc (do NOT stop anticoagulation based on perceived rate control adequacy). Monitor for symptoms, HF development, and anticoagulant compliance. Annual reassessment of rhythm vs rate strategy.',
      provenance: { section: 'Long-term Management', page_or_location: 'Section 8' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for Atrial Fibrillation. Covers AFib classification, CHA2DS2-VASc-based anticoagulation, rate vs rhythm control, WPW management, and cardioversion indications.',

  all_item_ids: [
    'PACK.ACCAHA.AFIB.2023.REC.01', 'PACK.ACCAHA.AFIB.2023.REC.02', 'PACK.ACCAHA.AFIB.2023.REC.03',
    'PACK.ACCAHA.AFIB.2023.REC.04', 'PACK.ACCAHA.AFIB.2023.REC.05', 'PACK.ACCAHA.AFIB.2023.REC.06',
    'PACK.ACCAHA.AFIB.2023.DC.01', 'PACK.ACCAHA.AFIB.2023.DC.02', 'PACK.ACCAHA.AFIB.2023.DC.03',
    'PACK.ACCAHA.AFIB.2023.T.01', 'PACK.ACCAHA.AFIB.2023.T.02', 'PACK.ACCAHA.AFIB.2023.T.03',
    'PACK.ACCAHA.AFIB.2023.T.04', 'PACK.ACCAHA.AFIB.2023.TX.01', 'PACK.ACCAHA.AFIB.2023.TX.02',
    'PACK.ACCAHA.AFIB.2023.TX.03', 'PACK.ACCAHA.AFIB.2023.TX.04', 'PACK.ACCAHA.AFIB.2023.RF.01',
    'PACK.ACCAHA.AFIB.2023.RF.02', 'PACK.ACCAHA.AFIB.2023.RF.03', 'PACK.ACCAHA.AFIB.2023.SEV.01',
    'PACK.ACCAHA.AFIB.2023.SEV.02', 'PACK.ACCAHA.AFIB.2023.SEV.03',
  ],
  all_display_ids: [
    'ACCAHA-AFIB-R1', 'ACCAHA-AFIB-R2', 'ACCAHA-AFIB-R3', 'ACCAHA-AFIB-R4', 'ACCAHA-AFIB-R5', 'ACCAHA-AFIB-R6',
    'ACCAHA-AFIB-DC1', 'ACCAHA-AFIB-DC2', 'ACCAHA-AFIB-DC3',
    'ACCAHA-AFIB-T1', 'ACCAHA-AFIB-T2', 'ACCAHA-AFIB-T3', 'ACCAHA-AFIB-T4',
    'ACCAHA-AFIB-TX1', 'ACCAHA-AFIB-TX2', 'ACCAHA-AFIB-TX3', 'ACCAHA-AFIB-TX4',
    'ACCAHA-AFIB-RF1', 'ACCAHA-AFIB-RF2', 'ACCAHA-AFIB-RF3',
    'ACCAHA-AFIB-SEV1', 'ACCAHA-AFIB-SEV2', 'ACCAHA-AFIB-SEV3',
  ],
};
