import type { SourcePack } from './types';

export const PACK_ACCAHA_VHD_2020: SourcePack = {
  source_pack_id: 'PACK.ACCAHA.VHD.2020',
  source_name: 'ACC/AHA 2020 Guideline for the Management of Patients with Valvular Heart Disease',
  source_registry_id: 'REG.ACCAHA.VHD',
  canonical_url: 'https://doi.org/10.1161/CIR.0000000000000923',
  publication_year: 2020,
  guideline_body: 'ACC/AHA',

  topic_tags: ['Valvular Heart Disease', 'Aortic Stenosis', 'Mitral Regurgitation', 'Mitral Stenosis', 'Prosthetic Valves', 'Cardiology'],
  allowed_decision_scopes: [
    'aortic stenosis severity grading',
    'aortic stenosis surgical indications',
    'TAVR vs SAVR selection',
    'mitral regurgitation severity grading',
    'mitral regurgitation surgical indications',
    'mitral stenosis management',
    'prosthetic valve anticoagulation',
  ],
  excluded_decision_scopes: [
    'tricuspid valve disease detailed management',
    'pulmonary valve disease',
    'endocarditis on prosthetic valves (see IE pack)',
    'congenital valve disease in adults (detailed)',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ACCAHA.VHD.2020.REC.01',
      display_id: 'ACCAHA-VHD-R1',
      statement: 'Aortic valve replacement (AVR) is indicated for symptomatic patients with severe aortic stenosis (Stage D). Symptoms include exertional dyspnea, angina, or syncope.',
      normalized_claim: 'Symptomatic severe AS (AVA <1.0cm2, mean gradient >40mmHg) requires aortic valve replacement.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Aortic Stenosis', page_or_location: 'Section 4.2' },
    },
    {
      rec_id: 'PACK.ACCAHA.VHD.2020.REC.02',
      display_id: 'ACCAHA-VHD-R2',
      statement: 'AVR is recommended for asymptomatic patients with severe AS and LVEF <50%.',
      normalized_claim: 'Asymptomatic severe AS with LVEF <50% is an indication for AVR.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Aortic Stenosis', page_or_location: 'Section 4.2' },
    },
    {
      rec_id: 'PACK.ACCAHA.VHD.2020.REC.03',
      display_id: 'ACCAHA-VHD-R3',
      statement: 'TAVR is recommended for patients with severe AS who are at high or prohibitive surgical risk. SAVR or TAVR is recommended for patients at intermediate surgical risk based on shared decision-making.',
      normalized_claim: 'TAVR preferred for high/prohibitive surgical risk. SAVR or TAVR for intermediate risk via shared decision-making.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'For patients <65 years or with bicuspid valve, SAVR generally preferred',
      provenance: { section: 'Aortic Stenosis — Intervention', page_or_location: 'Section 4.3' },
    },
    {
      rec_id: 'PACK.ACCAHA.VHD.2020.REC.04',
      display_id: 'ACCAHA-VHD-R4',
      statement: 'Mitral valve surgery is recommended for symptomatic patients with chronic severe primary mitral regurgitation (Stage D) and LVEF >30%.',
      normalized_claim: 'Symptomatic chronic severe primary MR with LVEF >30% requires mitral valve surgery (repair preferred over replacement).',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Mitral Regurgitation', page_or_location: 'Section 5.2' },
    },
    {
      rec_id: 'PACK.ACCAHA.VHD.2020.REC.05',
      display_id: 'ACCAHA-VHD-R5',
      statement: 'Mitral valve repair is preferred over replacement for primary MR when a durable repair is feasible.',
      normalized_claim: 'Mitral valve repair preferred over replacement for primary MR when durable repair is achievable.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Mitral Regurgitation', page_or_location: 'Section 5.3' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ACCAHA.VHD.2020.DC.01',
      display_id: 'ACCAHA-VHD-DC1',
      name: 'Severe Aortic Stenosis (Stage D)',
      components: [
        'Aortic valve area (AVA) <1.0 cm2 (or indexed AVA <0.6 cm2/m2)',
        'Mean transvalvular gradient >=40 mmHg',
        'Peak aortic jet velocity >=4.0 m/s',
        'Heavily calcified valve with severely reduced mobility',
      ],
      threshold: 'AVA <1.0 cm2 AND mean gradient >=40 mmHg in setting of normal LVEF',
      interpretation: 'Meets criteria for severe AS. If symptomatic, AVR is indicated. If asymptomatic, monitor closely or intervene if LVEF <50%.',
      normalized_claim: 'Severe AS defined by AVA <1.0cm2, mean gradient >=40mmHg, peak velocity >=4.0m/s with normal flow.',
      provenance: { section: 'Aortic Stenosis — Classification', page_or_location: 'Table 4' },
    },
    {
      criterion_id: 'PACK.ACCAHA.VHD.2020.DC.02',
      display_id: 'ACCAHA-VHD-DC2',
      name: 'Severe Primary Mitral Regurgitation',
      components: [
        'Effective regurgitant orifice area (EROA) >=0.40 cm2',
        'Regurgitant volume >=60 mL',
        'Regurgitant fraction >=50%',
        'Vena contracta width >=0.7 cm',
        'Flail leaflet or ruptured papillary muscle',
      ],
      interpretation: 'Severe primary MR warrants surgical intervention when symptomatic or when LV dilation/dysfunction develops.',
      normalized_claim: 'Severe primary MR: EROA >=0.40cm2, regurgitant volume >=60mL, regurgitant fraction >=50%, vena contracta >=0.7cm.',
      provenance: { section: 'Mitral Regurgitation — Grading', page_or_location: 'Table 8' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ACCAHA.VHD.2020.T.01',
      display_id: 'ACCAHA-VHD-T1',
      parameter: 'Aortic valve area (AVA) for severe AS',
      value: '1.0',
      unit: 'cm2',
      clinical_meaning: 'AVA <1.0 cm2 defines severe aortic stenosis. Below this threshold, valve replacement should be considered in symptomatic patients.',
      normalized_claim: 'AVA <1.0cm2 = severe AS; intervention indicated when symptomatic.',
      direction: 'below',
      provenance: { section: 'Aortic Stenosis', page_or_location: 'Table 4' },
    },
    {
      threshold_id: 'PACK.ACCAHA.VHD.2020.T.02',
      display_id: 'ACCAHA-VHD-T2',
      parameter: 'Mean gradient for severe AS',
      value: '40',
      unit: 'mmHg',
      clinical_meaning: 'Mean transvalvular gradient >=40 mmHg in the setting of normal flow indicates hemodynamically severe aortic stenosis.',
      normalized_claim: 'Mean gradient >=40mmHg with normal flow = hemodynamically severe AS.',
      direction: 'above',
      provenance: { section: 'Aortic Stenosis', page_or_location: 'Table 4' },
    },
    {
      threshold_id: 'PACK.ACCAHA.VHD.2020.T.03',
      display_id: 'ACCAHA-VHD-T3',
      parameter: 'Mitral valve area for severe MS',
      value: '1.5',
      unit: 'cm2',
      clinical_meaning: 'MVA <=1.5 cm2 defines severe mitral stenosis. Intervention indicated when symptomatic despite medical therapy.',
      normalized_claim: 'MVA <=1.5cm2 = severe MS; percutaneous commissurotomy or surgery when symptomatic.',
      direction: 'below',
      provenance: { section: 'Mitral Stenosis', page_or_location: 'Table 10' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ACCAHA.VHD.2020.TX.01',
      display_id: 'ACCAHA-VHD-TX1',
      action: 'Surgical aortic valve replacement (SAVR) for symptomatic severe AS in low/intermediate risk patients',
      normalized_claim: 'Symptomatic severe AS in low surgical risk: SAVR is standard of care, especially in patients <65 years.',
      timing: 'Once symptoms develop or LVEF <50%',
      condition: 'Symptomatic severe AS, low or intermediate surgical risk',
      contraindications: ['Prohibitive surgical risk', 'Limited life expectancy <1 year'],
      provenance: { section: 'Aortic Stenosis — Management', page_or_location: 'Section 4.3' },
    },
    {
      step_id: 'PACK.ACCAHA.VHD.2020.TX.02',
      display_id: 'ACCAHA-VHD-TX2',
      action: 'Transcatheter aortic valve replacement (TAVR) for severe AS in high/prohibitive surgical risk patients',
      normalized_claim: 'TAVR recommended for symptomatic severe AS with high or prohibitive surgical risk. Transfemoral approach preferred.',
      timing: 'Once symptomatic or LVEF <50%',
      condition: 'Symptomatic severe AS, high or prohibitive surgical risk',
      contraindications: ['Inadequate vascular access (relative)', 'Bicuspid valve (relative, depends on anatomy)'],
      provenance: { section: 'Aortic Stenosis — TAVR', page_or_location: 'Section 4.3' },
    },
    {
      step_id: 'PACK.ACCAHA.VHD.2020.TX.03',
      display_id: 'ACCAHA-VHD-TX3',
      action: 'Percutaneous mitral balloon commissurotomy (PMBC) for symptomatic severe MS with favorable valve morphology',
      normalized_claim: 'PMBC is first-line for symptomatic severe MS (MVA <=1.5cm2) with favorable valve morphology (Wilkins score <=8), no LA thrombus, and <=2+ MR.',
      timing: 'When symptomatic despite diuretics and rate control',
      condition: 'Symptomatic severe MS with favorable anatomy',
      contraindications: ['Left atrial thrombus', 'More than moderate MR', 'Unfavorable valve morphology (Wilkins >8)'],
      provenance: { section: 'Mitral Stenosis — Intervention', page_or_location: 'Section 6.2' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ACCAHA.VHD.2020.RF.01',
      display_id: 'ACCAHA-VHD-RF1',
      finding: 'Syncope or near-syncope in a patient with known aortic stenosis murmur',
      implication: 'Syncope is a late symptom of severe AS with high short-term mortality risk if untreated. Median survival ~3 years after syncope onset without AVR.',
      action: 'Urgent echocardiography. If severe AS confirmed, expedite AVR evaluation. Avoid vasodilators.',
      urgency: 'urgent',
      provenance: { section: 'Aortic Stenosis — Natural History', page_or_location: 'Section 4.1' },
    },
    {
      flag_id: 'PACK.ACCAHA.VHD.2020.RF.02',
      display_id: 'ACCAHA-VHD-RF2',
      finding: 'Acute severe mitral regurgitation: sudden-onset pulmonary edema, hypotension, and new holosystolic murmur (may be soft due to rapid equalization of pressures)',
      implication: 'Acute severe MR from chordal or papillary muscle rupture is a surgical emergency. Unlike chronic MR, the LA is non-compliant, causing severe pulmonary edema.',
      action: 'Emergent echocardiography, afterload reduction (nitroprusside or IABP), emergent surgical consultation for mitral repair/replacement.',
      urgency: 'immediate',
      provenance: { section: 'Mitral Regurgitation — Acute', page_or_location: 'Section 5.1' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ACCAHA.VHD.2020.SEV.01',
      display_id: 'ACCAHA-VHD-SEV1',
      level: 'Severe symptomatic aortic stenosis (Stage D)',
      criteria: [
        'AVA <1.0 cm2',
        'Mean gradient >=40 mmHg or peak velocity >=4.0 m/s',
        'Symptoms: exertional dyspnea, angina, syncope, or heart failure',
        'Normal or reduced LVEF',
      ],
      management_implications:
        'AVR required. Without intervention, 2-year mortality is 50%. Choice of SAVR vs TAVR depends on surgical risk, age, anatomy, and patient preference.',
      provenance: { section: 'Aortic Stenosis — Staging', page_or_location: 'Table 4' },
    },
    {
      severity_id: 'PACK.ACCAHA.VHD.2020.SEV.02',
      display_id: 'ACCAHA-VHD-SEV2',
      level: 'Low-flow low-gradient severe AS (Stage D2/D3)',
      criteria: [
        'AVA <1.0 cm2',
        'Mean gradient <40 mmHg due to reduced stroke volume',
        'LVEF <50% (classical) or normal LVEF with small LV (paradoxical)',
        'Dobutamine stress echo may show true severe AS vs pseudo-severe AS',
      ],
      management_implications:
        'Distinguish true severe AS (fixed AVA on dobutamine) from pseudo-severe (AVA increases with flow). True severe AS benefits from AVR. CT calcium scoring helpful for paradoxical low-flow.',
      provenance: { section: 'Aortic Stenosis — Low-Flow', page_or_location: 'Section 4.2' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for valvular heart disease. Covers AS severity/intervention, MR grading/surgery, MS intervention, TAVR vs SAVR.',

  all_item_ids: [
    'PACK.ACCAHA.VHD.2020.REC.01', 'PACK.ACCAHA.VHD.2020.REC.02', 'PACK.ACCAHA.VHD.2020.REC.03',
    'PACK.ACCAHA.VHD.2020.REC.04', 'PACK.ACCAHA.VHD.2020.REC.05',
    'PACK.ACCAHA.VHD.2020.DC.01', 'PACK.ACCAHA.VHD.2020.DC.02',
    'PACK.ACCAHA.VHD.2020.T.01', 'PACK.ACCAHA.VHD.2020.T.02', 'PACK.ACCAHA.VHD.2020.T.03',
    'PACK.ACCAHA.VHD.2020.TX.01', 'PACK.ACCAHA.VHD.2020.TX.02', 'PACK.ACCAHA.VHD.2020.TX.03',
    'PACK.ACCAHA.VHD.2020.RF.01', 'PACK.ACCAHA.VHD.2020.RF.02',
    'PACK.ACCAHA.VHD.2020.SEV.01', 'PACK.ACCAHA.VHD.2020.SEV.02',
  ],
  all_display_ids: [
    'ACCAHA-VHD-R1', 'ACCAHA-VHD-R2', 'ACCAHA-VHD-R3', 'ACCAHA-VHD-R4', 'ACCAHA-VHD-R5',
    'ACCAHA-VHD-DC1', 'ACCAHA-VHD-DC2',
    'ACCAHA-VHD-T1', 'ACCAHA-VHD-T2', 'ACCAHA-VHD-T3',
    'ACCAHA-VHD-TX1', 'ACCAHA-VHD-TX2', 'ACCAHA-VHD-TX3',
    'ACCAHA-VHD-RF1', 'ACCAHA-VHD-RF2',
    'ACCAHA-VHD-SEV1', 'ACCAHA-VHD-SEV2',
  ],
};
