import type { SourcePack } from './types';

export const PACK_ACCAHA_PERI_2015: SourcePack = {
  source_pack_id: 'PACK.ACCAHA.PERI.2015',
  source_name: 'ESC 2015 Guidelines for the Diagnosis and Management of Pericardial Diseases',
  source_registry_id: 'REG.ESC.PERI',
  canonical_url: 'https://doi.org/10.1093/eurheartj/ehv318',
  publication_year: 2015,
  guideline_body: 'ESC',

  topic_tags: ['Pericarditis', 'Cardiac Tamponade', 'Constrictive Pericarditis', 'Pericardial Effusion', 'Cardiology'],
  allowed_decision_scopes: [
    'acute pericarditis diagnosis',
    'acute pericarditis treatment',
    'recurrent pericarditis management',
    'cardiac tamponade recognition and treatment',
    'constrictive pericarditis diagnosis',
    'pericardial effusion management',
  ],
  excluded_decision_scopes: [
    'post-surgical pericarditis (detailed cardiac surgery protocols)',
    'neoplastic pericardial disease chemotherapy regimens',
    'tuberculous pericarditis detailed regimens',
    'congenital pericardial absence',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ACCAHA.PERI.2015.REC.01',
      display_id: 'ESC-PERI-R1',
      statement: 'NSAIDs are the mainstay of treatment for acute pericarditis. Aspirin (750-1000mg q8h) or ibuprofen (600mg q8h) are first-line agents, tapered over 1-2 weeks.',
      normalized_claim: 'Acute pericarditis first-line: aspirin 750-1000mg q8h or ibuprofen 600mg q8h, tapered over 1-2 weeks.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Acute Pericarditis — Treatment', page_or_location: 'Section 4.4' },
    },
    {
      rec_id: 'PACK.ACCAHA.PERI.2015.REC.02',
      display_id: 'ESC-PERI-R2',
      statement: 'Colchicine (0.5mg BID, or 0.5mg daily if <70kg) is recommended as adjunct to NSAIDs for the initial episode of acute pericarditis for 3 months to reduce recurrence.',
      normalized_claim: 'Colchicine 0.5mg BID added to NSAIDs for 3 months in acute pericarditis reduces recurrence (COPE, ICAP trials).',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Acute Pericarditis — Treatment', page_or_location: 'Section 4.4' },
    },
    {
      rec_id: 'PACK.ACCAHA.PERI.2015.REC.03',
      display_id: 'ESC-PERI-R3',
      statement: 'Corticosteroids should be considered only as second-line therapy for acute pericarditis when NSAIDs and colchicine are contraindicated or have failed. Low doses (prednisone 0.2-0.5 mg/kg/day) are preferred over high doses.',
      normalized_claim: 'Corticosteroids are second-line for pericarditis (use low dose 0.2-0.5mg/kg/day). High doses increase recurrence risk.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      provenance: { section: 'Acute Pericarditis — Second-Line', page_or_location: 'Section 4.4' },
    },
    {
      rec_id: 'PACK.ACCAHA.PERI.2015.REC.04',
      display_id: 'ESC-PERI-R4',
      statement: 'Exercise restriction is recommended until symptom resolution and CRP normalization for non-athletes. Athletes should restrict activity for at least 3 months.',
      normalized_claim: 'Exercise restriction until symptoms and CRP resolve; athletes restrict >=3 months.',
      strength: 'strong',
      evidence_quality: 'low',
      provenance: { section: 'Acute Pericarditis — Activity', page_or_location: 'Section 4.5' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ACCAHA.PERI.2015.DC.01',
      display_id: 'ESC-PERI-DC1',
      name: 'Acute Pericarditis Diagnostic Criteria',
      components: [
        'Chest pain: sharp, pleuritic, improved by sitting up and leaning forward',
        'Pericardial friction rub: scratchy, best heard with diaphragm at left sternal border',
        'ECG changes: diffuse ST elevation with PR depression (Stage I), followed by ST normalization (II), T-wave inversions (III), normalization (IV)',
        'New or worsening pericardial effusion on echocardiography',
      ],
      threshold: 'At least 2 of 4 criteria required for diagnosis',
      interpretation: 'Acute pericarditis is a clinical diagnosis requiring at least 2 of 4 criteria. CRP elevation and imaging support the diagnosis.',
      normalized_claim: 'Acute pericarditis diagnosis: >=2 of chest pain, friction rub, ECG changes (diffuse ST elevation + PR depression), or new pericardial effusion.',
      provenance: { section: 'Diagnosis', page_or_location: 'Table 1' },
    },
    {
      criterion_id: 'PACK.ACCAHA.PERI.2015.DC.02',
      display_id: 'ESC-PERI-DC2',
      name: 'Constrictive Pericarditis Diagnostic Features',
      components: [
        'Signs of right heart failure: elevated JVP, peripheral edema, ascites, hepatomegaly',
        'Kussmaul sign: paradoxical rise in JVP with inspiration',
        'Pericardial knock: early diastolic sound',
        'CT/MRI: pericardial thickening >=4mm and/or calcification',
        'Echo: septal bounce (ventricular interdependence), respiratory variation in mitral/tricuspid inflow',
        'Cardiac catheterization: equalization of diastolic pressures, dip-and-plateau (square root sign)',
      ],
      interpretation: 'Constrictive pericarditis must be distinguished from restrictive cardiomyopathy. Key differentiator: ventricular interdependence present in constriction, absent in restriction.',
      normalized_claim: 'Constrictive pericarditis: elevated JVP with Kussmaul sign, pericardial knock, septal bounce on echo, equalized diastolic pressures on cath. Distinguished from restrictive CMP by ventricular interdependence.',
      provenance: { section: 'Constrictive Pericarditis', page_or_location: 'Section 6' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ACCAHA.PERI.2015.T.01',
      display_id: 'ESC-PERI-T1',
      parameter: 'Pulsus paradoxus for tamponade',
      value: '10',
      unit: 'mmHg',
      clinical_meaning: 'Pulsus paradoxus >10mmHg (drop in SBP during inspiration) is a classic finding in cardiac tamponade. Higher values indicate more hemodynamic compromise.',
      normalized_claim: 'Pulsus paradoxus >10mmHg suggests cardiac tamponade; also seen in severe asthma, COPD, and PE.',
      direction: 'above',
      provenance: { section: 'Cardiac Tamponade', page_or_location: 'Section 5.2' },
    },
    {
      threshold_id: 'PACK.ACCAHA.PERI.2015.T.02',
      display_id: 'ESC-PERI-T2',
      parameter: 'Pericardial thickness for constriction',
      value: '4',
      unit: 'mm',
      clinical_meaning: 'Pericardial thickness >=4mm on CT or MRI supports the diagnosis of constrictive pericarditis, though normal thickness does not exclude it.',
      normalized_claim: 'Pericardial thickness >=4mm supports constriction diagnosis, but normal thickness does not exclude it.',
      direction: 'above',
      provenance: { section: 'Constrictive Pericarditis — Imaging', page_or_location: 'Section 6.2' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ACCAHA.PERI.2015.TX.01',
      display_id: 'ESC-PERI-TX1',
      action: 'First-line therapy for acute pericarditis: NSAID + colchicine',
      normalized_claim: 'Acute pericarditis: aspirin 750-1000mg q8h or ibuprofen 600mg q8h PLUS colchicine 0.5mg BID for 3 months.',
      timing: 'At diagnosis',
      condition: 'First episode of acute pericarditis, idiopathic or viral',
      drug_details: { drug: 'Ibuprofen + Colchicine', dose: 'Ibuprofen 600mg q8h; Colchicine 0.5mg BID', route: 'PO' , duration: 'NSAIDs 1-2 weeks taper; colchicine 3 months' },
      contraindications: ['Renal failure (colchicine dose adjust)', 'GI bleeding (avoid NSAIDs)', 'Pregnancy (avoid colchicine)'],
      provenance: { section: 'Acute Pericarditis — Treatment', page_or_location: 'Section 4.4' },
    },
    {
      step_id: 'PACK.ACCAHA.PERI.2015.TX.02',
      display_id: 'ESC-PERI-TX2',
      action: 'Pericardiocentesis for cardiac tamponade',
      normalized_claim: 'Cardiac tamponade requires emergent pericardiocentesis (echo-guided preferred). Subxiphoid approach is standard.',
      timing: 'Emergent',
      condition: 'Cardiac tamponade with hemodynamic compromise',
      contraindications: ['Aortic dissection (relative — surgical drainage preferred)', 'Loculated effusion (surgical drainage)'],
      escalation: 'Surgical pericardial window if recurrent effusion',
      provenance: { section: 'Cardiac Tamponade — Treatment', page_or_location: 'Section 5.3' },
    },
    {
      step_id: 'PACK.ACCAHA.PERI.2015.TX.03',
      display_id: 'ESC-PERI-TX3',
      action: 'Pericardiectomy for chronic constrictive pericarditis',
      normalized_claim: 'Pericardiectomy is definitive treatment for chronic constrictive pericarditis refractory to medical therapy. Trial of anti-inflammatory therapy first if transient constriction suspected.',
      timing: 'After failure of medical therapy or confirmed chronic constriction',
      condition: 'Chronic constrictive pericarditis with persistent symptoms',
      provenance: { section: 'Constrictive Pericarditis — Surgery', page_or_location: 'Section 6.4' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ACCAHA.PERI.2015.RF.01',
      display_id: 'ESC-PERI-RF1',
      finding: 'Beck triad: hypotension, muffled heart sounds, and distended neck veins in a patient with pericardial effusion',
      implication: 'Classic presentation of cardiac tamponade. Hemodynamic collapse imminent without intervention.',
      action: 'Emergent pericardiocentesis. IV fluid bolus as bridge. Avoid positive pressure ventilation if possible (reduces preload).',
      urgency: 'immediate',
      provenance: { section: 'Cardiac Tamponade', page_or_location: 'Section 5.1' },
    },
    {
      flag_id: 'PACK.ACCAHA.PERI.2015.RF.02',
      display_id: 'ESC-PERI-RF2',
      finding: 'Electrical alternans on ECG with low-voltage QRS complexes and large pericardial effusion',
      implication: 'Electrical alternans (alternating QRS amplitude) is highly specific for large pericardial effusion with tamponade physiology (swinging heart).',
      action: 'Emergent echocardiography. Prepare for pericardiocentesis if hemodynamically significant.',
      urgency: 'urgent',
      provenance: { section: 'Cardiac Tamponade — ECG', page_or_location: 'Section 5.2' },
    },
    {
      flag_id: 'PACK.ACCAHA.PERI.2015.RF.03',
      display_id: 'ESC-PERI-RF3',
      finding: 'High-risk features at presentation of acute pericarditis: fever >38°C, subacute onset, large effusion, tamponade, failure to respond to NSAIDs within 7 days',
      implication: 'Predictors of non-idiopathic etiology (bacterial, neoplastic, autoimmune). Higher complication rate.',
      action: 'Hospital admission for workup. Consider pericardiocentesis for diagnostic and therapeutic purposes. Evaluate for specific etiology.',
      urgency: 'urgent',
      provenance: { section: 'Acute Pericarditis — Triage', page_or_location: 'Section 4.3' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ACCAHA.PERI.2015.SEV.01',
      display_id: 'ESC-PERI-SEV1',
      level: 'Cardiac tamponade',
      criteria: [
        'Hemodynamic compromise: hypotension, tachycardia, pulsus paradoxus >10mmHg',
        'Beck triad: hypotension, muffled heart sounds, JVD',
        'Echo: diastolic RA collapse, early diastolic RV collapse, respiratory variation in mitral/tricuspid inflow >25%',
        'Electrical alternans or low-voltage QRS on ECG',
      ],
      management_implications:
        'Life-threatening emergency requiring emergent pericardiocentesis. IV fluids as temporizing measure. Avoid vasodilators and diuretics. Positive pressure ventilation may worsen hemodynamics.',
      provenance: { section: 'Cardiac Tamponade', page_or_location: 'Section 5' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for pericardial disease. Covers acute pericarditis diagnosis/treatment, tamponade recognition/management, and constrictive pericarditis.',

  all_item_ids: [
    'PACK.ACCAHA.PERI.2015.REC.01', 'PACK.ACCAHA.PERI.2015.REC.02', 'PACK.ACCAHA.PERI.2015.REC.03',
    'PACK.ACCAHA.PERI.2015.REC.04',
    'PACK.ACCAHA.PERI.2015.DC.01', 'PACK.ACCAHA.PERI.2015.DC.02',
    'PACK.ACCAHA.PERI.2015.T.01', 'PACK.ACCAHA.PERI.2015.T.02',
    'PACK.ACCAHA.PERI.2015.TX.01', 'PACK.ACCAHA.PERI.2015.TX.02', 'PACK.ACCAHA.PERI.2015.TX.03',
    'PACK.ACCAHA.PERI.2015.RF.01', 'PACK.ACCAHA.PERI.2015.RF.02', 'PACK.ACCAHA.PERI.2015.RF.03',
    'PACK.ACCAHA.PERI.2015.SEV.01',
  ],
  all_display_ids: [
    'ESC-PERI-R1', 'ESC-PERI-R2', 'ESC-PERI-R3', 'ESC-PERI-R4',
    'ESC-PERI-DC1', 'ESC-PERI-DC2',
    'ESC-PERI-T1', 'ESC-PERI-T2',
    'ESC-PERI-TX1', 'ESC-PERI-TX2', 'ESC-PERI-TX3',
    'ESC-PERI-RF1', 'ESC-PERI-RF2', 'ESC-PERI-RF3',
    'ESC-PERI-SEV1',
  ],
};
