// ─── DRAFT Source Pack: Iron Deficiency Anemia ───
// Generated by DI/IC Accelerator on 2026-04-16
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (19 total):
//   DI.029.077, DI.029.078, DI.029.079, DI.029.080, DI.029.081, DI.036.129, DI.226.002, DI.226.006, DI.226.010, DI.226.012, DI.226.017, DI.226.018, DI.261.014, EH.001.165, EH.006.001, EH.PEDS.009.005, IC.051.004, IC.057.054, IC.061.088
//
// Evidence classification summary:
//   Recommendations: 10 items → pack
//   Diagnostic criteria: 1 items → pack
//   Treatment steps: 0 items → pack
//   Thresholds: 5 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 3 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_ACG_IDA_2020: SourcePack = {
  "source_pack_id": "PACK.ACG.IDA.2020",
  "source_name": "American College of Gastroenterology Clinical Guidelines on Iron Deficiency Anemia",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2020,
  "guideline_body": "American College of Gastroenterology",
  "topic_tags": [
    "iron deficiency anemia",
    "anemia",
    "hematology",
    "gastroenterology",
    "malabsorption"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "workup",
    "treatment",
    "monitoring",
    "risk_stratification"
  ],
  "excluded_decision_scopes": [
    "prevention",
    "screening"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.ACG.IDA.2020.REC.01",
      "display_id": "ACG-IDA-R1",
      "statement": "Iron studies should include ferritin, TIBC, and transferrin saturation to diagnose iron deficiency anemia",
      "normalized_claim": "Iron deficiency anemia is characterized by decreased ferritin, increased TIBC, and decreased transferrin saturation",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Diagnostic workup",
      "population": "Adults with suspected iron deficiency anemia",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Decreased ferritin + increased TIBC + decreased transferrin saturation"
      }
    },
    {
      "rec_id": "PACK.ACG.IDA.2020.REC.02",
      "display_id": "ACG-IDA-R2",
      "statement": "Patients with iron deficiency anemia and history of H. pylori infection should be evaluated for peptic ulcer disease",
      "normalized_claim": "H. pylori infection is the biggest risk factor for peptic ulcer disease in patients with iron deficiency anemia",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Risk assessment",
      "population": "Patients with iron deficiency anemia and H. pylori history",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Biggest RF in iron deficiency anemia pt with h/o H. Pylori → PUD"
      }
    },
    {
      "rec_id": "PACK.ACG.IDA.2020.REC.03",
      "display_id": "ACG-IDA-R3",
      "statement": "Iron deficiency anemia with pruritic vesicles on extensor surfaces should prompt evaluation for celiac disease",
      "normalized_claim": "Celiac disease should be considered in patients with iron deficiency anemia and dermatitis herpetiformis",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "context": "Associated conditions",
      "population": "Patients with iron deficiency anemia and characteristic skin lesions",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Iron deficiency anemia + itchy vesicles on extensors → celiac disease"
      }
    },
    {
      "rec_id": "PACK.ACG.IDA.2020.REC.04",
      "display_id": "ACG-IDA-R4",
      "statement": "Progressive dysphagia in the setting of iron deficiency anemia requires urgent evaluation",
      "normalized_claim": "Progressive dysphagia is an alarm symptom that requires immediate investigation in iron deficiency anemia patients",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Alarm symptoms",
      "population": "Patients with iron deficiency anemia",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Alarm symptoms | Progressive dysphagia | Iron deficiency anemia"
      }
    },
    {
      "rec_id": "PACK.ACG.IDA.2020.REC.05",
      "display_id": "ACG-IDA-R5",
      "statement": "Right-sided colon cancer should be considered in patients with occult bleeding and iron deficiency anemia",
      "normalized_claim": "Right-sided adenocarcinoma commonly presents with occult bleeding and iron deficiency anemia due to larger lumen and liquid stools",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Malignancy screening",
      "population": "Adults with iron deficiency anemia and occult bleeding",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Right-sided Adenocarcinoma | Occult bleeding, Iron-deficiency anemia"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.ACG.IDA.2020.DC.01",
      "display_id": "ACG-IDA-DC1",
      "name": "Iron Deficiency Anemia Laboratory Criteria",
      "components": [
        "Decreased ferritin",
        "Increased TIBC",
        "Decreased transferrin saturation",
        "Microcytic anemia"
      ],
      "interpretation": "Combination of these findings confirms iron deficiency anemia",
      "normalized_claim": "Iron deficiency anemia is diagnosed by the combination of decreased ferritin, increased TIBC, decreased transferrin saturation, and microcytic anemia",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Decreased ferritin + increased TIBC + decreased transferrin saturation"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.ACG.IDA.2020.T.01",
      "display_id": "ACG-IDA-T1",
      "parameter": "Hematocrit",
      "value": "27",
      "unit": "%",
      "clinical_meaning": "Significant anemia requiring investigation for underlying cause",
      "normalized_claim": "Hematocrit of 27% in a 61-year-old male with exertional dyspnea warrants colonoscopy to rule out colon cancer",
      "direction": "below",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "61 yo M + exertional dyspnea + Hct of 27%. NBSIM? Colonoscopy"
      }
    },
    {
      "threshold_id": "PACK.ACG.IDA.2020.T.02",
      "display_id": "ACG-IDA-T2",
      "parameter": "Hemoglobin",
      "value": "7",
      "unit": "g/dL",
      "clinical_meaning": "Threshold for blood transfusion",
      "normalized_claim": "Blood transfusion is indicated when hemoglobin falls below 7 g/dL",
      "direction": "below",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "When is transfusion indicated? Hgb < 7"
      }
    },
    {
      "threshold_id": "PACK.ACG.IDA.2020.T.03",
      "display_id": "ACG-IDA-T3",
      "parameter": "MCV",
      "value": "75",
      "unit": "fL",
      "clinical_meaning": "Microcytic anemia in pediatric iron deficiency",
      "normalized_claim": "MCV of 75 fL in an 18-month-old child indicates microcytic anemia consistent with iron deficiency",
      "direction": "below",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "18 mo kiddo, picky eater, drinks lots of cow's milk -> Fe-deficiency | MCV 75"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.ACG.IDA.2020.TX.01",
      "display_id": "ACG-IDA-TX1",
      "action": "Administer oral ferrous salts for iron deficiency anemia",
      "normalized_claim": "Iron deficiency anemia in children should be treated with oral ferrous salts",
      "timing": "First-line treatment",
      "condition": "Confirmed iron deficiency anemia",
      "drug_details": {
        "drug": "ferrous salts",
        "route": "oral"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Tx w/ oral ferrous salts"
      }
    },
    {
      "step_id": "PACK.ACG.IDA.2020.TX.02",
      "display_id": "ACG-IDA-TX2",
      "action": "Perform colonoscopy to evaluate for malignancy",
      "normalized_claim": "Colonoscopy should be performed in older adults with iron deficiency anemia to rule out colon cancer",
      "timing": "Urgent evaluation",
      "condition": "Iron deficiency anemia in adults, especially with concerning symptoms",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "61 yo M + exertional dyspnea + Hct of 27%. NBSIM? Colonoscopy to r/o colon cancer"
      }
    },
    {
      "step_id": "PACK.ACG.IDA.2020.TX.03",
      "display_id": "ACG-IDA-TX3",
      "action": "Screen for restless leg syndrome in iron deficiency anemia workup",
      "normalized_claim": "Iron deficiency anemia should be ruled out in patients presenting with restless leg syndrome",
      "timing": "During initial evaluation",
      "condition": "Restless leg syndrome presentation",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "RLS workup → Rule out iron-deficiency anemia"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.ACG.IDA.2020.RF.01",
      "display_id": "ACG-IDA-RF1",
      "finding": "Progressive dysphagia with iron deficiency anemia",
      "implication": "Possible Plummer-Vinson syndrome or esophageal malignancy",
      "action": "Urgent endoscopic evaluation",
      "urgency": "urgent",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "61 yo M + similar presentation + difficulty swallowing -> Plummer-Vinson syndrome"
      }
    },
    {
      "flag_id": "PACK.ACG.IDA.2020.RF.02",
      "display_id": "ACG-IDA-RF2",
      "finding": "Occult bleeding with iron deficiency anemia",
      "implication": "Possible colorectal malignancy, especially right-sided",
      "action": "Colonoscopy and upper endoscopy evaluation",
      "urgency": "urgent",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Right-sided Adenocarcinoma | Occult bleeding, Iron-deficiency anemia"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.ACG.IDA.2020.SEV.01",
      "display_id": "ACG-IDA-SEV1",
      "level": "Severe anemia requiring transfusion",
      "criteria": [
        "Hemoglobin < 7 g/dL",
        "Symptomatic anemia"
      ],
      "management_implications": "Blood transfusion indicated along with iron replacement and investigation of underlying cause",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "When is transfusion indicated? Hgb < 7"
      }
    },
    {
      "severity_id": "PACK.ACG.IDA.2020.SEV.02",
      "display_id": "ACG-IDA-SEV2",
      "level": "Moderate anemia with symptoms",
      "criteria": [
        "Hematocrit around 27%",
        "Exertional dyspnea",
        "Adults over 60"
      ],
      "management_implications": "Urgent investigation for underlying malignancy, particularly colonoscopy",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "61 yo M + exertional dyspnea + Hct of 27%. NBSIM? Colonoscopy"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-12-19",
  "normalizer_version": 1,
  "normalization_notes": "Generated from board review sources (DI/IC/EH). Key limitations: 1) Treatment section sparse - needs expansion with iron dosing, route selection, duration; 2) Missing prevention strategies and dietary counseling; 3) Pediatric considerations limited; 4) Need verification of thresholds and management protocols against actual ACG guidelines; 5) Red flags section needs expansion with additional alarm symptoms; 6) Missing drug interactions and contraindications for iron therapy.",
  "all_item_ids": [
    "PACK.ACG.IDA.2020.REC.01",
    "PACK.ACG.IDA.2020.REC.02",
    "PACK.ACG.IDA.2020.REC.03",
    "PACK.ACG.IDA.2020.REC.04",
    "PACK.ACG.IDA.2020.REC.05",
    "PACK.ACG.IDA.2020.DC.01",
    "PACK.ACG.IDA.2020.T.01",
    "PACK.ACG.IDA.2020.T.02",
    "PACK.ACG.IDA.2020.T.03",
    "PACK.ACG.IDA.2020.TX.01",
    "PACK.ACG.IDA.2020.TX.02",
    "PACK.ACG.IDA.2020.TX.03",
    "PACK.ACG.IDA.2020.RF.01",
    "PACK.ACG.IDA.2020.RF.02",
    "PACK.ACG.IDA.2020.SEV.01",
    "PACK.ACG.IDA.2020.SEV.02"
  ],
  "all_display_ids": [
    "ACG-IDA-R1",
    "ACG-IDA-R2",
    "ACG-IDA-R3",
    "ACG-IDA-R4",
    "ACG-IDA-R5",
    "ACG-IDA-DC1",
    "ACG-IDA-T1",
    "ACG-IDA-T2",
    "ACG-IDA-T3",
    "ACG-IDA-TX1",
    "ACG-IDA-TX2",
    "ACG-IDA-TX3",
    "ACG-IDA-RF1",
    "ACG-IDA-RF2",
    "ACG-IDA-SEV1",
    "ACG-IDA-SEV2"
  ]
};
