import type { SourcePack } from './types';

export const PACK_ACG_CDIFF_2021: SourcePack = {
  source_pack_id: 'PACK.ACG.CDIFF.2021',
  source_name: 'ACG/IDSA Clinical Practice Guidelines for Clostridioides difficile Infection in Adults',
  canonical_url: 'https://doi.org/10.14309/ajg.0000000000001278',
  publication_year: 2021,
  guideline_body: 'ACG/IDSA',

  topic_tags: ['C. difficile', 'CDI', 'Infectious Disease', 'Gastroenterology', 'FMT', 'Antibiotic-Associated Diarrhea'],
  allowed_decision_scopes: [
    'C. difficile diagnosis — testing algorithms',
    'initial CDI treatment by severity',
    'fulminant CDI management',
    'recurrent CDI treatment',
    'fecal microbiota transplantation indications',
    'infection control measures',
    'bezlotoxumab for recurrence prevention',
  ],
  excluded_decision_scopes: [
    'pediatric CDI management',
    'other causes of antibiotic-associated diarrhea',
    'inflammatory bowel disease flare vs CDI',
    'Clostridium perfringens or botulinum',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ACG.CDIFF.2021.REC.01',
      display_id: 'ACG-CDIFF-R1',
      statement: 'Fidaxomicin is preferred over oral vancomycin for initial and recurrent CDI due to lower recurrence rates.',
      normalized_claim: 'Fidaxomicin 200mg BID x 10 days is preferred first-line for initial CDI. Lower recurrence rate (~13%) vs oral vancomycin (~27%).',
      strength: 'conditional',
      evidence_quality: 'moderate',
      provenance: { section: 'Initial Treatment', page_or_location: 'Section 5.1' },
    },
    {
      rec_id: 'PACK.ACG.CDIFF.2021.REC.02',
      display_id: 'ACG-CDIFF-R2',
      statement: 'Oral vancomycin 125mg QID for 10 days remains an acceptable first-line alternative for initial CDI episodes.',
      normalized_claim: 'Oral vancomycin 125mg QID x 10 days is acceptable alternative first-line for initial CDI when fidaxomicin unavailable.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Initial Treatment', page_or_location: 'Section 5.1' },
    },
    {
      rec_id: 'PACK.ACG.CDIFF.2021.REC.03',
      display_id: 'ACG-CDIFF-R3',
      statement: 'Metronidazole should NOT be used as first-line therapy for CDI. It may be used only when vancomycin and fidaxomicin are unavailable, and only for non-severe initial episodes.',
      normalized_claim: 'Metronidazole is NOT first-line for CDI. Inferior to vancomycin. Only acceptable when vancomycin/fidaxomicin unavailable for non-severe initial episodes.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Initial Treatment', page_or_location: 'Section 5.2' },
    },
    {
      rec_id: 'PACK.ACG.CDIFF.2021.REC.04',
      display_id: 'ACG-CDIFF-R4',
      statement: 'Fecal microbiota transplantation (FMT) is recommended for patients with >=3 recurrences of CDI who have failed standard antibiotic therapy.',
      normalized_claim: 'FMT recommended for >=3 CDI recurrences after failed standard antibiotics. Cure rate ~80-90%. Colonoscopic delivery preferred.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      provenance: { section: 'Recurrent CDI', page_or_location: 'Section 6.3' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ACG.CDIFF.2021.DC.01',
      display_id: 'ACG-CDIFF-DC1',
      name: 'C. difficile Diagnostic Testing Algorithm',
      components: [
        'Only test patients with >=3 unformed stools in 24 hours (do NOT test formed stool)',
        'Preferred: Multi-step algorithm — GDH screen + toxin EIA; if discordant, NAAT (PCR) as tiebreaker',
        'Alternative: NAAT alone (high sensitivity but may detect colonization without disease)',
        'Do NOT repeat testing within 7 days or test for cure',
      ],
      interpretation: 'GDH+/Toxin+ = CDI. GDH+/Toxin-/NAAT+ = possible CDI (clinical judgment). GDH-/NAAT- = not CDI. Never test asymptomatic patients or formed stool.',
      normalized_claim: 'CDI diagnosis: GDH screen + toxin EIA (NAAT tiebreaker if discordant). Only test unformed stool with >=3 stools/24h. No test of cure. No repeat within 7 days.',
      provenance: { section: 'Diagnosis', page_or_location: 'Section 3.1' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ACG.CDIFF.2021.T.01',
      display_id: 'ACG-CDIFF-T1',
      parameter: 'WBC count for severe CDI',
      value: '15000',
      unit: 'cells/microL',
      clinical_meaning: 'WBC >=15,000 defines severe CDI. Combined with serum creatinine >=1.5 mg/dL for severity classification.',
      normalized_claim: 'Severe CDI defined by WBC >=15,000 cells/microL OR serum creatinine >=1.5 mg/dL.',
      direction: 'above',
      provenance: { section: 'Severity Classification', page_or_location: 'Section 4.1' },
    },
    {
      threshold_id: 'PACK.ACG.CDIFF.2021.T.02',
      display_id: 'ACG-CDIFF-T2',
      parameter: 'Serum creatinine for severe CDI',
      value: '1.5',
      unit: 'mg/dL',
      clinical_meaning: 'Serum creatinine >=1.5 mg/dL (or >50% increase from baseline) defines severe CDI, warranting oral vancomycin over metronidazole.',
      normalized_claim: 'Serum creatinine >=1.5 mg/dL is a marker of severe CDI.',
      direction: 'above',
      provenance: { section: 'Severity Classification', page_or_location: 'Section 4.1' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ACG.CDIFF.2021.TX.01',
      display_id: 'ACG-CDIFF-TX1',
      action: 'Initial non-severe CDI treatment',
      normalized_claim: 'Non-severe initial CDI: fidaxomicin 200mg BID x 10 days (preferred) OR oral vancomycin 125mg QID x 10 days. Discontinue inciting antibiotic if possible.',
      timing: 'At diagnosis',
      condition: 'Initial CDI episode, non-severe (WBC <15K, Cr <1.5)',
      drug_details: { drug: 'Fidaxomicin', dose: '200mg BID', route: 'PO', duration: '10 days' },
      provenance: { section: 'Initial Treatment', page_or_location: 'Section 5.1' },
    },
    {
      step_id: 'PACK.ACG.CDIFF.2021.TX.02',
      display_id: 'ACG-CDIFF-TX2',
      action: 'Severe CDI treatment',
      normalized_claim: 'Severe CDI (WBC >=15K or Cr >=1.5): oral vancomycin 125mg QID x 10 days OR fidaxomicin 200mg BID x 10 days. Monitor for progression to fulminant.',
      timing: 'At diagnosis of severe CDI',
      condition: 'Severe CDI (WBC >=15,000 or serum creatinine >=1.5)',
      drug_details: { drug: 'Vancomycin', dose: '125mg QID', route: 'PO', duration: '10 days' },
      escalation: 'If progressing to fulminant: add IV metronidazole + increase vancomycin dose',
      provenance: { section: 'Severe CDI Treatment', page_or_location: 'Section 5.2' },
    },
    {
      step_id: 'PACK.ACG.CDIFF.2021.TX.03',
      display_id: 'ACG-CDIFF-TX3',
      action: 'Fulminant CDI treatment',
      normalized_claim: 'Fulminant CDI: vancomycin 500mg QID PO + vancomycin 500mg per 500mL NS rectal enema q6h + IV metronidazole 500mg q8h. Surgical consultation for colectomy.',
      timing: 'Immediately upon recognition of fulminant disease',
      condition: 'Fulminant CDI (hypotension, shock, ileus, or megacolon)',
      drug_details: { drug: 'Vancomycin', dose: '500mg QID PO + 500mg rectal q6h', route: 'PO + rectal' },
      contraindications: ['Rectal vancomycin contraindicated in recent rectal surgery'],
      escalation: 'Subtotal colectomy if no improvement, perforation, or toxic megacolon',
      provenance: { section: 'Fulminant CDI', page_or_location: 'Section 5.3' },
    },
    {
      step_id: 'PACK.ACG.CDIFF.2021.TX.04',
      display_id: 'ACG-CDIFF-TX4',
      action: 'Recurrent CDI: bezlotoxumab adjunct',
      normalized_claim: 'Bezlotoxumab (anti-toxin B monoclonal antibody) as single IV infusion during CDI antibiotic treatment reduces recurrence by ~40% in high-risk patients.',
      timing: 'During antibiotic treatment for recurrent CDI',
      condition: 'Recurrent CDI (>=1 prior episode), high risk for further recurrence (age >65, immunocompromised, severe CDI)',
      drug_details: { drug: 'Bezlotoxumab', dose: '10mg/kg', route: 'IV single infusion' },
      contraindications: ['History of heart failure (may worsen)'],
      provenance: { section: 'Recurrent CDI', page_or_location: 'Section 6.2' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ACG.CDIFF.2021.RF.01',
      display_id: 'ACG-CDIFF-RF1',
      finding: 'Fulminant CDI: hypotension, ileus (absent bowel sounds, abdominal distension), WBC >40,000 or <2,000, serum lactate >5 mmol/L, or toxic megacolon',
      implication: 'Mortality 30-50% without surgery. Colonic perforation risk. Multi-organ failure imminent.',
      action: 'ICU admission. Triple therapy: oral vancomycin 500mg QID + rectal vancomycin enemas + IV metronidazole 500mg q8h. Immediate surgical consultation. Subtotal colectomy if no improvement in 24-48 hours.',
      urgency: 'immediate',
      provenance: { section: 'Fulminant CDI', page_or_location: 'Section 5.3' },
    },
    {
      flag_id: 'PACK.ACG.CDIFF.2021.RF.02',
      display_id: 'ACG-CDIFF-RF2',
      finding: 'WBC >40,000 (leukemoid reaction) in setting of CDI',
      implication: 'Marker of fulminant disease with high mortality. Often seen with hypervirulent NAP1/BI/027 strain.',
      action: 'Escalate to fulminant CDI protocol immediately. Surgical consultation. ICU-level monitoring.',
      urgency: 'immediate',
      provenance: { section: 'Severity Markers', page_or_location: 'Section 4.2' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ACG.CDIFF.2021.SEV.01',
      display_id: 'ACG-CDIFF-SEV1',
      level: 'Non-severe CDI',
      criteria: [
        'WBC <15,000 cells/microL',
        'Serum creatinine <1.5 mg/dL',
        'No signs of systemic toxicity',
        'Able to tolerate oral medications',
      ],
      management_implications:
        'Fidaxomicin preferred or oral vancomycin. Discontinue inciting antibiotic. Outpatient management acceptable. Contact precautions in healthcare settings.',
      provenance: { section: 'Severity Classification', page_or_location: 'Section 4.1' },
    },
    {
      severity_id: 'PACK.ACG.CDIFF.2021.SEV.02',
      display_id: 'ACG-CDIFF-SEV2',
      level: 'Severe CDI',
      criteria: [
        'WBC >=15,000 cells/microL',
        'OR serum creatinine >=1.5 mg/dL (or >50% increase from baseline)',
        'Abdominal tenderness',
        'No hypotension, shock, or ileus',
      ],
      management_implications:
        'Oral vancomycin or fidaxomicin. Inpatient monitoring recommended. Serial labs (WBC, Cr, lactate). Surgical consultation if worsening. Monitor for progression to fulminant.',
      provenance: { section: 'Severity Classification', page_or_location: 'Section 4.1' },
    },
    {
      severity_id: 'PACK.ACG.CDIFF.2021.SEV.03',
      display_id: 'ACG-CDIFF-SEV3',
      level: 'Fulminant CDI',
      criteria: [
        'Hypotension or vasopressor requirement',
        'Ileus (absent bowel sounds, abdominal distension)',
        'Toxic megacolon (colon >6 cm)',
        'WBC >40,000 or <2,000 (leukemoid reaction or leukopenia)',
        'Serum lactate >5 mmol/L',
        'End-organ dysfunction',
      ],
      management_implications:
        'ICU admission mandatory. Triple therapy: high-dose oral vancomycin (500mg QID) + rectal vancomycin enemas (q6h) + IV metronidazole (500mg q8h). Emergent surgical consultation. Subtotal colectomy with end ileostomy if perforation, refractory shock, or no improvement in 24-48h. Mortality 30-50%.',
      provenance: { section: 'Fulminant CDI', page_or_location: 'Section 5.3' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for C. difficile infection. Covers diagnostic algorithm, severity classification, fidaxomicin vs vancomycin, fulminant CDI triple therapy, recurrent CDI with bezlotoxumab and FMT.',

  all_item_ids: [
    'PACK.ACG.CDIFF.2021.REC.01', 'PACK.ACG.CDIFF.2021.REC.02', 'PACK.ACG.CDIFF.2021.REC.03',
    'PACK.ACG.CDIFF.2021.REC.04',
    'PACK.ACG.CDIFF.2021.DC.01',
    'PACK.ACG.CDIFF.2021.T.01', 'PACK.ACG.CDIFF.2021.T.02',
    'PACK.ACG.CDIFF.2021.TX.01', 'PACK.ACG.CDIFF.2021.TX.02', 'PACK.ACG.CDIFF.2021.TX.03',
    'PACK.ACG.CDIFF.2021.TX.04',
    'PACK.ACG.CDIFF.2021.RF.01', 'PACK.ACG.CDIFF.2021.RF.02',
    'PACK.ACG.CDIFF.2021.SEV.01', 'PACK.ACG.CDIFF.2021.SEV.02', 'PACK.ACG.CDIFF.2021.SEV.03',
  ],
  all_display_ids: [
    'ACG-CDIFF-R1', 'ACG-CDIFF-R2', 'ACG-CDIFF-R3', 'ACG-CDIFF-R4',
    'ACG-CDIFF-DC1',
    'ACG-CDIFF-T1', 'ACG-CDIFF-T2',
    'ACG-CDIFF-TX1', 'ACG-CDIFF-TX2', 'ACG-CDIFF-TX3', 'ACG-CDIFF-TX4',
    'ACG-CDIFF-RF1', 'ACG-CDIFF-RF2',
    'ACG-CDIFF-SEV1', 'ACG-CDIFF-SEV2', 'ACG-CDIFF-SEV3',
  ],
};
