import type { SourcePack } from './types';

export const PACK_ACG_IBD_2019: SourcePack = {
  source_pack_id: 'PACK.ACG.IBD.2019',
  source_name: 'ACG Clinical Guidelines: Ulcerative Colitis and Crohn\'s Disease in Adults',
  canonical_url: 'https://doi.org/10.14309/ajg.0000000000000101',
  publication_year: 2019,
  guideline_body: 'ACG',

  topic_tags: ['IBD', 'Ulcerative Colitis', 'Crohn\'s Disease', 'Gastroenterology', 'Toxic Megacolon'],
  allowed_decision_scopes: [
    'UC vs Crohn differentiation',
    'UC severity classification',
    'Crohn phenotype classification',
    '5-ASA therapy for mild UC',
    'biologic therapy for moderate-severe IBD',
    'immunomodulator selection',
    'surgical indications for UC',
    'surgical indications for Crohn disease',
    'toxic megacolon management',
    'colorectal cancer surveillance in IBD',
  ],
  excluded_decision_scopes: [
    'pediatric IBD management',
    'microscopic colitis',
    'irritable bowel syndrome',
    'celiac disease',
    'C. difficile colitis (covered in separate pack)',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ACG.IBD.2019.REC.01',
      display_id: 'ACG-IBD-R1',
      statement: 'Oral and topical 5-ASA (mesalamine) is recommended as first-line therapy for induction and maintenance of remission in mild-to-moderate ulcerative colitis.',
      normalized_claim: '5-ASA (mesalamine) is first-line for mild-to-moderate UC induction and maintenance. Combination oral + rectal 5-ASA is superior to either alone.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'Not effective for Crohn disease',
      provenance: { section: 'UC Treatment', page_or_location: 'Section 5.1' },
    },
    {
      rec_id: 'PACK.ACG.IBD.2019.REC.02',
      display_id: 'ACG-IBD-R2',
      statement: 'Anti-TNF therapy (infliximab, adalimumab, golimumab) is recommended for moderate-to-severe UC and Crohn disease refractory to conventional therapy.',
      normalized_claim: 'Anti-TNF agents (infliximab, adalimumab) for moderate-severe UC and Crohn disease failing conventional therapy. Infliximab preferred for acute severe UC.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Biologic Therapy', page_or_location: 'Section 6.1' },
    },
    {
      rec_id: 'PACK.ACG.IBD.2019.REC.03',
      display_id: 'ACG-IBD-R3',
      statement: 'Corticosteroids are effective for inducing remission in moderate-to-severe IBD but should not be used for maintenance therapy due to long-term adverse effects.',
      normalized_claim: 'Corticosteroids induce remission in moderate-severe IBD but are NOT maintenance therapy. Steroid dependence requires immunomodulator or biologic escalation.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Corticosteroid Use', page_or_location: 'Section 5.3' },
    },
    {
      rec_id: 'PACK.ACG.IBD.2019.REC.04',
      display_id: 'ACG-IBD-R4',
      statement: 'Colonoscopic surveillance for colorectal cancer should begin 8 years after IBD diagnosis in patients with extensive colitis, with biopsies every 1-2 years.',
      normalized_claim: 'CRC surveillance colonoscopy starting 8 years after IBD diagnosis with extensive colitis. Repeat every 1-2 years with chromoendoscopy or random biopsies.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Cancer Surveillance', page_or_location: 'Section 9.1' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ACG.IBD.2019.DC.01',
      display_id: 'ACG-IBD-DC1',
      name: 'Ulcerative Colitis vs Crohn Disease Differentiation',
      components: [
        'UC: Continuous mucosal inflammation starting at rectum, extending proximally; limited to colon',
        'UC: Mucosal and submucosal involvement only (non-transmural)',
        'UC: Crypt abscesses, pseudopolyps on histology',
        'Crohn: Skip lesions (discontinuous), can affect any part of GI tract (mouth to anus)',
        'Crohn: Transmural inflammation with non-caseating granulomas (30% of biopsies)',
        'Crohn: Fistulae, strictures, perianal disease',
      ],
      interpretation: 'UC = continuous, mucosal, colon only. Crohn = skip, transmural, anywhere in GI. ~10% remain indeterminate colitis.',
      normalized_claim: 'UC: continuous mucosal inflammation from rectum proximally, colon only. Crohn: skip lesions, transmural, any GI location, granulomas, fistulae. 10% indeterminate.',
      provenance: { section: 'Diagnosis', page_or_location: 'Section 2.1' },
    },
    {
      criterion_id: 'PACK.ACG.IBD.2019.DC.02',
      display_id: 'ACG-IBD-DC2',
      name: 'Montreal Classification - Crohn Disease Phenotype',
      components: [
        'Age at diagnosis: A1 (<16y), A2 (17-40y), A3 (>40y)',
        'Location: L1 (ileal), L2 (colonic), L3 (ileocolonic), L4 (upper GI modifier)',
        'Behavior: B1 (non-stricturing, non-penetrating), B2 (stricturing), B3 (penetrating), p (perianal modifier)',
      ],
      interpretation: 'Montreal classification guides prognosis and therapy. B2/B3 phenotypes have higher surgical rates. Perianal disease requires combined medical and surgical approach.',
      normalized_claim: 'Montreal classification for Crohn: Age (A1-3), Location (L1-4), Behavior (B1-3, p). B2 (stricturing) and B3 (penetrating) predict surgical need.',
      provenance: { section: 'Classification', page_or_location: 'Section 2.2' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ACG.IBD.2019.T.01',
      display_id: 'ACG-IBD-T1',
      parameter: 'Fecal calprotectin for IBD activity',
      value: '250',
      unit: 'mcg/g',
      clinical_meaning: 'Fecal calprotectin >250 mcg/g strongly suggests active mucosal inflammation in known IBD. Useful for monitoring disease activity and predicting relapse.',
      normalized_claim: 'Fecal calprotectin >250 mcg/g indicates active mucosal inflammation in IBD; useful for non-invasive monitoring.',
      direction: 'above',
      provenance: { section: 'Monitoring', page_or_location: 'Section 3.2' },
    },
    {
      threshold_id: 'PACK.ACG.IBD.2019.T.02',
      display_id: 'ACG-IBD-T2',
      parameter: 'CRC surveillance initiation after IBD diagnosis',
      value: '8',
      unit: 'years',
      clinical_meaning: 'Colonoscopic surveillance for CRC begins 8 years after symptom onset in patients with colitis extending beyond the splenic flexure.',
      normalized_claim: 'CRC surveillance starts 8 years after IBD diagnosis for extensive colitis (beyond splenic flexure).',
      direction: 'above',
      provenance: { section: 'Cancer Surveillance', page_or_location: 'Section 9.1' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ACG.IBD.2019.TX.01',
      display_id: 'ACG-IBD-TX1',
      action: 'Mild UC: 5-ASA induction therapy',
      normalized_claim: 'Mild UC: oral mesalamine 2.4-4.8g/day + rectal mesalamine suppository/enema. Combination oral + rectal superior to either alone.',
      timing: 'At diagnosis of mild UC',
      condition: 'Mild ulcerative colitis (Truelove-Witts: <4 stools/day, no systemic toxicity)',
      drug_details: { drug: 'Mesalamine', dose: '2.4-4.8g/day oral + rectal', route: 'PO + PR' },
      provenance: { section: 'UC Treatment', page_or_location: 'Section 5.1' },
    },
    {
      step_id: 'PACK.ACG.IBD.2019.TX.02',
      display_id: 'ACG-IBD-TX2',
      action: 'Moderate-severe UC/Crohn: Biologic therapy',
      normalized_claim: 'Moderate-severe IBD: anti-TNF (infliximab 5mg/kg IV induction at 0, 2, 6 weeks then q8 weeks; or adalimumab SC). Vedolizumab (gut-selective) for TNF failures.',
      timing: 'After failure of conventional therapy or for high-risk features at diagnosis',
      condition: 'Moderate-severe UC or Crohn disease refractory to 5-ASA/steroids',
      drug_details: { drug: 'Infliximab', dose: '5mg/kg', route: 'IV at weeks 0, 2, 6, then q8 weeks' },
      escalation: 'Vedolizumab or ustekinumab for anti-TNF failure',
      provenance: { section: 'Biologic Therapy', page_or_location: 'Section 6.1' },
    },
    {
      step_id: 'PACK.ACG.IBD.2019.TX.03',
      display_id: 'ACG-IBD-TX3',
      action: 'Acute severe UC: IV corticosteroids + surgical consultation',
      normalized_claim: 'Acute severe UC (Truelove-Witts): IV methylprednisolone 60mg/day. If no response in 3 days, rescue therapy (infliximab or cyclosporine) or colectomy.',
      timing: 'Hospital admission for acute severe UC',
      condition: 'Acute severe UC (>=6 bloody stools/day + systemic toxicity: HR >90, ESR >30, temp >37.8C)',
      drug_details: { drug: 'Methylprednisolone', dose: '60mg/day', route: 'IV' },
      contraindications: ['Uncontrolled infection', 'Perforation'],
      escalation: 'Infliximab rescue or colectomy if no response in 3 days',
      provenance: { section: 'Acute Severe UC', page_or_location: 'Section 5.4' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ACG.IBD.2019.RF.01',
      display_id: 'ACG-IBD-RF1',
      finding: 'Toxic megacolon: Transverse colon diameter >6 cm on abdominal X-ray with systemic toxicity (fever, tachycardia, leukocytosis, anemia)',
      implication: 'Risk of perforation and sepsis. Mortality 20-30% if perforated. Medical emergency requiring surgical standby.',
      action: 'NPO, NG decompression, IV steroids, broad-spectrum antibiotics, serial abdominal exams q6-8h. Emergent colectomy if perforation, clinical deterioration, or no improvement in 48-72 hours.',
      urgency: 'immediate',
      provenance: { section: 'Toxic Megacolon', page_or_location: 'Section 5.5' },
    },
    {
      flag_id: 'PACK.ACG.IBD.2019.RF.02',
      display_id: 'ACG-IBD-RF2',
      finding: 'Crohn disease with intra-abdominal abscess (fever, abdominal mass, leukocytosis)',
      implication: 'Requires drainage before initiating immunosuppressive therapy. Biologic or immunomodulator use with undrained abscess risks sepsis.',
      action: 'CT-guided percutaneous drainage + IV antibiotics. Delay biologic therapy until abscess resolved. Surgical resection if drainage fails.',
      urgency: 'urgent',
      provenance: { section: 'Crohn Complications', page_or_location: 'Section 7.2' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ACG.IBD.2019.SEV.01',
      display_id: 'ACG-IBD-SEV1',
      level: 'Mild UC (Truelove-Witts)',
      criteria: [
        '<4 bloody stools per day',
        'No systemic toxicity (normal HR, temperature, ESR, hemoglobin)',
        'No extraintestinal manifestations',
      ],
      management_implications:
        'Outpatient management with oral + rectal 5-ASA. No steroids needed. Response expected within 4-8 weeks. If no response, escalate to budesonide MMX or oral prednisone.',
      provenance: { section: 'UC Severity', page_or_location: 'Section 4.1' },
    },
    {
      severity_id: 'PACK.ACG.IBD.2019.SEV.02',
      display_id: 'ACG-IBD-SEV2',
      level: 'Moderate-severe UC',
      criteria: [
        '4-6 bloody stools per day',
        'Mild systemic toxicity (mild anemia, low-grade fever)',
        'Elevated inflammatory markers (CRP, ESR)',
      ],
      management_implications:
        'Oral corticosteroids for induction. Biologic therapy (anti-TNF, vedolizumab, tofacitinib) for steroid-refractory or steroid-dependent disease. Immunomodulator (azathioprine, 6-MP) for maintenance.',
      provenance: { section: 'UC Severity', page_or_location: 'Section 4.1' },
    },
    {
      severity_id: 'PACK.ACG.IBD.2019.SEV.03',
      display_id: 'ACG-IBD-SEV3',
      level: 'Acute severe/fulminant UC',
      criteria: [
        '>=6 bloody stools per day',
        'Systemic toxicity: HR >90, temperature >37.8C, hemoglobin <10.5 g/dL, ESR >30',
        'Abdominal tenderness, distension',
        'Colonic dilation >6 cm = toxic megacolon',
      ],
      management_implications:
        'Hospital admission required. IV methylprednisolone 60mg/day. Surgical consultation on admission. C. diff testing. If no response in 3 days: rescue infliximab/cyclosporine or colectomy. Toxic megacolon: emergent colectomy if perforation or no response in 48-72h.',
      provenance: { section: 'Acute Severe UC', page_or_location: 'Section 5.4' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for IBD. Covers UC vs Crohn differentiation, UC severity classification (Truelove-Witts), 5-ASA for mild UC, biologics for moderate-severe, toxic megacolon, and CRC surveillance.',

  all_item_ids: [
    'PACK.ACG.IBD.2019.REC.01', 'PACK.ACG.IBD.2019.REC.02', 'PACK.ACG.IBD.2019.REC.03',
    'PACK.ACG.IBD.2019.REC.04',
    'PACK.ACG.IBD.2019.DC.01', 'PACK.ACG.IBD.2019.DC.02',
    'PACK.ACG.IBD.2019.T.01', 'PACK.ACG.IBD.2019.T.02',
    'PACK.ACG.IBD.2019.TX.01', 'PACK.ACG.IBD.2019.TX.02', 'PACK.ACG.IBD.2019.TX.03',
    'PACK.ACG.IBD.2019.RF.01', 'PACK.ACG.IBD.2019.RF.02',
    'PACK.ACG.IBD.2019.SEV.01', 'PACK.ACG.IBD.2019.SEV.02', 'PACK.ACG.IBD.2019.SEV.03',
  ],
  all_display_ids: [
    'ACG-IBD-R1', 'ACG-IBD-R2', 'ACG-IBD-R3', 'ACG-IBD-R4',
    'ACG-IBD-DC1', 'ACG-IBD-DC2',
    'ACG-IBD-T1', 'ACG-IBD-T2',
    'ACG-IBD-TX1', 'ACG-IBD-TX2', 'ACG-IBD-TX3',
    'ACG-IBD-RF1', 'ACG-IBD-RF2',
    'ACG-IBD-SEV1', 'ACG-IBD-SEV2', 'ACG-IBD-SEV3',
  ],
};
