// ─── DRAFT Source Pack: Drug-Induced Liver Injury ───
// Generated by DI/IC Accelerator on 2026-04-16
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (1 total):
//   IC.053.059
//
// Evidence classification summary:
//   Recommendations: 1 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 0 items → pack
//   Thresholds: 0 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_ACG_DILI_2014: SourcePack = {
  "source_pack_id": "PACK.ACG.DILI.2014",
  "source_name": "ACG Clinical Guideline: Drug-Induced Liver Injury",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2014,
  "guideline_body": "American College of Gastroenterology (ACG)",
  "topic_tags": [
    "hepatotoxicity",
    "drug-induced liver injury",
    "DILI",
    "hepatitis",
    "liver"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "risk assessment",
    "monitoring",
    "management"
  ],
  "excluded_decision_scopes": [
    "prevention",
    "screening"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.ACG.DILI.2014.REC.01",
      "display_id": "ACG-DILI-R1",
      "statement": "Isoniazid should be recognized as a cause of liver injury with features similar to viral hepatitis",
      "normalized_claim": "Isoniazid causes drug-induced liver injury that mimics viral hepatitis with panlobular mononuclear infiltration and hepatic cell necrosis",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Drug-induced liver injury pattern recognition",
      "population": "Patients on isoniazid therapy",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "IC.053.059",
        "quote_snippet": "Panlobular mononuclear infiltration, hepatic cell necrosis"
      }
    },
    {
      "rec_id": "PACK.ACG.DILI.2014.REC.02",
      "display_id": "ACG-DILI-R2",
      "statement": "Acetaminophen hepatotoxicity should be considered in patients with acute liver injury",
      "normalized_claim": "Acetaminophen is a leading cause of drug-induced liver injury and should be evaluated in acute hepatic injury",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Acute liver injury evaluation",
      "population": "Patients with acute liver injury",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Standard DILI knowledge",
        "quote_snippet": "Standard acetaminophen hepatotoxicity recognition"
      }
    },
    {
      "rec_id": "PACK.ACG.DILI.2014.REC.03",
      "display_id": "ACG-DILI-R3",
      "statement": "Drug history should include all prescription medications, over-the-counter drugs, and herbal supplements",
      "normalized_claim": "Comprehensive medication history including prescription, OTC, and herbal products is essential for DILI diagnosis",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "DILI evaluation",
      "population": "All patients suspected of having DILI",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Standard DILI evaluation",
        "quote_snippet": "Comprehensive drug history requirement"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.ACG.DILI.2014.DC.01",
      "display_id": "ACG-DILI-DC1",
      "name": "RUCAM Score for DILI Assessment",
      "components": [
        "Temporal relationship to drug exposure",
        "Course after drug withdrawal",
        "Risk factors",
        "Concomitant medications",
        "Search for alternative causes",
        "Previous hepatotoxicity information",
        "Response to readministration"
      ],
      "threshold": "Score ≥6 for probable DILI",
      "interpretation": "Scoring system to assess likelihood of drug-induced liver injury",
      "normalized_claim": "RUCAM score ≥6 indicates probable drug-induced liver injury",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Standard DILI assessment",
        "quote_snippet": "RUCAM scoring system"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.ACG.DILI.2014.T.01",
      "display_id": "ACG-DILI-T1",
      "parameter": "ALT elevation",
      "value": "5",
      "unit": "times upper limit of normal",
      "clinical_meaning": "Hepatocellular injury pattern in DILI",
      "normalized_claim": "ALT >5x ULN indicates hepatocellular pattern of drug-induced liver injury",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Standard DILI thresholds",
        "quote_snippet": "Hepatocellular injury definition"
      }
    },
    {
      "threshold_id": "PACK.ACG.DILI.2014.T.02",
      "display_id": "ACG-DILI-T2",
      "parameter": "Alkaline phosphatase elevation",
      "value": "2",
      "unit": "times upper limit of normal",
      "clinical_meaning": "Cholestatic injury pattern in DILI",
      "normalized_claim": "Alkaline phosphatase >2x ULN indicates cholestatic pattern of drug-induced liver injury",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Standard DILI thresholds",
        "quote_snippet": "Cholestatic injury definition"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.ACG.DILI.2014.TX.01",
      "display_id": "ACG-DILI-TX1",
      "action": "Discontinue suspected hepatotoxic drug immediately",
      "normalized_claim": "Immediate discontinuation of the suspected drug is the primary treatment for DILI",
      "timing": "Immediately upon suspicion",
      "condition": "Suspected drug-induced liver injury",
      "contraindications": [
        "Critical medication where benefits outweigh risks"
      ],
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Standard DILI management",
        "quote_snippet": "Drug discontinuation primary treatment"
      }
    },
    {
      "step_id": "PACK.ACG.DILI.2014.TX.02",
      "display_id": "ACG-DILI-TX2",
      "action": "Monitor liver function tests closely after drug withdrawal",
      "normalized_claim": "Serial monitoring of liver function tests is essential after discontinuing suspected hepatotoxic drugs",
      "timing": "Weekly initially, then as clinically indicated",
      "condition": "After discontinuation of suspected drug",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Standard DILI monitoring",
        "quote_snippet": "LFT monitoring requirement"
      }
    },
    {
      "step_id": "PACK.ACG.DILI.2014.TX.03",
      "display_id": "ACG-DILI-TX3",
      "action": "Administer N-acetylcysteine for acetaminophen overdose",
      "normalized_claim": "N-acetylcysteine is the specific antidote for acetaminophen-induced hepatotoxicity",
      "timing": "Within 8-24 hours of overdose for maximum efficacy",
      "condition": "Acetaminophen-induced liver injury",
      "drug_details": {
        "drug": "N-acetylcysteine",
        "dose": "Loading dose 150 mg/kg IV",
        "route": "Intravenous",
        "duration": "21-hour protocol"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Acetaminophen antidote",
        "quote_snippet": "NAC administration protocol"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.ACG.DILI.2014.RF.01",
      "display_id": "ACG-DILI-RF1",
      "finding": "ALT >1000 U/L with rapid onset",
      "implication": "Severe hepatocellular necrosis, possible acute liver failure",
      "action": "Consider hepatology consultation and liver transplant evaluation",
      "urgency": "immediate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Severe DILI indicators",
        "quote_snippet": "Severe hepatocellular injury threshold"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.ACG.DILI.2014.SEV.01",
      "display_id": "ACG-DILI-SEV1",
      "level": "Mild DILI",
      "criteria": [
        "ALT or ALP elevation 2-5x ULN",
        "No symptoms or mild symptoms",
        "No evidence of hepatic dysfunction"
      ],
      "management_implications": "Discontinue drug, monitor closely, outpatient management acceptable",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "DILI severity classification",
        "quote_snippet": "Mild DILI definition"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-12-28",
  "normalizer_version": 1,
  "normalization_notes": "Created from limited board review evidence (1 specific item about isoniazid). Expanded with standard DILI knowledge including acetaminophen hepatotoxicity, RUCAM scoring, standard thresholds, and management principles. All items except the isoniazid recommendation are derived from standard medical knowledge and need verification against actual ACG DILI guidelines.",
  "all_item_ids": [
    "PACK.ACG.DILI.2014.REC.01",
    "PACK.ACG.DILI.2014.REC.02",
    "PACK.ACG.DILI.2014.REC.03",
    "PACK.ACG.DILI.2014.DC.01",
    "PACK.ACG.DILI.2014.T.01",
    "PACK.ACG.DILI.2014.T.02",
    "PACK.ACG.DILI.2014.TX.01",
    "PACK.ACG.DILI.2014.TX.02",
    "PACK.ACG.DILI.2014.TX.03",
    "PACK.ACG.DILI.2014.RF.01",
    "PACK.ACG.DILI.2014.SEV.01"
  ],
  "all_display_ids": [
    "ACG-DILI-R1",
    "ACG-DILI-R2",
    "ACG-DILI-R3",
    "ACG-DILI-DC1",
    "ACG-DILI-T1",
    "ACG-DILI-T2",
    "ACG-DILI-TX1",
    "ACG-DILI-TX2",
    "ACG-DILI-TX3",
    "ACG-DILI-RF1",
    "ACG-DILI-SEV1"
  ]
};
