import type { SourcePack } from './types';

export const pack: SourcePack = {
  source_pack_id: 'PACK.ACG.GIB.2021',
  source_name: 'ACG Clinical Guideline: Upper Gastrointestinal and Lower Gastrointestinal Bleeding 2021/2023',
  source_registry_id: 'REG.ACG.GIB',
  canonical_url: 'https://journals.lww.com/ajg/fulltext/2021/05000/acg_clinical_guideline__upper_gastrointestinal_and.14.aspx',
  publication_year: 2021,
  guideline_body: 'American College of Gastroenterology',

  topic_tags: ['Upper GI Bleeding', 'Lower GI Bleeding', 'PUD', 'Variceal Bleeding', 'Diverticular Bleeding', 'Ischemic Colitis', 'Gastroenterology'],
  allowed_decision_scopes: [
    'upper GI bleed risk stratification',
    'PPI therapy in upper GI bleed',
    'endoscopy timing in GI bleed',
    'transfusion thresholds in GI bleed',
    'variceal bleeding management',
    'PUD bleeding endoscopic hemostasis',
    'lower GI bleed evaluation and management',
    'diverticular bleeding management',
    'Glasgow-Blatchford score interpretation',
    'post-endoscopy PPI therapy',
  ],
  excluded_decision_scopes: [
    'obscure GI bleeding workup (capsule endoscopy)',
    'chronic iron deficiency anemia evaluation',
    'H. pylori eradication regimens',
    'NSAID gastropathy prevention',
    'small bowel bleeding evaluation',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ACG.GIB.2021.REC.01',
      display_id: 'ACG-GIB-R1',
      statement: 'A restrictive transfusion strategy with a hemoglobin threshold of <=7 g/dL is recommended for hemodynamically stable patients with upper GI bleeding, targeting Hgb 7-9 g/dL.',
      normalized_claim: 'Transfuse at Hgb <=7 g/dL in hemodynamically stable upper GIB patients. Target Hgb 7-9 g/dL. Liberal transfusion worsens outcomes.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'Liberal transfusion may increase portal pressure and worsen variceal bleeding',
      provenance: { section: 'Resuscitation', page_or_location: 'Section 3.1' },
    },
    {
      rec_id: 'PACK.ACG.GIB.2021.REC.02',
      display_id: 'ACG-GIB-R2',
      statement: 'IV PPI therapy (e.g., pantoprazole 80mg bolus followed by 8mg/hr continuous infusion) should be initiated in patients with suspected upper GI bleeding and high-risk stigmata on endoscopy.',
      normalized_claim: 'High-risk PUD: PPI 80mg IV bolus then 8mg/hr continuous infusion x72h after endoscopic hemostasis. Reduces rebleeding.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Acid Suppression', page_or_location: 'Section 4.2' },
    },
    {
      rec_id: 'PACK.ACG.GIB.2021.REC.03',
      display_id: 'ACG-GIB-R3',
      statement: 'Upper endoscopy (EGD) should be performed within 24 hours of presentation in patients with upper GI bleeding for both diagnostic and therapeutic purposes.',
      normalized_claim: 'EGD within 24h for upper GI bleed. Urgent (within 12h) if hemodynamic instability, bloody NG aspirate, or high-risk features.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Endoscopy Timing', page_or_location: 'Section 4.1' },
    },
    {
      rec_id: 'PACK.ACG.GIB.2021.REC.04',
      display_id: 'ACG-GIB-R4',
      statement: 'IV octreotide (50mcg bolus followed by 50mcg/hr infusion) should be started as early as possible in suspected variceal upper GI bleeding, in combination with antibiotics.',
      normalized_claim: 'Suspected variceal bleed: IV octreotide 50mcg bolus then 50mcg/hr + empiric IV ceftriaxone 1g daily. Start before endoscopy.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Variceal Bleeding', page_or_location: 'Section 5.1' },
    },
    {
      rec_id: 'PACK.ACG.GIB.2021.REC.05',
      display_id: 'ACG-GIB-R5',
      statement: 'The Glasgow-Blatchford Score (GBS) should be used for pre-endoscopy risk stratification. Patients with GBS 0-1 may be considered for outpatient management.',
      normalized_claim: 'Glasgow-Blatchford Score 0-1: very low risk, consider outpatient endoscopy. GBS >=6: high risk, requires inpatient management and urgent endoscopy.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 2.1' },
    },
    {
      rec_id: 'PACK.ACG.GIB.2021.REC.06',
      display_id: 'ACG-GIB-R6',
      statement: 'Endoscopic hemostasis should be performed for actively bleeding ulcers and ulcers with non-bleeding visible vessels (Forrest Ia, Ib, IIa). Combination therapy (epinephrine injection + thermal or mechanical hemostasis) is preferred over monotherapy.',
      normalized_claim: 'Endoscopic hemostasis for Forrest Ia/Ib/IIa ulcers. Combination therapy (epi + clip or thermal) superior to epi alone.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Endoscopic Hemostasis', page_or_location: 'Section 4.3' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ACG.GIB.2021.DC.01',
      display_id: 'ACG-GIB-DC1',
      name: 'Glasgow-Blatchford Score (GBS)',
      components: [
        'BUN (mg/dL): <18.2=0, 18.2-22.3=2, 22.4-27.9=3, 28-69.9=4, >=70=6',
        'Hemoglobin (g/dL) men: >=13=0, 12-12.9=1, 10-11.9=3, <10=6',
        'Hemoglobin (g/dL) women: >=12=0, 10-11.9=1, <10=6',
        'Systolic BP: >=110=0, 100-109=1, 90-99=2, <90=3',
        'Heart rate >=100: +1',
        'Melena: +1',
        'Syncope: +2',
        'Hepatic disease: +2',
        'Heart failure: +2',
      ],
      threshold: 'Score range 0-23. Score 0-1 = very low risk. Score >=6 = high risk.',
      interpretation: 'GBS 0-1: very low risk for intervention, consider outpatient management. GBS >=6: high risk, requires inpatient management with urgent endoscopy within 24h. GBS is the best validated pre-endoscopy risk score for UGIB.',
      normalized_claim: 'Glasgow-Blatchford Score (0-23): 0-1 = very low risk (outpatient); >=6 = high risk (inpatient, urgent endoscopy). Best pre-endoscopy tool for UGIB.',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 2.1' },
    },
    {
      criterion_id: 'PACK.ACG.GIB.2021.DC.02',
      display_id: 'ACG-GIB-DC2',
      name: 'Forrest Classification of Ulcer Bleeding',
      components: [
        'Ia: Spurting arterial hemorrhage (active)',
        'Ib: Oozing hemorrhage (active)',
        'IIa: Non-bleeding visible vessel (high risk)',
        'IIb: Adherent clot (intermediate risk)',
        'IIc: Flat pigmented spot (low risk)',
        'III: Clean-base ulcer (low risk)',
      ],
      interpretation: 'Forrest Ia/Ib/IIa: require endoscopic hemostasis (rebleed risk 55-90% without treatment). IIb: consider clot removal and treat underlying lesion. IIc/III: low rebleed risk (<5%), no endoscopic therapy needed.',
      normalized_claim: 'Forrest classification guides endoscopic management: Ia/Ib/IIa = hemostasis required (rebleed 55-90%). IIc/III = no therapy needed (rebleed <5%).',
      provenance: { section: 'Endoscopic Findings', page_or_location: 'Section 4.3' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ACG.GIB.2021.T.01',
      display_id: 'ACG-GIB-T1',
      parameter: 'Hemoglobin transfusion trigger',
      value: '7',
      unit: 'g/dL',
      clinical_meaning: 'Transfuse pRBCs when Hgb <=7 g/dL in hemodynamically stable patients. More liberal threshold (<=8-9 g/dL) may be appropriate in active CAD, hemodynamic instability, or ongoing brisk hemorrhage.',
      normalized_claim: 'Transfuse at Hgb <=7 g/dL (stable patients). Consider <=9 g/dL with active CAD or hemodynamic instability.',
      direction: 'below',
      provenance: { section: 'Resuscitation', page_or_location: 'Section 3.1' },
    },
    {
      threshold_id: 'PACK.ACG.GIB.2021.T.02',
      display_id: 'ACG-GIB-T2',
      parameter: 'Endoscopy timing — upper GI bleed',
      value: '24',
      unit: 'hours',
      clinical_meaning: 'EGD within 24 hours for all patients with upper GI bleeding. Urgent EGD within 12 hours for high-risk patients (hemodynamic instability, bloody NG aspirate, GBS >=6).',
      normalized_claim: 'EGD within 24h for upper GIB. Within 12h if hemodynamically unstable or GBS >=6.',
      direction: 'below',
      provenance: { section: 'Endoscopy Timing', page_or_location: 'Section 4.1' },
    },
    {
      threshold_id: 'PACK.ACG.GIB.2021.T.03',
      display_id: 'ACG-GIB-T3',
      parameter: 'IV PPI bolus dose for upper GIB',
      value: '80',
      unit: 'mg',
      clinical_meaning: 'Pantoprazole (or equivalent) 80mg IV bolus followed by 8mg/hr continuous infusion for 72 hours after endoscopic hemostasis of high-risk PUD.',
      normalized_claim: 'PPI protocol for high-risk PUD: 80mg IV bolus then 8mg/hr drip x72h post-endoscopic hemostasis.',
      direction: 'above',
      provenance: { section: 'Acid Suppression', page_or_location: 'Section 4.2' },
    },
    {
      threshold_id: 'PACK.ACG.GIB.2021.T.04',
      display_id: 'ACG-GIB-T4',
      parameter: 'Glasgow-Blatchford Score for outpatient management',
      value: '1',
      unit: 'points',
      clinical_meaning: 'GBS 0-1 identifies patients at very low risk for needing intervention. These patients may be safely discharged for outpatient endoscopy.',
      normalized_claim: 'GBS 0-1: safe for outpatient management and elective endoscopy.',
      direction: 'below',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 2.1' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ACG.GIB.2021.TX.01',
      display_id: 'ACG-GIB-TX1',
      action: 'Upper GIB initial management: Resuscitation + PPI + risk stratification',
      normalized_claim: 'Upper GIB: 2 large-bore IVs, IV crystalloid, type and cross, restrictive transfusion (Hgb <=7), IV PPI, GBS scoring, EGD within 24h.',
      timing: 'Immediately upon presentation',
      condition: 'Upper gastrointestinal bleeding (hematemesis, melena, coffee-ground emesis)',
      drug_details: { drug: 'Pantoprazole', dose: '80mg IV bolus', route: 'IV' },
      contraindications: ['PPI allergy (use H2RA as alternative)'],
      escalation: 'If hemodynamically unstable: aggressive fluid resuscitation, liberal transfusion threshold, urgent EGD within 12h, ICU admission.',
      provenance: { section: 'Initial Management', page_or_location: 'Section 3.1' },
    },
    {
      step_id: 'PACK.ACG.GIB.2021.TX.02',
      display_id: 'ACG-GIB-TX2',
      action: 'Variceal upper GIB: Octreotide + antibiotics + EVL',
      normalized_claim: 'Variceal bleed: octreotide 50mcg IV bolus then 50mcg/hr + ceftriaxone 1g IV daily + EVL at endoscopy. Restrictive transfusion. Avoid over-resuscitation.',
      timing: 'Octreotide and antibiotics immediately; EVL within 12 hours',
      condition: 'Known or suspected variceal hemorrhage',
      drug_details: { drug: 'Octreotide', dose: '50mcg IV bolus then 50mcg/hr', route: 'IV', duration: '3-5 days' },
      escalation: 'If EVL fails: balloon tamponade as bridge, then emergent TIPS. Consider early TIPS (within 72h) for Child-Pugh B with active bleeding or Child-Pugh C (10-13).',
      provenance: { section: 'Variceal Bleeding', page_or_location: 'Section 5.1' },
    },
    {
      step_id: 'PACK.ACG.GIB.2021.TX.03',
      display_id: 'ACG-GIB-TX3',
      action: 'Lower GIB: Hemodynamic stabilization and colonoscopy',
      normalized_claim: 'Lower GIB: resuscitation, correct coagulopathy, colonoscopy within 24h after bowel prep. CT angiography if brisk bleeding precludes colonoscopy.',
      timing: 'Colonoscopy within 24 hours after adequate bowel preparation',
      condition: 'Lower gastrointestinal bleeding (hematochezia)',
      escalation: 'If massive bleeding or hemodynamic instability: CT angiography to localize, then IR embolization or surgical consultation. Tagged RBC scan if intermittent bleeding.',
      provenance: { section: 'Lower GI Bleeding', page_or_location: 'Section 6.1' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ACG.GIB.2021.RF.01',
      display_id: 'ACG-GIB-RF1',
      finding: 'Hemodynamic instability: SBP <90 mmHg, heart rate >120, orthostatic changes, or altered mental status in the setting of GI bleeding',
      implication: 'Indicates significant acute blood loss (>30% blood volume). High mortality risk. Requires aggressive resuscitation and urgent endoscopy.',
      action: 'Two large-bore IVs, crystalloid bolus, emergent type and crossmatch, liberal transfusion threshold, ICU admission, urgent EGD within 12h.',
      urgency: 'immediate',
      provenance: { section: 'Resuscitation', page_or_location: 'Section 3.1' },
    },
    {
      flag_id: 'PACK.ACG.GIB.2021.RF.02',
      display_id: 'ACG-GIB-RF2',
      finding: 'Fresh hematemesis (bright red blood per emesis) or large-volume bloody NG aspirate',
      implication: 'Suggests active arterial upper GI bleeding. High rebleed and mortality risk. Needs urgent endoscopic intervention.',
      action: 'Airway protection if massive hematemesis, urgent EGD within 12h, IV PPI infusion, consider prokinetic (erythromycin 250mg IV) 30min before EGD to improve visualization.',
      urgency: 'immediate',
      provenance: { section: 'Endoscopy Timing', page_or_location: 'Section 4.1' },
    },
    {
      flag_id: 'PACK.ACG.GIB.2021.RF.03',
      display_id: 'ACG-GIB-RF3',
      finding: 'Dropping hemoglobin despite transfusion of >=2 units pRBCs',
      implication: 'Indicates ongoing active hemorrhage exceeding replacement. May need interventional radiology or surgical intervention.',
      action: 'Activate massive transfusion protocol if needed. Urgent endoscopy if not yet performed. If post-endoscopy, consider repeat endoscopy, IR angiographic embolization, or surgical consultation.',
      urgency: 'immediate',
      provenance: { section: 'Refractory Bleeding', page_or_location: 'Section 4.4' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ACG.GIB.2021.SEV.01',
      display_id: 'ACG-GIB-SEV1',
      level: 'Low-risk upper GI bleed',
      criteria: [
        'Glasgow-Blatchford Score 0-1',
        'Hemodynamically stable (SBP >110, HR <100)',
        'No melena or syncope',
        'Hemoglobin >=12 g/dL (men) or >=10 g/dL (women)',
        'BUN <18.2 mg/dL',
        'No hepatic disease or heart failure',
      ],
      management_implications: 'Very low risk of needing intervention. May be safely discharged for outpatient EGD within 72 hours. Start oral PPI. Avoid anticoagulants/NSAIDs. Close follow-up with gastroenterology.',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 2.1' },
    },
    {
      severity_id: 'PACK.ACG.GIB.2021.SEV.02',
      display_id: 'ACG-GIB-SEV2',
      level: 'Moderate-risk upper GI bleed',
      criteria: [
        'Glasgow-Blatchford Score 2-5',
        'Hemodynamically stable but with risk factors',
        'Melena or coffee-ground emesis present',
        'Hemoglobin 10-12 g/dL',
        'Mild BUN elevation',
      ],
      management_implications: 'Admit for inpatient observation. EGD within 24 hours. IV PPI. Monitor hemoglobin q6-8h. Floor-level care appropriate unless clinical deterioration.',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 2.1' },
    },
    {
      severity_id: 'PACK.ACG.GIB.2021.SEV.03',
      display_id: 'ACG-GIB-SEV3',
      level: 'High-risk upper GI bleed',
      criteria: [
        'Glasgow-Blatchford Score >=6',
        'Hemodynamic instability (SBP <100 or HR >100)',
        'Active hematemesis or bloody NG aspirate',
        'Hemoglobin <10 g/dL or dropping',
        'Syncope or altered mental status',
        'Known cirrhosis or suspected variceal source',
      ],
      management_implications: 'ICU admission. Urgent EGD within 12 hours. Aggressive resuscitation with restrictive transfusion strategy. IV PPI infusion (80mg bolus + 8mg/hr). If variceal source suspected: add octreotide + ceftriaxone. Interventional radiology and surgery on standby. Mortality risk 5-10% even with intervention.',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 2.2' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for GI bleeding. Covers upper and lower GIB risk stratification, PPI therapy, endoscopy timing, variceal bleed management, and Forrest classification for question generation.',

  all_item_ids: [
    'PACK.ACG.GIB.2021.REC.01', 'PACK.ACG.GIB.2021.REC.02', 'PACK.ACG.GIB.2021.REC.03',
    'PACK.ACG.GIB.2021.REC.04', 'PACK.ACG.GIB.2021.REC.05', 'PACK.ACG.GIB.2021.REC.06',
    'PACK.ACG.GIB.2021.DC.01', 'PACK.ACG.GIB.2021.DC.02',
    'PACK.ACG.GIB.2021.T.01', 'PACK.ACG.GIB.2021.T.02', 'PACK.ACG.GIB.2021.T.03', 'PACK.ACG.GIB.2021.T.04',
    'PACK.ACG.GIB.2021.TX.01', 'PACK.ACG.GIB.2021.TX.02', 'PACK.ACG.GIB.2021.TX.03',
    'PACK.ACG.GIB.2021.RF.01', 'PACK.ACG.GIB.2021.RF.02', 'PACK.ACG.GIB.2021.RF.03',
    'PACK.ACG.GIB.2021.SEV.01', 'PACK.ACG.GIB.2021.SEV.02', 'PACK.ACG.GIB.2021.SEV.03',
  ],
  all_display_ids: [
    'ACG-GIB-R1', 'ACG-GIB-R2', 'ACG-GIB-R3', 'ACG-GIB-R4', 'ACG-GIB-R5', 'ACG-GIB-R6',
    'ACG-GIB-DC1', 'ACG-GIB-DC2',
    'ACG-GIB-T1', 'ACG-GIB-T2', 'ACG-GIB-T3', 'ACG-GIB-T4',
    'ACG-GIB-TX1', 'ACG-GIB-TX2', 'ACG-GIB-TX3',
    'ACG-GIB-RF1', 'ACG-GIB-RF2', 'ACG-GIB-RF3',
    'ACG-GIB-SEV1', 'ACG-GIB-SEV2', 'ACG-GIB-SEV3',
  ],
};
