import type { SourcePack } from './types';

export const PACK_ACOG_PREEC_2020: SourcePack = {
  source_pack_id: 'PACK.ACOG.PREEC.2020',
  source_name: 'ACOG Practice Bulletin No. 222: Gestational Hypertension and Preeclampsia',
  source_registry_id: 'REG.ACOG.PREEC',
  canonical_url: 'https://doi.org/10.1097/AOG.0000000000003891',
  publication_year: 2020,
  guideline_body: 'ACOG',

  topic_tags: ['Preeclampsia', 'Eclampsia', 'HELLP', 'Gestational Hypertension', 'OB/GYN'],
  allowed_decision_scopes: [
    'preeclampsia diagnosis',
    'severe feature identification',
    'magnesium sulfate prophylaxis',
    'antihypertensive therapy in pregnancy',
    'delivery timing in preeclampsia',
    'HELLP syndrome management',
    'eclampsia management',
    'postpartum preeclampsia monitoring',
  ],
  excluded_decision_scopes: [
    'chronic hypertension management outside pregnancy',
    'superimposed preeclampsia on chronic HTN (detailed)',
    'long-term cardiovascular risk counseling',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ACOG.PREEC.2020.REC.01',
      display_id: 'ACOG-PREEC-R1',
      statement: 'Low-dose aspirin (81 mg/day) is recommended starting at 12-28 weeks for women at high risk of preeclampsia.',
      normalized_claim: 'Aspirin 81 mg daily starting 12-28 weeks gestation reduces preeclampsia risk in high-risk women.',
      strength: 'strong',
      evidence_quality: 'high',
      population: 'Women with prior preeclampsia, multifetal gestation, chronic HTN, pregestational DM, renal disease, or autoimmune disease',
      provenance: { section: 'Prevention', page_or_location: 'Section 3' },
    },
    {
      rec_id: 'PACK.ACOG.PREEC.2020.REC.02',
      display_id: 'ACOG-PREEC-R2',
      statement: 'Magnesium sulfate is recommended for seizure prophylaxis in women with preeclampsia with severe features and for treatment of eclampsia.',
      normalized_claim: 'MgSO4 is first-line for eclampsia seizure prophylaxis and treatment; superior to diazepam and phenytoin.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Seizure Prophylaxis', page_or_location: 'Section 7' },
    },
    {
      rec_id: 'PACK.ACOG.PREEC.2020.REC.03',
      display_id: 'ACOG-PREEC-R3',
      statement: 'Delivery is recommended at 37 0/7 weeks for preeclampsia without severe features and at 34 0/7 weeks for preeclampsia with severe features.',
      normalized_claim: 'Deliver at 37 wks without severe features; deliver at 34 wks with severe features after corticosteroids.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Timing of Delivery', page_or_location: 'Section 8' },
    },
    {
      rec_id: 'PACK.ACOG.PREEC.2020.REC.04',
      display_id: 'ACOG-PREEC-R4',
      statement: 'Acute-onset severe hypertension (SBP >=160 or DBP >=110) in pregnancy requires treatment within 30-60 minutes to prevent maternal stroke.',
      normalized_claim: 'Treat severe-range BP (>=160/110) within 30-60 min with IV labetalol, IV hydralazine, or PO nifedipine.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Acute Management', page_or_location: 'Section 6' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ACOG.PREEC.2020.DC.01',
      display_id: 'ACOG-PREEC-DC1',
      name: 'Preeclampsia Diagnostic Criteria',
      components: [
        'New-onset hypertension (BP >=140/90 on two occasions at least 4 hours apart) after 20 weeks gestation',
        'Proteinuria (>=300 mg/24h, protein/creatinine ratio >=0.3, or dipstick >=2+)',
        'OR in absence of proteinuria: thrombocytopenia, renal insufficiency, elevated liver enzymes, pulmonary edema, or cerebral/visual symptoms',
      ],
      interpretation: 'Preeclampsia diagnosed by hypertension after 20 wks plus proteinuria or end-organ dysfunction.',
      normalized_claim: 'Preeclampsia = BP >=140/90 after 20 wks + proteinuria OR end-organ damage (platelets <100K, Cr >1.1, LFTs 2x normal, pulmonary edema, cerebral/visual sx).',
      provenance: { section: 'Diagnosis', page_or_location: 'Section 4' },
    },
    {
      criterion_id: 'PACK.ACOG.PREEC.2020.DC.02',
      display_id: 'ACOG-PREEC-DC2',
      name: 'HELLP Syndrome Criteria',
      components: [
        'Hemolysis (elevated LDH, schistocytes on smear, elevated indirect bilirubin)',
        'Elevated liver enzymes (AST/ALT >=2x upper limit of normal)',
        'Low platelets (<100,000/microL)',
      ],
      interpretation: 'HELLP is a severe variant of preeclampsia requiring urgent delivery consideration.',
      normalized_claim: 'HELLP = hemolysis + elevated liver enzymes + platelets <100K; considered a severe form of preeclampsia requiring delivery.',
      provenance: { section: 'HELLP Syndrome', page_or_location: 'Section 5' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ACOG.PREEC.2020.T.01',
      display_id: 'ACOG-PREEC-T1',
      parameter: 'Severe-range systolic blood pressure',
      value: '160',
      unit: 'mmHg',
      clinical_meaning: 'SBP >=160 mmHg defines severe-range hypertension requiring urgent treatment to prevent stroke.',
      normalized_claim: 'SBP >=160 mmHg is a severe feature of preeclampsia requiring treatment within 30-60 minutes.',
      direction: 'above',
      provenance: { section: 'Severe Features', page_or_location: 'Section 4.2' },
    },
    {
      threshold_id: 'PACK.ACOG.PREEC.2020.T.02',
      display_id: 'ACOG-PREEC-T2',
      parameter: 'Platelet count for severe preeclampsia',
      value: '100000',
      unit: '/microL',
      clinical_meaning: 'Platelets <100,000 is a severe feature of preeclampsia and component of HELLP syndrome.',
      normalized_claim: 'Platelets <100,000/microL defines thrombocytopenia as a severe feature of preeclampsia.',
      direction: 'below',
      provenance: { section: 'Severe Features', page_or_location: 'Section 4.2' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ACOG.PREEC.2020.TX.01',
      display_id: 'ACOG-PREEC-TX1',
      action: 'Magnesium sulfate loading and maintenance for seizure prophylaxis',
      normalized_claim: 'MgSO4: 4-6g IV loading dose over 20-30 min, then 1-2g/hr maintenance. Monitor reflexes, urine output, respiratory rate.',
      timing: 'Upon diagnosis of severe features or eclampsia',
      condition: 'Preeclampsia with severe features or eclampsia',
      drug_details: { drug: 'Magnesium sulfate', dose: '4-6g load, 1-2g/hr maintenance', route: 'IV' },
      contraindications: ['Myasthenia gravis', 'Severe renal failure without dose adjustment'],
      provenance: { section: 'Seizure Prophylaxis', page_or_location: 'Section 7' },
    },
    {
      step_id: 'PACK.ACOG.PREEC.2020.TX.02',
      display_id: 'ACOG-PREEC-TX2',
      action: 'IV labetalol for acute severe hypertension in pregnancy',
      normalized_claim: 'IV labetalol 20 mg initial dose, escalate to 40 mg then 80 mg every 10 min (max 300 mg) for acute severe HTN in pregnancy.',
      timing: 'Within 30-60 minutes of severe-range BP',
      condition: 'SBP >=160 or DBP >=110 mmHg',
      drug_details: { drug: 'Labetalol', dose: '20-80mg escalating', route: 'IV' },
      contraindications: ['Asthma', 'Heart block', 'Decompensated heart failure'],
      escalation: 'Switch to IV hydralazine or PO nifedipine if labetalol fails',
      provenance: { section: 'Acute Hypertension Management', page_or_location: 'Section 6' },
    },
    {
      step_id: 'PACK.ACOG.PREEC.2020.TX.03',
      display_id: 'ACOG-PREEC-TX3',
      action: 'Delivery for preeclampsia without severe features at 37 weeks',
      normalized_claim: 'Preeclampsia without severe features: expectant management until 37 0/7 wks with twice-weekly monitoring, then deliver.',
      timing: 'At 37 0/7 weeks gestation',
      condition: 'Preeclampsia without severe features, stable maternal and fetal status',
      provenance: { section: 'Timing of Delivery', page_or_location: 'Section 8' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ACOG.PREEC.2020.RF.01',
      display_id: 'ACOG-PREEC-RF1',
      finding: 'Eclamptic seizure: new-onset tonic-clonic seizure in a pregnant or postpartum woman with hypertension',
      implication: 'Life-threatening emergency with risk of maternal death, aspiration, placental abruption.',
      action: 'MgSO4 bolus, secure airway, lateral decubitus position, delivery after maternal stabilization.',
      urgency: 'immediate',
      provenance: { section: 'Eclampsia', page_or_location: 'Section 9' },
    },
    {
      flag_id: 'PACK.ACOG.PREEC.2020.RF.02',
      display_id: 'ACOG-PREEC-RF2',
      finding: 'Severe persistent headache, visual changes (scotomata, blurred vision), or RUQ/epigastric pain in preeclamptic patient',
      implication: 'Indicates impending eclampsia or hepatic involvement (subcapsular hematoma, rupture).',
      action: 'Initiate MgSO4, check labs (CBC, LFTs, Cr, LDH), plan delivery.',
      urgency: 'urgent',
      provenance: { section: 'Severe Features', page_or_location: 'Section 4.2' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ACOG.PREEC.2020.SEV.01',
      display_id: 'ACOG-PREEC-SEV1',
      level: 'Preeclampsia with severe features',
      criteria: [
        'SBP >=160 mmHg or DBP >=110 mmHg on two occasions at least 4 hours apart',
        'Platelets <100,000/microL',
        'Serum creatinine >1.1 mg/dL or doubling of baseline',
        'Liver transaminases >=2x upper limit of normal',
        'Pulmonary edema',
        'New-onset headache unresponsive to medication or visual disturbances',
      ],
      management_implications:
        'Admit, initiate MgSO4, treat severe-range BP, administer betamethasone if <34 wks, deliver at 34 0/7 wks or sooner if maternal/fetal deterioration. Continuous fetal monitoring.',
      provenance: { section: 'Severe Features Classification', page_or_location: 'Section 4.2' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'OB/GYN pack covering preeclampsia spectrum: diagnosis, severe features, HELLP, eclampsia, MgSO4, delivery timing.',

  all_item_ids: [
    'PACK.ACOG.PREEC.2020.REC.01', 'PACK.ACOG.PREEC.2020.REC.02', 'PACK.ACOG.PREEC.2020.REC.03',
    'PACK.ACOG.PREEC.2020.REC.04', 'PACK.ACOG.PREEC.2020.DC.01', 'PACK.ACOG.PREEC.2020.DC.02',
    'PACK.ACOG.PREEC.2020.T.01', 'PACK.ACOG.PREEC.2020.T.02', 'PACK.ACOG.PREEC.2020.TX.01',
    'PACK.ACOG.PREEC.2020.TX.02', 'PACK.ACOG.PREEC.2020.TX.03', 'PACK.ACOG.PREEC.2020.RF.01',
    'PACK.ACOG.PREEC.2020.RF.02', 'PACK.ACOG.PREEC.2020.SEV.01',
  ],
  all_display_ids: [
    'ACOG-PREEC-R1', 'ACOG-PREEC-R2', 'ACOG-PREEC-R3', 'ACOG-PREEC-R4',
    'ACOG-PREEC-DC1', 'ACOG-PREEC-DC2',
    'ACOG-PREEC-T1', 'ACOG-PREEC-T2',
    'ACOG-PREEC-TX1', 'ACOG-PREEC-TX2', 'ACOG-PREEC-TX3',
    'ACOG-PREEC-RF1', 'ACOG-PREEC-RF2',
    'ACOG-PREEC-SEV1',
  ],
};
