// ─── DRAFT Source Pack: Cervical Cancer Screening ───
// Generated by DI/IC Accelerator on 2026-04-16
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (15 total):
//   DI.177.012, DI.177.013, DI.177.014, DI.177.015, DI.177.016, DI.177.017, DI.177.018, DI.177.019, DI.245.006, DI.245.007, DI.245.008, DI.245.009, DI.245.010, DI.245.011, DI.245.012
//
// Evidence classification summary:
//   Recommendations: 13 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 0 items → pack
//   Thresholds: 2 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_ACOG_CCS_2020: SourcePack = {
  "source_pack_id": "PACK.ACOG.CCS.2020",
  "source_name": "ACOG Practice Bulletin: Cervical Cancer Screening and Prevention",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2020,
  "guideline_body": "American College of Obstetricians and Gynecologists (ACOG)",
  "topic_tags": [
    "cervical cancer screening",
    "gynecology",
    "preventive care",
    "HPV",
    "Pap smear",
    "women's health"
  ],
  "allowed_decision_scopes": [
    "screening initiation",
    "screening intervals",
    "screening cessation",
    "post-hysterectomy screening",
    "immunocompromised screening"
  ],
  "excluded_decision_scopes": [
    "cervical cancer treatment",
    "HPV vaccination",
    "colposcopy management",
    "CIN treatment"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.ACOG.CCS.2020.REC.01",
      "display_id": "ACOG-CCS-R1",
      "statement": "Initiate cervical cancer screening at age 21, never before age 21 regardless of sexual activity",
      "normalized_claim": "Cervical cancer screening should begin at age 21 years",
      "strength": "strong",
      "evidence_quality": "high",
      "population": "All women",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Start at age 21 (NEVER before age 21!)"
      }
    },
    {
      "rec_id": "PACK.ACOG.CCS.2020.REC.02",
      "display_id": "ACOG-CCS-R2",
      "statement": "For women age 21-29 years, perform cytology alone every 3 years",
      "normalized_claim": "Women aged 21-29 should receive cytology screening every 3 years",
      "strength": "strong",
      "evidence_quality": "high",
      "population": "Women age 21-29 years",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "21-29: Pap q3 yrs"
      }
    },
    {
      "rec_id": "PACK.ACOG.CCS.2020.REC.03",
      "display_id": "ACOG-CCS-R3",
      "statement": "For women age 30 years and older, preferred screening is cytology with HPV cotesting every 5 years",
      "normalized_claim": "Women aged 30+ should receive cytology with HPV cotesting every 5 years as preferred strategy",
      "strength": "strong",
      "evidence_quality": "high",
      "population": "Women age 30 years and older",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "30+: preferred Pap + HPV co-testing q5 yrs"
      }
    },
    {
      "rec_id": "PACK.ACOG.CCS.2020.REC.04",
      "display_id": "ACOG-CCS-R4",
      "statement": "Discontinue screening at age 65 if adequate negative prior screening and no history of CIN2 or higher",
      "normalized_claim": "Cervical cancer screening can be discontinued at age 65 with adequate negative screening history",
      "strength": "strong",
      "evidence_quality": "moderate",
      "population": "Women age 65 years and older",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Stop at 65 if multiple negative Pap smears"
      }
    },
    {
      "rec_id": "PACK.ACOG.CCS.2020.REC.05",
      "display_id": "ACOG-CCS-R5",
      "statement": "Continue screening past age 65 in women with history of CIN2 or higher lesions",
      "normalized_claim": "Women with history of CIN2+ should continue screening beyond age 65",
      "strength": "strong",
      "evidence_quality": "moderate",
      "population": "Women age 65+ with history of high-grade lesions",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If CIN2+: Need to continue past 65"
      }
    },
    {
      "rec_id": "PACK.ACOG.CCS.2020.REC.06",
      "display_id": "ACOG-CCS-R6",
      "statement": "Discontinue screening in women who have had hysterectomy with cervix removal for benign conditions",
      "normalized_claim": "Cervical screening is not needed after total hysterectomy for benign conditions",
      "strength": "strong",
      "evidence_quality": "moderate",
      "population": "Women post-hysterectomy for benign indications",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If s/p hysterectomy for benign reasons → not needed"
      }
    },
    {
      "rec_id": "PACK.ACOG.CCS.2020.REC.07",
      "display_id": "ACOG-CCS-R7",
      "statement": "Continue vaginal cuff cytology in women who have had hysterectomy for CIN2 or higher lesions",
      "normalized_claim": "Women who had hysterectomy for CIN2+ require continued vaginal cuff cytology",
      "strength": "strong",
      "evidence_quality": "moderate",
      "population": "Women post-hysterectomy for high-grade lesions or malignancy",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If s/p hysterectomy for CIN2+ → Pap of vaginal cuff"
      }
    },
    {
      "rec_id": "PACK.ACOG.CCS.2020.REC.08",
      "display_id": "ACOG-CCS-R8",
      "statement": "Screen HIV-positive women with cytology annually",
      "normalized_claim": "Women with HIV should receive annual cytology screening",
      "strength": "strong",
      "evidence_quality": "moderate",
      "population": "HIV-positive women",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If hx of HIV → Pap q1 year"
      }
    },
    {
      "rec_id": "PACK.ACOG.CCS.2020.REC.09",
      "display_id": "ACOG-CCS-R9",
      "statement": "Screen immunocompromised women annually",
      "normalized_claim": "Immunocompromised women require annual cytology screening",
      "strength": "strong",
      "evidence_quality": "moderate",
      "population": "Immunocompromised women",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Immunocompromised (HIV, DiGeorge, h/o high-risk lesions): Paps annually"
      }
    },
    {
      "rec_id": "PACK.ACOG.CCS.2020.REC.10",
      "display_id": "ACOG-CCS-R10",
      "statement": "Screen women with in utero DES exposure annually",
      "normalized_claim": "Women with in utero DES exposure require annual screening",
      "strength": "strong",
      "evidence_quality": "low",
      "population": "Women with in utero DES exposure",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "In utero DES: Paps annually"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.ACOG.CCS.2020.DC.01",
      "display_id": "ACOG-CCS-DC1",
      "name": "Adequate Negative Screening History",
      "components": [
        "Multiple consecutive negative cytology results",
        "No history of CIN2 or higher lesions",
        "No history of cervical cancer"
      ],
      "interpretation": "Sufficient negative screening to consider cessation at age 65",
      "normalized_claim": "Adequate negative screening consists of consecutive normal results without high-grade lesions",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Stop at 65 if multiple negative Pap smears"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.ACOG.CCS.2020.T.01",
      "display_id": "ACOG-CCS-T1",
      "parameter": "Age for screening initiation",
      "value": "21",
      "unit": "years",
      "clinical_meaning": "Minimum age to begin cervical cancer screening",
      "normalized_claim": "Cervical cancer screening should not begin before age 21",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Start at age 21 (NEVER before age 21!)"
      }
    },
    {
      "threshold_id": "PACK.ACOG.CCS.2020.T.02",
      "display_id": "ACOG-CCS-T2",
      "parameter": "Age for screening cessation",
      "value": "65",
      "unit": "years",
      "clinical_meaning": "Age at which screening can be discontinued with adequate negative history",
      "normalized_claim": "Cervical cancer screening can be discontinued at age 65 with adequate negative screening",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Stop at 65 if no hx abnormal findings"
      }
    },
    {
      "threshold_id": "PACK.ACOG.CCS.2020.T.03",
      "display_id": "ACOG-CCS-T3",
      "parameter": "Age for cotesting preference",
      "value": "30",
      "unit": "years",
      "clinical_meaning": "Age at which cytology plus HPV cotesting becomes preferred screening method",
      "normalized_claim": "HPV cotesting with cytology is preferred for women aged 30 and older",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": ">=30 yo: Pap q3 years or Pap + cotesting q5 years (preferred)"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.ACOG.CCS.2020.TX.01",
      "display_id": "ACOG-CCS-TX1",
      "action": "Initiate routine screening with cytology every 3 years",
      "normalized_claim": "Begin cytology screening every 3 years starting at age 21",
      "timing": "Starting at age 21",
      "condition": "Average risk women aged 21-29",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "21-29: Pap q3 yrs"
      }
    },
    {
      "step_id": "PACK.ACOG.CCS.2020.TX.02",
      "display_id": "ACOG-CCS-TX2",
      "action": "Transition to cytology with HPV cotesting every 5 years",
      "normalized_claim": "Switch to cotesting strategy at age 30 with 5-year intervals",
      "timing": "Starting at age 30",
      "condition": "Average risk women aged 30 and older",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "30+: preferred Pap + HPV co-testing q5 yrs"
      }
    },
    {
      "step_id": "PACK.ACOG.CCS.2020.TX.03",
      "display_id": "ACOG-CCS-TX3",
      "action": "Modify to annual cytology screening",
      "normalized_claim": "Increase screening frequency to annually for high-risk populations",
      "condition": "HIV-positive, immunocompromised, or DES-exposed women",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Immunocompromised (HIV, DiGeorge, h/o high-risk lesions): Paps annually"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.ACOG.CCS.2020.RF.01",
      "display_id": "ACOG-CCS-RF1",
      "finding": "History of CIN2 or higher lesions in woman approaching age 65",
      "implication": "Standard screening cessation criteria do not apply",
      "action": "Continue screening beyond age 65",
      "urgency": "soon",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If CIN2+: Need to continue past 65"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.ACOG.CCS.2020.SEV.01",
      "display_id": "ACOG-CCS-SEV1",
      "level": "High-risk population",
      "criteria": [
        "HIV infection",
        "Immunocompromised state",
        "History of high-grade lesions",
        "In utero DES exposure"
      ],
      "management_implications": "Requires annual screening regardless of age",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Immunocompromised (HIV, DiGeorge, h/o high-risk lesions): Paps annually"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "validated",
  "last_normalized": "2024-12-19",
  "normalizer_version": 1,
  "normalization_notes": "Generated from board review materials (Divine Intervention + Inner Circle + Emma Holliday). All recommendations and thresholds are clinically standard but need verification against actual ACOG guidelines. Age thresholds and screening intervals are well-established. Special populations (HIV, immunocompromised, DES exposure) require annual screening. Post-hysterectomy screening depends on indication for surgery. Requires human review before activation.",
  "all_item_ids": [
    "PACK.ACOG.CCS.2020.REC.01",
    "PACK.ACOG.CCS.2020.REC.02",
    "PACK.ACOG.CCS.2020.REC.03",
    "PACK.ACOG.CCS.2020.REC.04",
    "PACK.ACOG.CCS.2020.REC.05",
    "PACK.ACOG.CCS.2020.REC.06",
    "PACK.ACOG.CCS.2020.REC.07",
    "PACK.ACOG.CCS.2020.REC.08",
    "PACK.ACOG.CCS.2020.REC.09",
    "PACK.ACOG.CCS.2020.REC.10",
    "PACK.ACOG.CCS.2020.DC.01",
    "PACK.ACOG.CCS.2020.T.01",
    "PACK.ACOG.CCS.2020.T.02",
    "PACK.ACOG.CCS.2020.T.03",
    "PACK.ACOG.CCS.2020.TX.01",
    "PACK.ACOG.CCS.2020.TX.02",
    "PACK.ACOG.CCS.2020.TX.03",
    "PACK.ACOG.CCS.2020.RF.01",
    "PACK.ACOG.CCS.2020.SEV.01"
  ],
  "all_display_ids": [
    "ACOG-CCS-R1",
    "ACOG-CCS-R2",
    "ACOG-CCS-R3",
    "ACOG-CCS-R4",
    "ACOG-CCS-R5",
    "ACOG-CCS-R6",
    "ACOG-CCS-R7",
    "ACOG-CCS-R8",
    "ACOG-CCS-R9",
    "ACOG-CCS-R10",
    "ACOG-CCS-DC1",
    "ACOG-CCS-T1",
    "ACOG-CCS-T2",
    "ACOG-CCS-T3",
    "ACOG-CCS-TX1",
    "ACOG-CCS-TX2",
    "ACOG-CCS-TX3",
    "ACOG-CCS-RF1",
    "ACOG-CCS-SEV1"
  ]
};
