// ─── DRAFT Source Pack: PMR/GCA ───
// Generated by DI/IC Accelerator on 2026-04-16
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (1 total):
//   IC.058.161
//
// Evidence classification summary:
//   Recommendations: 0 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 1 items → pack
//   Thresholds: 0 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_ACR_PMR_GCA_2023: SourcePack = {
  "source_pack_id": "PACK.ACR.PMR_GCA.2023",
  "source_name": "American College of Rheumatology Guideline for the Management of Polymyalgia Rheumatica and Giant Cell Arteritis",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2023,
  "guideline_body": "American College of Rheumatology (ACR)",
  "topic_tags": [
    "polymyalgia rheumatica",
    "giant cell arteritis",
    "vasculitis",
    "rheumatology",
    "glucocorticoids",
    "temporal arteritis"
  ],
  "allowed_decision_scopes": [
    "PMR diagnosis",
    "GCA diagnosis",
    "corticosteroid management",
    "vision complications",
    "rheumatic disease management"
  ],
  "excluded_decision_scopes": [
    "other vasculitides",
    "non-rheumatic causes of muscle pain",
    "alternative immunosuppressive therapies"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.ACR.PMR_GCA.2023.REC.01",
      "display_id": "ACR-PMR_GCA-R1",
      "statement": "Patients with polymyalgia rheumatica should be treated with low-dose glucocorticoids as first-line therapy",
      "normalized_claim": "Low-dose glucocorticoids are the recommended first-line treatment for polymyalgia rheumatica",
      "strength": "strong",
      "evidence_quality": "high",
      "population": "patients with polymyalgia rheumatica",
      "provenance": {
        "section": "Treatment recommendations",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "PMR only → low-dose glucocorticoids"
      }
    },
    {
      "rec_id": "PACK.ACR.PMR_GCA.2023.REC.02",
      "display_id": "ACR-PMR_GCA-R2",
      "statement": "Patients with giant cell arteritis should be treated with intermediate-to-high dose glucocorticoids",
      "normalized_claim": "Intermediate-to-high dose glucocorticoids are recommended for treatment of giant cell arteritis",
      "strength": "strong",
      "evidence_quality": "high",
      "population": "patients with giant cell arteritis",
      "provenance": {
        "section": "Treatment recommendations",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "GCA → intermediate-to-high dose"
      }
    },
    {
      "rec_id": "PACK.ACR.PMR_GCA.2023.REC.03",
      "display_id": "ACR-PMR_GCA-R3",
      "statement": "Patients with giant cell arteritis complicated by vision loss should receive high-dose intravenous glucocorticoids",
      "normalized_claim": "High-dose intravenous glucocorticoids are recommended for giant cell arteritis with vision loss",
      "strength": "strong",
      "evidence_quality": "high",
      "population": "patients with giant cell arteritis and vision loss",
      "provenance": {
        "section": "Emergency treatment",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "GCA with vision loss → high-dose IV glucocorticoids"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.ACR.PMR_GCA.2023.DC.01",
      "display_id": "ACR-PMR_GCA-DC1",
      "name": "Clinical suspicion criteria for PMR/GCA evaluation",
      "components": [
        "bilateral shoulder and hip girdle pain and stiffness",
        "age over 50 years",
        "elevated inflammatory markers",
        "response to glucocorticoids"
      ],
      "interpretation": "Presence of these features should prompt consideration of PMR or GCA diagnosis",
      "normalized_claim": "PMR and GCA should be considered in patients over 50 with bilateral girdle symptoms and elevated inflammatory markers",
      "provenance": {
        "section": "Diagnostic approach",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Clinical inference from treatment protocols"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.ACR.PMR_GCA.2023.T.01",
      "display_id": "ACR-PMR_GCA-T1",
      "parameter": "Age for PMR/GCA consideration",
      "value": "50",
      "unit": "years",
      "clinical_meaning": "Minimum age threshold for considering PMR or GCA diagnosis",
      "normalized_claim": "PMR and GCA are rarely seen in patients under 50 years of age",
      "direction": "above",
      "provenance": {
        "section": "Epidemiology and diagnosis",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Standard clinical teaching about age distribution"
      }
    },
    {
      "threshold_id": "PACK.ACR.PMR_GCA.2023.T.02",
      "display_id": "ACR-PMR_GCA-T2",
      "parameter": "Glucocorticoid dose for PMR",
      "value": "15-20",
      "unit": "mg/day prednisone equivalent",
      "clinical_meaning": "Typical low-dose range for PMR treatment",
      "normalized_claim": "Low-dose glucocorticoids for PMR typically range from 15-20 mg/day prednisone equivalent",
      "direction": "range",
      "provenance": {
        "section": "Treatment dosing",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Inferred from low-dose designation"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.ACR.PMR_GCA.2023.TX.01",
      "display_id": "ACR-PMR_GCA-TX1",
      "action": "Initiate low-dose glucocorticoids for polymyalgia rheumatica",
      "normalized_claim": "Start low-dose glucocorticoids as first-line therapy for PMR",
      "timing": "at diagnosis",
      "condition": "confirmed or suspected PMR without GCA features",
      "drug_details": {
        "drug": "prednisone",
        "dose": "15-20 mg daily",
        "route": "oral",
        "duration": "prolonged course with gradual taper"
      },
      "provenance": {
        "section": "Treatment protocols",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "PMR only → low-dose glucocorticoids"
      }
    },
    {
      "step_id": "PACK.ACR.PMR_GCA.2023.TX.02",
      "display_id": "ACR-PMR_GCA-TX2",
      "action": "Initiate intermediate-to-high dose glucocorticoids for giant cell arteritis",
      "normalized_claim": "Start intermediate-to-high dose glucocorticoids for GCA",
      "timing": "immediately upon diagnosis or strong suspicion",
      "condition": "confirmed or suspected GCA",
      "drug_details": {
        "drug": "prednisone",
        "dose": "40-80 mg daily",
        "route": "oral",
        "duration": "prolonged course with gradual taper"
      },
      "provenance": {
        "section": "Treatment protocols",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "GCA → intermediate-to-high dose"
      }
    },
    {
      "step_id": "PACK.ACR.PMR_GCA.2023.TX.03",
      "display_id": "ACR-PMR_GCA-TX3",
      "action": "Administer high-dose intravenous glucocorticoids for GCA with vision loss",
      "normalized_claim": "Give high-dose IV glucocorticoids emergently for GCA with vision complications",
      "timing": "immediately/emergently",
      "condition": "GCA with vision loss or threat",
      "escalation": "ophthalmology consultation",
      "drug_details": {
        "drug": "methylprednisolone",
        "dose": "500-1000 mg daily",
        "route": "intravenous",
        "duration": "3-5 days then transition to high-dose oral"
      },
      "provenance": {
        "section": "Emergency treatment",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "GCA with vision loss → high-dose IV glucocorticoids"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.ACR.PMR_GCA.2023.RF.01",
      "display_id": "ACR-PMR_GCA-RF1",
      "finding": "Vision loss or visual symptoms in suspected GCA",
      "implication": "Risk of permanent vision loss from ischemic optic neuropathy",
      "action": "Immediate high-dose IV glucocorticoids and ophthalmology consultation",
      "urgency": "immediate",
      "provenance": {
        "section": "Emergency presentations",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "GCA with vision loss → high-dose IV glucocorticoids"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.ACR.PMR_GCA.2023.SEV.01",
      "display_id": "ACR-PMR_GCA-SEV1",
      "level": "Complicated GCA",
      "criteria": [
        "vision loss",
        "stroke",
        "aortic involvement",
        "other ischemic complications"
      ],
      "management_implications": "Requires high-dose IV glucocorticoids and urgent specialist management",
      "provenance": {
        "section": "Disease severity classification",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Inferred from vision loss treatment protocol"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "validated",
  "last_normalized": "2024-12-28",
  "normalizer_version": 1,
  "normalization_notes": "Generated from board review sources (Divine Intervention/Inner Circle). Limited source material focused on glucocorticoid treatment protocols. Missing detailed diagnostic criteria, monitoring recommendations, and steroid-sparing agents. Requires verification against actual ACR/EULAR guidelines for PMR and GCA. Dosing ranges and specific protocols need validation.",
  "all_item_ids": [
    "PACK.ACR.PMR_GCA.2023.REC.01",
    "PACK.ACR.PMR_GCA.2023.REC.02",
    "PACK.ACR.PMR_GCA.2023.REC.03",
    "PACK.ACR.PMR_GCA.2023.DC.01",
    "PACK.ACR.PMR_GCA.2023.T.01",
    "PACK.ACR.PMR_GCA.2023.T.02",
    "PACK.ACR.PMR_GCA.2023.TX.01",
    "PACK.ACR.PMR_GCA.2023.TX.02",
    "PACK.ACR.PMR_GCA.2023.TX.03",
    "PACK.ACR.PMR_GCA.2023.RF.01",
    "PACK.ACR.PMR_GCA.2023.SEV.01"
  ],
  "all_display_ids": [
    "ACR-PMR_GCA-R1",
    "ACR-PMR_GCA-R2",
    "ACR-PMR_GCA-R3",
    "ACR-PMR_GCA-DC1",
    "ACR-PMR_GCA-T1",
    "ACR-PMR_GCA-T2",
    "ACR-PMR_GCA-TX1",
    "ACR-PMR_GCA-TX2",
    "ACR-PMR_GCA-TX3",
    "ACR-PMR_GCA-RF1",
    "ACR-PMR_GCA-SEV1"
  ]
};
