import type { SourcePack } from './types';

export const PACK_ACR_RA_2021: SourcePack = {
  source_pack_id: 'PACK.ACR.RA.2021',
  source_name: 'ACR Guideline for Treatment of Rheumatoid Arthritis 2021',
  canonical_url: 'https://doi.org/10.1002/acr.24596',
  publication_year: 2021,
  guideline_body: 'ACR',

  topic_tags: ['Rheumatoid Arthritis', 'DMARD', 'Biologic Therapy', 'Rheumatology'],
  allowed_decision_scopes: [
    'RA diagnosis using 2010 ACR/EULAR criteria',
    'DMARD initiation and selection',
    'biologic escalation strategy',
    'treat-to-target monitoring',
    'glucocorticoid bridging therapy',
    'RF and anti-CCP prognostic use',
    'DMARD tapering in sustained remission',
  ],
  excluded_decision_scopes: [
    'osteoarthritis management',
    'juvenile idiopathic arthritis',
    'perioperative DMARD management details',
    'vaccination schedule specifics on immunosuppression',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ACR.RA.2021.REC.01',
      display_id: 'ACR-RA-R1',
      statement: 'Methotrexate monotherapy is recommended as the preferred initial DMARD for DMARD-naive patients with moderate-to-high disease activity.',
      normalized_claim: 'Methotrexate is the first-line DMARD for treatment-naive RA with moderate-to-high disease activity.',
      strength: 'strong',
      evidence_quality: 'moderate',
      context: 'Applies to DMARD-naive patients. Low disease activity may use hydroxychloroquine or sulfasalazine.',
      provenance: { section: 'Initial DMARD Therapy', page_or_location: 'Recommendation 1' },
    },
    {
      rec_id: 'PACK.ACR.RA.2021.REC.02',
      display_id: 'ACR-RA-R2',
      statement: 'In patients with moderate-to-high disease activity despite methotrexate optimization, addition of a biologic DMARD (TNF inhibitor preferred) or JAK inhibitor is conditionally recommended over triple conventional DMARD therapy.',
      normalized_claim: 'Add biologic DMARD (TNFi preferred) or JAK inhibitor when methotrexate fails to achieve target after 3 months.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      context: 'Inadequate response defined as failure to reach low disease activity or remission at 3 months of optimized MTX.',
      provenance: { section: 'Biologic Escalation', page_or_location: 'Recommendation 3' },
    },
    {
      rec_id: 'PACK.ACR.RA.2021.REC.03',
      display_id: 'ACR-RA-R3',
      statement: 'Treat-to-target strategy aiming for remission (or low disease activity as an alternative) is strongly recommended over non-targeted treatment.',
      normalized_claim: 'Treat-to-target with remission as primary goal and low disease activity as acceptable alternative.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Treatment Strategy', page_or_location: 'Recommendation 7' },
    },
    {
      rec_id: 'PACK.ACR.RA.2021.REC.04',
      display_id: 'ACR-RA-R4',
      statement: 'Short-term glucocorticoids (lowest effective dose for shortest duration) are conditionally recommended as bridging therapy when initiating or changing DMARDs. Long-term glucocorticoid use should be avoided.',
      normalized_claim: 'Short-term low-dose glucocorticoids for bridging only; avoid long-term steroid use in RA.',
      strength: 'conditional',
      evidence_quality: 'low',
      context: 'Bridge period typically <=3 months. Taper once DMARD effect expected.',
      provenance: { section: 'Glucocorticoid Use', page_or_location: 'Recommendation 5' },
    },
    {
      rec_id: 'PACK.ACR.RA.2021.REC.05',
      display_id: 'ACR-RA-R5',
      statement: 'In patients achieving sustained remission on combination biologic + methotrexate, dose reduction of the biologic is conditionally recommended over continuation at full dose.',
      normalized_claim: 'Taper biologic dose (not abrupt discontinuation) in sustained remission on combination therapy.',
      strength: 'conditional',
      evidence_quality: 'low',
      provenance: { section: 'DMARD Tapering', page_or_location: 'Recommendation 10' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ACR.RA.2021.DC.01',
      display_id: 'ACR-RA-DC1',
      name: '2010 ACR/EULAR Classification Criteria for RA',
      components: [
        'Joint involvement: 1 large joint (0) to >10 joints including >=1 small joint (5)',
        'Serology: Negative RF and anti-CCP (0), low-positive (2), high-positive (3)',
        'Acute-phase reactants: Normal CRP and ESR (0), abnormal CRP or ESR (1)',
        'Duration of symptoms: <6 weeks (0), >=6 weeks (1)',
      ],
      threshold: 'Score >=6/10 classifies as definite RA',
      interpretation: 'Requires at least 1 joint with definite clinical synovitis not better explained by another disease. Score >=6 on 0-10 scale = definite RA.',
      normalized_claim: '2010 ACR/EULAR criteria: score >=6/10 (joint involvement + serology + acute-phase reactants + duration >=6 weeks) classifies definite RA.',
      provenance: { section: 'Classification Criteria', page_or_location: 'Table 1' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ACR.RA.2021.T.01',
      display_id: 'ACR-RA-T1',
      parameter: 'Disease Activity Score (DAS28)',
      value: '2.6',
      clinical_meaning: 'DAS28 <2.6 defines remission; 2.6-3.2 is low disease activity; >3.2 is moderate; >5.1 is high disease activity.',
      normalized_claim: 'DAS28 <2.6 = remission; treat-to-target goal is remission or low disease activity (DAS28 <=3.2).',
      direction: 'below',
      provenance: { section: 'Disease Activity Assessment', page_or_location: 'Table 2' },
    },
    {
      threshold_id: 'PACK.ACR.RA.2021.T.02',
      display_id: 'ACR-RA-T2',
      parameter: 'Anti-CCP antibody titer',
      value: '3x upper limit of normal',
      clinical_meaning: 'High-positive anti-CCP (>3x ULN) indicates poor prognosis and higher likelihood of erosive disease. Scores 3 points on ACR/EULAR criteria.',
      normalized_claim: 'Anti-CCP >3x ULN is high-positive, predicts erosive disease and poor prognosis.',
      direction: 'above',
      provenance: { section: 'Serology', page_or_location: 'Table 1, Serology domain' },
    },
    {
      threshold_id: 'PACK.ACR.RA.2021.T.03',
      display_id: 'ACR-RA-T3',
      parameter: 'Time to reassess treatment response',
      value: '3',
      unit: 'months',
      clinical_meaning: 'Treatment adequacy should be assessed at 3 months. If target not reached, escalate therapy.',
      normalized_claim: 'Reassess DMARD response at 3 months; escalate if target not met.',
      direction: 'below',
      provenance: { section: 'Treatment Strategy', page_or_location: 'Recommendation 7' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ACR.RA.2021.TX.01',
      display_id: 'ACR-RA-TX1',
      action: 'Initiate methotrexate monotherapy',
      normalized_claim: 'Start methotrexate 15-25mg weekly (oral or subcutaneous) with folic acid supplementation for all DMARD-naive RA with moderate-to-high disease activity.',
      timing: 'At diagnosis of RA with moderate-to-high disease activity',
      condition: 'DMARD-naive RA with moderate-to-high disease activity',
      drug_details: { drug: 'Methotrexate', dose: '15-25mg weekly', route: 'PO or SQ' },
      contraindications: ['Pregnancy or planned pregnancy', 'Significant hepatic disease', 'eGFR <30', 'Active serious infection'],
      escalation: 'If inadequate response at 3 months, add biologic DMARD',
      provenance: { section: 'Initial DMARD Therapy', page_or_location: 'Recommendation 1' },
    },
    {
      step_id: 'PACK.ACR.RA.2021.TX.02',
      display_id: 'ACR-RA-TX2',
      action: 'Add TNF inhibitor for inadequate methotrexate response',
      normalized_claim: 'Add TNF inhibitor (adalimumab, etanercept, or infliximab) to methotrexate when target not reached after 3 months of optimized MTX.',
      timing: 'After 3 months of optimized methotrexate without reaching target',
      condition: 'Inadequate response to optimized methotrexate monotherapy',
      drug_details: { drug: 'Adalimumab (or other TNFi)', dose: '40mg every 2 weeks', route: 'SQ' },
      contraindications: ['Active or latent untreated TB', 'Active serious infection', 'Decompensated heart failure (NYHA III-IV)', 'Demyelinating disease'],
      provenance: { section: 'Biologic Escalation', page_or_location: 'Recommendation 3' },
    },
    {
      step_id: 'PACK.ACR.RA.2021.TX.03',
      display_id: 'ACR-RA-TX3',
      action: 'Glucocorticoid bridging during DMARD initiation',
      normalized_claim: 'Prednisone <=10mg/day as bridge therapy for <=3 months while awaiting DMARD onset of action. Taper as soon as DMARD effect achieved.',
      timing: 'During DMARD initiation or switch',
      condition: 'Active RA symptoms requiring rapid symptom control during DMARD ramp-up',
      drug_details: { drug: 'Prednisone', dose: '<=10mg daily', route: 'PO', duration: '<=3 months' },
      contraindications: ['Uncontrolled diabetes', 'Active untreated infection'],
      provenance: { section: 'Glucocorticoid Use', page_or_location: 'Recommendation 5' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ACR.RA.2021.RF.01',
      display_id: 'ACR-RA-RF1',
      finding: 'C-spine instability: neck pain with neurologic symptoms (myelopathy) in longstanding RA',
      implication: 'Atlantoaxial subluxation from pannus erosion. Risk of spinal cord compression.',
      action: 'Flexion-extension cervical spine radiographs. Neurosurgery consultation if subluxation confirmed. Avoid intubation without cervical spine clearance.',
      urgency: 'urgent',
      provenance: { section: 'Complications', page_or_location: 'Extra-articular RA' },
    },
    {
      flag_id: 'PACK.ACR.RA.2021.RF.02',
      display_id: 'ACR-RA-RF2',
      finding: 'Serious infection on biologic DMARD therapy: fever, sepsis signs in patient on TNF inhibitor or other biologic',
      implication: 'Biologics increase risk of serious and opportunistic infections. Must hold biologic and treat infection.',
      action: 'Hold biologic DMARD immediately. Broad-spectrum antibiotics. Evaluate for TB reactivation, fungal infection. Do not restart biologic until infection fully resolved.',
      urgency: 'immediate',
      provenance: { section: 'Safety Monitoring', page_or_location: 'Recommendation 6' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ACR.RA.2021.SEV.01',
      display_id: 'ACR-RA-SEV1',
      level: 'High disease activity',
      criteria: [
        'DAS28 >5.1',
        'Multiple swollen and tender joints (typically >10)',
        'Elevated ESR and CRP',
        'Significant functional impairment',
        'Positive RF and anti-CCP (especially high-positive) with erosive changes on imaging',
      ],
      management_implications:
        'Initiate methotrexate immediately. Consider early biologic addition if poor prognostic factors (high-positive RF/anti-CCP, early erosions, high disease activity despite MTX). Glucocorticoid bridging appropriate. Reassess at 3 months; escalate aggressively if target not met.',
      provenance: { section: 'Disease Activity Assessment', page_or_location: 'Table 2' },
    },
    {
      severity_id: 'PACK.ACR.RA.2021.SEV.02',
      display_id: 'ACR-RA-SEV2',
      level: 'Low disease activity / Remission',
      criteria: [
        'DAS28 <2.6 (remission) or <=3.2 (low disease activity)',
        'Minimal or no swollen/tender joints',
        'Normal or near-normal ESR/CRP',
        'Preserved functional status',
      ],
      management_implications:
        'Continue current DMARD regimen. In sustained remission (>=6 months), consider cautious dose reduction of biologic (not methotrexate first). Monitor every 3-6 months. Do not discontinue all DMARDs — high relapse rate.',
      provenance: { section: 'DMARD Tapering', page_or_location: 'Recommendation 10' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 lightweight pack for RA. Covers DMARD initiation, biologic escalation, treat-to-target, and 2010 ACR/EULAR classification criteria.',

  all_item_ids: [
    'PACK.ACR.RA.2021.REC.01', 'PACK.ACR.RA.2021.REC.02', 'PACK.ACR.RA.2021.REC.03',
    'PACK.ACR.RA.2021.REC.04', 'PACK.ACR.RA.2021.REC.05', 'PACK.ACR.RA.2021.DC.01',
    'PACK.ACR.RA.2021.T.01', 'PACK.ACR.RA.2021.T.02', 'PACK.ACR.RA.2021.T.03',
    'PACK.ACR.RA.2021.TX.01', 'PACK.ACR.RA.2021.TX.02', 'PACK.ACR.RA.2021.TX.03',
    'PACK.ACR.RA.2021.RF.01', 'PACK.ACR.RA.2021.RF.02',
    'PACK.ACR.RA.2021.SEV.01', 'PACK.ACR.RA.2021.SEV.02',
  ],
  all_display_ids: [
    'ACR-RA-R1', 'ACR-RA-R2', 'ACR-RA-R3', 'ACR-RA-R4', 'ACR-RA-R5',
    'ACR-RA-DC1',
    'ACR-RA-T1', 'ACR-RA-T2', 'ACR-RA-T3',
    'ACR-RA-TX1', 'ACR-RA-TX2', 'ACR-RA-TX3',
    'ACR-RA-RF1', 'ACR-RA-RF2',
    'ACR-RA-SEV1', 'ACR-RA-SEV2',
  ],
};
