import type { SourcePack } from './types';

export const PACK_ACR_VASC_2021: SourcePack = {
  source_pack_id: 'PACK.ACR.VASC.2021',
  source_name: 'ACR/VF Guideline for Management of ANCA-Associated Vasculitis and Large/Medium Vessel Vasculitis 2021',
  canonical_url: 'https://doi.org/10.1002/art.41773',
  publication_year: 2021,
  guideline_body: 'ACR',

  topic_tags: ['Vasculitis', 'ANCA', 'GPA', 'MPA', 'EGPA', 'GCA', 'Takayasu', 'PAN', 'Kawasaki', 'Rheumatology'],
  allowed_decision_scopes: [
    'ANCA-associated vasculitis classification and treatment',
    'GPA vs MPA vs EGPA differentiation',
    'rituximab vs cyclophosphamide for AAV induction',
    'GCA diagnosis and emergent glucocorticoid therapy',
    'temporal artery biopsy indications',
    'large vessel vasculitis imaging',
    'PAN and HBV association',
    'Kawasaki disease recognition in adults',
  ],
  excluded_decision_scopes: [
    'IgA vasculitis (Henoch-Schonlein purpura) management details',
    'cryoglobulinemic vasculitis management',
    'primary CNS vasculitis',
    'Behcet disease management',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ACR.VASC.2021.REC.01',
      display_id: 'ACR-VASC-R1',
      statement: 'For severe active GPA or MPA, rituximab is conditionally recommended over cyclophosphamide for remission induction, particularly in relapsing disease.',
      normalized_claim: 'Rituximab is noninferior (and preferred for relapsing disease) to cyclophosphamide for severe AAV induction (RAVE and RITUXVAS trials).',
      strength: 'conditional',
      evidence_quality: 'high',
      context: 'RAVE trial demonstrated noninferiority. Rituximab preferred in relapsing disease, reproductive-age patients, and those with prior cyclophosphamide exposure.',
      provenance: { section: 'AAV Induction Therapy', page_or_location: 'Recommendation 2' },
    },
    {
      rec_id: 'PACK.ACR.VASC.2021.REC.02',
      display_id: 'ACR-VASC-R2',
      statement: 'In patients with suspected GCA, glucocorticoids should be started IMMEDIATELY upon clinical suspicion. Do NOT delay treatment to obtain temporal artery biopsy.',
      normalized_claim: 'Start high-dose glucocorticoids for GCA immediately on clinical suspicion. Temporal artery biopsy can be performed within 2 weeks of starting steroids without affecting results.',
      strength: 'strong',
      evidence_quality: 'moderate',
      context: 'Delay risks irreversible vision loss. Biopsy remains informative up to 2 weeks after starting steroids.',
      provenance: { section: 'GCA Management', page_or_location: 'Recommendation 12' },
    },
    {
      rec_id: 'PACK.ACR.VASC.2021.REC.03',
      display_id: 'ACR-VASC-R3',
      statement: 'For remission maintenance in AAV, rituximab is conditionally recommended over azathioprine. Maintenance should continue for at least 18-24 months after remission induction.',
      normalized_claim: 'Rituximab maintenance superior to azathioprine for preventing AAV relapse (MAINRITSAN trial). Continue >=18-24 months.',
      strength: 'conditional',
      evidence_quality: 'high',
      provenance: { section: 'AAV Maintenance', page_or_location: 'Recommendation 5' },
    },
    {
      rec_id: 'PACK.ACR.VASC.2021.REC.04',
      display_id: 'ACR-VASC-R4',
      statement: 'ANCA serotype correlates with disease phenotype: c-ANCA/PR3 is strongly associated with GPA; p-ANCA/MPO is associated with MPA.',
      normalized_claim: 'c-ANCA (anti-PR3) = GPA; p-ANCA (anti-MPO) = MPA. ANCA type predicts relapse risk and guides treatment duration.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'AAV Classification', page_or_location: 'ANCA serotype section' },
    },
    {
      rec_id: 'PACK.ACR.VASC.2021.REC.05',
      display_id: 'ACR-VASC-R5',
      statement: 'Polyarteritis nodosa (PAN) should be tested for HBV association. HBV-associated PAN is treated with antivirals and plasma exchange rather than immunosuppression alone.',
      normalized_claim: 'PAN: test for HBV. HBV-associated PAN requires antiviral therapy (entecavir or tenofovir) + plasma exchange; limit immunosuppression.',
      strength: 'conditional',
      evidence_quality: 'low',
      provenance: { section: 'Medium Vessel Vasculitis', page_or_location: 'PAN management' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ACR.VASC.2021.DC.01',
      display_id: 'ACR-VASC-DC1',
      name: 'ANCA-Associated Vasculitis Classification',
      components: [
        'GPA (granulomatosis with polyangiitis): Upper/lower respiratory tract granulomatous inflammation + necrotizing vasculitis + glomerulonephritis. c-ANCA/PR3 positive in ~90%.',
        'MPA (microscopic polyangiitis): Necrotizing small vessel vasculitis without granulomas. Pulmonary-renal syndrome common. p-ANCA/MPO positive in ~70%.',
        'EGPA (eosinophilic granulomatosis with polyangiitis): Asthma + eosinophilia + vasculitis. p-ANCA/MPO positive in ~40%. Cardiac involvement is leading cause of mortality.',
      ],
      interpretation: 'AAV triad differentiated by granulomas (GPA), no granulomas (MPA), and eosinophils/asthma (EGPA). ANCA pattern helps but is not diagnostic alone.',
      normalized_claim: 'GPA = granulomas + c-ANCA/PR3; MPA = no granulomas + p-ANCA/MPO; EGPA = asthma + eosinophilia + vasculitis (p-ANCA in ~40%).',
      provenance: { section: 'AAV Classification', page_or_location: 'Table 1' },
    },
    {
      criterion_id: 'PACK.ACR.VASC.2021.DC.02',
      display_id: 'ACR-VASC-DC2',
      name: 'GCA Diagnostic Criteria',
      components: [
        'Age >=50 at disease onset',
        'New-onset headache (especially temporal)',
        'Temporal artery tenderness or reduced pulsation on exam',
        'ESR >=50 mm/h (often >100)',
        'Temporal artery biopsy showing granulomatous inflammation with multinucleated giant cells',
        'Jaw claudication (highly specific symptom)',
        'Visual disturbances: amaurosis fugax, diplopia, or acute vision loss',
      ],
      threshold: 'ACR 1990 criteria: >=3 of 5 criteria (age >=50, new headache, temporal artery abnormality, ESR >=50, positive biopsy)',
      interpretation: 'GCA is a clinical-pathologic diagnosis. Temporal artery biopsy is gold standard but sensitivity is ~85% (skip lesions). Negative biopsy does not exclude GCA.',
      normalized_claim: 'GCA: age >=50 + new headache + jaw claudication + ESR >=50 + temporal artery biopsy with giant cells. Biopsy sensitivity ~85% due to skip lesions.',
      provenance: { section: 'Large Vessel Vasculitis', page_or_location: 'GCA diagnosis' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ACR.VASC.2021.T.01',
      display_id: 'ACR-VASC-T1',
      parameter: 'ESR in suspected GCA',
      value: '50',
      unit: 'mm/h',
      clinical_meaning: 'ESR >=50 mm/h is one of the ACR classification criteria for GCA. ESR is often >100 mm/h. However, ~5% of biopsy-proven GCA has normal ESR.',
      normalized_claim: 'ESR >=50 mm/h supports GCA diagnosis (often >100), but normal ESR does not exclude biopsy-proven GCA (~5% have normal ESR).',
      direction: 'above',
      provenance: { section: 'GCA Diagnosis', page_or_location: 'ACR 1990 criteria' },
    },
    {
      threshold_id: 'PACK.ACR.VASC.2021.T.02',
      display_id: 'ACR-VASC-T2',
      parameter: 'Temporal artery biopsy timing after steroid initiation',
      value: '14',
      unit: 'days',
      clinical_meaning: 'Temporal artery biopsy should be obtained within 2 weeks of starting glucocorticoids. Inflammatory infiltrate remains interpretable for up to 2 weeks on steroids.',
      normalized_claim: 'Temporal artery biopsy reliable within 14 days of starting steroids; do not delay steroid initiation for biopsy scheduling.',
      direction: 'below',
      provenance: { section: 'GCA Biopsy', page_or_location: 'Recommendation 12' },
    },
    {
      threshold_id: 'PACK.ACR.VASC.2021.T.03',
      display_id: 'ACR-VASC-T3',
      parameter: 'Serum creatinine rise suggesting RPGN in AAV',
      value: '50',
      unit: '% increase from baseline',
      clinical_meaning: 'Rapid creatinine rise (>=50% or doubling) with active urine sediment (RBC casts) in ANCA-positive patient indicates rapidly progressive glomerulonephritis. Requires urgent treatment.',
      normalized_claim: 'Creatinine rise >=50% with active sediment in ANCA-positive patient = RPGN; requires urgent induction therapy.',
      direction: 'above',
      provenance: { section: 'AAV Renal Involvement', page_or_location: 'Severe AAV criteria' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ACR.VASC.2021.TX.01',
      display_id: 'ACR-VASC-TX1',
      action: 'AAV severe induction: Rituximab + glucocorticoids',
      normalized_claim: 'Rituximab 375mg/m2 weekly x 4 doses (or 1000mg x 2 doses 2 weeks apart) + IV methylprednisolone pulse then oral prednisone taper for severe AAV induction.',
      timing: 'At diagnosis of severe active AAV',
      condition: 'Severe active GPA or MPA with organ-threatening disease (renal, pulmonary)',
      drug_details: { drug: 'Rituximab', dose: '375mg/m2 weekly x 4 OR 1000mg x 2', route: 'IV' },
      contraindications: ['Active hepatitis B', 'Severe active infection', 'Severe heart failure'],
      escalation: 'Add plasma exchange if creatinine >5.7 mg/dL or pulmonary hemorrhage (PEXIVAS trial showed no overall benefit but may help in select severe cases)',
      provenance: { section: 'AAV Induction', page_or_location: 'Recommendation 2' },
    },
    {
      step_id: 'PACK.ACR.VASC.2021.TX.02',
      display_id: 'ACR-VASC-TX2',
      action: 'GCA: Immediate high-dose glucocorticoids',
      normalized_claim: 'Prednisone 1mg/kg/day (max 60-80mg) immediately upon clinical suspicion of GCA. If visual symptoms present: IV methylprednisolone 1g/day x 3 days first.',
      timing: 'Immediately upon clinical suspicion — before biopsy',
      condition: 'Clinical suspicion of GCA (headache, jaw claudication, visual symptoms, elevated ESR in patient >=50)',
      drug_details: { drug: 'Prednisone', dose: '1mg/kg/day (max 60-80mg)', route: 'PO' },
      contraindications: ['Active untreated systemic infection (relative — risk of vision loss outweighs infection risk in most cases)'],
      escalation: 'Tocilizumab (IL-6 receptor inhibitor) as steroid-sparing agent for relapsing GCA or inability to taper below prednisone 10mg/day',
      provenance: { section: 'GCA Treatment', page_or_location: 'Recommendation 12' },
    },
    {
      step_id: 'PACK.ACR.VASC.2021.TX.03',
      display_id: 'ACR-VASC-TX3',
      action: 'AAV maintenance: Rituximab',
      normalized_claim: 'Rituximab 500mg IV every 6 months for >=18-24 months as maintenance therapy after AAV remission induction. Superior to azathioprine for relapse prevention.',
      timing: 'After achieving remission with induction therapy',
      condition: 'AAV in remission after induction with rituximab or cyclophosphamide',
      drug_details: { drug: 'Rituximab', dose: '500mg every 6 months', route: 'IV', duration: '>=18-24 months' },
      provenance: { section: 'AAV Maintenance', page_or_location: 'Recommendation 5' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ACR.VASC.2021.RF.01',
      display_id: 'ACR-VASC-RF1',
      finding: 'Acute vision loss or amaurosis fugax with headache and jaw claudication in patient >=50 years old',
      implication: 'GCA with anterior ischemic optic neuropathy. Untreated, 50% risk of bilateral permanent blindness within days.',
      action: 'IV methylprednisolone 1g/day x 3 days IMMEDIATELY. Do NOT wait for biopsy, ESR, or ophthalmology consult before starting steroids. Temporal artery biopsy within 14 days. Urgent ophthalmology referral.',
      urgency: 'immediate',
      provenance: { section: 'GCA Emergency', page_or_location: 'Recommendation 12, visual symptoms' },
    },
    {
      flag_id: 'PACK.ACR.VASC.2021.RF.02',
      display_id: 'ACR-VASC-RF2',
      finding: 'Diffuse alveolar hemorrhage in ANCA-positive patient: Hemoptysis, bilateral infiltrates, dropping hemoglobin, rising creatinine',
      implication: 'Pulmonary-renal syndrome (AAV). Life-threatening. Mortality >25% without emergent treatment.',
      action: 'ICU admission. IV methylprednisolone 1g x 3 days + rituximab or cyclophosphamide. Consider plasma exchange. Bronchoscopy with BAL for confirmation (progressively bloodier returns). Mechanical ventilation if needed.',
      urgency: 'immediate',
      provenance: { section: 'AAV Pulmonary Hemorrhage', page_or_location: 'Severe AAV management' },
    },
    {
      flag_id: 'PACK.ACR.VASC.2021.RF.03',
      display_id: 'ACR-VASC-RF3',
      finding: 'Saddle nose deformity, subglottic stenosis, or destructive sinusitis with ANCA positivity',
      implication: 'Granulomatosis with polyangiitis (GPA). Upper airway involvement can cause life-threatening airway obstruction.',
      action: 'ENT evaluation. CT sinuses. Assess for subglottic stenosis (stridor, dyspnea). Induction immunosuppression. Biopsy of involved tissue for confirmation.',
      urgency: 'urgent',
      provenance: { section: 'GPA Upper Airway', page_or_location: 'GPA clinical features' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ACR.VASC.2021.SEV.01',
      display_id: 'ACR-VASC-SEV1',
      level: 'Severe/organ-threatening AAV',
      criteria: [
        'Rapidly progressive glomerulonephritis (creatinine rising, active sediment, ANCA positive)',
        'Diffuse alveolar hemorrhage',
        'CNS vasculitis (cranial nerve palsies, stroke, pachymeningitis)',
        'Scleritis or orbital pseudotumor with vision threat',
        'Severe subglottic stenosis with airway compromise',
        'Cardiac involvement (pericarditis, cardiomyopathy — especially in EGPA)',
      ],
      management_implications:
        'Immediate induction with rituximab or cyclophosphamide + IV methylprednisolone pulse. ICU admission for pulmonary hemorrhage or airway compromise. Consider plasma exchange for creatinine >5.7 mg/dL or DAH. Maintenance rituximab after remission for >=24 months.',
      provenance: { section: 'AAV Severity', page_or_location: 'Severe AAV definition' },
    },
    {
      severity_id: 'PACK.ACR.VASC.2021.SEV.02',
      display_id: 'ACR-VASC-SEV2',
      level: 'Non-severe/limited AAV',
      criteria: [
        'Upper airway involvement without airway compromise',
        'Skin vasculitis (palpable purpura, ulcers) without systemic threat',
        'Arthritis/arthralgia',
        'Stable mild renal involvement (stable creatinine, non-nephrotic proteinuria)',
        'Constitutional symptoms (fever, weight loss, fatigue)',
      ],
      management_implications:
        'Rituximab or methotrexate (for non-renal limited GPA) + lower-dose glucocorticoids. Outpatient management with close monitoring. ANCA titers and inflammatory markers for disease activity tracking. Maintenance therapy after remission.',
      provenance: { section: 'AAV Severity', page_or_location: 'Non-severe AAV definition' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 lightweight pack for vasculitis. Covers ANCA-associated vasculitis (GPA/MPA/EGPA), GCA emergent management, PAN-HBV association, and severity stratification.',

  all_item_ids: [
    'PACK.ACR.VASC.2021.REC.01', 'PACK.ACR.VASC.2021.REC.02', 'PACK.ACR.VASC.2021.REC.03',
    'PACK.ACR.VASC.2021.REC.04', 'PACK.ACR.VASC.2021.REC.05', 'PACK.ACR.VASC.2021.DC.01',
    'PACK.ACR.VASC.2021.DC.02', 'PACK.ACR.VASC.2021.T.01', 'PACK.ACR.VASC.2021.T.02',
    'PACK.ACR.VASC.2021.T.03', 'PACK.ACR.VASC.2021.TX.01', 'PACK.ACR.VASC.2021.TX.02',
    'PACK.ACR.VASC.2021.TX.03', 'PACK.ACR.VASC.2021.RF.01', 'PACK.ACR.VASC.2021.RF.02',
    'PACK.ACR.VASC.2021.RF.03', 'PACK.ACR.VASC.2021.SEV.01', 'PACK.ACR.VASC.2021.SEV.02',
  ],
  all_display_ids: [
    'ACR-VASC-R1', 'ACR-VASC-R2', 'ACR-VASC-R3', 'ACR-VASC-R4', 'ACR-VASC-R5',
    'ACR-VASC-DC1', 'ACR-VASC-DC2',
    'ACR-VASC-T1', 'ACR-VASC-T2', 'ACR-VASC-T3',
    'ACR-VASC-TX1', 'ACR-VASC-TX2', 'ACR-VASC-TX3',
    'ACR-VASC-RF1', 'ACR-VASC-RF2', 'ACR-VASC-RF3',
    'ACR-VASC-SEV1', 'ACR-VASC-SEV2',
  ],
};
