import type { SourcePack } from './types';

export const PACK_ACR_GOUT_2020: SourcePack = {
  source_pack_id: 'PACK.ACR.GOUT.2020',
  source_name: 'ACR Guideline for Management of Gout 2020',
  canonical_url: 'https://doi.org/10.1002/art.41247',
  publication_year: 2020,
  guideline_body: 'ACR',

  topic_tags: ['Gout', 'Hyperuricemia', 'Crystal Arthropathy', 'Pseudogout', 'Rheumatology'],
  allowed_decision_scopes: [
    'acute gout flare treatment',
    'urate-lowering therapy initiation and titration',
    'target serum urate level',
    'flare prophylaxis during ULT',
    'crystal analysis interpretation',
    'gout vs pseudogout differentiation',
    'ULT in CKD patients',
  ],
  excluded_decision_scopes: [
    'asymptomatic hyperuricemia without gout',
    'calcium pyrophosphate deposition disease management in detail',
    'uric acid nephrolithiasis management',
    'tumor lysis syndrome prophylaxis',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ACR.GOUT.2020.REC.01',
      display_id: 'ACR-GOUT-R1',
      statement: 'Allopurinol is conditionally recommended as the preferred first-line urate-lowering therapy over other ULT agents.',
      normalized_claim: 'Allopurinol is first-line ULT for gout; preferred over febuxostat and probenecid.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      context: 'Febuxostat is an alternative for allopurinol-intolerant patients. Avoid febuxostat in patients with significant cardiovascular disease (CARES trial).',
      provenance: { section: 'Urate-Lowering Therapy', page_or_location: 'Recommendation 4' },
    },
    {
      rec_id: 'PACK.ACR.GOUT.2020.REC.02',
      display_id: 'ACR-GOUT-R2',
      statement: 'ULT should be started at a low dose and titrated to target. Allopurinol should be initiated at <=100mg/day (<=50mg/day if CKD stage >=3) and titrated every 2-5 weeks.',
      normalized_claim: 'Start allopurinol low (100mg/day, 50mg if CKD >=3) and titrate upward every 2-5 weeks to target urate <6 mg/dL.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'ULT Dosing', page_or_location: 'Recommendation 5' },
    },
    {
      rec_id: 'PACK.ACR.GOUT.2020.REC.03',
      display_id: 'ACR-GOUT-R3',
      statement: 'Anti-inflammatory prophylaxis is strongly recommended when initiating ULT to prevent mobilization flares. Colchicine is the preferred agent.',
      normalized_claim: 'Colchicine 0.6mg once or twice daily for flare prophylaxis during ULT initiation, continuing for 3-6 months.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Flare Prophylaxis', page_or_location: 'Recommendation 8' },
    },
    {
      rec_id: 'PACK.ACR.GOUT.2020.REC.04',
      display_id: 'ACR-GOUT-R4',
      statement: 'ULT should NOT be stopped during an acute gout flare. If already on ULT, continue it. If not yet started, ULT may be initiated during a flare.',
      normalized_claim: 'Never stop ULT during an acute flare; continuing ULT does not worsen flare outcomes.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      provenance: { section: 'ULT During Flares', page_or_location: 'Recommendation 6' },
    },
    {
      rec_id: 'PACK.ACR.GOUT.2020.REC.05',
      display_id: 'ACR-GOUT-R5',
      statement: 'For acute gout flare treatment, colchicine, NSAIDs, or glucocorticoids are recommended as first-line monotherapy. Choice depends on patient comorbidities.',
      normalized_claim: 'Acute gout flare: colchicine (within 36h of onset), NSAIDs, or glucocorticoids as first-line depending on comorbidities.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'Colchicine most effective if started within 36 hours of flare onset. NSAIDs preferred if no renal or GI contraindication. Steroids for patients with CKD or NSAID contraindications.',
      provenance: { section: 'Acute Flare Management', page_or_location: 'Recommendation 1' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ACR.GOUT.2020.DC.01',
      display_id: 'ACR-GOUT-DC1',
      name: 'Definitive Gout Diagnosis by Crystal Analysis',
      components: [
        'Arthrocentesis of affected joint',
        'Polarized light microscopy of synovial fluid',
        'Identification of monosodium urate (MSU) crystals: needle-shaped, negatively birefringent (yellow when parallel to slow axis)',
        'Differentiation from calcium pyrophosphate (CPP) crystals: rhomboid-shaped, positively birefringent (blue when parallel to slow axis)',
      ],
      interpretation: 'Needle-shaped negatively birefringent crystals = gout (MSU). Rhomboid positively birefringent crystals = pseudogout (CPPD). Crystal analysis is the gold standard.',
      normalized_claim: 'Gout diagnosis confirmed by negatively birefringent needle-shaped MSU crystals on polarized microscopy; pseudogout shows positively birefringent rhomboid CPP crystals.',
      provenance: { section: 'Diagnosis', page_or_location: 'Background, Crystal Analysis' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ACR.GOUT.2020.T.01',
      display_id: 'ACR-GOUT-T1',
      parameter: 'Serum urate target',
      value: '6',
      unit: 'mg/dL',
      clinical_meaning: 'Treat-to-target: serum urate <6 mg/dL for all gout patients on ULT. Below the saturation point for monosodium urate crystallization.',
      normalized_claim: 'Target serum urate <6 mg/dL on ULT; this is below the MSU crystallization threshold.',
      direction: 'below',
      provenance: { section: 'ULT Target', page_or_location: 'Recommendation 3' },
    },
    {
      threshold_id: 'PACK.ACR.GOUT.2020.T.02',
      display_id: 'ACR-GOUT-T2',
      parameter: 'Colchicine flare prophylaxis duration',
      value: '3-6',
      unit: 'months',
      clinical_meaning: 'Flare prophylaxis should continue for at least 3 months (6 months preferred) after reaching target serum urate, or longer if tophi present.',
      normalized_claim: 'Continue flare prophylaxis 3-6 months after achieving target urate; longer if tophi present.',
      direction: 'range',
      provenance: { section: 'Flare Prophylaxis', page_or_location: 'Recommendation 8' },
    },
    {
      threshold_id: 'PACK.ACR.GOUT.2020.T.03',
      display_id: 'ACR-GOUT-T3',
      parameter: 'Allopurinol starting dose in CKD stage >=3',
      value: '50',
      unit: 'mg/day',
      clinical_meaning: 'Reduced starting dose in CKD to minimize hypersensitivity risk. Titrate upward with urate monitoring every 2-5 weeks. CKD does not limit maximum dose if tolerated.',
      normalized_claim: 'Start allopurinol at 50mg/day in CKD >=3 (not 100mg); CKD does not cap the maximum tolerated dose.',
      direction: 'below',
      provenance: { section: 'ULT Dosing', page_or_location: 'Recommendation 5' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ACR.GOUT.2020.TX.01',
      display_id: 'ACR-GOUT-TX1',
      action: 'Acute gout flare: Colchicine within 36 hours',
      normalized_claim: 'Colchicine 1.2mg followed by 0.6mg one hour later, then 0.6mg once or twice daily until flare resolves. Most effective within 36 hours of onset.',
      timing: 'Within 36 hours of flare onset for maximum efficacy',
      condition: 'Acute gout flare without renal failure or colchicine contraindications',
      drug_details: { drug: 'Colchicine', dose: '1.2mg then 0.6mg in 1 hour (day 1); 0.6mg daily-BID after', route: 'PO' },
      contraindications: ['Severe renal impairment (eGFR <30)', 'Concurrent strong CYP3A4 inhibitors or P-glycoprotein inhibitors', 'Hepatic impairment'],
      provenance: { section: 'Acute Flare Management', page_or_location: 'Recommendation 1' },
    },
    {
      step_id: 'PACK.ACR.GOUT.2020.TX.02',
      display_id: 'ACR-GOUT-TX2',
      action: 'Acute gout flare: Glucocorticoids for patients with CKD or NSAID contraindications',
      normalized_claim: 'Prednisone 0.5mg/kg/day for 5-10 days (or taper) for acute gout when NSAIDs and colchicine are contraindicated.',
      timing: 'At flare onset when colchicine and NSAIDs are contraindicated',
      condition: 'Acute gout flare in patients with CKD, GI disease, or anticoagulation',
      drug_details: { drug: 'Prednisone', dose: '0.5mg/kg/day', route: 'PO', duration: '5-10 days then taper' },
      contraindications: ['Uncontrolled diabetes (relative)', 'Active systemic infection'],
      provenance: { section: 'Acute Flare Management', page_or_location: 'Recommendation 1' },
    },
    {
      step_id: 'PACK.ACR.GOUT.2020.TX.03',
      display_id: 'ACR-GOUT-TX3',
      action: 'Initiate allopurinol with titration to urate target',
      normalized_claim: 'Start allopurinol 100mg/day (50mg in CKD >=3). Titrate by 100mg every 2-5 weeks. Goal serum urate <6 mg/dL. Concurrent flare prophylaxis required.',
      timing: 'After >=2 flares/year, tophi, CKD, or urolithiasis',
      condition: 'Indication for urate-lowering therapy established',
      drug_details: { drug: 'Allopurinol', dose: '100mg/day initial, titrate to target', route: 'PO' },
      contraindications: ['HLA-B*5801 positive (check before starting in Southeast Asian, African American, or Korean patients)'],
      escalation: 'If allopurinol-intolerant, switch to febuxostat 40mg daily (avoid if significant CV disease)',
      provenance: { section: 'ULT Dosing', page_or_location: 'Recommendation 5' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ACR.GOUT.2020.RF.01',
      display_id: 'ACR-GOUT-RF1',
      finding: 'Allopurinol hypersensitivity syndrome (AHS): Fever, rash (especially SJS/TEN), eosinophilia, hepatitis, renal failure after starting allopurinol',
      implication: 'Life-threatening drug reaction with 20-30% mortality. Associated with HLA-B*5801 allele.',
      action: 'Stop allopurinol immediately. Supportive care. Never rechallenge. Screen HLA-B*5801 before starting allopurinol in high-risk populations (Southeast Asian, African American, Korean descent).',
      urgency: 'immediate',
      provenance: { section: 'ULT Safety', page_or_location: 'Recommendation 5, Safety note' },
    },
    {
      flag_id: 'PACK.ACR.GOUT.2020.RF.02',
      display_id: 'ACR-GOUT-RF2',
      finding: 'Septic arthritis mimicking gout flare: Monoarticular joint effusion with fever, especially in immunocompromised patients',
      implication: 'Gout and septic arthritis can coexist. Crystals do not exclude infection.',
      action: 'Arthrocentesis with Gram stain, culture, cell count, AND crystal analysis on every acute monoarthritis. Treat empirically for septic arthritis until culture results available.',
      urgency: 'immediate',
      provenance: { section: 'Diagnosis', page_or_location: 'Differential Diagnosis' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ACR.GOUT.2020.SEV.01',
      display_id: 'ACR-GOUT-SEV1',
      level: 'Tophaceous gout',
      criteria: [
        'Visible or palpable tophi on exam',
        'Chronic synovitis with joint damage',
        'Serum urate persistently elevated despite ULT',
        'Frequent flares (>=2/year) despite therapy',
      ],
      management_implications:
        'Aggressive ULT titration (may need higher allopurinol doses up to 800mg/day). Extended flare prophylaxis (>=6 months). Consider pegloticase for refractory tophaceous gout failing oral ULT. Target urate <5 mg/dL to accelerate tophus resolution.',
      provenance: { section: 'Refractory Gout', page_or_location: 'Recommendation 9' },
    },
    {
      severity_id: 'PACK.ACR.GOUT.2020.SEV.02',
      display_id: 'ACR-GOUT-SEV2',
      level: 'Mild/infrequent gout',
      criteria: [
        'Fewer than 2 flares per year',
        'No tophi',
        'No chronic arthropathy',
        'Normal renal function',
      ],
      management_implications:
        'Acute flare treatment PRN may suffice initially. ULT conditionally recommended if >=2 flares/year, any tophus, or radiographic damage. Lifestyle modifications (weight loss, limit alcohol/purine-rich foods).',
      provenance: { section: 'ULT Indications', page_or_location: 'Recommendation 2' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 lightweight pack for gout. Covers acute flare management, ULT initiation/titration, crystal analysis, and gout vs pseudogout differentiation.',

  all_item_ids: [
    'PACK.ACR.GOUT.2020.REC.01', 'PACK.ACR.GOUT.2020.REC.02', 'PACK.ACR.GOUT.2020.REC.03',
    'PACK.ACR.GOUT.2020.REC.04', 'PACK.ACR.GOUT.2020.REC.05', 'PACK.ACR.GOUT.2020.DC.01',
    'PACK.ACR.GOUT.2020.T.01', 'PACK.ACR.GOUT.2020.T.02', 'PACK.ACR.GOUT.2020.T.03',
    'PACK.ACR.GOUT.2020.TX.01', 'PACK.ACR.GOUT.2020.TX.02', 'PACK.ACR.GOUT.2020.TX.03',
    'PACK.ACR.GOUT.2020.RF.01', 'PACK.ACR.GOUT.2020.RF.02',
    'PACK.ACR.GOUT.2020.SEV.01', 'PACK.ACR.GOUT.2020.SEV.02',
  ],
  all_display_ids: [
    'ACR-GOUT-R1', 'ACR-GOUT-R2', 'ACR-GOUT-R3', 'ACR-GOUT-R4', 'ACR-GOUT-R5',
    'ACR-GOUT-DC1',
    'ACR-GOUT-T1', 'ACR-GOUT-T2', 'ACR-GOUT-T3',
    'ACR-GOUT-TX1', 'ACR-GOUT-TX2', 'ACR-GOUT-TX3',
    'ACR-GOUT-RF1', 'ACR-GOUT-RF2',
    'ACR-GOUT-SEV1', 'ACR-GOUT-SEV2',
  ],
};
