import type { SourcePack } from './types';

export const PACK_ACR_SLE_2019: SourcePack = {
  source_pack_id: 'PACK.ACR.SLE.2019',
  source_name: 'ACR/EULAR 2019 Classification Criteria and ACR Guideline for Management of SLE',
  canonical_url: 'https://doi.org/10.1002/art.40930',
  publication_year: 2019,
  guideline_body: 'ACR/EULAR',

  topic_tags: ['Systemic Lupus Erythematosus', 'Lupus Nephritis', 'Autoimmune', 'Rheumatology'],
  allowed_decision_scopes: [
    'SLE classification using 2019 ACR/EULAR criteria',
    'hydroxychloroquine use in all SLE patients',
    'lupus nephritis immunosuppressive therapy',
    'SLE flare management',
    'drug-induced lupus recognition',
    'anti-dsDNA and complement monitoring',
    'SLE pregnancy management',
  ],
  excluded_decision_scopes: [
    'antiphospholipid syndrome management in detail',
    'neonatal lupus management',
    'overlap connective tissue diseases',
    'SLE-related pulmonary hypertension management',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ACR.SLE.2019.REC.01',
      display_id: 'ACR-SLE-R1',
      statement: 'Hydroxychloroquine is recommended for ALL patients with SLE unless contraindicated. It reduces flares, damage accrual, thrombotic risk, and improves survival.',
      normalized_claim: 'Hydroxychloroquine for ALL SLE patients: reduces flares, organ damage, thrombotic events, and mortality.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'Continue even during remission. Dose <=5mg/kg/day to minimize retinal toxicity. Annual ophthalmologic screening after 5 years.',
      provenance: { section: 'Pharmacologic Treatment', page_or_location: 'Core therapy recommendation' },
    },
    {
      rec_id: 'PACK.ACR.SLE.2019.REC.02',
      display_id: 'ACR-SLE-R2',
      statement: 'For proliferative lupus nephritis (Class III/IV), induction therapy with mycophenolate mofetil or cyclophosphamide is recommended, followed by maintenance with mycophenolate.',
      normalized_claim: 'Lupus nephritis Class III/IV induction: mycophenolate mofetil or IV cyclophosphamide. Maintenance: mycophenolate mofetil.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'MMF preferred in patients of African or Hispanic ancestry (better outcomes in ALMS trial). Cyclophosphamide preferred for rapidly progressive or severe disease.',
      provenance: { section: 'Lupus Nephritis', page_or_location: 'Nephritis management' },
    },
    {
      rec_id: 'PACK.ACR.SLE.2019.REC.03',
      display_id: 'ACR-SLE-R3',
      statement: 'Glucocorticoids should be used at the lowest effective dose for the shortest duration. Steroid-sparing agents should be prioritized.',
      normalized_claim: 'Minimize glucocorticoid exposure in SLE. Prioritize steroid-sparing immunosuppressants (mycophenolate, azathioprine, belimumab).',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Glucocorticoid Management', page_or_location: 'Steroid reduction strategy' },
    },
    {
      rec_id: 'PACK.ACR.SLE.2019.REC.04',
      display_id: 'ACR-SLE-R4',
      statement: 'Anti-dsDNA antibody titers and complement levels (C3, C4) should be monitored serially as markers of disease activity and impending flare.',
      normalized_claim: 'Rising anti-dsDNA and falling C3/C4 complement levels predict SLE flare and guide treatment escalation.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Disease Monitoring', page_or_location: 'Serologic markers' },
    },
    {
      rec_id: 'PACK.ACR.SLE.2019.REC.05',
      display_id: 'ACR-SLE-R5',
      statement: 'Belimumab (anti-BLyS) is conditionally recommended as add-on therapy in patients with persistently active SLE despite standard therapy, particularly for reducing flares and steroid dependence.',
      normalized_claim: 'Belimumab add-on therapy for active SLE despite hydroxychloroquine and immunosuppressants; reduces flares and allows steroid tapering.',
      strength: 'conditional',
      evidence_quality: 'high',
      provenance: { section: 'Biologic Therapy', page_or_location: 'Belimumab recommendation' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ACR.SLE.2019.DC.01',
      display_id: 'ACR-SLE-DC1',
      name: '2019 ACR/EULAR SLE Classification Criteria',
      components: [
        'Entry criterion: ANA >=1:80 (by HEp-2 IFL or equivalent)',
        'Constitutional domain: Fever (2 points)',
        'Hematologic domain: Leukopenia (3), thrombocytopenia (4), autoimmune hemolysis (4)',
        'Neuropsychiatric domain: Delirium (2), psychosis (3), seizure (5)',
        'Mucocutaneous domain: Non-scarring alopecia (2), oral ulcers (2), subacute cutaneous or discoid lupus (4), acute cutaneous lupus (6)',
        'Serosal domain: Pleural or pericardial effusion (5), acute pericarditis (6)',
        'Musculoskeletal domain: Joint involvement (6)',
        'Renal domain: Proteinuria >0.5g/24h (4), Class II or V lupus nephritis (8), Class III or IV lupus nephritis (10)',
        'Immunologic criteria: Anti-dsDNA (6) or anti-Sm (6), antiphospholipid antibodies (2), low complement C3 OR C4 (3), low complement C3 AND C4 (4)',
      ],
      threshold: 'Score >=10 with ANA entry criterion classifies as SLE',
      interpretation: 'ANA >=1:80 is required entry criterion. Additive weighted scoring across 7 clinical and 3 immunologic domains. Highest-weighted item within each domain counts. >=10 points = SLE classification.',
      normalized_claim: '2019 ACR/EULAR SLE criteria: ANA >=1:80 entry + weighted domain scoring >=10 points. Renal (Class III/IV = 10 points) and anti-dsDNA/anti-Sm (6 points each) are highest weighted.',
      provenance: { section: 'Classification Criteria', page_or_location: 'Table 3' },
    },
    {
      criterion_id: 'PACK.ACR.SLE.2019.DC.02',
      display_id: 'ACR-SLE-DC2',
      name: 'Drug-Induced Lupus Recognition',
      components: [
        'Temporal relationship: Symptoms develop after weeks to months of drug exposure',
        'Common culprits: hydralazine, procainamide, isoniazid, minocycline, TNF inhibitors',
        'Positive anti-histone antibodies (present in >95% of drug-induced lupus)',
        'Anti-dsDNA typically NEGATIVE (unlike idiopathic SLE)',
        'Renal and CNS involvement are RARE (unlike idiopathic SLE)',
        'Symptoms resolve upon drug discontinuation',
      ],
      interpretation: 'Drug-induced lupus: anti-histone positive, anti-dsDNA negative, no renal/CNS involvement, resolves with drug cessation. Key differentiator from idiopathic SLE.',
      normalized_claim: 'Drug-induced lupus: anti-histone positive, anti-dsDNA negative, spares kidneys/CNS, resolves with drug discontinuation. Common triggers: hydralazine, procainamide, isoniazid.',
      provenance: { section: 'Differential Diagnosis', page_or_location: 'Drug-induced lupus' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ACR.SLE.2019.T.01',
      display_id: 'ACR-SLE-T1',
      parameter: 'ANA titer (entry criterion)',
      value: '1:80',
      clinical_meaning: 'ANA >=1:80 by immunofluorescence on HEp-2 cells is the mandatory entry criterion for the 2019 classification. Without this, SLE classification criteria cannot be applied.',
      normalized_claim: 'ANA >=1:80 is the mandatory entry gate for 2019 ACR/EULAR SLE classification criteria.',
      direction: 'above',
      provenance: { section: 'Entry Criterion', page_or_location: 'Table 3, Entry criterion' },
    },
    {
      threshold_id: 'PACK.ACR.SLE.2019.T.02',
      display_id: 'ACR-SLE-T2',
      parameter: 'Proteinuria for lupus nephritis classification',
      value: '0.5',
      unit: 'g/24h',
      clinical_meaning: 'Proteinuria >0.5g/24h in the context of SLE warrants renal biopsy to classify lupus nephritis and guide immunosuppressive therapy.',
      normalized_claim: 'Proteinuria >0.5g/24h in SLE triggers renal biopsy; scores 4 points on classification criteria (8-10 with biopsy confirmation).',
      direction: 'above',
      provenance: { section: 'Renal Domain', page_or_location: 'Table 3, Renal criteria' },
    },
    {
      threshold_id: 'PACK.ACR.SLE.2019.T.03',
      display_id: 'ACR-SLE-T3',
      parameter: 'Hydroxychloroquine dose limit',
      value: '5',
      unit: 'mg/kg/day',
      clinical_meaning: 'HCQ dose should not exceed 5mg/kg/day to minimize risk of irreversible retinal toxicity. Annual ophthalmologic screening recommended after 5 years of use.',
      normalized_claim: 'HCQ dose <=5mg/kg/day to prevent retinal toxicity; annual eye exam after 5 years of use.',
      direction: 'below',
      provenance: { section: 'HCQ Safety', page_or_location: 'Pharmacologic treatment, dosing' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ACR.SLE.2019.TX.01',
      display_id: 'ACR-SLE-TX1',
      action: 'Initiate hydroxychloroquine for all SLE patients',
      normalized_claim: 'Start HCQ <=5mg/kg/day at SLE diagnosis. Continue indefinitely including during remission. Baseline and annual ophthalmologic screening.',
      timing: 'At SLE diagnosis',
      condition: 'All patients diagnosed with SLE',
      drug_details: { drug: 'Hydroxychloroquine', dose: '<=5mg/kg/day (typically 200-400mg daily)', route: 'PO' },
      contraindications: ['Pre-existing macular disease', 'Known retinal toxicity from prior HCQ use', 'Hypersensitivity to 4-aminoquinolines'],
      provenance: { section: 'Core Therapy', page_or_location: 'HCQ recommendation' },
    },
    {
      step_id: 'PACK.ACR.SLE.2019.TX.02',
      display_id: 'ACR-SLE-TX2',
      action: 'Induction immunosuppression for proliferative lupus nephritis (Class III/IV)',
      normalized_claim: 'Mycophenolate mofetil 2-3g/day (preferred in African/Hispanic patients) OR IV cyclophosphamide (Euro-Lupus or NIH protocol) for Class III/IV lupus nephritis induction.',
      timing: 'Upon biopsy-confirmed Class III or IV lupus nephritis',
      condition: 'Biopsy-proven proliferative lupus nephritis (Class III or IV)',
      drug_details: { drug: 'Mycophenolate mofetil', dose: '2-3g/day in divided doses', route: 'PO' },
      contraindications: ['Pregnancy (teratogenic)', 'Active serious infection', 'Live vaccines during treatment'],
      escalation: 'If refractory to MMF, switch to cyclophosphamide. Consider rituximab for refractory cases.',
      provenance: { section: 'Lupus Nephritis', page_or_location: 'Induction therapy' },
    },
    {
      step_id: 'PACK.ACR.SLE.2019.TX.03',
      display_id: 'ACR-SLE-TX3',
      action: 'SLE flare management with glucocorticoid pulse',
      normalized_claim: 'IV methylprednisolone 500-1000mg/day for 3 days for severe SLE flares (nephritis, cerebritis, severe cytopenias), then oral prednisone taper.',
      timing: 'At onset of severe SLE flare',
      condition: 'Severe SLE flare with major organ involvement',
      drug_details: { drug: 'Methylprednisolone', dose: '500-1000mg/day x 3 days', route: 'IV' },
      contraindications: ['Active systemic infection', 'Uncontrolled hypertension (relative)'],
      provenance: { section: 'Flare Management', page_or_location: 'Severe flare protocol' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ACR.SLE.2019.RF.01',
      display_id: 'ACR-SLE-RF1',
      finding: 'Rapidly progressive glomerulonephritis: Rising creatinine with active urine sediment (RBC casts, dysmorphic RBCs) and heavy proteinuria in SLE',
      implication: 'Diffuse proliferative lupus nephritis (Class IV) with crescent formation. Risk of permanent renal failure without immediate treatment.',
      action: 'Urgent renal biopsy. IV methylprednisolone pulse 1g x 3 days. Start induction immunosuppression (cyclophosphamide preferred for severe/crescentic disease). Nephrology consultation.',
      urgency: 'immediate',
      provenance: { section: 'Lupus Nephritis', page_or_location: 'Emergency nephritis management' },
    },
    {
      flag_id: 'PACK.ACR.SLE.2019.RF.02',
      display_id: 'ACR-SLE-RF2',
      finding: 'Catastrophic antiphospholipid syndrome: Multi-organ thrombosis developing over days with thrombocytopenia and positive antiphospholipid antibodies in SLE',
      implication: 'Life-threatening with >30% mortality. Requires triple therapy.',
      action: 'Therapeutic anticoagulation (heparin) + high-dose glucocorticoids + plasma exchange or IVIG. ICU admission.',
      urgency: 'immediate',
      provenance: { section: 'Complications', page_or_location: 'APS in SLE' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ACR.SLE.2019.SEV.01',
      display_id: 'ACR-SLE-SEV1',
      level: 'Severe SLE (major organ involvement)',
      criteria: [
        'Proliferative lupus nephritis (Class III/IV) with rising creatinine or nephrotic-range proteinuria',
        'Neuropsychiatric lupus (seizures, psychosis, transverse myelitis)',
        'Severe hematologic: hemolytic anemia (Hgb <7), thrombocytopenia (<20,000), TTP-like picture',
        'Pulmonary hemorrhage or severe serositis with hemodynamic compromise',
        'Mesenteric vasculitis',
      ],
      management_implications:
        'IV methylprednisolone pulse (1g x 3 days) followed by high-dose oral prednisone taper. Aggressive immunosuppression (cyclophosphamide or mycophenolate). Consider rituximab for refractory disease. Hospital admission. Subspecialty consultation (nephrology, neurology as needed).',
      provenance: { section: 'Severity Assessment', page_or_location: 'Organ-threatening SLE' },
    },
    {
      severity_id: 'PACK.ACR.SLE.2019.SEV.02',
      display_id: 'ACR-SLE-SEV2',
      level: 'Mild-to-moderate SLE',
      criteria: [
        'Mucocutaneous disease (rash, oral ulcers, alopecia)',
        'Arthritis/arthralgia without erosive changes',
        'Mild cytopenias (not life-threatening)',
        'Serositis without hemodynamic compromise',
        'Constitutional symptoms (fatigue, fever)',
      ],
      management_implications:
        'Hydroxychloroquine (continue or optimize). Low-dose glucocorticoids (<=7.5mg prednisone). Consider azathioprine or methotrexate as steroid-sparing agents. Belimumab add-on if recurrent flares. Outpatient management with close monitoring.',
      provenance: { section: 'Severity Assessment', page_or_location: 'Non-organ-threatening SLE' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 lightweight pack for SLE. Covers 2019 ACR/EULAR classification, HCQ for all, lupus nephritis induction/maintenance, drug-induced lupus differentiation, and severity stratification.',

  all_item_ids: [
    'PACK.ACR.SLE.2019.REC.01', 'PACK.ACR.SLE.2019.REC.02', 'PACK.ACR.SLE.2019.REC.03',
    'PACK.ACR.SLE.2019.REC.04', 'PACK.ACR.SLE.2019.REC.05', 'PACK.ACR.SLE.2019.DC.01',
    'PACK.ACR.SLE.2019.DC.02', 'PACK.ACR.SLE.2019.T.01', 'PACK.ACR.SLE.2019.T.02',
    'PACK.ACR.SLE.2019.T.03', 'PACK.ACR.SLE.2019.TX.01', 'PACK.ACR.SLE.2019.TX.02',
    'PACK.ACR.SLE.2019.TX.03', 'PACK.ACR.SLE.2019.RF.01', 'PACK.ACR.SLE.2019.RF.02',
    'PACK.ACR.SLE.2019.SEV.01', 'PACK.ACR.SLE.2019.SEV.02',
  ],
  all_display_ids: [
    'ACR-SLE-R1', 'ACR-SLE-R2', 'ACR-SLE-R3', 'ACR-SLE-R4', 'ACR-SLE-R5',
    'ACR-SLE-DC1', 'ACR-SLE-DC2',
    'ACR-SLE-T1', 'ACR-SLE-T2', 'ACR-SLE-T3',
    'ACR-SLE-TX1', 'ACR-SLE-TX2', 'ACR-SLE-TX3',
    'ACR-SLE-RF1', 'ACR-SLE-RF2',
    'ACR-SLE-SEV1', 'ACR-SLE-SEV2',
  ],
};
