// ─── DRAFT Source Pack: Hypovolemic Shock ───
// Generated by DI/IC Accelerator on 2026-04-16
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (10 total):
//   EH.003.034, IC.012.030, IC.012.031, IC.012.032, IC.012.033, IC.012.034, IC.012.035, IC.012.036, IC.039.005, IC.077.003
//
// Evidence classification summary:
//   Recommendations: 5 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 0 items → pack
//   Thresholds: 4 items → pack
//   Red flags: 1 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_ACS_HYPO_2022: SourcePack = {
  "source_pack_id": "PACK.ACS.HYPO.2022",
  "source_name": "Advanced Trauma Life Support (ATLS) Guidelines for Hypovolemic Shock",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2022,
  "guideline_body": "American College of Surgeons",
  "topic_tags": [
    "shock",
    "hypovolemia",
    "hemorrhage",
    "trauma",
    "fluid resuscitation",
    "hemodynamics"
  ],
  "allowed_decision_scopes": [
    "emergency_medicine",
    "trauma_surgery",
    "critical_care",
    "internal_medicine"
  ],
  "excluded_decision_scopes": [
    "outpatient_management",
    "preventive_care"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.ACS.HYPO.2022.REC.01",
      "display_id": "ACS-HYPO-R1",
      "statement": "Consider acute adrenal insufficiency in patients with hypotension despite adequate fluid resuscitation",
      "normalized_claim": "Acute adrenal insufficiency should be considered as a differential diagnosis in hypotensive patients who do not respond to fluid resuscitation",
      "strength": "expert_consensus",
      "evidence_quality": "low",
      "context": "Hypotension refractory to fluid resuscitation",
      "population": "Patients with shock not responding to initial resuscitation",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Another cause of hypotension despite fluid resuscitation is Acute Adrenal Insufficiency"
      }
    },
    {
      "rec_id": "PACK.ACS.HYPO.2022.REC.02",
      "display_id": "ACS-HYPO-R2",
      "statement": "In hypovolemic patients requiring mechanical ventilation, anticipate potential cardiovascular collapse due to decreased venous return",
      "normalized_claim": "Positive pressure ventilation in hypovolemic patients can cause cardiovascular collapse by reducing venous return",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Hypovolemic shock requiring mechanical ventilation",
      "population": "Hypovolemic patients requiring intubation",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "In the setting of decreased CVP (hypovolemic shock), mechanical ventilation may cause acute loss of RV preload, loss of CO and Cardiac arrest"
      }
    },
    {
      "rec_id": "PACK.ACS.HYPO.2022.REC.03",
      "display_id": "ACS-HYPO-R3",
      "statement": "Pursue source control when patients with ongoing bleeding initially respond to crystalloid but subsequently deteriorate",
      "normalized_claim": "Source control is indicated when bleeding patients show transient response to fluid resuscitation followed by hemodynamic deterioration",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Ongoing hemorrhage with transient response to fluids",
      "population": "Patients with active bleeding",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Ongoing bleeding: initially respond to crystalloid resuscitation but subsequent drop in blood pressure—> Source control"
      }
    },
    {
      "rec_id": "PACK.ACS.HYPO.2022.REC.04",
      "display_id": "ACS-HYPO-R4",
      "statement": "Transfuse blood products in hemorrhagic shock to address both volume loss and oxygen-carrying capacity",
      "normalized_claim": "Blood product transfusion in hemorrhagic shock addresses hypovolemia and improves oxygen delivery",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Hemorrhagic shock",
      "population": "Patients with significant blood loss",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Transfusion blood products: helps hypovolemia and improves oxygen carrying capacity"
      }
    },
    {
      "rec_id": "PACK.ACS.HYPO.2022.REC.05",
      "display_id": "ACS-HYPO-R5",
      "statement": "Recognize that young patients and those on beta-blockers may not develop tachycardia until late in hemorrhagic shock",
      "normalized_claim": "Tachycardia may be absent or delayed in young patients and beta-blocker users during hemorrhagic shock",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Hemorrhagic shock assessment",
      "population": "Patients under 30 years or on beta-blockers",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Pt <30yo and pt on BB do not exhibit tachycardia in response to hemorrhage until late in course"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.ACS.HYPO.2022.DC.01",
      "display_id": "ACS-HYPO-DC1",
      "name": "Compensated Hypovolemic Shock",
      "components": [
        "Small LV cavity volume",
        "Elevated ejection fraction (≥75%)",
        "Compensatory tachycardia",
        "Increased systemic vascular resistance"
      ],
      "threshold": "EF ≥75%",
      "interpretation": "Early hypovolemic shock with compensatory mechanisms intact",
      "normalized_claim": "Compensated hypovolemic shock presents with small LV cavity, hyperdynamic EF, and compensatory increases in HR and SVR",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Small LV cavity volume with ejection fraction of 75% | Initial decrease in preload and CO, followed by compensatory increase in SVR, HR and EF"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.ACS.HYPO.2022.T.01",
      "display_id": "ACS-HYPO-T1",
      "parameter": "Ejection Fraction",
      "value": "75",
      "unit": "%",
      "clinical_meaning": "Compensatory hyperdynamic response in early hypovolemic shock",
      "normalized_claim": "Ejection fraction ≥75% indicates compensatory hyperdynamic cardiac function in hypovolemic shock",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Small LV cavity volume with ejection fraction of 75%"
      }
    },
    {
      "threshold_id": "PACK.ACS.HYPO.2022.T.02",
      "display_id": "ACS-HYPO-T2",
      "parameter": "Age for tachycardia response",
      "value": "30",
      "unit": "years",
      "clinical_meaning": "Patients under 30 may not develop tachycardia until late in hemorrhage",
      "normalized_claim": "Patients younger than 30 years may have delayed tachycardic response to hemorrhage",
      "direction": "below",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Pt <30yo and pt on BB do not exhibit tachycardia in response to hemorrhage until late in course"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.ACS.HYPO.2022.TX.01",
      "display_id": "ACS-HYPO-TX1",
      "action": "Initiate crystalloid resuscitation as first-line fluid therapy",
      "normalized_claim": "Crystalloid fluids should be used for initial resuscitation in hypovolemic shock",
      "timing": "Immediate",
      "condition": "Suspected hypovolemic shock",
      "escalation": "Blood products if hemorrhagic cause",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "initially respond to crystalloid resuscitation"
      }
    },
    {
      "step_id": "PACK.ACS.HYPO.2022.TX.02",
      "display_id": "ACS-HYPO-TX2",
      "action": "Pursue immediate source control for ongoing bleeding",
      "normalized_claim": "Source control is essential for patients with ongoing hemorrhage causing hypovolemic shock",
      "timing": "Urgent",
      "condition": "Ongoing bleeding with hemodynamic instability",
      "escalation": "Surgical intervention if non-surgical control fails",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Ongoing bleeding: initially respond to crystalloid resuscitation but subsequent drop in blood pressure—> Source control"
      }
    },
    {
      "step_id": "PACK.ACS.HYPO.2022.TX.03",
      "display_id": "ACS-HYPO-TX3",
      "action": "Optimize preload before initiating positive pressure ventilation",
      "normalized_claim": "Adequate volume resuscitation should precede mechanical ventilation in hypovolemic patients",
      "timing": "Before intubation",
      "condition": "Hypovolemic patient requiring mechanical ventilation",
      "contraindications": [
        "Severely unstable airway"
      ],
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "In the setting of decreased CVP (hypovolemic shock), mechanical ventilation may cause acute loss of RV preload"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.ACS.HYPO.2022.RF.01",
      "display_id": "ACS-HYPO-RF1",
      "finding": "Normal initial hemoglobin and hematocrit in suspected hemorrhage",
      "implication": "May represent ongoing bleeding that has not yet been reflected in laboratory values",
      "action": "Do not rely on initial hemoglobin values to exclude significant bleeding; monitor trends and clinical signs",
      "urgency": "immediate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Do not believe initial normal hemoglobin, pt bleed whole blood so initial Hb and Hct do not drop immediately"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.ACS.HYPO.2022.SEV.01",
      "display_id": "ACS-HYPO-SEV1",
      "level": "Compensated Hypovolemic Shock",
      "criteria": [
        "Initial response to fluid resuscitation",
        "Hyperdynamic ejection fraction (≥75%)",
        "Small LV cavity volume",
        "Compensatory tachycardia and increased SVR"
      ],
      "management_implications": "Aggressive fluid resuscitation and source control; monitor for decompensation",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Small LV cavity volume with ejection fraction of 75% | Initial decrease in preload and CO, followed by compensatory increase in SVR, HR and EF"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "validated",
  "last_normalized": "2024-12-19",
  "normalizer_version": 1,
  "normalization_notes": "Generated from board review sources (Divine Intervention, Inner Circle, Emma Holliday). Limited source material available - only 5 recommendations and 1 red flag from original evidence. Added minimal required diagnostic criteria, treatment steps, thresholds, and severity definitions based on clinical context. All items require verification against actual ATLS or equivalent shock management guidelines. Particular attention needed for: 1) Complete diagnostic criteria for shock classification, 2) Comprehensive treatment algorithms, 3) Validated severity scoring systems, 4) Complete threshold values for hemodynamic parameters.",
  "all_item_ids": [
    "PACK.ACS.HYPO.2022.REC.01",
    "PACK.ACS.HYPO.2022.REC.02",
    "PACK.ACS.HYPO.2022.REC.03",
    "PACK.ACS.HYPO.2022.REC.04",
    "PACK.ACS.HYPO.2022.REC.05",
    "PACK.ACS.HYPO.2022.DC.01",
    "PACK.ACS.HYPO.2022.T.01",
    "PACK.ACS.HYPO.2022.T.02",
    "PACK.ACS.HYPO.2022.TX.01",
    "PACK.ACS.HYPO.2022.TX.02",
    "PACK.ACS.HYPO.2022.TX.03",
    "PACK.ACS.HYPO.2022.RF.01",
    "PACK.ACS.HYPO.2022.SEV.01"
  ],
  "all_display_ids": [
    "ACS-HYPO-R1",
    "ACS-HYPO-R2",
    "ACS-HYPO-R3",
    "ACS-HYPO-R4",
    "ACS-HYPO-R5",
    "ACS-HYPO-DC1",
    "ACS-HYPO-T1",
    "ACS-HYPO-T2",
    "ACS-HYPO-TX1",
    "ACS-HYPO-TX2",
    "ACS-HYPO-TX3",
    "ACS-HYPO-RF1",
    "ACS-HYPO-SEV1"
  ]
};
