import type { SourcePack } from './types';

export const PACK_ACS_ATLS_2018: SourcePack = {
  source_pack_id: 'PACK.ACS.ATLS.2018',
  source_name: 'ACS ATLS 10th Edition — Advanced Trauma Life Support',
  canonical_url: 'https://www.facs.org/quality-programs/trauma/atls/',
  publication_year: 2018,
  guideline_body: 'ACS/ATLS',

  topic_tags: ['Trauma', 'Hemorrhagic Shock', 'FAST Exam', 'Massive Transfusion', 'Pneumothorax', 'Damage Control Surgery', 'Surgery'],
  allowed_decision_scopes: [
    'primary survey ABCDE',
    'secondary survey',
    'hemorrhagic shock classification and resuscitation',
    'FAST exam interpretation',
    'massive transfusion protocol activation',
    'tension pneumothorax management',
    'damage control surgery indications',
    'permissive hypotension strategy',
  ],
  excluded_decision_scopes: [
    'definitive orthopedic fixation',
    'chronic pain management post-trauma',
    'rehabilitation protocols',
    'forensic documentation specifics',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ACS.ATLS.2018.REC.01',
      display_id: 'ATLS-R1',
      statement: 'The primary survey follows the ABCDE sequence: Airway with C-spine protection, Breathing, Circulation, Disability (neurologic status), Exposure/Environment. Life-threatening conditions are addressed as identified.',
      normalized_claim: 'Primary survey follows ABCDE; life threats treated immediately upon identification before moving to next step.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Initial Assessment', page_or_location: 'Chapter 1' },
    },
    {
      rec_id: 'PACK.ACS.ATLS.2018.REC.02',
      display_id: 'ATLS-R2',
      statement: 'Massive transfusion protocol (MTP) should be activated for patients with hemorrhagic shock who are expected to require ≥10 units pRBC in 24 hours. Balanced resuscitation with 1:1:1 ratio of pRBC:FFP:platelets is recommended.',
      normalized_claim: 'MTP uses balanced 1:1:1 ratio (pRBC:FFP:platelets). Activate for anticipated need ≥10 units pRBC/24h.',
      strength: 'strong',
      evidence_quality: 'moderate',
      context: 'Based on PROPPR trial data and military experience',
      provenance: { section: 'Shock', page_or_location: 'Chapter 3' },
    },
    {
      rec_id: 'PACK.ACS.ATLS.2018.REC.03',
      display_id: 'ATLS-R3',
      statement: 'Permissive hypotension (target SBP 80-90 mmHg) is recommended in penetrating torso trauma prior to definitive hemorrhage control. Aggressive crystalloid resuscitation should be avoided.',
      normalized_claim: 'Permissive hypotension (SBP 80-90 mmHg) for penetrating torso trauma until surgical hemorrhage control. Avoid large-volume crystalloid.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      population: 'Penetrating torso trauma without TBI',
      provenance: { section: 'Shock', page_or_location: 'Chapter 3' },
    },
    {
      rec_id: 'PACK.ACS.ATLS.2018.REC.04',
      display_id: 'ATLS-R4',
      statement: 'FAST (Focused Assessment with Sonography for Trauma) should be performed during the primary survey in hemodynamically unstable blunt trauma patients. A positive FAST in an unstable patient warrants emergent operative exploration.',
      normalized_claim: 'FAST positive + hemodynamically unstable = emergent OR for exploratory laparotomy.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Abdominal and Pelvic Trauma', page_or_location: 'Chapter 5' },
    },
    {
      rec_id: 'PACK.ACS.ATLS.2018.REC.05',
      display_id: 'ATLS-R5',
      statement: 'Damage control surgery is indicated when the lethal triad of hypothermia, acidosis, and coagulopathy develops. The goal is abbreviated laparotomy with hemorrhage control and contamination containment, followed by ICU resuscitation before definitive repair.',
      normalized_claim: 'Damage control surgery for lethal triad (hypothermia + acidosis + coagulopathy): abbreviated surgery → ICU resuscitation → definitive repair.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Abdominal and Pelvic Trauma', page_or_location: 'Chapter 5' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ACS.ATLS.2018.DC.01',
      display_id: 'ATLS-DC1',
      name: 'Hemorrhagic Shock Classification (Classes I-IV)',
      components: [
        'Class I: <15% blood loss (~750 mL), normal vitals, minimal tachycardia',
        'Class II: 15-30% blood loss (750-1500 mL), tachycardia, narrowed pulse pressure, anxiety',
        'Class III: 30-40% blood loss (1500-2000 mL), tachycardia >120, hypotension, confusion, decreased UOP',
        'Class IV: >40% blood loss (>2000 mL), marked tachycardia, profound hypotension, lethargy, negligible UOP',
      ],
      threshold: 'Class III/IV require blood product transfusion',
      interpretation: 'Classification guides resuscitation strategy. Class I-II may respond to crystalloid alone; Class III-IV require blood products and likely surgical intervention.',
      normalized_claim: 'Hemorrhagic shock Class III (30-40% loss) presents with tachycardia >120, hypotension, confusion and requires crystalloid + blood. Class IV (>40%) is immediately life-threatening.',
      provenance: { section: 'Shock', page_or_location: 'Chapter 3, Table 3.1' },
    },
    {
      criterion_id: 'PACK.ACS.ATLS.2018.DC.02',
      display_id: 'ATLS-DC2',
      name: 'Tension Pneumothorax — Clinical Diagnosis',
      components: [
        'Respiratory distress with hypoxia',
        'Unilateral absent breath sounds',
        'Tracheal deviation away from affected side (late finding)',
        'Hypotension/shock',
        'Distended neck veins (may be absent if hypovolemic)',
      ],
      interpretation: 'Clinical diagnosis — do not delay treatment for imaging. Immediate needle decompression followed by tube thoracostomy.',
      normalized_claim: 'Tension pneumothorax is a clinical diagnosis (absent breath sounds, hypotension, distended neck veins). Treat immediately with needle decompression; do not wait for CXR.',
      provenance: { section: 'Thoracic Trauma', page_or_location: 'Chapter 4' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ACS.ATLS.2018.T.01',
      display_id: 'ATLS-T1',
      parameter: 'Estimated blood loss for Class III shock',
      value: '1500-2000',
      unit: 'mL',
      clinical_meaning: 'Class III hemorrhage (30-40% blood volume) requires crystalloid AND blood product resuscitation. Mental status changes and hypotension develop at this level.',
      normalized_claim: 'Class III hemorrhage = 1500-2000 mL loss (30-40% blood volume) with tachycardia, hypotension, and altered mental status.',
      direction: 'above',
      provenance: { section: 'Shock', page_or_location: 'Chapter 3, Table 3.1' },
    },
    {
      threshold_id: 'PACK.ACS.ATLS.2018.T.02',
      display_id: 'ATLS-T2',
      parameter: 'Permissive hypotension target SBP in penetrating trauma',
      value: '80-90',
      unit: 'mmHg',
      clinical_meaning: 'In penetrating torso trauma without TBI, targeting SBP 80-90 mmHg reduces hemorrhage while maintaining minimal perfusion until surgical control achieved.',
      normalized_claim: 'Target SBP 80-90 mmHg in penetrating torso trauma (permissive hypotension) until hemorrhage control.',
      direction: 'range',
      provenance: { section: 'Shock', page_or_location: 'Chapter 3' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ACS.ATLS.2018.TX.01',
      display_id: 'ATLS-TX1',
      action: 'Needle decompression for tension pneumothorax',
      normalized_claim: 'Tension pneumothorax: immediate needle decompression at 2nd intercostal space, midclavicular line (or 4th/5th ICS anterior axillary line), followed by tube thoracostomy.',
      timing: 'Immediately upon clinical diagnosis',
      condition: 'Tension pneumothorax identified on primary survey',
      provenance: { section: 'Thoracic Trauma', page_or_location: 'Chapter 4' },
    },
    {
      step_id: 'PACK.ACS.ATLS.2018.TX.02',
      display_id: 'ATLS-TX2',
      action: 'Initial crystalloid resuscitation for hemorrhagic shock',
      normalized_claim: 'Initial bolus 1L warm isotonic crystalloid (lactated Ringer preferred). Reassess response. Limit crystalloid to avoid dilutional coagulopathy; transition to blood products early.',
      timing: 'During primary survey circulation assessment',
      condition: 'Hemorrhagic shock — all classes',
      drug_details: { drug: 'Lactated Ringer solution', dose: '1L', route: 'IV' },
      provenance: { section: 'Shock', page_or_location: 'Chapter 3' },
    },
    {
      step_id: 'PACK.ACS.ATLS.2018.TX.03',
      display_id: 'ATLS-TX3',
      action: 'Massive transfusion protocol activation',
      normalized_claim: 'Activate MTP for Class III/IV hemorrhage or ongoing hemorrhage unresponsive to crystalloid. Use 1:1:1 balanced ratio (pRBC:FFP:platelets). Administer TXA within 3 hours of injury.',
      timing: 'Within minutes of identifying Class III/IV hemorrhage',
      condition: 'Class III/IV hemorrhagic shock or anticipated massive transfusion',
      drug_details: { drug: 'Tranexamic acid (TXA)', dose: '1g IV over 10 min, then 1g over 8h', route: 'IV' },
      provenance: { section: 'Shock', page_or_location: 'Chapter 3' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ACS.ATLS.2018.RF.01',
      display_id: 'ATLS-RF1',
      finding: 'Hemodynamic instability + positive FAST in blunt trauma',
      implication: 'Indicates significant hemoperitoneum requiring emergent surgical hemorrhage control.',
      action: 'Emergent exploratory laparotomy. Do not delay for CT scan.',
      urgency: 'immediate',
      provenance: { section: 'Abdominal and Pelvic Trauma', page_or_location: 'Chapter 5' },
    },
    {
      flag_id: 'PACK.ACS.ATLS.2018.RF.02',
      display_id: 'ATLS-RF2',
      finding: 'Lethal triad: hypothermia (<35°C) + metabolic acidosis (pH <7.2) + coagulopathy (INR >1.5)',
      implication: 'Self-perpetuating cycle of physiologic exhaustion. Mortality increases dramatically if not interrupted.',
      action: 'Abort definitive surgery. Perform damage control: pack and temporarily close abdomen. Transfer to ICU for resuscitation.',
      urgency: 'immediate',
      provenance: { section: 'Abdominal and Pelvic Trauma', page_or_location: 'Chapter 5' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ACS.ATLS.2018.SEV.01',
      display_id: 'ATLS-SEV1',
      level: 'Class III Hemorrhagic Shock',
      criteria: [
        'Estimated blood loss 30-40% (1500-2000 mL)',
        'Heart rate >120 bpm',
        'Systolic blood pressure decreased',
        'Altered mental status (confusion, anxiety)',
        'Decreased urine output (5-15 mL/h)',
      ],
      management_implications:
        'Requires crystalloid AND blood product transfusion. Likely requires surgical or interventional hemorrhage control. Activate massive transfusion protocol. Administer TXA. Identify and control source of hemorrhage.',
      provenance: { section: 'Shock', page_or_location: 'Chapter 3, Table 3.1' },
    },
    {
      severity_id: 'PACK.ACS.ATLS.2018.SEV.02',
      display_id: 'ATLS-SEV2',
      level: 'Class IV Hemorrhagic Shock',
      criteria: [
        'Estimated blood loss >40% (>2000 mL)',
        'Heart rate >140 bpm',
        'Systolic blood pressure profoundly decreased',
        'Lethargy or obtundation',
        'Negligible urine output',
        'Cold, pale extremities',
      ],
      management_implications:
        'Immediately life-threatening. Massive transfusion protocol mandatory. Emergent surgical hemorrhage control. Consider damage control surgery. High mortality without rapid intervention.',
      provenance: { section: 'Shock', page_or_location: 'Chapter 3, Table 3.1' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Surgery pack: ATLS trauma management. Covers primary survey, hemorrhagic shock classification, FAST, MTP, tension pneumothorax, damage control surgery.',

  all_item_ids: [
    'PACK.ACS.ATLS.2018.REC.01', 'PACK.ACS.ATLS.2018.REC.02', 'PACK.ACS.ATLS.2018.REC.03',
    'PACK.ACS.ATLS.2018.REC.04', 'PACK.ACS.ATLS.2018.REC.05',
    'PACK.ACS.ATLS.2018.DC.01', 'PACK.ACS.ATLS.2018.DC.02',
    'PACK.ACS.ATLS.2018.T.01', 'PACK.ACS.ATLS.2018.T.02',
    'PACK.ACS.ATLS.2018.TX.01', 'PACK.ACS.ATLS.2018.TX.02', 'PACK.ACS.ATLS.2018.TX.03',
    'PACK.ACS.ATLS.2018.RF.01', 'PACK.ACS.ATLS.2018.RF.02',
    'PACK.ACS.ATLS.2018.SEV.01', 'PACK.ACS.ATLS.2018.SEV.02',
  ],
  all_display_ids: [
    'ATLS-R1', 'ATLS-R2', 'ATLS-R3', 'ATLS-R4', 'ATLS-R5',
    'ATLS-DC1', 'ATLS-DC2',
    'ATLS-T1', 'ATLS-T2',
    'ATLS-TX1', 'ATLS-TX2', 'ATLS-TX3',
    'ATLS-RF1', 'ATLS-RF2',
    'ATLS-SEV1', 'ATLS-SEV2',
  ],
};
