import type { SourcePack } from './types';

export const PACK_ADA_T2DM_2024: SourcePack = {
  source_pack_id: 'PACK.ADA.T2DM.2024',
  source_name: 'ADA Standards of Care in Diabetes — 2024',
  canonical_url: 'https://doi.org/10.2337/dc24-SREV',
  publication_year: 2024,
  guideline_body: 'American Diabetes Association',

  topic_tags: ['Type 2 Diabetes', 'T2DM', 'Pharmacotherapy', 'Glucose Management', 'Cardiovascular Risk', 'Endocrinology'],
  allowed_decision_scopes: [
    'T2DM diagnosis',
    'T2DM initial pharmacotherapy',
    'T2DM A1c target selection',
    'T2DM add-on therapy for ASCVD',
    'T2DM add-on therapy for CKD',
    'T2DM add-on therapy for heart failure',
    'T2DM insulin initiation',
    'T2DM insulin intensification',
    'metformin use in renal impairment',
    'hypoglycemia risk assessment',
    'lifestyle modification in T2DM',
  ],
  excluded_decision_scopes: [
    'type 1 diabetes management',
    'gestational diabetes management',
    'DKA/HHS acute management',
    'diabetic retinopathy treatment',
    'pancreatic transplantation',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ADA.T2DM.2024.REC.01',
      display_id: 'ADA-T2DM-R1',
      statement: 'Metformin is the preferred initial pharmacologic agent for type 2 diabetes, in combination with lifestyle modifications, unless contraindicated.',
      normalized_claim: 'Metformin is first-line therapy for T2DM combined with lifestyle changes.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'Applies to newly diagnosed T2DM without compelling comorbidities (ASCVD, CKD, HF)',
      provenance: { section: 'Pharmacologic Approaches', page_or_location: 'Section 9.1' },
    },
    {
      rec_id: 'PACK.ADA.T2DM.2024.REC.02',
      display_id: 'ADA-T2DM-R2',
      statement: 'For patients with T2DM and established ASCVD or high cardiovascular risk, a GLP-1 receptor agonist or SGLT2 inhibitor with demonstrated cardiovascular benefit should be used independent of A1c.',
      normalized_claim: 'T2DM + ASCVD/high CV risk: add GLP-1 RA or SGLT2i with proven CV benefit, regardless of A1c.',
      strength: 'strong',
      evidence_quality: 'high',
      population: 'T2DM with established atherosclerotic cardiovascular disease or high CV risk',
      provenance: { section: 'Cardiovascular Risk Reduction', page_or_location: 'Section 9.2' },
    },
    {
      rec_id: 'PACK.ADA.T2DM.2024.REC.03',
      display_id: 'ADA-T2DM-R3',
      statement: 'For patients with T2DM and CKD (eGFR 20–60 mL/min/1.73m² or UACR ≥200 mg/g), an SGLT2 inhibitor with evidence of reducing CKD progression is recommended.',
      normalized_claim: 'T2DM + CKD (eGFR 20–60 or UACR ≥200): SGLT2i with proven renal benefit, independent of A1c.',
      strength: 'strong',
      evidence_quality: 'high',
      population: 'T2DM with chronic kidney disease',
      provenance: { section: 'CKD Management', page_or_location: 'Section 11.3' },
    },
    {
      rec_id: 'PACK.ADA.T2DM.2024.REC.04',
      display_id: 'ADA-T2DM-R4',
      statement: 'An A1c target of <7% (53 mmol/mol) is appropriate for most non-pregnant adults. More stringent targets (<6.5%) may be appropriate for select patients if achievable without significant hypoglycemia.',
      normalized_claim: 'A1c <7% for most adults; <6.5% if achievable without hypoglycemia in select patients.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'Less stringent A1c targets (<8%) for patients with limited life expectancy, extensive comorbidities, or history of severe hypoglycemia',
      provenance: { section: 'Glycemic Targets', page_or_location: 'Section 6.1' },
    },
    {
      rec_id: 'PACK.ADA.T2DM.2024.REC.05',
      display_id: 'ADA-T2DM-R5',
      statement: 'Lifestyle modification (medical nutrition therapy, 150 min/week moderate-intensity physical activity, weight management) is the foundation of T2DM management and should accompany all pharmacologic therapy.',
      normalized_claim: 'Lifestyle modification (diet + 150 min/week exercise + weight management) is foundational and accompanies all drug therapy.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Lifestyle Management', page_or_location: 'Section 5.1' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ADA.T2DM.2024.DC.01',
      display_id: 'ADA-T2DM-DC1',
      name: 'Diabetes Mellitus Diagnostic Criteria',
      components: [
        'Fasting plasma glucose (FPG) ≥126 mg/dL (fasting ≥8 hours)',
        '2-hour plasma glucose ≥200 mg/dL during 75g OGTT',
        'A1c ≥6.5% (NGSP-certified, DCCT-standardized assay)',
        'Random plasma glucose ≥200 mg/dL with classic symptoms (polyuria, polydipsia, weight loss)',
      ],
      threshold: 'Any one criterion is sufficient for diagnosis; two abnormal tests from same sample or two separate samples required (except random glucose + symptoms)',
      interpretation: 'In the absence of unequivocal hyperglycemia, diagnosis requires two abnormal test results from the same sample or two separate samples. Random glucose ≥200 + symptoms is diagnostic on its own.',
      normalized_claim: 'Diabetes: FPG ≥126, or 2h OGTT ≥200, or A1c ≥6.5%, or random glucose ≥200 + symptoms. Two tests needed unless symptomatic hyperglycemia.',
      provenance: { section: 'Classification and Diagnosis', page_or_location: 'Table 2.2' },
    },
    {
      criterion_id: 'PACK.ADA.T2DM.2024.DC.02',
      display_id: 'ADA-T2DM-DC2',
      name: 'Prediabetes Diagnostic Criteria',
      components: [
        'Fasting plasma glucose 100–125 mg/dL (impaired fasting glucose, IFG)',
        '2-hour plasma glucose 140–199 mg/dL during 75g OGTT (impaired glucose tolerance, IGT)',
        'A1c 5.7–6.4%',
      ],
      interpretation: 'Prediabetes identifies individuals at increased risk for developing T2DM. Lifestyle intervention reduces progression by 58% (DPP trial).',
      normalized_claim: 'Prediabetes: FPG 100–125, or 2h OGTT 140–199, or A1c 5.7–6.4%. Lifestyle intervention reduces T2DM progression by 58%.',
      provenance: { section: 'Classification and Diagnosis', page_or_location: 'Table 2.3' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ADA.T2DM.2024.T.01',
      display_id: 'ADA-T2DM-T1',
      parameter: 'A1c target',
      value: '7',
      unit: '%',
      clinical_meaning: 'General A1c target for most non-pregnant adults with T2DM. Reduces microvascular complications.',
      normalized_claim: 'A1c <7% is the general glycemic target; reduces microvascular complications in T2DM.',
      direction: 'below',
      provenance: { section: 'Glycemic Targets', page_or_location: 'Section 6.1' },
    },
    {
      threshold_id: 'PACK.ADA.T2DM.2024.T.02',
      display_id: 'ADA-T2DM-T2',
      parameter: 'A1c threshold for early insulin consideration',
      value: '10',
      unit: '%',
      clinical_meaning: 'Patients presenting with A1c >10% or symptomatic hyperglycemia (polyuria, polydipsia, weight loss) should be started on insulin as part of initial therapy.',
      normalized_claim: 'A1c >10% or symptomatic hyperglycemia: start insulin as initial therapy alongside metformin.',
      direction: 'above',
      provenance: { section: 'Insulin Initiation', page_or_location: 'Section 9.3' },
    },
    {
      threshold_id: 'PACK.ADA.T2DM.2024.T.03',
      display_id: 'ADA-T2DM-T3',
      parameter: 'eGFR threshold for metformin discontinuation',
      value: '30',
      unit: 'mL/min/1.73m²',
      clinical_meaning: 'Metformin should be discontinued when eGFR falls below 30 mL/min/1.73m² due to increased risk of lactic acidosis. Dose reduction recommended when eGFR 30–45.',
      normalized_claim: 'Stop metformin at eGFR <30; reduce dose at eGFR 30–45 due to lactic acidosis risk.',
      direction: 'below',
      provenance: { section: 'Metformin in Renal Impairment', page_or_location: 'Section 9.1' },
    },
    {
      threshold_id: 'PACK.ADA.T2DM.2024.T.04',
      display_id: 'ADA-T2DM-T4',
      parameter: 'A1c recheck interval',
      value: '3',
      unit: 'months',
      clinical_meaning: 'A1c should be measured at least twice yearly in patients meeting goals and quarterly in patients not meeting goals or after therapy changes.',
      normalized_claim: 'Recheck A1c every 3 months if not at goal; every 6 months if stable and at target.',
      direction: 'range',
      provenance: { section: 'Monitoring', page_or_location: 'Section 6.2' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ADA.T2DM.2024.TX.01',
      display_id: 'ADA-T2DM-TX1',
      action: 'Step 1: Lifestyle modification + metformin monotherapy',
      normalized_claim: 'Start metformin 500mg daily, titrate to 2000mg/day. Combine with lifestyle modification. Assess A1c in 3 months.',
      timing: 'At diagnosis',
      condition: 'Newly diagnosed T2DM without ASCVD/CKD/HF and A1c <10%',
      drug_details: { drug: 'Metformin', dose: '500–2000mg daily', route: 'PO', duration: 'Lifelong unless contraindicated' },
      contraindications: ['eGFR <30 mL/min/1.73m²', 'History of lactic acidosis', 'Acute or chronic metabolic acidosis'],
      escalation: 'If A1c not at goal after 3 months, add second agent',
      provenance: { section: 'Initial Therapy', page_or_location: 'Section 9.1' },
    },
    {
      step_id: 'PACK.ADA.T2DM.2024.TX.02',
      display_id: 'ADA-T2DM-TX2',
      action: 'Step 2: Add GLP-1 RA or SGLT2 inhibitor based on comorbidities',
      normalized_claim: 'Add GLP-1 RA if ASCVD or high CV risk. Add SGLT2i if HF or CKD. If no compelling comorbidity, choose based on A1c lowering, weight, cost, and hypoglycemia risk.',
      timing: 'When A1c not at goal on metformin monotherapy, or at diagnosis if ASCVD/CKD/HF present',
      condition: 'T2DM not at A1c goal on monotherapy or with compelling comorbidity',
      provenance: { section: 'Add-on Therapy', page_or_location: 'Figure 9.3' },
    },
    {
      step_id: 'PACK.ADA.T2DM.2024.TX.03',
      display_id: 'ADA-T2DM-TX3',
      action: 'Step 3: Initiate basal insulin',
      normalized_claim: 'Add basal insulin (glargine, detemir, or degludec) when oral agents + GLP-1 RA insufficient. Start 10 units/day or 0.1–0.2 units/kg/day. Titrate by 2 units every 3 days to fasting glucose target.',
      timing: 'When dual/triple oral therapy fails or A1c >10% at presentation',
      condition: 'T2DM with inadequate glycemic control on non-insulin agents',
      drug_details: { drug: 'Insulin glargine (or detemir/degludec)', dose: '10 units or 0.1–0.2 units/kg/day', route: 'SubQ', duration: 'Ongoing' },
      contraindications: ['Frequent severe hypoglycemia without adjustable lifestyle factors'],
      escalation: 'If fasting glucose at goal but A1c still elevated, add prandial insulin',
      provenance: { section: 'Insulin Therapy', page_or_location: 'Section 9.3' },
    },
    {
      step_id: 'PACK.ADA.T2DM.2024.TX.04',
      display_id: 'ADA-T2DM-TX4',
      action: 'Step 4: Add prandial insulin (basal-bolus regimen)',
      normalized_claim: 'Add rapid-acting insulin (lispro, aspart, or glulisine) before the largest meal initially, then expand to multiple meals. Alternative: switch to premixed insulin.',
      timing: 'When basal insulin optimized but A1c remains above target',
      condition: 'T2DM on optimized basal insulin with persistent postprandial hyperglycemia',
      drug_details: { drug: 'Insulin lispro/aspart/glulisine', dose: '4 units or 10% of basal dose before largest meal', route: 'SubQ' },
      provenance: { section: 'Insulin Intensification', page_or_location: 'Section 9.4' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ADA.T2DM.2024.RF.01',
      display_id: 'ADA-T2DM-RF1',
      finding: 'Hypoglycemia on sulfonylureas or insulin: glucose <54 mg/dL (level 2) or severe hypoglycemia requiring assistance (level 3)',
      implication: 'Recurrent severe hypoglycemia is associated with increased cardiovascular mortality, cognitive decline, and falls. Requires therapy reassessment.',
      action: 'Reduce or discontinue sulfonylurea. Reassess insulin dose. Consider switching to agents with lower hypoglycemia risk (GLP-1 RA, SGLT2i, DPP-4i). Educate on hypoglycemia recognition and treatment.',
      urgency: 'urgent',
      provenance: { section: 'Hypoglycemia', page_or_location: 'Section 6.3' },
    },
    {
      flag_id: 'PACK.ADA.T2DM.2024.RF.02',
      display_id: 'ADA-T2DM-RF2',
      finding: 'Lactic acidosis risk: metformin use with eGFR <30, acute kidney injury, hepatic failure, or contrast dye administration',
      implication: 'Metformin-associated lactic acidosis (MALA) has >50% mortality. Risk increases sharply with renal impairment and tissue hypoperfusion.',
      action: 'Hold metformin 48 hours before and after iodinated contrast. Discontinue metformin if eGFR <30 or acute illness causing hypoperfusion/hypoxia.',
      urgency: 'urgent',
      provenance: { section: 'Metformin Safety', page_or_location: 'Section 9.1' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ADA.T2DM.2024.SEV.01',
      display_id: 'ADA-T2DM-SEV1',
      level: 'Newly diagnosed T2DM without complications',
      criteria: [
        'A1c <10%',
        'No symptoms of hyperglycemia',
        'No established ASCVD, CKD, or heart failure',
        'eGFR >60 mL/min/1.73m²',
        'No diabetic retinopathy or neuropathy',
      ],
      management_implications:
        'Start metformin monotherapy with lifestyle modification. A1c target <7%. Recheck A1c at 3 months. Screen for complications at diagnosis: dilated eye exam, foot exam, urine albumin-to-creatinine ratio, lipid panel.',
      provenance: { section: 'Newly Diagnosed T2DM', page_or_location: 'Section 9.1' },
    },
    {
      severity_id: 'PACK.ADA.T2DM.2024.SEV.02',
      display_id: 'ADA-T2DM-SEV2',
      level: 'Established T2DM with cardiorenal complications',
      criteria: [
        'Established ASCVD (prior MI, stroke, PAD) or high CV risk',
        'CKD stage 3+ (eGFR <60) or albuminuria (UACR ≥30 mg/g)',
        'Heart failure (HFrEF or HFpEF)',
        'May be at any A1c level',
      ],
      management_implications:
        'Cardiorenal comorbidity drives drug selection independent of A1c. ASCVD: GLP-1 RA preferred. HF: SGLT2i preferred. CKD: SGLT2i with renal benefit data (empagliflozin, dapagliflozin, canagliflozin). Combination therapy common. Cardiology/nephrology co-management.',
      provenance: { section: 'Cardiorenal Risk Reduction', page_or_location: 'Section 9.2, 10.2, 11.3' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for T2DM management. Covers diagnostic criteria, stepwise pharmacotherapy, cardiorenal risk-driven drug selection, and insulin initiation for USMLE Step 2 CK question generation.',

  all_item_ids: [
    'PACK.ADA.T2DM.2024.REC.01', 'PACK.ADA.T2DM.2024.REC.02', 'PACK.ADA.T2DM.2024.REC.03',
    'PACK.ADA.T2DM.2024.REC.04', 'PACK.ADA.T2DM.2024.REC.05',
    'PACK.ADA.T2DM.2024.DC.01', 'PACK.ADA.T2DM.2024.DC.02',
    'PACK.ADA.T2DM.2024.T.01', 'PACK.ADA.T2DM.2024.T.02', 'PACK.ADA.T2DM.2024.T.03',
    'PACK.ADA.T2DM.2024.T.04',
    'PACK.ADA.T2DM.2024.TX.01', 'PACK.ADA.T2DM.2024.TX.02', 'PACK.ADA.T2DM.2024.TX.03',
    'PACK.ADA.T2DM.2024.TX.04',
    'PACK.ADA.T2DM.2024.RF.01', 'PACK.ADA.T2DM.2024.RF.02',
    'PACK.ADA.T2DM.2024.SEV.01', 'PACK.ADA.T2DM.2024.SEV.02',
  ],
  all_display_ids: [
    'ADA-T2DM-R1', 'ADA-T2DM-R2', 'ADA-T2DM-R3', 'ADA-T2DM-R4', 'ADA-T2DM-R5',
    'ADA-T2DM-DC1', 'ADA-T2DM-DC2',
    'ADA-T2DM-T1', 'ADA-T2DM-T2', 'ADA-T2DM-T3', 'ADA-T2DM-T4',
    'ADA-T2DM-TX1', 'ADA-T2DM-TX2', 'ADA-T2DM-TX3', 'ADA-T2DM-TX4',
    'ADA-T2DM-RF1', 'ADA-T2DM-RF2',
    'ADA-T2DM-SEV1', 'ADA-T2DM-SEV2',
  ],
};
