import type { SourcePack } from './types';

export const PACK_ADA_DKAHHS_2024: SourcePack = {
  source_pack_id: 'PACK.ADA.DKAHHS.2024',
  source_name: 'ADA Standards of Care in Diabetes — 2024: Diabetes Care in the Hospital',
  canonical_url: 'https://doi.org/10.2337/dc24-S016',
  publication_year: 2024,
  guideline_body: 'American Diabetes Association',

  topic_tags: ['DKA', 'HHS', 'Diabetic Ketoacidosis', 'Hyperosmolar Hyperglycemic State', 'Endocrinology', 'Critical Care'],
  allowed_decision_scopes: [
    'DKA diagnosis',
    'DKA severity classification',
    'DKA fluid resuscitation',
    'DKA insulin therapy',
    'DKA potassium management',
    'DKA bicarbonate administration',
    'DKA anion gap monitoring',
    'DKA transition to subcutaneous insulin',
    'HHS diagnosis',
    'HHS fluid management',
    'HHS insulin timing',
  ],
  excluded_decision_scopes: [
    'outpatient diabetes management',
    'chronic insulin dosing adjustments',
    'diabetic neuropathy management',
    'diabetic retinopathy screening',
    'type 1 diabetes autoimmune workup',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ADA.DKAHHS.2024.REC.01',
      display_id: 'ADA-DKAHHS-R1',
      statement: 'Continuous IV insulin infusion is the standard of care for moderate-to-severe DKA. Regular insulin drip at 0.1–0.14 units/kg/hr should be initiated after potassium is confirmed ≥3.3 mEq/L.',
      normalized_claim: 'DKA requires continuous IV insulin at 0.1–0.14 units/kg/hr; hold insulin until K+ ≥3.3 mEq/L.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'Applies to adult patients with moderate-to-severe DKA',
      provenance: { section: 'DKA Management', page_or_location: 'Table 16.1' },
    },
    {
      rec_id: 'PACK.ADA.DKAHHS.2024.REC.02',
      display_id: 'ADA-DKAHHS-R2',
      statement: 'Aggressive isotonic fluid resuscitation (0.9% NaCl at 15–20 mL/kg/hr or 1–1.5 L in the first hour) is the initial step in DKA and HHS management.',
      normalized_claim: 'Initial fluid resuscitation in DKA/HHS: 0.9% NaCl 15–20 mL/kg/hr (1–1.5 L) in the first hour.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Fluid Therapy', page_or_location: 'Section 16.2' },
    },
    {
      rec_id: 'PACK.ADA.DKAHHS.2024.REC.03',
      display_id: 'ADA-DKAHHS-R3',
      statement: 'Potassium replacement should be initiated before insulin therapy if serum K+ is <3.3 mEq/L. Insulin administration in the setting of hypokalemia can precipitate life-threatening arrhythmias.',
      normalized_claim: 'Replace K+ before starting insulin if K+ <3.3 mEq/L to prevent fatal arrhythmias.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Potassium Replacement', page_or_location: 'Section 16.3' },
    },
    {
      rec_id: 'PACK.ADA.DKAHHS.2024.REC.04',
      display_id: 'ADA-DKAHHS-R4',
      statement: 'Sodium bicarbonate administration is not recommended unless arterial pH is <6.9. Routine bicarbonate use has not shown benefit and may worsen intracellular acidosis and hypokalemia.',
      normalized_claim: 'Bicarbonate only if pH <6.9; routine use worsens intracellular acidosis and hypokalemia.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Bicarbonate Therapy', page_or_location: 'Section 16.4' },
    },
    {
      rec_id: 'PACK.ADA.DKAHHS.2024.REC.05',
      display_id: 'ADA-DKAHHS-R5',
      statement: 'Transition from IV to subcutaneous insulin requires: patient able to eat, anion gap closed (≤12), serum bicarbonate ≥15, pH >7.3, and overlap of subcutaneous insulin with IV drip for 1–2 hours.',
      normalized_claim: 'Transition to subQ insulin when AG ≤12, bicarb ≥15, pH >7.3, patient eating; overlap IV drip 1–2 hours.',
      strength: 'strong',
      evidence_quality: 'moderate',
      context: 'Premature discontinuation of IV insulin is a common cause of DKA recurrence',
      provenance: { section: 'Transition to Subcutaneous Insulin', page_or_location: 'Section 16.5' },
    },
    {
      rec_id: 'PACK.ADA.DKAHHS.2024.REC.06',
      display_id: 'ADA-DKAHHS-R6',
      statement: 'In HHS, fluid replacement is the primary initial intervention. Insulin should be withheld or given at a lower rate (0.05 units/kg/hr) until adequate volume resuscitation has been achieved.',
      normalized_claim: 'HHS: prioritize fluids over insulin. Start insulin at reduced rate (0.05 units/kg/hr) only after volume resuscitation.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'HHS Management', page_or_location: 'Section 16.6' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ADA.DKAHHS.2024.DC.01',
      display_id: 'ADA-DKAHHS-DC1',
      name: 'DKA Diagnostic Criteria',
      components: [
        'Blood glucose >250 mg/dL (though euglycemic DKA can occur with SGLT2 inhibitors)',
        'Arterial pH <7.3',
        'Serum bicarbonate <18 mEq/L',
        'Anion gap >12 mEq/L',
        'Ketonemia (serum beta-hydroxybutyrate ≥3.0 mmol/L) or ketonuria',
      ],
      interpretation: 'All five criteria should be assessed. DKA is confirmed by the combination of hyperglycemia, metabolic acidosis with elevated anion gap, and ketosis. Euglycemic DKA (glucose <250) occurs with SGLT2 inhibitors.',
      normalized_claim: 'DKA = glucose >250 + pH <7.3 + bicarb <18 + AG >12 + ketonemia/ketonuria. Euglycemic DKA possible with SGLT2i.',
      provenance: { section: 'DKA Diagnosis', page_or_location: 'Table 16.1' },
    },
    {
      criterion_id: 'PACK.ADA.DKAHHS.2024.DC.02',
      display_id: 'ADA-DKAHHS-DC2',
      name: 'HHS Diagnostic Criteria',
      components: [
        'Blood glucose >600 mg/dL',
        'Effective serum osmolality >320 mOsm/kg',
        'Arterial pH >7.3',
        'Serum bicarbonate >18 mEq/L',
        'Absent or minimal ketones',
        'Altered mental status or profound dehydration',
      ],
      interpretation: 'HHS is distinguished from DKA by the absence of significant ketoacidosis, markedly higher glucose, and hyperosmolality. Mixed DKA/HHS presentations occur in ~30% of cases.',
      normalized_claim: 'HHS = glucose >600 + osmolality >320 + pH >7.3 + minimal ketones + altered mental status. Mixed DKA/HHS occurs in ~30%.',
      provenance: { section: 'HHS Diagnosis', page_or_location: 'Table 16.2' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ADA.DKAHHS.2024.T.01',
      display_id: 'ADA-DKAHHS-T1',
      parameter: 'Anion gap',
      value: '12',
      unit: 'mEq/L',
      clinical_meaning: 'Anion gap closure (≤12) indicates resolution of ketoacidosis and is required before transitioning to subcutaneous insulin.',
      normalized_claim: 'Anion gap ≤12 mEq/L signals DKA resolution and readiness for insulin transition.',
      direction: 'below',
      provenance: { section: 'DKA Resolution', page_or_location: 'Section 16.5' },
    },
    {
      threshold_id: 'PACK.ADA.DKAHHS.2024.T.02',
      display_id: 'ADA-DKAHHS-T2',
      parameter: 'Blood glucose target during DKA treatment',
      value: '150–200',
      unit: 'mg/dL',
      clinical_meaning: 'When glucose reaches 200 mg/dL, add dextrose (D5) to IV fluids and reduce insulin rate to 0.02–0.05 units/kg/hr to prevent hypoglycemia while continuing to close the anion gap.',
      normalized_claim: 'Target glucose 150–200 mg/dL during DKA; add D5 at glucose 200 and reduce insulin rate.',
      direction: 'range',
      provenance: { section: 'Glucose Management in DKA', page_or_location: 'Section 16.3' },
    },
    {
      threshold_id: 'PACK.ADA.DKAHHS.2024.T.03',
      display_id: 'ADA-DKAHHS-T3',
      parameter: 'Serum potassium — hold insulin threshold',
      value: '3.3',
      unit: 'mEq/L',
      clinical_meaning: 'If K+ <3.3 mEq/L, do not start insulin. Replace potassium aggressively (20–40 mEq/hr IV) until K+ ≥3.3, then begin insulin.',
      normalized_claim: 'K+ <3.3 mEq/L: hold insulin, replace K+ at 20–40 mEq/hr until ≥3.3.',
      direction: 'below',
      provenance: { section: 'Potassium Replacement', page_or_location: 'Table 16.1' },
    },
    {
      threshold_id: 'PACK.ADA.DKAHHS.2024.T.04',
      display_id: 'ADA-DKAHHS-T4',
      parameter: 'Serum potassium — replacement range',
      value: '3.3–5.3',
      unit: 'mEq/L',
      clinical_meaning: 'If K+ is 3.3–5.3 mEq/L, add 20–30 mEq K+ to each liter of IV fluid to maintain K+ in the 4–5 mEq/L range during insulin therapy.',
      normalized_claim: 'K+ 3.3–5.3 mEq/L: add 20–30 mEq K+ per liter of IV fluid; target K+ 4–5 mEq/L.',
      direction: 'range',
      provenance: { section: 'Potassium Replacement', page_or_location: 'Table 16.1' },
    },
    {
      threshold_id: 'PACK.ADA.DKAHHS.2024.T.05',
      display_id: 'ADA-DKAHHS-T5',
      parameter: 'Arterial pH — bicarbonate threshold',
      value: '6.9',
      clinical_meaning: 'Sodium bicarbonate (100 mmol in 400 mL sterile water with 20 mEq KCl over 2 hours) is indicated only when pH <6.9.',
      normalized_claim: 'Bicarbonate indicated only when pH <6.9: 100 mmol NaHCO3 in 400 mL + 20 mEq KCl over 2 hours.',
      direction: 'below',
      provenance: { section: 'Bicarbonate Therapy', page_or_location: 'Section 16.4' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ADA.DKAHHS.2024.TX.01',
      display_id: 'ADA-DKAHHS-TX1',
      action: 'DKA Step 1: Aggressive IV fluid resuscitation',
      normalized_claim: 'Start 0.9% NaCl 15–20 mL/kg/hr (1–1.5 L first hour). Switch to 0.45% NaCl if corrected Na+ is normal/high.',
      timing: 'Immediately upon DKA diagnosis',
      condition: 'DKA confirmed by diagnostic criteria',
      drug_details: { drug: '0.9% Normal Saline', dose: '15–20 mL/kg/hr', route: 'IV' },
      provenance: { section: 'DKA Fluid Therapy', page_or_location: 'Section 16.2' },
    },
    {
      step_id: 'PACK.ADA.DKAHHS.2024.TX.02',
      display_id: 'ADA-DKAHHS-TX2',
      action: 'DKA Step 2: Assess and replace potassium before insulin',
      normalized_claim: 'Check K+ immediately. If <3.3: replace K+ 20–40 mEq/hr, hold insulin. If 3.3–5.3: add 20–30 mEq K+/L. If >5.3: hold K+, recheck in 2 hours.',
      timing: 'Within 30 minutes, before insulin initiation',
      condition: 'DKA with serum potassium assessment',
      provenance: { section: 'Potassium Protocol', page_or_location: 'Table 16.1' },
    },
    {
      step_id: 'PACK.ADA.DKAHHS.2024.TX.03',
      display_id: 'ADA-DKAHHS-TX3',
      action: 'DKA Step 3: Initiate continuous IV insulin infusion',
      normalized_claim: 'Regular insulin drip 0.1–0.14 units/kg/hr (or 0.1 units/kg bolus + 0.1 units/kg/hr drip) once K+ ≥3.3.',
      timing: 'After confirming K+ ≥3.3 mEq/L',
      condition: 'DKA with adequate potassium',
      drug_details: { drug: 'Regular insulin', dose: '0.1–0.14 units/kg/hr', route: 'IV continuous infusion' },
      contraindications: ['Serum K+ <3.3 mEq/L'],
      provenance: { section: 'Insulin Therapy', page_or_location: 'Section 16.3' },
    },
    {
      step_id: 'PACK.ADA.DKAHHS.2024.TX.04',
      display_id: 'ADA-DKAHHS-TX4',
      action: 'DKA Step 4: Monitor anion gap and transition to subcutaneous insulin',
      normalized_claim: 'Check BMP every 2–4 hours. When AG ≤12, bicarb ≥15, pH >7.3, and patient eating: give subQ insulin and overlap IV drip 1–2 hours.',
      timing: 'Every 2–4 hours until resolution',
      condition: 'DKA with ongoing insulin infusion',
      escalation: 'If AG not closing, increase insulin rate by 50% and reassess fluid status',
      provenance: { section: 'DKA Monitoring and Transition', page_or_location: 'Section 16.5' },
    },
    {
      step_id: 'PACK.ADA.DKAHHS.2024.TX.05',
      display_id: 'ADA-DKAHHS-TX5',
      action: 'HHS: Prioritize fluid resuscitation, delay insulin',
      normalized_claim: 'HHS: give isotonic saline aggressively (may need 6–9 L in first 24 hours). Start insulin only after adequate volume resuscitation at 0.05 units/kg/hr.',
      timing: 'Fluid resuscitation begins immediately; insulin deferred until volume restored',
      condition: 'HHS confirmed by diagnostic criteria',
      drug_details: { drug: '0.9% Normal Saline', dose: '1–1.5 L first hour, then 250–500 mL/hr', route: 'IV' },
      provenance: { section: 'HHS Management', page_or_location: 'Section 16.6' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ADA.DKAHHS.2024.RF.01',
      display_id: 'ADA-DKAHHS-RF1',
      finding: 'Cerebral edema in pediatric DKA: headache, altered mental status, bradycardia, hypertension, pupillary changes during DKA treatment',
      implication: 'Mortality 20–25%. Most common cause of death in pediatric DKA. Risk increased by rapid fluid administration and rapid glucose correction.',
      action: 'Reduce IV fluid rate, elevate head of bed, administer mannitol 0.5–1 g/kg IV or hypertonic saline 3% 5 mL/kg. Emergent CT head. Neurosurgery consultation.',
      urgency: 'immediate',
      provenance: { section: 'Pediatric DKA Complications', page_or_location: 'Section 16.7' },
    },
    {
      flag_id: 'PACK.ADA.DKAHHS.2024.RF.02',
      display_id: 'ADA-DKAHHS-RF2',
      finding: 'Hypokalemia during insulin therapy: K+ <3.3 mEq/L with insulin infusion running',
      implication: 'Insulin drives K+ intracellularly. Life-threatening cardiac arrhythmias (peaked T waves → sine wave → VFib) may result.',
      action: 'Hold insulin infusion immediately. Replace K+ aggressively (20–40 mEq/hr IV with cardiac monitoring). Resume insulin only when K+ ≥3.3.',
      urgency: 'immediate',
      provenance: { section: 'Potassium Monitoring', page_or_location: 'Section 16.3' },
    },
    {
      flag_id: 'PACK.ADA.DKAHHS.2024.RF.03',
      display_id: 'ADA-DKAHHS-RF3',
      finding: 'Overcorrection of glucose without AG closure: glucose normalizes but anion gap remains elevated',
      implication: 'Stopping insulin when glucose normalizes (before AG closure) causes DKA rebound. Common management error.',
      action: 'Add dextrose (D5 or D10) to IV fluids and continue insulin drip at reduced rate (0.02–0.05 units/kg/hr) until anion gap closes.',
      urgency: 'urgent',
      provenance: { section: 'DKA Treatment Pitfalls', page_or_location: 'Section 16.5' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ADA.DKAHHS.2024.SEV.01',
      display_id: 'ADA-DKAHHS-SEV1',
      level: 'Mild DKA',
      criteria: [
        'Arterial pH 7.25–7.30',
        'Serum bicarbonate 15–18 mEq/L',
        'Blood glucose >250 mg/dL',
        'Anion gap >12 mEq/L',
        'Patient alert and oriented',
      ],
      management_implications:
        'May be managed with subcutaneous insulin analogs (lispro/aspart) in select patients. IV fluids still required. Hourly glucose monitoring. Consider ICU vs step-down based on institutional protocol.',
      provenance: { section: 'DKA Severity Classification', page_or_location: 'Table 16.1' },
    },
    {
      severity_id: 'PACK.ADA.DKAHHS.2024.SEV.02',
      display_id: 'ADA-DKAHHS-SEV2',
      level: 'Moderate DKA',
      criteria: [
        'Arterial pH 7.00–7.24',
        'Serum bicarbonate 10–14 mEq/L',
        'Blood glucose >250 mg/dL',
        'Anion gap >12 mEq/L',
        'Patient alert or drowsy',
      ],
      management_implications:
        'Requires ICU admission and continuous IV insulin infusion. Frequent (every 2 hour) electrolyte monitoring. Potassium replacement protocol. Assess for precipitating cause (infection, MI, medication non-adherence).',
      provenance: { section: 'DKA Severity Classification', page_or_location: 'Table 16.1' },
    },
    {
      severity_id: 'PACK.ADA.DKAHHS.2024.SEV.03',
      display_id: 'ADA-DKAHHS-SEV3',
      level: 'Severe DKA',
      criteria: [
        'Arterial pH <7.00',
        'Serum bicarbonate <10 mEq/L',
        'Blood glucose >250 mg/dL',
        'Anion gap >12 mEq/L',
        'Patient obtunded or comatose',
      ],
      management_implications:
        'ICU mandatory. IV insulin drip with hourly BMP. Consider bicarbonate if pH <6.9. Continuous cardiac monitoring for arrhythmias. High mortality risk — search aggressively for precipitant. May require intubation if obtunded.',
      provenance: { section: 'DKA Severity Classification', page_or_location: 'Table 16.1' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for DKA/HHS. Covers core diagnostic criteria, stepwise management, potassium protocols, and severity stratification for USMLE Step 2 CK question generation.',

  all_item_ids: [
    'PACK.ADA.DKAHHS.2024.REC.01', 'PACK.ADA.DKAHHS.2024.REC.02', 'PACK.ADA.DKAHHS.2024.REC.03',
    'PACK.ADA.DKAHHS.2024.REC.04', 'PACK.ADA.DKAHHS.2024.REC.05', 'PACK.ADA.DKAHHS.2024.REC.06',
    'PACK.ADA.DKAHHS.2024.DC.01', 'PACK.ADA.DKAHHS.2024.DC.02',
    'PACK.ADA.DKAHHS.2024.T.01', 'PACK.ADA.DKAHHS.2024.T.02', 'PACK.ADA.DKAHHS.2024.T.03',
    'PACK.ADA.DKAHHS.2024.T.04', 'PACK.ADA.DKAHHS.2024.T.05',
    'PACK.ADA.DKAHHS.2024.TX.01', 'PACK.ADA.DKAHHS.2024.TX.02', 'PACK.ADA.DKAHHS.2024.TX.03',
    'PACK.ADA.DKAHHS.2024.TX.04', 'PACK.ADA.DKAHHS.2024.TX.05',
    'PACK.ADA.DKAHHS.2024.RF.01', 'PACK.ADA.DKAHHS.2024.RF.02', 'PACK.ADA.DKAHHS.2024.RF.03',
    'PACK.ADA.DKAHHS.2024.SEV.01', 'PACK.ADA.DKAHHS.2024.SEV.02', 'PACK.ADA.DKAHHS.2024.SEV.03',
  ],
  all_display_ids: [
    'ADA-DKAHHS-R1', 'ADA-DKAHHS-R2', 'ADA-DKAHHS-R3', 'ADA-DKAHHS-R4', 'ADA-DKAHHS-R5', 'ADA-DKAHHS-R6',
    'ADA-DKAHHS-DC1', 'ADA-DKAHHS-DC2',
    'ADA-DKAHHS-T1', 'ADA-DKAHHS-T2', 'ADA-DKAHHS-T3', 'ADA-DKAHHS-T4', 'ADA-DKAHHS-T5',
    'ADA-DKAHHS-TX1', 'ADA-DKAHHS-TX2', 'ADA-DKAHHS-TX3', 'ADA-DKAHHS-TX4', 'ADA-DKAHHS-TX5',
    'ADA-DKAHHS-RF1', 'ADA-DKAHHS-RF2', 'ADA-DKAHHS-RF3',
    'ADA-DKAHHS-SEV1', 'ADA-DKAHHS-SEV2', 'ADA-DKAHHS-SEV3',
  ],
};
