// ─── DRAFT Source Pack: Achalasia ───
// Generated by DI/IC Accelerator on 2026-04-17
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (26 total):
//   DI.029.110, DI.029.111, DI.029.112, DI.029.113, DI.029.114, DI.029.115, DI.030.268, DI.030.560, DI.031.719, DI.102.046, DI.199.029, DI.213.006, DI.213.007, DI.213.008, DI.213.009, DI.231.019, EH.003.024, EH.003.025, EH.003.029, IC.050.020 ... and 6 more
//
// Evidence classification summary:
//   Recommendations: 17 items → pack
//   Diagnostic criteria: 2 items → pack
//   Treatment steps: 2 items → pack
//   Thresholds: 5 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_AGA_ACHAL_2020: SourcePack = {
  "source_pack_id": "PACK.AGA.ACHAL.2020",
  "source_name": "AGA Clinical Practice Guidelines on the Management of Achalasia",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2020,
  "guideline_body": "American Gastroenterological Association",
  "topic_tags": [
    "achalasia",
    "esophageal motility disorders",
    "dysphagia",
    "gastroenterology"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "treatment",
    "management",
    "complications"
  ],
  "excluded_decision_scopes": [
    "prevention",
    "screening"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.AGA.ACHAL.2020.REC.01",
      "display_id": "AGA-ACHAL-R1",
      "statement": "Esophageal manometry is the test of choice for diagnosing achalasia",
      "normalized_claim": "Manometry should be performed as the definitive test for achalasia diagnosis",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "After initial imaging suggests achalasia",
      "population": "Patients with suspected achalasia",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Manometry is the test of choice for achalasia"
      }
    },
    {
      "rec_id": "PACK.AGA.ACHAL.2020.REC.02",
      "display_id": "AGA-ACHAL-R2",
      "statement": "Use sequential diagnostic approach: barium swallow, then manometry, then endoscopy",
      "normalized_claim": "A systematic three-step diagnostic approach should be followed for achalasia evaluation",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Initial evaluation of suspected achalasia",
      "population": "Patients with dysphagia suggestive of achalasia",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "BME: 1st Barium swallow, 2nd Manometry, 3rd Endoscopy"
      }
    },
    {
      "rec_id": "PACK.AGA.ACHAL.2020.REC.03",
      "display_id": "AGA-ACHAL-R3",
      "statement": "Endoscopy should be performed to rule out pseudoachalasia and evaluate for malignancy",
      "normalized_claim": "EGD is recommended to exclude secondary causes of achalasia-like symptoms",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "After manometric confirmation of achalasia",
      "population": "Patients with confirmed achalasia",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "EGD (r/o pseudo-achalasia)"
      }
    },
    {
      "rec_id": "PACK.AGA.ACHAL.2020.REC.04",
      "display_id": "AGA-ACHAL-R4",
      "statement": "Laparoscopic Heller myotomy is preferred surgical treatment for achalasia",
      "normalized_claim": "Laparoscopic myotomy should be considered as definitive surgical therapy",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "For patients requiring definitive treatment",
      "population": "Surgical candidates with achalasia",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Laparoscopic myotomy and pneumatic balloon dilation"
      }
    },
    {
      "rec_id": "PACK.AGA.ACHAL.2020.REC.05",
      "display_id": "AGA-ACHAL-R5",
      "statement": "Pneumatic balloon dilation is an effective non-surgical treatment option",
      "normalized_claim": "Pneumatic dilation can be used as primary therapy for achalasia",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "For patients preferring non-surgical approach",
      "population": "Non-surgical candidates or patient preference",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Balloon dilation"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.AGA.ACHAL.2020.DC.01",
      "display_id": "AGA-ACHAL-DC1",
      "name": "Achalasia Manometric Criteria",
      "components": [
        "Incomplete LES relaxation",
        "Increased LES tone",
        "Aperistalsis of esophageal body"
      ],
      "threshold": "All three components must be present",
      "interpretation": "Diagnostic triad confirming achalasia",
      "normalized_claim": "Achalasia is diagnosed by manometric findings of incomplete LES relaxation, increased LES tone, and aperistalsis",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Triad: Incomplete LES relaxation, Increased LES tone, Aperistalsis"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.AGA.ACHAL.2020.T.01",
      "display_id": "AGA-ACHAL-T1",
      "parameter": "Dysphagia pattern",
      "value": "Both solids and liquids affected",
      "clinical_meaning": "Suggests motility disorder rather than mechanical obstruction",
      "normalized_claim": "Dysphagia to both solids and liquids indicates achalasia or other motility disorders",
      "direction": "present",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Dysphagia to solids and liquids --> Motility issue (Achalasia)"
      }
    },
    {
      "threshold_id": "PACK.AGA.ACHAL.2020.T.02",
      "display_id": "AGA-ACHAL-T2",
      "parameter": "Barium swallow finding",
      "value": "Bird's beak appearance",
      "clinical_meaning": "Characteristic radiographic sign of achalasia",
      "normalized_claim": "Bird's beak sign on barium swallow is pathognomonic for achalasia",
      "direction": "present",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "+Bird's beak sign"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.AGA.ACHAL.2020.TX.01",
      "display_id": "AGA-ACHAL-TX1",
      "action": "Medical management with calcium channel blockers",
      "normalized_claim": "CCBs can provide symptomatic relief in achalasia",
      "timing": "First-line medical therapy",
      "condition": "Mild symptoms or poor surgical candidate",
      "contraindications": [
        "Hypotension",
        "Heart failure"
      ],
      "drug_details": {
        "drug": "Dihydropyridine calcium channel blockers",
        "route": "oral"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Dihydropyridine CCB"
      }
    },
    {
      "step_id": "PACK.AGA.ACHAL.2020.TX.02",
      "display_id": "AGA-ACHAL-TX2",
      "action": "Botulinum toxin injection into LES",
      "normalized_claim": "Botox injection provides temporary relief of achalasia symptoms",
      "timing": "For temporary relief or poor surgical candidates",
      "condition": "Elderly or high-risk patients",
      "escalation": "May need repeated injections",
      "drug_details": {
        "drug": "Botulinum toxin",
        "route": "endoscopic injection"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Botulinum toxin injection"
      }
    },
    {
      "step_id": "PACK.AGA.ACHAL.2020.TX.03",
      "display_id": "AGA-ACHAL-TX3",
      "action": "Surgical myotomy with fundoplication",
      "normalized_claim": "Laparoscopic Heller myotomy with fundoplication is definitive treatment",
      "timing": "For definitive treatment",
      "condition": "Good surgical candidate",
      "escalation": "Consider for failed medical or pneumatic dilation therapy",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Heller myotomy (cut LES muscles)"
      }
    },
    {
      "step_id": "PACK.AGA.ACHAL.2020.TX.04",
      "display_id": "AGA-ACHAL-TX4",
      "action": "Add proton pump inhibitor post-procedure",
      "normalized_claim": "PPI therapy is recommended after achalasia treatment to prevent GERD",
      "timing": "Post-treatment maintenance",
      "condition": "After myotomy or dilation",
      "drug_details": {
        "drug": "Proton pump inhibitor",
        "route": "oral"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "surgical myotomy + PPI"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.AGA.ACHAL.2020.RF.01",
      "display_id": "AGA-ACHAL-RF1",
      "finding": "Esophageal perforation during pneumatic dilation",
      "implication": "Life-threatening complication requiring immediate intervention",
      "action": "Emergent surgical repair and broad-spectrum antibiotics",
      "urgency": "immediate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Esophageal perforation is cause for emergent surgical repair"
      }
    },
    {
      "flag_id": "PACK.AGA.ACHAL.2020.RF.02",
      "display_id": "AGA-ACHAL-RF2",
      "finding": "Development of esophageal mass in longstanding achalasia",
      "implication": "High risk for squamous cell carcinoma",
      "action": "Urgent endoscopic evaluation with biopsy",
      "urgency": "urgent",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "RF esophageal squamous cell carcinoma: Achalasia"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.AGA.ACHAL.2020.SEV.01",
      "display_id": "AGA-ACHAL-SEV1",
      "level": "Chagas-related achalasia",
      "criteria": [
        "History of exposure to Trypanosoma cruzi",
        "Associated cardiac involvement (dilated cardiomyopathy)",
        "Associated GI involvement (megacolon)",
        "Romana sign (periorbital edema)"
      ],
      "management_implications": "Requires antiparasitic treatment with nifurtimox or benznidazole in addition to achalasia management",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "RSM + achalasia + megacolon + S3 + periorbital edema (Romana sign) → Chagas disease"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-01-15",
  "normalizer_version": 1,
  "normalization_notes": "Generated from board review evidence (Divine Intervention, Inner Circle, Emma Holliday). Key areas needing verification: (1) Specific manometric criteria and thresholds, (2) Detailed treatment protocols and sequencing, (3) Complications and contraindications, (4) Integration with current AGA/ACG guidelines. Evidence strongly emphasizes Chagas disease association which may need regional context. All medical claims appear sound but require validation against current guidelines.",
  "all_item_ids": [
    "PACK.AGA.ACHAL.2020.REC.01",
    "PACK.AGA.ACHAL.2020.REC.02",
    "PACK.AGA.ACHAL.2020.REC.03",
    "PACK.AGA.ACHAL.2020.REC.04",
    "PACK.AGA.ACHAL.2020.REC.05",
    "PACK.AGA.ACHAL.2020.DC.01",
    "PACK.AGA.ACHAL.2020.T.01",
    "PACK.AGA.ACHAL.2020.T.02",
    "PACK.AGA.ACHAL.2020.TX.01",
    "PACK.AGA.ACHAL.2020.TX.02",
    "PACK.AGA.ACHAL.2020.TX.03",
    "PACK.AGA.ACHAL.2020.TX.04",
    "PACK.AGA.ACHAL.2020.RF.01",
    "PACK.AGA.ACHAL.2020.RF.02",
    "PACK.AGA.ACHAL.2020.SEV.01"
  ],
  "all_display_ids": [
    "AGA-ACHAL-R1",
    "AGA-ACHAL-R2",
    "AGA-ACHAL-R3",
    "AGA-ACHAL-R4",
    "AGA-ACHAL-R5",
    "AGA-ACHAL-DC1",
    "AGA-ACHAL-T1",
    "AGA-ACHAL-T2",
    "AGA-ACHAL-TX1",
    "AGA-ACHAL-TX2",
    "AGA-ACHAL-TX3",
    "AGA-ACHAL-TX4",
    "AGA-ACHAL-RF1",
    "AGA-ACHAL-RF2",
    "AGA-ACHAL-SEV1"
  ]
};
