import type { SourcePack } from './types';

export const PACK_AHA_IE_2015: SourcePack = {
  source_pack_id: 'PACK.AHA.IE.2015',
  source_name: 'AHA 2015 Infective Endocarditis in Adults: Diagnosis, Antimicrobial Therapy, and Management of Complications',
  source_registry_id: 'REG.AHA.IE',
  canonical_url: 'https://doi.org/10.1161/CIR.0000000000000296',
  publication_year: 2015,
  guideline_body: 'AHA',

  topic_tags: ['Infective Endocarditis', 'Duke Criteria', 'Valvular Infection', 'Cardiology', 'Infectious Disease'],
  allowed_decision_scopes: [
    'IE diagnosis using modified Duke criteria',
    'empiric antibiotic selection for native valve IE',
    'empiric antibiotic selection for prosthetic valve IE',
    'surgical indications in IE',
    'blood culture-negative endocarditis workup',
    'IE prophylaxis indications',
  ],
  excluded_decision_scopes: [
    'right-sided IE in IV drug users (detailed management)',
    'pediatric endocarditis',
    'device-related endocarditis (detailed CIED extraction)',
    'fungal endocarditis detailed regimens',
  ],

  recommendations: [
    {
      rec_id: 'PACK.AHA.IE.2015.REC.01',
      display_id: 'AHA-IE-R1',
      statement: 'At least 2 sets of blood cultures from separate venipuncture sites should be obtained before initiating antimicrobial therapy in patients with suspected IE.',
      normalized_claim: 'Obtain >=2 blood culture sets from separate sites before starting antibiotics in suspected IE.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Diagnosis', page_or_location: 'Section 3.1' },
    },
    {
      rec_id: 'PACK.AHA.IE.2015.REC.02',
      display_id: 'AHA-IE-R2',
      statement: 'Transthoracic echocardiography (TTE) is recommended as the initial imaging modality in suspected IE. Transesophageal echocardiography (TEE) is recommended when TTE is nondiagnostic, when prosthetic valve IE is suspected, or when intracardiac complications are suspected.',
      normalized_claim: 'TTE first for suspected IE; TEE if TTE nondiagnostic, prosthetic valve, or suspected complications.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Imaging', page_or_location: 'Section 3.2' },
    },
    {
      rec_id: 'PACK.AHA.IE.2015.REC.03',
      display_id: 'AHA-IE-R3',
      statement: 'Empiric therapy for native valve IE should cover staphylococci, streptococci, and enterococci. Nafcillin/oxacillin plus gentamicin is recommended pending culture results.',
      normalized_claim: 'Native valve IE empiric therapy: nafcillin/oxacillin + gentamicin pending cultures.',
      strength: 'strong',
      evidence_quality: 'moderate',
      context: 'Vancomycin substituted for nafcillin if MRSA risk factors present',
      provenance: { section: 'Antimicrobial Therapy', page_or_location: 'Section 4.1' },
    },
    {
      rec_id: 'PACK.AHA.IE.2015.REC.04',
      display_id: 'AHA-IE-R4',
      statement: 'Empiric therapy for prosthetic valve IE should include vancomycin plus gentamicin plus rifampin to cover MRSA and coagulase-negative staphylococci.',
      normalized_claim: 'Prosthetic valve IE empiric therapy: vancomycin + gentamicin + rifampin.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Antimicrobial Therapy', page_or_location: 'Section 4.2' },
    },
    {
      rec_id: 'PACK.AHA.IE.2015.REC.05',
      display_id: 'AHA-IE-R5',
      statement: 'Antibiotic prophylaxis before dental procedures is recommended only for patients at highest risk: prosthetic valves, prior IE, certain congenital heart diseases, and cardiac transplant recipients with valvulopathy.',
      normalized_claim: 'IE prophylaxis limited to highest-risk patients: prosthetic valves, prior IE, unrepaired cyanotic CHD, cardiac transplant with valvulopathy.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Prevention', page_or_location: 'Section 8.1' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.AHA.IE.2015.DC.01',
      display_id: 'AHA-IE-DC1',
      name: 'Modified Duke Criteria for IE',
      components: [
        'Major criterion 1: Blood cultures — typical IE organism from 2 separate cultures (viridans strep, S. bovis, HACEK, S. aureus, enterococci without primary focus) OR persistently positive cultures',
        'Major criterion 2: Endocardial involvement — positive echocardiogram (vegetation, abscess, new prosthetic dehiscence) OR new valvular regurgitation',
        'Minor criterion 1: Predisposing heart condition or IV drug use',
        'Minor criterion 2: Fever >=38°C (100.4°F)',
        'Minor criterion 3: Vascular phenomena (septic emboli, mycotic aneurysm, Janeway lesions, conjunctival hemorrhage)',
        'Minor criterion 4: Immunologic phenomena (Osler nodes, Roth spots, glomerulonephritis, positive rheumatoid factor)',
        'Minor criterion 5: Microbiologic evidence not meeting major criterion',
      ],
      threshold: 'Definite IE: 2 major, or 1 major + 3 minor, or 5 minor criteria. Possible IE: 1 major + 1 minor, or 3 minor criteria.',
      interpretation: 'Modified Duke criteria classify IE as definite, possible, or rejected based on clinical, microbiologic, and echocardiographic findings.',
      normalized_claim: 'Definite IE requires 2 major criteria OR 1 major + 3 minor OR 5 minor. Possible IE: 1 major + 1 minor OR 3 minor.',
      provenance: { section: 'Diagnosis', page_or_location: 'Table 3' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.AHA.IE.2015.T.01',
      display_id: 'AHA-IE-T1',
      parameter: 'Vegetation size for embolic risk',
      value: '10',
      unit: 'mm',
      clinical_meaning: 'Vegetations >10mm, especially on the anterior mitral leaflet, are associated with increased embolic risk and may be an indication for surgery.',
      normalized_claim: 'Vegetation >10mm on anterior mitral leaflet increases embolic risk and is a surgical consideration.',
      direction: 'above',
      provenance: { section: 'Surgical Indications', page_or_location: 'Section 6.3' },
    },
    {
      threshold_id: 'PACK.AHA.IE.2015.T.02',
      display_id: 'AHA-IE-T2',
      parameter: 'Fever duration for IE workup',
      value: '38',
      unit: '°C',
      clinical_meaning: 'Fever >=38°C is a minor Duke criterion. Persistent fever despite appropriate antibiotics suggests perivalvular abscess or need for surgical intervention.',
      normalized_claim: 'Fever >=38°C is a minor Duke criterion; persistent fever on antibiotics suggests abscess or surgical need.',
      direction: 'above',
      provenance: { section: 'Diagnosis', page_or_location: 'Table 3' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.AHA.IE.2015.TX.01',
      display_id: 'AHA-IE-TX1',
      action: 'Obtain blood cultures and initiate empiric therapy for native valve IE',
      normalized_claim: 'Native valve IE: obtain >=2 BC sets, then start nafcillin/oxacillin + gentamicin (or vancomycin + gentamicin if MRSA risk).',
      timing: 'Immediately after blood cultures obtained',
      condition: 'Native valve, suspected acute IE',
      drug_details: { drug: 'Nafcillin or Oxacillin', dose: '2g IV q4h', route: 'IV', duration: '6 weeks' },
      contraindications: ['Penicillin allergy (use vancomycin)'],
      provenance: { section: 'Antimicrobial Therapy', page_or_location: 'Section 4.1' },
    },
    {
      step_id: 'PACK.AHA.IE.2015.TX.02',
      display_id: 'AHA-IE-TX2',
      action: 'Initiate empiric therapy for prosthetic valve IE',
      normalized_claim: 'Prosthetic valve IE: vancomycin + gentamicin + rifampin; rifampin added 3-5 days after initial therapy once bacteremia clears.',
      timing: 'Immediately after blood cultures obtained',
      condition: 'Prosthetic valve, suspected IE',
      drug_details: { drug: 'Vancomycin', dose: '15-20mg/kg IV q8-12h', route: 'IV', duration: '>=6 weeks' },
      provenance: { section: 'Antimicrobial Therapy', page_or_location: 'Section 4.2' },
    },
    {
      step_id: 'PACK.AHA.IE.2015.TX.03',
      display_id: 'AHA-IE-TX3',
      action: 'Surgical intervention for IE with heart failure',
      normalized_claim: 'Surgery recommended for IE causing moderate-severe HF due to valve dysfunction, especially acute aortic or mitral regurgitation.',
      timing: 'Urgent (within days)',
      condition: 'IE complicated by heart failure from valvular dysfunction',
      provenance: { section: 'Surgical Indications', page_or_location: 'Section 6.1' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.AHA.IE.2015.RF.01',
      display_id: 'AHA-IE-RF1',
      finding: 'Perivalvular abscess: persistent fever and bacteremia despite appropriate antibiotics, new conduction abnormalities (especially PR prolongation or new heart block)',
      implication: 'Perivalvular extension with abscess formation. High mortality without surgery.',
      action: 'Urgent TEE to evaluate for abscess. Surgical consultation for valve replacement and abscess debridement.',
      urgency: 'urgent',
      provenance: { section: 'Complications', page_or_location: 'Section 5.2' },
    },
    {
      flag_id: 'PACK.AHA.IE.2015.RF.02',
      display_id: 'AHA-IE-RF2',
      finding: 'Embolic stroke or systemic embolization in a patient with known or suspected IE',
      implication: 'Embolic events occur in 20-50% of IE. Risk highest in first 2 weeks and with large (>10mm) mobile vegetations.',
      action: 'Brain imaging (CT/MRI), evaluate for mycotic aneurysm. Early surgery may reduce recurrent embolization if vegetation >10mm with prior embolic event.',
      urgency: 'urgent',
      provenance: { section: 'Complications', page_or_location: 'Section 5.3' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.AHA.IE.2015.SEV.01',
      display_id: 'AHA-IE-SEV1',
      level: 'Complicated IE requiring surgery',
      criteria: [
        'Heart failure due to valvular dysfunction (acute AR or MR)',
        'Uncontrolled infection: persistent bacteremia >5-7 days on appropriate therapy, perivalvular abscess, or fistula',
        'Embolic risk: recurrent emboli or large vegetation >10mm despite appropriate antibiotics',
        'Fungal or highly resistant organism IE',
      ],
      management_implications:
        'Early surgical intervention (valve repair or replacement) recommended. Mortality significantly reduced with timely surgery in these indications compared to medical therapy alone.',
      provenance: { section: 'Surgical Indications', page_or_location: 'Section 6' },
    },
    {
      severity_id: 'PACK.AHA.IE.2015.SEV.02',
      display_id: 'AHA-IE-SEV2',
      level: 'Uncomplicated IE (medical management)',
      criteria: [
        'No heart failure from valve dysfunction',
        'No perivalvular extension or abscess',
        'No embolic events after initiation of therapy',
        'Susceptible organism with documented bacteremia clearance',
        'No prosthetic valve involvement',
      ],
      management_implications:
        'Complete antibiotic course (4-6 weeks IV). Serial blood cultures to document clearance. Repeat echocardiography at completion of therapy. Outpatient parenteral antibiotic therapy (OPAT) may be considered in stable patients.',
      provenance: { section: 'Medical Management', page_or_location: 'Section 4' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for infective endocarditis. Covers modified Duke criteria, empiric therapy (native vs prosthetic), and surgical indications.',

  all_item_ids: [
    'PACK.AHA.IE.2015.REC.01', 'PACK.AHA.IE.2015.REC.02', 'PACK.AHA.IE.2015.REC.03',
    'PACK.AHA.IE.2015.REC.04', 'PACK.AHA.IE.2015.REC.05',
    'PACK.AHA.IE.2015.DC.01',
    'PACK.AHA.IE.2015.T.01', 'PACK.AHA.IE.2015.T.02',
    'PACK.AHA.IE.2015.TX.01', 'PACK.AHA.IE.2015.TX.02', 'PACK.AHA.IE.2015.TX.03',
    'PACK.AHA.IE.2015.RF.01', 'PACK.AHA.IE.2015.RF.02',
    'PACK.AHA.IE.2015.SEV.01', 'PACK.AHA.IE.2015.SEV.02',
  ],
  all_display_ids: [
    'AHA-IE-R1', 'AHA-IE-R2', 'AHA-IE-R3', 'AHA-IE-R4', 'AHA-IE-R5',
    'AHA-IE-DC1',
    'AHA-IE-T1', 'AHA-IE-T2',
    'AHA-IE-TX1', 'AHA-IE-TX2', 'AHA-IE-TX3',
    'AHA-IE-RF1', 'AHA-IE-RF2',
    'AHA-IE-SEV1', 'AHA-IE-SEV2',
  ],
};
