// ─── DRAFT Source Pack: Aortic Aneurysm ───
// Generated by DI/IC Accelerator on 2026-04-17
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (44 total):
//   DI.138.100, DI.138.106, DI.163.083, DI.163.084, DI.163.085, DI.163.086, DI.163.087, DI.163.088, DI.163.089, DI.163.090, DI.163.091, DI.163.092, DI.163.093, DI.163.094, DI.163.095, DI.163.096, DI.163.097, DI.163.098, DI.163.099, DI.167.071 ... and 24 more
//
// Evidence classification summary:
//   Recommendations: 30 items → pack
//   Diagnostic criteria: 2 items → pack
//   Treatment steps: 1 items → pack
//   Thresholds: 5 items → pack
//   Red flags: 2 items → pack
//   Severity definitions: 3 items → pack
//   Skipped: 1 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_AHA_AAA_2022: SourcePack = {
  "source_pack_id": "PACK.AHA.AAA.2022",
  "source_name": "AHA/ACC Guideline for the Diagnosis and Management of Aortic Disease",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2022,
  "guideline_body": "American Heart Association/American College of Cardiology",
  "topic_tags": [
    "aortic aneurysm",
    "abdominal aortic aneurysm",
    "thoracic aortic aneurysm",
    "vascular surgery",
    "cardiovascular disease"
  ],
  "allowed_decision_scopes": [
    "screening",
    "diagnosis",
    "surgical_management",
    "medical_management",
    "complications",
    "surveillance"
  ],
  "excluded_decision_scopes": [
    "pediatric_management",
    "pregnancy_related"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.AHA.AAA.2022.REC.01",
      "display_id": "AHA-AAA-R1",
      "statement": "One-time abdominal ultrasound screening for AAA in men aged 65-75 years with smoking history or family history of AAA",
      "normalized_claim": "Men aged 65-75 with smoking history or family history of AAA should receive one-time abdominal ultrasound screening",
      "strength": "strong",
      "evidence_quality": "high",
      "population": "Men aged 65-75 years with smoking history or family history of AAA",
      "provenance": {
        "section": "Screening recommendations",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "1-time Abdominal Ultrasound for men 65-75yo with smoking history or family history"
      }
    },
    {
      "rec_id": "PACK.AHA.AAA.2022.REC.02",
      "display_id": "AHA-AAA-R2",
      "statement": "AAA >5.5 cm or growing >0.5 cm in 6 months should undergo repair",
      "normalized_claim": "AAA repair is indicated for aneurysms >5.5 cm diameter or growth >0.5 cm in 6 months",
      "strength": "strong",
      "evidence_quality": "high",
      "provenance": {
        "section": "Surgical management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "AAA > 5.5 cm or > 0.5 cm growth in 6 months → repair ASAP"
      }
    },
    {
      "rec_id": "PACK.AHA.AAA.2022.REC.03",
      "display_id": "AHA-AAA-R3",
      "statement": "Hemodynamically unstable patients with known AAA should undergo emergency repair without imaging",
      "normalized_claim": "Emergency AAA repair is indicated for hemodynamically unstable patients with known AAA",
      "strength": "strong",
      "evidence_quality": "low",
      "context": "Emergency setting — expert consensus",
      "provenance": {
        "section": "Emergency management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "HD Unstable with known AAA: Emergency repair"
      }
    },
    {
      "rec_id": "PACK.AHA.AAA.2022.REC.04",
      "display_id": "AHA-AAA-R4",
      "statement": "Smoking cessation should be recommended for all patients with aortic aneurysm",
      "normalized_claim": "Smoking cessation is recommended for all patients with aortic aneurysm",
      "strength": "strong",
      "evidence_quality": "high",
      "provenance": {
        "section": "Medical management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Management: 1. Smoking cessation"
      }
    },
    {
      "rec_id": "PACK.AHA.AAA.2022.REC.05",
      "display_id": "AHA-AAA-R5",
      "statement": "Avoid fluoroquinolones in patients with aortic aneurysm due to risk of rupture",
      "normalized_claim": "Fluoroquinolones should be avoided in patients with aortic aneurysm",
      "strength": "strong",
      "evidence_quality": "moderate",
      "provenance": {
        "section": "Medical management contraindications",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Avoid Fluoroquinolones (risk of increased collagen degradation — aortic aneurysm rupture)"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.AHA.AAA.2022.DC.01",
      "display_id": "AHA-AAA-DC1",
      "name": "Abdominal Aortic Aneurysm Definition",
      "components": [
        "Abdominal aorta diameter >3 cm"
      ],
      "interpretation": "Enlargement of abdominal aorta to >3 cm diameter defines AAA",
      "normalized_claim": "AAA is defined as enlargement of abdominal aorta diameter to >3 cm",
      "provenance": {
        "section": "Definitions",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Enlargement of abdominal aorta diameter to >3cm"
      }
    },
    {
      "criterion_id": "PACK.AHA.AAA.2022.DC.02",
      "display_id": "AHA-AAA-DC2",
      "name": "Thoracic Aortic Aneurysm Imaging Criteria",
      "components": [
        "CXR: Widened mediastinum",
        "CXR: Enlarged aortic knob",
        "CXR: Tracheal deviation",
        "CT with contrast for confirmation"
      ],
      "interpretation": "CXR findings suggest TAA but CT with contrast required for definitive diagnosis",
      "normalized_claim": "Thoracic aortic aneurysm diagnosis requires CT with contrast for confirmation after suggestive CXR findings",
      "provenance": {
        "section": "Diagnostic imaging",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "CXR: Widened mediastinum, enlarged aortic knob, tracheal deviation; CT with contrast: Confirm diagnosis"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.AHA.AAA.2022.T.01",
      "display_id": "AHA-AAA-T1",
      "parameter": "AAA diameter surgical threshold",
      "value": "5.5",
      "unit": "cm",
      "clinical_meaning": "Threshold for surgical repair recommendation",
      "normalized_claim": "AAA diameter >5.5 cm indicates need for surgical repair",
      "direction": "above",
      "provenance": {
        "section": "Surgical indications",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": ">5.5 cm → surgery"
      }
    },
    {
      "threshold_id": "PACK.AHA.AAA.2022.T.02",
      "display_id": "AHA-AAA-T2",
      "parameter": "AAA growth rate surgical threshold",
      "value": "0.5",
      "unit": "cm per 6 months",
      "clinical_meaning": "Growth rate indicating need for surgical repair",
      "normalized_claim": "AAA growth >0.5 cm in 6 months indicates need for surgical repair",
      "direction": "above",
      "provenance": {
        "section": "Surgical indications",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "growing >0.5 cm/6mo → surgery"
      }
    },
    {
      "threshold_id": "PACK.AHA.AAA.2022.T.03",
      "display_id": "AHA-AAA-T3",
      "parameter": "AAA definition threshold",
      "value": "3",
      "unit": "cm",
      "clinical_meaning": "Minimum diameter to define abdominal aortic aneurysm",
      "normalized_claim": "Abdominal aorta diameter >3 cm defines AAA",
      "direction": "above",
      "provenance": {
        "section": "Definitions",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Enlargement of abdominal aorta diameter to >3cm"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.AHA.AAA.2022.TX.01",
      "display_id": "AHA-AAA-TX1",
      "action": "Smoking cessation counseling and support",
      "normalized_claim": "Smoking cessation should be implemented for all AAA patients",
      "timing": "At diagnosis and ongoing",
      "provenance": {
        "section": "Medical management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Management: 1. Smoking cessation"
      }
    },
    {
      "step_id": "PACK.AHA.AAA.2022.TX.02",
      "display_id": "AHA-AAA-TX2",
      "action": "Initiate beta-blocker therapy",
      "normalized_claim": "Beta-blocker therapy with labetalol should be considered for AAA patients",
      "drug_details": {
        "drug": "Labetalol",
        "dose": "Per standard dosing",
        "route": "Oral"
      },
      "provenance": {
        "section": "Medical management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Labetalol: Nonselective a-1 and B-1 blocker"
      }
    },
    {
      "step_id": "PACK.AHA.AAA.2022.TX.03",
      "display_id": "AHA-AAA-TX3",
      "action": "Emergency surgical repair for unstable patients",
      "normalized_claim": "Hemodynamically unstable patients with AAA require immediate surgical repair",
      "timing": "Immediate",
      "condition": "Hemodynamic instability with known or suspected AAA rupture",
      "provenance": {
        "section": "Emergency management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "HD Unstable with known AAA: Emergency repair"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.AHA.AAA.2022.RF.01",
      "display_id": "AHA-AAA-RF1",
      "finding": "Hemodynamic instability with known AAA",
      "implication": "Possible AAA rupture",
      "action": "Immediate surgical repair without delay for imaging",
      "urgency": "immediate",
      "provenance": {
        "section": "Emergency presentations",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "HD Unstable with known AAA: Emergency repair"
      }
    },
    {
      "flag_id": "PACK.AHA.AAA.2022.RF.02",
      "display_id": "AHA-AAA-RF2",
      "finding": "Severe abdominal or back pain with pulsatile mass in smoker",
      "implication": "Ruptured AAA",
      "action": "Emergency evaluation and likely surgical repair",
      "urgency": "immediate",
      "provenance": {
        "section": "Emergency presentations",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Smoker + severe mid-abdominal/back pain + profound hypotension + pulsatile abdominal mass → ruptured AAA"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.AHA.AAA.2022.SEV.01",
      "display_id": "AHA-AAA-SEV1",
      "level": "Ruptured AAA",
      "criteria": [
        "Severe abdominal or back pain",
        "Profound hypotension",
        "Pulsatile abdominal mass",
        "History of smoking"
      ],
      "management_implications": "Requires immediate emergency surgical repair",
      "provenance": {
        "section": "Emergency presentations",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Smoker + severe mid-abdominal/back pain + profound hypotension + pulsatile abdominal mass → ruptured AAA"
      }
    },
    {
      "severity_id": "PACK.AHA.AAA.2022.SEV.02",
      "display_id": "AHA-AAA-SEV2",
      "level": "Large AAA (>5.5 cm)",
      "criteria": [
        "Diameter >5.5 cm",
        "OR growth >0.5 cm in 6 months",
        "OR symptomatic"
      ],
      "management_implications": "Requires surgical repair",
      "provenance": {
        "section": "Surgical indications",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": ">5.5 cm, growing >0.5 cm/6mo or symptomatic → surgery"
      }
    },
    {
      "severity_id": "PACK.AHA.AAA.2022.SEV.03",
      "display_id": "AHA-AAA-SEV3",
      "level": "Small-moderate AAA (3-5.4 cm)",
      "criteria": [
        "Diameter 3-5.4 cm",
        "Growth <0.5 cm in 6 months",
        "Asymptomatic"
      ],
      "management_implications": "Surveillance with serial imaging and medical management",
      "provenance": {
        "section": "Surveillance protocols",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "3-4 cm → repeat US in 2 years; 4-5 cm → repeat US in 1 year"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-12-19",
  "normalizer_version": 1,
  "normalization_notes": "Generated from board review materials (Divine Intervention + Inner Circle + Emma Holliday). Key areas needing verification: (1) Specific guideline recommendations vs. board review summaries, (2) Exact thresholds and surveillance intervals, (3) Drug dosing and contraindications, (4) Emergency management protocols. Some recommendations synthesized from clinical pearls may not reflect exact guideline language. Surveillance intervals (2 years for 3-4cm, 1 year for 4-5cm, 6 months for 5-5.5cm) included from source material but need verification.",
  "all_item_ids": [
    "PACK.AHA.AAA.2022.REC.01",
    "PACK.AHA.AAA.2022.REC.02",
    "PACK.AHA.AAA.2022.REC.03",
    "PACK.AHA.AAA.2022.REC.04",
    "PACK.AHA.AAA.2022.REC.05",
    "PACK.AHA.AAA.2022.DC.01",
    "PACK.AHA.AAA.2022.DC.02",
    "PACK.AHA.AAA.2022.T.01",
    "PACK.AHA.AAA.2022.T.02",
    "PACK.AHA.AAA.2022.T.03",
    "PACK.AHA.AAA.2022.TX.01",
    "PACK.AHA.AAA.2022.TX.02",
    "PACK.AHA.AAA.2022.TX.03",
    "PACK.AHA.AAA.2022.RF.01",
    "PACK.AHA.AAA.2022.RF.02",
    "PACK.AHA.AAA.2022.SEV.01",
    "PACK.AHA.AAA.2022.SEV.02",
    "PACK.AHA.AAA.2022.SEV.03"
  ],
  "all_display_ids": [
    "AHA-AAA-R1",
    "AHA-AAA-R2",
    "AHA-AAA-R3",
    "AHA-AAA-R4",
    "AHA-AAA-R5",
    "AHA-AAA-DC1",
    "AHA-AAA-DC2",
    "AHA-AAA-T1",
    "AHA-AAA-T2",
    "AHA-AAA-T3",
    "AHA-AAA-TX1",
    "AHA-AAA-TX2",
    "AHA-AAA-TX3",
    "AHA-AAA-RF1",
    "AHA-AAA-RF2",
    "AHA-AAA-SEV1",
    "AHA-AAA-SEV2",
    "AHA-AAA-SEV3"
  ]
};
