import type { SourcePack } from './types';

export const PACK_AHA_TIA_2021: SourcePack = {
  source_pack_id: 'PACK.AHA.TIA.2021',
  source_name: '2021 AHA/ASA Guideline for the Prevention of Stroke in Patients with Stroke and Transient Ischemic Attack',
  canonical_url: 'https://doi.org/10.1161/STR.0000000000000375',
  publication_year: 2021,
  guideline_body: 'AHA/ASA',

  topic_tags: ['TIA', 'Minor Stroke', 'ABCD2 Score', 'Dual Antiplatelet', 'Secondary Stroke Prevention', 'Carotid Stenosis', 'Neurology'],
  allowed_decision_scopes: [
    'TIA diagnosis and workup',
    'ABCD2 risk stratification',
    'dual antiplatelet therapy for TIA/minor stroke',
    'carotid stenosis evaluation',
    'carotid endarterectomy timing',
    'anticoagulation for cardioembolic TIA',
    'secondary stroke prevention',
    'TIA disposition (admit vs discharge)',
    'statin therapy post-TIA',
  ],
  excluded_decision_scopes: [
    'acute ischemic stroke thrombolysis',
    'mechanical thrombectomy',
    'hemorrhagic stroke',
    'primary stroke prevention',
    'chronic atrial fibrillation management beyond anticoagulation initiation',
    'intracranial stenting',
  ],

  recommendations: [
    {
      rec_id: 'PACK.AHA.TIA.2021.REC.01',
      display_id: 'AHA-TIA-R1',
      statement: 'Emergent neuroimaging is recommended for all patients presenting with TIA. MRI with diffusion-weighted imaging (DWI) is preferred over CT to detect acute infarction and confirm tissue-based TIA diagnosis.',
      normalized_claim: 'All TIA patients need emergent neuroimaging. MRI-DWI preferred over CT to detect infarction and confirm tissue-based diagnosis.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'Up to 50% of clinically diagnosed TIAs show DWI lesions on MRI, reclassifying them as minor strokes.',
      provenance: { section: 'Diagnostic Evaluation', page_or_location: 'Section 3.1' },
    },
    {
      rec_id: 'PACK.AHA.TIA.2021.REC.02',
      display_id: 'AHA-TIA-R2',
      statement: 'Dual antiplatelet therapy (aspirin 162-325 mg loading + clopidogrel 300 mg loading, followed by aspirin 81 mg + clopidogrel 75 mg daily) for 21 days is recommended for high-risk TIA (ABCD2 >=4) or minor ischemic stroke (NIHSS <=3) presenting within 24 hours of onset.',
      normalized_claim: 'DAPT (ASA + clopidogrel) for 21 days for high-risk TIA (ABCD2 >=4) or minor stroke (NIHSS <=3) within 24h of onset. Then monotherapy.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'Based on CHANCE and POINT trials. Reduces recurrent stroke by ~25% vs aspirin alone. Bleeding risk increases after 21 days.',
      provenance: { section: 'Antiplatelet Therapy', page_or_location: 'Section 5.1' },
    },
    {
      rec_id: 'PACK.AHA.TIA.2021.REC.03',
      display_id: 'AHA-TIA-R3',
      statement: 'Carotid imaging (duplex ultrasound, CTA, or MRA) should be performed in all patients with anterior circulation TIA or minor stroke to evaluate for carotid stenosis.',
      normalized_claim: 'All anterior circulation TIA/minor stroke patients require carotid imaging (duplex US, CTA, or MRA) for stenosis evaluation.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Vascular Imaging', page_or_location: 'Section 3.3' },
    },
    {
      rec_id: 'PACK.AHA.TIA.2021.REC.04',
      display_id: 'AHA-TIA-R4',
      statement: 'High-intensity statin therapy (atorvastatin 40-80 mg or rosuvastatin 20-40 mg) is recommended for all patients with TIA or ischemic stroke of atherosclerotic origin.',
      normalized_claim: 'High-intensity statin for all atherosclerotic TIA/stroke regardless of LDL. Target LDL <70 mg/dL.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Lipid Management', page_or_location: 'Section 6.2' },
    },
    {
      rec_id: 'PACK.AHA.TIA.2021.REC.05',
      display_id: 'AHA-TIA-R5',
      statement: 'For TIA or ischemic stroke associated with atrial fibrillation, anticoagulation with a DOAC (apixaban, rivaroxaban, edoxaban, or dabigatran) is recommended over warfarin for most patients. Antiplatelet therapy alone is insufficient for cardioembolic prevention.',
      normalized_claim: 'AFib-related TIA/stroke requires DOAC anticoagulation (not aspirin alone). DOACs preferred over warfarin for most patients.',
      strength: 'strong',
      evidence_quality: 'high',
      population: 'Nonvalvular atrial fibrillation (excludes mechanical valves, moderate-severe mitral stenosis)',
      provenance: { section: 'Cardioembolic Stroke Prevention', page_or_location: 'Section 5.3' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.AHA.TIA.2021.DC.01',
      display_id: 'AHA-TIA-DC1',
      name: 'TIA Definition (Tissue-Based)',
      components: [
        'Transient episode of neurological dysfunction',
        'Caused by focal brain, spinal cord, or retinal ischemia',
        'Symptoms typically resolve within 1 hour (but may last up to 24 hours)',
        'No evidence of acute infarction on neuroimaging (DWI-MRI)',
      ],
      interpretation: 'Modern tissue-based definition requires negative DWI-MRI. If DWI shows infarction despite resolved symptoms, the diagnosis is minor ischemic stroke, not TIA. This distinction affects risk stratification and management intensity.',
      normalized_claim: 'TIA = transient focal neuro deficit without infarction on imaging. DWI+ reclassifies as minor stroke.',
      provenance: { section: 'Definition', page_or_location: 'Section 2.1' },
    },
    {
      criterion_id: 'PACK.AHA.TIA.2021.DC.02',
      display_id: 'AHA-TIA-DC2',
      name: 'ABCD2 Score',
      components: [
        'Age >=60 years (1 point)',
        'Blood pressure >=140/90 at presentation (1 point)',
        'Clinical features: unilateral weakness (2 points) or speech disturbance without weakness (1 point)',
        'Duration >=60 min (2 points) or 10-59 min (1 point)',
        'Diabetes mellitus (1 point)',
      ],
      threshold: 'Score range 0-7',
      interpretation: 'ABCD2 >=4 = high risk of early recurrent stroke (8% at 2 days). Score 0-3 = low risk (1% at 2 days). High-risk patients should be admitted for expedited workup. Score guides DAPT eligibility.',
      normalized_claim: 'ABCD2 score (0-7): >=4 is high-risk (admit, DAPT). 0-3 is lower risk (may discharge with rapid outpatient workup).',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 4.1' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.AHA.TIA.2021.T.01',
      display_id: 'AHA-TIA-T1',
      parameter: 'ABCD2 score for high-risk classification',
      value: '4',
      clinical_meaning: 'ABCD2 >=4 identifies high-risk TIA patients who benefit from hospital admission, expedited workup, and DAPT. 2-day stroke risk is approximately 8% vs 1% for low-risk.',
      normalized_claim: 'ABCD2 >=4 = high-risk TIA. Admit for workup and start DAPT.',
      direction: 'above',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 4.1' },
    },
    {
      threshold_id: 'PACK.AHA.TIA.2021.T.02',
      display_id: 'AHA-TIA-T2',
      parameter: 'Carotid stenosis for CEA/CAS',
      value: '70',
      unit: '%',
      clinical_meaning: 'Symptomatic carotid stenosis >=70% (NASCET criteria) is an indication for carotid endarterectomy (CEA) or carotid artery stenting (CAS). CEA preferred for most patients. Surgery within 2 weeks of index event provides greatest benefit.',
      normalized_claim: 'Symptomatic carotid stenosis >=70% requires CEA (preferred) or CAS. Surgery within 2 weeks of TIA for maximum benefit.',
      direction: 'above',
      provenance: { section: 'Carotid Revascularization', page_or_location: 'Section 7.1' },
    },
    {
      threshold_id: 'PACK.AHA.TIA.2021.T.03',
      display_id: 'AHA-TIA-T3',
      parameter: 'DAPT duration post-TIA/minor stroke',
      value: '21',
      unit: 'days',
      clinical_meaning: 'DAPT (aspirin + clopidogrel) is given for 21 days after high-risk TIA or minor stroke. After 21 days, transition to antiplatelet monotherapy (aspirin or clopidogrel). Extended DAPT increases bleeding without additional stroke reduction benefit.',
      normalized_claim: 'DAPT for exactly 21 days after high-risk TIA/minor stroke, then antiplatelet monotherapy. Longer DAPT increases bleeding.',
      direction: 'below',
      provenance: { section: 'Antiplatelet Therapy', page_or_location: 'Section 5.1' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.AHA.TIA.2021.TX.01',
      display_id: 'AHA-TIA-TX1',
      action: 'High-risk TIA: Admit and initiate DAPT with expedited workup',
      normalized_claim: 'High-risk TIA (ABCD2 >=4): admit, load ASA 325 mg + clopidogrel 300 mg, then ASA 81 mg + clopidogrel 75 mg daily x 21 days. MRI-DWI, CTA/carotid duplex, telemetry, echocardiogram, lipid panel, HbA1c.',
      timing: 'Within 24 hours of presentation',
      condition: 'ABCD2 >=4 or DWI-positive minor stroke or crescendo TIA',
      drug_details: { drug: 'Aspirin + Clopidogrel', dose: 'ASA 325 mg + clopidogrel 300 mg load; then ASA 81 mg + clopidogrel 75 mg daily', route: 'PO', duration: '21 days DAPT, then monotherapy' },
      contraindications: ['Active major bleeding', 'Known intracranial hemorrhage', 'Severe thrombocytopenia', 'Planned anticoagulation for AFib'],
      provenance: { section: 'Acute Management', page_or_location: 'Section 4.2' },
    },
    {
      step_id: 'PACK.AHA.TIA.2021.TX.02',
      display_id: 'AHA-TIA-TX2',
      action: 'CEA for symptomatic carotid stenosis 70-99%',
      normalized_claim: 'CEA within 2 weeks of TIA/minor stroke for symptomatic carotid stenosis 70-99% (NASCET). Maximum benefit when performed early. CAS is alternative if high surgical risk.',
      timing: 'Within 2 weeks of index TIA or minor stroke',
      condition: 'Ipsilateral carotid stenosis 70-99% by NASCET criteria with anterior circulation symptoms',
      escalation: 'CAS if high surgical risk (hostile neck, radiation, prior CEA, contralateral occlusion)',
      provenance: { section: 'Carotid Revascularization', page_or_location: 'Section 7.1' },
    },
    {
      step_id: 'PACK.AHA.TIA.2021.TX.03',
      display_id: 'AHA-TIA-TX3',
      action: 'Anticoagulation for cardioembolic TIA (atrial fibrillation)',
      normalized_claim: 'AFib-related TIA: start DOAC (apixaban 5 mg BID, rivaroxaban 20 mg daily, or dabigatran 150 mg BID). Do not use DAPT alone for cardioembolic prevention. Warfarin (INR 2-3) if DOAC contraindicated.',
      timing: 'Initiate within days of TIA (timing depends on infarct size if minor stroke)',
      condition: 'Atrial fibrillation detected on ECG, telemetry, or prolonged cardiac monitoring',
      drug_details: { drug: 'Apixaban (preferred DOAC)', dose: '5 mg BID (2.5 mg BID if >=2 of: age >=80, weight <=60 kg, Cr >=1.5)', route: 'PO' },
      contraindications: ['Mechanical heart valve', 'Moderate-severe mitral stenosis', 'Active major bleeding', 'CrCl <15 mL/min for most DOACs'],
      provenance: { section: 'Cardioembolic Prevention', page_or_location: 'Section 5.3' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.AHA.TIA.2021.RF.01',
      display_id: 'AHA-TIA-RF1',
      finding: 'Crescendo TIA: Multiple TIA events occurring with increasing frequency over hours to days, suggesting unstable vascular lesion',
      implication: 'Imminent risk of completed stroke. Suggests unstable carotid plaque, intracranial stenosis, or cardioembolism with repeated events.',
      action: 'Emergent hospital admission. Urgent CTA/MRA of head and neck. Start DAPT immediately. Expedite carotid imaging and cardiac workup. Consider heparin drip if recurrent despite DAPT.',
      urgency: 'immediate',
      provenance: { section: 'High-Risk Features', page_or_location: 'Section 4.3' },
    },
    {
      flag_id: 'PACK.AHA.TIA.2021.RF.02',
      display_id: 'AHA-TIA-RF2',
      finding: 'ABCD2 score >=4 with motor or speech deficit lasting >60 minutes',
      implication: 'Two-day stroke risk approaches 8-12%. These patients have the highest benefit from admission and DAPT.',
      action: 'Admit to stroke unit or monitored bed. Initiate DAPT. Complete stroke workup within 24 hours (MRI-DWI, CTA, telemetry, echocardiogram). Do not discharge without etiology assessment.',
      urgency: 'urgent',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 4.1' },
    },
    {
      flag_id: 'PACK.AHA.TIA.2021.RF.03',
      display_id: 'AHA-TIA-RF3',
      finding: 'Carotid stenosis >=70% ipsilateral to TIA symptoms',
      implication: 'Annual stroke risk 10-15% without intervention. Surgical benefit is greatest when CEA performed within 2 weeks of symptom onset.',
      action: 'Urgent vascular surgery or interventional consultation. CEA within 2 weeks. Optimize medical therapy (DAPT, high-intensity statin, BP control) while awaiting surgery.',
      urgency: 'urgent',
      provenance: { section: 'Carotid Revascularization', page_or_location: 'Section 7.1' },
    },
    {
      flag_id: 'PACK.AHA.TIA.2021.RF.04',
      display_id: 'AHA-TIA-RF4',
      finding: 'New atrial fibrillation discovered on telemetry during TIA workup',
      implication: 'Identifies cardioembolic mechanism requiring anticoagulation rather than antiplatelet monotherapy. Recurrence rate high without appropriate treatment.',
      action: 'Initiate DOAC anticoagulation. Discontinue DAPT (switch to anticoagulation alone for stroke prevention). Cardiology consultation for rate/rhythm control. Assess CHA2DS2-VASc score.',
      urgency: 'soon',
      provenance: { section: 'Cardiac Evaluation', page_or_location: 'Section 3.4' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.AHA.TIA.2021.SEV.01',
      display_id: 'AHA-TIA-SEV1',
      level: 'Low-risk TIA (ABCD2 0-3)',
      criteria: [
        'ABCD2 score 0-3',
        'Symptoms resolved completely',
        'Normal neurological examination',
        'No DWI lesion on MRI (if obtained)',
        'No large vessel stenosis on imaging',
      ],
      management_implications:
        'May be managed with rapid outpatient workup if reliable follow-up within 24-48 hours is ensured. Aspirin monotherapy (unless DAPT criteria met). Complete stroke workup as outpatient: MRI-DWI, carotid imaging, echocardiography, prolonged cardiac monitoring. Start high-intensity statin. Two-day stroke risk approximately 1%.',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 4.1' },
    },
    {
      severity_id: 'PACK.AHA.TIA.2021.SEV.02',
      display_id: 'AHA-TIA-SEV2',
      level: 'High-risk TIA (ABCD2 >=4)',
      criteria: [
        'ABCD2 score >=4',
        'OR DWI-positive on MRI (reclassified as minor stroke)',
        'OR crescendo TIA pattern',
        'OR known ipsilateral carotid stenosis >=50%',
        'OR known atrial fibrillation',
      ],
      management_implications:
        'Hospital admission for monitored observation and expedited workup. Initiate DAPT (aspirin + clopidogrel) for 21 days. MRI-DWI within 24 hours. CTA head/neck. Continuous telemetry for 24-72 hours. Echocardiography. Start high-intensity statin. Urgent vascular surgery referral if carotid stenosis >=70%. Two-day stroke risk approximately 8%.',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 4.1' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 lightweight pack for TIA/minor stroke. Covers ABCD2 stratification, DAPT decision, carotid management, and cardioembolic workup for question generation.',

  all_item_ids: [
    'PACK.AHA.TIA.2021.REC.01', 'PACK.AHA.TIA.2021.REC.02', 'PACK.AHA.TIA.2021.REC.03',
    'PACK.AHA.TIA.2021.REC.04', 'PACK.AHA.TIA.2021.REC.05',
    'PACK.AHA.TIA.2021.DC.01', 'PACK.AHA.TIA.2021.DC.02',
    'PACK.AHA.TIA.2021.T.01', 'PACK.AHA.TIA.2021.T.02', 'PACK.AHA.TIA.2021.T.03',
    'PACK.AHA.TIA.2021.TX.01', 'PACK.AHA.TIA.2021.TX.02', 'PACK.AHA.TIA.2021.TX.03',
    'PACK.AHA.TIA.2021.RF.01', 'PACK.AHA.TIA.2021.RF.02', 'PACK.AHA.TIA.2021.RF.03',
    'PACK.AHA.TIA.2021.RF.04',
    'PACK.AHA.TIA.2021.SEV.01', 'PACK.AHA.TIA.2021.SEV.02',
  ],
  all_display_ids: [
    'AHA-TIA-R1', 'AHA-TIA-R2', 'AHA-TIA-R3', 'AHA-TIA-R4', 'AHA-TIA-R5',
    'AHA-TIA-DC1', 'AHA-TIA-DC2',
    'AHA-TIA-T1', 'AHA-TIA-T2', 'AHA-TIA-T3',
    'AHA-TIA-TX1', 'AHA-TIA-TX2', 'AHA-TIA-TX3',
    'AHA-TIA-RF1', 'AHA-TIA-RF2', 'AHA-TIA-RF3', 'AHA-TIA-RF4',
    'AHA-TIA-SEV1', 'AHA-TIA-SEV2',
  ],
};
