// ─── DRAFT Source Pack: Subarachnoid Hemorrhage ───
// Generated by DI/IC Accelerator on 2026-04-16
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (25 total):
//   DI.031.066, DI.031.067, DI.031.068, DI.031.069, DI.031.070, DI.031.071, DI.031.072, DI.041.044, DI.045.082, DI.045.083, DI.045.084, DI.045.085, DI.045.086, DI.045.087, DI.045.088, DI.045.089, DI.125.004, DI.145.048, DI.145.049, DI.145.050 ... and 5 more
//
// Evidence classification summary:
//   Recommendations: 19 items → pack
//   Diagnostic criteria: 1 items → pack
//   Treatment steps: 1 items → pack
//   Thresholds: 2 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 2 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_AHA_SAH_2019: SourcePack = {
  "source_pack_id": "PACK.AHA.SAH.2019",
  "source_name": "Guidelines for the Management of Patients With Aneurysmal Subarachnoid Hemorrhage",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2019,
  "guideline_body": "American Heart Association/American Stroke Association",
  "topic_tags": [
    "subarachnoid hemorrhage",
    "aneurysm",
    "stroke",
    "neurocritical care",
    "vasospasm"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "acute management",
    "vasospasm prevention",
    "blood pressure management",
    "imaging workup"
  ],
  "excluded_decision_scopes": [
    "surgical intervention",
    "endovascular procedures",
    "long-term rehabilitation",
    "screening for aneurysms"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.AHA.SAH.2019.REC.01",
      "display_id": "AHA-SAH-R1",
      "statement": "Non-contrast head CT should be the initial imaging study for suspected subarachnoid hemorrhage",
      "normalized_claim": "Non-contrast CT is first-line imaging for SAH diagnosis",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Acute presentation with suspected SAH",
      "population": "Patients with acute severe headache",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Non-con head CT"
      }
    },
    {
      "rec_id": "PACK.AHA.SAH.2019.REC.02",
      "display_id": "AHA-SAH-R2",
      "statement": "If CT is negative for SAH, lumbar puncture should be performed to look for xanthochromia",
      "normalized_claim": "LP with xanthochromia testing is indicated when CT is negative but SAH is suspected",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Negative CT with continued SAH suspicion",
      "population": "Patients with suspected SAH and negative CT",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If CT negative → LP (looking for xanthochromia)"
      }
    },
    {
      "rec_id": "PACK.AHA.SAH.2019.REC.03",
      "display_id": "AHA-SAH-R3",
      "statement": "Nimodipine should be administered to prevent vasospasm-related ischemic complications",
      "normalized_claim": "Nimodipine prevents post-SAH vasospasm and ischemic stroke",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Confirmed SAH diagnosis",
      "population": "All patients with confirmed SAH",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Prevention of post-SAH vasospasm? nimodipine"
      }
    },
    {
      "rec_id": "PACK.AHA.SAH.2019.REC.04",
      "display_id": "AHA-SAH-R4",
      "statement": "Blood pressure should be lowered to 140/90 mmHg in SAH patients",
      "normalized_claim": "Target BP is 140/90 mmHg in acute SAH management",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "context": "Acute SAH management",
      "population": "SAH patients with elevated blood pressure",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Lower pt's BP to 140/90"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.AHA.SAH.2019.DC.01",
      "display_id": "AHA-SAH-DC1",
      "name": "Subarachnoid Hemorrhage Diagnostic Workup",
      "components": [
        "Non-contrast head CT as initial study",
        "Lumbar puncture if CT negative",
        "Xanthochromia in CSF",
        "RBC count in thousands (4000-5000) in CSF"
      ],
      "threshold": "RBC count 4000-5000/μL in CSF",
      "interpretation": "Confirms SAH diagnosis when imaging and CSF findings are consistent",
      "normalized_claim": "SAH diagnosis requires CT evidence of blood or CSF findings of xanthochromia and high RBC count",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Dx for SAH? Non-con head CT"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.AHA.SAH.2019.T.01",
      "display_id": "AHA-SAH-T1",
      "parameter": "CSF RBC count",
      "value": "4000-5000",
      "unit": "cells/μL",
      "clinical_meaning": "Indicates subarachnoid hemorrhage",
      "normalized_claim": "CSF RBC count in thousands suggests SAH",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Subarachnoid hemorrhage: RBCs in thousands (4000-5000)"
      }
    },
    {
      "threshold_id": "PACK.AHA.SAH.2019.T.02",
      "display_id": "AHA-SAH-T2",
      "parameter": "Blood pressure target",
      "value": "140/90",
      "unit": "mmHg",
      "clinical_meaning": "Target blood pressure in acute SAH management",
      "normalized_claim": "BP should be maintained at or below 140/90 mmHg in SAH",
      "direction": "below",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Lower pt's BP to 140/90"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.AHA.SAH.2019.TX.01",
      "display_id": "AHA-SAH-TX1",
      "action": "Administer nimodipine for vasospasm prevention",
      "normalized_claim": "Nimodipine prevents vasospasm-related ischemic complications in SAH",
      "timing": "As soon as SAH is confirmed",
      "condition": "Confirmed subarachnoid hemorrhage",
      "drug_details": {
        "drug": "nimodipine",
        "dose": "TODO: Verify dose from guideline",
        "route": "TODO: Verify route from guideline",
        "duration": "TODO: Verify duration from guideline"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Give nimodipine to prevent superimposed ischemic stroke"
      }
    },
    {
      "step_id": "PACK.AHA.SAH.2019.TX.02",
      "display_id": "AHA-SAH-TX2",
      "action": "Control blood pressure to target 140/90 mmHg",
      "normalized_claim": "BP control to 140/90 mmHg is indicated in acute SAH",
      "timing": "Acute phase",
      "condition": "Elevated blood pressure in SAH patient",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Tx: Lower pt's BP to 140/90"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.AHA.SAH.2019.RF.01",
      "display_id": "AHA-SAH-RF1",
      "finding": "Worst headache of patient's life with sudden onset",
      "implication": "High suspicion for subarachnoid hemorrhage",
      "action": "Immediate non-contrast head CT",
      "urgency": "immediate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Worst HA of pt's life, often mimics meningitis but is sudden onset"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.AHA.SAH.2019.SEV.01",
      "display_id": "AHA-SAH-SEV1",
      "level": "Acute SAH with vasospasm risk",
      "criteria": [
        "Confirmed subarachnoid hemorrhage",
        "Risk of delayed cerebral ischemia from vasospasm"
      ],
      "management_implications": "Requires nimodipine prophylaxis and neurological monitoring",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Nimodipine to reduce ischemic stroke from vasospasm (MC cause of M&M)"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-12-19",
  "normalizer_version": 1,
  "normalization_notes": "Generated from board review materials (Divine Intervention, Inner Circle, Emma Holliday). Key items extracted include: diagnostic workup with CT/LP, nimodipine for vasospasm prevention, BP management, and classic presentation patterns. Notable associations mentioned include ADPKD, MVP, and anterior communicating artery aneurysms. Requires verification against actual AHA/ASA guidelines for dosing details, specific protocols, and evidence grading. Some clinical pearls may need expansion into formal recommendations.",
  "all_item_ids": [
    "PACK.AHA.SAH.2019.REC.01",
    "PACK.AHA.SAH.2019.REC.02",
    "PACK.AHA.SAH.2019.REC.03",
    "PACK.AHA.SAH.2019.REC.04",
    "PACK.AHA.SAH.2019.DC.01",
    "PACK.AHA.SAH.2019.T.01",
    "PACK.AHA.SAH.2019.T.02",
    "PACK.AHA.SAH.2019.TX.01",
    "PACK.AHA.SAH.2019.TX.02",
    "PACK.AHA.SAH.2019.RF.01",
    "PACK.AHA.SAH.2019.SEV.01"
  ],
  "all_display_ids": [
    "AHA-SAH-R1",
    "AHA-SAH-R2",
    "AHA-SAH-R3",
    "AHA-SAH-R4",
    "AHA-SAH-DC1",
    "AHA-SAH-T1",
    "AHA-SAH-T2",
    "AHA-SAH-TX1",
    "AHA-SAH-TX2",
    "AHA-SAH-RF1",
    "AHA-SAH-SEV1"
  ]
};
