import type { SourcePack } from './types';

export const PACK_AHA_ACS_2023: SourcePack = {
  source_pack_id: 'PACK.AHA.ACS.2023',
  source_name: 'AHA/ACC 2023 Guideline for Management of Patients with Acute Coronary Syndromes',
  source_registry_id: 'REG.AHA.ACS',
  canonical_url: 'https://doi.org/10.1161/CIR.0000000000001123',
  publication_year: 2023,
  guideline_body: 'AHA/ACC',

  topic_tags: ['ACS', 'STEMI', 'NSTEMI', 'Unstable Angina', 'Cardiology'],
  allowed_decision_scopes: [
    'STEMI reperfusion strategy',
    'antiplatelet therapy selection',
    'anticoagulation during PCI',
    'NSTEMI risk stratification',
    'post-ACS medical therapy',
    'beta-blocker initiation',
    'statin therapy',
    'ACEi/ARB for LV dysfunction',
    'cardiogenic shock management',
    'RV infarction recognition',
  ],
  excluded_decision_scopes: [
    'chronic stable angina management',
    'primary prevention statin therapy',
    'heart failure management beyond acute phase',
    'cardiac rehabilitation specifics',
    'implantable defibrillator criteria',
  ],

  recommendations: [
    {
      rec_id: 'PACK.AHA.ACS.2023.REC.01',
      display_id: 'AHA-ACS-R1',
      statement: 'Patients with STEMI should undergo emergent reperfusion therapy. Primary PCI is preferred over fibrinolysis when available within 120 minutes of first medical contact.',
      normalized_claim: 'STEMI requires emergent reperfusion; PCI preferred if door-to-balloon achievable within 90 minutes.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'Applies to all STEMI presentations within 12 hours of symptom onset',
      provenance: { section: 'Reperfusion Therapy', page_or_location: 'Section 5.1' },
    },
    {
      rec_id: 'PACK.AHA.ACS.2023.REC.02',
      display_id: 'AHA-ACS-R2',
      statement: 'Dual antiplatelet therapy (aspirin plus a P2Y12 inhibitor) is recommended for all ACS patients.',
      normalized_claim: 'All ACS patients require DAPT: aspirin + P2Y12 inhibitor (ticagrelor or prasugrel preferred over clopidogrel for PCI-treated STEMI).',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Antiplatelet Therapy', page_or_location: 'Section 6.1' },
    },
    {
      rec_id: 'PACK.AHA.ACS.2023.REC.03',
      display_id: 'AHA-ACS-R3',
      statement: 'Parenteral anticoagulation is recommended for all ACS patients during the acute phase, with unfractionated heparin preferred during PCI.',
      normalized_claim: 'Anticoagulation required during PCI; UFH preferred intra-procedurally.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Anticoagulation', page_or_location: 'Section 6.2' },
    },
    {
      rec_id: 'PACK.AHA.ACS.2023.REC.04',
      display_id: 'AHA-ACS-R4',
      statement: 'NSTEMI patients should be risk-stratified using validated tools (TIMI, HEART, GRACE). High-risk patients benefit from early invasive strategy within 24 hours.',
      normalized_claim: 'NSTEMI risk stratification guides timing: high-risk patients need invasive strategy within 24 hours.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'NSTEMI Management', page_or_location: 'Section 4.3' },
    },
    {
      rec_id: 'PACK.AHA.ACS.2023.REC.05',
      display_id: 'AHA-ACS-R5',
      statement: 'Oral beta-blocker therapy should be initiated within the first 24 hours in patients without contraindications (cardiogenic shock, decompensated HF, heart block, active bronchospasm).',
      normalized_claim: 'Beta-blocker within 24h unless contraindicated by shock, HF, heart block, or bronchospasm.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Secondary Prevention', page_or_location: 'Section 7.2' },
    },
    {
      rec_id: 'PACK.AHA.ACS.2023.REC.06',
      display_id: 'AHA-ACS-R6',
      statement: 'High-intensity statin therapy (atorvastatin 80mg or rosuvastatin 40mg) should be initiated in all ACS patients regardless of baseline LDL.',
      normalized_claim: 'High-intensity statin for all ACS patients regardless of LDL level.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Lipid Management', page_or_location: 'Section 7.3' },
    },
    {
      rec_id: 'PACK.AHA.ACS.2023.REC.07',
      display_id: 'AHA-ACS-R7',
      statement: 'ACE inhibitor (or ARB) therapy should be started within 24 hours in patients with LVEF <=40%, heart failure, hypertension, or diabetes.',
      normalized_claim: 'ACEi/ARB within 24h when LVEF <=40%, HF, HTN, or DM present.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'RAAS Inhibition', page_or_location: 'Section 7.4' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.AHA.ACS.2023.DC.01',
      display_id: 'AHA-ACS-DC1',
      name: 'STEMI ECG Criteria',
      components: [
        'New ST elevation at the J-point in 2 contiguous leads',
        '>=1mm in all leads except V2-V3',
        'V2-V3: >=2mm in men >=40yo, >=2.5mm in men <40yo, >=1.5mm in women',
      ],
      threshold: '>=1mm ST elevation in 2 contiguous leads',
      interpretation: 'Meets STEMI criteria requiring emergent reperfusion.',
      normalized_claim: 'STEMI defined by new ST elevation >=1mm in 2 contiguous leads (higher thresholds for V2-V3).',
      provenance: { section: 'Diagnosis', page_or_location: 'Section 3.1' },
    },
    {
      criterion_id: 'PACK.AHA.ACS.2023.DC.02',
      display_id: 'AHA-ACS-DC2',
      name: 'NSTEMI Criteria',
      components: [
        'Troponin elevation above 99th percentile URL with rise/fall pattern',
        'Clinical context consistent with myocardial ischemia',
        'Absence of ST elevation meeting STEMI criteria',
      ],
      interpretation: 'NSTEMI = troponin elevation + ischemic symptoms without STEMI-pattern ECG.',
      normalized_claim: 'NSTEMI requires troponin above 99th percentile with ischemic symptoms and no STEMI ECG pattern.',
      provenance: { section: 'Diagnosis', page_or_location: 'Section 3.2' },
    },
    {
      criterion_id: 'PACK.AHA.ACS.2023.DC.03',
      display_id: 'AHA-ACS-DC3',
      name: 'Type 1 vs Type 2 MI',
      components: [
        'Type 1: Spontaneous MI due to atherosclerotic plaque rupture/erosion with thrombus',
        'Type 2: MI due to supply-demand mismatch (e.g., tachycardia, anemia, hypotension) without plaque disruption',
      ],
      interpretation: 'Type 1 MI warrants antiplatelet/anticoagulation and invasive evaluation. Type 2 MI requires treatment of underlying cause.',
      normalized_claim: 'Type 1 MI = plaque event requiring ACS treatment. Type 2 MI = supply-demand mismatch requiring treatment of cause.',
      provenance: { section: 'Classification', page_or_location: 'Section 2.1' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.AHA.ACS.2023.T.01',
      display_id: 'AHA-ACS-T1',
      parameter: 'High-sensitivity troponin I',
      value: '99th percentile URL',
      clinical_meaning: 'Values above 99th percentile upper reference limit with rise/fall pattern indicate myocardial injury.',
      normalized_claim: 'Troponin above 99th percentile URL with dynamic change indicates myocardial injury.',
      direction: 'above',
      provenance: { section: 'Biomarkers', page_or_location: 'Section 3.3' },
    },
    {
      threshold_id: 'PACK.AHA.ACS.2023.T.02',
      display_id: 'AHA-ACS-T2',
      parameter: 'Door-to-balloon time',
      value: '90',
      unit: 'minutes',
      clinical_meaning: 'Target for STEMI patients undergoing primary PCI. System goal <=90 minutes from first medical contact.',
      normalized_claim: 'Door-to-balloon time must be <=90 minutes for STEMI PCI.',
      direction: 'below',
      provenance: { section: 'Reperfusion', page_or_location: 'Section 5.1' },
    },
    {
      threshold_id: 'PACK.AHA.ACS.2023.T.03',
      display_id: 'AHA-ACS-T3',
      parameter: 'Door-to-needle time',
      value: '30',
      unit: 'minutes',
      clinical_meaning: 'Target for fibrinolytic therapy when PCI is not available within 120 minutes.',
      normalized_claim: 'Fibrinolysis within 30 minutes of arrival when PCI unavailable within 120 minutes.',
      direction: 'below',
      provenance: { section: 'Fibrinolysis', page_or_location: 'Section 5.2' },
    },
    {
      threshold_id: 'PACK.AHA.ACS.2023.T.04',
      display_id: 'AHA-ACS-T4',
      parameter: 'LVEF for ACEi indication',
      value: '40',
      unit: '%',
      clinical_meaning: 'LVEF <=40% is an indication for ACEi/ARB initiation post-ACS.',
      normalized_claim: 'LVEF <=40% triggers ACEi/ARB therapy post-ACS.',
      direction: 'below',
      provenance: { section: 'RAAS Inhibition', page_or_location: 'Section 7.4' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.AHA.ACS.2023.TX.01',
      display_id: 'AHA-ACS-TX1',
      action: 'Immediate ACS management',
      normalized_claim: 'All ACS patients receive aspirin 325mg chewed, sublingual NTG (unless RV infarct/hypotension), supplemental O2 if SpO2 <90%.',
      timing: 'Within minutes of presentation',
      drug_details: { drug: 'Aspirin', dose: '325mg', route: 'PO chewed' },
      contraindications: ['Aspirin allergy', 'Active GI hemorrhage'],
      provenance: { section: 'Initial Management', page_or_location: 'Section 4.1' },
    },
    {
      step_id: 'PACK.AHA.ACS.2023.TX.02',
      display_id: 'AHA-ACS-TX2',
      action: 'STEMI: Activate cardiac catheterization lab',
      normalized_claim: 'STEMI patients require immediate cath lab activation for primary PCI. Do not delay for serial troponins.',
      timing: 'Immediately upon STEMI diagnosis',
      condition: 'ST elevation meeting STEMI criteria',
      contraindications: ['Patient refusal', 'DNR/comfort care'],
      provenance: { section: 'STEMI Management', page_or_location: 'Section 5.1' },
    },
    {
      step_id: 'PACK.AHA.ACS.2023.TX.03',
      display_id: 'AHA-ACS-TX3',
      action: 'NSTEMI high-risk: Early invasive strategy',
      normalized_claim: 'High-risk NSTEMI (TIMI >=3, positive troponin, dynamic ST changes) warrants invasive strategy within 24 hours.',
      timing: 'Within 24 hours of presentation',
      condition: 'High-risk features on TIMI/HEART/GRACE scoring',
      provenance: { section: 'NSTEMI Invasive Strategy', page_or_location: 'Section 4.3' },
    },
    {
      step_id: 'PACK.AHA.ACS.2023.TX.04',
      display_id: 'AHA-ACS-TX4',
      action: 'Discharge medical therapy',
      normalized_claim: 'Post-ACS discharge: DAPT (12 months minimum), high-intensity statin, beta-blocker, ACEi/ARB if indicated.',
      timing: 'At hospital discharge',
      provenance: { section: 'Discharge Planning', page_or_location: 'Section 7.1' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.AHA.ACS.2023.RF.01',
      display_id: 'AHA-ACS-RF1',
      finding: 'Cardiogenic shock: SBP <90mmHg with signs of end-organ hypoperfusion and pulmonary congestion',
      implication: 'Mortality exceeds 40% without intervention. Requires emergent revascularization.',
      action: 'Emergent PCI, vasopressors (norepinephrine first-line), consider mechanical support (IABP, Impella).',
      urgency: 'immediate',
      provenance: { section: 'Cardiogenic Shock', page_or_location: 'Section 8.1' },
    },
    {
      flag_id: 'PACK.AHA.ACS.2023.RF.02',
      display_id: 'AHA-ACS-RF2',
      finding: 'RV infarction: Hypotension + clear lungs + elevated JVP in inferior STEMI',
      implication: 'Preload-dependent state. Nitrates and diuretics are contraindicated.',
      action: 'IV fluid bolus, avoid nitrates/diuretics, emergent PCI for RCA occlusion.',
      urgency: 'immediate',
      provenance: { section: 'RV Infarction', page_or_location: 'Section 8.2' },
    },
    {
      flag_id: 'PACK.AHA.ACS.2023.RF.03',
      display_id: 'AHA-ACS-RF3',
      finding: 'Mechanical complication: New systolic murmur + hemodynamic collapse post-MI',
      implication: 'Suggests papillary muscle rupture, VSD, or free wall rupture. Surgical emergency.',
      action: 'Emergent echocardiography, surgical consultation, hemodynamic support.',
      urgency: 'immediate',
      provenance: { section: 'Mechanical Complications', page_or_location: 'Section 8.3' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.AHA.ACS.2023.SEV.01',
      display_id: 'AHA-ACS-SEV1',
      level: 'STEMI with cardiogenic shock',
      criteria: [
        'ST elevation meeting STEMI criteria',
        'SBP <90 mmHg for ≥30 minutes or vasopressor requirement',
        'Signs of end-organ hypoperfusion (altered mental status, cool extremities, oliguria)',
        'Pulmonary congestion on exam or imaging',
      ],
      management_implications:
        'Emergent PCI regardless of time delay. Vasopressors (norepinephrine first-line). Consider mechanical circulatory support (IABP, Impella). Mortality >40% without intervention.',
      provenance: { section: 'Cardiogenic Shock', page_or_location: 'Section 8.1' },
    },
    {
      severity_id: 'PACK.AHA.ACS.2023.SEV.02',
      display_id: 'AHA-ACS-SEV2',
      level: 'NSTEMI high-risk',
      criteria: [
        'TIMI score ≥3 or GRACE score >140',
        'Positive troponin with dynamic changes',
        'Recurrent ischemic symptoms despite medical therapy',
        'Dynamic ST-segment or T-wave changes',
        'Hemodynamic instability or sustained VT',
      ],
      management_implications:
        'Early invasive strategy within 24 hours. Full anticoagulation + DAPT. ICU-level monitoring. Do not discharge without catheterization.',
      provenance: { section: 'NSTEMI Risk Stratification', page_or_location: 'Section 4.3' },
    },
    {
      severity_id: 'PACK.AHA.ACS.2023.SEV.03',
      display_id: 'AHA-ACS-SEV3',
      level: 'NSTEMI low-risk',
      criteria: [
        'TIMI score 0-2 and GRACE score <109',
        'Negative or minimally elevated troponin',
        'No recurrent chest pain',
        'No hemodynamic compromise',
        'No dynamic ECG changes',
      ],
      management_implications:
        'Ischemia-guided strategy acceptable. Stress testing before or shortly after discharge. Medical therapy with DAPT and statin. Outpatient cardiology follow-up.',
      provenance: { section: 'NSTEMI Risk Stratification', page_or_location: 'Section 4.3' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-14',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 lightweight pack for ACS. Covers core STEMI/NSTEMI decision points for question generation. Evidence grounding per P4 (Jia et al. 2026).',

  all_item_ids: [
    'PACK.AHA.ACS.2023.REC.01', 'PACK.AHA.ACS.2023.REC.02', 'PACK.AHA.ACS.2023.REC.03',
    'PACK.AHA.ACS.2023.REC.04', 'PACK.AHA.ACS.2023.REC.05', 'PACK.AHA.ACS.2023.REC.06',
    'PACK.AHA.ACS.2023.REC.07', 'PACK.AHA.ACS.2023.DC.01', 'PACK.AHA.ACS.2023.DC.02',
    'PACK.AHA.ACS.2023.DC.03', 'PACK.AHA.ACS.2023.T.01', 'PACK.AHA.ACS.2023.T.02',
    'PACK.AHA.ACS.2023.T.03', 'PACK.AHA.ACS.2023.T.04', 'PACK.AHA.ACS.2023.TX.01',
    'PACK.AHA.ACS.2023.TX.02', 'PACK.AHA.ACS.2023.TX.03', 'PACK.AHA.ACS.2023.TX.04',
    'PACK.AHA.ACS.2023.RF.01', 'PACK.AHA.ACS.2023.RF.02', 'PACK.AHA.ACS.2023.RF.03',
    'PACK.AHA.ACS.2023.SEV.01', 'PACK.AHA.ACS.2023.SEV.02', 'PACK.AHA.ACS.2023.SEV.03',
  ],
  all_display_ids: [
    'AHA-ACS-R1', 'AHA-ACS-R2', 'AHA-ACS-R3', 'AHA-ACS-R4', 'AHA-ACS-R5', 'AHA-ACS-R6', 'AHA-ACS-R7',
    'AHA-ACS-DC1', 'AHA-ACS-DC2', 'AHA-ACS-DC3',
    'AHA-ACS-T1', 'AHA-ACS-T2', 'AHA-ACS-T3', 'AHA-ACS-T4',
    'AHA-ACS-TX1', 'AHA-ACS-TX2', 'AHA-ACS-TX3', 'AHA-ACS-TX4',
    'AHA-ACS-RF1', 'AHA-ACS-RF2', 'AHA-ACS-RF3',
    'AHA-ACS-SEV1', 'AHA-ACS-SEV2', 'AHA-ACS-SEV3',
  ],
};
