import type { SourcePack } from './types';

export const PACK_AHA_STROKE_2019: SourcePack = {
  source_pack_id: 'PACK.AHA.STROKE.2019',
  source_name: '2019 AHA/ASA Guidelines for Early Management of Patients with Acute Ischemic Stroke',
  canonical_url: 'https://doi.org/10.1161/STR.0000000000000211',
  publication_year: 2019,
  guideline_body: 'AHA/ASA',

  topic_tags: ['Acute Ischemic Stroke', 'IV Alteplase', 'Mechanical Thrombectomy', 'Permissive Hypertension', 'NIHSS', 'Neurology'],
  allowed_decision_scopes: [
    'IV alteplase eligibility',
    'mechanical thrombectomy eligibility',
    'blood pressure management in acute stroke',
    'antiplatelet therapy post-stroke',
    'stroke severity assessment',
    'large vessel occlusion identification',
    'hemorrhagic transformation monitoring',
    'malignant MCA edema management',
    'permissive hypertension strategy',
  ],
  excluded_decision_scopes: [
    'hemorrhagic stroke management',
    'chronic stroke rehabilitation',
    'primary stroke prevention',
    'atrial fibrillation anticoagulation for secondary prevention',
    'carotid endarterectomy timing',
    'intracranial atherosclerosis stenting',
  ],

  recommendations: [
    {
      rec_id: 'PACK.AHA.STROKE.2019.REC.01',
      display_id: 'AHA-STROKE-R1',
      statement: 'IV alteplase (0.9 mg/kg, max 90 mg, 10% bolus over 1 minute, remainder over 60 minutes) is recommended for eligible patients within 4.5 hours of symptom onset or last known well.',
      normalized_claim: 'IV alteplase 0.9 mg/kg (max 90 mg) within 4.5h of onset for eligible patients. 10% IV bolus, remainder infused over 60 min.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'Benefit decreases with time; treat as early as possible. Extended 3-4.5h window has additional exclusion criteria.',
      provenance: { section: 'IV Alteplase', page_or_location: 'Section 3.1' },
    },
    {
      rec_id: 'PACK.AHA.STROKE.2019.REC.02',
      display_id: 'AHA-STROKE-R2',
      statement: 'Mechanical thrombectomy with a stent retriever is recommended for patients with LVO causing anterior circulation stroke, NIHSS >=6, ASPECTS >=6, who can be treated within 6 hours of symptom onset.',
      normalized_claim: 'Thrombectomy for anterior LVO with NIHSS >=6 and ASPECTS >=6 within 6h of onset.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'Based on MR CLEAN, ESCAPE, EXTEND-IA, SWIFT PRIME, and REVASCAT trials.',
      provenance: { section: 'Mechanical Thrombectomy', page_or_location: 'Section 3.5' },
    },
    {
      rec_id: 'PACK.AHA.STROKE.2019.REC.03',
      display_id: 'AHA-STROKE-R3',
      statement: 'Mechanical thrombectomy may be reasonable for select patients with anterior LVO up to 24 hours from last known well if they meet DAWN or DEFUSE-3 imaging eligibility criteria demonstrating salvageable penumbra.',
      normalized_claim: 'Extended-window thrombectomy (6-24h) for anterior LVO if perfusion imaging shows salvageable tissue (DAWN/DEFUSE-3 criteria).',
      strength: 'conditional',
      evidence_quality: 'moderate',
      population: 'Patients with clinical-core mismatch on CT perfusion or MRI diffusion-perfusion',
      provenance: { section: 'Extended Window Thrombectomy', page_or_location: 'Section 3.6' },
    },
    {
      rec_id: 'PACK.AHA.STROKE.2019.REC.04',
      display_id: 'AHA-STROKE-R4',
      statement: 'Blood pressure should be maintained below 185/110 mmHg before and during IV alteplase administration, and below 180/105 mmHg for the 24 hours after alteplase.',
      normalized_claim: 'BP must be <185/110 before tPA and <180/105 for 24h after tPA.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Blood Pressure Management', page_or_location: 'Section 3.2' },
    },
    {
      rec_id: 'PACK.AHA.STROKE.2019.REC.05',
      display_id: 'AHA-STROKE-R5',
      statement: 'In patients not receiving thrombolysis or thrombectomy, permissive hypertension up to 220/120 mmHg is recommended in the first 24-48 hours. Antihypertensive treatment is initiated only if BP exceeds 220/120 or there is a concurrent indication (e.g., aortic dissection, acute MI, heart failure).',
      normalized_claim: 'Permissive HTN up to 220/120 if no thrombolysis. Treat only if >220/120 or concurrent end-organ indication.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Blood Pressure Management', page_or_location: 'Section 3.3' },
    },
    {
      rec_id: 'PACK.AHA.STROKE.2019.REC.06',
      display_id: 'AHA-STROKE-R6',
      statement: 'Aspirin (325 mg loading, then 81 mg daily) should be administered within 24-48 hours of acute ischemic stroke onset. If tPA was given, aspirin is held for 24 hours post-alteplase.',
      normalized_claim: 'Aspirin within 24-48h of stroke onset. Hold 24h after tPA before starting.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Antiplatelet Therapy', page_or_location: 'Section 4.1' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.AHA.STROKE.2019.DC.01',
      display_id: 'AHA-STROKE-DC1',
      name: 'Acute Ischemic Stroke Definition',
      components: [
        'Acute onset of focal neurological deficit',
        'Symptoms attributable to a vascular territory',
        'Absence of hemorrhage on non-contrast CT head',
        'No alternative explanation (e.g., seizure, migraine, hypoglycemia)',
      ],
      interpretation: 'Clinical diagnosis confirmed by neuroimaging excluding hemorrhage. CT head is first-line to rule out bleed before thrombolysis.',
      normalized_claim: 'Acute ischemic stroke = sudden focal neuro deficit in a vascular territory with no hemorrhage on CT.',
      provenance: { section: 'Diagnosis', page_or_location: 'Section 2.1' },
    },
    {
      criterion_id: 'PACK.AHA.STROKE.2019.DC.02',
      display_id: 'AHA-STROKE-DC2',
      name: 'NIHSS (National Institutes of Health Stroke Scale)',
      components: [
        'Level of consciousness (LOC): questions and commands',
        'Best gaze (horizontal eye movements)',
        'Visual fields',
        'Facial palsy',
        'Motor arm and motor leg (each side scored separately)',
        'Limb ataxia',
        'Sensory',
        'Best language (aphasia)',
        'Dysarthria',
        'Extinction and inattention (neglect)',
      ],
      threshold: 'Score range 0-42',
      interpretation: 'Quantifies stroke severity. Guides thrombolysis/thrombectomy eligibility and prognosis. NIHSS >=6 generally considered for thrombectomy.',
      normalized_claim: 'NIHSS is a 42-point scale quantifying stroke severity across 11 domains. Score >=6 supports thrombectomy consideration for LVO.',
      provenance: { section: 'Stroke Severity Assessment', page_or_location: 'Section 2.3' },
    },
    {
      criterion_id: 'PACK.AHA.STROKE.2019.DC.03',
      display_id: 'AHA-STROKE-DC3',
      name: 'Large Vessel Occlusion (LVO) Criteria for Thrombectomy',
      components: [
        'Occlusion of internal carotid artery (ICA) terminus',
        'Occlusion of M1 segment of middle cerebral artery (MCA)',
        'Occlusion of proximal M2 MCA branch (selected cases)',
        'Confirmed on CT angiography (CTA) or MR angiography (MRA)',
      ],
      interpretation: 'LVO identification is essential for thrombectomy triage. CTA is the standard imaging modality for rapid LVO detection.',
      normalized_claim: 'LVO = ICA terminus or M1 MCA occlusion on CTA/MRA. Proximal M2 may qualify. Required for thrombectomy eligibility.',
      provenance: { section: 'Endovascular Therapy', page_or_location: 'Section 3.5' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.AHA.STROKE.2019.T.01',
      display_id: 'AHA-STROKE-T1',
      parameter: 'IV alteplase time window',
      value: '4.5',
      unit: 'hours from symptom onset',
      clinical_meaning: 'Maximum time from symptom onset (or last known well) to IV alteplase administration. Benefit is time-dependent; earlier treatment yields better outcomes.',
      normalized_claim: 'IV alteplase must be given within 4.5h of symptom onset or last known well.',
      direction: 'below',
      provenance: { section: 'IV Alteplase', page_or_location: 'Section 3.1' },
    },
    {
      threshold_id: 'PACK.AHA.STROKE.2019.T.02',
      display_id: 'AHA-STROKE-T2',
      parameter: 'Extended thrombectomy time window',
      value: '24',
      unit: 'hours from last known well',
      clinical_meaning: 'Thrombectomy may be performed up to 24 hours from last known well if perfusion imaging demonstrates salvageable penumbra (DAWN or DEFUSE-3 criteria).',
      normalized_claim: 'Thrombectomy window extends to 24h with perfusion imaging showing mismatch (DAWN/DEFUSE-3 eligible).',
      direction: 'below',
      provenance: { section: 'Extended Window Thrombectomy', page_or_location: 'Section 3.6' },
    },
    {
      threshold_id: 'PACK.AHA.STROKE.2019.T.03',
      display_id: 'AHA-STROKE-T3',
      parameter: 'Blood pressure for tPA eligibility',
      value: '185/110',
      unit: 'mmHg',
      clinical_meaning: 'BP must be reduced below 185/110 before alteplase can be administered. Labetalol or nicardipine are first-line agents for acute BP reduction.',
      normalized_claim: 'BP must be <185/110 mmHg before tPA administration. Labetalol or nicardipine to achieve target.',
      direction: 'below',
      provenance: { section: 'Blood Pressure Management', page_or_location: 'Section 3.2' },
    },
    {
      threshold_id: 'PACK.AHA.STROKE.2019.T.04',
      display_id: 'AHA-STROKE-T4',
      parameter: 'NIHSS for thrombectomy consideration',
      value: '6',
      clinical_meaning: 'NIHSS >=6 generally supports thrombectomy consideration when LVO is confirmed. Lower NIHSS scores may still warrant intervention if LVO is present and deficit is disabling.',
      normalized_claim: 'NIHSS >=6 with confirmed LVO supports thrombectomy. Lower scores may qualify if deficit is disabling.',
      direction: 'above',
      provenance: { section: 'Endovascular Therapy', page_or_location: 'Section 3.5' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.AHA.STROKE.2019.TX.01',
      display_id: 'AHA-STROKE-TX1',
      action: 'IV alteplase for eligible patients',
      normalized_claim: 'Alteplase 0.9 mg/kg (max 90 mg): 10% IV bolus over 1 min, remainder infused over 60 min. Admit to ICU/stroke unit for 24h neuro checks and BP monitoring.',
      timing: 'Within 4.5 hours of symptom onset',
      condition: 'tPA eligible: onset <4.5h, no hemorrhage on CT, BP <185/110, no contraindications',
      drug_details: { drug: 'Alteplase', dose: '0.9 mg/kg (max 90 mg)', route: 'IV', duration: '60-minute infusion after bolus' },
      contraindications: [
        'Active internal bleeding',
        'Recent intracranial surgery or head trauma (<3 months)',
        'Platelet count <100,000',
        'INR >1.7 or PT >15 seconds',
        'Current anticoagulant use with elevated INR',
        'Blood glucose <50 mg/dL',
      ],
      provenance: { section: 'IV Alteplase', page_or_location: 'Section 3.1' },
    },
    {
      step_id: 'PACK.AHA.STROKE.2019.TX.02',
      display_id: 'AHA-STROKE-TX2',
      action: 'Mechanical thrombectomy for LVO',
      normalized_claim: 'Endovascular thrombectomy with stent retriever or aspiration for confirmed LVO. IV tPA should not delay transfer to thrombectomy-capable center.',
      timing: 'Within 6-24 hours depending on imaging selection',
      condition: 'LVO confirmed on CTA with NIHSS >=6 and ASPECTS >=6',
      escalation: 'If initial pass fails, consider rescue techniques (aspiration, combined approach)',
      provenance: { section: 'Mechanical Thrombectomy', page_or_location: 'Section 3.5' },
    },
    {
      step_id: 'PACK.AHA.STROKE.2019.TX.03',
      display_id: 'AHA-STROKE-TX3',
      action: 'Supportive management for non-thrombolysis/non-thrombectomy candidates',
      normalized_claim: 'Non-tPA/non-thrombectomy stroke: aspirin within 24-48h, high-intensity statin, permissive HTN (allow up to 220/120), DVT prophylaxis, swallow evaluation before PO.',
      timing: 'Within 24-48 hours of presentation',
      condition: 'Not eligible for tPA or thrombectomy (outside time window, mild deficit, or contraindicated)',
      provenance: { section: 'General Supportive Care', page_or_location: 'Section 4.1' },
    },
    {
      step_id: 'PACK.AHA.STROKE.2019.TX.04',
      display_id: 'AHA-STROKE-TX4',
      action: 'Blood pressure management with IV labetalol or nicardipine',
      normalized_claim: 'Labetalol 10-20 mg IV over 1-2 min (may repeat) or nicardipine 5 mg/h IV infusion (titrate by 2.5 mg/h q5-15 min, max 15 mg/h) to achieve BP targets.',
      timing: 'Before and during thrombolytic therapy',
      condition: 'BP >185/110 in thrombolysis candidate or >220/120 in non-thrombolysis patient',
      drug_details: { drug: 'Labetalol or Nicardipine', dose: 'Labetalol 10-20 mg IV; Nicardipine 5-15 mg/h', route: 'IV' },
      provenance: { section: 'Blood Pressure Management', page_or_location: 'Section 3.2' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.AHA.STROKE.2019.RF.01',
      display_id: 'AHA-STROKE-RF1',
      finding: 'Hemorrhagic transformation: Acute neurological worsening during or after tPA infusion with headache, hypertension, nausea/vomiting, or declining consciousness',
      implication: 'Symptomatic intracerebral hemorrhage occurs in 6-7% of tPA-treated patients. Can be fatal if not recognized and treated immediately.',
      action: 'Stop tPA infusion immediately. Emergent non-contrast CT head. Administer cryoprecipitate (10 units), tranexamic acid, or aminocaproic acid. Reverse coagulopathy. Neurosurgical consultation.',
      urgency: 'immediate',
      provenance: { section: 'Hemorrhagic Complications', page_or_location: 'Section 3.4' },
    },
    {
      flag_id: 'PACK.AHA.STROKE.2019.RF.02',
      display_id: 'AHA-STROKE-RF2',
      finding: 'Malignant MCA edema: Large MCA territory infarct (>50% MCA territory) with progressive neurological decline, midline shift, and declining consciousness within 24-48 hours',
      implication: 'Mortality approaches 80% with medical management alone. Affects younger patients more often. Peak edema at 72-96 hours.',
      action: 'Decompressive hemicraniectomy within 48 hours of onset in patients <=60 years old. Consider osmotic therapy (hypertonic saline, mannitol) as bridge. Elevate head of bed to 30 degrees.',
      urgency: 'urgent',
      provenance: { section: 'Cerebral Edema', page_or_location: 'Section 5.2' },
    },
    {
      flag_id: 'PACK.AHA.STROKE.2019.RF.03',
      display_id: 'AHA-STROKE-RF3',
      finding: 'Basilar artery occlusion: Acute onset of quadriplegia, bilateral cranial nerve deficits, decreased consciousness, locked-in syndrome, or coma',
      implication: 'Near-complete mortality without intervention. Classic presentation includes crossed deficits (ipsilateral cranial nerve, contralateral motor) progressing to bilateral signs.',
      action: 'Emergent CTA to confirm basilar occlusion. IV tPA if within window. Emergent thrombectomy regardless of NIHSS score. Consider thrombectomy even in extended windows given poor natural history.',
      urgency: 'immediate',
      provenance: { section: 'Posterior Circulation Stroke', page_or_location: 'Section 3.7' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.AHA.STROKE.2019.SEV.01',
      display_id: 'AHA-STROKE-SEV1',
      level: 'Minor stroke (NIHSS <5)',
      criteria: [
        'NIHSS score 0-4',
        'Isolated minor deficit (e.g., facial droop, mild arm drift, dysarthria)',
        'No large vessel occlusion on imaging',
        'Functionally independent (can perform ADLs)',
      ],
      management_implications:
        'IV alteplase may be considered if deficit is disabling despite low NIHSS. Thrombectomy generally not indicated. Aspirin within 24-48h. Rapid workup for etiology (echocardiography, telemetry, carotid imaging). May not require ICU admission.',
      provenance: { section: 'Stroke Severity Classification', page_or_location: 'Section 2.3' },
    },
    {
      severity_id: 'PACK.AHA.STROKE.2019.SEV.02',
      display_id: 'AHA-STROKE-SEV2',
      level: 'Moderate stroke (NIHSS 5-15)',
      criteria: [
        'NIHSS score 5-15',
        'Significant motor deficit, aphasia, or neglect',
        'May have LVO (CTA warranted)',
        'Functional impairment requiring assistance',
      ],
      management_implications:
        'Strong candidate for IV alteplase if within window. Obtain CTA to evaluate for LVO and thrombectomy candidacy. ICU or stroke unit monitoring. Early rehabilitation assessment. Higher risk of hemorrhagic transformation with tPA.',
      provenance: { section: 'Stroke Severity Classification', page_or_location: 'Section 2.3' },
    },
    {
      severity_id: 'PACK.AHA.STROKE.2019.SEV.03',
      display_id: 'AHA-STROKE-SEV3',
      level: 'Severe stroke (NIHSS >15)',
      criteria: [
        'NIHSS score >15',
        'Dense hemiplegia, global aphasia, forced gaze deviation, or decreased consciousness',
        'High probability of LVO',
        'Complete functional dependence',
      ],
      management_implications:
        'Emergent IV alteplase plus CTA for thrombectomy evaluation. High risk for malignant cerebral edema (especially if large MCA territory involved). ICU-level care required. Monitor for herniation signs. Discuss goals of care early. Hemicraniectomy may be needed if malignant edema develops.',
      provenance: { section: 'Stroke Severity Classification', page_or_location: 'Section 2.3' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 lightweight pack for acute ischemic stroke. Covers tPA eligibility, thrombectomy decision-making, BP management, and severity stratification for question generation.',

  all_item_ids: [
    'PACK.AHA.STROKE.2019.REC.01', 'PACK.AHA.STROKE.2019.REC.02', 'PACK.AHA.STROKE.2019.REC.03',
    'PACK.AHA.STROKE.2019.REC.04', 'PACK.AHA.STROKE.2019.REC.05', 'PACK.AHA.STROKE.2019.REC.06',
    'PACK.AHA.STROKE.2019.DC.01', 'PACK.AHA.STROKE.2019.DC.02', 'PACK.AHA.STROKE.2019.DC.03',
    'PACK.AHA.STROKE.2019.T.01', 'PACK.AHA.STROKE.2019.T.02', 'PACK.AHA.STROKE.2019.T.03',
    'PACK.AHA.STROKE.2019.T.04',
    'PACK.AHA.STROKE.2019.TX.01', 'PACK.AHA.STROKE.2019.TX.02', 'PACK.AHA.STROKE.2019.TX.03',
    'PACK.AHA.STROKE.2019.TX.04',
    'PACK.AHA.STROKE.2019.RF.01', 'PACK.AHA.STROKE.2019.RF.02', 'PACK.AHA.STROKE.2019.RF.03',
    'PACK.AHA.STROKE.2019.SEV.01', 'PACK.AHA.STROKE.2019.SEV.02', 'PACK.AHA.STROKE.2019.SEV.03',
  ],
  all_display_ids: [
    'AHA-STROKE-R1', 'AHA-STROKE-R2', 'AHA-STROKE-R3', 'AHA-STROKE-R4', 'AHA-STROKE-R5', 'AHA-STROKE-R6',
    'AHA-STROKE-DC1', 'AHA-STROKE-DC2', 'AHA-STROKE-DC3',
    'AHA-STROKE-T1', 'AHA-STROKE-T2', 'AHA-STROKE-T3', 'AHA-STROKE-T4',
    'AHA-STROKE-TX1', 'AHA-STROKE-TX2', 'AHA-STROKE-TX3', 'AHA-STROKE-TX4',
    'AHA-STROKE-RF1', 'AHA-STROKE-RF2', 'AHA-STROKE-RF3',
    'AHA-STROKE-SEV1', 'AHA-STROKE-SEV2', 'AHA-STROKE-SEV3',
  ],
};
