import type { SourcePack } from './types';

export const PACK_AHA_PE_2024: SourcePack = {
  source_pack_id: 'PACK.AHA.PE.2024',
  source_name: 'AHA/ESC 2024 Guidelines on Pulmonary Embolism',
  source_registry_id: 'REG.AHA.PE',
  canonical_url: 'https://doi.org/10.1161/CIR.0000000000001200',
  publication_year: 2024,
  guideline_body: 'AHA/ESC',

  topic_tags: ['Pulmonary Embolism', 'DVT', 'VTE', 'Pulmonology', 'Cardiology'],
  allowed_decision_scopes: [
    'PE pre-test probability assessment',
    'PE diagnostic workup',
    'PE anticoagulation',
    'massive PE thrombolysis',
    'submassive PE management',
    'PE risk stratification',
    'VTE prophylaxis',
    'IVC filter indications',
  ],
  excluded_decision_scopes: [
    'chronic thromboembolic pulmonary hypertension',
    'pregnancy-specific VTE management',
    'cancer-associated thrombosis long-term',
    'upper extremity DVT',
  ],

  recommendations: [
    {
      rec_id: 'PACK.AHA.PE.2024.REC.01',
      display_id: 'AHA-PE-R1',
      statement: 'Use Wells criteria or Geneva score for pre-test probability assessment before diagnostic testing.',
      normalized_claim: 'Pre-test probability must be assessed before ordering D-dimer or imaging.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Diagnosis', page_or_location: 'Section 3.1' },
    },
    {
      rec_id: 'PACK.AHA.PE.2024.REC.02',
      display_id: 'AHA-PE-R2',
      statement: 'D-dimer testing can exclude PE in patients with low or intermediate pre-test probability. A negative age-adjusted D-dimer safely excludes PE.',
      normalized_claim: 'Negative D-dimer excludes PE in low/intermediate probability. Use age-adjusted cutoff (age x 10) for patients >50yo.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'D-dimer', page_or_location: 'Section 3.2' },
    },
    {
      rec_id: 'PACK.AHA.PE.2024.REC.03',
      display_id: 'AHA-PE-R3',
      statement: 'CT pulmonary angiography (CTPA) is the first-line confirmatory imaging test for PE.',
      normalized_claim: 'CTPA is the gold standard imaging for PE diagnosis.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Imaging', page_or_location: 'Section 3.3' },
    },
    {
      rec_id: 'PACK.AHA.PE.2024.REC.04',
      display_id: 'AHA-PE-R4',
      statement: 'Therapeutic anticoagulation should be initiated immediately in confirmed PE. DOACs (rivaroxaban, apixaban) are preferred over warfarin for most patients.',
      normalized_claim: 'Anticoagulate immediately upon PE diagnosis. DOACs preferred over warfarin for non-massive PE.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Treatment', page_or_location: 'Section 4.1' },
    },
    {
      rec_id: 'PACK.AHA.PE.2024.REC.05',
      display_id: 'AHA-PE-R5',
      statement: 'Systemic thrombolysis (alteplase) is recommended for massive PE with hemodynamic instability.',
      normalized_claim: 'Massive PE (SBP <90 or requiring vasopressors) requires systemic thrombolysis. Alteplase 100mg IV over 2 hours is standard.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Massive PE', page_or_location: 'Section 4.3' },
    },
    {
      rec_id: 'PACK.AHA.PE.2024.REC.06',
      display_id: 'AHA-PE-R6',
      statement: 'Submassive PE (RV dysfunction without hypotension) should be treated with anticoagulation and close monitoring. Thrombolysis may be considered if clinical deterioration occurs.',
      normalized_claim: 'Submassive PE: anticoagulate + monitor. Reserve thrombolysis for clinical deterioration.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      provenance: { section: 'Submassive PE', page_or_location: 'Section 4.2' },
    },
    {
      rec_id: 'PACK.AHA.PE.2024.REC.07',
      display_id: 'AHA-PE-R7',
      statement: 'IVC filter placement is indicated only when anticoagulation is absolutely contraindicated (e.g., active major hemorrhage).',
      normalized_claim: 'IVC filter only when anticoagulation is absolutely contraindicated. Not a substitute for anticoagulation.',
      strength: 'conditional',
      evidence_quality: 'low',
      provenance: { section: 'IVC Filters', page_or_location: 'Section 4.5' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.AHA.PE.2024.DC.01',
      display_id: 'AHA-PE-DC1',
      name: 'Wells Criteria for PE',
      components: [
        'Clinical signs of DVT (3 points)',
        'PE is #1 diagnosis or equally likely (3 points)',
        'Heart rate >100 (1.5 points)',
        'Immobilization/surgery in prior 4 weeks (1.5 points)',
        'Previous DVT/PE (1.5 points)',
        'Hemoptysis (1 point)',
        'Malignancy (1 point)',
      ],
      threshold: '>4 points = PE likely; <=4 = PE unlikely',
      interpretation: 'Score >4: proceed to CTPA. Score <=4: D-dimer first.',
      normalized_claim: 'Wells >4 = PE likely (image directly). Wells <=4 = PE unlikely (D-dimer to exclude).',
      provenance: { section: 'Pre-test Probability', page_or_location: 'Section 3.1' },
    },
    {
      criterion_id: 'PACK.AHA.PE.2024.DC.02',
      display_id: 'AHA-PE-DC2',
      name: 'Massive PE Definition',
      components: [
        'Sustained systolic BP <90 mmHg for >=15 minutes',
        'OR requirement for vasopressors',
        'OR cardiac arrest/pulselessness',
      ],
      interpretation: 'Massive PE requires emergent thrombolysis or catheter-directed therapy.',
      normalized_claim: 'Massive PE = SBP <90 sustained, vasopressor requirement, or cardiac arrest.',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 2.2' },
    },
    {
      criterion_id: 'PACK.AHA.PE.2024.DC.03',
      display_id: 'AHA-PE-DC3',
      name: 'Submassive PE Definition',
      components: [
        'RV dysfunction on echo or CT (RV/LV ratio >0.9)',
        'OR elevated troponin or BNP',
        'WITHOUT systemic hypotension',
      ],
      interpretation: 'Submassive PE: monitor closely for decompensation. Anticoagulate; consider thrombolysis if worsening.',
      normalized_claim: 'Submassive PE = RV dysfunction or biomarker elevation without hypotension.',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 2.2' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.AHA.PE.2024.T.01',
      display_id: 'AHA-PE-T1',
      parameter: 'D-dimer',
      value: '500',
      unit: 'ng/mL',
      clinical_meaning: 'D-dimer <500 ng/mL excludes PE in low/intermediate probability patients. Age-adjusted: age x 10 for patients >50yo.',
      normalized_claim: 'D-dimer <500 (or age-adjusted cutoff) excludes PE when pre-test probability is low/intermediate.',
      direction: 'below',
      provenance: { section: 'D-dimer', page_or_location: 'Section 3.2' },
    },
    {
      threshold_id: 'PACK.AHA.PE.2024.T.02',
      display_id: 'AHA-PE-T2',
      parameter: 'Wells score',
      value: '4',
      clinical_meaning: 'Score <=4 = PE unlikely (D-dimer first). Score >4 = PE likely (image directly with CTPA).',
      normalized_claim: 'Wells <=4 is low probability; >4 is high probability.',
      direction: 'above',
      provenance: { section: 'Pre-test Probability', page_or_location: 'Section 3.1' },
    },
    {
      threshold_id: 'PACK.AHA.PE.2024.T.03',
      display_id: 'AHA-PE-T3',
      parameter: 'sPESI score',
      value: '0',
      clinical_meaning: 'sPESI = 0 identifies low-risk PE patients who may be candidates for outpatient treatment.',
      normalized_claim: 'sPESI 0 = low risk, consider outpatient management.',
      direction: 'below',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 2.3' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.AHA.PE.2024.TX.01',
      display_id: 'AHA-PE-TX1',
      action: 'Empiric anticoagulation for high clinical suspicion',
      normalized_claim: 'When PE suspicion is high, start empiric heparin BEFORE imaging results.',
      timing: 'Before confirmatory imaging if high suspicion',
      drug_details: { drug: 'Unfractionated heparin', dose: '80 units/kg bolus then 18 units/kg/hr', route: 'IV' },
      provenance: { section: 'Empiric Treatment', page_or_location: 'Section 4.1' },
    },
    {
      step_id: 'PACK.AHA.PE.2024.TX.02',
      display_id: 'AHA-PE-TX2',
      action: 'Confirmed PE: therapeutic anticoagulation',
      normalized_claim: 'Confirmed non-massive PE: DOAC (rivaroxaban or apixaban) preferred, or LMWH bridged to warfarin.',
      timing: 'Immediately upon confirmation',
      drug_details: { drug: 'Rivaroxaban', dose: '15mg BID x 21 days then 20mg daily', route: 'PO' },
      provenance: { section: 'Anticoagulation', page_or_location: 'Section 4.1' },
    },
    {
      step_id: 'PACK.AHA.PE.2024.TX.03',
      display_id: 'AHA-PE-TX3',
      action: 'Massive PE: systemic thrombolysis',
      normalized_claim: 'Massive PE with hemodynamic instability: alteplase 100mg IV over 2 hours. Catheter-directed therapy if thrombolysis contraindicated.',
      timing: 'Emergent',
      condition: 'SBP <90 or requiring vasopressors',
      drug_details: { drug: 'Alteplase', dose: '100mg', route: 'IV over 2 hours' },
      contraindications: ['Active internal bleeding', 'Recent stroke (<3 months)', 'Intracranial neoplasm'],
      provenance: { section: 'Massive PE', page_or_location: 'Section 4.3' },
    },
    {
      step_id: 'PACK.AHA.PE.2024.TX.04',
      display_id: 'AHA-PE-TX4',
      action: 'Anticoagulation duration',
      normalized_claim: 'Minimum 3 months for provoked PE. Extended/indefinite for unprovoked PE or persistent risk factors.',
      timing: 'Reassess at 3 months',
      provenance: { section: 'Duration', page_or_location: 'Section 4.4' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.AHA.PE.2024.RF.01',
      display_id: 'AHA-PE-RF1',
      finding: 'Hemodynamic instability: SBP <90, tachycardia, altered mental status',
      implication: 'Massive PE. Mortality >25% without thrombolysis.',
      action: 'Emergent thrombolysis (alteplase) or catheter-directed therapy. IV fluid bolus. Vasopressors.',
      urgency: 'immediate',
      provenance: { section: 'Massive PE', page_or_location: 'Section 4.3' },
    },
    {
      flag_id: 'PACK.AHA.PE.2024.RF.02',
      display_id: 'AHA-PE-RF2',
      finding: 'RV failure on echocardiography: RV dilation, McConnell sign, RV/LV ratio >0.9',
      implication: 'Submassive PE with high risk of decompensation. Monitor in ICU.',
      action: 'Anticoagulate, ICU admission, serial troponin/BNP, low threshold for thrombolysis if worsening.',
      urgency: 'urgent',
      provenance: { section: 'Submassive PE', page_or_location: 'Section 4.2' },
    },
    {
      flag_id: 'PACK.AHA.PE.2024.RF.03',
      display_id: 'AHA-PE-RF3',
      finding: 'Saddle embolus on CTPA: thrombus straddling main pulmonary artery bifurcation',
      implication: 'High risk of hemodynamic collapse even if currently stable.',
      action: 'ICU monitoring, assess for RV strain, consider early intervention.',
      urgency: 'urgent',
      provenance: { section: 'Imaging Findings', page_or_location: 'Section 3.3' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.AHA.PE.2024.SEV.01',
      display_id: 'AHA-PE-SV1',
      level: 'Massive PE',
      criteria: ['SBP <90 for >=15 min', 'Vasopressor requirement', 'Cardiac arrest'],
      management_implications: 'Emergent thrombolysis or catheter-directed therapy. ICU admission.',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 2.2' },
    },
    {
      severity_id: 'PACK.AHA.PE.2024.SEV.02',
      display_id: 'AHA-PE-SV2',
      level: 'Submassive PE',
      criteria: ['RV dysfunction (echo or CT)', 'Elevated troponin or BNP', 'Hemodynamically stable'],
      management_implications: 'Anticoagulation + ICU monitoring. Thrombolysis if clinical deterioration.',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 2.2' },
    },
    {
      severity_id: 'PACK.AHA.PE.2024.SEV.03',
      display_id: 'AHA-PE-SV3',
      level: 'Low-risk PE',
      criteria: ['sPESI = 0', 'No RV dysfunction', 'Normal biomarkers'],
      management_implications: 'Outpatient anticoagulation may be appropriate.',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 2.3' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-14',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 lightweight pack for PE/VTE. Covers Wells criteria, D-dimer, risk stratification, and severity-based management. Evidence grounding per P4 (Jia et al. 2026).',

  all_item_ids: [
    'PACK.AHA.PE.2024.REC.01', 'PACK.AHA.PE.2024.REC.02', 'PACK.AHA.PE.2024.REC.03',
    'PACK.AHA.PE.2024.REC.04', 'PACK.AHA.PE.2024.REC.05', 'PACK.AHA.PE.2024.REC.06',
    'PACK.AHA.PE.2024.REC.07', 'PACK.AHA.PE.2024.DC.01', 'PACK.AHA.PE.2024.DC.02',
    'PACK.AHA.PE.2024.DC.03', 'PACK.AHA.PE.2024.T.01', 'PACK.AHA.PE.2024.T.02',
    'PACK.AHA.PE.2024.T.03', 'PACK.AHA.PE.2024.TX.01', 'PACK.AHA.PE.2024.TX.02',
    'PACK.AHA.PE.2024.TX.03', 'PACK.AHA.PE.2024.TX.04', 'PACK.AHA.PE.2024.RF.01',
    'PACK.AHA.PE.2024.RF.02', 'PACK.AHA.PE.2024.RF.03', 'PACK.AHA.PE.2024.SEV.01',
    'PACK.AHA.PE.2024.SEV.02', 'PACK.AHA.PE.2024.SEV.03',
  ],
  all_display_ids: [
    'AHA-PE-R1', 'AHA-PE-R2', 'AHA-PE-R3', 'AHA-PE-R4', 'AHA-PE-R5', 'AHA-PE-R6', 'AHA-PE-R7',
    'AHA-PE-DC1', 'AHA-PE-DC2', 'AHA-PE-DC3',
    'AHA-PE-T1', 'AHA-PE-T2', 'AHA-PE-T3',
    'AHA-PE-TX1', 'AHA-PE-TX2', 'AHA-PE-TX3', 'AHA-PE-TX4',
    'AHA-PE-RF1', 'AHA-PE-RF2', 'AHA-PE-RF3',
    'AHA-PE-SV1', 'AHA-PE-SV2', 'AHA-PE-SV3',
  ],
};
