import type { SourcePack } from './types';

export const PACK_AHA_KAWA_2017: SourcePack = {
  source_pack_id: 'PACK.AHA.KAWA.2017',
  source_name: 'AHA 2017 Scientific Statement: Diagnosis, Treatment, and Long-Term Management of Kawasaki Disease',
  source_registry_id: 'REG.AHA.KAWA',
  canonical_url: 'https://doi.org/10.1161/CIR.0000000000000484',
  publication_year: 2017,
  guideline_body: 'AHA',

  topic_tags: ['Kawasaki Disease', 'Pediatric Cardiology', 'Vasculitis', 'Coronary Artery Aneurysm'],
  allowed_decision_scopes: [
    'Kawasaki disease diagnosis',
    'incomplete Kawasaki evaluation',
    'IVIG therapy initiation',
    'aspirin dosing in Kawasaki',
    'coronary artery aneurysm surveillance',
    'refractory Kawasaki management',
  ],
  excluded_decision_scopes: [
    'adult-onset Kawasaki disease',
    'long-term anticoagulation for giant aneurysms',
    'cardiac surgery for coronary complications',
  ],

  recommendations: [
    {
      rec_id: 'PACK.AHA.KAWA.2017.REC.01',
      display_id: 'AHA-KAWA-R1',
      statement: 'IVIG (2 g/kg as a single infusion) should be administered within the first 10 days of illness, ideally within 7 days of fever onset.',
      normalized_claim: 'IVIG 2 g/kg single infusion within first 10 days of illness reduces coronary artery aneurysm risk from 25% to <5%.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'Treatment should not be delayed for confirmatory testing if clinical suspicion is high',
      provenance: { section: 'Treatment', page_or_location: 'Section 4.1' },
    },
    {
      rec_id: 'PACK.AHA.KAWA.2017.REC.02',
      display_id: 'AHA-KAWA-R2',
      statement: 'Aspirin is recommended during the acute phase (high-dose 80-100 mg/kg/day) followed by low-dose (3-5 mg/kg/day) for 6-8 weeks after fever resolution.',
      normalized_claim: 'Acute-phase high-dose aspirin (80-100 mg/kg/day) until afebrile, then low-dose aspirin (3-5 mg/kg/day) for 6-8 weeks.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Aspirin Therapy', page_or_location: 'Section 4.2' },
    },
    {
      rec_id: 'PACK.AHA.KAWA.2017.REC.03',
      display_id: 'AHA-KAWA-R3',
      statement: 'Echocardiography should be performed at diagnosis, at 1-2 weeks, and at 6-8 weeks after treatment. More frequent imaging is needed if coronary abnormalities are detected.',
      normalized_claim: 'Echocardiography at diagnosis, 1-2 weeks, and 6-8 weeks; increased frequency if coronary abnormalities found.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Cardiac Imaging', page_or_location: 'Section 5.1' },
    },
    {
      rec_id: 'PACK.AHA.KAWA.2017.REC.04',
      display_id: 'AHA-KAWA-R4',
      statement: 'Patients with IVIG-refractory Kawasaki disease (persistent or recrudescent fever >=36 hours after initial IVIG) should receive a second dose of IVIG or consider infliximab.',
      normalized_claim: 'IVIG-refractory KD (fever persisting >36h post-IVIG) requires second IVIG dose or infliximab.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      provenance: { section: 'Refractory Disease', page_or_location: 'Section 4.3' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.AHA.KAWA.2017.DC.01',
      display_id: 'AHA-KAWA-DC1',
      name: 'Classic Kawasaki Disease Criteria',
      components: [
        'Fever persisting >=5 days',
        'Plus >=4 of 5 principal clinical features:',
        '1. Bilateral bulbar conjunctival injection without exudate',
        '2. Changes in lips and oral cavity (strawberry tongue, erythema, cracking)',
        '3. Polymorphous exanthem (rash)',
        '4. Changes in extremities (erythema, edema, periungual desquamation)',
        '5. Cervical lymphadenopathy (>=1.5 cm, usually unilateral)',
      ],
      threshold: 'Fever >=5 days plus >=4 of 5 principal features',
      interpretation: 'Diagnosis is clinical. Experienced clinicians may diagnose with fewer criteria if coronary abnormalities are present.',
      normalized_claim: 'Classic KD requires fever >=5 days plus >=4 of 5 clinical features: conjunctivitis, oral changes, rash, extremity changes, cervical lymphadenopathy.',
      provenance: { section: 'Diagnosis', page_or_location: 'Section 2.1' },
    },
    {
      criterion_id: 'PACK.AHA.KAWA.2017.DC.02',
      display_id: 'AHA-KAWA-DC2',
      name: 'Incomplete Kawasaki Disease Criteria',
      components: [
        'Fever >=5 days with 2-3 principal clinical features',
        'CRP >=3.0 mg/dL and/or ESR >=40 mm/hr',
        'Plus >=3 supplemental lab criteria: albumin <=3.0, anemia, elevated ALT, platelets >450K after day 7, WBC >=15K, urine WBC >=10/hpf',
        'Or positive echocardiographic findings (coronary z-score >=2.5)',
      ],
      interpretation: 'Incomplete KD should be considered in any child with prolonged unexplained fever and fewer than 4 criteria. Lab and echo data support the diagnosis.',
      normalized_claim: 'Incomplete KD: fever >=5 days + 2-3 features + elevated inflammatory markers + supplemental lab/echo criteria.',
      provenance: { section: 'Incomplete Kawasaki Disease', page_or_location: 'Section 2.2' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.AHA.KAWA.2017.T.01',
      display_id: 'AHA-KAWA-T1',
      parameter: 'Fever duration for KD diagnosis',
      value: '5',
      unit: 'days',
      clinical_meaning: 'Fever persisting at least 5 days is required for classic KD diagnosis, though treatment should not be withheld if clinical suspicion is high before day 5.',
      normalized_claim: 'Fever >=5 days is the cardinal requirement for KD diagnosis.',
      direction: 'above',
      provenance: { section: 'Diagnosis', page_or_location: 'Section 2.1' },
    },
    {
      threshold_id: 'PACK.AHA.KAWA.2017.T.02',
      display_id: 'AHA-KAWA-T2',
      parameter: 'Coronary artery z-score for aneurysm classification',
      value: '2.5',
      clinical_meaning: 'Z-score >=2.5 defines coronary artery dilation. Small aneurysm: z-score 2.5-5; medium: 5-10; giant: >=10 or >=8mm absolute.',
      normalized_claim: 'Coronary artery z-score >=2.5 defines dilation; >=10 or >=8mm absolute defines giant aneurysm.',
      direction: 'above',
      provenance: { section: 'Coronary Classification', page_or_location: 'Section 3.1' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.AHA.KAWA.2017.TX.01',
      display_id: 'AHA-KAWA-TX1',
      action: 'Initial IVIG therapy for Kawasaki disease',
      normalized_claim: 'IVIG 2 g/kg single infusion over 10-12 hours is the primary treatment for acute KD.',
      timing: 'Within first 10 days of illness, ideally by day 7',
      condition: 'Classic or incomplete Kawasaki disease diagnosed',
      drug_details: { drug: 'IVIG', dose: '2 g/kg', route: 'IV infusion', duration: '10-12 hours' },
      contraindications: ['Severe IgA deficiency'],
      provenance: { section: 'Treatment', page_or_location: 'Section 4.1' },
    },
    {
      step_id: 'PACK.AHA.KAWA.2017.TX.02',
      display_id: 'AHA-KAWA-TX2',
      action: 'High-dose aspirin during acute phase',
      normalized_claim: 'High-dose aspirin 80-100 mg/kg/day in 4 divided doses until afebrile for 48-72 hours.',
      timing: 'Begin at diagnosis, continue until afebrile 48-72h',
      condition: 'Acute febrile phase of Kawasaki disease',
      drug_details: { drug: 'Aspirin', dose: '80-100 mg/kg/day', route: 'PO divided QID' },
      escalation: 'Transition to low-dose aspirin (3-5 mg/kg/day) once afebrile',
      provenance: { section: 'Aspirin Therapy', page_or_location: 'Section 4.2' },
    },
    {
      step_id: 'PACK.AHA.KAWA.2017.TX.03',
      display_id: 'AHA-KAWA-TX3',
      action: 'Low-dose aspirin for convalescent phase',
      normalized_claim: 'Low-dose aspirin 3-5 mg/kg/day for 6-8 weeks if no coronary abnormalities; indefinitely if aneurysms present.',
      timing: 'After fever resolution through 6-8 weeks (or indefinitely)',
      condition: 'Convalescent phase after acute treatment',
      drug_details: { drug: 'Aspirin', dose: '3-5 mg/kg/day', route: 'PO daily' },
      provenance: { section: 'Aspirin Therapy', page_or_location: 'Section 4.2' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.AHA.KAWA.2017.RF.01',
      display_id: 'AHA-KAWA-RF1',
      finding: 'Giant coronary artery aneurysm (z-score >=10 or absolute >=8mm) on echocardiography',
      implication: 'Highest risk for thrombosis, stenosis, and myocardial infarction. Lifelong cardiology follow-up required.',
      action: 'Anticoagulation (warfarin or LMWH) plus low-dose aspirin. Cardiology consultation. Restrict contact sports.',
      urgency: 'urgent',
      provenance: { section: 'Coronary Complications', page_or_location: 'Section 5.2' },
    },
    {
      flag_id: 'PACK.AHA.KAWA.2017.RF.02',
      display_id: 'AHA-KAWA-RF2',
      finding: 'Kawasaki disease shock syndrome: hypotension, hemodynamic instability during acute KD',
      implication: 'More severe systemic inflammation. Higher risk of coronary abnormalities and IVIG resistance.',
      action: 'ICU admission, fluid resuscitation, vasopressors if needed, urgent IVIG and aspirin.',
      urgency: 'immediate',
      provenance: { section: 'Severe Manifestations', page_or_location: 'Section 6.1' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.AHA.KAWA.2017.SEV.01',
      display_id: 'AHA-KAWA-SEV1',
      level: 'Uncomplicated Kawasaki disease',
      criteria: [
        'Meets classic or incomplete KD criteria',
        'Responds to initial IVIG (afebrile within 36 hours)',
        'No coronary artery abnormalities on serial echocardiography',
        'Normal ventricular function',
      ],
      management_implications:
        'Standard IVIG + aspirin protocol. Low-dose aspirin for 6-8 weeks. Echocardiography at diagnosis, 2 weeks, and 6-8 weeks. No long-term cardiac follow-up needed if echo remains normal.',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 5.3' },
    },
    {
      severity_id: 'PACK.AHA.KAWA.2017.SEV.02',
      display_id: 'AHA-KAWA-SEV2',
      level: 'KD with coronary artery aneurysm',
      criteria: [
        'Coronary artery z-score >=2.5 on echocardiography',
        'May be IVIG-responsive or refractory',
        'Small (z 2.5-5), medium (z 5-10), or giant (z >=10) aneurysm',
      ],
      management_implications:
        'Indefinite low-dose aspirin. Add anticoagulation for medium-giant aneurysms. Serial imaging (echo, CT angiography, or MRA). Activity restriction for giant aneurysms. Lifelong cardiology follow-up.',
      provenance: { section: 'Coronary Complications', page_or_location: 'Section 5.2' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Pediatrics pack for Kawasaki disease. Covers classic/incomplete diagnosis, IVIG/aspirin treatment, coronary artery surveillance, and severity stratification.',

  all_item_ids: [
    'PACK.AHA.KAWA.2017.REC.01', 'PACK.AHA.KAWA.2017.REC.02', 'PACK.AHA.KAWA.2017.REC.03',
    'PACK.AHA.KAWA.2017.REC.04', 'PACK.AHA.KAWA.2017.DC.01', 'PACK.AHA.KAWA.2017.DC.02',
    'PACK.AHA.KAWA.2017.T.01', 'PACK.AHA.KAWA.2017.T.02',
    'PACK.AHA.KAWA.2017.TX.01', 'PACK.AHA.KAWA.2017.TX.02', 'PACK.AHA.KAWA.2017.TX.03',
    'PACK.AHA.KAWA.2017.RF.01', 'PACK.AHA.KAWA.2017.RF.02',
    'PACK.AHA.KAWA.2017.SEV.01', 'PACK.AHA.KAWA.2017.SEV.02',
  ],
  all_display_ids: [
    'AHA-KAWA-R1', 'AHA-KAWA-R2', 'AHA-KAWA-R3', 'AHA-KAWA-R4',
    'AHA-KAWA-DC1', 'AHA-KAWA-DC2',
    'AHA-KAWA-T1', 'AHA-KAWA-T2',
    'AHA-KAWA-TX1', 'AHA-KAWA-TX2', 'AHA-KAWA-TX3',
    'AHA-KAWA-RF1', 'AHA-KAWA-RF2',
    'AHA-KAWA-SEV1', 'AHA-KAWA-SEV2',
  ],
};
