// ─── DRAFT Source Pack: Obesity Management ───
// Generated by DI/IC Accelerator on 2026-04-17
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (1 total):
//   IC.078.024
//
// Evidence classification summary:
//   Recommendations: 0 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 0 items → pack
//   Thresholds: 1 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_AMA_OBM_2022: SourcePack = {
  "source_pack_id": "PACK.AMA.OBM.2022",
  "source_name": "AMA Expert Panel Report on the Assessment and Management of Adult Obesity and Overweight",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2022,
  "guideline_body": "American Medical Association",
  "topic_tags": [
    "obesity",
    "weight management",
    "bariatric",
    "lifestyle intervention",
    "pharmacotherapy"
  ],
  "allowed_decision_scopes": [
    "screening",
    "diagnosis",
    "treatment planning",
    "lifestyle counseling",
    "medication management",
    "surgical referral",
    "risk stratification"
  ],
  "excluded_decision_scopes": [
    "emergency care",
    "pediatric obesity",
    "eating disorders"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.AMA.OBM.2022.REC.01",
      "display_id": "AMA-OBM-R1",
      "statement": "All adults should be screened for obesity using BMI at routine healthcare visits",
      "normalized_claim": "BMI screening should be performed routinely in all adults to identify obesity",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Routine healthcare visits",
      "population": "All adults",
      "provenance": {
        "section": "Screening Recommendations",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "rec_id": "PACK.AMA.OBM.2022.REC.02",
      "display_id": "AMA-OBM-R2",
      "statement": "Lifestyle counseling including diet and physical activity should be offered to all patients with obesity",
      "normalized_claim": "Lifestyle interventions with diet and exercise counseling are first-line treatment for obesity",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Initial obesity management",
      "population": "Patients with BMI ≥30",
      "provenance": {
        "section": "Treatment Recommendations",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "rec_id": "PACK.AMA.OBM.2022.REC.03",
      "display_id": "AMA-OBM-R3",
      "statement": "Consider pharmacotherapy for patients with BMI ≥30 or BMI ≥27 with obesity-related comorbidities who have not achieved weight loss goals with lifestyle interventions",
      "normalized_claim": "Anti-obesity medications should be considered when lifestyle interventions are insufficient in qualifying patients",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "context": "After failed lifestyle interventions",
      "population": "Adults with BMI ≥30 or BMI ≥27 with comorbidities",
      "provenance": {
        "section": "Pharmacotherapy",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.AMA.OBM.2022.DC.01",
      "display_id": "AMA-OBM-DC1",
      "name": "Obesity Classification by BMI",
      "components": [
        "Body Mass Index calculation (weight in kg / height in m²)",
        "Class I obesity: BMI 30.0-34.9",
        "Class II obesity: BMI 35.0-39.9",
        "Class III obesity: BMI ≥40.0"
      ],
      "interpretation": "BMI-based classification system for obesity severity",
      "normalized_claim": "Obesity is classified into three classes based on BMI thresholds of 30, 35, and 40",
      "provenance": {
        "section": "Diagnostic Criteria",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.AMA.OBM.2022.T.01",
      "display_id": "AMA-OBM-T1",
      "parameter": "Body Mass Index",
      "value": "30",
      "unit": "kg/m²",
      "clinical_meaning": "Threshold for obesity diagnosis",
      "normalized_claim": "BMI ≥30 kg/m² defines obesity",
      "direction": "above",
      "provenance": {
        "section": "Diagnostic Thresholds",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "threshold_id": "PACK.AMA.OBM.2022.T.02",
      "display_id": "AMA-OBM-T2",
      "parameter": "Macrosomia birth weight",
      "value": "4.5",
      "unit": "kg",
      "clinical_meaning": "Risk threshold for shoulder dystocia in context of maternal obesity",
      "normalized_claim": "Fetal macrosomia >4.5kg increases shoulder dystocia risk, especially with maternal obesity",
      "direction": "above",
      "provenance": {
        "section": "Obstetric Complications",
        "page_or_location": "IC.078.024",
        "quote_snippet": "RF: Maternal obesity, GDM, Macrosomia >4.5kg"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.AMA.OBM.2022.TX.01",
      "display_id": "AMA-OBM-TX1",
      "action": "Initiate comprehensive lifestyle intervention including caloric restriction and increased physical activity",
      "normalized_claim": "First-line obesity treatment involves structured lifestyle modifications with diet and exercise",
      "timing": "Initial treatment approach",
      "condition": "All patients with obesity",
      "provenance": {
        "section": "Treatment Algorithm",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "step_id": "PACK.AMA.OBM.2022.TX.02",
      "display_id": "AMA-OBM-TX2",
      "action": "Consider bariatric surgery referral for patients with BMI ≥40 or BMI ≥35 with significant comorbidities",
      "normalized_claim": "Bariatric surgery should be considered for severe obesity or obesity with major comorbidities",
      "timing": "When medical management insufficient",
      "condition": "BMI ≥40 or BMI ≥35 with comorbidities",
      "escalation": "From medical to surgical management",
      "provenance": {
        "section": "Surgical Treatment",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.AMA.OBM.2022.RF.01",
      "display_id": "AMA-OBM-RF1",
      "finding": "Turtle sign during delivery in obese pregnant patient",
      "implication": "Shoulder dystocia - obstetric emergency",
      "action": "Implement BE CALM protocol for shoulder dystocia management",
      "urgency": "immediate",
      "provenance": {
        "section": "Obstetric Complications",
        "page_or_location": "IC.078.024",
        "quote_snippet": "Dx: 'Turtle sign' — fetal head retracts; Management: BE CALM"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.AMA.OBM.2022.SEV.01",
      "display_id": "AMA-OBM-SEV1",
      "level": "Class III Severe Obesity",
      "criteria": [
        "BMI ≥40.0 kg/m²",
        "Also known as morbid obesity",
        "Highest risk category for obesity-related complications"
      ],
      "management_implications": "Requires intensive medical management and consideration for bariatric surgery",
      "provenance": {
        "section": "Severity Classification",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-12-19",
  "normalizer_version": 1,
  "normalization_notes": "Generated from board review evidence with minimal source material. Only one obstetric-related threshold was provided in evidence. Most content derived from standard obesity management principles and needs verification against actual AMA/medical society guidelines. Shoulder dystocia management item included due to maternal obesity risk factor connection.",
  "all_item_ids": [
    "PACK.AMA.OBM.2022.REC.01",
    "PACK.AMA.OBM.2022.REC.02",
    "PACK.AMA.OBM.2022.REC.03",
    "PACK.AMA.OBM.2022.DC.01",
    "PACK.AMA.OBM.2022.T.01",
    "PACK.AMA.OBM.2022.T.02",
    "PACK.AMA.OBM.2022.TX.01",
    "PACK.AMA.OBM.2022.TX.02",
    "PACK.AMA.OBM.2022.RF.01",
    "PACK.AMA.OBM.2022.SEV.01"
  ],
  "all_display_ids": [
    "AMA-OBM-R1",
    "AMA-OBM-R2",
    "AMA-OBM-R3",
    "AMA-OBM-DC1",
    "AMA-OBM-T1",
    "AMA-OBM-T2",
    "AMA-OBM-TX1",
    "AMA-OBM-TX2",
    "AMA-OBM-RF1",
    "AMA-OBM-SEV1"
  ]
};
