import type { SourcePack } from './types';

export const PACK_ASCO_TLS_2015: SourcePack = {
  source_pack_id: 'PACK.ASCO.TLS.2015',
  source_name: 'ASCO 2015 Expert Panel Recommendations for Tumor Lysis Syndrome Prevention and Treatment',
  source_registry_id: 'REG.ASCO.TLS',
  canonical_url: 'https://doi.org/10.1200/JCO.2015.61.5898',
  publication_year: 2015,
  guideline_body: 'ASCO',

  topic_tags: ['Tumor Lysis Syndrome', 'Oncologic Emergency', 'Hyperuricemia', 'Rasburicase', 'Hematology-Oncology'],
  allowed_decision_scopes: [
    'TLS risk stratification',
    'TLS prophylaxis (fluids, allopurinol, rasburicase)',
    'Cairo-Bishop criteria for lab and clinical TLS',
    'TLS electrolyte management',
    'rasburicase indications and contraindications',
    'hyperuricemia treatment in malignancy',
  ],
  excluded_decision_scopes: [
    'chemotherapy regimen selection',
    'tumor-specific treatment protocols',
    'chronic gout management',
    'renal replacement therapy specifics',
    'palliative care decisions',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ASCO.TLS.2015.REC.01',
      display_id: 'ASCO-TLS-R1',
      statement: 'All patients at risk for TLS should receive aggressive IV hydration (2-3 L/m2/day) beginning 24-48 hours before initiation of cytotoxic therapy, with close monitoring of fluid balance.',
      normalized_claim: 'TLS prophylaxis: aggressive IV hydration 2-3 L/m2/day starting 24-48h pre-chemo. Maintain urine output >2 mL/kg/hr.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Prevention of TLS', page_or_location: 'Section 3.1' },
    },
    {
      rec_id: 'PACK.ASCO.TLS.2015.REC.02',
      display_id: 'ASCO-TLS-R2',
      statement: 'Allopurinol is recommended for intermediate-risk patients to prevent uric acid formation. Begin 1-2 days before chemotherapy and continue for 10-14 days or until tumor burden is reduced.',
      normalized_claim: 'Allopurinol for intermediate-risk TLS prophylaxis. Start 1-2 days pre-chemo. Blocks new uric acid production but does not reduce existing levels.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Xanthine Oxidase Inhibition', page_or_location: 'Section 3.2' },
    },
    {
      rec_id: 'PACK.ASCO.TLS.2015.REC.03',
      display_id: 'ASCO-TLS-R3',
      statement: 'Rasburicase is recommended for high-risk patients or those with established hyperuricemia. It rapidly converts uric acid to allantoin (soluble metabolite). Contraindicated in G6PD deficiency.',
      normalized_claim: 'Rasburicase for high-risk TLS or existing hyperuricemia. Rapidly lowers uric acid. Absolutely contraindicated in G6PD deficiency (causes hemolytic anemia and methemoglobinemia).',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Rasburicase', page_or_location: 'Section 3.3' },
    },
    {
      rec_id: 'PACK.ASCO.TLS.2015.REC.04',
      display_id: 'ASCO-TLS-R4',
      statement: 'Urinary alkalinization is no longer recommended for TLS prevention. It may paradoxically increase calcium phosphate precipitation in renal tubules and does not improve outcomes.',
      normalized_claim: 'Do NOT alkalinize urine for TLS. Increases calcium phosphate deposition risk without benefit.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Alkalinization', page_or_location: 'Section 3.4' },
    },
    {
      rec_id: 'PACK.ASCO.TLS.2015.REC.05',
      display_id: 'ASCO-TLS-R5',
      statement: 'Monitor labs (uric acid, potassium, phosphorus, calcium, creatinine, LDH) every 6-8 hours for 48-72 hours after initiation of chemotherapy in high-risk patients.',
      normalized_claim: 'High-risk TLS: monitor uric acid, K, PO4, Ca, Cr, LDH every 6-8 hours for 48-72 hours post-chemo initiation.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Monitoring', page_or_location: 'Section 4.1' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ASCO.TLS.2015.DC.01',
      display_id: 'ASCO-TLS-DC1',
      name: 'Cairo-Bishop Laboratory TLS Criteria',
      components: [
        'Uric acid >=8 mg/dL or 25% increase from baseline',
        'Potassium >=6.0 mEq/L or 25% increase from baseline',
        'Phosphorus >=4.5 mg/dL (adults) or >=6.5 mg/dL (children), or 25% increase from baseline',
        'Calcium <=7.0 mg/dL or 25% decrease from baseline',
      ],
      threshold: 'Two or more lab criteria within 3 days before or 7 days after chemotherapy',
      interpretation: 'Laboratory TLS requires >=2 of the above criteria. Can occur spontaneously before treatment in high-tumor-burden malignancies.',
      normalized_claim: 'Lab TLS (Cairo-Bishop): >=2 of uric acid >=8, K >=6, PO4 >=4.5, Ca <=7 within 3 days pre- to 7 days post-chemo.',
      provenance: { section: 'TLS Diagnosis', page_or_location: 'Section 2.1, Table 1' },
    },
    {
      criterion_id: 'PACK.ASCO.TLS.2015.DC.02',
      display_id: 'ASCO-TLS-DC2',
      name: 'Cairo-Bishop Clinical TLS Criteria',
      components: [
        'Laboratory TLS (>=2 lab criteria met)',
        'Plus one or more clinical manifestations:',
        'Renal insufficiency: creatinine >=1.5x ULN (age-adjusted)',
        'Cardiac arrhythmia or sudden death',
        'Seizure',
      ],
      interpretation: 'Clinical TLS = lab TLS + end-organ damage (renal failure, arrhythmia, or seizure). Carries significantly higher mortality than lab TLS alone.',
      normalized_claim: 'Clinical TLS = lab TLS + organ damage (AKI, arrhythmia, or seizure). Higher mortality than lab TLS alone.',
      provenance: { section: 'TLS Classification', page_or_location: 'Section 2.2' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ASCO.TLS.2015.T.01',
      display_id: 'ASCO-TLS-T1',
      parameter: 'Uric acid',
      value: '8',
      unit: 'mg/dL',
      clinical_meaning: 'Uric acid >=8 mg/dL is one criterion for laboratory TLS. Elevated uric acid precipitates in renal tubules causing acute uric acid nephropathy.',
      normalized_claim: 'Uric acid >=8 mg/dL in TLS causes uric acid nephropathy via intratubular crystal deposition.',
      direction: 'above',
      provenance: { section: 'Cairo-Bishop Criteria', page_or_location: 'Section 2.1' },
    },
    {
      threshold_id: 'PACK.ASCO.TLS.2015.T.02',
      display_id: 'ASCO-TLS-T2',
      parameter: 'Potassium',
      value: '6.0',
      unit: 'mEq/L',
      clinical_meaning: 'K >=6.0 mEq/L in TLS is an oncologic emergency due to risk of fatal cardiac arrhythmia. Requires immediate treatment (calcium gluconate, insulin/glucose, kayexalate, and possibly emergent dialysis).',
      normalized_claim: 'K >=6.0 mEq/L in TLS requires emergent treatment (cardiac monitoring, calcium gluconate, insulin/dextrose, consider dialysis).',
      direction: 'above',
      provenance: { section: 'Hyperkalemia in TLS', page_or_location: 'Section 5.1' },
    },
    {
      threshold_id: 'PACK.ASCO.TLS.2015.T.03',
      display_id: 'ASCO-TLS-T3',
      parameter: 'Calcium (ionized or corrected)',
      value: '7.0',
      unit: 'mg/dL',
      clinical_meaning: 'Calcium <=7.0 mg/dL in TLS results from hyperphosphatemia-driven calcium phosphate precipitation. Symptomatic hypocalcemia (tetany, QT prolongation) requires cautious IV calcium only if symptomatic — aggressive calcium repletion worsens tissue calcification.',
      normalized_claim: 'TLS hypocalcemia (Ca <=7): secondary to hyperphosphatemia. Treat with IV calcium ONLY if symptomatic (seizure, arrhythmia). Aggressive repletion worsens metastatic calcification.',
      direction: 'below',
      provenance: { section: 'Hypocalcemia in TLS', page_or_location: 'Section 5.3' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ASCO.TLS.2015.TX.01',
      display_id: 'ASCO-TLS-TX1',
      action: 'TLS prophylaxis: Aggressive IV hydration',
      normalized_claim: 'IV NS or D5 1/2NS at 2-3 L/m2/day starting 24-48h before chemo. Goal urine output >2 mL/kg/hr. Avoid potassium and phosphorus in IV fluids.',
      timing: '24-48 hours before chemotherapy',
      condition: 'All patients at intermediate or high risk for TLS',
      contraindications: ['Severe heart failure (modify rate with close monitoring)', 'Oliguria/anuria (consider early dialysis)'],
      provenance: { section: 'Hydration', page_or_location: 'Section 3.1' },
    },
    {
      step_id: 'PACK.ASCO.TLS.2015.TX.02',
      display_id: 'ASCO-TLS-TX2',
      action: 'Intermediate-risk TLS: Allopurinol prophylaxis',
      normalized_claim: 'Allopurinol 300mg/day (adults) or 10mg/kg/day (children) starting 1-2 days before chemo. Reduce dose for renal impairment. Blocks xanthine oxidase (prevents new uric acid formation).',
      timing: '1-2 days before chemotherapy initiation',
      condition: 'Intermediate-risk TLS (e.g., AML, DLBCL with elevated LDH)',
      drug_details: { drug: 'Allopurinol', dose: '300mg/day (adults)', route: 'PO', duration: '10-14 days' },
      contraindications: ['Do not combine with 6-mercaptopurine or azathioprine (allopurinol inhibits their metabolism, causing severe myelosuppression)'],
      provenance: { section: 'Allopurinol', page_or_location: 'Section 3.2' },
    },
    {
      step_id: 'PACK.ASCO.TLS.2015.TX.03',
      display_id: 'ASCO-TLS-TX3',
      action: 'High-risk TLS: Rasburicase prophylaxis or treatment',
      normalized_claim: 'Rasburicase 0.2 mg/kg IV single dose (may repeat if needed). Rapidly lowers uric acid within 4 hours. Must check G6PD status before administration.',
      timing: 'Before chemotherapy initiation for prophylaxis; immediately for established TLS with hyperuricemia',
      condition: 'High-risk TLS (ALL, Burkitt lymphoma, high WBC, bulky disease) or established hyperuricemia',
      drug_details: { drug: 'Rasburicase', dose: '0.2 mg/kg', route: 'IV single dose' },
      contraindications: ['G6PD deficiency (causes hemolytic anemia and methemoglobinemia)', 'Pregnancy'],
      provenance: { section: 'Rasburicase', page_or_location: 'Section 3.3' },
    },
    {
      step_id: 'PACK.ASCO.TLS.2015.TX.04',
      display_id: 'ASCO-TLS-TX4',
      action: 'Established TLS: Emergent electrolyte management and renal replacement therapy',
      normalized_claim: 'Established TLS with AKI or refractory electrolyte derangements: emergent hemodialysis. Continuous renal replacement therapy (CRRT) preferred for hemodynamically unstable patients.',
      timing: 'Immediately upon recognition of clinical TLS',
      condition: 'Clinical TLS with renal failure, refractory hyperkalemia, or symptomatic hypocalcemia',
      escalation: 'If dialysis not immediately available, temporize hyperkalemia with IV calcium gluconate, insulin/glucose, and kayexalate.',
      provenance: { section: 'TLS Treatment', page_or_location: 'Section 5.4' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ASCO.TLS.2015.RF.01',
      display_id: 'ASCO-TLS-RF1',
      finding: 'Spontaneous TLS: Lab abnormalities consistent with TLS appearing before any chemotherapy initiation',
      implication: 'Indicates extremely high tumor burden with rapid cell turnover. Most common in Burkitt lymphoma, T-ALL, and high-WBC AML. Requires aggressive treatment before any chemotherapy can begin safely.',
      action: 'Aggressive hydration, rasburicase, correct electrolytes, establish dialysis access. Delay chemotherapy until metabolic control achieved.',
      urgency: 'immediate',
      provenance: { section: 'Spontaneous TLS', page_or_location: 'Section 2.3' },
    },
    {
      flag_id: 'PACK.ASCO.TLS.2015.RF.02',
      display_id: 'ASCO-TLS-RF2',
      finding: 'Hyperkalemia with ECG changes (peaked T waves, widened QRS, sine wave) in setting of TLS',
      implication: 'Imminent risk of ventricular fibrillation and cardiac arrest. Most acutely life-threatening electrolyte abnormality in TLS.',
      action: 'IV calcium gluconate (cardiac membrane stabilization), insulin + dextrose, kayexalate, emergent dialysis if refractory. Continuous cardiac monitoring.',
      urgency: 'immediate',
      provenance: { section: 'Hyperkalemia Emergency', page_or_location: 'Section 5.1' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ASCO.TLS.2015.SEV.01',
      display_id: 'ASCO-TLS-SEV1',
      level: 'High-risk for TLS',
      criteria: [
        'Burkitt lymphoma or Burkitt-like lymphoma',
        'Acute lymphoblastic leukemia (ALL) with WBC >100,000',
        'AML with WBC >100,000',
        'DLBCL with bulky disease and elevated LDH',
        'Baseline uric acid >=8 mg/dL or LDH >2x ULN',
        'Pre-existing renal insufficiency with any hematologic malignancy',
      ],
      management_implications:
        'Rasburicase prophylaxis (not allopurinol). Aggressive IV hydration 2-3 L/m2/day. ICU-level monitoring. Labs every 6 hours for 48-72 hours. Establish dialysis access prophylactically. Consider reduced-intensity initial chemotherapy dosing.',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 1.2' },
    },
    {
      severity_id: 'PACK.ASCO.TLS.2015.SEV.02',
      display_id: 'ASCO-TLS-SEV2',
      level: 'Intermediate-risk for TLS',
      criteria: [
        'AML with WBC 25,000-100,000',
        'ALL with WBC <100,000',
        'DLBCL with elevated LDH but non-bulky',
        'CLL treated with targeted agents (venetoclax)',
        'Other aggressive lymphomas with high tumor burden',
      ],
      management_implications:
        'Allopurinol prophylaxis + aggressive IV hydration. Labs every 8-12 hours for 48-72 hours. Rasburicase if uric acid rises despite allopurinol. Floor-level monitoring acceptable if labs stable.',
      provenance: { section: 'Risk Stratification', page_or_location: 'Section 1.2' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Pack for TLS prevention and treatment. Covers Cairo-Bishop criteria, risk stratification, hydration, allopurinol vs rasburicase, G6PD contraindication, and electrolyte emergencies.',

  all_item_ids: [
    'PACK.ASCO.TLS.2015.REC.01', 'PACK.ASCO.TLS.2015.REC.02', 'PACK.ASCO.TLS.2015.REC.03',
    'PACK.ASCO.TLS.2015.REC.04', 'PACK.ASCO.TLS.2015.REC.05',
    'PACK.ASCO.TLS.2015.DC.01', 'PACK.ASCO.TLS.2015.DC.02',
    'PACK.ASCO.TLS.2015.T.01', 'PACK.ASCO.TLS.2015.T.02', 'PACK.ASCO.TLS.2015.T.03',
    'PACK.ASCO.TLS.2015.TX.01', 'PACK.ASCO.TLS.2015.TX.02', 'PACK.ASCO.TLS.2015.TX.03',
    'PACK.ASCO.TLS.2015.TX.04',
    'PACK.ASCO.TLS.2015.RF.01', 'PACK.ASCO.TLS.2015.RF.02',
    'PACK.ASCO.TLS.2015.SEV.01', 'PACK.ASCO.TLS.2015.SEV.02',
  ],
  all_display_ids: [
    'ASCO-TLS-R1', 'ASCO-TLS-R2', 'ASCO-TLS-R3', 'ASCO-TLS-R4', 'ASCO-TLS-R5',
    'ASCO-TLS-DC1', 'ASCO-TLS-DC2',
    'ASCO-TLS-T1', 'ASCO-TLS-T2', 'ASCO-TLS-T3',
    'ASCO-TLS-TX1', 'ASCO-TLS-TX2', 'ASCO-TLS-TX3', 'ASCO-TLS-TX4',
    'ASCO-TLS-RF1', 'ASCO-TLS-RF2',
    'ASCO-TLS-SEV1', 'ASCO-TLS-SEV2',
  ],
};
