import type { SourcePack } from './types';

export const PACK_ASH_TTP_2020: SourcePack = {
  source_pack_id: 'PACK.ASH.TTP.2020',
  source_name: 'ASH/ISTH 2020 Guidelines for Thrombotic Microangiopathies and Heparin-Induced Thrombocytopenia',
  source_registry_id: 'REG.ASH.TTP',
  canonical_url: 'https://doi.org/10.1182/bloodadvances.2020002032',
  publication_year: 2020,
  guideline_body: 'ASH/ISTH',

  topic_tags: ['TTP', 'HUS', 'aHUS', 'HIT', 'DIC', 'Thrombotic Microangiopathy', 'Hematology'],
  allowed_decision_scopes: [
    'TTP diagnosis and initial management',
    'plasma exchange initiation',
    'ADAMTS13 testing and interpretation',
    'HUS classification and treatment',
    'aHUS complement-directed therapy',
    'HIT diagnosis and alternative anticoagulation',
    'DIC recognition and supportive care',
    'PLASMIC score interpretation',
    '4T score for HIT',
  ],
  excluded_decision_scopes: [
    'chronic relapsing TTP prophylaxis',
    'pregnancy-associated TMA long-term management',
    'complement genetic testing interpretation',
    'post-transplant TMA',
    'warfarin transition specifics after HIT resolution',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ASH.TTP.2020.REC.01',
      display_id: 'ASH-TTP-R1',
      statement: 'In patients with suspected TTP (thrombocytopenia, MAHA, no alternative explanation), initiate therapeutic plasma exchange (TPE) immediately. Do not delay TPE to await ADAMTS13 results.',
      normalized_claim: 'Suspected TTP: start plasma exchange immediately. Do NOT wait for ADAMTS13 results (mortality without treatment >90%).',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'TTP Management', page_or_location: 'Section 2.1' },
    },
    {
      rec_id: 'PACK.ASH.TTP.2020.REC.02',
      display_id: 'ASH-TTP-R2',
      statement: 'ADAMTS13 activity <10% confirms TTP diagnosis. Caplacizumab (anti-vWF nanobody) is recommended in addition to TPE and immunosuppression for acquired TTP.',
      normalized_claim: 'ADAMTS13 <10% confirms TTP. Treatment triad: plasma exchange + corticosteroids + caplacizumab.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'TTP Diagnosis and Treatment', page_or_location: 'Section 2.2' },
    },
    {
      rec_id: 'PACK.ASH.TTP.2020.REC.03',
      display_id: 'ASH-TTP-R3',
      statement: 'In STEC-HUS (Shiga toxin-producing E. coli), supportive care is the mainstay. Antibiotics should be avoided as they may increase Shiga toxin release and worsen HUS.',
      normalized_claim: 'STEC-HUS: supportive care only. Antibiotics contraindicated (increase toxin release). Plasma exchange not beneficial.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'HUS Management', page_or_location: 'Section 3.1' },
    },
    {
      rec_id: 'PACK.ASH.TTP.2020.REC.04',
      display_id: 'ASH-TTP-R4',
      statement: 'For atypical HUS (complement-mediated), eculizumab (terminal complement inhibitor) is the treatment of choice. Meningococcal vaccination is required before or concurrent with initiation.',
      normalized_claim: 'aHUS: eculizumab (anti-C5). Meningococcal vaccine required. Plasma exchange is bridging therapy only.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'aHUS Management', page_or_location: 'Section 3.2' },
    },
    {
      rec_id: 'PACK.ASH.TTP.2020.REC.05',
      display_id: 'ASH-TTP-R5',
      statement: 'When HIT is suspected (4T score intermediate or high), immediately discontinue all heparin products and initiate a non-heparin anticoagulant (argatroban or bivalirudin). Do not wait for confirmatory testing.',
      normalized_claim: 'Suspected HIT: stop ALL heparin immediately, start argatroban or bivalirudin. Do not wait for HIT antibody/SRA results.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'HIT Management', page_or_location: 'Section 4.1' },
    },
    {
      rec_id: 'PACK.ASH.TTP.2020.REC.06',
      display_id: 'ASH-TTP-R6',
      statement: 'In acute HIT, do NOT give warfarin until platelet count has recovered to >=150,000/mcL. Premature warfarin in HIT causes warfarin-induced skin necrosis and venous limb gangrene.',
      normalized_claim: 'Never give warfarin in acute HIT until platelets >=150K. Risk of venous limb gangrene and skin necrosis.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'HIT Anticoagulation Transition', page_or_location: 'Section 4.2' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ASH.TTP.2020.DC.01',
      display_id: 'ASH-TTP-DC1',
      name: 'PLASMIC Score for TTP',
      components: [
        'Platelet count <30,000 (+1)',
        'Combined hemolysis variables: reticulocyte >2.5%, haptoglobin undetectable, or indirect bilirubin >2 (+1)',
        'No active cancer (+1)',
        'No solid organ or stem cell transplant (+1)',
        'MCV <90 fL (+1)',
        'INR <1.5 (+1)',
        'Creatinine <2.0 mg/dL (+1)',
      ],
      threshold: 'Score >=5: high probability of ADAMTS13 <10% (TTP likely)',
      interpretation: 'PLASMIC >=5 has PPV >90% for severe ADAMTS13 deficiency. Supports empiric TPE initiation while awaiting confirmatory testing.',
      normalized_claim: 'PLASMIC score >=5 = high probability of TTP (ADAMTS13 <10%). Supports empiric plasma exchange.',
      provenance: { section: 'TTP Risk Stratification', page_or_location: 'Section 2.1, Table 2' },
    },
    {
      criterion_id: 'PACK.ASH.TTP.2020.DC.02',
      display_id: 'ASH-TTP-DC2',
      name: '4T Score for Heparin-Induced Thrombocytopenia',
      components: [
        'Thrombocytopenia: degree of platelet fall (0-2 points)',
        'Timing: onset of platelet fall relative to heparin exposure (0-2 points)',
        'Thrombosis: new thrombosis or other sequelae (0-2 points)',
        'Other causes: likelihood of other causes of thrombocytopenia (0-2 points)',
      ],
      threshold: 'Score 0-3: low probability; 4-5: intermediate; 6-8: high probability',
      interpretation: 'Low 4T score (0-3) has >99% NPV for HIT. Intermediate/high scores require HIT antibody testing (ELISA then SRA confirmation).',
      normalized_claim: '4T score: low (0-3) effectively rules out HIT. Intermediate/high (>=4) requires antibody testing and empiric non-heparin anticoagulation.',
      provenance: { section: 'HIT Diagnosis', page_or_location: 'Section 4.1, Table 3' },
    },
    {
      criterion_id: 'PACK.ASH.TTP.2020.DC.03',
      display_id: 'ASH-TTP-DC3',
      name: 'DIC Diagnostic Criteria (ISTH Scoring)',
      components: [
        'Platelet count: >100K (0), 50-100K (+1), <50K (+2)',
        'Fibrin markers (D-dimer): no increase (0), moderate increase (+2), strong increase (+3)',
        'Prolonged PT: <3s (0), 3-6s (+1), >6s (+2)',
        'Fibrinogen: >1g/L (0), <1g/L (+1)',
      ],
      threshold: 'Score >=5: compatible with overt DIC',
      interpretation: 'DIC is always secondary to an underlying condition (sepsis, malignancy, trauma, obstetric emergency). Treat the underlying cause.',
      normalized_claim: 'ISTH DIC score >=5 = overt DIC. DIC is always secondary; treat the underlying cause first.',
      provenance: { section: 'DIC Diagnosis', page_or_location: 'Section 5.1' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ASH.TTP.2020.T.01',
      display_id: 'ASH-TTP-T1',
      parameter: 'ADAMTS13 activity',
      value: '10',
      unit: '%',
      clinical_meaning: 'ADAMTS13 activity <10% is diagnostic of TTP and distinguishes it from other thrombotic microangiopathies. Activity >10% essentially rules out TTP.',
      normalized_claim: 'ADAMTS13 <10% = TTP confirmed. >10% = not TTP (consider HUS, DIC, other TMA).',
      direction: 'below',
      provenance: { section: 'TTP Diagnosis', page_or_location: 'Section 2.2' },
    },
    {
      threshold_id: 'PACK.ASH.TTP.2020.T.02',
      display_id: 'ASH-TTP-T2',
      parameter: 'Platelet recovery threshold for warfarin in HIT',
      value: '150000',
      unit: '/mcL',
      clinical_meaning: 'Warfarin must NOT be started in HIT until platelet count recovers to >=150,000/mcL. Premature warfarin causes protein C depletion, leading to skin necrosis or venous limb gangrene.',
      normalized_claim: 'HIT: warfarin contraindicated until platelets >=150K. Start with overlap of non-heparin anticoagulant.',
      direction: 'above',
      provenance: { section: 'HIT Transition to Warfarin', page_or_location: 'Section 4.2' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ASH.TTP.2020.TX.01',
      display_id: 'ASH-TTP-TX1',
      action: 'TTP: Emergent plasma exchange + corticosteroids',
      normalized_claim: 'TTP treatment: daily TPE (1-1.5 plasma volumes) + methylprednisolone 1g/day x3 then oral prednisone. Continue TPE until platelet >150K x2 days.',
      timing: 'Within hours of clinical suspicion',
      condition: 'Suspected or confirmed TTP (MAHA + thrombocytopenia + no alternative cause)',
      drug_details: { drug: 'Therapeutic plasma exchange + Methylprednisolone', dose: '1-1.5 PV exchange; methylpred 1g IV daily x3', route: 'Apheresis + IV' },
      contraindications: ['Hemodynamic instability precluding apheresis catheter placement'],
      escalation: 'Add caplacizumab 11mg SQ daily if confirmed acquired TTP. Add rituximab for refractory cases.',
      provenance: { section: 'TTP Treatment', page_or_location: 'Section 2.3' },
    },
    {
      step_id: 'PACK.ASH.TTP.2020.TX.02',
      display_id: 'ASH-TTP-TX2',
      action: 'HIT: Non-heparin anticoagulation with argatroban',
      normalized_claim: 'HIT treatment: argatroban IV infusion (0.5-2 mcg/kg/min, titrate to aPTT 1.5-3x baseline). Preferred in hepatic impairment-free patients. Bivalirudin alternative for cardiac surgery/PCI.',
      timing: 'Immediately upon HIT suspicion',
      condition: 'Intermediate or high 4T score with or without thrombosis',
      drug_details: { drug: 'Argatroban', dose: '0.5-2 mcg/kg/min', route: 'IV continuous infusion' },
      contraindications: ['Severe hepatic impairment (use bivalirudin instead)'],
      provenance: { section: 'HIT Anticoagulation', page_or_location: 'Section 4.1' },
    },
    {
      step_id: 'PACK.ASH.TTP.2020.TX.03',
      display_id: 'ASH-TTP-TX3',
      action: 'aHUS: Eculizumab initiation',
      normalized_claim: 'aHUS: eculizumab 900mg IV weekly x4, then 1200mg every 2 weeks. Vaccinate against Neisseria meningitidis before or at time of first dose. Prophylactic antibiotics if unvaccinated.',
      timing: 'As soon as aHUS diagnosis established',
      condition: 'Complement-mediated HUS (aHUS) confirmed or strongly suspected',
      drug_details: { drug: 'Eculizumab', dose: '900mg weekly x4, then 1200mg q2wk', route: 'IV' },
      contraindications: ['Unresolved Neisseria meningitidis infection'],
      provenance: { section: 'aHUS Treatment', page_or_location: 'Section 3.2' },
    },
    {
      step_id: 'PACK.ASH.TTP.2020.TX.04',
      display_id: 'ASH-TTP-TX4',
      action: 'DIC: Treat underlying cause + supportive transfusion',
      normalized_claim: 'DIC treatment: address underlying cause (sepsis, malignancy, trauma). Supportive: platelets if <10K or bleeding, cryoprecipitate if fibrinogen <100 mg/dL, FFP if INR >1.5 with bleeding.',
      timing: 'Concurrent with treatment of underlying cause',
      condition: 'Overt DIC (ISTH score >=5) with active bleeding or high bleeding risk',
      contraindications: ['Do not give anticoagulation for DIC unless thrombosis predominates (purpura fulminans)'],
      provenance: { section: 'DIC Management', page_or_location: 'Section 5.2' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ASH.TTP.2020.RF.01',
      display_id: 'ASH-TTP-RF1',
      finding: 'Pentad of TTP: MAHA + thrombocytopenia + neurologic symptoms + renal dysfunction + fever',
      implication: 'Classic TTP pentad is seen in <10% of cases. Do NOT wait for full pentad. MAHA + thrombocytopenia alone should prompt empiric TPE. Mortality >90% untreated.',
      action: 'Send ADAMTS13, LDH, haptoglobin, peripheral smear. Initiate TPE and corticosteroids immediately.',
      urgency: 'immediate',
      provenance: { section: 'TTP Recognition', page_or_location: 'Section 2.1' },
    },
    {
      flag_id: 'PACK.ASH.TTP.2020.RF.02',
      display_id: 'ASH-TTP-RF2',
      finding: 'Platelet drop >50% on days 5-14 of heparin therapy with or without thrombosis',
      implication: 'Classic timing for HIT. Even without thrombosis, HIT carries 30-50% risk of subsequent thrombotic event if untreated.',
      action: 'Stop all heparin (including flushes and coated catheters). Send HIT antibody (ELISA). Start non-heparin anticoagulant immediately.',
      urgency: 'immediate',
      provenance: { section: 'HIT Recognition', page_or_location: 'Section 4.1' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ASH.TTP.2020.SEV.01',
      display_id: 'ASH-TTP-SEV1',
      level: 'TTP with neurologic involvement',
      criteria: [
        'MAHA with schistocytes on peripheral smear',
        'Severe thrombocytopenia (typically <30,000)',
        'Neurologic symptoms (confusion, seizures, focal deficits, coma)',
        'Elevated LDH, undetectable haptoglobin',
        'ADAMTS13 <10% or PLASMIC >=5',
      ],
      management_implications:
        'ICU admission. Emergent TPE (do not delay). Corticosteroids + caplacizumab. Platelet transfusion relatively contraindicated (may worsen microvascular thrombosis) unless life-threatening hemorrhage. Daily TPE until platelet recovery >150K for 2 consecutive days.',
      provenance: { section: 'Severe TTP', page_or_location: 'Section 2.3' },
    },
    {
      severity_id: 'PACK.ASH.TTP.2020.SEV.02',
      display_id: 'ASH-TTP-SEV2',
      level: 'HIT with thrombosis (HITT)',
      criteria: [
        'Platelet drop >50% from baseline on days 5-14 of heparin',
        'New arterial or venous thrombosis (DVT, PE, limb ischemia, stroke)',
        'Positive HIT antibody (ELISA OD >1.0 or SRA positive)',
      ],
      management_implications:
        'Therapeutic-dose non-heparin anticoagulation (argatroban or bivalirudin). Minimum 3 months anticoagulation for HITT. Transition to warfarin only after platelets >=150K with 5-day overlap. Screen for additional thrombosis (bilateral lower extremity duplex US).',
      provenance: { section: 'HIT with Thrombosis', page_or_location: 'Section 4.2' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Combined pack for TMA (TTP, HUS, aHUS) + HIT + DIC. Covers PLASMIC/4T scoring, TPE for TTP, eculizumab for aHUS, non-heparin anticoagulation for HIT, and DIC supportive care.',

  all_item_ids: [
    'PACK.ASH.TTP.2020.REC.01', 'PACK.ASH.TTP.2020.REC.02', 'PACK.ASH.TTP.2020.REC.03',
    'PACK.ASH.TTP.2020.REC.04', 'PACK.ASH.TTP.2020.REC.05', 'PACK.ASH.TTP.2020.REC.06',
    'PACK.ASH.TTP.2020.DC.01', 'PACK.ASH.TTP.2020.DC.02', 'PACK.ASH.TTP.2020.DC.03',
    'PACK.ASH.TTP.2020.T.01', 'PACK.ASH.TTP.2020.T.02',
    'PACK.ASH.TTP.2020.TX.01', 'PACK.ASH.TTP.2020.TX.02', 'PACK.ASH.TTP.2020.TX.03',
    'PACK.ASH.TTP.2020.TX.04',
    'PACK.ASH.TTP.2020.RF.01', 'PACK.ASH.TTP.2020.RF.02',
    'PACK.ASH.TTP.2020.SEV.01', 'PACK.ASH.TTP.2020.SEV.02',
  ],
  all_display_ids: [
    'ASH-TTP-R1', 'ASH-TTP-R2', 'ASH-TTP-R3', 'ASH-TTP-R4', 'ASH-TTP-R5', 'ASH-TTP-R6',
    'ASH-TTP-DC1', 'ASH-TTP-DC2', 'ASH-TTP-DC3',
    'ASH-TTP-T1', 'ASH-TTP-T2',
    'ASH-TTP-TX1', 'ASH-TTP-TX2', 'ASH-TTP-TX3', 'ASH-TTP-TX4',
    'ASH-TTP-RF1', 'ASH-TTP-RF2',
    'ASH-TTP-SEV1', 'ASH-TTP-SEV2',
  ],
};
