import type { SourcePack } from './types';

export const PACK_ASH_SCD_2020: SourcePack = {
  source_pack_id: 'PACK.ASH.SCD.2020',
  source_name: 'ASH 2020 Guidelines for Sickle Cell Disease',
  source_registry_id: 'REG.ASH.SCD',
  canonical_url: 'https://doi.org/10.1182/bloodadvances.2019001271',
  publication_year: 2020,
  guideline_body: 'ASH',

  topic_tags: ['Sickle Cell Disease', 'Vaso-occlusive Crisis', 'Acute Chest Syndrome', 'Hydroxyurea', 'Hematology'],
  allowed_decision_scopes: [
    'vaso-occlusive crisis management',
    'acute chest syndrome diagnosis and treatment',
    'hydroxyurea initiation and monitoring',
    'stroke prevention in SCD',
    'transfusion therapy in SCD',
    'priapism management',
    'penicillin prophylaxis in SCD',
    'TCD screening indications',
  ],
  excluded_decision_scopes: [
    'hematopoietic stem cell transplant selection',
    'gene therapy for SCD',
    'SCD prenatal genetic counseling',
    'chronic pain management protocols',
    'iron chelation therapy specifics',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ASH.SCD.2020.REC.01',
      display_id: 'ASH-SCD-R1',
      statement: 'Hydroxyurea is recommended for all adults and adolescents with HbSS or HbS-beta0 thalassemia regardless of clinical severity to reduce frequency of vaso-occlusive crises, acute chest syndrome, and need for transfusion.',
      normalized_claim: 'Hydroxyurea recommended for all HbSS/HbS-beta0 adults (increases HbF, reduces VOC and ACS frequency).',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Disease-Modifying Therapy', page_or_location: 'Section 3.1' },
    },
    {
      rec_id: 'PACK.ASH.SCD.2020.REC.02',
      display_id: 'ASH-SCD-R2',
      statement: 'Penicillin V prophylaxis is recommended for all children with SCD from birth through at least age 5 to prevent invasive pneumococcal infection.',
      normalized_claim: 'Penicillin prophylaxis required for SCD children birth through age 5 (pneumococcal sepsis prevention).',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Infection Prevention', page_or_location: 'Section 2.1' },
    },
    {
      rec_id: 'PACK.ASH.SCD.2020.REC.03',
      display_id: 'ASH-SCD-R3',
      statement: 'Transcranial Doppler (TCD) screening is recommended annually for children with SCD ages 2-16 years. Chronic transfusion therapy should be initiated if TCD velocities are abnormal (>=200 cm/s).',
      normalized_claim: 'Annual TCD screening ages 2-16; chronic transfusion if TCD velocity >=200 cm/s to prevent primary stroke.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Stroke Prevention', page_or_location: 'Section 4.1' },
    },
    {
      rec_id: 'PACK.ASH.SCD.2020.REC.04',
      display_id: 'ASH-SCD-R4',
      statement: 'For acute vaso-occlusive crisis, rapid initiation of parenteral opioids is recommended. Pain assessment and first dose of analgesic should occur within 30 minutes of triage.',
      normalized_claim: 'VOC pain management: parenteral opioids within 30 minutes of triage. Do not delay analgesia for workup.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Acute Pain Management', page_or_location: 'Section 5.1' },
    },
    {
      rec_id: 'PACK.ASH.SCD.2020.REC.05',
      display_id: 'ASH-SCD-R5',
      statement: 'Exchange transfusion is recommended over simple transfusion for acute chest syndrome with rapidly progressive disease, severe hypoxemia, or multiorgan failure. Target hemoglobin S <30% and total hemoglobin ~10 g/dL.',
      normalized_claim: 'Exchange transfusion for severe ACS (target HbS <30%, total Hgb ~10). Simple transfusion for mild ACS.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Transfusion Therapy', page_or_location: 'Section 6.2' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ASH.SCD.2020.DC.01',
      display_id: 'ASH-SCD-DC1',
      name: 'Acute Chest Syndrome Diagnostic Criteria',
      components: [
        'New pulmonary infiltrate on chest imaging (not atelectasis alone)',
        'Plus at least one of: fever (>=38.5C), respiratory symptoms (cough, dyspnea, tachypnea), chest pain, hypoxemia',
        'In a patient with known sickle cell disease',
      ],
      interpretation: 'ACS is the leading cause of death in SCD. Requires immediate treatment with transfusion, antibiotics, supplemental O2, and bronchodilators.',
      normalized_claim: 'ACS = new pulmonary infiltrate + fever/respiratory symptoms/hypoxemia in SCD patient. Leading cause of SCD death.',
      provenance: { section: 'Acute Chest Syndrome', page_or_location: 'Section 6.1' },
    },
    {
      criterion_id: 'PACK.ASH.SCD.2020.DC.02',
      display_id: 'ASH-SCD-DC2',
      name: 'SCD Stroke Diagnosis',
      components: [
        'Acute neurologic deficit (hemiparesis, aphasia, seizure, altered consciousness)',
        'In a patient with sickle cell disease',
        'Confirmed by neuroimaging (MRI/MRA preferred, CT if MRI unavailable)',
        'Most commonly ischemic stroke in children, hemorrhagic in adults',
      ],
      interpretation: 'SCD stroke is a medical emergency. Emergent exchange transfusion to reduce HbS <30% while awaiting neurology consultation.',
      normalized_claim: 'SCD stroke: acute neuro deficit + imaging confirmation. Emergent exchange transfusion to HbS <30%.',
      provenance: { section: 'Stroke in SCD', page_or_location: 'Section 4.2' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ASH.SCD.2020.T.01',
      display_id: 'ASH-SCD-T1',
      parameter: 'Transcranial Doppler velocity',
      value: '200',
      unit: 'cm/s',
      clinical_meaning: 'TCD time-averaged mean of maximum velocity >=200 cm/s is abnormal and indicates high stroke risk. Chronic transfusion therapy reduces stroke risk by 90%.',
      normalized_claim: 'TCD velocity >=200 cm/s = abnormal = high stroke risk requiring chronic transfusion therapy.',
      direction: 'above',
      provenance: { section: 'Stroke Prevention', page_or_location: 'Section 4.1' },
    },
    {
      threshold_id: 'PACK.ASH.SCD.2020.T.02',
      display_id: 'ASH-SCD-T2',
      parameter: 'Target hemoglobin S with exchange transfusion',
      value: '30',
      unit: '%',
      clinical_meaning: 'Exchange transfusion target HbS <30% for acute stroke or severe ACS. Maintain total Hgb ~10 g/dL to avoid hyperviscosity.',
      normalized_claim: 'Exchange transfusion target: HbS <30%, total Hgb ~10 g/dL. Avoid over-transfusion (hyperviscosity risk).',
      direction: 'below',
      provenance: { section: 'Transfusion Targets', page_or_location: 'Section 6.2' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ASH.SCD.2020.TX.01',
      display_id: 'ASH-SCD-TX1',
      action: 'Vaso-occlusive crisis: Multimodal analgesia',
      normalized_claim: 'VOC treatment: IV opioids (morphine or hydromorphone) within 30 min + NSAIDs (ketorolac) + IV fluids at maintenance rate. Avoid over-hydration (ACS risk).',
      timing: 'Within 30 minutes of triage',
      condition: 'Acute vaso-occlusive crisis',
      drug_details: { drug: 'Morphine or Hydromorphone', route: 'IV', dose: 'Weight-based, reassess q15-30min' },
      contraindications: ['Meperidine (lowers seizure threshold, avoid in SCD)'],
      provenance: { section: 'Acute Pain Management', page_or_location: 'Section 5.1' },
    },
    {
      step_id: 'PACK.ASH.SCD.2020.TX.02',
      display_id: 'ASH-SCD-TX2',
      action: 'Acute chest syndrome: Multimodal treatment',
      normalized_claim: 'ACS treatment: supplemental O2 (target SpO2 >95%), empiric antibiotics (cephalosporin + macrolide for atypicals), simple or exchange transfusion, incentive spirometry, bronchodilators.',
      timing: 'Immediately upon diagnosis',
      condition: 'Mild to moderate acute chest syndrome',
      drug_details: { drug: 'Ceftriaxone + Azithromycin', route: 'IV + PO/IV' },
      escalation: 'If worsening hypoxemia or multiorgan failure, escalate to exchange transfusion.',
      provenance: { section: 'Acute Chest Syndrome Treatment', page_or_location: 'Section 6.1' },
    },
    {
      step_id: 'PACK.ASH.SCD.2020.TX.03',
      display_id: 'ASH-SCD-TX3',
      action: 'Exchange transfusion for severe ACS or stroke',
      normalized_claim: 'Exchange transfusion (automated or manual) for severe ACS, acute stroke, or multiorgan failure. Target HbS <30%, total Hgb ~10 g/dL.',
      timing: 'Emergent',
      condition: 'Severe ACS with respiratory failure, acute ischemic stroke, or multiorgan failure',
      contraindications: ['Lack of available crossmatched blood (do not delay for extended phenotyping in emergencies)'],
      provenance: { section: 'Transfusion Therapy', page_or_location: 'Section 6.2' },
    },
    {
      step_id: 'PACK.ASH.SCD.2020.TX.04',
      display_id: 'ASH-SCD-TX4',
      action: 'Hydroxyurea initiation and dose titration',
      normalized_claim: 'Start hydroxyurea 15-20 mg/kg/day. Titrate to maximum tolerated dose (target mild myelosuppression: ANC 2000-4000). Monitor CBC every 4-8 weeks during titration.',
      timing: 'Outpatient initiation, chronic therapy',
      condition: 'All adults with HbSS or HbS-beta0 thalassemia',
      drug_details: { drug: 'Hydroxyurea', dose: '15-20 mg/kg/day, titrate to MTD', route: 'PO', duration: 'Indefinite' },
      contraindications: ['Pregnancy (teratogenic)', 'Severe myelosuppression', 'Unwillingness to use contraception'],
      provenance: { section: 'Hydroxyurea', page_or_location: 'Section 3.1' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ASH.SCD.2020.RF.01',
      display_id: 'ASH-SCD-RF1',
      finding: 'Fever >=38.5C in SCD patient: Presume sepsis until proven otherwise due to functional asplenia',
      implication: 'Encapsulated organisms (Streptococcus pneumoniae, Haemophilus influenzae) can cause rapidly fatal sepsis in SCD due to autosplenectomy.',
      action: 'Blood cultures, empiric IV ceftriaxone immediately. Do not delay antibiotics for workup completion.',
      urgency: 'immediate',
      provenance: { section: 'Fever in SCD', page_or_location: 'Section 2.2' },
    },
    {
      flag_id: 'PACK.ASH.SCD.2020.RF.02',
      display_id: 'ASH-SCD-RF2',
      finding: 'Acute splenic sequestration: Rapidly enlarging spleen + acute drop in hemoglobin >=2 g/dL from baseline',
      implication: 'Can progress to hypovolemic shock within hours. More common in children (adults with HbSC may retain spleen).',
      action: 'Immediate IV fluid resuscitation, urgent simple transfusion (target Hgb to baseline, avoid over-transfusion as spleen releases sequestered cells). Splenectomy after stabilization if recurrent.',
      urgency: 'immediate',
      provenance: { section: 'Splenic Sequestration', page_or_location: 'Section 7.1' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ASH.SCD.2020.SEV.01',
      display_id: 'ASH-SCD-SEV1',
      level: 'Severe/life-threatening SCD complications',
      criteria: [
        'Acute chest syndrome with SpO2 <90% or respiratory failure',
        'Acute ischemic or hemorrhagic stroke',
        'Multiorgan failure',
        'Acute splenic sequestration with hemodynamic instability',
        'Aplastic crisis with Hgb <5 g/dL',
      ],
      management_implications:
        'ICU admission. Exchange transfusion (target HbS <30%). Aggressive supportive care. Neurology, hematology, and critical care consultation. These complications carry significant mortality risk.',
      provenance: { section: 'Acute Complications', page_or_location: 'Section 6-7' },
    },
    {
      severity_id: 'PACK.ASH.SCD.2020.SEV.02',
      display_id: 'ASH-SCD-SEV2',
      level: 'Moderate SCD complications',
      criteria: [
        'Uncomplicated vaso-occlusive crisis',
        'Mild ACS (new infiltrate, mild symptoms, SpO2 >92%)',
        'Priapism <4 hours',
        'Fever without hemodynamic instability',
      ],
      management_implications:
        'Inpatient management with IV opioids, IV fluids, incentive spirometry. Simple transfusion if Hgb drops >1 g/dL from baseline or if ACS. Monitor for escalation to severe category.',
      provenance: { section: 'Acute Complications', page_or_location: 'Section 5-6' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Pack for SCD acute and chronic management. Covers VOC, ACS, stroke prevention (TCD), hydroxyurea, exchange transfusion, penicillin prophylaxis, and splenic sequestration.',

  all_item_ids: [
    'PACK.ASH.SCD.2020.REC.01', 'PACK.ASH.SCD.2020.REC.02', 'PACK.ASH.SCD.2020.REC.03',
    'PACK.ASH.SCD.2020.REC.04', 'PACK.ASH.SCD.2020.REC.05',
    'PACK.ASH.SCD.2020.DC.01', 'PACK.ASH.SCD.2020.DC.02',
    'PACK.ASH.SCD.2020.T.01', 'PACK.ASH.SCD.2020.T.02',
    'PACK.ASH.SCD.2020.TX.01', 'PACK.ASH.SCD.2020.TX.02', 'PACK.ASH.SCD.2020.TX.03',
    'PACK.ASH.SCD.2020.TX.04',
    'PACK.ASH.SCD.2020.RF.01', 'PACK.ASH.SCD.2020.RF.02',
    'PACK.ASH.SCD.2020.SEV.01', 'PACK.ASH.SCD.2020.SEV.02',
  ],
  all_display_ids: [
    'ASH-SCD-R1', 'ASH-SCD-R2', 'ASH-SCD-R3', 'ASH-SCD-R4', 'ASH-SCD-R5',
    'ASH-SCD-DC1', 'ASH-SCD-DC2',
    'ASH-SCD-T1', 'ASH-SCD-T2',
    'ASH-SCD-TX1', 'ASH-SCD-TX2', 'ASH-SCD-TX3', 'ASH-SCD-TX4',
    'ASH-SCD-RF1', 'ASH-SCD-RF2',
    'ASH-SCD-SEV1', 'ASH-SCD-SEV2',
  ],
};
