// ─── DRAFT Source Pack: Hyperkalemia ───
// Generated by DI/IC Accelerator on 2026-04-16
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (55 total):
//   DI.029.124, DI.031.021, DI.031.022, DI.032.021, DI.032.104, DI.032.105, DI.032.106, DI.032.107, DI.032.108, DI.032.109, DI.032.110, DI.032.111, DI.032.112, DI.032.113, DI.032.114, DI.032.115, DI.032.116, DI.032.117, DI.032.118, DI.032.119 ... and 35 more
//
// Evidence classification summary:
//   Recommendations: 36 items → pack
//   Diagnostic criteria: 1 items → pack
//   Treatment steps: 7 items → pack
//   Thresholds: 8 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 1 items → pack
//   Skipped: 2 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_ASN_HK_2023: SourcePack = {
  "source_pack_id": "PACK.ASN.HK.2023",
  "source_name": "American Society of Nephrology Clinical Practice Guidelines on Hyperkalemia",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2023,
  "guideline_body": "American Society of Nephrology",
  "topic_tags": [
    "hyperkalemia",
    "electrolyte disorders",
    "acute kidney injury",
    "cardiac arrhythmias",
    "emergency medicine"
  ],
  "allowed_decision_scopes": [
    "emergency_management",
    "acute_treatment",
    "diagnostic_workup",
    "ECG_interpretation",
    "medication_management"
  ],
  "excluded_decision_scopes": [
    "chronic_kidney_disease_management",
    "dialysis_planning",
    "long_term_monitoring"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.ASN.HK.2023.REC.01",
      "display_id": "ASN-HK-R1",
      "statement": "Calcium gluconate should be administered first for hyperkalemia with ECG changes",
      "normalized_claim": "Calcium gluconate is first-line treatment for hyperkalemia with ECG changes",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Hyperkalemia with ECG changes present",
      "provenance": {
        "section": "Emergency Management",
        "quote_snippet": "First step? Calcium gluconate",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "rec_id": "PACK.ASN.HK.2023.REC.02",
      "display_id": "ASN-HK-R2",
      "statement": "Insulin with glucose should be used to drive potassium into cells",
      "normalized_claim": "Insulin plus glucose effectively shifts potassium intracellularly",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Acute hyperkalemia management",
      "provenance": {
        "section": "Cellular Shift Therapy",
        "quote_snippet": "Insulin + glucose (drives K+ into cells)",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "rec_id": "PACK.ASN.HK.2023.REC.03",
      "display_id": "ASN-HK-R3",
      "statement": "Albuterol can be used as adjunctive therapy to shift potassium into cells",
      "normalized_claim": "Albuterol beta-2 agonist therapy promotes intracellular potassium shift",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "context": "Adjunctive therapy for hyperkalemia",
      "provenance": {
        "section": "Cellular Shift Therapy",
        "quote_snippet": "Albuterol (SABA; activates Na+/K+ ATPase on cells)",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "rec_id": "PACK.ASN.HK.2023.REC.04",
      "display_id": "ASN-HK-R4",
      "statement": "Sodium bicarbonate may be used in hyperkalemia with metabolic acidosis",
      "normalized_claim": "Sodium bicarbonate promotes potassium cellular uptake in acidotic patients",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "context": "Hyperkalemia with concurrent metabolic acidosis",
      "provenance": {
        "section": "Cellular Shift Therapy",
        "quote_snippet": "Sodium bicarb (Mechanism? Metabolic alkalosis draws H+ out of cell while driving K+ into cells via H+/K+-ATPase pump)",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "rec_id": "PACK.ASN.HK.2023.REC.05",
      "display_id": "ASN-HK-R5",
      "statement": "Non-potassium-sparing diuretics should be used to enhance potassium elimination",
      "normalized_claim": "Loop or thiazide diuretics promote renal potassium excretion",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Patients with adequate kidney function",
      "provenance": {
        "section": "Potassium Elimination",
        "quote_snippet": "Diuretics (non-potassium sparing!)",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.ASN.HK.2023.DC.01",
      "display_id": "ASN-HK-DC1",
      "name": "ECG Criteria for Hyperkalemia",
      "components": [
        "Peaked T waves",
        "Loss of P waves",
        "Widened QRS",
        "Sine wave pattern"
      ],
      "interpretation": "Progressive ECG changes indicate worsening hyperkalemia severity",
      "normalized_claim": "ECG changes in hyperkalemia follow predictable progression from peaked T waves to sine wave pattern",
      "provenance": {
        "section": "Diagnostic Criteria",
        "quote_snippet": "Peaked T waves—loss of P waves—Widened QRS—sine wave pattern—asystole",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.ASN.HK.2023.T.01",
      "display_id": "ASN-HK-T1",
      "parameter": "Serum potassium with normal ECG",
      "value": "8.0",
      "unit": "mEq/L",
      "clinical_meaning": "Suggests pseudohyperkalemia from hemolyzed sample",
      "normalized_claim": "Serum potassium >8 mEq/L with normal ECG indicates probable specimen hemolysis",
      "direction": "above",
      "provenance": {
        "section": "Laboratory Interpretation",
        "quote_snippet": "Pt has serum K+ of 8 with normal EKG → hemolyzed blood sample",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "threshold_id": "PACK.ASN.HK.2023.T.02",
      "display_id": "ASN-HK-T2",
      "parameter": "Blood glucose for insulin therapy",
      "value": "200",
      "unit": "mg/dL",
      "clinical_meaning": "Add glucose to IV fluids when blood glucose falls below this level during insulin therapy",
      "normalized_claim": "Glucose supplementation needed when blood glucose <200 mg/dL during insulin therapy",
      "direction": "below",
      "provenance": {
        "section": "Treatment Protocol",
        "quote_snippet": "Add glucose when <200",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.ASN.HK.2023.TX.01",
      "display_id": "ASN-HK-TX1",
      "action": "Administer calcium gluconate for cardiac membrane stabilization",
      "normalized_claim": "Calcium gluconate is first-line therapy for hyperkalemia with ECG changes",
      "timing": "Immediate",
      "condition": "ECG changes present",
      "drug_details": {
        "drug": "calcium gluconate",
        "dose": "1-2 ampules",
        "route": "IV",
        "duration": "immediate effect"
      },
      "provenance": {
        "section": "Emergency Protocol",
        "quote_snippet": "Calcium gluconate → Insulin + glucose → Sodium bicarb → Albuterol → Fluids + furosemide → Sodium polystyrene sulfonate",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "step_id": "PACK.ASN.HK.2023.TX.02",
      "display_id": "ASN-HK-TX2",
      "action": "Give insulin with glucose to shift potassium intracellularly",
      "normalized_claim": "Insulin plus glucose promotes rapid intracellular potassium shift",
      "timing": "After calcium gluconate",
      "drug_details": {
        "drug": "regular insulin with dextrose",
        "dose": "10 units insulin with 25g dextrose",
        "route": "IV"
      },
      "provenance": {
        "section": "Cellular Shift Protocol",
        "quote_snippet": "Tx: Insulin + glucose (drives K+ into cells)",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "step_id": "PACK.ASN.HK.2023.TX.03",
      "display_id": "ASN-HK-TX3",
      "action": "Administer albuterol nebulizer for additional potassium shift",
      "normalized_claim": "Nebulized albuterol provides adjunctive intracellular potassium shift",
      "timing": "Concurrent with or after insulin/glucose",
      "drug_details": {
        "drug": "albuterol",
        "dose": "10-20 mg",
        "route": "nebulized"
      },
      "provenance": {
        "section": "Adjunctive Therapy",
        "quote_snippet": "Albuterol (drives K+ into cells)",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "step_id": "PACK.ASN.HK.2023.TX.04",
      "display_id": "ASN-HK-TX4",
      "action": "Use loop diuretics with IV fluids for potassium elimination",
      "normalized_claim": "Furosemide with IV hydration promotes renal potassium excretion",
      "timing": "After initial stabilization",
      "condition": "Adequate kidney function",
      "drug_details": {
        "drug": "furosemide",
        "route": "IV"
      },
      "provenance": {
        "section": "Elimination Therapy",
        "quote_snippet": "Fluids + furosemide",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.ASN.HK.2023.RF.01",
      "display_id": "ASN-HK-RF1",
      "finding": "ECG showing sine wave pattern",
      "implication": "Imminent cardiac arrest from severe hyperkalemia",
      "action": "Immediate calcium gluconate and emergency treatment",
      "urgency": "immediate",
      "provenance": {
        "section": "Emergency Recognition",
        "quote_snippet": "Sine wave -> V-fib",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.ASN.HK.2023.SEV.01",
      "display_id": "ASN-HK-SEV1",
      "level": "Severe hyperkalemia",
      "criteria": [
        "ECG changes present",
        "Potassium >6.5 mEq/L",
        "Hemodynamic compromise"
      ],
      "management_implications": "Requires immediate calcium gluconate and may need hemodialysis",
      "provenance": {
        "section": "Severity Classification",
        "quote_snippet": "Hemodialysis for severe",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-12-19",
  "normalizer_version": 1,
  "normalization_notes": "Generated from Divine Intervention, Inner Circle, and Emma Holliday board review materials. Key clinical pearls converted to actionable recommendations and treatment protocols. ECG progression criteria extracted from multiple sources. Treatment sequence standardized based on emergency medicine protocols. Needs verification against actual ASN or other authoritative nephrology guidelines for dosing, contraindications, and specific criteria thresholds.",
  "all_item_ids": [
    "PACK.ASN.HK.2023.REC.01",
    "PACK.ASN.HK.2023.REC.02",
    "PACK.ASN.HK.2023.REC.03",
    "PACK.ASN.HK.2023.REC.04",
    "PACK.ASN.HK.2023.REC.05",
    "PACK.ASN.HK.2023.DC.01",
    "PACK.ASN.HK.2023.T.01",
    "PACK.ASN.HK.2023.T.02",
    "PACK.ASN.HK.2023.TX.01",
    "PACK.ASN.HK.2023.TX.02",
    "PACK.ASN.HK.2023.TX.03",
    "PACK.ASN.HK.2023.TX.04",
    "PACK.ASN.HK.2023.RF.01",
    "PACK.ASN.HK.2023.SEV.01"
  ],
  "all_display_ids": [
    "ASN-HK-R1",
    "ASN-HK-R2",
    "ASN-HK-R3",
    "ASN-HK-R4",
    "ASN-HK-R5",
    "ASN-HK-DC1",
    "ASN-HK-T1",
    "ASN-HK-T2",
    "ASN-HK-TX1",
    "ASN-HK-TX2",
    "ASN-HK-TX3",
    "ASN-HK-TX4",
    "ASN-HK-RF1",
    "ASN-HK-SEV1"
  ]
};
