import type { SourcePack } from './types';

export const PACK_ATA_THY_2015: SourcePack = {
  source_pack_id: 'PACK.ATA.THY.2015',
  source_name: 'ATA 2015 Guidelines for Diagnosis and Management of Thyroid Disease',
  canonical_url: 'https://doi.org/10.1089/thy.2015.0020',
  publication_year: 2015,
  guideline_body: 'ATA',

  topic_tags: ['Hypothyroidism', 'Hyperthyroidism', 'Graves Disease', 'Thyroid Nodule', 'Thyroid Storm', 'Endocrinology'],
  allowed_decision_scopes: [
    'TSH-based diagnosis of thyroid dysfunction',
    'levothyroxine dosing and TSH targets',
    'antithyroid drug selection (methimazole vs PTU)',
    'radioactive iodine therapy indications',
    'thyroid nodule FNA criteria',
    'Bethesda classification interpretation',
    'thyroid storm recognition and management',
    'Graves disease treatment selection',
  ],
  excluded_decision_scopes: [
    'thyroid cancer staging and treatment',
    'thyroid lymphoma management',
    'medullary thyroid carcinoma genetic testing',
    'pediatric thyroid disease',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ATA.THY.2015.REC.01',
      display_id: 'ATA-THY-R1',
      statement: 'Methimazole is the preferred antithyroid drug for Graves disease in all patients except during the first trimester of pregnancy and in thyroid storm.',
      normalized_claim: 'Methimazole is first-line for Graves hyperthyroidism; PTU reserved for first trimester pregnancy and thyroid storm.',
      strength: 'strong',
      evidence_quality: 'moderate',
      context: 'PTU carries risk of hepatotoxicity; methimazole has better safety profile',
      provenance: { section: 'Hyperthyroidism Treatment', page_or_location: 'Recommendation 4' },
    },
    {
      rec_id: 'PACK.ATA.THY.2015.REC.02',
      display_id: 'ATA-THY-R2',
      statement: 'Levothyroxine is the standard of care for hypothyroidism. The goal TSH should be within the reference range, typically 0.5-2.5 mIU/L for most adults.',
      normalized_claim: 'Levothyroxine monotherapy is standard treatment for hypothyroidism with target TSH 0.5-2.5 mIU/L.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Hypothyroidism Treatment', page_or_location: 'Recommendation 1' },
    },
    {
      rec_id: 'PACK.ATA.THY.2015.REC.03',
      display_id: 'ATA-THY-R3',
      statement: 'FNA biopsy is recommended for thyroid nodules >=1 cm with suspicious sonographic features. Nodules <1 cm should be biopsied only if highly suspicious features or high-risk history.',
      normalized_claim: 'Thyroid nodule FNA indicated for nodules >=1 cm with suspicious US features; <1 cm only if highly suspicious or high-risk patient.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Thyroid Nodule Evaluation', page_or_location: 'Recommendation 8' },
    },
    {
      rec_id: 'PACK.ATA.THY.2015.REC.04',
      display_id: 'ATA-THY-R4',
      statement: 'Beta-blockers should be used in all patients with symptomatic thyrotoxicosis to control adrenergic symptoms (tachycardia, tremor, anxiety) regardless of etiology.',
      normalized_claim: 'Beta-blockers for symptomatic thyrotoxicosis control regardless of cause; propranolol also inhibits T4-to-T3 conversion.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Thyrotoxicosis Management', page_or_location: 'Recommendation 3' },
    },
    {
      rec_id: 'PACK.ATA.THY.2015.REC.05',
      display_id: 'ATA-THY-R5',
      statement: 'Radioactive iodine (RAI) ablation is an appropriate first-line therapy for Graves disease, toxic multinodular goiter, and toxic adenoma. Pregnancy must be excluded.',
      normalized_claim: 'RAI is a first-line option for Graves, toxic MNG, and toxic adenoma; contraindicated in pregnancy.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Radioactive Iodine Therapy', page_or_location: 'Recommendation 5' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ATA.THY.2015.DC.01',
      display_id: 'ATA-THY-DC1',
      name: 'Bethesda System for Thyroid FNA Cytopathology',
      components: [
        'Bethesda I: Nondiagnostic/unsatisfactory — repeat FNA',
        'Bethesda II: Benign — clinical follow-up',
        'Bethesda III: Atypia of undetermined significance (AUS) — repeat FNA or molecular testing',
        'Bethesda IV: Follicular neoplasm/suspicious for follicular neoplasm — diagnostic lobectomy',
        'Bethesda V: Suspicious for malignancy — lobectomy or total thyroidectomy',
        'Bethesda VI: Malignant — total thyroidectomy',
      ],
      interpretation: 'Risk of malignancy increases from Bethesda I (<5%) through Bethesda VI (97-99%). Guides surgical vs observational management.',
      normalized_claim: 'Bethesda classification stratifies thyroid FNA results into 6 categories with increasing malignancy risk, guiding management from observation to surgery.',
      provenance: { section: 'Thyroid Nodule Cytopathology', page_or_location: 'Table 6' },
    },
    {
      criterion_id: 'PACK.ATA.THY.2015.DC.02',
      display_id: 'ATA-THY-DC2',
      name: 'Burch-Wartofsky Point Scale for Thyroid Storm',
      components: [
        'Temperature: 99-99.9F (5pts) to >=104F (30pts)',
        'CNS effects: agitation (10pts) to seizure/coma (30pts)',
        'GI-hepatic: diarrhea/nausea (10pts) to jaundice (20pts)',
        'Heart rate: 100-109 (5pts) to >=140 (25pts)',
        'Heart failure: absent (0pts) to severe (15pts)',
        'Atrial fibrillation: absent (0pts) to present (10pts)',
        'Precipitant: absent (0pts) to present (10pts)',
      ],
      threshold: '>=45 points = thyroid storm; 25-44 = impending storm; <25 = unlikely',
      interpretation: 'Score >=45 confirms thyroid storm requiring aggressive multidrug therapy. Score 25-44 warrants close monitoring and consideration of treatment.',
      normalized_claim: 'Burch-Wartofsky score >=45 diagnoses thyroid storm; 25-44 indicates impending storm requiring urgent evaluation.',
      provenance: { section: 'Thyroid Storm Diagnosis', page_or_location: 'Table 3' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ATA.THY.2015.T.01',
      display_id: 'ATA-THY-T1',
      parameter: 'TSH for hypothyroidism diagnosis',
      value: '4.5',
      unit: 'mIU/L',
      clinical_meaning: 'TSH above upper limit of normal (typically >4.5 mIU/L) with low free T4 confirms primary hypothyroidism. Elevated TSH with normal free T4 = subclinical hypothyroidism.',
      normalized_claim: 'TSH >4.5 mIU/L with low free T4 = overt hypothyroidism; elevated TSH with normal free T4 = subclinical hypothyroidism.',
      direction: 'above',
      provenance: { section: 'Diagnosis of Hypothyroidism', page_or_location: 'Section 2.1' },
    },
    {
      threshold_id: 'PACK.ATA.THY.2015.T.02',
      display_id: 'ATA-THY-T2',
      parameter: 'Thyroid nodule size for FNA',
      value: '1',
      unit: 'cm',
      clinical_meaning: 'Nodules >=1 cm with suspicious US features warrant FNA. Sub-centimeter nodules biopsied only with highly suspicious features or high-risk history (radiation, family history).',
      normalized_claim: 'FNA threshold is >=1 cm for thyroid nodules with suspicious sonographic features.',
      direction: 'above',
      provenance: { section: 'Nodule Evaluation', page_or_location: 'Recommendation 8' },
    },
    {
      threshold_id: 'PACK.ATA.THY.2015.T.03',
      display_id: 'ATA-THY-T3',
      parameter: 'TSH for hyperthyroidism diagnosis',
      value: '0.1',
      unit: 'mIU/L',
      clinical_meaning: 'TSH suppressed below 0.1 mIU/L with elevated free T4 and/or free T3 confirms overt hyperthyroidism.',
      normalized_claim: 'TSH <0.1 mIU/L with elevated free T4/T3 = overt hyperthyroidism.',
      direction: 'below',
      provenance: { section: 'Diagnosis of Hyperthyroidism', page_or_location: 'Section 3.1' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ATA.THY.2015.TX.01',
      display_id: 'ATA-THY-TX1',
      action: 'Graves disease: Start methimazole',
      normalized_claim: 'Methimazole 10-30mg daily is first-line for Graves disease; dose titrated to maintain euthyroidism for 12-18 months.',
      timing: 'At diagnosis of Graves hyperthyroidism',
      condition: 'Graves disease — non-pregnant, not in thyroid storm',
      drug_details: { drug: 'Methimazole', dose: '10-30mg daily', route: 'PO', duration: '12-18 months' },
      contraindications: ['First trimester pregnancy', 'Prior agranulocytosis from thionamide'],
      provenance: { section: 'Antithyroid Drug Therapy', page_or_location: 'Recommendation 4' },
    },
    {
      step_id: 'PACK.ATA.THY.2015.TX.02',
      display_id: 'ATA-THY-TX2',
      action: 'Thyroid storm: Multidrug aggressive therapy',
      normalized_claim: 'Thyroid storm treatment: PTU (loading 500-1000mg then 250mg q4h) + iodine (1h after PTU) + hydrocortisone 300mg IV then 100mg q8h + beta-blocker + cooling.',
      timing: 'Immediately upon diagnosis of thyroid storm',
      condition: 'Thyroid storm (Burch-Wartofsky >=45)',
      drug_details: { drug: 'PTU + Iodine + Hydrocortisone + Beta-blocker', dose: 'PTU 500-1000mg load, then 250mg q4h', route: 'PO/NG for PTU, IV for hydrocortisone' },
      contraindications: ['Iodine before PTU (must give PTU first to block new hormone synthesis)'],
      escalation: 'Plasmapheresis or cholestyramine if refractory',
      provenance: { section: 'Thyroid Storm Management', page_or_location: 'Section 3.5' },
    },
    {
      step_id: 'PACK.ATA.THY.2015.TX.03',
      display_id: 'ATA-THY-TX3',
      action: 'Toxic adenoma/toxic MNG: Radioactive iodine ablation',
      normalized_claim: 'RAI is preferred definitive therapy for toxic adenoma and toxic multinodular goiter; surgery if large goiter with compressive symptoms.',
      timing: 'After confirming diagnosis with radioiodine uptake scan',
      condition: 'Toxic adenoma or toxic multinodular goiter',
      contraindications: ['Pregnancy', 'Breastfeeding', 'Severe Graves ophthalmopathy (relative)'],
      provenance: { section: 'Radioactive Iodine', page_or_location: 'Recommendation 5' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ATA.THY.2015.RF.01',
      display_id: 'ATA-THY-RF1',
      finding: 'Thyroid storm: fever >104F, tachycardia >140, altered mental status, and GI symptoms in a patient with known or suspected hyperthyroidism',
      implication: 'Life-threatening thyrotoxicosis with mortality 10-30% even with treatment. Requires ICU admission.',
      action: 'PTU (not methimazole), iodine 1 hour after PTU, IV hydrocortisone, beta-blocker, cooling measures, ICU admission.',
      urgency: 'immediate',
      provenance: { section: 'Thyroid Storm', page_or_location: 'Section 3.5' },
    },
    {
      flag_id: 'PACK.ATA.THY.2015.RF.02',
      display_id: 'ATA-THY-RF2',
      finding: 'Agranulocytosis (ANC <500) in patient on thionamide therapy presenting with fever and sore throat',
      implication: 'Rare but life-threatening complication of methimazole/PTU. Occurs in 0.1-0.5% of patients, typically within first 90 days.',
      action: 'Immediately discontinue thionamide, obtain CBC with differential, blood cultures, broad-spectrum antibiotics, G-CSF consideration.',
      urgency: 'immediate',
      provenance: { section: 'Adverse Effects of Antithyroid Drugs', page_or_location: 'Section 4.2' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ATA.THY.2015.SEV.01',
      display_id: 'ATA-THY-SEV1',
      level: 'Thyroid storm',
      criteria: [
        'Burch-Wartofsky score >=45',
        'Severe thyrotoxicosis with fever, tachycardia, CNS dysfunction',
        'GI/hepatic manifestations (nausea, vomiting, diarrhea, jaundice)',
        'Often precipitated by infection, surgery, trauma, or iodine load',
      ],
      management_implications:
        'ICU admission. PTU preferred over methimazole (blocks T4-to-T3 conversion). Iodine given 1 hour AFTER PTU. IV glucocorticoids (hydrocortisone 300mg then 100mg q8h). Aggressive beta-blockade. Mortality 10-30%.',
      provenance: { section: 'Thyroid Storm', page_or_location: 'Section 3.5' },
    },
    {
      severity_id: 'PACK.ATA.THY.2015.SEV.02',
      display_id: 'ATA-THY-SEV2',
      level: 'Subclinical hyperthyroidism',
      criteria: [
        'TSH suppressed (<0.1 mIU/L)',
        'Normal free T4 and free T3',
        'Patient may be asymptomatic or have mild symptoms',
      ],
      management_implications:
        'Treat if TSH persistently <0.1 in patients >=65 years (AF risk), postmenopausal women (osteoporosis risk), or those with cardiac disease. Observe if TSH 0.1-0.4 in younger asymptomatic patients.',
      provenance: { section: 'Subclinical Hyperthyroidism', page_or_location: 'Section 3.2' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for thyroid disease. Covers hypothyroidism, hyperthyroidism (Graves, toxic nodule), thyroid nodules (FNA/Bethesda), and thyroid storm.',

  all_item_ids: [
    'PACK.ATA.THY.2015.REC.01', 'PACK.ATA.THY.2015.REC.02', 'PACK.ATA.THY.2015.REC.03',
    'PACK.ATA.THY.2015.REC.04', 'PACK.ATA.THY.2015.REC.05',
    'PACK.ATA.THY.2015.DC.01', 'PACK.ATA.THY.2015.DC.02',
    'PACK.ATA.THY.2015.T.01', 'PACK.ATA.THY.2015.T.02', 'PACK.ATA.THY.2015.T.03',
    'PACK.ATA.THY.2015.TX.01', 'PACK.ATA.THY.2015.TX.02', 'PACK.ATA.THY.2015.TX.03',
    'PACK.ATA.THY.2015.RF.01', 'PACK.ATA.THY.2015.RF.02',
    'PACK.ATA.THY.2015.SEV.01', 'PACK.ATA.THY.2015.SEV.02',
  ],
  all_display_ids: [
    'ATA-THY-R1', 'ATA-THY-R2', 'ATA-THY-R3', 'ATA-THY-R4', 'ATA-THY-R5',
    'ATA-THY-DC1', 'ATA-THY-DC2',
    'ATA-THY-T1', 'ATA-THY-T2', 'ATA-THY-T3',
    'ATA-THY-TX1', 'ATA-THY-TX2', 'ATA-THY-TX3',
    'ATA-THY-RF1', 'ATA-THY-RF2',
    'ATA-THY-SEV1', 'ATA-THY-SEV2',
  ],
};
