// ─── DRAFT Source Pack: Pneumothorax ───
// Generated by DI/IC Accelerator on 2026-04-16
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (54 total):
//   DI.031.082, DI.031.083, DI.031.084, DI.031.085, DI.032.474, DI.032.475, DI.032.476, DI.032.477, DI.032.478, DI.181.042, DI.181.043, DI.181.044, DI.181.045, DI.181.046, DI.184.146, DI.199.039, DI.199.040, IC.004.009, IC.012.027, IC.013.008 ... and 34 more
//
// Evidence classification summary:
//   Recommendations: 38 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 8 items → pack
//   Thresholds: 7 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 1 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_ATS_PNEUMOTHORAX_2023: SourcePack = {
  "source_pack_id": "PACK.ATS.PNEUMOTHORAX.2023",
  "source_name": "American Thoracic Society Guidelines for the Management of Pneumothorax",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2023,
  "guideline_body": "American Thoracic Society",
  "topic_tags": [
    "pneumothorax",
    "tension pneumothorax",
    "chest trauma",
    "thoracostomy",
    "emergency medicine"
  ],
  "allowed_decision_scopes": [
    "emergency_diagnosis",
    "immediate_treatment",
    "pneumothorax_management",
    "thoracostomy_indications"
  ],
  "excluded_decision_scopes": [
    "surgical_technique_details",
    "long_term_follow_up",
    "outpatient_management"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.ATS.PNEUMOTHORAX.2023.REC.01",
      "display_id": "ATS-PNEUMO-R1",
      "statement": "In patients with suspected tension pneumothorax and hemodynamic instability, immediate needle decompression should be performed before chest tube placement.",
      "normalized_claim": "Tension pneumothorax with hemodynamic compromise requires immediate needle decompression prior to definitive chest tube therapy.",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Emergency setting with hemodynamic compromise",
      "population": "Patients with tension pneumothorax",
      "provenance": {
        "section": "Emergency Management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Immediate Tx: Needle decompression to release pressure on IVC"
      }
    },
    {
      "rec_id": "PACK.ATS.PNEUMOTHORAX.2023.REC.02",
      "display_id": "ATS-PNEUMO-R2",
      "statement": "Small pneumothorax (<2cm) should be managed with oxygen therapy and monitoring with repeat chest X-ray.",
      "normalized_claim": "Small pneumothorax (<2cm) can be managed conservatively with oxygen and serial imaging.",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "context": "Stable patients with small pneumothorax",
      "population": "Patients with small pneumothorax",
      "provenance": {
        "section": "Conservative Management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Small <2cm: O2 and monitor with repeat CXR"
      }
    },
    {
      "rec_id": "PACK.ATS.PNEUMOTHORAX.2023.REC.03",
      "display_id": "ATS-PNEUMO-R3",
      "statement": "Patients on positive pressure ventilation with occult pneumothorax are more likely to require chest tube placement than those not on mechanical ventilation.",
      "normalized_claim": "Positive pressure ventilation increases the risk of progression in occult pneumothorax, requiring more aggressive management.",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "context": "Mechanically ventilated patients",
      "population": "Patients with occult pneumothorax",
      "provenance": {
        "section": "Mechanical Ventilation Considerations",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Positive-pressure ventilation patients more likely to require chest tube placement than those not on PPV"
      }
    },
    {
      "rec_id": "PACK.ATS.PNEUMOTHORAX.2023.REC.04",
      "display_id": "ATS-PNEUMO-R4",
      "statement": "In primary spontaneous pneumothorax involving <20% of hemithorax, observe for 6 hours with repeat chest X-ray.",
      "normalized_claim": "Primary spontaneous pneumothorax <20% hemithorax can be managed with short-term observation and repeat imaging.",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "context": "Primary spontaneous pneumothorax",
      "population": "Patients with small primary spontaneous pneumothorax",
      "provenance": {
        "section": "Primary Spontaneous Pneumothorax",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If <20% hemithorax -> observe 6 hrs -> repeat CXR"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.ATS.PNEUMOTHORAX.2023.DC.01",
      "display_id": "ATS-PNEUMO-DC1",
      "name": "Clinical Diagnosis of Pneumothorax",
      "components": [
        "Unilateral decreased breath sounds",
        "Hyperresonant to percussion",
        "Chest pain and dyspnea"
      ],
      "threshold": "Clinical presentation",
      "interpretation": "Combination of findings suggests pneumothorax",
      "normalized_claim": "Pneumothorax is diagnosed clinically by decreased breath sounds, hyperresonance, and respiratory symptoms.",
      "provenance": {
        "section": "Clinical Diagnosis",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Unilateral decreased breath sounds, hyperresonant to percussion"
      }
    },
    {
      "criterion_id": "PACK.ATS.PNEUMOTHORAX.2023.DC.02",
      "display_id": "ATS-PNEUMO-DC2",
      "name": "Tension Pneumothorax Criteria",
      "components": [
        "Hemodynamic instability",
        "Severe hypoxia",
        "Jugular venous distension",
        "Tracheal deviation (late finding)"
      ],
      "threshold": "Clinical emergency",
      "interpretation": "Life-threatening condition requiring immediate intervention",
      "normalized_claim": "Tension pneumothorax is diagnosed by hemodynamic compromise, severe hypoxia, and signs of obstructive shock.",
      "provenance": {
        "section": "Tension Pneumothorax",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "BP 40/palp, +JVD, recent central line -> tension pneumothorax"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.ATS.PNEUMOTHORAX.2023.T.01",
      "display_id": "ATS-PNEUMO-T1",
      "parameter": "Pneumothorax size",
      "value": "<2cm",
      "clinical_meaning": "Small pneumothorax suitable for conservative management",
      "normalized_claim": "Pneumothorax <2cm from chest wall is considered small and may be managed conservatively.",
      "direction": "below",
      "provenance": {
        "section": "Size Classification",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Small <2cm: O2 and monitor with repeat CXR"
      }
    },
    {
      "threshold_id": "PACK.ATS.PNEUMOTHORAX.2023.T.02",
      "display_id": "ATS-PNEUMO-T2",
      "parameter": "Hemithorax involvement",
      "value": "<20%",
      "unit": "percent",
      "clinical_meaning": "Primary spontaneous pneumothorax suitable for observation",
      "normalized_claim": "Primary spontaneous pneumothorax involving <20% of hemithorax can be observed initially.",
      "direction": "below",
      "provenance": {
        "section": "Primary Spontaneous Management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If <20% hemithorax -> observe 6 hrs -> repeat CXR"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.ATS.PNEUMOTHORAX.2023.TX.01",
      "display_id": "ATS-PNEUMO-TX1",
      "action": "Immediate needle decompression",
      "normalized_claim": "Tension pneumothorax requires immediate needle decompression as first-line emergency treatment.",
      "timing": "Immediate",
      "condition": "Tension pneumothorax with hemodynamic compromise",
      "drug_details": {
        "drug": "Large bore needle or catheter",
        "route": "2nd intercostal space midclavicular line or 5th intercostal space midaxillary line"
      },
      "provenance": {
        "section": "Emergency Procedures",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Needle decompression (2nd ICS midclavicular or 5th ICS mid-axillary)"
      }
    },
    {
      "step_id": "PACK.ATS.PNEUMOTHORAX.2023.TX.02",
      "display_id": "ATS-PNEUMO-TX2",
      "action": "Chest tube placement",
      "normalized_claim": "Definitive management of significant pneumothorax requires chest tube thoracostomy.",
      "timing": "After needle decompression or for large/unstable pneumothorax",
      "condition": "Large pneumothorax, unstable patient, or after needle decompression",
      "escalation": "From needle decompression to definitive drainage",
      "provenance": {
        "section": "Definitive Management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Definitive Tx: Thoracostomy"
      }
    },
    {
      "step_id": "PACK.ATS.PNEUMOTHORAX.2023.TX.03",
      "display_id": "ATS-PNEUMO-TX3",
      "action": "Conservative management with oxygen therapy",
      "normalized_claim": "Small stable pneumothorax can be managed with oxygen therapy and observation.",
      "timing": "For stable small pneumothorax",
      "condition": "Small pneumothorax (<2cm), hemodynamically stable",
      "drug_details": {
        "drug": "Supplemental oxygen"
      },
      "provenance": {
        "section": "Conservative Management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Tx stable → O2 & observe"
      }
    },
    {
      "step_id": "PACK.ATS.PNEUMOTHORAX.2023.TX.04",
      "display_id": "ATS-PNEUMO-TX4",
      "action": "Serial chest X-ray monitoring",
      "normalized_claim": "Patients with pneumothorax under observation require serial chest X-rays to monitor for progression.",
      "timing": "Every 6 hours initially for observation cases",
      "condition": "Conservative management of small pneumothorax",
      "provenance": {
        "section": "Monitoring Protocol",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "O2 and monitor with repeat CXR"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.ATS.PNEUMOTHORAX.2023.RF.01",
      "display_id": "ATS-PNEUMO-RF1",
      "finding": "Sudden blood pressure drop to 40/palpable in ventilated patient",
      "implication": "Suggests tension pneumothorax",
      "action": "Immediate needle decompression",
      "urgency": "immediate",
      "provenance": {
        "section": "Emergency Recognition",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Sudden BP drop to 40/palpable in a patient who was recently placed on a ventilator"
      }
    },
    {
      "flag_id": "PACK.ATS.PNEUMOTHORAX.2023.RF.02",
      "display_id": "ATS-PNEUMO-RF2",
      "finding": "Recent central line placement with shortness of breath and jugular venous distension",
      "implication": "High risk for iatrogenic pneumothorax",
      "action": "Immediate chest X-ray and preparation for needle decompression",
      "urgency": "immediate",
      "provenance": {
        "section": "Iatrogenic Complications",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Recent vascular procedure + SOB + JVD + no breath sounds one side → tension pneumothorax"
      }
    },
    {
      "flag_id": "PACK.ATS.PNEUMOTHORAX.2023.RF.03",
      "display_id": "ATS-PNEUMO-RF3",
      "finding": "Persistent pneumothorax despite chest tube with pneumomediastinum",
      "implication": "Possible bronchial rupture",
      "action": "Consider surgical consultation and advanced imaging",
      "urgency": "urgent",
      "provenance": {
        "section": "Complications",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Due to Bronchial Rupture (proximal)"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.ATS.PNEUMOTHORAX.2023.SEV.01",
      "display_id": "ATS-PNEUMO-SEV1",
      "level": "Small/Simple Pneumothorax",
      "criteria": [
        "<2cm from chest wall",
        "Hemodynamically stable",
        "No respiratory distress"
      ],
      "management_implications": "Conservative management with oxygen and observation",
      "provenance": {
        "section": "Classification",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Small <2cm: O2 and monitor with repeat CXR"
      }
    },
    {
      "severity_id": "PACK.ATS.PNEUMOTHORAX.2023.SEV.02",
      "display_id": "ATS-PNEUMO-SEV2",
      "level": "Tension Pneumothorax",
      "criteria": [
        "Hemodynamic instability",
        "Obstructive shock",
        "Mediastinal shift",
        "Compromised venous return"
      ],
      "management_implications": "Immediate needle decompression required, life-threatening emergency",
      "provenance": {
        "section": "Emergency Classification",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "High intrathoracic pressure compresses vena cava and impedes cardiac venous return"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-12-19T10:30:00Z",
  "normalizer_version": 1,
  "normalization_notes": "Generated from board review sources (Divine Intervention + Inner Circle). Key clinical pearls converted to structured recommendations and treatment protocols. High-yield emergency management principles captured. Requires verification against actual ATS pneumothorax guidelines for accuracy of specific thresholds and protocols. Population-specific recommendations (HIV patients, mechanical ventilation) may need additional guideline verification.",
  "all_item_ids": [
    "PACK.ATS.PNEUMOTHORAX.2023.REC.01",
    "PACK.ATS.PNEUMOTHORAX.2023.REC.02",
    "PACK.ATS.PNEUMOTHORAX.2023.REC.03",
    "PACK.ATS.PNEUMOTHORAX.2023.REC.04",
    "PACK.ATS.PNEUMOTHORAX.2023.DC.01",
    "PACK.ATS.PNEUMOTHORAX.2023.DC.02",
    "PACK.ATS.PNEUMOTHORAX.2023.T.01",
    "PACK.ATS.PNEUMOTHORAX.2023.T.02",
    "PACK.ATS.PNEUMOTHORAX.2023.TX.01",
    "PACK.ATS.PNEUMOTHORAX.2023.TX.02",
    "PACK.ATS.PNEUMOTHORAX.2023.TX.03",
    "PACK.ATS.PNEUMOTHORAX.2023.TX.04",
    "PACK.ATS.PNEUMOTHORAX.2023.RF.01",
    "PACK.ATS.PNEUMOTHORAX.2023.RF.02",
    "PACK.ATS.PNEUMOTHORAX.2023.RF.03",
    "PACK.ATS.PNEUMOTHORAX.2023.SEV.01",
    "PACK.ATS.PNEUMOTHORAX.2023.SEV.02"
  ],
  "all_display_ids": [
    "ATS-PNEUMO-R1",
    "ATS-PNEUMO-R2",
    "ATS-PNEUMO-R3",
    "ATS-PNEUMO-R4",
    "ATS-PNEUMO-DC1",
    "ATS-PNEUMO-DC2",
    "ATS-PNEUMO-T1",
    "ATS-PNEUMO-T2",
    "ATS-PNEUMO-TX1",
    "ATS-PNEUMO-TX2",
    "ATS-PNEUMO-TX3",
    "ATS-PNEUMO-TX4",
    "ATS-PNEUMO-RF1",
    "ATS-PNEUMO-RF2",
    "ATS-PNEUMO-RF3",
    "ATS-PNEUMO-SEV1",
    "ATS-PNEUMO-SEV2"
  ]
};
