// ─── DRAFT Source Pack: ARDS ───
// Generated by DI/IC Accelerator on 2026-04-16
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (58 total):
//   AM.002.009, AM.004.012, DI.030.300, DI.030.324, DI.031.675, DI.032.337, DI.049.013, DI.049.052, DI.049.054, DI.049.083, DI.059.015, DI.065.009, DI.132.039, DI.132.040, DI.132.041, DI.134.010, DI.138.010, DI.141.048, DI.141.049, DI.141.050 ... and 38 more
//
// Evidence classification summary:
//   Recommendations: 26 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 6 items → pack
//   Thresholds: 21 items → pack
//   Red flags: 1 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 4 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_ATS_ARDS_2012: SourcePack = {
  "source_pack_id": "PACK.ATS.ARDS.2012",
  "source_name": "Berlin Definition of ARDS",
  "canonical_url": "https://doi.org/10.1001/jama.2012.5669",
  "publication_year": 2012,
  "guideline_body": "American Thoracic Society / European Society of Intensive Care Medicine",
  "topic_tags": [
    "ARDS",
    "acute respiratory distress syndrome",
    "mechanical ventilation",
    "critical care",
    "pulmonary edema"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "management",
    "mechanical ventilation",
    "prognosis"
  ],
  "excluded_decision_scopes": [
    "prevention",
    "pediatric management",
    "extracorporeal support"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.ATS.ARDS.2012.REC.01",
      "display_id": "ATS-ARDS-R1",
      "statement": "Use low tidal volume ventilation (6 mL/kg predicted body weight) in patients with ARDS",
      "normalized_claim": "Low tidal volume mechanical ventilation improves survival in ARDS patients",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Mechanical ventilation strategy for ARDS",
      "population": "Adults with ARDS requiring mechanical ventilation",
      "provenance": {
        "section": "Management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "ARDS survival strategies: low tidal volumes + high PEEP + PRONE position"
      }
    },
    {
      "rec_id": "PACK.ATS.ARDS.2012.REC.02",
      "display_id": "ATS-ARDS-R2",
      "statement": "Use high PEEP strategy in patients with moderate to severe ARDS",
      "normalized_claim": "Higher PEEP levels improve outcomes in ARDS patients with severe hypoxemia",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "context": "Mechanical ventilation strategy for ARDS",
      "population": "Adults with moderate to severe ARDS",
      "provenance": {
        "section": "Management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Tx? Ventilation with high PEEP & low tidal volumes"
      }
    },
    {
      "rec_id": "PACK.ATS.ARDS.2012.REC.03",
      "display_id": "ATS-ARDS-R3",
      "statement": "Consider prone positioning for patients with severe ARDS (PaO2/FiO2 < 150)",
      "normalized_claim": "Prone positioning improves survival in patients with severe ARDS",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "context": "Positioning strategy for severe ARDS",
      "population": "Adults with severe ARDS and PaO2/FiO2 < 150",
      "provenance": {
        "section": "Management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "ARDS survival strategies: low tidal volumes + high PEEP + PRONE position (not supine)"
      }
    },
    {
      "rec_id": "PACK.ATS.ARDS.2012.REC.04",
      "display_id": "ATS-ARDS-R4",
      "statement": "Mechanical ventilation should target oxygenation goals using FiO2 and PEEP adjustments",
      "normalized_claim": "Oxygenation in ARDS is optimally managed through coordinated FiO2 and PEEP titration",
      "strength": "expert_consensus",
      "evidence_quality": "low",
      "context": "Ventilator management principles",
      "population": "All ARDS patients on mechanical ventilation",
      "provenance": {
        "section": "Management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Oxygenation determined by FiO2 and PEEP"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.ATS.ARDS.2012.DC.01",
      "display_id": "ATS-ARDS-DC1",
      "name": "Berlin Definition of ARDS",
      "components": [
        "Acute onset (within 7 days)",
        "Bilateral opacities on chest imaging",
        "PaO2/FiO2 ratio ≤ 300 mmHg with PEEP ≥ 5 cmH2O",
        "Respiratory failure not fully explained by cardiac failure or fluid overload"
      ],
      "threshold": "PaO2/FiO2 ≤ 300 with PEEP ≥ 5",
      "interpretation": "Mild ARDS: 200 < PaO2/FiO2 ≤ 300; Moderate ARDS: 100 < PaO2/FiO2 ≤ 200; Severe ARDS: PaO2/FiO2 ≤ 100",
      "normalized_claim": "ARDS diagnosis requires acute bilateral lung injury with impaired oxygenation not due to heart failure",
      "provenance": {
        "section": "Definition and Criteria",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "ARDS diagnostic criteria: | PaO2/FiO2 < 300 | CXR with bilateral infiltrates"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.ATS.ARDS.2012.T.01",
      "display_id": "ATS-ARDS-T1",
      "parameter": "PaO2/FiO2 ratio",
      "value": "300",
      "unit": "mmHg",
      "clinical_meaning": "Upper threshold for ARDS diagnosis",
      "normalized_claim": "PaO2/FiO2 ratio ≤ 300 mmHg defines acute lung injury consistent with ARDS",
      "direction": "below",
      "provenance": {
        "section": "Diagnostic Criteria",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "PaO2/FiO2 < 300"
      }
    },
    {
      "threshold_id": "PACK.ATS.ARDS.2012.T.02",
      "display_id": "ATS-ARDS-T2",
      "parameter": "Pulmonary capillary wedge pressure",
      "value": "18",
      "unit": "mmHg",
      "clinical_meaning": "Upper limit to exclude cardiogenic pulmonary edema",
      "normalized_claim": "PCWP < 18 mmHg helps distinguish ARDS from cardiogenic pulmonary edema",
      "direction": "below",
      "provenance": {
        "section": "Diagnostic Criteria",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "PCWP must be < 18 to make ARDS diagnosis (non-cardiogenic pulmonary edema)"
      }
    },
    {
      "threshold_id": "PACK.ATS.ARDS.2012.T.03",
      "display_id": "ATS-ARDS-T3",
      "parameter": "PaO2/FiO2 ratio for severe ARDS",
      "value": "100",
      "unit": "mmHg",
      "clinical_meaning": "Threshold for severe ARDS classification",
      "normalized_claim": "PaO2/FiO2 ≤ 100 mmHg defines severe ARDS with highest mortality risk",
      "direction": "below",
      "provenance": {
        "section": "Severity Classification",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "PaO2/FiO2 < 200 (<300 means acute lung injury)"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.ATS.ARDS.2012.TX.01",
      "display_id": "ATS-ARDS-TX1",
      "action": "Initiate low tidal volume ventilation",
      "normalized_claim": "Initial ventilation should use 6 mL/kg predicted body weight tidal volumes",
      "timing": "Immediately upon ARDS diagnosis and intubation",
      "condition": "All patients with ARDS requiring mechanical ventilation",
      "contraindications": [
        "Severe metabolic acidosis requiring higher minute ventilation"
      ],
      "drug_details": {
        "drug": "Mechanical ventilation",
        "dose": "6 mL/kg predicted body weight",
        "route": "Endotracheal",
        "duration": "Duration of mechanical ventilation"
      },
      "provenance": {
        "section": "Mechanical Ventilation",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "low tidal volumes"
      }
    },
    {
      "step_id": "PACK.ATS.ARDS.2012.TX.02",
      "display_id": "ATS-ARDS-TX2",
      "action": "Apply appropriate PEEP levels",
      "normalized_claim": "PEEP should be titrated to optimize oxygenation while preventing overdistention",
      "timing": "Concurrent with mechanical ventilation initiation",
      "condition": "All ARDS patients on mechanical ventilation",
      "escalation": "Increase PEEP in moderate to severe ARDS",
      "provenance": {
        "section": "Mechanical Ventilation",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "mechanical ventilation w/ PEEP"
      }
    },
    {
      "step_id": "PACK.ATS.ARDS.2012.TX.03",
      "display_id": "ATS-ARDS-TX3",
      "action": "Consider prone positioning",
      "normalized_claim": "Prone positioning should be considered for severe ARDS to improve oxygenation and survival",
      "timing": "Within 48 hours of ARDS onset for severe cases",
      "condition": "Severe ARDS (PaO2/FiO2 < 150 mmHg)",
      "contraindications": [
        "Unstable spine",
        "Recent abdominal surgery",
        "Severe hemodynamic instability"
      ],
      "provenance": {
        "section": "Adjunctive Therapies",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "PRONE position (not supine)"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.ATS.ARDS.2012.RF.01",
      "display_id": "ATS-ARDS-RF1",
      "finding": "White-out chest X-ray with severe hypoxemia and diffuse crackles",
      "implication": "Suggests severe ARDS with high mortality risk",
      "action": "Immediate intensive care management with lung-protective ventilation",
      "urgency": "immediate",
      "provenance": {
        "section": "Clinical Features",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "wash out CXR respiratory distress, diffuse crackles, severe hypoxemia, b/l alveolar infiltrates"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.ATS.ARDS.2012.SEV.01",
      "display_id": "ATS-ARDS-SEV1",
      "level": "Mild ARDS",
      "criteria": [
        "PaO2/FiO2 200-300 mmHg with PEEP ≥ 5 cmH2O"
      ],
      "management_implications": "Standard lung-protective ventilation, monitor for progression",
      "provenance": {
        "section": "Berlin Definition",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "PaO2/FiO2 < 300"
      }
    },
    {
      "severity_id": "PACK.ATS.ARDS.2012.SEV.02",
      "display_id": "ATS-ARDS-SEV2",
      "level": "Moderate ARDS",
      "criteria": [
        "PaO2/FiO2 100-200 mmHg with PEEP ≥ 5 cmH2O"
      ],
      "management_implications": "Consider higher PEEP strategy, evaluate for adjunctive therapies",
      "provenance": {
        "section": "Berlin Definition",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "PaO2/FiO2 < 200"
      }
    },
    {
      "severity_id": "PACK.ATS.ARDS.2012.SEV.03",
      "display_id": "ATS-ARDS-SEV3",
      "level": "Severe ARDS",
      "criteria": [
        "PaO2/FiO2 ≤ 100 mmHg with PEEP ≥ 5 cmH2O"
      ],
      "management_implications": "High PEEP strategy, prone positioning, consider ECMO consultation, 40% hospital mortality",
      "provenance": {
        "section": "Berlin Definition and Prognosis",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Mortality: 40% in hospital, death due to multi organ failure"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-12-28",
  "normalizer_version": 1,
  "normalization_notes": "Converted from board review sources (DI/IC/EH). Key elements extracted include Berlin criteria for ARDS diagnosis, lung-protective ventilation strategies, and severity classifications. All clinical claims appear medically accurate but require verification against actual ATS/ESICM Berlin Definition guidelines. Mortality statistics and management recommendations need verification. Some specific drug dosing and contraindication details may need refinement against primary guidelines.",
  "all_item_ids": [
    "PACK.ATS.ARDS.2012.REC.01",
    "PACK.ATS.ARDS.2012.REC.02",
    "PACK.ATS.ARDS.2012.REC.03",
    "PACK.ATS.ARDS.2012.REC.04",
    "PACK.ATS.ARDS.2012.DC.01",
    "PACK.ATS.ARDS.2012.T.01",
    "PACK.ATS.ARDS.2012.T.02",
    "PACK.ATS.ARDS.2012.T.03",
    "PACK.ATS.ARDS.2012.TX.01",
    "PACK.ATS.ARDS.2012.TX.02",
    "PACK.ATS.ARDS.2012.TX.03",
    "PACK.ATS.ARDS.2012.RF.01",
    "PACK.ATS.ARDS.2012.SEV.01",
    "PACK.ATS.ARDS.2012.SEV.02",
    "PACK.ATS.ARDS.2012.SEV.03"
  ],
  "all_display_ids": [
    "ATS-ARDS-R1",
    "ATS-ARDS-R2",
    "ATS-ARDS-R3",
    "ATS-ARDS-R4",
    "ATS-ARDS-DC1",
    "ATS-ARDS-T1",
    "ATS-ARDS-T2",
    "ATS-ARDS-T3",
    "ATS-ARDS-TX1",
    "ATS-ARDS-TX2",
    "ATS-ARDS-TX3",
    "ATS-ARDS-RF1",
    "ATS-ARDS-SEV1",
    "ATS-ARDS-SEV2",
    "ATS-ARDS-SEV3"
  ]
};
