// ─── DRAFT Source Pack: Sarcoidosis ───
// Generated by DI/IC Accelerator on 2026-04-16
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (20 total):
//   DI.019.152, DI.031.189, DI.031.244, DI.031.245, DI.031.246, DI.031.247, DI.031.248, DI.031.249, DI.031.250, DI.031.251, DI.031.693, DI.135.031, DI.261.027, DI.261.028, EH.000.005, EH.002.044, EH.007.029, IC.036.020, IC.057.004, IC.058.131
//
// Evidence classification summary:
//   Recommendations: 16 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 1 items → pack
//   Thresholds: 3 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_ATS_SARC_2020: SourcePack = {
  "source_pack_id": "PACK.ATS.SARC.2020",
  "source_name": "ATS/ERS/WASOG Statement on Sarcoidosis",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2020,
  "guideline_body": "American Thoracic Society",
  "topic_tags": [
    "sarcoidosis",
    "granulomatous disease",
    "multisystem disease",
    "restrictive lung disease"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "management",
    "monitoring",
    "treatment initiation"
  ],
  "excluded_decision_scopes": [
    "surgical intervention",
    "advanced therapy selection"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.ATS.SARC.2020.REC.01",
      "display_id": "ATS-SARC-R1",
      "statement": "Most patients with sarcoidosis do not require treatment",
      "normalized_claim": "Treatment is not indicated for most sarcoidosis patients",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Asymptomatic or mild disease",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Most people don't require tx"
      }
    },
    {
      "rec_id": "PACK.ATS.SARC.2020.REC.02",
      "display_id": "ATS-SARC-R2",
      "statement": "Corticosteroids should be considered for symptomatic sarcoidosis requiring treatment",
      "normalized_claim": "Steroids are first-line therapy for sarcoidosis when treatment is needed",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Symptomatic disease requiring intervention",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "steroids if they need tx"
      }
    },
    {
      "rec_id": "PACK.ATS.SARC.2020.REC.03",
      "display_id": "ATS-SARC-R3",
      "statement": "TB skin testing may be falsely negative in sarcoidosis patients",
      "normalized_claim": "Tuberculin skin test has reduced sensitivity in sarcoidosis",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Differential diagnosis considerations",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "TB skin testing → false negative"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.ATS.SARC.2020.DC.01",
      "display_id": "ATS-SARC-DC1",
      "name": "Sarcoidosis Clinical Syndrome",
      "components": [
        "Bilateral hilar lymphadenopathy",
        "Elevated ACE levels",
        "Non-caseating granulomas",
        "Compatible clinical presentation"
      ],
      "threshold": "Presence of multiple components",
      "interpretation": "Consistent with sarcoidosis diagnosis",
      "normalized_claim": "Sarcoidosis diagnosis requires compatible clinical, laboratory, and histologic findings",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "bilateral lymphadenopathy, increased ACE levels, Non-caseating granulomas"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.ATS.SARC.2020.T.01",
      "display_id": "ATS-SARC-T1",
      "parameter": "Serum calcium",
      "value": "12.9",
      "unit": "mg/dL",
      "clinical_meaning": "Hypercalcemia associated with sarcoidosis",
      "normalized_claim": "Hypercalcemia occurs in sarcoidosis due to extrarenal 1-alpha-hydroxylase production",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Ca2+ of 12.9, Hypercalcemia (Why? Macrophages produce 1-alpha-hydroxylase)"
      }
    },
    {
      "threshold_id": "PACK.ATS.SARC.2020.T.02",
      "display_id": "ATS-SARC-T2",
      "parameter": "ACE level",
      "value": "elevated",
      "clinical_meaning": "Elevated angiotensin-converting enzyme in sarcoidosis",
      "normalized_claim": "ACE levels are characteristically elevated in active sarcoidosis",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "increased ACE levels, Elevated ACE"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.ATS.SARC.2020.TX.01",
      "display_id": "ATS-SARC-TX1",
      "action": "Observation without treatment for asymptomatic disease",
      "normalized_claim": "Watchful waiting is appropriate for most sarcoidosis patients",
      "timing": "Initial management",
      "condition": "Asymptomatic or mild disease",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Most people don't require tx"
      }
    },
    {
      "step_id": "PACK.ATS.SARC.2020.TX.02",
      "display_id": "ATS-SARC-TX2",
      "action": "Initiate corticosteroid therapy",
      "normalized_claim": "Corticosteroids are first-line treatment for symptomatic sarcoidosis",
      "timing": "When treatment is indicated",
      "condition": "Symptomatic disease requiring intervention",
      "drug_details": {
        "drug": "corticosteroids"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "steroids if they need tx"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.ATS.SARC.2020.RF.01",
      "display_id": "ATS-SARC-RF1",
      "finding": "Cardiac involvement with diastolic dysfunction",
      "implication": "Restrictive cardiomyopathy secondary to sarcoidosis",
      "action": "Urgent cardiology evaluation and cardiac-specific treatment",
      "urgency": "urgent",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Diastolic dysfunction in a patient with a history of sarcoidosis → restrictive cardiomyopathy"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.ATS.SARC.2020.SEV.01",
      "display_id": "ATS-SARC-SEV1",
      "level": "Pulmonary involvement",
      "criteria": [
        "Restrictive pattern on pulmonary function tests",
        "Normal FEV1",
        "Decreased total lung capacity",
        "Decreased DLCO"
      ],
      "management_implications": "Monitor respiratory function and consider treatment based on symptoms",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Restrictive lung PFTs pattern: Normal FEV1, Decreased TLC, Decreased DLCO"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "validated",
  "last_normalized": "2024-12-28",
  "normalizer_version": 1,
  "normalization_notes": "Generated from board review evidence (Divine Intervention, Inner Circle, Emma Holliday). Key areas needing verification: specific treatment protocols, dosing guidelines, staging systems, monitoring recommendations. Demographics show predilection for African American females. Multiple organ system involvement documented including eyes (anterior uveitis), skin (erythema nodosum, lupus pernio), lungs (restrictive pattern), and heart (restrictive cardiomyopathy). Histologic hallmark is non-caseating granulomas.",
  "all_item_ids": [
    "PACK.ATS.SARC.2020.REC.01",
    "PACK.ATS.SARC.2020.REC.02",
    "PACK.ATS.SARC.2020.REC.03",
    "PACK.ATS.SARC.2020.DC.01",
    "PACK.ATS.SARC.2020.T.01",
    "PACK.ATS.SARC.2020.T.02",
    "PACK.ATS.SARC.2020.TX.01",
    "PACK.ATS.SARC.2020.TX.02",
    "PACK.ATS.SARC.2020.RF.01",
    "PACK.ATS.SARC.2020.SEV.01"
  ],
  "all_display_ids": [
    "ATS-SARC-R1",
    "ATS-SARC-R2",
    "ATS-SARC-R3",
    "ATS-SARC-DC1",
    "ATS-SARC-T1",
    "ATS-SARC-T2",
    "ATS-SARC-TX1",
    "ATS-SARC-TX2",
    "ATS-SARC-RF1",
    "ATS-SARC-SEV1"
  ]
};
