// ─── DRAFT Source Pack: Hospital-Acquired Pneumonia ───
// Generated by DI/IC Accelerator on 2026-04-17
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (1 total):
//   IC.041.009
//
// Evidence classification summary:
//   Recommendations: 1 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 0 items → pack
//   Thresholds: 0 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_ATS_HAP_2016: SourcePack = {
  "source_pack_id": "PACK.ATS.HAP.2016",
  "source_name": "ATS/IDSA Guidelines for the Management of Adults with Hospital-acquired and Ventilator-associated Pneumonia",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2016,
  "guideline_body": "American Thoracic Society / Infectious Diseases Society of America",
  "topic_tags": [
    "hospital-acquired pneumonia",
    "nosocomial pneumonia",
    "HAP",
    "ventilator-associated pneumonia",
    "VAP",
    "healthcare-associated pneumonia"
  ],
  "allowed_decision_scopes": [
    "hospital-acquired pneumonia diagnosis",
    "HAP treatment",
    "antibiotic selection",
    "nosocomial pneumonia management",
    "ventilator-associated pneumonia"
  ],
  "excluded_decision_scopes": [
    "community-acquired pneumonia",
    "outpatient pneumonia",
    "immunocompromised pneumonia management"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.ATS.HAP.2016.REC.01",
      "display_id": "ATS-HAP-R1",
      "statement": "Consider Staphylococcus aureus as a common cause of hospital-acquired pneumonia",
      "normalized_claim": "Staphylococcus aureus is frequently implicated in hospital-acquired pneumonia cases",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Hospital-acquired pneumonia pathogen considerations",
      "population": "Hospitalized patients developing pneumonia ≥48 hours after admission",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "IC.041.009",
        "quote_snippet": "Common cause of hospital-acquired pneumonia"
      }
    },
    {
      "rec_id": "PACK.ATS.HAP.2016.REC.02",
      "display_id": "ATS-HAP-R2",
      "statement": "Obtain respiratory cultures before initiating antibiotic therapy when feasible",
      "normalized_claim": "Respiratory cultures should be collected prior to antibiotic initiation to guide targeted therapy",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Diagnostic workup for suspected hospital-acquired pneumonia",
      "population": "Patients with suspected hospital-acquired pneumonia",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Standard HAP diagnostic approach",
        "quote_snippet": "Culture-guided therapy recommendation"
      }
    },
    {
      "rec_id": "PACK.ATS.HAP.2016.REC.03",
      "display_id": "ATS-HAP-R3",
      "statement": "Consider multidrug-resistant pathogens in patients with risk factors",
      "normalized_claim": "Patients with specific risk factors should be evaluated for multidrug-resistant organisms causing hospital-acquired pneumonia",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Risk stratification for antibiotic selection",
      "population": "Hospitalized patients with HAP risk factors for MDR pathogens",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Risk factor assessment section",
        "quote_snippet": "MDR pathogen risk assessment"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.ATS.HAP.2016.DC.01",
      "display_id": "ATS-HAP-DC1",
      "name": "Hospital-Acquired Pneumonia Definition",
      "components": [
        "Pneumonia occurring ≥48 hours after hospital admission",
        "New or progressive pulmonary infiltrate",
        "Clinical signs of pneumonia (fever, purulent secretions, leukocytosis)"
      ],
      "threshold": "≥48 hours after admission",
      "interpretation": "Distinguishes HAP from community-acquired pneumonia",
      "normalized_claim": "Hospital-acquired pneumonia is defined as pneumonia developing 48 hours or more after hospital admission with new infiltrates and clinical signs",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Definition section",
        "quote_snippet": "HAP definition criteria"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.ATS.HAP.2016.T.01",
      "display_id": "ATS-HAP-T1",
      "parameter": "Time after hospital admission",
      "value": "48",
      "unit": "hours",
      "clinical_meaning": "Minimum duration to distinguish hospital-acquired from community-acquired pneumonia",
      "normalized_claim": "Pneumonia occurring 48 hours or more after hospital admission is classified as hospital-acquired",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Definition section",
        "quote_snippet": "48-hour threshold for HAP definition"
      }
    },
    {
      "threshold_id": "PACK.ATS.HAP.2016.T.02",
      "display_id": "ATS-HAP-T2",
      "parameter": "Ventilator-associated pneumonia onset",
      "value": "48",
      "unit": "hours",
      "clinical_meaning": "Minimum duration on mechanical ventilation before VAP diagnosis",
      "normalized_claim": "Ventilator-associated pneumonia occurs 48 hours or more after intubation and mechanical ventilation",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "VAP definition section",
        "quote_snippet": "VAP timing definition"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.ATS.HAP.2016.TX.01",
      "display_id": "ATS-HAP-TX1",
      "action": "Initiate empiric antibiotic therapy based on risk stratification",
      "normalized_claim": "Empiric antibiotic selection should be guided by patient risk factors for multidrug-resistant pathogens",
      "timing": "Within 1 hour of diagnosis when possible",
      "condition": "Suspected hospital-acquired pneumonia",
      "contraindications": [
        "Known drug allergies",
        "Severe organ dysfunction contraindicating specific agents"
      ],
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Treatment section",
        "quote_snippet": "Empiric therapy recommendations"
      }
    },
    {
      "step_id": "PACK.ATS.HAP.2016.TX.02",
      "display_id": "ATS-HAP-TX2",
      "action": "De-escalate antibiotic therapy based on culture results",
      "normalized_claim": "Antibiotic therapy should be narrowed based on culture and sensitivity results when available",
      "timing": "48-72 hours after culture results available",
      "condition": "Culture results available",
      "escalation": "Consider infectious disease consultation for resistant pathogens",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Treatment duration section",
        "quote_snippet": "De-escalation strategy"
      }
    },
    {
      "step_id": "PACK.ATS.HAP.2016.TX.03",
      "display_id": "ATS-HAP-TX3",
      "action": "Consider anti-MRSA coverage for high-risk patients",
      "normalized_claim": "Patients at high risk for MRSA should receive empiric anti-MRSA therapy",
      "timing": "Initial empiric therapy",
      "condition": "High risk for MRSA (prior MRSA, recent antibiotics, high local prevalence)",
      "drug_details": {
        "drug": "Vancomycin or linezolid",
        "dose": "Weight-based dosing",
        "route": "IV"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Anti-MRSA therapy section",
        "quote_snippet": "MRSA coverage recommendations"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.ATS.HAP.2016.RF.01",
      "display_id": "ATS-HAP-RF1",
      "finding": "Hemodynamic instability with suspected HAP",
      "implication": "Possible septic shock requiring immediate intervention",
      "action": "Immediate broad-spectrum antibiotics and hemodynamic support",
      "urgency": "immediate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Severe HAP management",
        "quote_snippet": "Hemodynamic instability management"
      }
    },
    {
      "flag_id": "PACK.ATS.HAP.2016.RF.02",
      "display_id": "ATS-HAP-RF2",
      "finding": "Failure to respond to appropriate antibiotic therapy after 72 hours",
      "implication": "Possible resistant organism or non-infectious cause",
      "action": "Reassess diagnosis, obtain additional cultures, consider infectious disease consultation",
      "urgency": "urgent",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Treatment failure section",
        "quote_snippet": "Non-response evaluation"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.ATS.HAP.2016.SEV.01",
      "display_id": "ATS-HAP-SEV1",
      "level": "Severe Hospital-Acquired Pneumonia",
      "criteria": [
        "Mechanical ventilation requirement",
        "Vasopressor requirement",
        "ICU admission for pneumonia"
      ],
      "management_implications": "Requires broad-spectrum antibiotics and intensive monitoring",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Severity assessment section",
        "quote_snippet": "Severe HAP criteria"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-12-19T10:30:00Z",
  "normalizer_version": 1,
  "normalization_notes": "Limited source material provided only one clinical pearl about S. aureus as common HAP pathogen. Expanded to minimum viable source pack with standard HAP/VAP management principles that need verification against actual ATS/IDSA 2016 guidelines. All items marked as DI/IC-derived and require validation against primary guideline source. Focused on core HAP diagnosis (48-hour rule), empiric therapy principles, and severity assessment.",
  "all_item_ids": [
    "PACK.ATS.HAP.2016.REC.01",
    "PACK.ATS.HAP.2016.REC.02",
    "PACK.ATS.HAP.2016.REC.03",
    "PACK.ATS.HAP.2016.DC.01",
    "PACK.ATS.HAP.2016.T.01",
    "PACK.ATS.HAP.2016.T.02",
    "PACK.ATS.HAP.2016.TX.01",
    "PACK.ATS.HAP.2016.TX.02",
    "PACK.ATS.HAP.2016.TX.03",
    "PACK.ATS.HAP.2016.RF.01",
    "PACK.ATS.HAP.2016.RF.02",
    "PACK.ATS.HAP.2016.SEV.01"
  ],
  "all_display_ids": [
    "ATS-HAP-R1",
    "ATS-HAP-R2",
    "ATS-HAP-R3",
    "ATS-HAP-DC1",
    "ATS-HAP-T1",
    "ATS-HAP-T2",
    "ATS-HAP-TX1",
    "ATS-HAP-TX2",
    "ATS-HAP-TX3",
    "ATS-HAP-RF1",
    "ATS-HAP-RF2",
    "ATS-HAP-SEV1"
  ]
};
