import type { SourcePack } from './types';

export const PACK_ATSIDSA_CAP_2019: SourcePack = {
  source_pack_id: 'PACK.ATSIDSA.CAP.2019',
  source_name: 'ATS/IDSA Clinical Practice Guideline: Diagnosis and Treatment of Adults with Community-Acquired Pneumonia (2019)',
  canonical_url: 'https://doi.org/10.1164/rccm.201908-1581ST',
  publication_year: 2019,
  guideline_body: 'ATS/IDSA',

  topic_tags: ['Community-Acquired Pneumonia', 'CAP', 'Pneumonia', 'Infectious Disease', 'Pulmonology'],
  allowed_decision_scopes: [
    'CAP diagnosis',
    'CAP severity assessment',
    'CAP outpatient antibiotic selection',
    'CAP inpatient non-ICU antibiotic selection',
    'CAP ICU antibiotic selection',
    'CAP disposition decision',
    'CURB-65 scoring',
    'PSI scoring',
    'severe CAP criteria',
    'MRSA/Pseudomonas risk factor assessment',
    'blood culture indications in CAP',
  ],
  excluded_decision_scopes: [
    'hospital-acquired pneumonia (HAP)',
    'ventilator-associated pneumonia (VAP)',
    'pneumonia in immunocompromised patients',
    'aspiration pneumonia specific management',
    'tuberculosis diagnosis and treatment',
    'pediatric pneumonia',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ATSIDSA.CAP.2019.REC.01',
      display_id: 'ATSIDSA-CAP-R1',
      statement: 'Severity assessment with a validated tool (PSI preferred over CURB-65) should be used to determine site of care in addition to clinical judgment.',
      normalized_claim: 'Use PSI (preferred) or CURB-65 to guide CAP disposition; clinical judgment supplements scoring.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Severity Assessment', page_or_location: 'Recommendation 1' },
    },
    {
      rec_id: 'PACK.ATSIDSA.CAP.2019.REC.02',
      display_id: 'ATSIDSA-CAP-R2',
      statement: 'Direct admission to an ICU is recommended for patients with septic shock requiring vasopressors or respiratory failure requiring mechanical ventilation (major criteria for severe CAP).',
      normalized_claim: 'ICU admission required for severe CAP: septic shock needing vasopressors or respiratory failure needing mechanical ventilation.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Severe CAP', page_or_location: 'Recommendation 2' },
    },
    {
      rec_id: 'PACK.ATSIDSA.CAP.2019.REC.03',
      display_id: 'ATSIDSA-CAP-R3',
      statement: 'Blood cultures and sputum cultures are recommended for patients with severe CAP and for inpatients being empirically treated for MRSA or Pseudomonas. Routine blood cultures are not recommended for non-severe inpatient CAP.',
      normalized_claim: 'Blood/sputum cultures for severe CAP and when empirically covering MRSA/Pseudomonas. Not routine for non-severe inpatient CAP.',
      strength: 'conditional',
      evidence_quality: 'low',
      provenance: { section: 'Diagnostic Studies', page_or_location: 'Recommendations 3–6' },
    },
    {
      rec_id: 'PACK.ATSIDSA.CAP.2019.REC.04',
      display_id: 'ATSIDSA-CAP-R4',
      statement: 'Procalcitonin should not be used to determine whether to initiate antibiotic therapy in adults with clinically suspected and radiographically confirmed CAP.',
      normalized_claim: 'Do not use procalcitonin to withhold antibiotics in clinically and radiographically confirmed CAP.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Diagnostic Studies', page_or_location: 'Recommendation 7' },
    },
    {
      rec_id: 'PACK.ATSIDSA.CAP.2019.REC.05',
      display_id: 'ATSIDSA-CAP-R5',
      statement: 'Empiric treatment for MRSA or Pseudomonas aeruginosa is recommended only when locally validated risk factors are present. Prior respiratory isolation of these organisms or recent hospitalization with parenteral antibiotics are the strongest risk factors.',
      normalized_claim: 'Cover MRSA/Pseudomonas only with validated risk factors: prior respiratory culture positive or recent hospitalization with IV antibiotics.',
      strength: 'conditional',
      evidence_quality: 'low',
      provenance: { section: 'MRSA and Pseudomonas Coverage', page_or_location: 'Recommendations 13–14' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ATSIDSA.CAP.2019.DC.01',
      display_id: 'ATSIDSA-CAP-DC1',
      name: 'CAP Clinical Definition',
      components: [
        'New pulmonary infiltrate on chest imaging (radiograph or CT)',
        'At least one of: fever >38°C, hypothermia <36°C, new cough, sputum production, dyspnea, pleuritic chest pain, altered breath sounds (crackles, bronchial breathing), leukocytosis or leukopenia',
        'Acquired in the community (not hospitalized in prior 48 hours)',
      ],
      interpretation: 'CAP requires both radiographic evidence of new infiltrate AND compatible clinical features. Imaging is essential — clinical findings alone are insufficient for diagnosis.',
      normalized_claim: 'CAP = new infiltrate on imaging + respiratory symptoms/signs, acquired outside hospital. Imaging required for diagnosis.',
      provenance: { section: 'Definition', page_or_location: 'Introduction' },
    },
    {
      criterion_id: 'PACK.ATSIDSA.CAP.2019.DC.02',
      display_id: 'ATSIDSA-CAP-DC2',
      name: 'ATS/IDSA Severe CAP Criteria',
      components: [
        'MAJOR criteria (1 sufficient): Septic shock requiring vasopressors; Respiratory failure requiring mechanical ventilation',
        'MINOR criteria (≥3 sufficient): RR ≥30, PaO2/FiO2 ratio ≤250, Multilobar infiltrates, Confusion/disorientation, BUN ≥20 mg/dL, WBC <4000, Platelets <100,000, Temperature <36°C, Hypotension requiring aggressive fluid resuscitation',
      ],
      threshold: '1 major OR ≥3 minor criteria',
      interpretation: 'Meeting severe CAP criteria mandates ICU admission. One major criterion alone is sufficient. If no major criterion, ≥3 minor criteria define severe CAP.',
      normalized_claim: 'Severe CAP: 1 major criterion (shock or ventilator) or ≥3 minor criteria (RR ≥30, P/F ≤250, multilobar, confusion, BUN ≥20, WBC <4k, platelets <100k, temp <36, hypotension).',
      provenance: { section: 'Defining Severe CAP', page_or_location: 'Table 2' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ATSIDSA.CAP.2019.T.01',
      display_id: 'ATSIDSA-CAP-T1',
      parameter: 'CURB-65 score — outpatient management',
      value: '0–1',
      clinical_meaning: 'CURB-65 0–1: low mortality risk (<3%). Outpatient treatment is appropriate if no other concerns (hypoxia, inability to tolerate PO, unstable social situation).',
      normalized_claim: 'CURB-65 0–1: outpatient treatment appropriate; mortality <3%.',
      direction: 'below',
      provenance: { section: 'Severity Assessment', page_or_location: 'Table 1' },
    },
    {
      threshold_id: 'PACK.ATSIDSA.CAP.2019.T.02',
      display_id: 'ATSIDSA-CAP-T2',
      parameter: 'CURB-65 score — hospital admission',
      value: '2',
      clinical_meaning: 'CURB-65 = 2: intermediate mortality risk (~9%). Consider hospital admission. Reassess for severe CAP criteria.',
      normalized_claim: 'CURB-65 = 2: consider hospital admission; mortality ~9%.',
      direction: 'above',
      provenance: { section: 'Severity Assessment', page_or_location: 'Table 1' },
    },
    {
      threshold_id: 'PACK.ATSIDSA.CAP.2019.T.03',
      display_id: 'ATSIDSA-CAP-T3',
      parameter: 'CURB-65 score — ICU consideration',
      value: '3–5',
      clinical_meaning: 'CURB-65 ≥3: high mortality risk (15–40%). Assess for ICU admission. Evaluate for severe CAP using ATS/IDSA major/minor criteria.',
      normalized_claim: 'CURB-65 ≥3: high mortality (15–40%); assess for ICU admission and severe CAP criteria.',
      direction: 'above',
      provenance: { section: 'Severity Assessment', page_or_location: 'Table 1' },
    },
    {
      threshold_id: 'PACK.ATSIDSA.CAP.2019.T.04',
      display_id: 'ATSIDSA-CAP-T4',
      parameter: 'PSI class',
      value: 'I–III',
      clinical_meaning: 'PSI class I–III (≤90 points): low risk, outpatient treatment appropriate. PSI class IV (91–130): inpatient. PSI class V (>130): ICU consideration.',
      normalized_claim: 'PSI I–III: outpatient. PSI IV (91–130): inpatient. PSI V (>130): consider ICU.',
      direction: 'range',
      provenance: { section: 'PSI Scoring', page_or_location: 'Recommendation 1' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ATSIDSA.CAP.2019.TX.01',
      display_id: 'ATSIDSA-CAP-TX1',
      action: 'Outpatient CAP: healthy adult without comorbidities or risk factors for resistant organisms',
      normalized_claim: 'Outpatient CAP (healthy, no comorbidities): amoxicillin 1g TID, OR doxycycline 100mg BID, OR macrolide (azithromycin 500mg day 1 then 250mg days 2–5) only if local resistance <25%.',
      timing: 'Initiate empiric therapy as soon as CAP diagnosis is made',
      condition: 'Outpatient CAP without comorbidities',
      drug_details: { drug: 'Amoxicillin (preferred)', dose: '1g three times daily', route: 'PO', duration: '5 days minimum' },
      provenance: { section: 'Outpatient Treatment', page_or_location: 'Recommendation 8' },
    },
    {
      step_id: 'PACK.ATSIDSA.CAP.2019.TX.02',
      display_id: 'ATSIDSA-CAP-TX2',
      action: 'Outpatient CAP: patient with comorbidities (chronic heart, lung, liver, or renal disease; diabetes; alcoholism; malignancy; asplenia)',
      normalized_claim: 'Outpatient CAP with comorbidities: amoxicillin-clavulanate or cephalosporin (cefpodoxime, cefuroxime) PLUS macrolide or doxycycline; OR respiratory fluoroquinolone monotherapy (levofloxacin 750mg or moxifloxacin 400mg).',
      timing: 'Initiate empiric therapy as soon as CAP diagnosis is made',
      condition: 'Outpatient CAP with comorbidities or prior antibiotic use within 90 days',
      drug_details: { drug: 'Amoxicillin-clavulanate + azithromycin OR respiratory fluoroquinolone', dose: 'Amox-clav 875/125 BID + azithromycin 500/250; OR levofloxacin 750mg daily', route: 'PO', duration: '5 days minimum' },
      provenance: { section: 'Outpatient Treatment', page_or_location: 'Recommendation 9' },
    },
    {
      step_id: 'PACK.ATSIDSA.CAP.2019.TX.03',
      display_id: 'ATSIDSA-CAP-TX3',
      action: 'Inpatient non-ICU CAP: standard empiric therapy',
      normalized_claim: 'Inpatient non-ICU CAP: beta-lactam (ampicillin-sulbactam 1.5–3g IV q6h, ceftriaxone 1–2g IV daily, or cefotaxime 1–2g IV q8h) PLUS macrolide (azithromycin 500mg IV/PO daily); OR respiratory fluoroquinolone monotherapy (levofloxacin 750mg or moxifloxacin 400mg IV/PO).',
      timing: 'Within 4 hours of presentation to hospital',
      condition: 'Inpatient non-ICU CAP without MRSA/Pseudomonas risk factors',
      drug_details: { drug: 'Ceftriaxone + azithromycin (preferred)', dose: 'Ceftriaxone 1–2g IV daily + azithromycin 500mg IV/PO daily', route: 'IV then step-down to PO', duration: '5 days minimum; extend if not clinically stable by day 5' },
      provenance: { section: 'Inpatient Non-ICU Treatment', page_or_location: 'Recommendation 10' },
    },
    {
      step_id: 'PACK.ATSIDSA.CAP.2019.TX.04',
      display_id: 'ATSIDSA-CAP-TX4',
      action: 'Inpatient ICU (severe CAP): empiric therapy',
      normalized_claim: 'Severe CAP (ICU): beta-lactam (ampicillin-sulbactam, ceftriaxone, or cefotaxime) PLUS macrolide (preferred) or respiratory fluoroquinolone. Add vancomycin or linezolid if MRSA risk. Add piperacillin-tazobactam, cefepime, or meropenem if Pseudomonas risk.',
      timing: 'Immediately upon ICU admission',
      condition: 'Severe CAP meeting ATS/IDSA major or minor criteria',
      drug_details: { drug: 'Ceftriaxone + azithromycin (base regimen)', dose: 'Ceftriaxone 2g IV daily + azithromycin 500mg IV daily', route: 'IV' },
      escalation: 'Add anti-MRSA (vancomycin 15–20mg/kg IV q8–12h or linezolid 600mg IV q12h) and/or anti-pseudomonal beta-lactam if risk factors present',
      provenance: { section: 'Severe CAP Treatment', page_or_location: 'Recommendations 11–14' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ATSIDSA.CAP.2019.RF.01',
      display_id: 'ATSIDSA-CAP-RF1',
      finding: 'Respiratory failure requiring mechanical ventilation: SpO2 <88% despite supplemental O2, severe tachypnea with accessory muscle use, altered mental status from hypoxia/hypercapnia',
      implication: 'Major criterion for severe CAP. Mandates ICU admission and intubation. Mortality significantly increased.',
      action: 'Endotracheal intubation and mechanical ventilation. ICU admission. Broad-spectrum antibiotics including ICU-level coverage. Consider ARDS protocol if P/F ratio <200.',
      urgency: 'immediate',
      provenance: { section: 'Severe CAP', page_or_location: 'Table 2' },
    },
    {
      flag_id: 'PACK.ATSIDSA.CAP.2019.RF.02',
      display_id: 'ATSIDSA-CAP-RF2',
      finding: 'Septic shock from CAP: hypotension (SBP <90 or MAP <65) persisting after adequate fluid resuscitation, requiring vasopressors',
      implication: 'Major criterion for severe CAP. In-hospital mortality 30–50%. Requires ICU admission and sepsis bundle within 1 hour.',
      action: 'Aggressive fluid resuscitation (30 mL/kg crystalloid within 3 hours). Vasopressors (norepinephrine first-line). Broad-spectrum antibiotics within 1 hour. Lactate monitoring. ICU admission.',
      urgency: 'immediate',
      provenance: { section: 'Severe CAP', page_or_location: 'Table 2' },
    },
    {
      flag_id: 'PACK.ATSIDSA.CAP.2019.RF.03',
      display_id: 'ATSIDSA-CAP-RF3',
      finding: 'Multilobar infiltrates with rapid progression on serial imaging',
      implication: 'Minor criterion for severe CAP. Suggests necrotizing or aggressive organism (S. aureus, Klebsiella, Legionella). Associated with higher treatment failure and mortality.',
      action: 'Broaden antibiotic coverage. Obtain blood and sputum cultures before antibiotics if not already done. Consider Legionella urine antigen. Monitor closely for clinical deterioration. Reassess for ICU transfer.',
      urgency: 'urgent',
      provenance: { section: 'Severe CAP Minor Criteria', page_or_location: 'Table 2' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ATSIDSA.CAP.2019.SEV.01',
      display_id: 'ATSIDSA-CAP-SEV1',
      level: 'Non-severe CAP',
      criteria: [
        'No major criteria for severe CAP (no shock, no ventilator requirement)',
        'Fewer than 3 minor criteria met',
        'CURB-65 0–2 or PSI class I–IV',
        'Hemodynamically stable',
        'Adequate oxygenation on low-flow O2 or room air',
      ],
      management_implications:
        'Outpatient management if CURB-65 0–1 or PSI I–III and able to tolerate PO. General medical floor if CURB-65 2 or PSI IV. Standard empiric antibiotic regimens. Minimum 5 days of therapy. Clinical stability criteria before discharge: temperature <37.8°C, HR <100, RR <24, SBP ≥90, SpO2 ≥90% on room air, ability to eat, normal mental status.',
      provenance: { section: 'Non-severe CAP Management', page_or_location: 'Recommendations 8–10' },
    },
    {
      severity_id: 'PACK.ATSIDSA.CAP.2019.SEV.02',
      display_id: 'ATSIDSA-CAP-SEV2',
      level: 'Severe CAP',
      criteria: [
        'At least 1 major criterion: septic shock requiring vasopressors OR respiratory failure requiring mechanical ventilation',
        'OR ≥3 minor criteria: RR ≥30, PaO2/FiO2 ≤250, multilobar infiltrates, confusion, BUN ≥20, WBC <4000, platelets <100,000, hypothermia <36°C, hypotension needing aggressive fluids',
      ],
      management_implications:
        'ICU admission mandatory. Combination antibiotic therapy (beta-lactam + macrolide preferred over beta-lactam + fluoroquinolone for mortality benefit). Blood cultures and sputum cultures before antibiotics. Assess for MRSA/Pseudomonas risk factors and add coverage if present. Daily reassessment for de-escalation when cultures return. Consider corticosteroids if refractory shock.',
      provenance: { section: 'Severe CAP Criteria and Management', page_or_location: 'Table 2, Recommendations 11–14' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for CAP. Covers severity assessment, disposition decision-making, empiric antibiotic regimens by treatment setting, and MRSA/Pseudomonas risk stratification for USMLE Step 2 CK question generation.',

  all_item_ids: [
    'PACK.ATSIDSA.CAP.2019.REC.01', 'PACK.ATSIDSA.CAP.2019.REC.02', 'PACK.ATSIDSA.CAP.2019.REC.03',
    'PACK.ATSIDSA.CAP.2019.REC.04', 'PACK.ATSIDSA.CAP.2019.REC.05',
    'PACK.ATSIDSA.CAP.2019.DC.01', 'PACK.ATSIDSA.CAP.2019.DC.02',
    'PACK.ATSIDSA.CAP.2019.T.01', 'PACK.ATSIDSA.CAP.2019.T.02', 'PACK.ATSIDSA.CAP.2019.T.03',
    'PACK.ATSIDSA.CAP.2019.T.04',
    'PACK.ATSIDSA.CAP.2019.TX.01', 'PACK.ATSIDSA.CAP.2019.TX.02', 'PACK.ATSIDSA.CAP.2019.TX.03',
    'PACK.ATSIDSA.CAP.2019.TX.04',
    'PACK.ATSIDSA.CAP.2019.RF.01', 'PACK.ATSIDSA.CAP.2019.RF.02', 'PACK.ATSIDSA.CAP.2019.RF.03',
    'PACK.ATSIDSA.CAP.2019.SEV.01', 'PACK.ATSIDSA.CAP.2019.SEV.02',
  ],
  all_display_ids: [
    'ATSIDSA-CAP-R1', 'ATSIDSA-CAP-R2', 'ATSIDSA-CAP-R3', 'ATSIDSA-CAP-R4', 'ATSIDSA-CAP-R5',
    'ATSIDSA-CAP-DC1', 'ATSIDSA-CAP-DC2',
    'ATSIDSA-CAP-T1', 'ATSIDSA-CAP-T2', 'ATSIDSA-CAP-T3', 'ATSIDSA-CAP-T4',
    'ATSIDSA-CAP-TX1', 'ATSIDSA-CAP-TX2', 'ATSIDSA-CAP-TX3', 'ATSIDSA-CAP-TX4',
    'ATSIDSA-CAP-RF1', 'ATSIDSA-CAP-RF2', 'ATSIDSA-CAP-RF3',
    'ATSIDSA-CAP-SEV1', 'ATSIDSA-CAP-SEV2',
  ],
};
