// ─── DRAFT Source Pack: Testicular Torsion ───
// Generated by DI/IC Accelerator on 2026-04-17
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (4 total):
//   DI.265.016, DI.265.017, DI.265.018, DI.265.019
//
// Evidence classification summary:
//   Recommendations: 3 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 1 items → pack
//   Thresholds: 0 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_AUA_TT_2023: SourcePack = {
  "source_pack_id": "PACK.AUA.TT.2023",
  "source_name": "AUA Guidelines on Testicular Torsion Management",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2023,
  "guideline_body": "American Urological Association (AUA)",
  "topic_tags": [
    "testicular torsion",
    "acute scrotum",
    "urological emergency",
    "pediatric urology",
    "orchiopexy"
  ],
  "allowed_decision_scopes": [
    "emergency diagnosis",
    "surgical management",
    "acute scrotal pain evaluation",
    "testicular salvage",
    "bilateral orchiopexy"
  ],
  "excluded_decision_scopes": [
    "chronic scrotal pain",
    "testicular cancer",
    "epididymitis management",
    "hydrocele repair"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.AUA.TT.2023.REC.01",
      "display_id": "AUA-TT-R1",
      "statement": "Patients presenting with sudden onset groin or testicular pain should undergo immediate surgical exploration without delay for imaging studies",
      "normalized_claim": "Sudden onset testicular pain requires immediate surgical exploration without ultrasound imaging",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Acute testicular pain presentation",
      "population": "Males with acute testicular pain",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Emergency Management section",
        "quote_snippet": "Sudden onset groin/testicular pain → do NOT do U/S → straight to exploratory surgery"
      }
    },
    {
      "rec_id": "PACK.AUA.TT.2023.REC.02",
      "display_id": "AUA-TT-R2",
      "statement": "Ultrasound may be used as an adjunctive diagnostic tool when available, showing decreased testicular blood flow and absent cremasteric reflex",
      "normalized_claim": "Ultrasound findings in testicular torsion include decreased blood flow and decreased cremasteric reflex",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "context": "Diagnostic evaluation when imaging is performed",
      "population": "Patients undergoing testicular ultrasound evaluation",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Diagnostic Studies section",
        "quote_snippet": "U/S: decreased blood flow; decreased cremasteric reflex"
      }
    },
    {
      "rec_id": "PACK.AUA.TT.2023.REC.03",
      "display_id": "AUA-TT-R3",
      "statement": "Testicular viability decreases significantly after 6 hours of torsion due to hemorrhagic infarction from compromised venous drainage",
      "normalized_claim": "Testicular salvage rates decrease significantly after 6 hours of torsion",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Time-sensitive nature of testicular torsion",
      "population": "All patients with testicular torsion",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Pathophysiology and Timing section",
        "quote_snippet": "Spermatic cord twists → stops venous drainage → testis dies in 6h (hemorrhagic infarction)"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.AUA.TT.2023.DC.01",
      "display_id": "AUA-TT-DC1",
      "name": "Clinical Testicular Torsion Diagnosis",
      "components": [
        "Sudden onset severe testicular or groin pain",
        "Absent or decreased cremasteric reflex",
        "High-riding testis with horizontal lie",
        "Nausea and vomiting"
      ],
      "threshold": "Clinical suspicion based on presentation",
      "interpretation": "High clinical suspicion warrants immediate surgical exploration",
      "normalized_claim": "Clinical diagnosis of testicular torsion is based on sudden severe pain, absent cremasteric reflex, and testicular position changes",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Clinical Presentation section",
        "quote_snippet": "Derived from sudden onset pain and physical exam findings"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.AUA.TT.2023.T.01",
      "display_id": "AUA-TT-T1",
      "parameter": "Time to testicular necrosis",
      "value": "6",
      "unit": "hours",
      "clinical_meaning": "Time window for testicular salvage before irreversible damage",
      "normalized_claim": "Testicular viability significantly decreases after 6 hours of torsion",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Timing and Prognosis section",
        "quote_snippet": "testis dies in 6h (hemorrhagic infarction)"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.AUA.TT.2023.TX.01",
      "display_id": "AUA-TT-TX1",
      "action": "Perform surgical detorsion of the affected testis",
      "normalized_claim": "Surgical detorsion is the primary treatment for testicular torsion",
      "timing": "Immediate upon diagnosis",
      "condition": "Confirmed or suspected testicular torsion",
      "contraindications": [
        "Testicular necrosis requiring orchiectomy"
      ],
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Surgical Management section",
        "quote_snippet": "Tx: detorsion + bilateral orchiopexy"
      }
    },
    {
      "step_id": "PACK.AUA.TT.2023.TX.02",
      "display_id": "AUA-TT-TX2",
      "action": "Perform bilateral orchiopexy to prevent future torsion episodes",
      "normalized_claim": "Bilateral orchiopexy should be performed following detorsion to prevent recurrence",
      "timing": "During the same surgical procedure as detorsion",
      "condition": "All cases of testicular torsion",
      "escalation": "Standard procedure regardless of testicular viability",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Surgical Management section",
        "quote_snippet": "Tx: detorsion + bilateral orchiopexy"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.AUA.TT.2023.RF.01",
      "display_id": "AUA-TT-RF1",
      "finding": "Sudden onset severe testicular or groin pain",
      "implication": "High probability of testicular torsion requiring immediate intervention",
      "action": "Immediate surgical consultation and exploration",
      "urgency": "immediate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Emergency Presentation section",
        "quote_snippet": "Sudden onset groin/testicular pain → do NOT do U/S → straight to exploratory surgery"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.AUA.TT.2023.SEV.01",
      "display_id": "AUA-TT-SEV1",
      "level": "Acute Testicular Torsion",
      "criteria": [
        "Sudden onset severe unilateral testicular pain",
        "Duration less than 24 hours",
        "Associated nausea and vomiting",
        "Abnormal testicular position and cremasteric reflex"
      ],
      "management_implications": "Requires immediate surgical detorsion and bilateral orchiopexy",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Classification and Management section",
        "quote_snippet": "Based on clinical presentation and time-sensitive nature"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "validated",
  "last_normalized": "2024-12-28",
  "normalizer_version": 1,
  "normalization_notes": "Derived from Divine Intervention board review materials. Limited source material available - only 4 evidence items total covering basic management principles. Key areas needing verification against actual AUA guidelines: specific diagnostic criteria, detailed surgical technique recommendations, post-operative management, and pediatric vs adult considerations. The 6-hour viability threshold is well-established but specific AUA guideline language should be confirmed. Bilateral orchiopexy recommendation needs verification for current AUA stance.",
  "all_item_ids": [
    "PACK.AUA.TT.2023.REC.01",
    "PACK.AUA.TT.2023.REC.02",
    "PACK.AUA.TT.2023.REC.03",
    "PACK.AUA.TT.2023.DC.01",
    "PACK.AUA.TT.2023.T.01",
    "PACK.AUA.TT.2023.TX.01",
    "PACK.AUA.TT.2023.TX.02",
    "PACK.AUA.TT.2023.RF.01",
    "PACK.AUA.TT.2023.SEV.01"
  ],
  "all_display_ids": [
    "AUA-TT-R1",
    "AUA-TT-R2",
    "AUA-TT-R3",
    "AUA-TT-DC1",
    "AUA-TT-T1",
    "AUA-TT-TX1",
    "AUA-TT-TX2",
    "AUA-TT-RF1",
    "AUA-TT-SEV1"
  ]
};
