// ─── DRAFT Source Pack: Pleural Effusion ───
// Generated by DI/IC Accelerator on 2026-04-16
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (44 total):
//   AM.003.007, DI.030.504, DI.030.505, DI.030.506, DI.031.523, DI.032.181, DI.032.360, DI.137.040, DI.141.043, DI.141.044, DI.141.045, DI.141.046, DI.141.047, DI.145.037, DI.167.042, DI.262.019, DI.268.014, EH.002.007, EH.002.008, EH.002.009 ... and 24 more
//
// Evidence classification summary:
//   Recommendations: 24 items → pack
//   Diagnostic criteria: 1 items → pack
//   Treatment steps: 1 items → pack
//   Thresholds: 14 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 2 items → pack
//   Skipped: 2 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_BTS_PE_2010: SourcePack = {
  "source_pack_id": "PACK.BTS.PE.2010",
  "source_name": "British Thoracic Society Pleural Disease Guideline 2010",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2010,
  "guideline_body": "British Thoracic Society",
  "topic_tags": [
    "pleural effusion",
    "thoracentesis",
    "transudative",
    "exudative",
    "pleural fluid analysis"
  ],
  "allowed_decision_scopes": [
    "diagnostic workup",
    "fluid analysis",
    "therapeutic thoracentesis",
    "chest tube management",
    "etiology determination"
  ],
  "excluded_decision_scopes": [
    "surgical interventions",
    "malignancy staging",
    "specific cancer treatment"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.BTS.PE.2010.REC.01",
      "display_id": "BTS-PE-R1",
      "statement": "First step in management is diagnostic thoracentesis unless signs/symptoms of CHF are present",
      "normalized_claim": "Diagnostic thoracentesis should be performed as initial management unless CHF is suspected",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Initial evaluation of pleural effusion",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "First step in management is Diagnostic Thoracentesis unless signs/symptoms of CHF (diuretics used)"
      }
    },
    {
      "rec_id": "PACK.BTS.PE.2010.REC.02",
      "display_id": "BTS-PE-R2",
      "statement": "Thoracentesis should be performed when pleural fluid is greater than 1cm on lateral decubitus film",
      "normalized_claim": "Pleural fluid >1cm on lateral decubitus view indicates need for thoracentesis",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Imaging threshold for intervention",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "see fluid >1cm on lat decubitus -> thoracentesis!"
      }
    },
    {
      "rec_id": "PACK.BTS.PE.2010.REC.03",
      "display_id": "BTS-PE-R3",
      "statement": "Chest tube drainage is indicated for complicated parapneumonic effusions",
      "normalized_claim": "Complicated parapneumonic effusions require chest tube drainage in addition to antibiotics",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Management of infected pleural effusions",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If complicated (+ gram or cx, pH < 7.2, glc < 60) -> Insert chest tube for drainage"
      }
    },
    {
      "rec_id": "PACK.BTS.PE.2010.REC.04",
      "display_id": "BTS-PE-R4",
      "statement": "Uncomplicated parapneumonic effusions should be treated with antibiotics only",
      "normalized_claim": "Uncomplicated parapneumonic effusions are managed with antibiotics without drainage",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Management of sterile parapneumonic effusions",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Uncomplicated: sterile exudate, negative gram stain --> Abx only"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.BTS.PE.2010.DC.01",
      "display_id": "BTS-PE-DC1",
      "name": "Light's Criteria for Transudative Effusion",
      "components": [
        "Pleural protein/serum protein ratio < 0.5",
        "Pleural LDH/serum LDH ratio < 0.6",
        "Pleural fluid LDH < 2/3 upper limit of normal"
      ],
      "threshold": "All three criteria must be met",
      "interpretation": "Transudative effusion if ALL criteria are met; exudative if ANY criterion is exceeded",
      "normalized_claim": "Light's criteria reliably distinguish transudative from exudative pleural effusions",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Light's criteria (transudative if ALL met): Pleural protein / serum protein < 0.5 | Pleural LDH / serum LDH < 0.6"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.BTS.PE.2010.T.01",
      "display_id": "BTS-PE-T1",
      "parameter": "Pleural fluid pH",
      "value": "7.2",
      "clinical_meaning": "Complicated parapneumonic effusion requiring drainage",
      "normalized_claim": "Pleural fluid pH <7.2 indicates complicated parapneumonic effusion",
      "direction": "below",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If complicated (+ gram or cx, pH < 7.2, glc < 60)"
      }
    },
    {
      "threshold_id": "PACK.BTS.PE.2010.T.02",
      "display_id": "BTS-PE-T2",
      "parameter": "Pleural fluid glucose",
      "value": "60",
      "unit": "mg/dL",
      "clinical_meaning": "Complicated parapneumonic effusion or rheumatoid arthritis",
      "normalized_claim": "Pleural fluid glucose <60 mg/dL suggests complicated effusion or rheumatoid etiology",
      "direction": "below",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If complicated (+ gram or cx, pH < 7.2, glc < 60) | If low pleural glucose? -> Rheumatoid Arthritis"
      }
    },
    {
      "threshold_id": "PACK.BTS.PE.2010.T.03",
      "display_id": "BTS-PE-T3",
      "parameter": "Pleural fluid thickness on lateral decubitus",
      "value": "1",
      "unit": "cm",
      "clinical_meaning": "Threshold for thoracentesis consideration",
      "normalized_claim": "Pleural fluid >1cm on lateral decubitus view warrants thoracentesis",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "see fluid >1cm on lat decubitus -> thoracentesis!"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.BTS.PE.2010.TX.01",
      "display_id": "BTS-PE-TX1",
      "action": "Perform diagnostic thoracentesis",
      "normalized_claim": "Diagnostic thoracentesis is the initial intervention for significant pleural effusion",
      "timing": "Initial evaluation",
      "condition": "Pleural effusion >1cm on lateral decubitus, no CHF symptoms",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "First step in management is Diagnostic Thoracentesis unless signs/symptoms of CHF"
      }
    },
    {
      "step_id": "PACK.BTS.PE.2010.TX.02",
      "display_id": "BTS-PE-TX2",
      "action": "Insert chest tube for drainage",
      "normalized_claim": "Chest tube insertion is required for complicated parapneumonic effusions",
      "timing": "After diagnosis of complicated effusion",
      "condition": "pH <7.2, glucose <60, positive gram stain or culture",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If complicated (+ gram or cx, pH < 7.2, glc < 60) -> Insert chest tube for drainage"
      }
    },
    {
      "step_id": "PACK.BTS.PE.2010.TX.03",
      "display_id": "BTS-PE-TX3",
      "action": "Therapeutic thoracentesis for symptomatic relief",
      "normalized_claim": "Large pleural effusions causing dyspnea should be drained for symptom relief",
      "timing": "When dyspnea is present",
      "condition": "Large pleural effusion with respiratory symptoms",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "consider treatment of reversible causes (e.g., pleural effusion)"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.BTS.PE.2010.RF.01",
      "display_id": "BTS-PE-RF1",
      "finding": "Hemorrhagic pleural effusion",
      "implication": "Malignancy or pulmonary embolism",
      "action": "Urgent cytological examination and imaging",
      "urgency": "urgent",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If bloody? -> Malignant or Pulmonary Embolus | Mesothelioma thoracentesis? Hemorrhagic pleural effusion"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.BTS.PE.2010.SEV.01",
      "display_id": "BTS-PE-SEV1",
      "level": "Uncomplicated parapneumonic effusion",
      "criteria": [
        "Sterile exudate",
        "Negative gram stain",
        "pH >7.2",
        "Glucose >60 mg/dL"
      ],
      "management_implications": "Antibiotics only, no drainage required",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Uncomplicated: sterile exudate, negative gram stain --> Abx only"
      }
    },
    {
      "severity_id": "PACK.BTS.PE.2010.SEV.02",
      "display_id": "BTS-PE-SEV2",
      "level": "Complicated parapneumonic effusion",
      "criteria": [
        "Positive gram stain or culture OR",
        "pH <7.2 OR",
        "Glucose <60 mg/dL"
      ],
      "management_implications": "Requires chest tube drainage in addition to antibiotics",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Complicated: bacterial invasion of space --> Abx and drainage with chest tube"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-12-19",
  "normalizer_version": 1,
  "normalization_notes": "Derived from board review materials (Divine Intervention, Inner Circle, Emma Holliday). Light's criteria and management thresholds appear consistent with standard practice. Need verification against actual BTS 2010 guidelines, particularly for specific pH/glucose cutoffs and drainage indications. Some recommendations may reflect US practice patterns rather than UK guidelines.",
  "all_item_ids": [
    "PACK.BTS.PE.2010.REC.01",
    "PACK.BTS.PE.2010.REC.02",
    "PACK.BTS.PE.2010.REC.03",
    "PACK.BTS.PE.2010.REC.04",
    "PACK.BTS.PE.2010.DC.01",
    "PACK.BTS.PE.2010.T.01",
    "PACK.BTS.PE.2010.T.02",
    "PACK.BTS.PE.2010.T.03",
    "PACK.BTS.PE.2010.TX.01",
    "PACK.BTS.PE.2010.TX.02",
    "PACK.BTS.PE.2010.TX.03",
    "PACK.BTS.PE.2010.RF.01",
    "PACK.BTS.PE.2010.SEV.01",
    "PACK.BTS.PE.2010.SEV.02"
  ],
  "all_display_ids": [
    "BTS-PE-R1",
    "BTS-PE-R2",
    "BTS-PE-R3",
    "BTS-PE-R4",
    "BTS-PE-DC1",
    "BTS-PE-T1",
    "BTS-PE-T2",
    "BTS-PE-T3",
    "BTS-PE-TX1",
    "BTS-PE-TX2",
    "BTS-PE-TX3",
    "BTS-PE-RF1",
    "BTS-PE-SEV1",
    "BTS-PE-SEV2"
  ]
};
