import type { SourcePack } from './types';

export const PACK_CDC_STI_2021: SourcePack = {
  source_pack_id: 'PACK.CDC.STI.2021',
  source_name: 'CDC Sexually Transmitted Infections Treatment Guidelines, 2021',
  canonical_url: 'https://www.cdc.gov/std/treatment-guidelines/',
  publication_year: 2021,
  guideline_body: 'CDC',

  topic_tags: ['STI', 'Chlamydia', 'Gonorrhea', 'Syphilis', 'PID', 'Genital Herpes', 'Infectious Disease'],
  allowed_decision_scopes: [
    'chlamydia treatment',
    'gonorrhea treatment',
    'syphilis staging and treatment',
    'neurosyphilis diagnosis and treatment',
    'PID empiric treatment',
    'genital herpes treatment — primary and suppressive',
    'STI screening recommendations',
    'co-infection management',
    'Jarisch-Herxheimer reaction recognition',
    'RPR/VDRL and confirmatory testing',
  ],
  excluded_decision_scopes: [
    'HIV management (covered in separate pack)',
    'hepatitis B/C treatment',
    'HPV vaccination schedules',
    'cervical cancer screening protocols',
    'sexual assault prophylaxis details',
  ],

  recommendations: [
    {
      rec_id: 'PACK.CDC.STI.2021.REC.01',
      display_id: 'CDC-STI-R1',
      statement: 'Doxycycline 100mg BID for 7 days is the recommended first-line treatment for uncomplicated chlamydial infection.',
      normalized_claim: 'Chlamydia treatment: doxycycline 100mg BID x 7 days (first-line). Azithromycin 1g single dose is alternative. Treat all sexual partners.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'Doxycycline preferred over azithromycin based on superior efficacy data, particularly for rectal chlamydia',
      provenance: { section: 'Chlamydial Infections', page_or_location: 'Chlamydia Treatment Section' },
    },
    {
      rec_id: 'PACK.CDC.STI.2021.REC.02',
      display_id: 'CDC-STI-R2',
      statement: 'Ceftriaxone 500mg IM single dose is the recommended treatment for uncomplicated gonococcal infection of the cervix, urethra, or rectum. For patients weighing >=150 kg, use 1g IM.',
      normalized_claim: 'Gonorrhea treatment: ceftriaxone 500mg IM x 1 (1g if >=150kg). Test of cure at 7-14 days for pharyngeal GC. Always test for concurrent chlamydia.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Gonococcal Infections', page_or_location: 'Gonorrhea Treatment Section' },
    },
    {
      rec_id: 'PACK.CDC.STI.2021.REC.03',
      display_id: 'CDC-STI-R3',
      statement: 'When gonorrhea is diagnosed, empiric treatment for chlamydia should be provided if chlamydia has not been excluded by testing.',
      normalized_claim: 'Always treat for chlamydia when gonorrhea is diagnosed unless chlamydia has been ruled out by NAAT. Dual therapy addresses frequent co-infection.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Gonococcal Infections', page_or_location: 'Gonorrhea Treatment Section' },
    },
    {
      rec_id: 'PACK.CDC.STI.2021.REC.04',
      display_id: 'CDC-STI-R4',
      statement: 'Benzathine penicillin G 2.4 million units IM single dose is the recommended treatment for primary, secondary, and early latent syphilis (<1 year duration).',
      normalized_claim: 'Early syphilis (primary, secondary, early latent): benzathine penicillin G 2.4M units IM x 1. Late latent or tertiary: 2.4M units IM weekly x 3 weeks.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Syphilis', page_or_location: 'Syphilis Treatment Section' },
    },
    {
      rec_id: 'PACK.CDC.STI.2021.REC.05',
      display_id: 'CDC-STI-R5',
      statement: 'All patients diagnosed with syphilis should be tested for HIV. Syphilis screening uses nontreponemal test (RPR/VDRL) with confirmatory treponemal test (FTA-ABS or TP-PA).',
      normalized_claim: 'Syphilis screening: RPR/VDRL (nontreponemal, quantitative) then FTA-ABS or TP-PA (treponemal, confirmatory). All syphilis patients need HIV testing.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Syphilis Diagnosis', page_or_location: 'Syphilis Screening Section' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.CDC.STI.2021.DC.01',
      display_id: 'CDC-STI-DC1',
      name: 'Syphilis Staging',
      components: [
        'Primary: painless chancre at inoculation site (3-90 days after exposure)',
        'Secondary: diffuse maculopapular rash (including palms and soles), condylomata lata, mucous patches, lymphadenopathy (6 weeks-6 months)',
        'Latent: positive serology, no clinical manifestations (early latent <1 year; late latent >1 year or unknown duration)',
        'Tertiary: gummas, cardiovascular syphilis (aortitis), neurosyphilis (any stage)',
      ],
      interpretation: 'Staging determines treatment duration. Neurosyphilis can occur at any stage and requires IV penicillin G. RPR titer >1:32 or neurologic symptoms warrant LP.',
      normalized_claim: 'Syphilis stages: primary (chancre), secondary (rash on palms/soles, condylomata lata), latent (seropositive, asymptomatic), tertiary (gummas, aortitis). Neurosyphilis possible at any stage.',
      provenance: { section: 'Syphilis', page_or_location: 'Syphilis Staging Section' },
    },
    {
      criterion_id: 'PACK.CDC.STI.2021.DC.02',
      display_id: 'CDC-STI-DC2',
      name: 'PID Clinical Diagnosis',
      components: [
        'Minimum criteria: cervical motion tenderness, uterine tenderness, or adnexal tenderness',
        'Supporting criteria: oral temperature >38.3C, cervical mucopurulent discharge, abundant WBCs on saline microscopy, elevated ESR/CRP, cervical infection with GC or CT',
        'Definitive criteria: endometrial biopsy showing endometritis, transvaginal ultrasound or MRI showing tubo-ovarian abscess, laparoscopic findings consistent with PID',
      ],
      interpretation: 'Low threshold for empiric treatment due to consequences of missed PID (infertility, ectopic pregnancy, chronic pain). Minimum criteria sufficient to initiate treatment.',
      normalized_claim: 'PID diagnosis: low threshold. Minimum criteria = cervical motion / uterine / adnexal tenderness. Empiric treatment with minimum criteria to prevent sequelae (infertility, ectopic).',
      provenance: { section: 'PID', page_or_location: 'PID Section' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.CDC.STI.2021.T.01',
      display_id: 'CDC-STI-T1',
      parameter: 'RPR titer for treatment response',
      value: '4-fold decline',
      clinical_meaning: 'Adequate treatment response = 4-fold decline in RPR titer (e.g., 1:32 to 1:8) within 6-12 months for early syphilis. Failure to decline suggests treatment failure or reinfection.',
      normalized_claim: '4-fold RPR titer decline within 6-12 months confirms adequate syphilis treatment response. No decline = treatment failure or reinfection requiring re-evaluation.',
      direction: 'below',
      provenance: { section: 'Syphilis Follow-up', page_or_location: 'Syphilis Management Section' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.CDC.STI.2021.TX.01',
      display_id: 'CDC-STI-TX1',
      action: 'Uncomplicated chlamydia treatment',
      normalized_claim: 'Chlamydia: doxycycline 100mg BID x 7 days (first-line). Pregnancy: azithromycin 1g PO x 1. Treat partners. Retest at 3 months.',
      timing: 'At diagnosis',
      condition: 'Uncomplicated chlamydial infection (cervicitis, urethritis, proctitis)',
      drug_details: { drug: 'Doxycycline', dose: '100mg BID', route: 'PO', duration: '7 days' },
      contraindications: ['Pregnancy (use azithromycin instead)'],
      provenance: { section: 'Chlamydial Infections', page_or_location: 'Chlamydia Treatment Section' },
    },
    {
      step_id: 'PACK.CDC.STI.2021.TX.02',
      display_id: 'CDC-STI-TX2',
      action: 'Uncomplicated gonorrhea treatment',
      normalized_claim: 'Gonorrhea: ceftriaxone 500mg IM x 1 dose. Add doxycycline 100mg BID x 7 days if chlamydia not excluded. Test of cure for pharyngeal GC.',
      timing: 'At diagnosis',
      condition: 'Uncomplicated gonococcal infection (cervix, urethra, rectum)',
      drug_details: { drug: 'Ceftriaxone', dose: '500mg', route: 'IM single dose' },
      contraindications: ['Cephalosporin allergy (use gentamicin 240mg IM + azithromycin 2g PO)'],
      provenance: { section: 'Gonococcal Infections', page_or_location: 'Gonorrhea Treatment Section' },
    },
    {
      step_id: 'PACK.CDC.STI.2021.TX.03',
      display_id: 'CDC-STI-TX3',
      action: 'PID empiric treatment',
      normalized_claim: 'PID outpatient: ceftriaxone 500mg IM x 1 + doxycycline 100mg BID x 14 days +/- metronidazole 500mg BID x 14 days. Inpatient: IV cefotetan/cefoxitin + doxy, or IV clindamycin + gentamicin.',
      timing: 'Empiric, at time of clinical diagnosis',
      condition: 'PID (cervical motion tenderness + uterine/adnexal tenderness)',
      drug_details: { drug: 'Ceftriaxone + doxycycline +/- metronidazole', dose: '500mg IM + 100mg BID + 500mg BID', route: 'IM + PO' },
      escalation: 'Hospitalize if: TOA suspected, pregnancy, unable to tolerate PO, no response to outpatient therapy in 72 hours',
      provenance: { section: 'PID', page_or_location: 'PID Treatment Section' },
    },
    {
      step_id: 'PACK.CDC.STI.2021.TX.04',
      display_id: 'CDC-STI-TX4',
      action: 'Neurosyphilis treatment',
      normalized_claim: 'Neurosyphilis: aqueous crystalline penicillin G 3-4 million units IV q4h (18-24M units/day) x 10-14 days. No adequate alternative for penicillin-allergic patients; desensitize.',
      timing: 'Immediately upon diagnosis',
      condition: 'Neurosyphilis (any stage syphilis with CSF abnormalities, neurologic symptoms, or ocular/otic involvement)',
      drug_details: { drug: 'Aqueous crystalline penicillin G', dose: '3-4 million units q4h', route: 'IV', duration: '10-14 days' },
      contraindications: ['Penicillin allergy requires desensitization — no adequate alternative for neurosyphilis'],
      provenance: { section: 'Neurosyphilis', page_or_location: 'Neurosyphilis Treatment Section' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.CDC.STI.2021.RF.01',
      display_id: 'CDC-STI-RF1',
      finding: 'Jarisch-Herxheimer reaction: fever, rigors, myalgias, hypotension within 24 hours of initiating syphilis treatment',
      implication: 'Immune response to treponemal antigen release from killed spirochetes. Self-limited (12-24h). More common in early syphilis. Can precipitate preterm labor in pregnant patients.',
      action: 'Supportive care (antipyretics, IV fluids). Warn patients before treatment. Do NOT stop antibiotics. In pregnancy, monitor for preterm contractions.',
      urgency: 'urgent',
      provenance: { section: 'Syphilis', page_or_location: 'Jarisch-Herxheimer Section' },
    },
    {
      flag_id: 'PACK.CDC.STI.2021.RF.02',
      display_id: 'CDC-STI-RF2',
      finding: 'Disseminated gonococcal infection (DGI): triad of tenosynovitis, dermatitis (painless pustular skin lesions), migratory polyarthralgia progressing to septic arthritis',
      implication: 'Hematogenous spread of N. gonorrhoeae. Can cause septic arthritis, endocarditis, meningitis. Requires parenteral treatment.',
      action: 'Blood cultures, joint fluid culture (if septic arthritis). IV ceftriaxone 1g daily until 24-48h improvement, then step down to PO cefixime 400mg BID to complete 7 days total.',
      urgency: 'urgent',
      provenance: { section: 'Disseminated GC', page_or_location: 'DGI Section' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.CDC.STI.2021.SEV.01',
      display_id: 'CDC-STI-SEV1',
      level: 'Uncomplicated STI (chlamydia, gonorrhea)',
      criteria: [
        'Localized infection (cervicitis, urethritis, proctitis)',
        'No systemic symptoms',
        'No evidence of upper tract spread',
      ],
      management_implications:
        'Outpatient treatment with appropriate antibiotics. Partner notification and treatment. Retest at 3 months for reinfection. No test of cure needed except for pharyngeal gonorrhea.',
      provenance: { section: 'General Principles', page_or_location: 'Overview' },
    },
    {
      severity_id: 'PACK.CDC.STI.2021.SEV.02',
      display_id: 'CDC-STI-SEV2',
      level: 'Complicated STI (PID, DGI, neurosyphilis)',
      criteria: [
        'Ascending infection (PID: endometritis, salpingitis, TOA)',
        'Disseminated infection (DGI, secondary syphilis with end-organ involvement)',
        'CNS involvement (neurosyphilis, ocular syphilis, otosyphilis)',
      ],
      management_implications:
        'Parenteral antibiotics often required. Hospitalization for PID with TOA, DGI, or neurosyphilis. Extended treatment courses. Long-term follow-up with serologic monitoring for syphilis. Fertility counseling for PID.',
      provenance: { section: 'Complicated Infections', page_or_location: 'Various Sections' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for STI treatment. Covers chlamydia (doxycycline), gonorrhea (ceftriaxone), syphilis staging and treatment (benzathine PCN), PID empiric therapy, neurosyphilis, DGI, and Jarisch-Herxheimer.',

  all_item_ids: [
    'PACK.CDC.STI.2021.REC.01', 'PACK.CDC.STI.2021.REC.02', 'PACK.CDC.STI.2021.REC.03',
    'PACK.CDC.STI.2021.REC.04', 'PACK.CDC.STI.2021.REC.05',
    'PACK.CDC.STI.2021.DC.01', 'PACK.CDC.STI.2021.DC.02',
    'PACK.CDC.STI.2021.T.01',
    'PACK.CDC.STI.2021.TX.01', 'PACK.CDC.STI.2021.TX.02', 'PACK.CDC.STI.2021.TX.03',
    'PACK.CDC.STI.2021.TX.04',
    'PACK.CDC.STI.2021.RF.01', 'PACK.CDC.STI.2021.RF.02',
    'PACK.CDC.STI.2021.SEV.01', 'PACK.CDC.STI.2021.SEV.02',
  ],
  all_display_ids: [
    'CDC-STI-R1', 'CDC-STI-R2', 'CDC-STI-R3', 'CDC-STI-R4', 'CDC-STI-R5',
    'CDC-STI-DC1', 'CDC-STI-DC2',
    'CDC-STI-T1',
    'CDC-STI-TX1', 'CDC-STI-TX2', 'CDC-STI-TX3', 'CDC-STI-TX4',
    'CDC-STI-RF1', 'CDC-STI-RF2',
    'CDC-STI-SEV1', 'CDC-STI-SEV2',
  ],
};
