import type { SourcePack } from './types';

export const PACK_CHEST_VTE_2021: SourcePack = {
  source_pack_id: 'PACK.CHEST.VTE.2021',
  source_name: 'CHEST 2021 Guideline for Antithrombotic Therapy for VTE Disease',
  source_registry_id: 'REG.CHEST.VTE',
  canonical_url: 'https://doi.org/10.1016/j.chest.2021.07.056',
  publication_year: 2021,
  guideline_body: 'CHEST',

  topic_tags: ['DVT', 'PE', 'VTE', 'Anticoagulation', 'Hematology'],
  allowed_decision_scopes: [
    'DVT pre-test probability assessment',
    'DVT diagnostic workup',
    'anticoagulant selection for VTE',
    'anticoagulation duration',
    'provoked vs unprovoked VTE management',
    'IVC filter indications',
    'VTE in cancer',
    'VTE in pregnancy',
    'recurrent VTE management',
  ],
  excluded_decision_scopes: [
    'PE hemodynamic management',
    'thrombolysis for massive PE',
    'surgical thrombectomy',
    'chronic thromboembolic pulmonary hypertension',
    'antiphospholipid syndrome long-term management',
  ],

  recommendations: [
    {
      rec_id: 'PACK.CHEST.VTE.2021.REC.01',
      display_id: 'CHEST-VTE-R1',
      statement: 'In patients with suspected first lower-extremity DVT, use a validated clinical prediction rule (Wells score) to estimate pre-test probability before diagnostic testing.',
      normalized_claim: 'Wells score should be used to stratify DVT pre-test probability before imaging or D-dimer.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Diagnosis of DVT', page_or_location: 'Section 2.1' },
    },
    {
      rec_id: 'PACK.CHEST.VTE.2021.REC.02',
      display_id: 'CHEST-VTE-R2',
      statement: 'In patients with low pre-test probability for DVT, obtain a high-sensitivity D-dimer. If negative, DVT is excluded without need for imaging.',
      normalized_claim: 'Low Wells score + negative D-dimer excludes DVT; no ultrasound needed.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Diagnosis of DVT', page_or_location: 'Section 2.2' },
    },
    {
      rec_id: 'PACK.CHEST.VTE.2021.REC.03',
      display_id: 'CHEST-VTE-R3',
      statement: 'For patients with VTE not associated with cancer, DOACs (rivaroxaban, apixaban, edoxaban, dabigatran) are recommended over vitamin K antagonists.',
      normalized_claim: 'DOACs preferred over warfarin for non-cancer VTE treatment.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Treatment of VTE', page_or_location: 'Section 3.1' },
    },
    {
      rec_id: 'PACK.CHEST.VTE.2021.REC.04',
      display_id: 'CHEST-VTE-R4',
      statement: 'For provoked DVT with a major transient risk factor (surgery, immobilization >3 days), anticoagulation for 3 months is recommended over shorter or extended durations.',
      normalized_claim: 'Provoked VTE from major transient risk factor requires 3 months anticoagulation.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Duration of Therapy', page_or_location: 'Section 4.1' },
    },
    {
      rec_id: 'PACK.CHEST.VTE.2021.REC.05',
      display_id: 'CHEST-VTE-R5',
      statement: 'For unprovoked proximal DVT or PE, extended anticoagulation (no scheduled stop date) is suggested over stopping at 3 months, provided bleeding risk is not high.',
      normalized_claim: 'Unprovoked VTE warrants extended (indefinite) anticoagulation if bleeding risk acceptable.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      provenance: { section: 'Duration of Therapy', page_or_location: 'Section 4.3' },
    },
    {
      rec_id: 'PACK.CHEST.VTE.2021.REC.06',
      display_id: 'CHEST-VTE-R6',
      statement: 'For VTE in active cancer, LMWH or DOACs (edoxaban, rivaroxaban) are recommended over warfarin. LMWH preferred for GI malignancies due to increased GI bleeding risk with DOACs.',
      normalized_claim: 'Cancer-associated VTE: LMWH or select DOACs preferred over warfarin; LMWH preferred for GI cancers.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Cancer-Associated VTE', page_or_location: 'Section 5.1' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.CHEST.VTE.2021.DC.01',
      display_id: 'CHEST-VTE-DC1',
      name: 'Wells Score for DVT',
      components: [
        'Active cancer (+1)',
        'Paralysis, paresis, or recent cast of lower extremity (+1)',
        'Recently bedridden >3 days or major surgery within 12 weeks (+1)',
        'Localized tenderness along deep venous system (+1)',
        'Entire leg swollen (+1)',
        'Calf swelling >3cm compared to asymptomatic leg (+1)',
        'Pitting edema confined to symptomatic leg (+1)',
        'Collateral superficial veins (+1)',
        'Previously documented DVT (+1)',
        'Alternative diagnosis as likely or more likely than DVT (-2)',
      ],
      threshold: 'Score >=2: DVT likely; Score <2: DVT unlikely',
      interpretation: 'Score >=2 (DVT likely): proceed to compression ultrasound. Score <2 (DVT unlikely): obtain D-dimer first.',
      normalized_claim: 'Wells score >=2 = DVT likely (image first); <2 = DVT unlikely (D-dimer first).',
      provenance: { section: 'Diagnosis of DVT', page_or_location: 'Section 2.1, Table 1' },
    },
    {
      criterion_id: 'PACK.CHEST.VTE.2021.DC.02',
      display_id: 'CHEST-VTE-DC2',
      name: 'Compression Ultrasonography Criteria for DVT',
      components: [
        'Non-compressibility of deep vein under direct transducer pressure',
        'Vein lumen fails to coapt completely',
        'Most reliable in proximal veins (common femoral, popliteal)',
      ],
      interpretation: 'Non-compressibility of a deep vein is diagnostic of acute DVT. Sensitivity >95% for proximal DVT.',
      normalized_claim: 'Non-compressibility of proximal deep vein on duplex US confirms DVT (sensitivity >95%).',
      provenance: { section: 'Imaging for DVT', page_or_location: 'Section 2.3' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.CHEST.VTE.2021.T.01',
      display_id: 'CHEST-VTE-T1',
      parameter: 'D-dimer',
      value: '500',
      unit: 'ng/mL',
      clinical_meaning: 'D-dimer <500 ng/mL in low pre-test probability patient excludes DVT. Sensitivity ~97% but low specificity.',
      normalized_claim: 'D-dimer <500 ng/mL with low Wells score excludes DVT (NPV >99%).',
      direction: 'below',
      provenance: { section: 'D-dimer Testing', page_or_location: 'Section 2.2' },
    },
    {
      threshold_id: 'PACK.CHEST.VTE.2021.T.02',
      display_id: 'CHEST-VTE-T2',
      parameter: 'Age-adjusted D-dimer cutoff',
      value: 'age x 10',
      unit: 'ng/mL (for patients >50)',
      clinical_meaning: 'In patients >50 years old, age-adjusted D-dimer (age x 10 ng/mL) improves specificity without significantly reducing sensitivity.',
      normalized_claim: 'Age-adjusted D-dimer cutoff (age x 10 ng/mL for age >50) improves specificity for VTE exclusion.',
      direction: 'below',
      provenance: { section: 'D-dimer Testing', page_or_location: 'Section 2.2' },
    },
    {
      threshold_id: 'PACK.CHEST.VTE.2021.T.03',
      display_id: 'CHEST-VTE-T3',
      parameter: 'INR target for warfarin in VTE',
      value: '2.0-3.0',
      clinical_meaning: 'When warfarin is used for VTE treatment, target INR 2.0-3.0. Supratherapeutic INR increases bleeding without improving efficacy.',
      normalized_claim: 'Warfarin target INR 2.0-3.0 for VTE treatment.',
      direction: 'range',
      provenance: { section: 'Warfarin Therapy', page_or_location: 'Section 3.4' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.CHEST.VTE.2021.TX.01',
      display_id: 'CHEST-VTE-TX1',
      action: 'Initiate anticoagulation for confirmed proximal DVT',
      normalized_claim: 'Start anticoagulation immediately upon confirmed proximal DVT. Rivaroxaban or apixaban as single-drug approach (no lead-in heparin required).',
      timing: 'Immediately upon diagnosis',
      condition: 'Confirmed proximal DVT, non-cancer',
      drug_details: { drug: 'Rivaroxaban', dose: '15mg BID x 21 days then 20mg daily', route: 'PO' },
      contraindications: ['Active major bleeding', 'Severe renal impairment (CrCl <30)', 'Pregnancy'],
      provenance: { section: 'Initial Treatment', page_or_location: 'Section 3.1' },
    },
    {
      step_id: 'PACK.CHEST.VTE.2021.TX.02',
      display_id: 'CHEST-VTE-TX2',
      action: 'Alternative DOAC: Apixaban monotherapy',
      normalized_claim: 'Apixaban 10mg BID x 7 days then 5mg BID is an alternative single-drug DOAC regimen for VTE (no lead-in parenteral anticoagulation).',
      timing: 'Immediately upon diagnosis',
      condition: 'Confirmed VTE, non-cancer, patient preference or rivaroxaban intolerance',
      drug_details: { drug: 'Apixaban', dose: '10mg BID x 7 days then 5mg BID', route: 'PO' },
      contraindications: ['Active major bleeding', 'Severe hepatic impairment', 'Pregnancy'],
      provenance: { section: 'Initial Treatment', page_or_location: 'Section 3.1' },
    },
    {
      step_id: 'PACK.CHEST.VTE.2021.TX.03',
      display_id: 'CHEST-VTE-TX3',
      action: 'Cancer-associated VTE: LMWH or DOAC',
      normalized_claim: 'Cancer-associated VTE: LMWH (enoxaparin 1mg/kg BID) or edoxaban/rivaroxaban. LMWH preferred in GI cancers. Treat for duration of active cancer.',
      timing: 'Immediately upon diagnosis',
      condition: 'Active cancer with confirmed VTE',
      drug_details: { drug: 'Enoxaparin', dose: '1mg/kg', route: 'SC BID', duration: 'Duration of active cancer or minimum 6 months' },
      contraindications: ['HIT', 'Severe thrombocytopenia (platelets <25,000)'],
      provenance: { section: 'Cancer-Associated VTE', page_or_location: 'Section 5.1' },
    },
    {
      step_id: 'PACK.CHEST.VTE.2021.TX.04',
      display_id: 'CHEST-VTE-TX4',
      action: 'IVC filter placement',
      normalized_claim: 'IVC filter only when anticoagulation is absolutely contraindicated (active life-threatening bleeding). Remove filter and start anticoagulation when bleeding resolves.',
      timing: 'When anticoagulation contraindicated',
      condition: 'Acute proximal DVT or PE with absolute contraindication to anticoagulation',
      contraindications: ['IVC thrombosis preventing filter placement'],
      escalation: 'Transition to anticoagulation and remove filter as soon as bleeding risk resolves.',
      provenance: { section: 'IVC Filters', page_or_location: 'Section 6.1' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.CHEST.VTE.2021.RF.01',
      display_id: 'CHEST-VTE-RF1',
      finding: 'Phlegmasia cerulea dolens: Massive DVT with cyanotic, swollen, painful limb and threatened limb viability',
      implication: 'Risk of venous gangrene, limb loss, and cardiovascular collapse. Requires emergent intervention.',
      action: 'Emergent catheter-directed thrombolysis or surgical thrombectomy. Heparinize immediately. Vascular surgery consult.',
      urgency: 'immediate',
      provenance: { section: 'Severe DVT Presentations', page_or_location: 'Section 3.5' },
    },
    {
      flag_id: 'PACK.CHEST.VTE.2021.RF.02',
      display_id: 'CHEST-VTE-RF2',
      finding: 'Recurrent VTE despite therapeutic anticoagulation',
      implication: 'Suggests treatment failure, non-compliance, antiphospholipid syndrome, or occult malignancy.',
      action: 'Confirm compliance and therapeutic levels. Switch anticoagulant class. Evaluate for antiphospholipid syndrome and malignancy.',
      urgency: 'urgent',
      provenance: { section: 'Recurrent VTE', page_or_location: 'Section 7.1' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.CHEST.VTE.2021.SEV.01',
      display_id: 'CHEST-VTE-SEV1',
      level: 'Proximal DVT (high-risk)',
      criteria: [
        'Thrombus in iliac, common femoral, or popliteal vein',
        'Higher risk of PE compared to distal DVT',
        'May present with significant limb swelling and pain',
      ],
      management_implications:
        'Requires immediate full-dose anticoagulation for minimum 3 months. Higher risk of post-thrombotic syndrome. Compression stockings may reduce chronic symptoms.',
      provenance: { section: 'Classification of DVT', page_or_location: 'Section 1.2' },
    },
    {
      severity_id: 'PACK.CHEST.VTE.2021.SEV.02',
      display_id: 'CHEST-VTE-SEV2',
      level: 'Distal (calf) DVT (lower-risk)',
      criteria: [
        'Thrombus confined to calf veins (peroneal, posterior tibial, anterior tibial)',
        'Lower risk of embolization to pulmonary vasculature',
        'May be managed with serial imaging if low-risk',
      ],
      management_implications:
        'Anticoagulation for 3 months if symptomatic or high-risk features. Alternatively, serial compression US at 1-2 weeks if asymptomatic and low-risk. Anticoagulate if thrombus extends proximally on serial imaging.',
      provenance: { section: 'Distal DVT', page_or_location: 'Section 3.6' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for VTE/DVT anticoagulation. Covers DVT diagnosis (Wells + D-dimer), DOAC-first treatment, duration decisions (provoked vs unprovoked), cancer-associated VTE, and IVC filter indications.',

  all_item_ids: [
    'PACK.CHEST.VTE.2021.REC.01', 'PACK.CHEST.VTE.2021.REC.02', 'PACK.CHEST.VTE.2021.REC.03',
    'PACK.CHEST.VTE.2021.REC.04', 'PACK.CHEST.VTE.2021.REC.05', 'PACK.CHEST.VTE.2021.REC.06',
    'PACK.CHEST.VTE.2021.DC.01', 'PACK.CHEST.VTE.2021.DC.02',
    'PACK.CHEST.VTE.2021.T.01', 'PACK.CHEST.VTE.2021.T.02', 'PACK.CHEST.VTE.2021.T.03',
    'PACK.CHEST.VTE.2021.TX.01', 'PACK.CHEST.VTE.2021.TX.02', 'PACK.CHEST.VTE.2021.TX.03',
    'PACK.CHEST.VTE.2021.TX.04',
    'PACK.CHEST.VTE.2021.RF.01', 'PACK.CHEST.VTE.2021.RF.02',
    'PACK.CHEST.VTE.2021.SEV.01', 'PACK.CHEST.VTE.2021.SEV.02',
  ],
  all_display_ids: [
    'CHEST-VTE-R1', 'CHEST-VTE-R2', 'CHEST-VTE-R3', 'CHEST-VTE-R4', 'CHEST-VTE-R5', 'CHEST-VTE-R6',
    'CHEST-VTE-DC1', 'CHEST-VTE-DC2',
    'CHEST-VTE-T1', 'CHEST-VTE-T2', 'CHEST-VTE-T3',
    'CHEST-VTE-TX1', 'CHEST-VTE-TX2', 'CHEST-VTE-TX3', 'CHEST-VTE-TX4',
    'CHEST-VTE-RF1', 'CHEST-VTE-RF2',
    'CHEST-VTE-SEV1', 'CHEST-VTE-SEV2',
  ],
};
