// ─── DRAFT Source Pack: Primary Aldosteronism ───
// Generated by DI/IC Accelerator on 2026-04-17
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (13 total):
//   DI.032.022, DI.032.023, DI.032.024, DI.032.025, DI.032.026, DI.032.027, DI.032.250, DI.199.037, IC.045.013, IC.045.014, IC.045.015, IC.045.016, IC.045.017
//
// Evidence classification summary:
//   Recommendations: 11 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 0 items → pack
//   Thresholds: 1 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 1 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_ENDOCRINE_PA_2020: SourcePack = {
  "source_pack_id": "PACK.ENDOCRINE.PA.2020",
  "source_name": "Endocrine Society Clinical Practice Guideline on Primary Aldosteronism",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2020,
  "guideline_body": "Endocrine Society",
  "topic_tags": [
    "primary aldosteronism",
    "conn syndrome",
    "hyperaldosteronism",
    "hypertension",
    "hypokalemia",
    "adrenal adenoma",
    "adrenal hyperplasia"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "screening",
    "management",
    "laboratory evaluation"
  ],
  "excluded_decision_scopes": [
    "surgical techniques",
    "pediatric populations",
    "pregnancy"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.ENDOCRINE.PA.2020.REC.01",
      "display_id": "ENDO-PA-R1",
      "statement": "Screen for primary aldosteronism in patients presenting with hypokalemia, metabolic alkalosis, and refractory hypertension",
      "normalized_claim": "Primary aldosteronism should be suspected in patients with the triad of hypokalemia, metabolic alkalosis, and treatment-resistant hypertension",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Screening for primary aldosteronism",
      "population": "Adults with resistant hypertension",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Screening recommendations",
        "quote_snippet": "Hypokalemia + metabolic alkalosis + unrelenting HTN (refractory to tx) → Primary Hyperaldosteronism"
      }
    },
    {
      "rec_id": "PACK.ENDOCRINE.PA.2020.REC.02",
      "display_id": "ENDO-PA-R2",
      "statement": "Use early morning plasma aldosterone concentration to plasma renin activity ratio as the initial screening test",
      "normalized_claim": "The PAC:PRA ratio measured in early morning is the recommended first-line screening test for primary aldosteronism",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Laboratory screening",
      "population": "Patients suspected of having primary aldosteronism",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Diagnostic evaluation",
        "quote_snippet": "1st: Early morning plasma aldosterone concentration (PAC) to plasma renin activity (PRA) ratio"
      }
    },
    {
      "rec_id": "PACK.ENDOCRINE.PA.2020.REC.03",
      "display_id": "ENDO-PA-R3",
      "statement": "Withdraw interfering medications 4 weeks prior to PAC:PRA ratio testing when clinically feasible",
      "normalized_claim": "Medications that interfere with the renin-angiotensin-aldosterone system should be discontinued 4 weeks before screening when safe to do so",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Pre-test preparation",
      "population": "Patients undergoing screening for primary aldosteronism",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Laboratory preparation",
        "quote_snippet": "Withdraw drugs that alter ratio 4 weeks prior (spironolactone, eplerenone, amiloride, triamterene)"
      }
    },
    {
      "rec_id": "PACK.ENDOCRINE.PA.2020.REC.04",
      "display_id": "ENDO-PA-R4",
      "statement": "Consider primary aldosteronism in patients with diuretic-induced hypokalemia even without spontaneous hypokalemia",
      "normalized_claim": "Patients may have primary aldosteronism despite normal baseline potassium if they develop hypokalemia with diuretic therapy",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "context": "Clinical recognition",
      "population": "Hypertensive patients on diuretic therapy",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Clinical features",
        "quote_snippet": "Lack spontaneous hypokalemia but prone to diuretic-induced Hypokalemia"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.ENDOCRINE.PA.2020.DC.01",
      "display_id": "ENDO-PA-DC1",
      "name": "Primary Aldosteronism Clinical Triad",
      "components": [
        "Hypokalemia",
        "Metabolic alkalosis",
        "Refractory hypertension"
      ],
      "threshold": "All three components present",
      "interpretation": "High suspicion for primary aldosteronism when all components present",
      "normalized_claim": "The presence of hypokalemia, metabolic alkalosis, and treatment-resistant hypertension constitutes the classic clinical triad for primary aldosteronism",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Clinical presentation",
        "quote_snippet": "Hypokalemia + metabolic alkalosis + unrelenting HTN (refractory to tx)"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.ENDOCRINE.PA.2020.T.01",
      "display_id": "ENDO-PA-T1",
      "parameter": "PAC:PRA ratio",
      "value": "TODO: Verify cutoff value",
      "unit": "ng/dL per ng/mL/hr",
      "clinical_meaning": "Screening threshold for primary aldosteronism",
      "normalized_claim": "An elevated PAC:PRA ratio above the institutional cutoff suggests possible primary aldosteronism",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Laboratory thresholds",
        "quote_snippet": "Early morning plasma aldosterone concentration (PAC) to plasma renin activity (PRA) ratio"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.ENDOCRINE.PA.2020.TX.01",
      "display_id": "ENDO-PA-TX1",
      "action": "Initiate aldosterone antagonist therapy for bilateral adrenal hyperplasia",
      "normalized_claim": "Bilateral adrenal hyperplasia should be treated with mineralocorticoid receptor antagonists",
      "timing": "After confirming bilateral disease",
      "condition": "Bilateral adrenal hyperplasia confirmed",
      "contraindications": [
        "Severe renal impairment",
        "Hyperkalemia"
      ],
      "drug_details": {
        "drug": "Spironolactone or Eplerenone",
        "dose": "TODO: Verify dosing",
        "route": "oral"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Management section",
        "quote_snippet": "Hyperplasia --> Medical therapy | Aldosterone antagonists — Spironolactone, Eplerenone"
      }
    },
    {
      "step_id": "PACK.ENDOCRINE.PA.2020.TX.02",
      "display_id": "ENDO-PA-TX2",
      "action": "Consider adrenalectomy for unilateral aldosterone-producing adenoma",
      "normalized_claim": "Unilateral adrenalectomy is the preferred treatment for unilateral aldosterone-producing adenomas",
      "timing": "After confirming unilateral disease and surgical candidacy",
      "condition": "Unilateral aldosterone-producing adenoma confirmed",
      "contraindications": [
        "Poor surgical candidate",
        "Bilateral disease"
      ],
      "escalation": "Medical therapy if surgery contraindicated",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Treatment options",
        "quote_snippet": "Aldosterone-producing adrenal adenoma"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.ENDOCRINE.PA.2020.RF.01",
      "display_id": "ENDO-PA-RF1",
      "finding": "Severe hypokalemia with metabolic alkalosis in young hypertensive patient",
      "implication": "May indicate secondary hypertension including primary aldosteronism",
      "action": "Urgent endocrine evaluation and specialist referral",
      "urgency": "urgent",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Clinical recognition",
        "quote_snippet": "Hypokalemia + metabolic alkalosis + unrelenting HTN"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.ENDOCRINE.PA.2020.SEV.01",
      "display_id": "ENDO-PA-SEV1",
      "level": "Classic Primary Aldosteronism",
      "criteria": [
        "Treatment-resistant hypertension",
        "Spontaneous hypokalemia",
        "Metabolic alkalosis",
        "Absence of peripheral edema"
      ],
      "management_implications": "Requires comprehensive evaluation including imaging and possible adrenal vein sampling",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Clinical classification",
        "quote_snippet": "Refractory HTN | Lack peripheral edema due to spontaneous diuresis (aldosterone escape)"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "validated",
  "last_normalized": "2024-12-19T15:30:00Z",
  "normalizer_version": 1,
  "normalization_notes": "Created from board review sources (DI/IC). Key items identified include classic clinical triad, PAC:PRA ratio screening, and treatment differentiation between adenoma vs hyperplasia. Missing specific threshold values, detailed drug dosing, and confirmatory testing procedures that need verification against actual Endocrine Society guidelines. Several clinical pearls about licorice ingestion and Cushing's overlap noted but not fully integrated pending guideline review.",
  "all_item_ids": [
    "PACK.ENDOCRINE.PA.2020.REC.01",
    "PACK.ENDOCRINE.PA.2020.REC.02",
    "PACK.ENDOCRINE.PA.2020.REC.03",
    "PACK.ENDOCRINE.PA.2020.REC.04",
    "PACK.ENDOCRINE.PA.2020.DC.01",
    "PACK.ENDOCRINE.PA.2020.T.01",
    "PACK.ENDOCRINE.PA.2020.TX.01",
    "PACK.ENDOCRINE.PA.2020.TX.02",
    "PACK.ENDOCRINE.PA.2020.RF.01",
    "PACK.ENDOCRINE.PA.2020.SEV.01"
  ],
  "all_display_ids": [
    "ENDO-PA-R1",
    "ENDO-PA-R2",
    "ENDO-PA-R3",
    "ENDO-PA-R4",
    "ENDO-PA-DC1",
    "ENDO-PA-T1",
    "ENDO-PA-TX1",
    "ENDO-PA-TX2",
    "ENDO-PA-RF1",
    "ENDO-PA-SEV1"
  ]
};
