import type { SourcePack } from './types';

export const PACK_ES_ADRENAL_2016: SourcePack = {
  source_pack_id: 'PACK.ES.ADRENAL.2016',
  source_name: 'Endocrine Society 2016 Clinical Practice Guideline: Diagnosis and Treatment of Primary Adrenal Insufficiency and Cushing Syndrome',
  canonical_url: 'https://doi.org/10.1210/jc.2015-1710',
  publication_year: 2016,
  guideline_body: 'Endocrine Society',

  topic_tags: ['Adrenal Insufficiency', 'Addison Disease', 'Cushing Syndrome', 'Adrenal Crisis', 'Endocrinology'],
  allowed_decision_scopes: [
    'primary adrenal insufficiency diagnosis',
    'secondary adrenal insufficiency diagnosis',
    'cortisol replacement dosing',
    'mineralocorticoid replacement',
    'adrenal crisis recognition and treatment',
    'stress dose steroid protocols',
    'Cushing syndrome screening and workup',
    'ACTH stimulation test interpretation',
  ],
  excluded_decision_scopes: [
    'adrenal incidentaloma surgical management',
    'pheochromocytoma diagnosis and treatment',
    'primary aldosteronism workup',
    'congenital adrenal hyperplasia',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ES.ADRENAL.2016.REC.01',
      display_id: 'ES-ADRENAL-R1',
      statement: 'The standard ACTH stimulation test (250 mcg cosyntropin IV) is the gold standard for diagnosing primary adrenal insufficiency. A peak cortisol <18 mcg/dL at 30 or 60 minutes confirms the diagnosis.',
      normalized_claim: 'ACTH stimulation test: peak cortisol <18 mcg/dL confirms adrenal insufficiency.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Diagnosis of AI', page_or_location: 'Section 2.1' },
    },
    {
      rec_id: 'PACK.ES.ADRENAL.2016.REC.02',
      display_id: 'ES-ADRENAL-R2',
      statement: 'Hydrocortisone (15-25mg/day in 2-3 divided doses) is the preferred glucocorticoid replacement for primary adrenal insufficiency. The largest dose should be given upon waking.',
      normalized_claim: 'Hydrocortisone 15-25mg/day in divided doses is standard glucocorticoid replacement for primary AI; largest dose given in the morning.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Glucocorticoid Replacement', page_or_location: 'Recommendation 3' },
    },
    {
      rec_id: 'PACK.ES.ADRENAL.2016.REC.03',
      display_id: 'ES-ADRENAL-R3',
      statement: 'All patients with primary adrenal insufficiency require mineralocorticoid replacement with fludrocortisone (0.05-0.2 mg/day). Secondary AI does not require mineralocorticoid replacement.',
      normalized_claim: 'Primary AI requires fludrocortisone (0.05-0.2mg/day); secondary AI does not need mineralocorticoid replacement (ACTH does not regulate aldosterone).',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Mineralocorticoid Replacement', page_or_location: 'Recommendation 4' },
    },
    {
      rec_id: 'PACK.ES.ADRENAL.2016.REC.04',
      display_id: 'ES-ADRENAL-R4',
      statement: 'Cushing syndrome screening should use at least two first-line tests: 24-hour urinary free cortisol, late-night salivary cortisol, or 1mg overnight dexamethasone suppression test.',
      normalized_claim: 'Cushing screening requires >=2 positive first-line tests: 24h UFC, late-night salivary cortisol, or 1mg overnight dex suppression.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Cushing Syndrome Screening', page_or_location: 'Section 5.1' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ES.ADRENAL.2016.DC.01',
      display_id: 'ES-ADRENAL-DC1',
      name: 'Primary vs Secondary Adrenal Insufficiency',
      components: [
        'Primary AI (Addison): High ACTH (>2x ULN) + low cortisol + low aldosterone',
        'Secondary AI: Low/normal ACTH + low cortisol + normal aldosterone',
        'Primary AI: hyperpigmentation, salt craving, hyperkalemia',
        'Secondary AI: no hyperpigmentation, no hyperkalemia, may have other pituitary hormone deficiencies',
      ],
      interpretation: 'ACTH level distinguishes primary (high ACTH) from secondary (low ACTH). Hyperkalemia and hyperpigmentation occur only in primary AI. Aldosterone is preserved in secondary AI.',
      normalized_claim: 'Primary AI: high ACTH, low cortisol, low aldosterone, hyperkalemia, hyperpigmentation. Secondary AI: low ACTH, low cortisol, normal aldosterone, no hyperkalemia.',
      provenance: { section: 'Differential Diagnosis', page_or_location: 'Table 2' },
    },
    {
      criterion_id: 'PACK.ES.ADRENAL.2016.DC.02',
      display_id: 'ES-ADRENAL-DC2',
      name: 'Cushing Syndrome Workup Ladder',
      components: [
        'Step 1: Screen with >=2 first-line tests (24h UFC, late-night salivary cortisol, 1mg overnight DST)',
        'Step 2: Confirm with ACTH level — ACTH-dependent (>20 pg/mL) vs ACTH-independent (<5 pg/mL)',
        'Step 3: ACTH-dependent — high-dose DST or CRH stimulation to distinguish pituitary (Cushing disease) from ectopic ACTH',
        'Step 4: Inferior petrosal sinus sampling (IPSS) if biochemistry equivocal',
      ],
      interpretation: 'Stepwise approach: screen, confirm, localize. ACTH-independent suggests adrenal tumor (CT adrenals). ACTH-dependent requires pituitary vs ectopic source differentiation.',
      normalized_claim: 'Cushing workup: screen (UFC/salivary/DST) then ACTH level to differentiate ACTH-dependent (pituitary vs ectopic) from ACTH-independent (adrenal) causes.',
      provenance: { section: 'Cushing Syndrome Evaluation', page_or_location: 'Figure 2' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ES.ADRENAL.2016.T.01',
      display_id: 'ES-ADRENAL-T1',
      parameter: 'Morning serum cortisol',
      value: '3',
      unit: 'mcg/dL',
      clinical_meaning: 'Morning cortisol <3 mcg/dL is highly suggestive of adrenal insufficiency and may obviate stimulation testing. Morning cortisol >15 mcg/dL makes AI unlikely.',
      normalized_claim: 'Morning cortisol <3 mcg/dL strongly suggests AI; >15 mcg/dL makes AI unlikely; 3-15 requires ACTH stimulation test.',
      direction: 'below',
      provenance: { section: 'Screening for AI', page_or_location: 'Section 2.1' },
    },
    {
      threshold_id: 'PACK.ES.ADRENAL.2016.T.02',
      display_id: 'ES-ADRENAL-T2',
      parameter: 'ACTH stimulation test peak cortisol',
      value: '18',
      unit: 'mcg/dL',
      clinical_meaning: 'Peak cortisol <18 mcg/dL at 30 or 60 minutes after 250 mcg cosyntropin confirms adrenal insufficiency.',
      normalized_claim: 'ACTH stim test: peak cortisol <18 mcg/dL = adrenal insufficiency confirmed.',
      direction: 'below',
      provenance: { section: 'ACTH Stimulation Test', page_or_location: 'Section 2.2' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ES.ADRENAL.2016.TX.01',
      display_id: 'ES-ADRENAL-TX1',
      action: 'Adrenal crisis: Emergency IV hydrocortisone',
      normalized_claim: 'Adrenal crisis requires immediate hydrocortisone 100mg IV bolus followed by 50mg IV q6-8h, plus aggressive IV normal saline resuscitation.',
      timing: 'Immediately — do not wait for lab confirmation',
      condition: 'Adrenal crisis (hypotension, shock, altered mental status in known AI or suspected AI)',
      drug_details: { drug: 'Hydrocortisone', dose: '100mg IV bolus, then 50mg IV q6-8h', route: 'IV' },
      contraindications: [],
      provenance: { section: 'Adrenal Crisis Management', page_or_location: 'Section 3.1' },
    },
    {
      step_id: 'PACK.ES.ADRENAL.2016.TX.02',
      display_id: 'ES-ADRENAL-TX2',
      action: 'Stress dose steroids for physiologic stress',
      normalized_claim: 'Stress dosing: minor illness = double/triple oral dose; moderate stress (surgery) = hydrocortisone 50mg IV q8h; major stress = 100mg IV q8h.',
      timing: 'During physiologic stress (illness, surgery, trauma)',
      condition: 'Known adrenal insufficiency with intercurrent illness or surgery',
      drug_details: { drug: 'Hydrocortisone', dose: '50-100mg IV q8h depending on severity', route: 'IV or PO' },
      provenance: { section: 'Stress Dosing', page_or_location: 'Table 4' },
    },
    {
      step_id: 'PACK.ES.ADRENAL.2016.TX.03',
      display_id: 'ES-ADRENAL-TX3',
      action: 'Cushing disease: Transsphenoidal surgery',
      normalized_claim: 'Transsphenoidal pituitary surgery is first-line treatment for Cushing disease (pituitary ACTH-secreting adenoma).',
      timing: 'After biochemical confirmation and tumor localization',
      condition: 'Confirmed ACTH-dependent Cushing syndrome from pituitary source',
      escalation: 'If surgery fails: repeat surgery, radiation, bilateral adrenalectomy, or medical therapy (ketoconazole, metyrapone, pasireotide)',
      provenance: { section: 'Cushing Disease Treatment', page_or_location: 'Section 5.4' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ES.ADRENAL.2016.RF.01',
      display_id: 'ES-ADRENAL-RF1',
      finding: 'Adrenal crisis: Refractory hypotension, hyperkalemia, hyponatremia, hypoglycemia in a patient with known AI or recent steroid withdrawal',
      implication: 'Life-threatening emergency with mortality >10% if untreated. Often precipitated by infection, trauma, surgery, or steroid non-compliance.',
      action: 'Hydrocortisone 100mg IV bolus immediately. Aggressive NS resuscitation. Treat precipitant. Do NOT delay steroids for diagnostic testing.',
      urgency: 'immediate',
      provenance: { section: 'Adrenal Crisis', page_or_location: 'Section 3.1' },
    },
    {
      flag_id: 'PACK.ES.ADRENAL.2016.RF.02',
      display_id: 'ES-ADRENAL-RF2',
      finding: 'New-onset hypertension, proximal myopathy, wide purple striae, easy bruising, and central obesity suggesting Cushing syndrome',
      implication: 'Cushing syndrome increases cardiovascular mortality, infection risk, and causes metabolic derangements. Must exclude exogenous glucocorticoid use first.',
      action: 'Screen with 24h UFC, late-night salivary cortisol, or 1mg overnight DST. At least 2 abnormal results needed to confirm.',
      urgency: 'soon',
      provenance: { section: 'Cushing Syndrome Recognition', page_or_location: 'Section 5.1' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ES.ADRENAL.2016.SEV.01',
      display_id: 'ES-ADRENAL-SEV1',
      level: 'Adrenal crisis',
      criteria: [
        'Hemodynamic instability (SBP <100 mmHg or refractory to fluids)',
        'Severe hyponatremia (<120 mEq/L) and/or hyperkalemia (>6.0 mEq/L)',
        'Hypoglycemia',
        'Altered mental status or obtundation',
        'Often preceded by precipitant (infection, surgery, trauma, steroid non-compliance)',
      ],
      management_implications:
        'Emergency: hydrocortisone 100mg IV stat, then 50mg q6-8h. NS bolus 1-3L. At stress doses, hydrocortisone provides sufficient mineralocorticoid activity — fludrocortisone not needed acutely. Identify and treat precipitant.',
      provenance: { section: 'Adrenal Crisis', page_or_location: 'Section 3.1' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for adrenal disorders. Covers primary/secondary AI, adrenal crisis, stress dosing, and Cushing syndrome screening/workup.',

  all_item_ids: [
    'PACK.ES.ADRENAL.2016.REC.01', 'PACK.ES.ADRENAL.2016.REC.02', 'PACK.ES.ADRENAL.2016.REC.03',
    'PACK.ES.ADRENAL.2016.REC.04',
    'PACK.ES.ADRENAL.2016.DC.01', 'PACK.ES.ADRENAL.2016.DC.02',
    'PACK.ES.ADRENAL.2016.T.01', 'PACK.ES.ADRENAL.2016.T.02',
    'PACK.ES.ADRENAL.2016.TX.01', 'PACK.ES.ADRENAL.2016.TX.02', 'PACK.ES.ADRENAL.2016.TX.03',
    'PACK.ES.ADRENAL.2016.RF.01', 'PACK.ES.ADRENAL.2016.RF.02',
    'PACK.ES.ADRENAL.2016.SEV.01',
  ],
  all_display_ids: [
    'ES-ADRENAL-R1', 'ES-ADRENAL-R2', 'ES-ADRENAL-R3', 'ES-ADRENAL-R4',
    'ES-ADRENAL-DC1', 'ES-ADRENAL-DC2',
    'ES-ADRENAL-T1', 'ES-ADRENAL-T2',
    'ES-ADRENAL-TX1', 'ES-ADRENAL-TX2', 'ES-ADRENAL-TX3',
    'ES-ADRENAL-RF1', 'ES-ADRENAL-RF2',
    'ES-ADRENAL-SEV1',
  ],
};
