// ─── DRAFT Source Pack: Hypocalcemia ───
// Generated by DI/IC Accelerator on 2026-04-16
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (62 total):
//   DI.017.127, DI.022.074, DI.029.124, DI.029.127, DI.030.274, DI.030.275, DI.030.276, DI.030.277, DI.030.278, DI.030.279, DI.030.280, DI.030.281, DI.030.663, DI.031.305, DI.031.598, DI.032.039, DI.032.212, DI.032.213, DI.032.214, DI.032.215 ... and 42 more
//
// Evidence classification summary:
//   Recommendations: 49 items → pack
//   Diagnostic criteria: 1 items → pack
//   Treatment steps: 3 items → pack
//   Thresholds: 6 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 3 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_ES_HYPOCA_2023: SourcePack = {
  "source_pack_id": "PACK.ES.HYPOCA.2023",
  "source_name": "Endocrine Society Clinical Practice Guideline: Diagnosis and Management of Hypoparathyroidism",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2023,
  "guideline_body": "Endocrine Society",
  "topic_tags": [
    "hypocalcemia",
    "hypoparathyroidism",
    "endocrine",
    "electrolyte disorders",
    "DiGeorge syndrome",
    "calcium metabolism"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "treatment",
    "monitoring",
    "emergency management"
  ],
  "excluded_decision_scopes": [
    "prevention",
    "screening"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.ES.HYPOCA.2023.REC.01",
      "display_id": "ES-HYPOCA-R1",
      "statement": "Evaluate for hypomagnesemia in patients with hypocalcemia refractory to calcium repletion",
      "normalized_claim": "Hypomagnesemia should be evaluated and corrected when hypocalcemia is refractory to calcium replacement",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Refractory hypocalcemia",
      "provenance": {
        "section": "Treatment protocols",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "rec_id": "PACK.ES.HYPOCA.2023.REC.02",
      "display_id": "ES-HYPOCA-R2",
      "statement": "Assess for DiGeorge syndrome in patients with hypocalcemia and recurrent infections",
      "normalized_claim": "DiGeorge syndrome should be considered in patients presenting with hypocalcemia and recurrent infections",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "context": "Pediatric hypocalcemia with infections",
      "provenance": {
        "section": "Differential diagnosis",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "rec_id": "PACK.ES.HYPOCA.2023.REC.03",
      "display_id": "ES-HYPOCA-R3",
      "statement": "Monitor for hypocalcemia in patients undergoing total thyroidectomy",
      "normalized_claim": "Postoperative calcium monitoring is indicated after total thyroidectomy due to risk of parathyroid gland injury",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Post-thyroidectomy care",
      "provenance": {
        "section": "Postoperative monitoring",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "rec_id": "PACK.ES.HYPOCA.2023.REC.04",
      "display_id": "ES-HYPOCA-R4",
      "statement": "Use calcitriol rather than calcidiol for treatment of hypocalcemia in chronic kidney disease",
      "normalized_claim": "Active vitamin D (calcitriol) is preferred over inactive forms in CKD patients with hypocalcemia",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Chronic kidney disease",
      "provenance": {
        "section": "Treatment protocols",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.ES.HYPOCA.2023.DC.01",
      "display_id": "ES-HYPOCA-DC1",
      "name": "Clinical Signs of Hypocalcemia",
      "components": [
        "Chvostek sign (facial muscle spasm on cheek tapping)",
        "Trousseau sign (carpopedal spasm with BP cuff inflation)",
        "QT prolongation on ECG",
        "Seizures or tetany"
      ],
      "threshold": "Presence of 2 or more signs",
      "interpretation": "Suggestive of hypocalcemia requiring laboratory confirmation",
      "normalized_claim": "Clinical signs including Chvostek sign, Trousseau sign, QT prolongation, and seizures are diagnostic indicators of hypocalcemia",
      "provenance": {
        "section": "Clinical assessment",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.ES.HYPOCA.2023.T.01",
      "display_id": "ES-HYPOCA-T1",
      "parameter": "Serum ionized calcium",
      "value": "1.12",
      "unit": "mmol/L",
      "clinical_meaning": "Threshold for hypocalcemia diagnosis",
      "normalized_claim": "Ionized calcium below 1.12 mmol/L defines hypocalcemia",
      "direction": "below",
      "provenance": {
        "section": "Laboratory diagnosis",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "threshold_id": "PACK.ES.HYPOCA.2023.T.02",
      "display_id": "ES-HYPOCA-T2",
      "parameter": "Neonatal glucose",
      "value": "40",
      "unit": "mg/dL",
      "clinical_meaning": "Threshold requiring frequent feeding in neonates at risk for hypocalcemia",
      "normalized_claim": "Neonatal glucose below 40 mg/dL requires intervention in at-risk infants",
      "direction": "below",
      "provenance": {
        "section": "Neonatal management",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.ES.HYPOCA.2023.TX.01",
      "display_id": "ES-HYPOCA-TX1",
      "action": "Administer calcium supplementation with vitamin D",
      "normalized_claim": "Calcium and vitamin D should be administered for hypocalcemia treatment",
      "timing": "Acute management",
      "condition": "Symptomatic hypocalcemia",
      "drug_details": {
        "drug": "Calcium with Vitamin D",
        "route": "oral or IV"
      },
      "provenance": {
        "section": "Treatment protocols",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "step_id": "PACK.ES.HYPOCA.2023.TX.02",
      "display_id": "ES-HYPOCA-TX2",
      "action": "Correct hypomagnesemia before calcium repletion",
      "normalized_claim": "Magnesium deficiency must be corrected for effective calcium repletion",
      "timing": "Before calcium treatment",
      "condition": "Refractory hypocalcemia",
      "drug_details": {
        "drug": "Magnesium",
        "route": "IV or oral"
      },
      "provenance": {
        "section": "Treatment protocols",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "step_id": "PACK.ES.HYPOCA.2023.TX.03",
      "display_id": "ES-HYPOCA-TX3",
      "action": "Use phosphate binders for hyperphosphatemia in CKD patients",
      "normalized_claim": "Phosphate binders should be used to manage hyperphosphatemia in CKD patients with hypocalcemia",
      "condition": "CKD with hyperphosphatemia",
      "drug_details": {
        "drug": "Sevelamer",
        "route": "oral"
      },
      "provenance": {
        "section": "CKD management",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.ES.HYPOCA.2023.RF.01",
      "display_id": "ES-HYPOCA-RF1",
      "finding": "QT prolongation with carpopedal spasms after thyroidectomy",
      "implication": "Hypocalcemia secondary to parathyroid gland removal",
      "action": "Immediate calcium replacement and monitoring",
      "urgency": "immediate",
      "provenance": {
        "section": "Postoperative complications",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "flag_id": "PACK.ES.HYPOCA.2023.RF.02",
      "display_id": "ES-HYPOCA-RF2",
      "finding": "Seizures in neonate of diabetic mother",
      "implication": "Hypocalcemia or hypoglycemia requiring immediate evaluation",
      "action": "Check glucose and calcium levels immediately",
      "urgency": "immediate",
      "provenance": {
        "section": "Neonatal emergencies",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.ES.HYPOCA.2023.SEV.01",
      "display_id": "ES-HYPOCA-SEV1",
      "level": "Severe symptomatic hypocalcemia",
      "criteria": [
        "Seizures",
        "QT prolongation",
        "Positive Chvostek and Trousseau signs",
        "Carpopedal spasms"
      ],
      "management_implications": "Requires immediate IV calcium replacement and cardiac monitoring",
      "provenance": {
        "section": "Severity classification",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "severity_id": "PACK.ES.HYPOCA.2023.SEV.02",
      "display_id": "ES-HYPOCA-SEV2",
      "level": "Refractory hypocalcemia",
      "criteria": [
        "Hypocalcemia persisting despite adequate calcium replacement",
        "Associated hypomagnesemia",
        "Poor response to standard treatment"
      ],
      "management_implications": "Requires magnesium correction and specialized endocrine consultation",
      "provenance": {
        "section": "Treatment challenges",
        "quote_snippet": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-01-15",
  "normalizer_version": 1,
  "normalization_notes": "Extracted from board review materials (Divine Intervention, Inner Circle, Emma Holliday). Key clinical pearls converted to structured recommendations. Treatment protocols derived from clinical scenarios. All items require verification against actual Endocrine Society guidelines. Particular attention needed for: dosing protocols, specific calcium formulations, and monitoring parameters.",
  "all_item_ids": [
    "PACK.ES.HYPOCA.2023.REC.01",
    "PACK.ES.HYPOCA.2023.REC.02",
    "PACK.ES.HYPOCA.2023.REC.03",
    "PACK.ES.HYPOCA.2023.REC.04",
    "PACK.ES.HYPOCA.2023.DC.01",
    "PACK.ES.HYPOCA.2023.T.01",
    "PACK.ES.HYPOCA.2023.T.02",
    "PACK.ES.HYPOCA.2023.TX.01",
    "PACK.ES.HYPOCA.2023.TX.02",
    "PACK.ES.HYPOCA.2023.TX.03",
    "PACK.ES.HYPOCA.2023.RF.01",
    "PACK.ES.HYPOCA.2023.RF.02",
    "PACK.ES.HYPOCA.2023.SEV.01",
    "PACK.ES.HYPOCA.2023.SEV.02"
  ],
  "all_display_ids": [
    "ES-HYPOCA-R1",
    "ES-HYPOCA-R2",
    "ES-HYPOCA-R3",
    "ES-HYPOCA-R4",
    "ES-HYPOCA-DC1",
    "ES-HYPOCA-T1",
    "ES-HYPOCA-T2",
    "ES-HYPOCA-TX1",
    "ES-HYPOCA-TX2",
    "ES-HYPOCA-TX3",
    "ES-HYPOCA-RF1",
    "ES-HYPOCA-RF2",
    "ES-HYPOCA-SEV1",
    "ES-HYPOCA-SEV2"
  ]
};
