import type { SourcePack } from './types';

export const PACK_ES_OSTEO_2020: SourcePack = {
  source_pack_id: 'PACK.ES.OSTEO.2020',
  source_name: 'Endocrine Society 2020 Clinical Practice Guideline: Pharmacological Management of Osteoporosis in Postmenopausal Women',
  canonical_url: 'https://doi.org/10.1210/clinem/dgaa926',
  publication_year: 2020,
  guideline_body: 'Endocrine Society',

  topic_tags: ['Osteoporosis', 'Osteopenia', 'DEXA', 'FRAX', 'Bisphosphonates', 'Endocrinology', 'Rheumatology'],
  allowed_decision_scopes: [
    'DEXA interpretation and T-score classification',
    'FRAX risk assessment and treatment thresholds',
    'bisphosphonate selection and duration',
    'denosumab indications',
    'teriparatide and anabolic therapy for severe disease',
    'bisphosphonate drug holiday criteria',
    'secondary osteoporosis workup',
  ],
  excluded_decision_scopes: [
    'premenopausal osteoporosis management',
    'glucocorticoid-induced osteoporosis (separate guideline)',
    'Paget disease of bone',
    'osteoporosis in men (separate guideline)',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ES.OSTEO.2020.REC.01',
      display_id: 'ES-OSTEO-R1',
      statement: 'Oral bisphosphonates (alendronate or risedronate) are recommended as first-line pharmacologic therapy for postmenopausal women at high fracture risk.',
      normalized_claim: 'Alendronate or risedronate is first-line pharmacotherapy for postmenopausal osteoporosis.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Initial Pharmacotherapy', page_or_location: 'Recommendation 1' },
    },
    {
      rec_id: 'PACK.ES.OSTEO.2020.REC.02',
      display_id: 'ES-OSTEO-R2',
      statement: 'For patients at very high fracture risk (recent vertebral fracture, T-score <=-3.0, or FRAX >=30% major osteoporotic), anabolic therapy (teriparatide or romosozumab) should be considered as initial treatment before antiresorptive.',
      normalized_claim: 'Very high fracture risk patients should receive anabolic therapy (teriparatide/romosozumab) first, followed by antiresorptive therapy.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      provenance: { section: 'Severe Osteoporosis', page_or_location: 'Recommendation 6' },
    },
    {
      rec_id: 'PACK.ES.OSTEO.2020.REC.03',
      display_id: 'ES-OSTEO-R3',
      statement: 'Bisphosphonate drug holiday should be considered after 5 years of oral therapy or 3 years of IV zoledronic acid in patients who are no longer at high fracture risk.',
      normalized_claim: 'Bisphosphonate holiday after 5 years oral or 3 years IV in patients no longer at high fracture risk; reassess after 2-3 years off therapy.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      provenance: { section: 'Duration of Therapy', page_or_location: 'Recommendation 8' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ES.OSTEO.2020.DC.01',
      display_id: 'ES-OSTEO-DC1',
      name: 'WHO DEXA T-score Classification',
      components: [
        'Normal: T-score >= -1.0',
        'Osteopenia (low bone mass): T-score -1.0 to -2.5',
        'Osteoporosis: T-score <= -2.5',
        'Severe osteoporosis: T-score <= -2.5 with fragility fracture',
      ],
      threshold: 'T-score <= -2.5 at hip, femoral neck, or lumbar spine',
      interpretation: 'T-score compares BMD to young adult reference population. Z-score (age-matched) used in premenopausal women and men <50. DEXA at hip and spine; use lowest T-score for diagnosis.',
      normalized_claim: 'Osteoporosis = T-score <=-2.5 at hip or spine; osteopenia = -1.0 to -2.5; severe = <=-2.5 plus fragility fracture.',
      provenance: { section: 'Bone Density Assessment', page_or_location: 'Table 1' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ES.OSTEO.2020.T.01',
      display_id: 'ES-OSTEO-T1',
      parameter: 'FRAX 10-year major osteoporotic fracture risk',
      value: '20',
      unit: '%',
      clinical_meaning: 'FRAX >=20% 10-year major osteoporotic fracture risk is a treatment threshold even without a T-score of -2.5.',
      normalized_claim: 'Treat if FRAX >=20% major osteoporotic fracture risk or >=3% hip fracture risk, even with osteopenia.',
      direction: 'above',
      provenance: { section: 'Treatment Thresholds', page_or_location: 'Section 3.2' },
    },
    {
      threshold_id: 'PACK.ES.OSTEO.2020.T.02',
      display_id: 'ES-OSTEO-T2',
      parameter: 'FRAX 10-year hip fracture risk',
      value: '3',
      unit: '%',
      clinical_meaning: 'FRAX >=3% 10-year hip fracture risk is a treatment threshold per NOF/Endocrine Society guidelines.',
      normalized_claim: 'FRAX >=3% hip fracture risk triggers pharmacotherapy.',
      direction: 'above',
      provenance: { section: 'Treatment Thresholds', page_or_location: 'Section 3.2' },
    },
    {
      threshold_id: 'PACK.ES.OSTEO.2020.T.03',
      display_id: 'ES-OSTEO-T3',
      parameter: 'T-score for osteoporosis diagnosis',
      value: '-2.5',
      clinical_meaning: 'T-score at or below -2.5 at any measured site (lumbar spine, total hip, femoral neck) establishes the diagnosis of osteoporosis.',
      normalized_claim: 'T-score <=-2.5 = osteoporosis diagnosis; treatment indicated.',
      direction: 'below',
      provenance: { section: 'Diagnosis', page_or_location: 'Section 2.1' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ES.OSTEO.2020.TX.01',
      display_id: 'ES-OSTEO-TX1',
      action: 'First-line: Oral bisphosphonate',
      normalized_claim: 'Alendronate 70mg weekly or risedronate 35mg weekly/150mg monthly as first-line. Take on empty stomach with full glass of water, remain upright 30 minutes.',
      timing: 'At diagnosis of osteoporosis or high FRAX risk',
      condition: 'Postmenopausal osteoporosis, standard fracture risk',
      drug_details: { drug: 'Alendronate', dose: '70mg weekly', route: 'PO' },
      contraindications: ['Esophageal disorders (stricture, achalasia)', 'Inability to sit upright 30 min', 'GFR <30-35 mL/min', 'Hypocalcemia'],
      provenance: { section: 'Bisphosphonate Therapy', page_or_location: 'Recommendation 1' },
    },
    {
      step_id: 'PACK.ES.OSTEO.2020.TX.02',
      display_id: 'ES-OSTEO-TX2',
      action: 'Severe disease: Anabolic therapy first',
      normalized_claim: 'Teriparatide 20mcg SC daily for 2 years, then transition to bisphosphonate/denosumab. Romosozumab 210mg SC monthly for 12 months is an alternative.',
      timing: 'First-line for very high-risk patients',
      condition: 'Very high fracture risk: recent vertebral fracture, T-score <=-3.0, or FRAX >=30%',
      drug_details: { drug: 'Teriparatide', dose: '20mcg daily', route: 'SC', duration: '2 years maximum' },
      contraindications: ['Hypercalcemia', 'Paget disease', 'Prior bone radiation', 'Open epiphyses', 'Bone metastases'],
      escalation: 'Must transition to antiresorptive after anabolic course to maintain gains',
      provenance: { section: 'Anabolic Therapy', page_or_location: 'Recommendation 6' },
    },
    {
      step_id: 'PACK.ES.OSTEO.2020.TX.03',
      display_id: 'ES-OSTEO-TX3',
      action: 'Alternative: Denosumab for bisphosphonate-intolerant patients',
      normalized_claim: 'Denosumab 60mg SC every 6 months for patients intolerant of or contraindicated to bisphosphonates. Must not discontinue without transitioning to bisphosphonate (rebound vertebral fractures).',
      timing: 'When bisphosphonates contraindicated or not tolerated',
      condition: 'Bisphosphonate intolerance or renal impairment (GFR <30)',
      drug_details: { drug: 'Denosumab', dose: '60mg', route: 'SC every 6 months' },
      contraindications: ['Hypocalcemia (must correct first)'],
      provenance: { section: 'Denosumab', page_or_location: 'Recommendation 4' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ES.OSTEO.2020.RF.01',
      display_id: 'ES-OSTEO-RF1',
      finding: 'Denosumab discontinuation without bisphosphonate transition — rapid BMD loss and rebound vertebral fractures within 6-12 months',
      implication: 'Multiple vertebral fractures reported after denosumab cessation. Must transition to bisphosphonate to prevent rebound bone loss.',
      action: 'Do not discontinue denosumab without starting a bisphosphonate. If discontinued, give zoledronic acid 6 months after last denosumab dose.',
      urgency: 'urgent',
      provenance: { section: 'Denosumab Discontinuation', page_or_location: 'Section 4.3' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ES.OSTEO.2020.SEV.01',
      display_id: 'ES-OSTEO-SEV1',
      level: 'Very high fracture risk',
      criteria: [
        'T-score <= -3.0 at any site',
        'Recent (within 12 months) vertebral or hip fragility fracture',
        'Multiple vertebral fractures',
        'FRAX >=30% major osteoporotic or >=4.5% hip',
        'Fracture on current osteoporosis therapy',
      ],
      management_implications:
        'Consider anabolic-first strategy (teriparatide or romosozumab) before transitioning to antiresorptive. Bisphosphonate alone may be insufficient. Fall prevention program. Vertebroplasty consideration for acute painful vertebral fractures.',
      provenance: { section: 'Severe Osteoporosis', page_or_location: 'Recommendation 6' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for osteoporosis. Covers DEXA interpretation, FRAX thresholds, bisphosphonates, denosumab, and anabolic therapy for severe disease.',

  all_item_ids: [
    'PACK.ES.OSTEO.2020.REC.01', 'PACK.ES.OSTEO.2020.REC.02', 'PACK.ES.OSTEO.2020.REC.03',
    'PACK.ES.OSTEO.2020.DC.01',
    'PACK.ES.OSTEO.2020.T.01', 'PACK.ES.OSTEO.2020.T.02', 'PACK.ES.OSTEO.2020.T.03',
    'PACK.ES.OSTEO.2020.TX.01', 'PACK.ES.OSTEO.2020.TX.02', 'PACK.ES.OSTEO.2020.TX.03',
    'PACK.ES.OSTEO.2020.RF.01',
    'PACK.ES.OSTEO.2020.SEV.01',
  ],
  all_display_ids: [
    'ES-OSTEO-R1', 'ES-OSTEO-R2', 'ES-OSTEO-R3',
    'ES-OSTEO-DC1',
    'ES-OSTEO-T1', 'ES-OSTEO-T2', 'ES-OSTEO-T3',
    'ES-OSTEO-TX1', 'ES-OSTEO-TX2', 'ES-OSTEO-TX3',
    'ES-OSTEO-RF1',
    'ES-OSTEO-SEV1',
  ],
};
