import type { SourcePack } from './types';

export const PACK_ES_PHEO_2014: SourcePack = {
  source_pack_id: 'PACK.ES.PHEO.2014',
  source_name: 'Endocrine Society 2014 Clinical Practice Guideline: Pheochromocytoma and Paraganglioma',
  canonical_url: 'https://doi.org/10.1210/jc.2014-1498',
  publication_year: 2014,
  guideline_body: 'Endocrine Society',

  topic_tags: ['Pheochromocytoma', 'Paraganglioma', 'Adrenal', 'Endocrinology', 'Hypertension'],
  allowed_decision_scopes: [
    'pheochromocytoma biochemical diagnosis',
    'pheochromocytoma localization imaging',
    'preoperative alpha-blockade',
    'preoperative beta-blockade',
    'surgical resection planning',
    'genetic testing for hereditary syndromes',
    'catecholamine crisis management',
    'metastatic pheochromocytoma treatment',
  ],
  excluded_decision_scopes: [
    'primary hypertension management',
    'adrenal incidentaloma workup beyond pheo exclusion',
    'Cushing syndrome evaluation',
    'primary aldosteronism management',
  ],

  recommendations: [
    {
      rec_id: 'PACK.ES.PHEO.2014.REC.01',
      display_id: 'ES-PHEO-R1',
      statement: 'Measurement of plasma free metanephrines or 24-hour urinary fractionated metanephrines is recommended as the initial biochemical test for pheochromocytoma.',
      normalized_claim: 'Initial biochemical screening for pheochromocytoma uses plasma free metanephrines or 24h urinary fractionated metanephrines.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'Plasma free metanephrines have higher sensitivity (~97%); urinary fractionated metanephrines have higher specificity (~93%)',
      provenance: { section: 'Biochemical Diagnosis', page_or_location: 'Section 3.1' },
    },
    {
      rec_id: 'PACK.ES.PHEO.2014.REC.02',
      display_id: 'ES-PHEO-R2',
      statement: 'All patients with pheochromocytoma or paraganglioma should be considered for genetic testing, especially those with bilateral, extra-adrenal, or metastatic disease, family history, or young age at diagnosis.',
      normalized_claim: 'Genetic testing (RET, VHL, SDHx, NF1) recommended for all pheochromocytoma/paraganglioma patients; mandatory if bilateral, extra-adrenal, metastatic, familial, or age <45.',
      strength: 'strong',
      evidence_quality: 'moderate',
      population: 'All patients with confirmed pheochromocytoma or paraganglioma',
      provenance: { section: 'Genetic Testing', page_or_location: 'Section 6.1' },
    },
    {
      rec_id: 'PACK.ES.PHEO.2014.REC.03',
      display_id: 'ES-PHEO-R3',
      statement: 'Preoperative alpha-adrenergic blockade should be initiated at least 10-14 days before surgery to normalize blood pressure and expand contracted intravascular volume.',
      normalized_claim: 'Alpha-blockade (phenoxybenzamine or doxazosin) must begin 10-14 days preoperatively to control BP and restore intravascular volume.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Preoperative Management', page_or_location: 'Section 4.1' },
    },
    {
      rec_id: 'PACK.ES.PHEO.2014.REC.04',
      display_id: 'ES-PHEO-R4',
      statement: 'Beta-adrenergic blockade should only be started after adequate alpha-blockade has been established. Initiating beta-blockers without prior alpha-blockade can precipitate a hypertensive crisis from unopposed alpha-receptor stimulation.',
      normalized_claim: 'Beta-blockers are CONTRAINDICATED before alpha-blockade in pheochromocytoma; unopposed alpha stimulation causes hypertensive crisis.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Preoperative Management', page_or_location: 'Section 4.2' },
    },
    {
      rec_id: 'PACK.ES.PHEO.2014.REC.05',
      display_id: 'ES-PHEO-R5',
      statement: 'Surgical resection is the definitive treatment for pheochromocytoma. Laparoscopic adrenalectomy is preferred for most tumors <6 cm.',
      normalized_claim: 'Surgery is the only curative treatment for pheochromocytoma; laparoscopic adrenalectomy preferred for tumors <6 cm.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Surgical Management', page_or_location: 'Section 5.1' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.ES.PHEO.2014.DC.01',
      display_id: 'ES-PHEO-DC1',
      name: 'Biochemical Diagnosis of Pheochromocytoma',
      components: [
        'Plasma free metanephrines (normetanephrine and/or metanephrine) elevated above upper reference limit',
        'OR 24-hour urinary fractionated metanephrines and catecholamines elevated above upper reference limit',
        'Values >2x upper limit of normal are highly suggestive',
        'Borderline elevations require confirmatory testing (clonidine suppression test)',
      ],
      threshold: 'Plasma metanephrines >2x upper reference limit strongly suggestive',
      interpretation: 'Elevated plasma free metanephrines (sensitivity ~97%) or urinary fractionated metanephrines (specificity ~93%) confirm biochemical diagnosis. Imaging follows biochemical confirmation.',
      normalized_claim: 'Pheochromocytoma diagnosed biochemically by elevated plasma free metanephrines (sensitivity 97%) or 24h urinary fractionated metanephrines (specificity 93%); values >2x URL highly suggestive.',
      provenance: { section: 'Biochemical Diagnosis', page_or_location: 'Section 3.1-3.3' },
    },
    {
      criterion_id: 'PACK.ES.PHEO.2014.DC.02',
      display_id: 'ES-PHEO-DC2',
      name: 'Classic Pheochromocytoma Clinical Triad',
      components: [
        'Episodic headache',
        'Diaphoresis (sweating)',
        'Palpitations/tachycardia',
        'Associated with paroxysmal or sustained hypertension',
      ],
      interpretation: 'Classic triad present in ~40% of patients. Absence does not exclude diagnosis. Paroxysmal symptoms triggered by physical activity, stress, anesthesia induction, or tyramine-containing foods.',
      normalized_claim: 'Classic pheochromocytoma triad: episodic headache + diaphoresis + palpitations with hypertension. Present in ~40%; absence does not exclude diagnosis.',
      provenance: { section: 'Clinical Presentation', page_or_location: 'Section 2.1' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.ES.PHEO.2014.T.01',
      display_id: 'ES-PHEO-T1',
      parameter: 'Plasma free metanephrines',
      value: '2x upper reference limit',
      clinical_meaning: 'Values exceeding twice the upper reference limit are highly suggestive of pheochromocytoma and warrant imaging. Borderline values require confirmatory testing.',
      normalized_claim: 'Plasma free metanephrines >2x URL highly suggestive of pheo; borderline values need clonidine suppression test.',
      direction: 'above',
      provenance: { section: 'Biochemical Diagnosis', page_or_location: 'Section 3.2' },
    },
    {
      threshold_id: 'PACK.ES.PHEO.2014.T.02',
      display_id: 'ES-PHEO-T2',
      parameter: 'Preoperative alpha-blockade duration',
      value: '10-14',
      unit: 'days',
      clinical_meaning: 'Minimum duration of alpha-blockade before surgery to allow blood pressure control and intravascular volume expansion.',
      normalized_claim: 'Alpha-blockade must be maintained for minimum 10-14 days preoperatively.',
      direction: 'above',
      provenance: { section: 'Preoperative Management', page_or_location: 'Section 4.1' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.ES.PHEO.2014.TX.01',
      display_id: 'ES-PHEO-TX1',
      action: 'Initiate alpha-adrenergic blockade',
      normalized_claim: 'First-line preoperative management: phenoxybenzamine 10mg BID (titrate to BP <130/80 seated) or doxazosin 2mg daily (titrate up). High-sodium diet + fluid intake to expand volume.',
      timing: '10-14 days before planned surgery',
      condition: 'Confirmed pheochromocytoma, planned surgical resection',
      drug_details: { drug: 'Phenoxybenzamine', dose: '10mg BID initial, titrate to effect', route: 'PO' },
      contraindications: ['Hypotension at baseline'],
      provenance: { section: 'Preoperative Management', page_or_location: 'Section 4.1' },
    },
    {
      step_id: 'PACK.ES.PHEO.2014.TX.02',
      display_id: 'ES-PHEO-TX2',
      action: 'Add beta-adrenergic blockade after adequate alpha-blockade',
      normalized_claim: 'Beta-blocker (propranolol or atenolol) added ONLY after 2-3 days of alpha-blockade to control reflex tachycardia. Never before alpha-blockade.',
      timing: '2-3 days after initiating alpha-blockade',
      condition: 'Reflex tachycardia (HR >100) present after alpha-blockade established',
      drug_details: { drug: 'Propranolol', dose: '20-40mg TID-QID', route: 'PO' },
      contraindications: ['Inadequate alpha-blockade', 'Asthma', 'Bradycardia', 'Decompensated heart failure'],
      escalation: 'Metyrosine (alpha-methyl-para-tyrosine) for refractory cases',
      provenance: { section: 'Preoperative Management', page_or_location: 'Section 4.2' },
    },
    {
      step_id: 'PACK.ES.PHEO.2014.TX.03',
      display_id: 'ES-PHEO-TX3',
      action: 'Surgical resection (laparoscopic adrenalectomy)',
      normalized_claim: 'Laparoscopic adrenalectomy is definitive treatment for pheochromocytoma <6 cm. Open surgery for tumors >6 cm or suspected malignancy.',
      timing: 'After 10-14 days of adequate alpha- and beta-blockade',
      condition: 'Localized pheochromocytoma after adequate preoperative blockade',
      provenance: { section: 'Surgical Management', page_or_location: 'Section 5.1' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.ES.PHEO.2014.RF.01',
      display_id: 'ES-PHEO-RF1',
      finding: 'Hypertensive crisis (BP >250/150) with headache, diaphoresis, and palpitations during anesthesia induction, abdominal palpation, or after starting beta-blocker without alpha-blockade',
      implication: 'Catecholamine surge from undiagnosed or inadequately blocked pheochromocytoma. Life-threatening arrhythmias, stroke, or MI possible.',
      action: 'IV phentolamine (alpha-blocker) 2-5mg boluses. IV nitroprusside for persistent HTN. Avoid beta-blockers until alpha-blockade adequate. Arterial line monitoring.',
      urgency: 'immediate',
      provenance: { section: 'Emergency Management', page_or_location: 'Section 4.3' },
    },
    {
      flag_id: 'PACK.ES.PHEO.2014.RF.02',
      display_id: 'ES-PHEO-RF2',
      finding: 'Postoperative hypotension and hypoglycemia after pheochromocytoma resection',
      implication: 'Loss of catecholamine-driven vasoconstriction and glycogenolysis. Expected but requires aggressive management.',
      action: 'IV fluid resuscitation, vasopressors if needed. Monitor glucose q1h for 24 hours. Hydrocortisone if bilateral adrenalectomy performed.',
      urgency: 'urgent',
      provenance: { section: 'Postoperative Management', page_or_location: 'Section 5.3' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.ES.PHEO.2014.SEV.01',
      display_id: 'ES-PHEO-SEV1',
      level: 'Catecholamine crisis',
      criteria: [
        'Severe paroxysmal hypertension (SBP >200 mmHg)',
        'Tachycardia or arrhythmia',
        'Diaphoresis, pallor, headache',
        'End-organ damage (pulmonary edema, encephalopathy, myocardial ischemia)',
      ],
      management_implications:
        'ICU admission. IV phentolamine bolus (2-5mg q5min). IV nitroprusside infusion for refractory HTN. Arterial line and continuous cardiac monitoring. NO beta-blockers until alpha-blockade established. Emergent surgery contraindicated until hemodynamically stabilized.',
      provenance: { section: 'Emergency Management', page_or_location: 'Section 4.3' },
    },
    {
      severity_id: 'PACK.ES.PHEO.2014.SEV.02',
      display_id: 'ES-PHEO-SEV2',
      level: 'Metastatic pheochromocytoma',
      criteria: [
        'Presence of chromaffin tissue in non-chromaffin organs (bone, liver, lung, lymph nodes)',
        'SDHB mutation carrier with extra-adrenal paraganglioma',
        'Tumor >5 cm or locally invasive features',
      ],
      management_implications:
        'Not curable by surgery alone. CVD (cyclophosphamide, vincristine, dacarbazine) chemotherapy for progressive disease. MIBG therapy if MIBG-avid. Lifelong biochemical surveillance. Genetic counseling mandatory.',
      provenance: { section: 'Malignant Pheochromocytoma', page_or_location: 'Section 7.1' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for pheochromocytoma. Covers biochemical diagnosis, preoperative blockade sequence (alpha before beta), surgical management, and genetic testing indications.',

  all_item_ids: [
    'PACK.ES.PHEO.2014.REC.01', 'PACK.ES.PHEO.2014.REC.02', 'PACK.ES.PHEO.2014.REC.03',
    'PACK.ES.PHEO.2014.REC.04', 'PACK.ES.PHEO.2014.REC.05',
    'PACK.ES.PHEO.2014.DC.01', 'PACK.ES.PHEO.2014.DC.02',
    'PACK.ES.PHEO.2014.T.01', 'PACK.ES.PHEO.2014.T.02',
    'PACK.ES.PHEO.2014.TX.01', 'PACK.ES.PHEO.2014.TX.02', 'PACK.ES.PHEO.2014.TX.03',
    'PACK.ES.PHEO.2014.RF.01', 'PACK.ES.PHEO.2014.RF.02',
    'PACK.ES.PHEO.2014.SEV.01', 'PACK.ES.PHEO.2014.SEV.02',
  ],
  all_display_ids: [
    'ES-PHEO-R1', 'ES-PHEO-R2', 'ES-PHEO-R3', 'ES-PHEO-R4', 'ES-PHEO-R5',
    'ES-PHEO-DC1', 'ES-PHEO-DC2',
    'ES-PHEO-T1', 'ES-PHEO-T2',
    'ES-PHEO-TX1', 'ES-PHEO-TX2', 'ES-PHEO-TX3',
    'ES-PHEO-RF1', 'ES-PHEO-RF2',
    'ES-PHEO-SEV1', 'ES-PHEO-SEV2',
  ],
};
