// ─── DRAFT Source Pack: SIADH ───
// Generated by DI/IC Accelerator on 2026-04-17
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (42 total):
//   DI.029.126, DI.030.460, DI.030.479, DI.031.197, DI.031.455, DI.031.456, DI.031.457, DI.031.458, DI.031.459, DI.031.460, DI.031.461, DI.031.462, DI.031.554, DI.031.634, DI.031.642, DI.032.240, DI.059.078, DI.059.125, DI.102.048, DI.111.048 ... and 22 more
//
// Evidence classification summary:
//   Recommendations: 24 items → pack
//   Diagnostic criteria: 2 items → pack
//   Treatment steps: 4 items → pack
//   Thresholds: 5 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 1 items → pack
//   Skipped: 6 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_ESE_SIADH_2024: SourcePack = {
  "source_pack_id": "PACK.ESE.SIADH.2024",
  "source_name": "Syndrome of Inappropriate Antidiuretic Hormone Secretion (SIADH) - Clinical Management Guidelines",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2024,
  "guideline_body": "Endocrine Society",
  "topic_tags": [
    "endocrinology",
    "hyponatremia",
    "fluid_electrolyte_disorders",
    "paraneoplastic_syndromes",
    "SIADH"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "treatment",
    "monitoring",
    "drug_management"
  ],
  "excluded_decision_scopes": [
    "surgical_management",
    "pediatric_management"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.ESE.SIADH.2024.REC.01",
      "display_id": "ESE-SIADH-R1",
      "statement": "In patients with suspected SIADH, assess for common drug causes including SSRIs, cyclophosphamide, and first-generation sulfonylureas (chlorpropamide)",
      "normalized_claim": "Common medications that can cause SIADH include SSRIs, cyclophosphamide, and chlorpropamide",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Drug-induced SIADH evaluation",
      "population": "Patients with euvolemic hyponatremia",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Drugs: SSRIs, Cyclophosphamide, Chlorpropamide (1st gen sulfonylureas)"
      }
    },
    {
      "rec_id": "PACK.ESE.SIADH.2024.REC.02",
      "display_id": "ESE-SIADH-R2",
      "statement": "Evaluate for small cell lung cancer as a potential cause of SIADH, particularly in patients with smoking history",
      "normalized_claim": "Small cell lung cancer is a major cause of SIADH and should be considered in the differential diagnosis",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Paraneoplastic SIADH evaluation",
      "population": "Patients with SIADH, especially smokers",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Small cell lung cancer, paraneoplastic syndrome"
      }
    },
    {
      "rec_id": "PACK.ESE.SIADH.2024.REC.03",
      "display_id": "ESE-SIADH-R3",
      "statement": "Consider ADH receptor antagonists (vaptans) or demeclocycline for SIADH patients who are resistant to fluid restriction",
      "normalized_claim": "Vaptans or demeclocycline can be used for fluid restriction-resistant SIADH",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "context": "Refractory SIADH management",
      "population": "Patients with SIADH not responding to fluid restriction",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If resistant to fluid restriction? Demeclocycline | ADH receptor antagonists (-vaptans)"
      }
    },
    {
      "rec_id": "PACK.ESE.SIADH.2024.REC.04",
      "display_id": "ESE-SIADH-R4",
      "statement": "Evaluate for other causes of euvolemic hyponatremia including hypothyroidism, Addison's disease, and psychogenic polydipsia",
      "normalized_claim": "The differential diagnosis for euvolemic hyponatremia includes SIADH, hypothyroidism, Addison's disease, and psychogenic polydipsia",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Differential diagnosis of euvolemic hyponatremia",
      "population": "Patients with euvolemic hyponatremia",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "SIADH, Hypothyroidism, Psychogenic polydipsia, Tea & toast/beer potomania"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.ESE.SIADH.2024.DC.01",
      "display_id": "ESE-SIADH-DC1",
      "name": "SIADH Diagnostic Criteria",
      "components": [
        "Euvolemic hyponatremia",
        "Low serum osmolality",
        "Inappropriately concentrated urine (urine osmolality > 100 mOsm/kg)",
        "Normal kidney and adrenal function",
        "No recent diuretic use"
      ],
      "threshold": "Urine osmolality > 100 mOsm/kg with concurrent hyponatremia",
      "interpretation": "Presence of concentrated urine in the setting of hyponatremia suggests inappropriate ADH secretion",
      "normalized_claim": "SIADH is diagnosed by euvolemic hyponatremia with inappropriately concentrated urine",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "euvolemic hyponatremia, Urine is hyperosmolar, Concentrated urine (Uosm > 100)"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.ESE.SIADH.2024.T.01",
      "display_id": "ESE-SIADH-T1",
      "parameter": "Urine osmolality",
      "value": "100",
      "unit": "mOsm/kg",
      "clinical_meaning": "Inappropriately concentrated urine suggesting SIADH",
      "normalized_claim": "Urine osmolality > 100 mOsm/kg in hyponatremic patients suggests SIADH",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Concentrated urine (Uosm > 100) → SIADH"
      }
    },
    {
      "threshold_id": "PACK.ESE.SIADH.2024.T.02",
      "display_id": "ESE-SIADH-T2",
      "parameter": "Serum sodium",
      "value": "120",
      "unit": "mEq/L",
      "clinical_meaning": "Severe hyponatremia requiring urgent treatment with hypertonic saline",
      "normalized_claim": "Serum sodium < 120 mEq/L with seizures warrants hypertonic saline administration",
      "direction": "below",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "When should hypertonic saline be administered? Seizures + Na < 120"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.ESE.SIADH.2024.TX.01",
      "display_id": "ESE-SIADH-TX1",
      "action": "Initiate fluid restriction as first-line therapy",
      "normalized_claim": "Fluid restriction is the primary treatment for SIADH",
      "timing": "Initial management",
      "condition": "Confirmed SIADH diagnosis",
      "contraindications": [
        "Severe symptomatic hyponatremia with seizures"
      ],
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Tx? Fluid restriction"
      }
    },
    {
      "step_id": "PACK.ESE.SIADH.2024.TX.02",
      "display_id": "ESE-SIADH-TX2",
      "action": "Administer hypertonic saline for severe symptomatic hyponatremia",
      "normalized_claim": "Hypertonic saline should be given for severe hyponatremia with neurologic symptoms",
      "timing": "Emergency management",
      "condition": "Seizures with sodium < 120 mEq/L",
      "escalation": "Immediate intervention required",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "When should hypertonic saline be administered? Seizures + Na < 120"
      }
    },
    {
      "step_id": "PACK.ESE.SIADH.2024.TX.03",
      "display_id": "ESE-SIADH-TX3",
      "action": "Consider demeclocycline for fluid restriction-resistant cases",
      "normalized_claim": "Demeclocycline can be used as second-line therapy for refractory SIADH",
      "timing": "When fluid restriction fails",
      "condition": "Inadequate response to fluid restriction",
      "drug_details": {
        "drug": "Demeclocycline",
        "route": "oral"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If resistant to fluid restriction? Demeclocycline"
      }
    },
    {
      "step_id": "PACK.ESE.SIADH.2024.TX.04",
      "display_id": "ESE-SIADH-TX4",
      "action": "Consider ADH receptor antagonists (vaptans) for refractory cases",
      "normalized_claim": "Vaptans are an option for SIADH not responding to conservative measures",
      "timing": "When other treatments fail",
      "condition": "Refractory SIADH",
      "drug_details": {
        "drug": "Vaptan (ADH receptor antagonist)",
        "route": "oral or IV"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "ADH receptor antagonists (-vaptans), very expensive"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.ESE.SIADH.2024.RF.01",
      "display_id": "ESE-SIADH-RF1",
      "finding": "Seizures in patient with hyponatremia",
      "implication": "Severe symptomatic hyponatremia requiring immediate intervention",
      "action": "Administer hypertonic saline immediately",
      "urgency": "immediate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Seizing patient with small cell lung cancer with Na of 115"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.ESE.SIADH.2024.SEV.01",
      "display_id": "ESE-SIADH-SEV1",
      "level": "Severe symptomatic hyponatremia",
      "criteria": [
        "Serum sodium < 120 mEq/L",
        "Neurologic symptoms (seizures, altered mental status)",
        "Acute onset or rapidly progressive"
      ],
      "management_implications": "Requires immediate treatment with hypertonic saline and close monitoring",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Seizures + Na < 120, Seizing patient with Na of 115"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-12-19",
  "normalizer_version": 1,
  "normalization_notes": "Generated from Divine Intervention, Inner Circle, and Emma Holliday board review materials. Key areas requiring verification against actual guidelines: 1) Specific fluid restriction protocols, 2) Vaptan dosing and selection criteria, 3) Hypertonic saline administration rates and monitoring, 4) Complete diagnostic workup requirements. Strong emphasis on paraneoplastic causes (especially SCLC) and drug-induced SIADH. Treatment hierarchy appears to be fluid restriction → demeclocycline/vaptans → hypertonic saline for severe cases.",
  "all_item_ids": [
    "PACK.ESE.SIADH.2024.REC.01",
    "PACK.ESE.SIADH.2024.REC.02",
    "PACK.ESE.SIADH.2024.REC.03",
    "PACK.ESE.SIADH.2024.REC.04",
    "PACK.ESE.SIADH.2024.DC.01",
    "PACK.ESE.SIADH.2024.T.01",
    "PACK.ESE.SIADH.2024.T.02",
    "PACK.ESE.SIADH.2024.TX.01",
    "PACK.ESE.SIADH.2024.TX.02",
    "PACK.ESE.SIADH.2024.TX.03",
    "PACK.ESE.SIADH.2024.TX.04",
    "PACK.ESE.SIADH.2024.RF.01",
    "PACK.ESE.SIADH.2024.SEV.01"
  ],
  "all_display_ids": [
    "ESE-SIADH-R1",
    "ESE-SIADH-R2",
    "ESE-SIADH-R3",
    "ESE-SIADH-R4",
    "ESE-SIADH-DC1",
    "ESE-SIADH-T1",
    "ESE-SIADH-T2",
    "ESE-SIADH-TX1",
    "ESE-SIADH-TX2",
    "ESE-SIADH-TX3",
    "ESE-SIADH-TX4",
    "ESE-SIADH-RF1",
    "ESE-SIADH-SEV1"
  ]
};
