import type { SourcePack } from './types';

export const PACK_GINA_ASTHMA_2024: SourcePack = {
  source_pack_id: 'PACK.GINA.ASTHMA.2024',
  source_name: 'GINA Report 2024: Global Strategy for Asthma Management and Prevention',
  source_registry_id: 'REG.GINA.ASTHMA',
  canonical_url: 'https://ginasthma.org/2024-report/',
  publication_year: 2024,
  guideline_body: 'GINA',

  topic_tags: ['Asthma', 'Reactive Airway Disease', 'Bronchospasm', 'Pulmonology', 'Allergy'],
  allowed_decision_scopes: [
    'asthma diagnosis and spirometry interpretation',
    'asthma severity classification',
    'stepwise pharmacotherapy',
    'ICS-formoterol as reliever',
    'acute exacerbation management',
    'biologic therapy for severe asthma',
    'asthma-COPD overlap considerations',
    'exercise-induced bronchoconstriction',
  ],
  excluded_decision_scopes: [
    'COPD-only management',
    'cystic fibrosis',
    'bronchiectasis management',
    'vocal cord dysfunction',
    'allergic rhinitis as primary diagnosis',
    'occupational asthma causative agent identification',
  ],

  recommendations: [
    {
      rec_id: 'PACK.GINA.ASTHMA.2024.REC.01',
      display_id: 'GINA-ASTHMA-R1',
      statement: 'GINA no longer recommends SABA-only treatment for asthma. All adults and adolescents with asthma should receive ICS-containing therapy: either as-needed low-dose ICS-formoterol (Track 1, preferred) or as-needed SABA with ICS whenever SABA is taken (Track 2).',
      normalized_claim: 'No more SABA-only asthma treatment. All patients need ICS: preferred Track 1 = PRN ICS-formoterol, Track 2 = SABA + ICS taken together.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'SYGMA 1/2 and Novel START trials showed PRN ICS-formoterol reduces severe exacerbations vs SABA-only',
      provenance: { section: 'Stepwise Approach', page_or_location: 'Chapter 3, Box 3-5' },
    },
    {
      rec_id: 'PACK.GINA.ASTHMA.2024.REC.02',
      display_id: 'GINA-ASTHMA-R2',
      statement: 'Low-dose ICS is recommended for all patients with persistent asthma symptoms. ICS reduces exacerbations, controls symptoms, and reduces the risk of asthma-related death.',
      normalized_claim: 'Low-dose ICS for all persistent asthma. ICS reduces exacerbations, symptoms, and asthma mortality. Cornerstone of asthma therapy.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Controller Therapy', page_or_location: 'Chapter 3' },
    },
    {
      rec_id: 'PACK.GINA.ASTHMA.2024.REC.03',
      display_id: 'GINA-ASTHMA-R3',
      statement: 'Step-up therapy should be considered when symptoms are not controlled despite good adherence and correct inhaler technique. Step-down should be attempted after 3 months of good control.',
      normalized_claim: 'Before stepping up: verify adherence, inhaler technique, trigger avoidance. Step down after 3 months good control. Never stop ICS completely.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Adjusting Treatment', page_or_location: 'Chapter 3' },
    },
    {
      rec_id: 'PACK.GINA.ASTHMA.2024.REC.04',
      display_id: 'GINA-ASTHMA-R4',
      statement: 'Biologic therapy should be considered for patients with severe asthma uncontrolled on high-dose ICS-LABA (Step 5). Selection guided by phenotype: anti-IgE (omalizumab) for allergic, anti-IL5/IL5R (mepolizumab, benralizumab) for eosinophilic, anti-IL4R (dupilumab) for eosinophilic or type 2, anti-TSLP (tezepelumab) for broad severe asthma.',
      normalized_claim: 'Severe asthma uncontrolled on Step 4-5: add biologic. Anti-IgE for allergic, anti-IL5 for eosinophilic, anti-IL4R for type 2, anti-TSLP for broad phenotype.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Severe Asthma / Biologics', page_or_location: 'Chapter 3, Step 5' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.GINA.ASTHMA.2024.DC.01',
      display_id: 'GINA-ASTHMA-DC1',
      name: 'Asthma Diagnosis',
      components: [
        'History of variable respiratory symptoms: wheeze, shortness of breath, chest tightness, cough (typically >1 type, worse at night/early morning, variable over time)',
        'Confirmed variable expiratory airflow limitation on spirometry',
        'Positive bronchodilator reversibility: FEV1 increase >=12% AND >=200 mL from baseline after 200-400 mcg salbutamol',
        'OR positive bronchial provocation test (methacholine PC20 <4 mg/mL or mannitol)',
        'OR excessive variability in PEF (>10% in adults)',
      ],
      threshold: 'FEV1 increase >=12% AND >=200 mL post-bronchodilator',
      interpretation: 'Both characteristic symptoms AND documented variable airflow limitation are required. Greater reversibility (>15% and >400 mL) increases diagnostic confidence. A normal spirometry does not exclude asthma — repeat testing or provocation may be needed.',
      normalized_claim: 'Asthma = variable symptoms + confirmed variable airflow limitation. Reversibility: FEV1 >=12% and >=200 mL post-bronchodilator.',
      provenance: { section: 'Diagnosis', page_or_location: 'Chapter 1, Box 1-2' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.GINA.ASTHMA.2024.T.01',
      display_id: 'GINA-ASTHMA-T1',
      parameter: 'FEV1 for severe exacerbation',
      value: '60',
      unit: '% predicted',
      clinical_meaning: 'FEV1 <60% predicted in an acute asthma exacerbation indicates severe obstruction requiring aggressive treatment including systemic corticosteroids and close monitoring.',
      normalized_claim: 'FEV1 <60% predicted in acute asthma = severe exacerbation requiring systemic steroids, frequent bronchodilators, and possible hospitalization.',
      direction: 'below',
      provenance: { section: 'Exacerbation Severity', page_or_location: 'Chapter 4, Box 4-3' },
    },
    {
      threshold_id: 'PACK.GINA.ASTHMA.2024.T.02',
      display_id: 'GINA-ASTHMA-T2',
      parameter: 'PEF for life-threatening asthma',
      value: '50',
      unit: '% predicted or personal best',
      clinical_meaning: 'PEF <50% of predicted or personal best in acute exacerbation indicates severe or life-threatening asthma requiring emergency department evaluation.',
      normalized_claim: 'PEF <50% predicted = severe/life-threatening exacerbation. PEF <25% = near-fatal asthma. Requires immediate emergency treatment.',
      direction: 'below',
      provenance: { section: 'Exacerbation Severity', page_or_location: 'Chapter 4, Box 4-3' },
    },
    {
      threshold_id: 'PACK.GINA.ASTHMA.2024.T.03',
      display_id: 'GINA-ASTHMA-T3',
      parameter: 'SpO2',
      value: '92',
      unit: '%',
      clinical_meaning: 'SpO2 <92% in acute asthma indicates severe exacerbation with significant ventilation-perfusion mismatch. Supplemental oxygen should be titrated to maintain SpO2 93-95% (not 100%, which may mask deterioration).',
      normalized_claim: 'SpO2 <92% in acute asthma = severe exacerbation. Target SpO2 93-95% with supplemental O2. Overoxgenation may mask deterioration.',
      direction: 'below',
      provenance: { section: 'Exacerbation Management', page_or_location: 'Chapter 4' },
    },
    {
      threshold_id: 'PACK.GINA.ASTHMA.2024.T.04',
      display_id: 'GINA-ASTHMA-T4',
      parameter: 'Bronchodilator reversibility (FEV1 increase)',
      value: '12% and 200 mL',
      clinical_meaning: 'An increase in FEV1 of >=12% AND >=200 mL from baseline after bronchodilator confirms variable airflow limitation consistent with asthma. Both criteria must be met simultaneously.',
      normalized_claim: 'Positive bronchodilator reversibility: FEV1 increase >=12% AND >=200 mL. Both thresholds must be met. Confirms asthma diagnosis.',
      direction: 'above',
      provenance: { section: 'Spirometry', page_or_location: 'Chapter 1, Box 1-2' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.GINA.ASTHMA.2024.TX.01',
      display_id: 'GINA-ASTHMA-TX1',
      action: 'Step 1-2: As-needed low-dose ICS-formoterol (Track 1, preferred) for mild asthma',
      normalized_claim: 'Steps 1-2 (mild asthma): PRN low-dose ICS-formoterol (budesonide-formoterol 200/6 mcg). No daily controller needed if symptoms infrequent. Replaces SABA-only approach.',
      condition: 'Mild asthma (symptoms <4-5 days/week, no waking, no risk factors)',
      drug_details: { drug: 'Budesonide-formoterol', dose: '200/6 mcg PRN', route: 'Inhaled' },
      provenance: { section: 'Stepwise Therapy', page_or_location: 'Chapter 3, Box 3-5' },
    },
    {
      step_id: 'PACK.GINA.ASTHMA.2024.TX.02',
      display_id: 'GINA-ASTHMA-TX2',
      action: 'Step 3: Low-dose ICS-LABA maintenance + PRN ICS-formoterol reliever',
      normalized_claim: 'Step 3 (moderate persistent): daily low-dose ICS-formoterol maintenance and reliever therapy (MART). Alternative: low-dose ICS-LABA + PRN SABA.',
      condition: 'Moderate persistent asthma (symptoms most days, or waking >=1/week)',
      drug_details: { drug: 'Budesonide-formoterol', dose: '200/6 mcg 1 puff BID + PRN', route: 'Inhaled' },
      escalation: 'If not controlled, increase to medium-dose ICS-LABA (Step 4)',
      provenance: { section: 'Stepwise Therapy', page_or_location: 'Chapter 3, Box 3-5' },
    },
    {
      step_id: 'PACK.GINA.ASTHMA.2024.TX.03',
      display_id: 'GINA-ASTHMA-TX3',
      action: 'Step 4-5: Medium/high-dose ICS-LABA, consider add-on therapies',
      normalized_claim: 'Step 4: medium-dose ICS-LABA. Step 5: high-dose ICS-LABA + add-on (LAMA tiotropium, biologic, or low-dose OCS as last resort). Phenotype assessment required at Step 5.',
      condition: 'Severe persistent asthma (daily symptoms, frequent exacerbations, limited activity)',
      drug_details: { drug: 'Budesonide-formoterol or fluticasone-salmeterol', dose: 'Medium to high dose ICS component', route: 'Inhaled' },
      escalation: 'Step 5: add tiotropium (LAMA), then biologic therapy based on phenotype. Low-dose OCS only as last resort due to adverse effects.',
      contraindications: ['Long-term OCS: monitor for adrenal suppression, osteoporosis, diabetes, cataracts'],
      provenance: { section: 'Stepwise Therapy', page_or_location: 'Chapter 3, Box 3-5' },
    },
    {
      step_id: 'PACK.GINA.ASTHMA.2024.TX.04',
      display_id: 'GINA-ASTHMA-TX4',
      action: 'Acute exacerbation: SABA, systemic corticosteroids, ipratropium, consider magnesium',
      normalized_claim: 'Acute asthma exacerbation: SABA 4-10 puffs q20min x3, prednis(ol)one 40-50mg PO (or IV methylprednisolone), add ipratropium for severe, IV magnesium sulfate 2g over 20min if life-threatening.',
      timing: 'Immediately at presentation',
      condition: 'Acute asthma exacerbation (any severity)',
      drug_details: { drug: 'Albuterol + prednisone', dose: 'Albuterol 4-10 puffs via MDI+spacer q20min x3; prednisone 40-50 mg', route: 'Inhaled + PO' },
      escalation: 'Severe: add ipratropium 4-8 puffs q20min. Life-threatening: IV magnesium sulfate 2g over 20 min. Consider IV aminophylline only if ICU. Intubation for respiratory failure.',
      provenance: { section: 'Exacerbation Management', page_or_location: 'Chapter 4, Box 4-4' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.GINA.ASTHMA.2024.RF.01',
      display_id: 'GINA-ASTHMA-RF1',
      finding: 'History of prior intubation or ICU admission for asthma',
      implication: 'Single strongest predictor of near-fatal asthma. Patient is at high risk for future life-threatening exacerbations.',
      action: 'Ensure patient has written asthma action plan, is on appropriate Step 4-5 therapy, has systemic corticosteroid prescription for emergencies, and has close follow-up.',
      urgency: 'urgent',
      provenance: { section: 'Risk Factors for Exacerbation', page_or_location: 'Chapter 2, Box 2-3' },
    },
    {
      flag_id: 'PACK.GINA.ASTHMA.2024.RF.02',
      display_id: 'GINA-ASTHMA-RF2',
      finding: '>2 ED visits or hospitalizations for asthma in the past year',
      implication: 'Indicates poorly controlled disease and high exacerbation risk. Often associated with poor adherence, inadequate controller therapy, or unrecognized triggers.',
      action: 'Review adherence and inhaler technique. Assess for comorbidities (GERD, rhinosinusitis, obesity, anxiety/depression). Consider step-up therapy and specialist referral.',
      urgency: 'urgent',
      provenance: { section: 'Risk Factors for Exacerbation', page_or_location: 'Chapter 2, Box 2-3' },
    },
    {
      flag_id: 'PACK.GINA.ASTHMA.2024.RF.03',
      display_id: 'GINA-ASTHMA-RF3',
      finding: 'Recent oral corticosteroid use or current high SABA use (>1 canister/month)',
      implication: 'Recent OCS use indicates recent severe exacerbation. High SABA use (overreliance on reliever) is an independent risk factor for exacerbation and death.',
      action: 'Step up controller therapy. SABA overuse (>3 canisters/year) associated with increased mortality. Transition to ICS-formoterol reliever to reduce SABA dependence.',
      urgency: 'urgent',
      provenance: { section: 'Risk Assessment', page_or_location: 'Chapter 2, Box 2-3' },
    },
    {
      flag_id: 'PACK.GINA.ASTHMA.2024.RF.04',
      display_id: 'GINA-ASTHMA-RF4',
      finding: 'FEV1 <60% predicted despite treatment',
      implication: 'Indicates severe persistent airflow limitation. Increased risk of exacerbations independent of symptom level. Some patients have poor symptom perception ("poor perceivers").',
      action: 'Optimize therapy to Step 4-5. Consider specialist referral for phenotyping and biologic therapy. Ensure patient understands severity even if symptoms seem mild.',
      urgency: 'urgent',
      provenance: { section: 'Risk Factors', page_or_location: 'Chapter 2, Box 2-3' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.GINA.ASTHMA.2024.SEV.01',
      display_id: 'GINA-ASTHMA-SEV1',
      level: 'Intermittent asthma',
      criteria: [
        'Symptoms <2 days/week',
        'Nighttime awakenings <=2x/month',
        'SABA use for symptom control <=2 days/week',
        'No interference with normal activity',
        'FEV1 >80% predicted',
        'FEV1/FVC normal',
      ],
      management_implications:
        'GINA Step 1: PRN low-dose ICS-formoterol (preferred). No daily controller needed. However, all patients still receive ICS with every reliever use. Annual reassessment. Risk factor assessment at every visit.',
      provenance: { section: 'Severity Classification', page_or_location: 'Chapter 2' },
    },
    {
      severity_id: 'PACK.GINA.ASTHMA.2024.SEV.02',
      display_id: 'GINA-ASTHMA-SEV2',
      level: 'Mild persistent asthma',
      criteria: [
        'Symptoms >2 days/week but not daily',
        'Nighttime awakenings 3-4x/month',
        'Some limitation of activity',
        'FEV1 >=80% predicted',
      ],
      management_implications:
        'GINA Step 2: daily low-dose ICS or PRN ICS-formoterol (MART). Low-dose ICS reduces exacerbation risk by ~50%. Check adherence before escalation. Review in 1-3 months.',
      provenance: { section: 'Severity Classification', page_or_location: 'Chapter 2' },
    },
    {
      severity_id: 'PACK.GINA.ASTHMA.2024.SEV.03',
      display_id: 'GINA-ASTHMA-SEV3',
      level: 'Moderate persistent asthma',
      criteria: [
        'Daily symptoms',
        'Nighttime awakenings >1x/week',
        'Daily use of SABA',
        'Some limitation of activity',
        'FEV1 60-80% predicted',
      ],
      management_implications:
        'GINA Step 3: low-dose ICS-LABA (MART preferred). Consider medium-dose ICS if not controlled. Assess comorbidities. Pulmonary function monitoring. Consider allergy testing and trigger avoidance strategies.',
      provenance: { section: 'Severity Classification', page_or_location: 'Chapter 2' },
    },
    {
      severity_id: 'PACK.GINA.ASTHMA.2024.SEV.04',
      display_id: 'GINA-ASTHMA-SEV4',
      level: 'Severe persistent asthma',
      criteria: [
        'Symptoms throughout the day',
        'Frequent nighttime awakenings (often nightly)',
        'Extreme limitation of activity',
        'FEV1 <60% predicted',
        'Frequent exacerbations (>=2/year requiring OCS)',
      ],
      management_implications:
        'GINA Steps 4-5: medium/high-dose ICS-LABA + add-on therapy. Phenotype assessment required (eosinophilic vs allergic vs non-type 2). Add LAMA (tiotropium). Consider biologic therapy. Specialist referral mandatory. Low-dose OCS only as last resort. Monitor for steroid side effects. Written action plan essential.',
      provenance: { section: 'Severe Asthma', page_or_location: 'Chapter 3' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for asthma. GINA 2024 with updated Track 1/Track 2 reliever approach (no more SABA-only). Covers stepwise therapy, ICS-formoterol as reliever, exacerbation management, biologic selection, and severity classification.',

  all_item_ids: [
    'PACK.GINA.ASTHMA.2024.REC.01', 'PACK.GINA.ASTHMA.2024.REC.02',
    'PACK.GINA.ASTHMA.2024.REC.03', 'PACK.GINA.ASTHMA.2024.REC.04',
    'PACK.GINA.ASTHMA.2024.DC.01',
    'PACK.GINA.ASTHMA.2024.T.01', 'PACK.GINA.ASTHMA.2024.T.02',
    'PACK.GINA.ASTHMA.2024.T.03', 'PACK.GINA.ASTHMA.2024.T.04',
    'PACK.GINA.ASTHMA.2024.TX.01', 'PACK.GINA.ASTHMA.2024.TX.02',
    'PACK.GINA.ASTHMA.2024.TX.03', 'PACK.GINA.ASTHMA.2024.TX.04',
    'PACK.GINA.ASTHMA.2024.RF.01', 'PACK.GINA.ASTHMA.2024.RF.02',
    'PACK.GINA.ASTHMA.2024.RF.03', 'PACK.GINA.ASTHMA.2024.RF.04',
    'PACK.GINA.ASTHMA.2024.SEV.01', 'PACK.GINA.ASTHMA.2024.SEV.02',
    'PACK.GINA.ASTHMA.2024.SEV.03', 'PACK.GINA.ASTHMA.2024.SEV.04',
  ],
  all_display_ids: [
    'GINA-ASTHMA-R1', 'GINA-ASTHMA-R2', 'GINA-ASTHMA-R3', 'GINA-ASTHMA-R4',
    'GINA-ASTHMA-DC1',
    'GINA-ASTHMA-T1', 'GINA-ASTHMA-T2', 'GINA-ASTHMA-T3', 'GINA-ASTHMA-T4',
    'GINA-ASTHMA-TX1', 'GINA-ASTHMA-TX2', 'GINA-ASTHMA-TX3', 'GINA-ASTHMA-TX4',
    'GINA-ASTHMA-RF1', 'GINA-ASTHMA-RF2', 'GINA-ASTHMA-RF3', 'GINA-ASTHMA-RF4',
    'GINA-ASTHMA-SEV1', 'GINA-ASTHMA-SEV2', 'GINA-ASTHMA-SEV3', 'GINA-ASTHMA-SEV4',
  ],
};
