import type { SourcePack } from './types';

export const PACK_GINA_PASTHMA_2024: SourcePack = {
  source_pack_id: 'PACK.GINA.PASTHMA.2024',
  source_name: 'GINA 2024 Global Strategy for Asthma Management and Prevention: Pediatric Sections (Children <=11 years)',
  source_registry_id: 'REG.GINA.PASTHMA',
  canonical_url: 'https://ginasthma.org/gina-reports/',
  publication_year: 2024,
  guideline_body: 'GINA',

  topic_tags: ['Pediatric Asthma', 'Asthma', 'ICS', 'SABA', 'Exercise-Induced Bronchoconstriction'],
  allowed_decision_scopes: [
    'pediatric asthma diagnosis',
    'asthma controller therapy initiation',
    'step-up and step-down therapy',
    'acute exacerbation management in children',
    'exercise-induced bronchoconstriction management',
    'inhaler technique and adherence',
  ],
  excluded_decision_scopes: [
    'adult asthma management',
    'severe asthma biologics',
    'occupational asthma',
    'asthma in pregnancy',
  ],

  recommendations: [
    {
      rec_id: 'PACK.GINA.PASTHMA.2024.REC.01',
      display_id: 'GINA-PASTHMA-R1',
      statement: 'In children 6-11 years, low-dose inhaled corticosteroid (ICS) is the preferred controller therapy for Step 2. ICS should be initiated when symptoms occur more than twice per month.',
      normalized_claim: 'Low-dose ICS is first-line controller for children 6-11 with asthma symptoms >2x/month (Step 2). Fluticasone 50-100mcg/day or budesonide 100-200mcg/day.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Stepwise Management 6-11', page_or_location: 'Figure 3.5' },
    },
    {
      rec_id: 'PACK.GINA.PASTHMA.2024.REC.02',
      display_id: 'GINA-PASTHMA-R2',
      statement: 'In children <=5 years, a trial of low-dose ICS (or intermittent ICS during viral episodes) is recommended when recurrent wheezing episodes suggest asthma.',
      normalized_claim: 'For children <=5 years with recurrent wheeze suggestive of asthma: trial of low-dose ICS for >=3 months; assess response to confirm diagnosis.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      context: 'Asthma diagnosis in children <5 is challenging; treatment response helps confirm diagnosis',
      provenance: { section: 'Preschool Wheeze', page_or_location: 'Section 6.2' },
    },
    {
      rec_id: 'PACK.GINA.PASTHMA.2024.REC.03',
      display_id: 'GINA-PASTHMA-R3',
      statement: 'SABA-only treatment (without ICS) is no longer recommended for any asthma patient, including children. Even mild asthma benefits from ICS-containing therapy.',
      normalized_claim: 'SABA-only treatment is NOT recommended; all children with asthma should have ICS-containing therapy (daily or as-needed with SABA).',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Key Changes', page_or_location: 'Section 3.1' },
    },
    {
      rec_id: 'PACK.GINA.PASTHMA.2024.REC.04',
      display_id: 'GINA-PASTHMA-R4',
      statement: 'Before stepping up therapy, verify inhaler technique, medication adherence, trigger avoidance, and correct diagnosis.',
      normalized_claim: 'Before step-up: check inhaler technique (with spacer/VHC in children), adherence, trigger exposure, and confirm asthma diagnosis.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Assessment Before Step-Up', page_or_location: 'Section 3.4' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.GINA.PASTHMA.2024.DC.01',
      display_id: 'GINA-PASTHMA-DC1',
      name: 'Asthma Diagnosis in Children 6-11 Years',
      components: [
        'History of variable respiratory symptoms: wheeze, cough, chest tightness, dyspnea',
        'Symptoms vary over time and in intensity',
        'Symptoms often worse at night or early morning',
        'Symptoms triggered by exercise, allergens, cold air, viral infections',
        'Variable expiratory airflow limitation on spirometry: FEV1/FVC <0.90 in children',
        'Positive bronchodilator reversibility: >=12% increase in FEV1 after SABA',
      ],
      interpretation: 'Both symptom pattern AND objective evidence of variable airflow limitation are needed. Spirometry can be reliably performed in most children >=6 years.',
      normalized_claim: 'Pediatric asthma diagnosis requires variable symptoms (wheeze, cough, dyspnea) plus spirometric evidence: FEV1/FVC <0.90 and >=12% bronchodilator reversibility.',
      provenance: { section: 'Diagnosis 6-11', page_or_location: 'Box 1-2' },
    },
    {
      criterion_id: 'PACK.GINA.PASTHMA.2024.DC.02',
      display_id: 'GINA-PASTHMA-DC2',
      name: 'Probability-Based Asthma Diagnosis in Children <=5 Years',
      components: [
        'Recurrent wheeze (>=3 episodes), especially if triggered by viral infections',
        'Atopic features: eczema, allergic rhinitis, food allergy, family history of asthma/atopy',
        'Wheeze occurs without colds',
        'Symptom improvement with ICS trial (>=3 months) supports diagnosis',
        'Spirometry not feasible; diagnosis is clinical and based on treatment response',
      ],
      interpretation: 'Asthma is more likely with atopic background, multiple wheezing episodes, and symptom improvement with controller therapy. Consider alternative diagnoses if no response to ICS trial.',
      normalized_claim: 'In children <=5 years, asthma diagnosis is probability-based: recurrent wheeze + atopic features + ICS response; spirometry not feasible at this age.',
      provenance: { section: 'Diagnosis <=5', page_or_location: 'Section 6.1' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.GINA.PASTHMA.2024.T.01',
      display_id: 'GINA-PASTHMA-T1',
      parameter: 'FEV1/FVC ratio for airflow limitation in children',
      value: '0.90',
      clinical_meaning: 'FEV1/FVC <0.90 in children indicates expiratory airflow limitation. Normal ratio is higher in children than adults.',
      normalized_claim: 'FEV1/FVC <0.90 in children 6-11 years indicates airflow limitation (lower threshold than adult 0.70).',
      direction: 'below',
      provenance: { section: 'Spirometry', page_or_location: 'Box 1-2' },
    },
    {
      threshold_id: 'PACK.GINA.PASTHMA.2024.T.02',
      display_id: 'GINA-PASTHMA-T2',
      parameter: 'Symptom frequency threshold for Step 2 controller initiation',
      value: '2',
      unit: 'times per month',
      clinical_meaning: 'Asthma symptoms occurring >2 times per month (or any nighttime awakening due to asthma) indicate need for regular ICS controller therapy (Step 2).',
      normalized_claim: 'Symptoms >2x/month or any nighttime symptoms triggers Step 2 (daily low-dose ICS) in children.',
      direction: 'above',
      provenance: { section: 'Stepwise Management', page_or_location: 'Figure 3.5' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.GINA.PASTHMA.2024.TX.01',
      display_id: 'GINA-PASTHMA-TX1',
      action: 'Step 2: Low-dose ICS controller therapy for children 6-11 years',
      normalized_claim: 'Low-dose ICS daily (fluticasone 50-100mcg/day or budesonide 100-200mcg/day via MDI + spacer) for symptoms >2x/month.',
      timing: 'At diagnosis when symptoms >2x/month',
      condition: 'Asthma symptoms >2 times per month in child 6-11 years',
      drug_details: { drug: 'Fluticasone propionate', dose: '50-100 mcg/day', route: 'MDI with spacer/VHC' },
      escalation: 'Step 3: Low-dose ICS + LABA (formoterol), or medium-dose ICS',
      provenance: { section: 'Stepwise Management', page_or_location: 'Figure 3.5, Step 2' },
    },
    {
      step_id: 'PACK.GINA.PASTHMA.2024.TX.02',
      display_id: 'GINA-PASTHMA-TX2',
      action: 'Acute exacerbation management in children',
      normalized_claim: 'Acute asthma exacerbation: SABA 4-10 puffs via MDI+spacer every 20 min for 1 hour, oral prednisolone 1-2 mg/kg/day (max 40mg) for 3-5 days, O2 to maintain SpO2 >=94%.',
      timing: 'At presentation with acute exacerbation',
      condition: 'Acute asthma exacerbation in child',
      drug_details: { drug: 'Prednisolone', dose: '1-2 mg/kg/day (max 40mg)', route: 'PO', duration: '3-5 days' },
      contraindications: ['Active varicella or herpes (relative for systemic steroids)'],
      provenance: { section: 'Acute Management', page_or_location: 'Section 4.2' },
    },
    {
      step_id: 'PACK.GINA.PASTHMA.2024.TX.03',
      display_id: 'GINA-PASTHMA-TX3',
      action: 'Exercise-induced bronchoconstriction (EIB) prevention',
      normalized_claim: 'EIB prevention: SABA 15 minutes before exercise. For frequent EIB despite SABA, daily low-dose ICS reduces exercise-induced symptoms. Warm-up period before exercise also helps.',
      timing: '15 minutes before exercise',
      condition: 'Exercise-induced bronchoconstriction',
      drug_details: { drug: 'Albuterol', dose: '2 puffs', route: 'MDI with spacer' },
      provenance: { section: 'Exercise-Induced BCC', page_or_location: 'Section 3.6' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.GINA.PASTHMA.2024.RF.01',
      display_id: 'GINA-PASTHMA-RF1',
      finding: 'Life-threatening asthma exacerbation: drowsiness, confusion, silent chest, cyanosis, poor respiratory effort, SpO2 <92%',
      implication: 'Impending respiratory arrest. Silent chest indicates minimal air movement despite severe obstruction.',
      action: 'Immediate SABA + ipratropium nebulization, IV magnesium sulfate (40-50 mg/kg, max 2g), IV corticosteroids, O2 to target SpO2 >=94%. Prepare for intubation. ICU transfer.',
      urgency: 'immediate',
      provenance: { section: 'Severe Exacerbation', page_or_location: 'Section 4.4' },
    },
    {
      flag_id: 'PACK.GINA.PASTHMA.2024.RF.02',
      display_id: 'GINA-PASTHMA-RF2',
      finding: 'Child with asthma-like symptoms unresponsive to standard ICS trial (>=3 months of good adherence and technique)',
      implication: 'May indicate alternative diagnosis: foreign body aspiration, tracheomalacia, vascular ring, cystic fibrosis, primary ciliary dyskinesia, immunodeficiency, or cardiac disease.',
      action: 'Reconsider diagnosis. Chest X-ray, sweat chloride test, CT if structural abnormality suspected, flexible bronchoscopy for persistent focal wheeze, immunoglobulin levels.',
      urgency: 'soon',
      provenance: { section: 'Differential Diagnosis', page_or_location: 'Box 1-3' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.GINA.PASTHMA.2024.SEV.01',
      display_id: 'GINA-PASTHMA-SEV1',
      level: 'Well-controlled asthma in children',
      criteria: [
        'Daytime symptoms <=2 times per week',
        'No nighttime awakening due to asthma',
        'Reliever (SABA) use <=2 times per week',
        'No activity limitation',
        'FEV1 >80% predicted (in children >=6 who can perform spirometry)',
      ],
      management_implications:
        'Continue current therapy for at least 3 months. Consider step-down if well-controlled for >=3 months. Maintain lowest effective ICS dose. Continue monitoring technique and adherence. Annual influenza vaccination.',
      provenance: { section: 'Asthma Control Assessment', page_or_location: 'Box 2-2' },
    },
    {
      severity_id: 'PACK.GINA.PASTHMA.2024.SEV.02',
      display_id: 'GINA-PASTHMA-SEV2',
      level: 'Uncontrolled asthma in children',
      criteria: [
        'Daytime symptoms >2 times per week',
        'Nighttime awakening due to asthma >=1 time per week',
        'SABA use >2 times per week',
        'Activity limitation due to asthma',
        '>=1 exacerbation requiring oral corticosteroids in past year',
      ],
      management_implications:
        'Before step-up: verify diagnosis, check technique, assess adherence, identify triggers. If confirmed: step up one level. Step 3: low-dose ICS + LABA or medium-dose ICS. Step 4: medium-dose ICS + LABA. Refer to specialist if not controlled at Step 4.',
      provenance: { section: 'Uncontrolled Asthma', page_or_location: 'Box 2-2, Section 3.4' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Pediatrics pack for asthma per GINA 2024. Covers diagnosis (<5 vs 6-11), stepwise ICS therapy, acute exacerbation, exercise-induced bronchoconstriction.',

  all_item_ids: [
    'PACK.GINA.PASTHMA.2024.REC.01', 'PACK.GINA.PASTHMA.2024.REC.02', 'PACK.GINA.PASTHMA.2024.REC.03',
    'PACK.GINA.PASTHMA.2024.REC.04', 'PACK.GINA.PASTHMA.2024.DC.01', 'PACK.GINA.PASTHMA.2024.DC.02',
    'PACK.GINA.PASTHMA.2024.T.01', 'PACK.GINA.PASTHMA.2024.T.02',
    'PACK.GINA.PASTHMA.2024.TX.01', 'PACK.GINA.PASTHMA.2024.TX.02', 'PACK.GINA.PASTHMA.2024.TX.03',
    'PACK.GINA.PASTHMA.2024.RF.01', 'PACK.GINA.PASTHMA.2024.RF.02',
    'PACK.GINA.PASTHMA.2024.SEV.01', 'PACK.GINA.PASTHMA.2024.SEV.02',
  ],
  all_display_ids: [
    'GINA-PASTHMA-R1', 'GINA-PASTHMA-R2', 'GINA-PASTHMA-R3', 'GINA-PASTHMA-R4',
    'GINA-PASTHMA-DC1', 'GINA-PASTHMA-DC2',
    'GINA-PASTHMA-T1', 'GINA-PASTHMA-T2',
    'GINA-PASTHMA-TX1', 'GINA-PASTHMA-TX2', 'GINA-PASTHMA-TX3',
    'GINA-PASTHMA-RF1', 'GINA-PASTHMA-RF2',
    'GINA-PASTHMA-SEV1', 'GINA-PASTHMA-SEV2',
  ],
};
