import type { SourcePack } from './types';

export const PACK_GOLD_COPD_2024: SourcePack = {
  source_pack_id: 'PACK.GOLD.COPD.2024',
  source_name: 'GOLD Report 2024: Global Strategy for Prevention, Diagnosis, and Management of COPD',
  source_registry_id: 'REG.GOLD.COPD',
  canonical_url: 'https://goldcopd.org/2024-gold-report/',
  publication_year: 2024,
  guideline_body: 'GOLD',

  topic_tags: ['COPD', 'Chronic Bronchitis', 'Emphysema', 'AECOPD', 'Pulmonology'],
  allowed_decision_scopes: [
    'COPD diagnosis with spirometry',
    'GOLD ABE classification',
    'stable COPD pharmacotherapy',
    'ICS escalation criteria',
    'acute exacerbation management',
    'oxygen therapy indications',
    'NIPPV indications in AECOPD',
    'smoking cessation in COPD',
  ],
  excluded_decision_scopes: [
    'asthma management',
    'interstitial lung disease',
    'lung cancer screening',
    'pulmonary rehabilitation exercise prescriptions',
    'lung volume reduction surgery patient selection',
    'lung transplant criteria',
  ],

  recommendations: [
    {
      rec_id: 'PACK.GOLD.COPD.2024.REC.01',
      display_id: 'GOLD-COPD-R1',
      statement: 'Spirometry is required to establish a diagnosis of COPD. A post-bronchodilator FEV1/FVC <0.7 confirms persistent airflow limitation.',
      normalized_claim: 'COPD diagnosis requires post-bronchodilator spirometry showing FEV1/FVC <0.7. Clinical symptoms alone are insufficient.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Diagnosis', page_or_location: 'Chapter 2' },
    },
    {
      rec_id: 'PACK.GOLD.COPD.2024.REC.02',
      display_id: 'GOLD-COPD-R2',
      statement: 'For Group B patients (low exacerbation risk, more symptoms), initial therapy should be a long-acting bronchodilator: LAMA preferred over LABA.',
      normalized_claim: 'Group B (mMRC >=2 or CAT >=10, 0-1 moderate exacerbations): start LAMA monotherapy. LAMA preferred over LABA for exacerbation prevention.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Pharmacologic Treatment Algorithm', page_or_location: 'Chapter 3, Figure 3.2' },
    },
    {
      rec_id: 'PACK.GOLD.COPD.2024.REC.03',
      display_id: 'GOLD-COPD-R3',
      statement: 'For Group E patients (high exacerbation risk), initial therapy should be LABA + LAMA combination. If blood eosinophils >=300 cells/microL, consider LABA + LAMA + ICS (triple therapy).',
      normalized_claim: 'Group E (>=2 moderate or >=1 severe exacerbation): start LABA + LAMA. Add ICS if eosinophils >=300. Triple therapy (ICS/LABA/LAMA) reduces exacerbations and mortality.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'IMPACT and ETHOS trials demonstrated mortality benefit of triple therapy in frequent exacerbators',
      provenance: { section: 'Pharmacologic Treatment Algorithm', page_or_location: 'Chapter 3, Figure 3.2' },
    },
    {
      rec_id: 'PACK.GOLD.COPD.2024.REC.04',
      display_id: 'GOLD-COPD-R4',
      statement: 'ICS should be added to bronchodilator therapy when blood eosinophils are >=300 cells/microL in patients with persistent exacerbations. ICS should be avoided when eosinophils <100.',
      normalized_claim: 'ICS escalation guided by blood eosinophils: add ICS if >=300, consider if 100-299 with exacerbations, avoid if <100.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'ICS in COPD', page_or_location: 'Chapter 3' },
    },
    {
      rec_id: 'PACK.GOLD.COPD.2024.REC.05',
      display_id: 'GOLD-COPD-R5',
      statement: 'Smoking cessation is the single most effective intervention to reduce the rate of FEV1 decline and alter the natural history of COPD.',
      normalized_claim: 'Smoking cessation is the most effective intervention in COPD. Pharmacotherapy (varenicline, NRT, bupropion) + counseling improves quit rates.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Smoking Cessation', page_or_location: 'Chapter 3' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.GOLD.COPD.2024.DC.01',
      display_id: 'GOLD-COPD-DC1',
      name: 'COPD Spirometric Diagnosis',
      components: [
        'Persistent respiratory symptoms (dyspnea, chronic cough, sputum production)',
        'History of risk factor exposure (tobacco smoke, biomass fuel, occupational dusts)',
        'Post-bronchodilator spirometry: FEV1/FVC <0.7',
      ],
      threshold: 'FEV1/FVC <0.7 post-bronchodilator',
      interpretation: 'Confirms persistent airflow limitation consistent with COPD. Spirometry must be performed after adequate bronchodilator administration (400 mcg salbutamol). A normal FEV1/FVC ratio excludes COPD.',
      normalized_claim: 'COPD diagnosed by symptoms + risk factors + post-bronchodilator FEV1/FVC <0.7. Spirometry is mandatory for diagnosis.',
      provenance: { section: 'Diagnosis', page_or_location: 'Chapter 2, Table 2.4' },
    },
    {
      criterion_id: 'PACK.GOLD.COPD.2024.DC.02',
      display_id: 'GOLD-COPD-DC2',
      name: 'GOLD ABE Classification',
      components: [
        'Group A: 0-1 moderate exacerbation (not leading to hospitalization) AND mMRC 0-1 or CAT <10',
        'Group B: 0-1 moderate exacerbation (not leading to hospitalization) AND mMRC >=2 or CAT >=10',
        'Group E: >=2 moderate exacerbations OR >=1 exacerbation leading to hospitalization (regardless of symptoms)',
      ],
      interpretation: 'Replaces former ABCD classification (2024 update merged C and D into E). Drives initial pharmacotherapy selection. Exacerbation history takes priority for Group E classification.',
      normalized_claim: 'GOLD ABE: A (low risk, fewer symptoms), B (low risk, more symptoms), E (high exacerbation risk). Group E defined by >=2 moderate or >=1 severe exacerbation.',
      provenance: { section: 'Assessment', page_or_location: 'Chapter 2, Figure 2.4' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.GOLD.COPD.2024.T.01',
      display_id: 'GOLD-COPD-T1',
      parameter: 'FEV1/FVC ratio (post-bronchodilator)',
      value: '0.7',
      clinical_meaning: 'A fixed ratio of FEV1/FVC <0.7 after bronchodilator confirms airflow limitation. May overdiagnose COPD in elderly (where LLN may be more appropriate).',
      normalized_claim: 'Post-bronchodilator FEV1/FVC <0.7 confirms COPD. Fixed ratio may overdiagnose in elderly; LLN is an alternative.',
      direction: 'below',
      provenance: { section: 'Spirometry', page_or_location: 'Chapter 2' },
    },
    {
      threshold_id: 'PACK.GOLD.COPD.2024.T.02',
      display_id: 'GOLD-COPD-T2',
      parameter: 'Blood eosinophil count for ICS indication',
      value: '300',
      unit: 'cells/microL',
      clinical_meaning: 'Blood eosinophils >=300 cells/microL predict good response to ICS and are an indication to add ICS to bronchodilator therapy in patients with persistent exacerbations.',
      normalized_claim: 'Blood eosinophils >=300 cells/microL: add ICS. 100-299: consider ICS if exacerbations persist. <100: ICS unlikely to benefit.',
      direction: 'above',
      provenance: { section: 'ICS Considerations', page_or_location: 'Chapter 3' },
    },
    {
      threshold_id: 'PACK.GOLD.COPD.2024.T.03',
      display_id: 'GOLD-COPD-T3',
      parameter: 'Exacerbation frequency for Group E classification',
      value: '2 moderate or 1 severe',
      clinical_meaning: '>=2 moderate exacerbations or >=1 exacerbation requiring hospitalization in the prior year classifies a patient as Group E, triggering combination bronchodilator therapy.',
      normalized_claim: 'Group E: >=2 moderate exacerbations/year or >=1 hospitalization for exacerbation. Triggers LABA + LAMA initial therapy.',
      direction: 'above',
      provenance: { section: 'ABE Classification', page_or_location: 'Chapter 2, Figure 2.4' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.GOLD.COPD.2024.TX.01',
      display_id: 'GOLD-COPD-TX1',
      action: 'Stable COPD: Initiate bronchodilator therapy based on ABE group',
      normalized_claim: 'Group A: PRN short-acting bronchodilator. Group B: LAMA monotherapy. Group E: LABA + LAMA combination. Escalate to triple therapy (ICS/LABA/LAMA) if eosinophils >=300.',
      condition: 'Stable COPD (not exacerbating)',
      drug_details: { drug: 'LAMA (tiotropium) or LABA+LAMA (umeclidinium-vilanterol)', route: 'Inhaled' },
      escalation: 'If persistent dyspnea on monotherapy, escalate to LABA + LAMA. If persistent exacerbations and eosinophils >=300, add ICS for triple therapy.',
      provenance: { section: 'Initial Pharmacotherapy', page_or_location: 'Chapter 3, Figure 3.2' },
    },
    {
      step_id: 'PACK.GOLD.COPD.2024.TX.02',
      display_id: 'GOLD-COPD-TX2',
      action: 'AECOPD: Short-acting bronchodilators + systemic corticosteroids',
      normalized_claim: 'AECOPD treatment: SABAs (albuterol) q1-4h, prednisone 40 mg/day x5 days, antibiotics if purulent sputum or severe exacerbation.',
      timing: 'At presentation of acute exacerbation',
      condition: 'Acute exacerbation of COPD (AECOPD)',
      drug_details: { drug: 'Prednisone', dose: '40 mg daily', route: 'PO', duration: '5 days' },
      contraindications: ['Active GI bleeding for systemic steroids'],
      escalation: 'If inadequate response or severe exacerbation, add NIPPV if respiratory acidosis present (pH <7.35). Intubation if NIPPV fails.',
      provenance: { section: 'Exacerbation Management', page_or_location: 'Chapter 5' },
    },
    {
      step_id: 'PACK.GOLD.COPD.2024.TX.03',
      display_id: 'GOLD-COPD-TX3',
      action: 'AECOPD: Antibiotics for purulent exacerbations',
      normalized_claim: 'Antibiotics indicated for AECOPD with: (1) increased sputum purulence + increased dyspnea or sputum volume, (2) severe exacerbation requiring mechanical ventilation. Typical agents: amoxicillin-clavulanate, azithromycin, or doxycycline.',
      timing: 'At presentation of AECOPD with purulent sputum',
      condition: 'AECOPD with purulent sputum or requiring ventilatory support',
      drug_details: { drug: 'Amoxicillin-clavulanate or azithromycin', dose: 'Amox-clav 875/125 BID or azithromycin 500 then 250 daily', route: 'PO', duration: '5-7 days' },
      provenance: { section: 'Exacerbation Antibiotics', page_or_location: 'Chapter 5' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.GOLD.COPD.2024.RF.01',
      display_id: 'GOLD-COPD-RF1',
      finding: 'Acute respiratory failure in AECOPD: respiratory rate >30, accessory muscle use, paradoxical abdominal breathing, pH <7.35 with PaCO2 >45 mmHg',
      implication: 'Indicates severe exacerbation with respiratory acidosis. Mortality is high without ventilatory support.',
      action: 'Initiate NIPPV (BiPAP) immediately if pH 7.25-7.35. Consider intubation and invasive ventilation if pH <7.25, altered consciousness, or NIPPV failure.',
      urgency: 'immediate',
      provenance: { section: 'Respiratory Failure in AECOPD', page_or_location: 'Chapter 5' },
    },
    {
      flag_id: 'PACK.GOLD.COPD.2024.RF.02',
      display_id: 'GOLD-COPD-RF2',
      finding: 'Signs of cor pulmonale: peripheral edema, elevated JVP, hepatomegaly, tricuspid regurgitation murmur in a COPD patient',
      implication: 'Indicates right heart failure secondary to pulmonary hypertension from chronic hypoxemia. Associated with poor prognosis.',
      action: 'Long-term oxygen therapy (LTOT) if PaO2 <=55 mmHg or SpO2 <=88%. Diuretics for fluid overload. Evaluate for pulmonary hypertension workup.',
      urgency: 'urgent',
      provenance: { section: 'Comorbidities', page_or_location: 'Chapter 6' },
    },
    {
      flag_id: 'PACK.GOLD.COPD.2024.RF.03',
      display_id: 'GOLD-COPD-RF3',
      finding: 'Need for invasive mechanical ventilation during AECOPD',
      implication: 'Indicates life-threatening exacerbation. In-hospital mortality 15-25%. Marks transition to severe disease trajectory.',
      action: 'ICU admission. Intubation with lung-protective ventilation (avoid auto-PEEP). Optimize bronchodilators and steroids. Plan for difficult weaning.',
      urgency: 'immediate',
      provenance: { section: 'Ventilatory Support', page_or_location: 'Chapter 5' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.GOLD.COPD.2024.SEV.01',
      display_id: 'GOLD-COPD-SEV1',
      level: 'GOLD 1 - Mild',
      criteria: [
        'Post-bronchodilator FEV1 >=80% predicted',
        'FEV1/FVC <0.7',
      ],
      management_implications:
        'Patient may not be aware of abnormal lung function. Short-acting bronchodilator PRN may be sufficient. Smoking cessation counseling and influenza/pneumococcal vaccination. Annual spirometry monitoring.',
      provenance: { section: 'Severity Classification', page_or_location: 'Chapter 2, Table 2.5' },
    },
    {
      severity_id: 'PACK.GOLD.COPD.2024.SEV.02',
      display_id: 'GOLD-COPD-SEV2',
      level: 'GOLD 2 - Moderate',
      criteria: [
        'Post-bronchodilator FEV1 50-79% predicted',
        'FEV1/FVC <0.7',
      ],
      management_implications:
        'Symptoms typically prompt medical attention. Long-acting bronchodilator indicated. Pulmonary rehabilitation referral. Assessment for oxygen needs during exertion.',
      provenance: { section: 'Severity Classification', page_or_location: 'Chapter 2, Table 2.5' },
    },
    {
      severity_id: 'PACK.GOLD.COPD.2024.SEV.03',
      display_id: 'GOLD-COPD-SEV3',
      level: 'GOLD 3 - Severe',
      criteria: [
        'Post-bronchodilator FEV1 30-49% predicted',
        'FEV1/FVC <0.7',
      ],
      management_implications:
        'Significant dyspnea and exercise limitation. Combination bronchodilator therapy (LABA + LAMA). Consider ICS if eosinophilic phenotype. Pulmonary rehabilitation. Evaluate for LTOT. Frequent exacerbation monitoring.',
      provenance: { section: 'Severity Classification', page_or_location: 'Chapter 2, Table 2.5' },
    },
    {
      severity_id: 'PACK.GOLD.COPD.2024.SEV.04',
      display_id: 'GOLD-COPD-SEV4',
      level: 'GOLD 4 - Very Severe',
      criteria: [
        'Post-bronchodilator FEV1 <30% predicted',
        'FEV1/FVC <0.7',
      ],
      management_implications:
        'Profound airflow limitation. Quality of life severely impaired. High risk of exacerbations and death. Triple therapy (ICS/LABA/LAMA) typically indicated. LTOT if hypoxemic. Evaluate for lung volume reduction surgery or transplant referral. Palliative care discussion.',
      provenance: { section: 'Severity Classification', page_or_location: 'Chapter 2, Table 2.5' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for COPD. GOLD 2024 report with updated ABE classification (replacing former ABCD). Covers spirometric diagnosis, pharmacotherapy escalation, eosinophil-guided ICS, and AECOPD management.',

  all_item_ids: [
    'PACK.GOLD.COPD.2024.REC.01', 'PACK.GOLD.COPD.2024.REC.02', 'PACK.GOLD.COPD.2024.REC.03',
    'PACK.GOLD.COPD.2024.REC.04', 'PACK.GOLD.COPD.2024.REC.05',
    'PACK.GOLD.COPD.2024.DC.01', 'PACK.GOLD.COPD.2024.DC.02',
    'PACK.GOLD.COPD.2024.T.01', 'PACK.GOLD.COPD.2024.T.02', 'PACK.GOLD.COPD.2024.T.03',
    'PACK.GOLD.COPD.2024.TX.01', 'PACK.GOLD.COPD.2024.TX.02', 'PACK.GOLD.COPD.2024.TX.03',
    'PACK.GOLD.COPD.2024.RF.01', 'PACK.GOLD.COPD.2024.RF.02', 'PACK.GOLD.COPD.2024.RF.03',
    'PACK.GOLD.COPD.2024.SEV.01', 'PACK.GOLD.COPD.2024.SEV.02',
    'PACK.GOLD.COPD.2024.SEV.03', 'PACK.GOLD.COPD.2024.SEV.04',
  ],
  all_display_ids: [
    'GOLD-COPD-R1', 'GOLD-COPD-R2', 'GOLD-COPD-R3', 'GOLD-COPD-R4', 'GOLD-COPD-R5',
    'GOLD-COPD-DC1', 'GOLD-COPD-DC2',
    'GOLD-COPD-T1', 'GOLD-COPD-T2', 'GOLD-COPD-T3',
    'GOLD-COPD-TX1', 'GOLD-COPD-TX2', 'GOLD-COPD-TX3',
    'GOLD-COPD-RF1', 'GOLD-COPD-RF2', 'GOLD-COPD-RF3',
    'GOLD-COPD-SEV1', 'GOLD-COPD-SEV2', 'GOLD-COPD-SEV3', 'GOLD-COPD-SEV4',
  ],
};
