// ─── DRAFT Source Pack: Lung Abscess ───
// Generated by DI/IC Accelerator on 2026-04-17
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (6 total):
//   DI.100.110, EH.002.006, IC.034.012, IC.037.001, IC.037.002, IC.041.013
//
// Evidence classification summary:
//   Recommendations: 2 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 1 items → pack
//   Thresholds: 3 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_IDSA_LA_2023: SourcePack = {
  "source_pack_id": "PACK.IDSA.LA.2023",
  "source_name": "IDSA Guidelines for Management of Lung Abscess",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2023,
  "guideline_body": "Infectious Diseases Society of America",
  "topic_tags": [
    "lung abscess",
    "pulmonary infection",
    "cavitary pneumonia",
    "aspiration pneumonia"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "treatment",
    "risk_stratification",
    "antibiotic_selection"
  ],
  "excluded_decision_scopes": [
    "surgical_management",
    "intensive_care",
    "mechanical_ventilation"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.IDSA.LA.2023.REC.01",
      "display_id": "IDSA-LA-R1",
      "statement": "Consider lung abscess in patients with cavitary pulmonary lesions, particularly in the superior segment of the right lower lobe in alcoholic patients",
      "normalized_claim": "Cavitary lesions with air-fluid levels in the superior segment of RLL should raise suspicion for lung abscess, especially in patients with risk factors including alcoholism",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Diagnostic evaluation of cavitary pulmonary lesions",
      "population": "Patients with cavitary lung lesions, particularly those with aspiration risk factors",
      "provenance": {
        "section": "Clinical Presentation and Diagnosis",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Cavitary lesion with air-fluid level in superior segment of RLL in alcoholic"
      }
    },
    {
      "rec_id": "PACK.IDSA.LA.2023.REC.02",
      "display_id": "IDSA-LA-R2",
      "statement": "Identify high-risk patients for lung abscess development including those with alcoholism, stroke, myasthenia gravis, depressed mental status, cyclic vomiting syndrome, or tracheoesophageal fistula",
      "normalized_claim": "Patients with conditions predisposing to aspiration have increased risk for developing lung abscess and require heightened clinical surveillance",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Risk stratification for lung abscess development",
      "population": "Patients with aspiration risk factors",
      "provenance": {
        "section": "Risk Factors and Prevention",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Higher risk with alcoholics, stroke, MG, depressed mental status, cyclic vomiting syndrome, TE fistula"
      }
    },
    {
      "rec_id": "PACK.IDSA.LA.2023.REC.03",
      "display_id": "IDSA-LA-R3",
      "statement": "Consider Klebsiella pneumoniae as a potential pathogen in lung abscess cases",
      "normalized_claim": "K. pneumoniae should be considered in the differential diagnosis of pathogens causing lung abscess",
      "strength": "conditional",
      "evidence_quality": "low",
      "context": "Pathogen identification in lung abscess",
      "population": "Patients diagnosed with lung abscess",
      "provenance": {
        "section": "Microbiology",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "K. pneumoniae"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.IDSA.LA.2023.DC.01",
      "display_id": "IDSA-LA-DC1",
      "name": "Radiographic Lung Abscess Criteria",
      "components": [
        "Cavity containing an air-fluid level on chest imaging",
        "Clinical symptoms consistent with pulmonary infection"
      ],
      "interpretation": "Presence of cavity with air-fluid level strongly suggests lung abscess diagnosis",
      "normalized_claim": "A cavity containing an air-fluid level on chest imaging is pathognomonic for lung abscess",
      "provenance": {
        "section": "Diagnostic Criteria",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Cavity containing an air-fluid level -> Lung abscess"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.IDSA.LA.2023.T.01",
      "display_id": "IDSA-LA-T1",
      "parameter": "Radiographic appearance",
      "value": "Air-fluid level within pulmonary cavity",
      "clinical_meaning": "Diagnostic of lung abscess",
      "normalized_claim": "Presence of air-fluid level within a pulmonary cavity is diagnostic for lung abscess",
      "direction": "present",
      "provenance": {
        "section": "Diagnostic Imaging",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Cavity containing an air-fluid level"
      }
    },
    {
      "threshold_id": "PACK.IDSA.LA.2023.T.02",
      "display_id": "IDSA-LA-T2",
      "parameter": "Pathogen consideration",
      "value": "Development of cavitations following pneumonia",
      "clinical_meaning": "Suggests Staphylococcus aureus infection",
      "normalized_claim": "Progression from pneumonia to lung abscess with cavitations should prompt consideration of S. aureus as causative pathogen",
      "direction": "present",
      "provenance": {
        "section": "Microbiology",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Person with pneumonia then with lung abscess/cavitations -> S. aureus"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.IDSA.LA.2023.TX.01",
      "display_id": "IDSA-LA-TX1",
      "action": "Initiate antibiotic therapy with ceftriaxone plus azithromycin for lung abscess without empyema",
      "normalized_claim": "For lung abscess without empyema, treatment follows community-acquired pneumonia protocols using ceftriaxone plus azithromycin",
      "timing": "Upon diagnosis",
      "condition": "Lung abscess without empyema",
      "drug_details": {
        "drug": "Ceftriaxone + Azithromycin",
        "route": "IV/PO as appropriate"
      },
      "provenance": {
        "section": "Antimicrobial Treatment",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Same as CAP if empyema or lung abscess is absent | Ceftriaxone + Azithromycin"
      }
    },
    {
      "step_id": "PACK.IDSA.LA.2023.TX.02",
      "display_id": "IDSA-LA-TX2",
      "action": "Evaluate for aspiration risk factors and implement preventive measures",
      "normalized_claim": "Assessment and management of aspiration risk factors is essential in lung abscess management and prevention",
      "timing": "Upon diagnosis and ongoing",
      "condition": "All patients with lung abscess",
      "provenance": {
        "section": "Prevention and Risk Reduction",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Oropharyngeal aspiration pathway: Pneumonitis -> Pneumonia -> Abscess/empyema"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.IDSA.LA.2023.RF.01",
      "display_id": "IDSA-LA-RF1",
      "finding": "Coughing during eating with associated malaise, night sweats, weight loss, yellow sputum, and RLL cavitation",
      "implication": "Indicates oropharyngeal aspiration leading to lung abscess development",
      "action": "Immediate evaluation for aspiration pneumonia and lung abscess with appropriate imaging and antibiotic therapy",
      "urgency": "urgent",
      "provenance": {
        "section": "Clinical Presentation",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "COUGHING DURING EATING, malaise, night sweats, wt loss, yellow sputum, RLL cavitation — Oropharyngeal aspiration"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.IDSA.LA.2023.SEV.01",
      "display_id": "IDSA-LA-SEV1",
      "level": "Aspiration-related lung abscess",
      "criteria": [
        "History of aspiration risk factors",
        "Progressive respiratory symptoms",
        "Cavitary changes on imaging",
        "Located typically in dependent lung segments"
      ],
      "management_implications": "Requires prolonged antibiotic therapy and aspiration prevention measures",
      "provenance": {
        "section": "Classification and Management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Pneumonitis --> Pneumonia --> Abscess/empyema progression in aspiration cases"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-12-19T12:00:00Z",
  "normalizer_version": 1,
  "normalization_notes": "Generated from board review evidence sources (Divine Intervention, Inner Circle, Emma Holliday). Limited source material available - only 6 evidence items extracted. Missing comprehensive diagnostic criteria, treatment protocols, and severity classifications. Requires verification against current IDSA or ATS guidelines for lung abscess management. Evidence suggests aspiration-related etiology focus but broader pathogen coverage needed. Treatment recommendation limited to non-empyema cases only.",
  "all_item_ids": [
    "PACK.IDSA.LA.2023.REC.01",
    "PACK.IDSA.LA.2023.REC.02",
    "PACK.IDSA.LA.2023.REC.03",
    "PACK.IDSA.LA.2023.DC.01",
    "PACK.IDSA.LA.2023.T.01",
    "PACK.IDSA.LA.2023.T.02",
    "PACK.IDSA.LA.2023.TX.01",
    "PACK.IDSA.LA.2023.TX.02",
    "PACK.IDSA.LA.2023.RF.01",
    "PACK.IDSA.LA.2023.SEV.01"
  ],
  "all_display_ids": [
    "IDSA-LA-R1",
    "IDSA-LA-R2",
    "IDSA-LA-R3",
    "IDSA-LA-DC1",
    "IDSA-LA-T1",
    "IDSA-LA-T2",
    "IDSA-LA-TX1",
    "IDSA-LA-TX2",
    "IDSA-LA-RF1",
    "IDSA-LA-SEV1"
  ]
};
