import type { SourcePack } from './types';

export const PACK_IDSA_UTI_2011: SourcePack = {
  source_pack_id: 'PACK.IDSA.UTI.2011',
  source_name: 'IDSA/ESCMID Guidelines for the Treatment of Acute Uncomplicated Cystitis and Pyelonephritis in Women',
  canonical_url: 'https://doi.org/10.1093/cid/ciq257',
  publication_year: 2011,
  guideline_body: 'IDSA',

  topic_tags: ['UTI', 'Cystitis', 'Pyelonephritis', 'CAUTI', 'Infectious Disease', 'Urology'],
  allowed_decision_scopes: [
    'uncomplicated cystitis antibiotic selection',
    'acute pyelonephritis treatment — outpatient vs inpatient',
    'complicated UTI management',
    'catheter-associated UTI diagnosis and treatment',
    'fluoroquinolone stewardship in UTI',
    'recurrent UTI prophylaxis',
    'asymptomatic bacteriuria — when to treat',
  ],
  excluded_decision_scopes: [
    'UTI in men (separate guidelines)',
    'UTI in children',
    'urologic structural abnormalities',
    'renal abscess or perinephric abscess drainage',
    'sexually transmitted infections (covered in separate pack)',
  ],

  recommendations: [
    {
      rec_id: 'PACK.IDSA.UTI.2011.REC.01',
      display_id: 'IDSA-UTI-R1',
      statement: 'Nitrofurantoin monohydrate/macrocrystals 100mg BID for 5 days is recommended as first-line therapy for uncomplicated cystitis.',
      normalized_claim: 'Nitrofurantoin 100mg BID x 5 days is first-line for uncomplicated cystitis. Avoid if CrCl <30 mL/min or suspected pyelonephritis (poor tissue penetration).',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Uncomplicated Cystitis', page_or_location: 'Section 3, Table 1' },
    },
    {
      rec_id: 'PACK.IDSA.UTI.2011.REC.02',
      display_id: 'IDSA-UTI-R2',
      statement: 'TMP-SMX DS BID for 3 days is recommended for uncomplicated cystitis when local E. coli resistance rates are <20%.',
      normalized_claim: 'TMP-SMX DS BID x 3 days for uncomplicated cystitis if local E. coli resistance <20%. Check local antibiogram before prescribing.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Uncomplicated Cystitis', page_or_location: 'Section 3, Table 1' },
    },
    {
      rec_id: 'PACK.IDSA.UTI.2011.REC.03',
      display_id: 'IDSA-UTI-R3',
      statement: 'Fluoroquinolones should NOT be used for uncomplicated cystitis due to collateral damage (resistance selection, C. difficile risk, tendinopathy) when other effective agents are available.',
      normalized_claim: 'Fluoroquinolones should be AVOIDED for uncomplicated cystitis. Reserve for pyelonephritis or complicated UTI. Collateral damage outweighs benefit.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Antimicrobial Stewardship', page_or_location: 'Section 3' },
    },
    {
      rec_id: 'PACK.IDSA.UTI.2011.REC.04',
      display_id: 'IDSA-UTI-R4',
      statement: 'Fosfomycin 3g single dose is an acceptable alternative for uncomplicated cystitis, particularly for multidrug-resistant organisms.',
      normalized_claim: 'Fosfomycin 3g PO single dose for uncomplicated cystitis. Useful for MDR organisms. Slightly less efficacious than standard agents.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      provenance: { section: 'Uncomplicated Cystitis', page_or_location: 'Section 3, Table 1' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.IDSA.UTI.2011.DC.01',
      display_id: 'IDSA-UTI-DC1',
      name: 'Uncomplicated vs Complicated UTI',
      components: [
        'Uncomplicated: cystitis or pyelonephritis in a non-pregnant, premenopausal woman with normal urinary tract anatomy',
        'Complicated: UTI in men, pregnant women, patients with structural/functional urinary tract abnormalities, indwelling catheters, immunosuppression, or renal transplant',
        'CAUTI: Symptomatic UTI in patient with indwelling catheter or within 48h of catheter removal',
      ],
      interpretation: 'Classification determines antibiotic selection, duration, and need for imaging. Complicated UTIs require broader coverage and longer courses.',
      normalized_claim: 'Uncomplicated UTI: cystitis/pyelo in non-pregnant premenopausal woman with normal anatomy. Complicated: any UTI with structural abnormality, catheter, pregnancy, male sex, or immunosuppression.',
      provenance: { section: 'Classification', page_or_location: 'Section 1' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.IDSA.UTI.2011.T.01',
      display_id: 'IDSA-UTI-T1',
      parameter: 'Colony count for UTI diagnosis',
      value: '100000',
      unit: 'CFU/mL',
      clinical_meaning: 'Traditional threshold for significant bacteriuria. However, >=10^2 CFU/mL of a uropathogen in a symptomatic woman with pyuria is sufficient for cystitis diagnosis.',
      normalized_claim: 'Significant bacteriuria: >=10^5 CFU/mL traditional; >=10^2 CFU/mL sufficient in symptomatic women with pyuria for cystitis.',
      direction: 'above',
      provenance: { section: 'Diagnosis', page_or_location: 'Section 2' },
    },
    {
      threshold_id: 'PACK.IDSA.UTI.2011.T.02',
      display_id: 'IDSA-UTI-T2',
      parameter: 'Local E. coli TMP-SMX resistance rate',
      value: '20',
      unit: '%',
      clinical_meaning: 'TMP-SMX should not be used empirically for cystitis when local E. coli resistance exceeds 20%. Check institutional antibiogram.',
      normalized_claim: 'Do not use empiric TMP-SMX for cystitis if local E. coli resistance rate >20%.',
      direction: 'above',
      provenance: { section: 'Antimicrobial Selection', page_or_location: 'Section 3' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.IDSA.UTI.2011.TX.01',
      display_id: 'IDSA-UTI-TX1',
      action: 'Uncomplicated cystitis first-line therapy',
      normalized_claim: 'Uncomplicated cystitis: nitrofurantoin 100mg BID x 5 days (first-line) OR TMP-SMX DS BID x 3 days (if resistance <20%) OR fosfomycin 3g single dose.',
      timing: 'At diagnosis; urine culture not required for typical uncomplicated cystitis',
      condition: 'Uncomplicated cystitis in non-pregnant premenopausal woman',
      drug_details: { drug: 'Nitrofurantoin', dose: '100mg BID', route: 'PO', duration: '5 days' },
      contraindications: ['CrCl <30 mL/min', 'Suspected pyelonephritis (inadequate tissue levels)'],
      provenance: { section: 'Uncomplicated Cystitis', page_or_location: 'Section 3' },
    },
    {
      step_id: 'PACK.IDSA.UTI.2011.TX.02',
      display_id: 'IDSA-UTI-TX2',
      action: 'Outpatient pyelonephritis treatment',
      normalized_claim: 'Outpatient pyelonephritis: ciprofloxacin 500mg BID x 7 days OR TMP-SMX DS BID x 14 days (if susceptible, with initial IV ceftriaxone dose). Urine culture required.',
      timing: 'After urine culture obtained',
      condition: 'Acute uncomplicated pyelonephritis, able to tolerate oral meds, no sepsis',
      drug_details: { drug: 'Ciprofloxacin', dose: '500mg BID', route: 'PO', duration: '7 days' },
      escalation: 'Hospitalization with IV antibiotics if unable to tolerate PO, sepsis, or complicated',
      provenance: { section: 'Pyelonephritis', page_or_location: 'Section 4' },
    },
    {
      step_id: 'PACK.IDSA.UTI.2011.TX.03',
      display_id: 'IDSA-UTI-TX3',
      action: 'Inpatient complicated pyelonephritis',
      normalized_claim: 'Complicated pyelonephritis/urosepsis: IV ceftriaxone 1g daily, IV fluoroquinolone, or IV piperacillin-tazobactam. Step down to PO based on culture sensitivities.',
      timing: 'On admission',
      condition: 'Complicated pyelonephritis, sepsis, unable to tolerate oral therapy, or structural abnormality',
      drug_details: { drug: 'Ceftriaxone', dose: '1g daily', route: 'IV' },
      escalation: 'Add aminoglycoside or switch to carbapenem for ESBL-producing organisms',
      provenance: { section: 'Complicated UTI', page_or_location: 'Section 5' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.IDSA.UTI.2011.RF.01',
      display_id: 'IDSA-UTI-RF1',
      finding: 'Pyelonephritis with hemodynamic instability (hypotension, tachycardia), high fever, rigors, or flank pain with inability to tolerate oral medications',
      implication: 'Urosepsis requiring hospitalization. Risk of septic shock, renal abscess, or emphysematous pyelonephritis (especially in diabetics).',
      action: 'Hospital admission. IV fluid resuscitation. Blood cultures x2. IV antibiotics (ceftriaxone or fluoroquinolone). CT abdomen/pelvis to rule out obstruction or abscess.',
      urgency: 'immediate',
      provenance: { section: 'Severe Pyelonephritis', page_or_location: 'Section 4' },
    },
    {
      flag_id: 'PACK.IDSA.UTI.2011.RF.02',
      display_id: 'IDSA-UTI-RF2',
      finding: 'UTI symptoms with obstructive uropathy (hydronephrosis on imaging, ureteral stone, elevated creatinine)',
      implication: 'Infected obstructed system is a urologic emergency. Antibiotics alone will not resolve infection without drainage.',
      action: 'Emergent urology consultation for ureteral stent or percutaneous nephrostomy. IV antibiotics. Do NOT delay decompression.',
      urgency: 'immediate',
      provenance: { section: 'Complicated UTI', page_or_location: 'Section 5' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.IDSA.UTI.2011.SEV.01',
      display_id: 'IDSA-UTI-SEV1',
      level: 'Uncomplicated cystitis',
      criteria: [
        'Dysuria, frequency, urgency',
        'Non-pregnant, premenopausal woman',
        'No fever, flank pain, or systemic symptoms',
        'Normal urinary tract anatomy',
      ],
      management_implications:
        'Outpatient treatment. No urine culture needed for typical presentation. Nitrofurantoin 5 days first-line. Avoid fluoroquinolones. Empiric treatment without imaging.',
      provenance: { section: 'Classification', page_or_location: 'Section 1' },
    },
    {
      severity_id: 'PACK.IDSA.UTI.2011.SEV.02',
      display_id: 'IDSA-UTI-SEV2',
      level: 'Acute pyelonephritis (uncomplicated)',
      criteria: [
        'Fever (>38C), flank pain, CVA tenderness',
        'With or without lower urinary tract symptoms',
        'Non-pregnant, premenopausal woman',
        'Pyuria and bacteriuria on urinalysis',
      ],
      management_implications:
        'Urine culture mandatory. Outpatient if tolerating PO and hemodynamically stable: fluoroquinolone 7 days or TMP-SMX 14 days. Consider initial IM/IV ceftriaxone dose. Hospitalize if sepsis, vomiting, or unable to take PO.',
      provenance: { section: 'Pyelonephritis', page_or_location: 'Section 4' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for UTI. Covers uncomplicated cystitis (nitrofurantoin first-line, avoid fluoroquinolones), pyelonephritis outpatient vs inpatient, complicated UTI, and CAUTI.',

  all_item_ids: [
    'PACK.IDSA.UTI.2011.REC.01', 'PACK.IDSA.UTI.2011.REC.02', 'PACK.IDSA.UTI.2011.REC.03',
    'PACK.IDSA.UTI.2011.REC.04',
    'PACK.IDSA.UTI.2011.DC.01',
    'PACK.IDSA.UTI.2011.T.01', 'PACK.IDSA.UTI.2011.T.02',
    'PACK.IDSA.UTI.2011.TX.01', 'PACK.IDSA.UTI.2011.TX.02', 'PACK.IDSA.UTI.2011.TX.03',
    'PACK.IDSA.UTI.2011.RF.01', 'PACK.IDSA.UTI.2011.RF.02',
    'PACK.IDSA.UTI.2011.SEV.01', 'PACK.IDSA.UTI.2011.SEV.02',
  ],
  all_display_ids: [
    'IDSA-UTI-R1', 'IDSA-UTI-R2', 'IDSA-UTI-R3', 'IDSA-UTI-R4',
    'IDSA-UTI-DC1',
    'IDSA-UTI-T1', 'IDSA-UTI-T2',
    'IDSA-UTI-TX1', 'IDSA-UTI-TX2', 'IDSA-UTI-TX3',
    'IDSA-UTI-RF1', 'IDSA-UTI-RF2',
    'IDSA-UTI-SEV1', 'IDSA-UTI-SEV2',
  ],
};
