// ─── DRAFT Source Pack: Encephalitis ───
// Generated by DI/IC Accelerator on 2026-04-17
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (34 total):
//   DI.030.585, DI.030.586, DI.030.587, DI.032.370, DI.041.041, DI.041.042, DI.041.043, DI.045.002, DI.045.003, DI.045.004, DI.045.005, DI.045.006, DI.047.010, DI.047.011, DI.047.023, DI.047.028, DI.100.036, DI.100.078, DI.100.079, DI.125.001 ... and 14 more
//
// Evidence classification summary:
//   Recommendations: 20 items → pack
//   Diagnostic criteria: 2 items → pack
//   Treatment steps: 5 items → pack
//   Thresholds: 7 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_IDSA_ENC_2023: SourcePack = {
  "source_pack_id": "PACK.IDSA.ENC.2023",
  "source_name": "IDSA Guidelines for Encephalitis Management",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2023,
  "guideline_body": "Infectious Diseases Society of America (IDSA)",
  "topic_tags": [
    "encephalitis",
    "HSV encephalitis",
    "meningoencephalitis",
    "CNS infections",
    "neurology",
    "infectious disease"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "treatment",
    "monitoring",
    "emergency_management"
  ],
  "excluded_decision_scopes": [
    "prevention",
    "screening"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.IDSA.ENC.2023.REC.01",
      "display_id": "IDSA-ENC-R1",
      "statement": "HSV encephalitis characteristically affects the temporal lobes",
      "normalized_claim": "HSV encephalitis has predilection for temporal lobe involvement",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "HSV encephalitis diagnosis",
      "population": "All patients with suspected HSV encephalitis",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Brain area affected by HSV encephalitis: Temporal lobes"
      }
    },
    {
      "rec_id": "PACK.IDSA.ENC.2023.REC.02",
      "display_id": "IDSA-ENC-R2",
      "statement": "CSF analysis in HSV encephalitis typically shows RBCs in the hundreds",
      "normalized_claim": "HSV encephalitis CSF characteristically contains RBCs",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Lumbar puncture findings",
      "population": "Patients with HSV encephalitis",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "CSF findings in HSV encephalitis: RBCs"
      }
    },
    {
      "rec_id": "PACK.IDSA.ENC.2023.REC.03",
      "display_id": "IDSA-ENC-R3",
      "statement": "Encephalitis presents with more neurologic deficits and may not have nuchal rigidity",
      "normalized_claim": "Encephalitis differs from meningitis by having more focal neurologic deficits and less meningeal signs",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Clinical differentiation",
      "population": "Patients with CNS infections",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Encephalitis → more neuro deficits, may not have nuchal rigidity"
      }
    },
    {
      "rec_id": "PACK.IDSA.ENC.2023.REC.04",
      "display_id": "IDSA-ENC-R4",
      "statement": "Young adults with altered mental status and behavioral changes over days with CSF RBCs should be evaluated for HSV encephalitis",
      "normalized_claim": "HSV encephalitis should be suspected in young adults with subacute behavioral changes and hemorrhagic CSF",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Clinical presentation",
      "population": "Young adults with altered mental status",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Young adult, AMS for last 3d, close acquaintances think they're weird recently"
      }
    },
    {
      "rec_id": "PACK.IDSA.ENC.2023.REC.05",
      "display_id": "IDSA-ENC-R5",
      "statement": "Start IV acyclovir as soon as HSV encephalitis is suspected",
      "normalized_claim": "Empiric acyclovir should be initiated immediately when HSV encephalitis is suspected",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Emergency treatment",
      "population": "Patients with suspected HSV encephalitis",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Give acyclovir as SOON as suspected"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.IDSA.ENC.2023.DC.01",
      "display_id": "IDSA-ENC-DC1",
      "name": "HSV Encephalitis Diagnostic Criteria",
      "components": [
        "HSV PCR of CSF",
        "Temporal lobe involvement on imaging"
      ],
      "interpretation": "Definitive diagnosis requires HSV PCR confirmation",
      "normalized_claim": "HSV encephalitis is diagnosed by HSV PCR of CSF with characteristic temporal lobe involvement",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Dx: HSV PCR of CSF"
      }
    },
    {
      "criterion_id": "PACK.IDSA.ENC.2023.DC.02",
      "display_id": "IDSA-ENC-DC2",
      "name": "NMDAR Encephalitis Diagnostic Criteria",
      "components": [
        "Psychiatric symptoms (anxiety, psychosis, insomnia)",
        "Autonomic instability",
        "Cognitive impairment",
        "Movement disorders (rigidity, dystonia)",
        "Focal seizures",
        "CSF antibodies to GluN1 subunit of NMDAR"
      ],
      "interpretation": "Autoimmune encephalitis with median onset age 21, >50% have ovarian teratoma",
      "normalized_claim": "NMDAR encephalitis is diagnosed by clinical syndrome plus CSF NMDAR antibodies",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Dx: CSF antibodies to GluN1 subunit of NMDAR"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.IDSA.ENC.2023.T.01",
      "display_id": "IDSA-ENC-T1",
      "parameter": "CSF RBC count in HSV encephalitis",
      "value": "100-1000",
      "unit": "cells/μL",
      "clinical_meaning": "Characteristic finding in HSV encephalitis, distinguish from SAH",
      "normalized_claim": "HSV encephalitis typically has CSF RBCs in hundreds but less than 1000",
      "direction": "range",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "RBCs in hundreds but < 1000"
      }
    },
    {
      "threshold_id": "PACK.IDSA.ENC.2023.T.02",
      "display_id": "IDSA-ENC-T2",
      "parameter": "CSF RBC count suggesting SAH",
      "value": "4000-5000",
      "unit": "cells/μL",
      "clinical_meaning": "Consider subarachnoid hemorrhage rather than HSV encephalitis",
      "normalized_claim": "CSF RBCs >4000 suggest SAH rather than HSV encephalitis",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If 4000-5000 RBCs → think SAH instead"
      }
    },
    {
      "threshold_id": "PACK.IDSA.ENC.2023.T.03",
      "display_id": "IDSA-ENC-T3",
      "parameter": "Treatment threshold CSF RBC",
      "value": "500",
      "unit": "cells/μL",
      "clinical_meaning": "Threshold for empiric acyclovir in seizure patients",
      "normalized_claim": "Seizure with 500 CSF RBCs warrants empiric acyclovir for HSV encephalitis",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "If seizure w/ deja vu aura and 500 RBCs in CSF"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.IDSA.ENC.2023.TX.01",
      "display_id": "IDSA-ENC-TX1",
      "action": "Initiate IV acyclovir for HSV encephalitis",
      "normalized_claim": "IV acyclovir is first-line treatment for HSV encephalitis",
      "timing": "Immediately upon suspicion",
      "condition": "Suspected or confirmed HSV encephalitis",
      "drug_details": {
        "drug": "Acyclovir",
        "route": "IV"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Tx herpes encephalitis: Acyclovir"
      }
    },
    {
      "step_id": "PACK.IDSA.ENC.2023.TX.02",
      "display_id": "IDSA-ENC-TX2",
      "action": "Alternative therapy with IV foscarnet",
      "normalized_claim": "Foscarnet is alternative therapy for HSV encephalitis",
      "condition": "HSV encephalitis when acyclovir contraindicated",
      "drug_details": {
        "drug": "Foscarnet",
        "route": "IV"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Tx: IV Acyclovir or foscarnet"
      }
    },
    {
      "step_id": "PACK.IDSA.ENC.2023.TX.03",
      "display_id": "IDSA-ENC-TX3",
      "action": "Monitor for crystal nephropathy during acyclovir therapy",
      "normalized_claim": "Crystal nephropathy is an adverse effect of acyclovir requiring monitoring",
      "condition": "Patients receiving IV acyclovir",
      "drug_details": {
        "drug": "Acyclovir"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Acyclovir (AE: crystal nephropathy)"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.IDSA.ENC.2023.RF.01",
      "display_id": "IDSA-ENC-RF1",
      "finding": "Signs of increased intracranial pressure with uncal herniation",
      "implication": "Risk of transtentorial herniation with CN3 palsy and contralateral weakness",
      "action": "Emergency neurosurgical consultation and ICP management",
      "urgency": "immediate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "increased ICP → uncal herniation → CN3 → down and out eye w/ blown pupil"
      }
    },
    {
      "flag_id": "PACK.IDSA.ENC.2023.RF.02",
      "display_id": "IDSA-ENC-RF2",
      "finding": "Encephalitis in neonate with CSF RBCs or temporal enhancement",
      "implication": "High risk of HSV encephalitis in vulnerable population",
      "action": "Immediate IV acyclovir and HSV PCR",
      "urgency": "immediate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Neonate with encephalitis and LP shows RBC or temporal enhancement"
      }
    },
    {
      "flag_id": "PACK.IDSA.ENC.2023.RF.03",
      "display_id": "IDSA-ENC-RF3",
      "finding": "Animal bite with encephalitis and hydrophobia",
      "implication": "Rabies encephalitis - universally fatal once symptomatic",
      "action": "Supportive care, contact public health authorities",
      "urgency": "immediate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Pt bitten by an animal and has encephalitis and hydrophobia -> Rabies"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.IDSA.ENC.2023.SEV.01",
      "display_id": "IDSA-ENC-SEV1",
      "level": "Complicated HSV Encephalitis",
      "criteria": [
        "Increased intracranial pressure",
        "Uncal herniation signs",
        "CN3 palsy with blown pupil",
        "Contralateral hemiparesis"
      ],
      "management_implications": "Requires emergency neurosurgical intervention and intensive care monitoring",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "quote_snippet": "C/b increased ICP → uncal herniation"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-12-19",
  "normalizer_version": 1,
  "normalization_notes": "Converted board review evidence into structured guidelines format. Key areas needing verification: 1) Specific dosing protocols for acyclovir, 2) Exact CSF thresholds and their clinical significance, 3) Complete diagnostic workup algorithms, 4) Duration of treatment protocols. Evidence primarily focused on HSV encephalitis with limited coverage of other etiologies. Requires validation against actual IDSA encephalitis guidelines.",
  "all_item_ids": [
    "PACK.IDSA.ENC.2023.REC.01",
    "PACK.IDSA.ENC.2023.REC.02",
    "PACK.IDSA.ENC.2023.REC.03",
    "PACK.IDSA.ENC.2023.REC.04",
    "PACK.IDSA.ENC.2023.REC.05",
    "PACK.IDSA.ENC.2023.DC.01",
    "PACK.IDSA.ENC.2023.DC.02",
    "PACK.IDSA.ENC.2023.T.01",
    "PACK.IDSA.ENC.2023.T.02",
    "PACK.IDSA.ENC.2023.T.03",
    "PACK.IDSA.ENC.2023.TX.01",
    "PACK.IDSA.ENC.2023.TX.02",
    "PACK.IDSA.ENC.2023.TX.03",
    "PACK.IDSA.ENC.2023.RF.01",
    "PACK.IDSA.ENC.2023.RF.02",
    "PACK.IDSA.ENC.2023.RF.03",
    "PACK.IDSA.ENC.2023.SEV.01"
  ],
  "all_display_ids": [
    "IDSA-ENC-R1",
    "IDSA-ENC-R2",
    "IDSA-ENC-R3",
    "IDSA-ENC-R4",
    "IDSA-ENC-R5",
    "IDSA-ENC-DC1",
    "IDSA-ENC-DC2",
    "IDSA-ENC-T1",
    "IDSA-ENC-T2",
    "IDSA-ENC-T3",
    "IDSA-ENC-TX1",
    "IDSA-ENC-TX2",
    "IDSA-ENC-TX3",
    "IDSA-ENC-RF1",
    "IDSA-ENC-RF2",
    "IDSA-ENC-RF3",
    "IDSA-ENC-SEV1"
  ]
};
