import type { SourcePack } from './types';

export const PACK_IDSA_MENING_2004: SourcePack = {
  source_pack_id: 'PACK.IDSA.MENING.2004',
  source_name: 'IDSA Practice Guidelines for the Management of Bacterial Meningitis (2004)',
  source_registry_id: 'REG.IDSA.MENING',
  canonical_url: 'https://doi.org/10.1086/425368',
  publication_year: 2004,
  guideline_body: 'IDSA',

  topic_tags: ['Bacterial Meningitis', 'CNS Infection', 'LP Interpretation', 'Infectious Disease', 'Neurology'],
  allowed_decision_scopes: [
    'empiric antibiotic selection by age group',
    'dexamethasone adjunctive therapy',
    'LP interpretation and timing',
    'indications for CT before LP',
    'CSF Gram stain interpretation',
    'duration of antibiotic therapy',
    'chemoprophylaxis for close contacts',
  ],
  excluded_decision_scopes: [
    'viral meningitis management',
    'fungal meningitis management',
    'tuberculous meningitis management',
    'brain abscess management',
    'ventriculitis/shunt infection management',
    'neonatal sepsis workup beyond meningitis',
  ],

  recommendations: [
    {
      rec_id: 'PACK.IDSA.MENING.2004.REC.01',
      display_id: 'IDSA-MENING-R1',
      statement: 'Empiric antimicrobial therapy should be initiated immediately when bacterial meningitis is suspected. If lumbar puncture will be delayed (e.g., awaiting CT), blood cultures should be obtained and empiric antibiotics started before imaging.',
      normalized_claim: 'Do not delay empiric antibiotics for LP or CT. Start antibiotics immediately after blood cultures if LP will be delayed.',
      strength: 'strong',
      evidence_quality: 'moderate',
      context: 'Delay in antibiotic administration is associated with increased mortality',
      provenance: { section: 'Initial Management', page_or_location: 'Section IV' },
    },
    {
      rec_id: 'PACK.IDSA.MENING.2004.REC.02',
      display_id: 'IDSA-MENING-R2',
      statement: 'Adjunctive dexamethasone (0.15 mg/kg IV q6h for 4 days) should be administered before or with the first dose of antibiotics in adults with suspected pneumococcal meningitis.',
      normalized_claim: 'Dexamethasone 0.15 mg/kg IV q6h x4 days, given before or concurrent with first antibiotic dose, reduces mortality in pneumococcal meningitis.',
      strength: 'strong',
      evidence_quality: 'high',
      context: 'de Gans trial demonstrated mortality benefit in pneumococcal meningitis; must be given before or with first ABx dose to be effective',
      provenance: { section: 'Adjunctive Dexamethasone', page_or_location: 'Section V' },
    },
    {
      rec_id: 'PACK.IDSA.MENING.2004.REC.03',
      display_id: 'IDSA-MENING-R3',
      statement: 'Blood cultures should be obtained in all patients before initiation of antimicrobial therapy.',
      normalized_claim: 'Blood cultures must be drawn before antibiotics in suspected bacterial meningitis; positive in 50-80% of cases.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Diagnostic Approach', page_or_location: 'Section III' },
    },
    {
      rec_id: 'PACK.IDSA.MENING.2004.REC.04',
      display_id: 'IDSA-MENING-R4',
      statement: 'For adults, empiric therapy should include vancomycin plus a third-generation cephalosporin (ceftriaxone or cefotaxime) to cover S. pneumoniae (including penicillin-resistant strains) and N. meningitidis.',
      normalized_claim: 'Adult empiric meningitis therapy: vancomycin + ceftriaxone (or cefotaxime) to cover resistant pneumococcus and meningococcus.',
      strength: 'strong',
      evidence_quality: 'moderate',
      population: 'Adults 18-50 years',
      provenance: { section: 'Empiric Antimicrobial Therapy', page_or_location: 'Table 4' },
    },
    {
      rec_id: 'PACK.IDSA.MENING.2004.REC.05',
      display_id: 'IDSA-MENING-R5',
      statement: 'CT scan before LP is indicated in patients with new-onset seizures, immunocompromised state, papilledema, focal neurological deficits, or moderate-to-severe impairment of consciousness.',
      normalized_claim: 'CT before LP required if: immunocompromised, seizures, papilledema, focal neuro deficits, or altered consciousness. Do not delay antibiotics for imaging.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Indications for CT Before LP', page_or_location: 'Section III' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.IDSA.MENING.2004.DC.01',
      display_id: 'IDSA-MENING-DC1',
      name: 'CSF Findings in Bacterial Meningitis',
      components: [
        'Opening pressure >20 cmH2O (elevated in >90% of cases)',
        'WBC count >1,000/microL (range 100-10,000; neutrophil predominance >80%)',
        'Glucose <40 mg/dL or CSF:serum glucose ratio <0.4',
        'Protein >45 mg/dL (typically 100-500 mg/dL)',
        'Gram stain positive in 60-90% of untreated cases',
        'CSF culture positive in 70-85% of untreated cases',
      ],
      threshold: 'WBC >1000 with PMN predominance + low glucose + high protein',
      interpretation: 'Classic bacterial meningitis CSF profile. Partially treated meningitis may show atypical findings. CSF lactate >35 mg/dL supports bacterial etiology.',
      normalized_claim: 'Bacterial meningitis CSF: WBC >1000 (PMN predominant), glucose <40, protein >45, elevated opening pressure, positive Gram stain in 60-90%.',
      provenance: { section: 'CSF Analysis', page_or_location: 'Table 1' },
    },
    {
      criterion_id: 'PACK.IDSA.MENING.2004.DC.02',
      display_id: 'IDSA-MENING-DC2',
      name: 'Gram Stain Organism Patterns',
      components: [
        'Gram-positive diplococci: Streptococcus pneumoniae',
        'Gram-negative diplococci: Neisseria meningitidis',
        'Gram-positive rods: Listeria monocytogenes',
        'Gram-negative rods: Escherichia coli, Klebsiella (neonates), Haemophilus influenzae',
        'Gram-positive cocci in clusters: Staphylococcus (post-neurosurgical)',
      ],
      interpretation: 'Gram stain morphology directs targeted therapy. Sensitivity depends on organism concentration; negative Gram stain does not exclude bacterial meningitis.',
      normalized_claim: 'CSF Gram stain identifies organism in 60-90% of untreated bacterial meningitis and directs targeted antibiotic therapy.',
      provenance: { section: 'CSF Gram Stain', page_or_location: 'Section III' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.IDSA.MENING.2004.T.01',
      display_id: 'IDSA-MENING-T1',
      parameter: 'CSF glucose',
      value: '40',
      unit: 'mg/dL',
      clinical_meaning: 'CSF glucose <40 mg/dL is characteristic of bacterial meningitis. Normal CSF glucose is 40-70 mg/dL (approximately 60% of serum glucose).',
      normalized_claim: 'CSF glucose <40 mg/dL suggests bacterial meningitis; always compare to serum glucose (ratio <0.4 is abnormal).',
      direction: 'below',
      provenance: { section: 'CSF Analysis', page_or_location: 'Table 1' },
    },
    {
      threshold_id: 'PACK.IDSA.MENING.2004.T.02',
      display_id: 'IDSA-MENING-T2',
      parameter: 'CSF:serum glucose ratio',
      value: '0.4',
      clinical_meaning: 'CSF:serum glucose ratio <0.4 has higher sensitivity than absolute CSF glucose for detecting bacterial meningitis.',
      normalized_claim: 'CSF:serum glucose ratio <0.4 is more sensitive than absolute CSF glucose for diagnosing bacterial meningitis.',
      direction: 'below',
      provenance: { section: 'CSF Analysis', page_or_location: 'Table 1' },
    },
    {
      threshold_id: 'PACK.IDSA.MENING.2004.T.03',
      display_id: 'IDSA-MENING-T3',
      parameter: 'CSF protein',
      value: '45',
      unit: 'mg/dL',
      clinical_meaning: 'CSF protein >45 mg/dL indicates meningeal inflammation. Bacterial meningitis typically produces protein levels of 100-500 mg/dL.',
      normalized_claim: 'CSF protein >45 mg/dL indicates meningeal inflammation; bacterial meningitis typically causes protein 100-500 mg/dL.',
      direction: 'above',
      provenance: { section: 'CSF Analysis', page_or_location: 'Table 1' },
    },
    {
      threshold_id: 'PACK.IDSA.MENING.2004.T.04',
      display_id: 'IDSA-MENING-T4',
      parameter: 'CSF opening pressure',
      value: '20',
      unit: 'cmH2O',
      clinical_meaning: 'Opening pressure >20 cmH2O is elevated. Bacterial meningitis typically produces pressures of 20-50 cmH2O. Markedly elevated pressure (>40) raises concern for cerebral edema or complications.',
      normalized_claim: 'CSF opening pressure >20 cmH2O is elevated; bacterial meningitis typically 20-50 cmH2O. Pressures >40 suggest complications.',
      direction: 'above',
      provenance: { section: 'CSF Analysis', page_or_location: 'Table 1' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.IDSA.MENING.2004.TX.01',
      display_id: 'IDSA-MENING-TX1',
      action: 'Neonatal empiric therapy: ampicillin + cefotaxime (or ampicillin + gentamicin)',
      normalized_claim: 'Neonates (0-28 days): ampicillin (covers Listeria, GBS) + cefotaxime (covers E. coli, gram-negatives). Cefotaxime preferred over ceftriaxone in neonates due to bilirubin displacement risk.',
      timing: 'Immediately upon clinical suspicion',
      condition: 'Neonate (0-28 days)',
      drug_details: { drug: 'Ampicillin + cefotaxime', dose: 'Ampicillin 200-300 mg/kg/day divided q6-8h; cefotaxime 200 mg/kg/day divided q6-8h', route: 'IV' },
      contraindications: ['Ceftriaxone contraindicated in neonates (bilirubin displacement)'],
      provenance: { section: 'Empiric Therapy by Age', page_or_location: 'Table 4' },
    },
    {
      step_id: 'PACK.IDSA.MENING.2004.TX.02',
      display_id: 'IDSA-MENING-TX2',
      action: 'Pediatric empiric therapy (1 month - 18 years): vancomycin + ceftriaxone (or cefotaxime)',
      normalized_claim: 'Children 1 month-18 years: vancomycin + ceftriaxone covers S. pneumoniae (including resistant), N. meningitidis, and H. influenzae.',
      timing: 'Immediately upon clinical suspicion',
      condition: 'Child (1 month to 18 years)',
      drug_details: { drug: 'Vancomycin + ceftriaxone', dose: 'Vancomycin 60 mg/kg/day divided q6h; ceftriaxone 100 mg/kg/day divided q12-24h', route: 'IV' },
      provenance: { section: 'Empiric Therapy by Age', page_or_location: 'Table 4' },
    },
    {
      step_id: 'PACK.IDSA.MENING.2004.TX.03',
      display_id: 'IDSA-MENING-TX3',
      action: 'Adult empiric therapy (18-50 years): vancomycin + ceftriaxone',
      normalized_claim: 'Adults 18-50: vancomycin (15-20 mg/kg q8-12h) + ceftriaxone (2g q12h) covers pneumococcus and meningococcus.',
      timing: 'Immediately upon clinical suspicion',
      condition: 'Adult (18-50 years)',
      drug_details: { drug: 'Vancomycin + ceftriaxone', dose: 'Vancomycin 15-20 mg/kg q8-12h; ceftriaxone 2g q12h', route: 'IV' },
      provenance: { section: 'Empiric Therapy by Age', page_or_location: 'Table 4' },
    },
    {
      step_id: 'PACK.IDSA.MENING.2004.TX.04',
      display_id: 'IDSA-MENING-TX4',
      action: 'Elderly/immunocompromised empiric therapy (>50 years or immunocompromised): vancomycin + ceftriaxone + ampicillin',
      normalized_claim: 'Age >50 or immunocompromised: add ampicillin to vancomycin + ceftriaxone for Listeria monocytogenes coverage.',
      timing: 'Immediately upon clinical suspicion',
      condition: 'Elderly (>50 years) or immunocompromised',
      drug_details: { drug: 'Vancomycin + ceftriaxone + ampicillin', dose: 'Vancomycin 15-20 mg/kg q8-12h; ceftriaxone 2g q12h; ampicillin 2g q4h', route: 'IV' },
      escalation: 'Meropenem may substitute for ceftriaxone + ampicillin if beta-lactam allergy concerns are managed',
      provenance: { section: 'Empiric Therapy by Age', page_or_location: 'Table 4' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.IDSA.MENING.2004.RF.01',
      display_id: 'IDSA-MENING-RF1',
      finding: 'Altered mental status (GCS <14) or moderate-to-severe impairment of consciousness',
      implication: 'Associated with increased mortality. Requires CT before LP to rule out mass lesion or elevated ICP. Do not delay antibiotics for imaging.',
      action: 'Obtain blood cultures, start empiric antibiotics + dexamethasone immediately, then CT head, then LP if safe.',
      urgency: 'immediate',
      provenance: { section: 'Indications for CT Before LP', page_or_location: 'Section III' },
    },
    {
      flag_id: 'PACK.IDSA.MENING.2004.RF.02',
      display_id: 'IDSA-MENING-RF2',
      finding: 'New-onset seizures in the setting of suspected meningitis',
      implication: 'Indicates cortical irritation or complications (abscess, empyema, cerebral infarction). CT before LP is mandatory.',
      action: 'Seizure management (benzodiazepines), CT head before LP, empiric antibiotics immediately.',
      urgency: 'immediate',
      provenance: { section: 'Complications', page_or_location: 'Section VII' },
    },
    {
      flag_id: 'PACK.IDSA.MENING.2004.RF.03',
      display_id: 'IDSA-MENING-RF3',
      finding: 'Focal neurological deficits or papilledema in suspected meningitis',
      implication: 'Suggests mass effect (abscess, subdural empyema) or elevated ICP. LP may cause herniation if performed without prior imaging.',
      action: 'CT head before LP is mandatory. Start empiric antibiotics before imaging. Neurosurgical consultation if mass lesion identified.',
      urgency: 'immediate',
      provenance: { section: 'Indications for CT Before LP', page_or_location: 'Section III' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.IDSA.MENING.2004.SEV.01',
      display_id: 'IDSA-MENING-SEV1',
      level: 'Uncomplicated bacterial meningitis',
      criteria: [
        'Meningeal signs (nuchal rigidity, Kernig sign, Brudzinski sign) present',
        'No focal neurological deficits',
        'No seizures',
        'GCS 14-15 (alert or mildly impaired)',
        'No evidence of raised ICP or mass effect',
      ],
      management_implications:
        'LP can proceed without prior CT. Empiric antibiotics + dexamethasone (if pneumococcal suspected). Monitor closely for deterioration. Expected antibiotic duration: 7-21 days depending on organism (7 days for N. meningitidis, 10-14 for S. pneumoniae, 21 for Listeria, gram-negatives).',
      provenance: { section: 'Clinical Presentation', page_or_location: 'Section II' },
    },
    {
      severity_id: 'PACK.IDSA.MENING.2004.SEV.02',
      display_id: 'IDSA-MENING-SEV2',
      level: 'Complicated bacterial meningitis',
      criteria: [
        'Focal neurological deficits present',
        'Seizures (new onset)',
        'GCS <14 or rapidly declining mental status',
        'Evidence of complications: cerebral abscess, subdural empyema, hydrocephalus, cerebral infarction',
        'Markedly elevated ICP (opening pressure >40 cmH2O)',
      ],
      management_implications:
        'CT before LP mandatory. ICU admission. Neurosurgical consultation for abscess/empyema drainage or VP shunt for hydrocephalus. ICP monitoring and management (head of bed elevation, osmotic therapy). Prolonged antibiotic course. Repeat imaging to assess treatment response. Mortality significantly increased (20-30%).',
      provenance: { section: 'Complications', page_or_location: 'Section VII' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for bacterial meningitis. IDSA 2004 guidelines remain the standard reference. Covers empiric therapy by age, CSF interpretation, dexamethasone timing, and indications for CT before LP.',

  all_item_ids: [
    'PACK.IDSA.MENING.2004.REC.01', 'PACK.IDSA.MENING.2004.REC.02', 'PACK.IDSA.MENING.2004.REC.03',
    'PACK.IDSA.MENING.2004.REC.04', 'PACK.IDSA.MENING.2004.REC.05',
    'PACK.IDSA.MENING.2004.DC.01', 'PACK.IDSA.MENING.2004.DC.02',
    'PACK.IDSA.MENING.2004.T.01', 'PACK.IDSA.MENING.2004.T.02',
    'PACK.IDSA.MENING.2004.T.03', 'PACK.IDSA.MENING.2004.T.04',
    'PACK.IDSA.MENING.2004.TX.01', 'PACK.IDSA.MENING.2004.TX.02',
    'PACK.IDSA.MENING.2004.TX.03', 'PACK.IDSA.MENING.2004.TX.04',
    'PACK.IDSA.MENING.2004.RF.01', 'PACK.IDSA.MENING.2004.RF.02', 'PACK.IDSA.MENING.2004.RF.03',
    'PACK.IDSA.MENING.2004.SEV.01', 'PACK.IDSA.MENING.2004.SEV.02',
  ],
  all_display_ids: [
    'IDSA-MENING-R1', 'IDSA-MENING-R2', 'IDSA-MENING-R3', 'IDSA-MENING-R4', 'IDSA-MENING-R5',
    'IDSA-MENING-DC1', 'IDSA-MENING-DC2',
    'IDSA-MENING-T1', 'IDSA-MENING-T2', 'IDSA-MENING-T3', 'IDSA-MENING-T4',
    'IDSA-MENING-TX1', 'IDSA-MENING-TX2', 'IDSA-MENING-TX3', 'IDSA-MENING-TX4',
    'IDSA-MENING-RF1', 'IDSA-MENING-RF2', 'IDSA-MENING-RF3',
    'IDSA-MENING-SEV1', 'IDSA-MENING-SEV2',
  ],
};
