import type { SourcePack } from './types';

export const PACK_DHHS_HIV_2024: SourcePack = {
  source_pack_id: 'PACK.DHHS.HIV.2024',
  source_name: 'DHHS Guidelines for the Use of Antiretroviral Agents in Adults and Adolescents with HIV',
  canonical_url: 'https://clinicalinfo.hiv.gov/en/guidelines',
  publication_year: 2024,
  guideline_body: 'DHHS/NIH',

  topic_tags: ['HIV', 'AIDS', 'ART', 'Opportunistic Infections', 'PrEP', 'Infectious Disease'],
  allowed_decision_scopes: [
    'ART initiation timing',
    'initial ART regimen selection',
    'OI prophylaxis by CD4 count',
    'PrEP indications and regimens',
    'viral load monitoring',
    'resistance testing indications',
    'IRIS recognition and management',
    'treatment failure evaluation',
    'ART in pregnancy',
  ],
  excluded_decision_scopes: [
    'pediatric HIV management',
    'HIV vaccine development',
    'post-exposure prophylaxis (PEP) details',
    'hepatitis C co-infection treatment specifics',
  ],

  recommendations: [
    {
      rec_id: 'PACK.DHHS.HIV.2024.REC.01',
      display_id: 'DHHS-HIV-R1',
      statement: 'ART is recommended for all people with HIV, regardless of CD4 count, to reduce morbidity and mortality and to prevent HIV transmission.',
      normalized_claim: 'Treat all HIV-positive patients with ART regardless of CD4 count. No threshold required for initiation.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Initiation of ART', page_or_location: 'Section A' },
    },
    {
      rec_id: 'PACK.DHHS.HIV.2024.REC.02',
      display_id: 'DHHS-HIV-R2',
      statement: 'For most treatment-naive patients, an INSTI-based regimen is recommended as initial therapy. Preferred regimens include bictegravir/TAF/FTC (Biktarvy) or dolutegravir + TAF/FTC or TDF/FTC.',
      normalized_claim: 'First-line ART: INSTI-based regimen. Preferred: bictegravir/TAF/FTC (Biktarvy) or dolutegravir-based with TAF/FTC or TDF/FTC.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'What to Start', page_or_location: 'Section B, Table 6' },
    },
    {
      rec_id: 'PACK.DHHS.HIV.2024.REC.03',
      display_id: 'DHHS-HIV-R3',
      statement: 'Resistance testing (genotype) is recommended before initiating ART and at treatment failure to guide regimen selection.',
      normalized_claim: 'HIV genotype resistance testing required before starting ART and at virologic failure.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Drug Resistance Testing', page_or_location: 'Section C' },
    },
    {
      rec_id: 'PACK.DHHS.HIV.2024.REC.04',
      display_id: 'DHHS-HIV-R4',
      statement: 'PrEP is recommended for individuals at substantial risk of HIV acquisition. Oral TDF/FTC daily or injectable cabotegravir every 2 months are approved options.',
      normalized_claim: 'PrEP options: oral TDF/FTC (daily) or injectable cabotegravir (q2mo). Indicated for individuals at substantial HIV risk.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'PrEP', page_or_location: 'PrEP Guideline Section' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.DHHS.HIV.2024.DC.01',
      display_id: 'DHHS-HIV-DC1',
      name: 'Virologic Failure Definition',
      components: [
        'Viral load >200 copies/mL on two consecutive measurements after 6 months of ART',
        'Failure to achieve viral suppression (<200 copies/mL) within 6 months of starting ART',
        'Viral rebound: confirmed detectable viral load after prior suppression',
      ],
      interpretation: 'Virologic failure requires evaluation of adherence, drug interactions, and resistance testing before regimen change.',
      normalized_claim: 'Virologic failure = VL >200 copies/mL on 2 consecutive tests after 6 months ART. Requires adherence assessment and resistance testing before switch.',
      provenance: { section: 'Treatment Failure', page_or_location: 'Section E' },
    },
    {
      criterion_id: 'PACK.DHHS.HIV.2024.DC.02',
      display_id: 'DHHS-HIV-DC2',
      name: 'IRIS (Immune Reconstitution Inflammatory Syndrome)',
      components: [
        'Paradoxical worsening of known OI or unmasking of subclinical OI after ART initiation',
        'Occurs within first 4-8 weeks of ART, especially with low baseline CD4 (<50)',
        'Evidence of immune recovery (rising CD4, falling viral load)',
        'Exclusion of new OI, drug reaction, or treatment failure',
      ],
      interpretation: 'IRIS reflects exuberant immune response to pre-existing pathogen antigens. Most common with TB and Cryptococcus. Continue ART; treat with corticosteroids if severe.',
      normalized_claim: 'IRIS = paradoxical worsening or unmasking of OI within 4-8 weeks of ART start, with rising CD4 and falling VL. Most common with TB/Crypto. Continue ART; steroids if severe.',
      provenance: { section: 'IRIS', page_or_location: 'Section G' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.DHHS.HIV.2024.T.01',
      display_id: 'DHHS-HIV-T1',
      parameter: 'CD4 count for PCP prophylaxis',
      value: '200',
      unit: 'cells/microL',
      clinical_meaning: 'PCP (Pneumocystis jirovecii pneumonia) prophylaxis with TMP-SMX required when CD4 <200 or CD4% <14%.',
      normalized_claim: 'PCP prophylaxis (TMP-SMX) required when CD4 <200 cells/microL or CD4% <14%.',
      direction: 'below',
      provenance: { section: 'OI Prophylaxis', page_or_location: 'OI Guidelines Table 1' },
    },
    {
      threshold_id: 'PACK.DHHS.HIV.2024.T.02',
      display_id: 'DHHS-HIV-T2',
      parameter: 'CD4 count for Toxoplasma prophylaxis',
      value: '100',
      unit: 'cells/microL',
      clinical_meaning: 'Toxoplasma gondii prophylaxis required when CD4 <100 and positive Toxoplasma IgG. TMP-SMX (DS daily) covers both PCP and Toxo.',
      normalized_claim: 'Toxoplasma prophylaxis required when CD4 <100 and Toxo IgG positive. TMP-SMX DS daily covers both PCP and Toxo.',
      direction: 'below',
      provenance: { section: 'OI Prophylaxis', page_or_location: 'OI Guidelines Table 1' },
    },
    {
      threshold_id: 'PACK.DHHS.HIV.2024.T.03',
      display_id: 'DHHS-HIV-T3',
      parameter: 'CD4 count for MAC prophylaxis',
      value: '50',
      unit: 'cells/microL',
      clinical_meaning: 'MAC (Mycobacterium avium complex) prophylaxis with azithromycin required when CD4 <50 and not on suppressive ART.',
      normalized_claim: 'MAC prophylaxis (azithromycin 1200mg weekly) when CD4 <50 and ART not yet suppressive.',
      direction: 'below',
      provenance: { section: 'OI Prophylaxis', page_or_location: 'OI Guidelines Table 1' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.DHHS.HIV.2024.TX.01',
      display_id: 'DHHS-HIV-TX1',
      action: 'Initiate ART with preferred INSTI-based regimen',
      normalized_claim: 'Start bictegravir/TAF/FTC (Biktarvy) as single-tablet regimen OR dolutegravir + TAF/FTC. Check HLA-B*5701 before abacavir use.',
      timing: 'As soon as possible after diagnosis, including same-day start',
      condition: 'Treatment-naive HIV-positive patient',
      drug_details: { drug: 'Bictegravir/emtricitabine/tenofovir alafenamide', dose: '50/200/25mg', route: 'PO daily' },
      provenance: { section: 'What to Start', page_or_location: 'Section B, Table 6' },
    },
    {
      step_id: 'PACK.DHHS.HIV.2024.TX.02',
      display_id: 'DHHS-HIV-TX2',
      action: 'PCP prophylaxis with TMP-SMX',
      normalized_claim: 'TMP-SMX DS daily (or SS daily) for PCP prophylaxis when CD4 <200. Alternatives: dapsone, atovaquone, or aerosolized pentamidine for sulfa allergy.',
      timing: 'When CD4 <200; discontinue when CD4 >200 for >3 months on ART',
      condition: 'CD4 <200 cells/microL or CD4% <14%',
      drug_details: { drug: 'Trimethoprim-sulfamethoxazole', dose: '1 DS tablet daily', route: 'PO' },
      contraindications: ['Sulfonamide allergy (use alternatives)'],
      provenance: { section: 'OI Prophylaxis', page_or_location: 'OI Guidelines Table 1' },
    },
    {
      step_id: 'PACK.DHHS.HIV.2024.TX.03',
      display_id: 'DHHS-HIV-TX3',
      action: 'Viral load monitoring on ART',
      normalized_claim: 'Check viral load at ART initiation, 2-4 weeks after start, then q4-8 weeks until suppressed, then q3-6 months once stable and suppressed.',
      timing: 'Baseline, 2-4 weeks, then every 3-6 months',
      condition: 'Patient on ART',
      provenance: { section: 'Monitoring', page_or_location: 'Section D' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.DHHS.HIV.2024.RF.01',
      display_id: 'DHHS-HIV-RF1',
      finding: 'New fever, lymphadenopathy, or worsening pulmonary infiltrates within 4-8 weeks of ART initiation in patient with low baseline CD4',
      implication: 'IRIS (immune reconstitution inflammatory syndrome). Most common with TB, Cryptococcus, CMV, or PML. Can be life-threatening with CNS involvement.',
      action: 'Continue ART. Treat underlying OI aggressively. Corticosteroids (prednisone 1mg/kg) for severe IRIS (respiratory distress, CNS involvement). Monitor closely.',
      urgency: 'urgent',
      provenance: { section: 'IRIS', page_or_location: 'Section G' },
    },
    {
      flag_id: 'PACK.DHHS.HIV.2024.RF.02',
      display_id: 'DHHS-HIV-RF2',
      finding: 'CD4 <50 with new focal neurologic deficits, ring-enhancing lesions on MRI',
      implication: 'CNS toxoplasmosis vs primary CNS lymphoma. Toxoplasma serology, empiric treatment response distinguishes them.',
      action: 'Start empiric pyrimethamine + sulfadiazine + leucovorin for presumed toxoplasmosis. Brain biopsy if no improvement in 2 weeks. Start ART after 2 weeks of OI treatment.',
      urgency: 'immediate',
      provenance: { section: 'OI Management', page_or_location: 'OI Guidelines, CNS Section' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.DHHS.HIV.2024.SEV.01',
      display_id: 'DHHS-HIV-SEV1',
      level: 'AIDS-defining illness',
      criteria: [
        'CD4 <200 cells/microL or CD4% <14%',
        'OR presence of an AIDS-defining condition (PCP, KS, CMV retinitis, MAC, Cryptococcal meningitis, CNS toxoplasmosis, wasting syndrome, invasive cervical cancer, recurrent pneumonia)',
      ],
      management_implications:
        'Start ART urgently (within 2 weeks for most OIs, delayed 4-6 weeks for Cryptococcal meningitis and TB meningitis to reduce IRIS risk). Initiate OI prophylaxis. Screen for all OIs at baseline.',
      provenance: { section: 'AIDS Classification', page_or_location: 'Section A' },
    },
    {
      severity_id: 'PACK.DHHS.HIV.2024.SEV.02',
      display_id: 'DHHS-HIV-SEV2',
      level: 'Advanced HIV (CD4 <50)',
      criteria: [
        'CD4 <50 cells/microL',
        'Highest risk for disseminated MAC, CMV, CNS lymphoma, progressive multifocal leukoencephalopathy',
        'Often presents with multiple concurrent OIs',
      ],
      management_implications:
        'Start ART urgently. MAC prophylaxis (azithromycin). CMV screening (fundoscopy). PCP + Toxo prophylaxis. Blood cultures for MAC. Serum Cryptococcal antigen screening.',
      provenance: { section: 'OI Prophylaxis', page_or_location: 'OI Guidelines' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for HIV/AIDS. Covers ART initiation, preferred regimens, OI prophylaxis by CD4 thresholds, PrEP, IRIS, and viral load monitoring.',

  all_item_ids: [
    'PACK.DHHS.HIV.2024.REC.01', 'PACK.DHHS.HIV.2024.REC.02', 'PACK.DHHS.HIV.2024.REC.03',
    'PACK.DHHS.HIV.2024.REC.04',
    'PACK.DHHS.HIV.2024.DC.01', 'PACK.DHHS.HIV.2024.DC.02',
    'PACK.DHHS.HIV.2024.T.01', 'PACK.DHHS.HIV.2024.T.02', 'PACK.DHHS.HIV.2024.T.03',
    'PACK.DHHS.HIV.2024.TX.01', 'PACK.DHHS.HIV.2024.TX.02', 'PACK.DHHS.HIV.2024.TX.03',
    'PACK.DHHS.HIV.2024.RF.01', 'PACK.DHHS.HIV.2024.RF.02',
    'PACK.DHHS.HIV.2024.SEV.01', 'PACK.DHHS.HIV.2024.SEV.02',
  ],
  all_display_ids: [
    'DHHS-HIV-R1', 'DHHS-HIV-R2', 'DHHS-HIV-R3', 'DHHS-HIV-R4',
    'DHHS-HIV-DC1', 'DHHS-HIV-DC2',
    'DHHS-HIV-T1', 'DHHS-HIV-T2', 'DHHS-HIV-T3',
    'DHHS-HIV-TX1', 'DHHS-HIV-TX2', 'DHHS-HIV-TX3',
    'DHHS-HIV-RF1', 'DHHS-HIV-RF2',
    'DHHS-HIV-SEV1', 'DHHS-HIV-SEV2',
  ],
};
