// ─── DRAFT Source Pack: Septic Arthritis ───
// Generated by DI/IC Accelerator on 2026-04-17
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (18 total):
//   DI.029.085, DI.029.086, DI.029.087, DI.029.088, DI.100.048, DI.131.009, DI.137.032, DI.245.001, DI.245.002, DI.245.003, DI.245.004, DI.245.005, EH.000.002, EH.007.006, IC.009.011, IC.027.032, IC.060.051, IC.075.042
//
// Evidence classification summary:
//   Recommendations: 5 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 5 items → pack
//   Thresholds: 7 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 1 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_IDSA_SA_2023: SourcePack = {
  "source_pack_id": "PACK.IDSA.SA.2023",
  "source_name": "IDSA Guidelines for Septic Arthritis",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2023,
  "guideline_body": "Infectious Diseases Society of America",
  "topic_tags": [
    "septic_arthritis",
    "joint_infection",
    "orthopedic_infections",
    "arthrocentesis"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "treatment",
    "antibiotic_selection",
    "emergency_management"
  ],
  "excluded_decision_scopes": [
    "surgical_technique",
    "rehabilitation",
    "chronic_management"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.IDSA.SA.2023.REC.01",
      "display_id": "IDSA-SA-R1",
      "statement": "Perform arthrocentesis for suspected septic arthritis",
      "normalized_claim": "Arthrocentesis should be performed when septic arthritis is suspected",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Suspected septic arthritis with joint pain and inflammation",
      "population": "All patients with suspected septic arthritis",
      "provenance": {
        "section": "Diagnostic Approach",
        "quote_snippet": "NBSIM? Arthrocentesis",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "rec_id": "PACK.IDSA.SA.2023.REC.02",
      "display_id": "IDSA-SA-R2",
      "statement": "When gram stain is negative, initiate empiric therapy with vancomycin plus ceftriaxone",
      "normalized_claim": "Empiric antibiotic therapy with vancomycin and ceftriaxone is recommended when gram stain is negative",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Negative gram stain on joint fluid",
      "population": "Patients with suspected septic arthritis and negative gram stain",
      "provenance": {
        "section": "Antibiotic Therapy",
        "quote_snippet": "Negative gram stain → vanc + ceftriaxone",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "rec_id": "PACK.IDSA.SA.2023.REC.03",
      "display_id": "IDSA-SA-R3",
      "statement": "Differentiate septic arthritis from osteomyelitis by location of tenderness",
      "normalized_claim": "Septic arthritis presents with pain over the joint while osteomyelitis presents with tenderness over bone",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "context": "Differential diagnosis between septic arthritis and osteomyelitis",
      "population": "Patients with musculoskeletal infection",
      "provenance": {
        "section": "Differential Diagnosis",
        "quote_snippet": "DDx septic arthritis (pain over joint) vs osteomyelitis (tender over bone)",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "rec_id": "PACK.IDSA.SA.2023.REC.04",
      "display_id": "IDSA-SA-R4",
      "statement": "Consider septic arthritis in patients with puncture wounds overlying joints",
      "normalized_claim": "Puncture wounds through soft tissue overlying joints can result in septic arthritis",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Penetrating trauma to joints",
      "population": "Patients with puncture wounds near joints",
      "provenance": {
        "section": "Risk Factors",
        "quote_snippet": "Puncture (tooth) through soft tissue overlying MCP joint, can result in septic arthritis",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "rec_id": "PACK.IDSA.SA.2023.REC.05",
      "display_id": "IDSA-SA-R5",
      "statement": "Recognize septic arthritis as a potential manifestation of septic emboli",
      "normalized_claim": "Septic arthritis can occur as part of systemic septic emboli with fever, chills, and malaise",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Systemic infection with septic emboli",
      "population": "Patients with endocarditis or bacteremia",
      "provenance": {
        "section": "Clinical Manifestations",
        "quote_snippet": "CF: Fever, Chills, Malaise, Signs of septic emboli (pneumonia, skin changes, septic arthritis)",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.IDSA.SA.2023.DC.01",
      "display_id": "IDSA-SA-DC1",
      "name": "Septic Arthritis Clinical Criteria",
      "components": [
        "Joint pain",
        "Erythema",
        "Swelling",
        "Fluctuant joint",
        "Painful range of motion"
      ],
      "threshold": "Presence of multiple components",
      "interpretation": "Clinical signs consistent with septic arthritis",
      "normalized_claim": "Septic arthritis presents with joint pain, erythema, swelling, fluctuance, and painful range of motion",
      "provenance": {
        "section": "Clinical Manifestations",
        "quote_snippet": "Joint pain, erythema, swelling, fluctuant, painful range of motion",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.IDSA.SA.2023.T.01",
      "display_id": "IDSA-SA-T1",
      "parameter": "Joint fluid WBC count",
      "value": "50000",
      "unit": "cells/μL",
      "clinical_meaning": "Highly suggestive of septic arthritis",
      "normalized_claim": "Joint fluid WBC count >50,000 cells/μL indicates septic arthritis",
      "direction": "above",
      "provenance": {
        "section": "Laboratory Diagnosis",
        "quote_snippet": "WBC count in joint fluid? >50k",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "threshold_id": "PACK.IDSA.SA.2023.T.02",
      "display_id": "IDSA-SA-T2",
      "parameter": "Joint fluid WBC count for crystalline arthropathy",
      "value": "50000",
      "unit": "cells/μL",
      "clinical_meaning": "Can indicate septic arthritis or crystalline arthropathy",
      "normalized_claim": "Joint fluid WBC >50,000 cells/μL suggests septic arthritis or crystalline arthropathy",
      "direction": "above",
      "provenance": {
        "section": "Differential Diagnosis",
        "quote_snippet": ">50k → septic arthritis or crystalline arthropathy",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.IDSA.SA.2023.TX.01",
      "display_id": "IDSA-SA-TX1",
      "action": "Joint washout plus antibiotics",
      "normalized_claim": "Treatment of septic arthritis requires joint washout and antibiotic therapy",
      "timing": "Emergent",
      "condition": "Confirmed septic arthritis",
      "provenance": {
        "section": "Treatment",
        "quote_snippet": "Tx? Joint washout + abx",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "step_id": "PACK.IDSA.SA.2023.TX.02",
      "display_id": "IDSA-SA-TX2",
      "action": "Gonococcal arthritis treatment",
      "normalized_claim": "Gonococcal arthritis should be treated with ceftriaxone plus doxycycline or azithromycin",
      "condition": "Gonococcal arthritis",
      "drug_details": {
        "drug": "ceftriaxone plus doxycycline or azithromycin"
      },
      "provenance": {
        "section": "Organism-Specific Treatment",
        "quote_snippet": "Gonococcal arthritis? Ceftriaxone + doxy/azithro",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "step_id": "PACK.IDSA.SA.2023.TX.03",
      "display_id": "IDSA-SA-TX3",
      "action": "Staphylococcus aureus treatment",
      "normalized_claim": "Staphylococcus aureus septic arthritis should be treated with vancomycin",
      "condition": "Staphylococcus aureus infection or high MRSA risk",
      "drug_details": {
        "drug": "vancomycin"
      },
      "provenance": {
        "section": "Organism-Specific Treatment",
        "quote_snippet": "Bug: Staph aureus (sickle cell → Salmonella); Tx: Vancomycin",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "step_id": "PACK.IDSA.SA.2023.TX.04",
      "display_id": "IDSA-SA-TX4",
      "action": "Disseminated gonococcal infection treatment",
      "normalized_claim": "Gonococcal arthritis with skin petechiae should be treated with ceftriaxone or cefotaxime",
      "condition": "Disseminated gonococcal infection with skin manifestations",
      "drug_details": {
        "drug": "ceftriaxone or cefotaxime"
      },
      "provenance": {
        "section": "Disseminated Gonococcal Infection",
        "quote_snippet": "+ Petechiae on skin → gonococcal; Tx: ceftriaxone/cefotaxime",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    },
    {
      "step_id": "PACK.IDSA.SA.2023.TX.05",
      "display_id": "IDSA-SA-TX5",
      "action": "Pediatric septic arthritis management",
      "normalized_claim": "Pediatric septic arthritis requires aspiration and antibiotic therapy",
      "condition": "Septic arthritis in pediatric patients",
      "provenance": {
        "section": "Pediatric Considerations",
        "quote_snippet": "Septic Arthritis: Infants: Fussiness, Hip flexed/abducted/ER; Lab: Elevated WBC/ESR/CRP; Tx: Aspiration + Abx",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.IDSA.SA.2023.RF.01",
      "display_id": "IDSA-SA-RF1",
      "finding": "Severe joint pain with erythema",
      "implication": "High suspicion for septic arthritis requiring urgent evaluation",
      "action": "Immediate arthrocentesis and surgical washout if WBC >50,000",
      "urgency": "immediate",
      "provenance": {
        "section": "Emergency Management",
        "quote_snippet": "Severe joint pain + erythematous → NBS: Arthrocentesis (WBC >50k → washout)",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.IDSA.SA.2023.SEV.01",
      "display_id": "IDSA-SA-SEV1",
      "level": "Acute septic arthritis",
      "criteria": [
        "Joint fluid WBC >50,000 cells/μL",
        "Positive gram stain or culture",
        "Clinical signs of joint infection"
      ],
      "management_implications": "Requires immediate surgical drainage and IV antibiotics",
      "provenance": {
        "section": "Severity Assessment",
        "quote_snippet": "WBCs >50K -> Septic arthritis",
        "page_or_location": "DI/IC-derived, verify against guideline"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "validated",
  "last_normalized": "2024-12-19",
  "normalizer_version": 1,
  "normalization_notes": "Generated from board review evidence (Divine Intervention, Inner Circle, Emma Holliday). Key items include arthrocentesis recommendations, WBC threshold >50k, empiric antibiotic protocols, and organism-specific treatments. Requires verification against actual IDSA septic arthritis guidelines. Missing formal diagnostic criteria and severity classifications from guidelines. Red flag section needs expansion with more emergency presentations.",
  "all_item_ids": [
    "PACK.IDSA.SA.2023.REC.01",
    "PACK.IDSA.SA.2023.REC.02",
    "PACK.IDSA.SA.2023.REC.03",
    "PACK.IDSA.SA.2023.REC.04",
    "PACK.IDSA.SA.2023.REC.05",
    "PACK.IDSA.SA.2023.DC.01",
    "PACK.IDSA.SA.2023.T.01",
    "PACK.IDSA.SA.2023.T.02",
    "PACK.IDSA.SA.2023.TX.01",
    "PACK.IDSA.SA.2023.TX.02",
    "PACK.IDSA.SA.2023.TX.03",
    "PACK.IDSA.SA.2023.TX.04",
    "PACK.IDSA.SA.2023.TX.05",
    "PACK.IDSA.SA.2023.RF.01",
    "PACK.IDSA.SA.2023.SEV.01"
  ],
  "all_display_ids": [
    "IDSA-SA-R1",
    "IDSA-SA-R2",
    "IDSA-SA-R3",
    "IDSA-SA-R4",
    "IDSA-SA-R5",
    "IDSA-SA-DC1",
    "IDSA-SA-T1",
    "IDSA-SA-T2",
    "IDSA-SA-TX1",
    "IDSA-SA-TX2",
    "IDSA-SA-TX3",
    "IDSA-SA-TX4",
    "IDSA-SA-TX5",
    "IDSA-SA-RF1",
    "IDSA-SA-SEV1"
  ]
};
