import type { SourcePack } from './types';

export const PACK_IDSA_SSTI_2014: SourcePack = {
  source_pack_id: 'PACK.IDSA.SSTI.2014',
  source_name: 'IDSA 2014 Practice Guidelines for the Diagnosis and Management of Skin and Soft Tissue Infections',
  source_registry_id: 'REG.IDSA.SSTI',
  canonical_url: 'https://doi.org/10.1093/cid/ciu296',
  publication_year: 2014,
  guideline_body: 'IDSA',

  topic_tags: ['Cellulitis', 'Abscess', 'Necrotizing Fasciitis', 'MRSA', 'SSTI', 'Infectious Disease'],
  allowed_decision_scopes: [
    'cellulitis diagnosis and treatment',
    'purulent vs non-purulent SSTI classification',
    'MRSA coverage decisions',
    'abscess incision and drainage',
    'necrotizing fasciitis recognition and management',
    'diabetic foot infection classification',
    'bite wound management',
    'surgical site infection treatment',
  ],
  excluded_decision_scopes: [
    'chronic wound care',
    'burn wound management',
    'osteomyelitis treatment specifics',
    'prosthetic joint infection management',
    'decubitus ulcer staging',
  ],

  recommendations: [
    {
      rec_id: 'PACK.IDSA.SSTI.2014.REC.01',
      display_id: 'IDSA-SSTI-R1',
      statement: 'Non-purulent cellulitis (no abscess, no drainable focus) should be treated with a beta-lactam antibiotic targeting streptococci. MRSA coverage is NOT routinely needed.',
      normalized_claim: 'Non-purulent cellulitis: beta-lactam (cephalexin or dicloxacillin). No MRSA coverage needed; strep is the predominant pathogen.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Non-Purulent SSTI', page_or_location: 'Section III' },
    },
    {
      rec_id: 'PACK.IDSA.SSTI.2014.REC.02',
      display_id: 'IDSA-SSTI-R2',
      statement: 'Purulent cellulitis or cutaneous abscess should be treated with incision and drainage (I&D). For abscesses, I&D alone is often sufficient for mild disease. Add TMP-SMX or doxycycline for MRSA coverage if moderate-severe.',
      normalized_claim: 'Purulent SSTI: I&D is primary treatment. Add MRSA-active antibiotic (TMP-SMX or doxycycline) for moderate-severe cases.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Purulent SSTI', page_or_location: 'Section IV' },
    },
    {
      rec_id: 'PACK.IDSA.SSTI.2014.REC.03',
      display_id: 'IDSA-SSTI-R3',
      statement: 'Necrotizing fasciitis is a surgical emergency. Empiric broad-spectrum antibiotics should be initiated immediately, but definitive treatment is aggressive surgical debridement. Delay in surgery increases mortality.',
      normalized_claim: 'Necrotizing fasciitis: emergent surgical debridement is definitive treatment. Antibiotics alone are insufficient. Surgical delay increases mortality.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Necrotizing Fasciitis', page_or_location: 'Section VII' },
    },
    {
      rec_id: 'PACK.IDSA.SSTI.2014.REC.04',
      display_id: 'IDSA-SSTI-R4',
      statement: 'Empiric antibiotic therapy for necrotizing fasciitis should cover gram-positives (including MRSA), gram-negatives, and anaerobes. Vancomycin + piperacillin-tazobactam (or a carbapenem) is recommended.',
      normalized_claim: 'Necrotizing fasciitis empiric antibiotics: vancomycin (MRSA) + piperacillin-tazobactam or meropenem (gram-neg + anaerobes). Add clindamycin for toxin inhibition in GAS.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Necrotizing SSTI Antibiotics', page_or_location: 'Section VII' },
    },
    {
      rec_id: 'PACK.IDSA.SSTI.2014.REC.05',
      display_id: 'IDSA-SSTI-R5',
      statement: 'Diabetic foot infections should be classified by severity (mild, moderate, severe) to guide treatment intensity. All moderate-severe diabetic foot infections require assessment for osteomyelitis.',
      normalized_claim: 'Diabetic foot infections: classify severity. Mild = oral antibiotics. Moderate-severe = IV antibiotics + imaging for osteomyelitis (MRI preferred). All need vascular assessment.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Diabetic Foot Infections', page_or_location: 'Section VIII' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.IDSA.SSTI.2014.DC.01',
      display_id: 'IDSA-SSTI-DC1',
      name: 'LRINEC Score for Necrotizing Fasciitis',
      components: [
        'CRP >=150 mg/L (+4)',
        'WBC: 15,000-25,000 (+1), >25,000 (+2)',
        'Hemoglobin: 11-13.5 (+1), <11 (+2)',
        'Sodium <135 mEq/L (+2)',
        'Creatinine >1.6 mg/dL (+2)',
        'Glucose >180 mg/dL (+1)',
      ],
      threshold: 'Score >=6: suspicious for necrotizing fasciitis; >=8: strongly predictive',
      interpretation: 'LRINEC >=6 should raise suspicion for necrotizing fasciitis. However, a low score does not exclude it. Clinical judgment and surgical exploration remain the gold standard.',
      normalized_claim: 'LRINEC >=6 raises necrotizing fasciitis suspicion. Low score does NOT exclude it. Surgical exploration is the diagnostic gold standard.',
      provenance: { section: 'Necrotizing SSTI Diagnosis', page_or_location: 'Section VII, referenced scoring' },
    },
    {
      criterion_id: 'PACK.IDSA.SSTI.2014.DC.02',
      display_id: 'IDSA-SSTI-DC2',
      name: 'Purulent vs Non-Purulent SSTI Classification',
      components: [
        'Purulent: Presence of abscess, fluctuance, purulent drainage, or wound with purulent exudate. S. aureus (including MRSA) is primary pathogen.',
        'Non-purulent: Erythema, warmth, tenderness without drainable focus. Beta-hemolytic streptococci are primary pathogens.',
      ],
      interpretation: 'Classification determines antibiotic choice: purulent SSTIs need S. aureus/MRSA coverage; non-purulent cellulitis needs streptococcal coverage (beta-lactam).',
      normalized_claim: 'Purulent SSTI = S. aureus/MRSA coverage. Non-purulent cellulitis = streptococcal coverage (beta-lactam). This distinction drives antibiotic selection.',
      provenance: { section: 'SSTI Classification', page_or_location: 'Section II' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.IDSA.SSTI.2014.T.01',
      display_id: 'IDSA-SSTI-T1',
      parameter: 'LRINEC score',
      value: '6',
      clinical_meaning: 'LRINEC score >=6 is the threshold that should prompt evaluation for necrotizing fasciitis. Score >=8 is strongly predictive. Sensitivity is moderate; clinical exam and surgical exploration remain essential.',
      normalized_claim: 'LRINEC >=6 prompts necrotizing fasciitis workup; >=8 strongly predictive. Clinical judgment supersedes score.',
      direction: 'above',
      provenance: { section: 'Necrotizing Fasciitis Scoring', page_or_location: 'Section VII' },
    },
    {
      threshold_id: 'PACK.IDSA.SSTI.2014.T.02',
      display_id: 'IDSA-SSTI-T2',
      parameter: 'Abscess size for antibiotic adjunct',
      value: '2',
      unit: 'cm',
      clinical_meaning: 'Simple abscesses <2 cm may be treated with I&D alone without antibiotics in immunocompetent patients. Abscesses >=2 cm or with surrounding cellulitis benefit from adjunctive MRSA-active antibiotics.',
      normalized_claim: 'Abscess <2 cm: I&D alone may suffice. >=2 cm or cellulitis surround: add TMP-SMX or doxycycline.',
      direction: 'above',
      provenance: { section: 'Abscess Management', page_or_location: 'Section IV' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.IDSA.SSTI.2014.TX.01',
      display_id: 'IDSA-SSTI-TX1',
      action: 'Non-purulent cellulitis: Outpatient oral beta-lactam',
      normalized_claim: 'Non-purulent cellulitis: cephalexin 500mg QID or dicloxacillin 500mg QID x 5-7 days. Elevation of affected extremity. No MRSA coverage needed.',
      timing: 'At diagnosis',
      condition: 'Mild non-purulent cellulitis without systemic signs',
      drug_details: { drug: 'Cephalexin', dose: '500mg QID', route: 'PO', duration: '5-7 days' },
      contraindications: ['Severe penicillin/cephalosporin allergy (use clindamycin)'],
      provenance: { section: 'Non-Purulent SSTI Treatment', page_or_location: 'Section III' },
    },
    {
      step_id: 'PACK.IDSA.SSTI.2014.TX.02',
      display_id: 'IDSA-SSTI-TX2',
      action: 'Purulent SSTI: Incision and drainage + MRSA coverage',
      normalized_claim: 'Purulent SSTI: I&D is primary. For moderate disease, add TMP-SMX DS 1-2 tabs BID or doxycycline 100mg BID x 7-10 days for MRSA coverage. Send wound culture.',
      timing: 'At presentation',
      condition: 'Cutaneous abscess or purulent cellulitis',
      drug_details: { drug: 'TMP-SMX DS', dose: '1-2 tablets BID', route: 'PO', duration: '7-10 days' },
      escalation: 'If SIRS present or immunocompromised: IV vancomycin + admission.',
      provenance: { section: 'Purulent SSTI Treatment', page_or_location: 'Section IV' },
    },
    {
      step_id: 'PACK.IDSA.SSTI.2014.TX.03',
      display_id: 'IDSA-SSTI-TX3',
      action: 'Necrotizing fasciitis: Emergent surgical debridement + broad-spectrum antibiotics',
      normalized_claim: 'Necrotizing fasciitis: emergent OR for debridement. Vancomycin + piperacillin-tazobactam (or meropenem) + clindamycin (toxin suppression). Planned re-exploration at 24-48 hours.',
      timing: 'Immediate surgical consultation upon suspicion',
      condition: 'Suspected necrotizing fasciitis (pain out of proportion, systemic toxicity, crepitus, rapid spread)',
      drug_details: { drug: 'Vancomycin + Piperacillin-Tazobactam + Clindamycin', route: 'IV' },
      contraindications: ['Do NOT delay surgery for imaging (CT/MRI). Imaging may be falsely reassuring early.'],
      provenance: { section: 'Necrotizing SSTI Treatment', page_or_location: 'Section VII' },
    },
    {
      step_id: 'PACK.IDSA.SSTI.2014.TX.04',
      display_id: 'IDSA-SSTI-TX4',
      action: 'Moderate diabetic foot infection: IV antibiotics + imaging',
      normalized_claim: 'Moderate DFI: ampicillin-sulbactam or ertapenem (polymicrobial coverage). MRI to evaluate for osteomyelitis. Vascular assessment for PAD. Wound care and off-loading.',
      timing: 'At admission for moderate-severe DFI',
      condition: 'Diabetic foot infection with cellulitis >2 cm, deep tissue involvement, or systemic signs',
      drug_details: { drug: 'Ampicillin-Sulbactam', dose: '3g IV q6h', route: 'IV' },
      escalation: 'If osteomyelitis confirmed: 6 weeks IV antibiotics or surgical resection. If limb-threatening ischemia: vascular surgery consultation.',
      provenance: { section: 'Diabetic Foot Infections', page_or_location: 'Section VIII' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.IDSA.SSTI.2014.RF.01',
      display_id: 'IDSA-SSTI-RF1',
      finding: 'Pain out of proportion to exam findings with systemic toxicity (fever, tachycardia, hypotension) in SSTI',
      implication: 'Hallmark of necrotizing fasciitis. Skin may appear deceptively normal early while deep fascial necrosis progresses. Mortality 20-40% even with treatment.',
      action: 'Emergent surgical consultation for exploration and debridement. Broad-spectrum IV antibiotics. ICU admission. Do NOT delay surgery for imaging.',
      urgency: 'immediate',
      provenance: { section: 'Necrotizing Fasciitis Recognition', page_or_location: 'Section VII' },
    },
    {
      flag_id: 'PACK.IDSA.SSTI.2014.RF.02',
      display_id: 'IDSA-SSTI-RF2',
      finding: 'Crepitus on palpation or subcutaneous gas on imaging in SSTI',
      implication: 'Indicates gas-producing organisms (Clostridium or mixed aerobic-anaerobic infection). Highly suggestive of necrotizing infection or gas gangrene. Requires emergent surgical intervention.',
      action: 'Immediate surgical exploration and debridement. IV antibiotics with anaerobic coverage (clindamycin + penicillin for clostridial; broad-spectrum for polymicrobial).',
      urgency: 'immediate',
      provenance: { section: 'Gas Gangrene/Necrotizing Infection', page_or_location: 'Section VII' },
    },
    {
      flag_id: 'PACK.IDSA.SSTI.2014.RF.03',
      display_id: 'IDSA-SSTI-RF3',
      finding: 'Rapidly spreading cellulitis with bullae formation, skin necrosis, or anesthesia of overlying skin',
      implication: 'Suggests progression from simple cellulitis to necrotizing fasciitis. Skin necrosis and anesthesia indicate loss of blood supply to dermis from underlying fascial involvement.',
      action: 'Emergent surgical consultation. Upgrade to broad-spectrum IV antibiotics. Prepare for OR debridement.',
      urgency: 'immediate',
      provenance: { section: 'Necrotizing Fasciitis Progression', page_or_location: 'Section VII' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.IDSA.SSTI.2014.SEV.01',
      display_id: 'IDSA-SSTI-SEV1',
      level: 'Severe SSTI (necrotizing or life-threatening)',
      criteria: [
        'Necrotizing fasciitis (clinical or surgical diagnosis)',
        'Gas gangrene (clostridial myonecrosis)',
        'SSTI with sepsis or septic shock',
        'Failed outpatient therapy with hemodynamic compromise',
        'Rapidly progressive cellulitis with skin necrosis',
      ],
      management_implications:
        'ICU admission. Emergent surgical debridement (within hours, not days). Broad-spectrum IV antibiotics (vancomycin + pip-tazo + clindamycin). Planned surgical re-exploration at 24-48 hours. May require multiple debridements, skin grafting, or amputation.',
      provenance: { section: 'Severe SSTI Classification', page_or_location: 'Section VII' },
    },
    {
      severity_id: 'PACK.IDSA.SSTI.2014.SEV.02',
      display_id: 'IDSA-SSTI-SEV2',
      level: 'Moderate SSTI (systemic signs, requires IV therapy)',
      criteria: [
        'Cellulitis >5 cm with SIRS (fever, tachycardia, leukocytosis)',
        'Abscess with surrounding cellulitis and systemic signs',
        'Purulent SSTI in immunocompromised host',
        'Moderate diabetic foot infection with deep tissue involvement',
        'Failed initial outpatient antibiotic therapy',
      ],
      management_implications:
        'Hospital admission for IV antibiotics. Blood cultures if febrile. For purulent: I&D + IV vancomycin (MRSA). For non-purulent: IV cefazolin or nafcillin. Daily reassessment for clinical improvement vs progression. Transition to oral when improving for 24-48 hours.',
      provenance: { section: 'Moderate SSTI Classification', page_or_location: 'Section II-IV' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Pack for SSTI management. Covers purulent vs non-purulent classification, MRSA coverage decisions, necrotizing fasciitis recognition (LRINEC, pain out of proportion), diabetic foot infections, and severity-based treatment escalation.',

  all_item_ids: [
    'PACK.IDSA.SSTI.2014.REC.01', 'PACK.IDSA.SSTI.2014.REC.02', 'PACK.IDSA.SSTI.2014.REC.03',
    'PACK.IDSA.SSTI.2014.REC.04', 'PACK.IDSA.SSTI.2014.REC.05',
    'PACK.IDSA.SSTI.2014.DC.01', 'PACK.IDSA.SSTI.2014.DC.02',
    'PACK.IDSA.SSTI.2014.T.01', 'PACK.IDSA.SSTI.2014.T.02',
    'PACK.IDSA.SSTI.2014.TX.01', 'PACK.IDSA.SSTI.2014.TX.02', 'PACK.IDSA.SSTI.2014.TX.03',
    'PACK.IDSA.SSTI.2014.TX.04',
    'PACK.IDSA.SSTI.2014.RF.01', 'PACK.IDSA.SSTI.2014.RF.02', 'PACK.IDSA.SSTI.2014.RF.03',
    'PACK.IDSA.SSTI.2014.SEV.01', 'PACK.IDSA.SSTI.2014.SEV.02',
  ],
  all_display_ids: [
    'IDSA-SSTI-R1', 'IDSA-SSTI-R2', 'IDSA-SSTI-R3', 'IDSA-SSTI-R4', 'IDSA-SSTI-R5',
    'IDSA-SSTI-DC1', 'IDSA-SSTI-DC2',
    'IDSA-SSTI-T1', 'IDSA-SSTI-T2',
    'IDSA-SSTI-TX1', 'IDSA-SSTI-TX2', 'IDSA-SSTI-TX3', 'IDSA-SSTI-TX4',
    'IDSA-SSTI-RF1', 'IDSA-SSTI-RF2', 'IDSA-SSTI-RF3',
    'IDSA-SSTI-SEV1', 'IDSA-SSTI-SEV2',
  ],
};
