import type { SourcePack } from './types';

export const PACK_KDIGO_AKI_2024: SourcePack = {
  source_pack_id: 'PACK.KDIGO.AKI.2024',
  source_name: 'KDIGO 2024 Clinical Practice Guideline for Acute Kidney Injury',
  source_registry_id: 'REG.KDIGO.AKI',
  canonical_url: 'https://doi.org/10.1038/s41581-024-00800-0',
  publication_year: 2024,
  guideline_body: 'KDIGO',

  topic_tags: ['AKI', 'Acute Kidney Injury', 'Renal', 'Electrolytes', 'Nephrology'],
  allowed_decision_scopes: [
    'AKI diagnosis and staging',
    'prerenal vs intrinsic vs postrenal differentiation',
    'volume assessment and fluid management',
    'nephrotoxin avoidance',
    'hyperkalemia management',
    'RRT indications',
    'urinary diagnostic studies',
    'drug dose adjustment in AKI',
  ],
  excluded_decision_scopes: [
    'chronic kidney disease management',
    'dialysis modality selection for ESRD',
    'renal transplant evaluation',
    'glomerulonephritis-specific treatment',
    'polycystic kidney disease',
  ],

  recommendations: [
    {
      rec_id: 'PACK.KDIGO.AKI.2024.REC.01',
      display_id: 'KDIGO-AKI-R1',
      statement: 'Initial evaluation of AKI should include assessment of volume status, medication review for nephrotoxins, and urinalysis to differentiate prerenal, intrinsic, and postrenal causes.',
      normalized_claim: 'AKI workup: volume assessment + nephrotoxin review + UA with microscopy + renal US if postrenal suspected.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Evaluation', page_or_location: 'Section 2.1' },
    },
    {
      rec_id: 'PACK.KDIGO.AKI.2024.REC.02',
      display_id: 'KDIGO-AKI-R2',
      statement: 'Isotonic crystalloid fluid challenge is recommended for patients with suspected prerenal AKI. Reassess urine output and creatinine after fluid administration.',
      normalized_claim: 'Prerenal AKI: IV NS bolus, reassess UOP and Cr. Improvement confirms prerenal etiology.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Prerenal Management', page_or_location: 'Section 3.1' },
    },
    {
      rec_id: 'PACK.KDIGO.AKI.2024.REC.03',
      display_id: 'KDIGO-AKI-R3',
      statement: 'All nephrotoxic medications should be discontinued or dose-adjusted in AKI. NSAIDs, aminoglycosides, and iodinated contrast are the most common culprits.',
      normalized_claim: 'Discontinue nephrotoxins: NSAIDs, aminoglycosides, ACEi/ARBs in acute setting, IV contrast.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Nephrotoxin Avoidance', page_or_location: 'Section 3.2' },
    },
    {
      rec_id: 'PACK.KDIGO.AKI.2024.REC.04',
      display_id: 'KDIGO-AKI-R4',
      statement: 'Renal replacement therapy should be initiated for life-threatening indications: refractory hyperkalemia, severe metabolic acidosis, uremic symptoms (pericarditis, encephalopathy), or refractory fluid overload.',
      normalized_claim: 'RRT indications: refractory hyperK, severe acidosis, uremic symptoms, refractory fluid overload.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'RRT Indications', page_or_location: 'Section 5.1' },
    },
    {
      rec_id: 'PACK.KDIGO.AKI.2024.REC.05',
      display_id: 'KDIGO-AKI-R5',
      statement: 'Urinary indices (FENa, FEUrea, urine sodium) should be obtained before diuretic administration to distinguish prerenal from intrinsic AKI.',
      normalized_claim: 'Obtain urinary indices BEFORE diuretics. FENa <1% = prerenal, >2% = ATN. FEUrea <35% = prerenal (reliable even on diuretics).',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Diagnostic Studies', page_or_location: 'Section 2.2' },
    },
    {
      rec_id: 'PACK.KDIGO.AKI.2024.REC.06',
      display_id: 'KDIGO-AKI-R6',
      statement: 'Hyperkalemia with ECG changes requires emergent treatment: IV calcium gluconate for membrane stabilization, insulin + dextrose for intracellular shift, and consideration of RRT.',
      normalized_claim: 'Hyperkalemia + ECG changes: calcium gluconate first (stabilize membrane), then insulin+D50 for shift, kayexalate/patiromer for removal, RRT if refractory.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Hyperkalemia', page_or_location: 'Section 4.1' },
    },
    {
      rec_id: 'PACK.KDIGO.AKI.2024.REC.07',
      display_id: 'KDIGO-AKI-R7',
      statement: 'Postrenal AKI (obstruction) should be excluded early with renal ultrasound. Foley catheter placement is both diagnostic and therapeutic for bladder outlet obstruction.',
      normalized_claim: 'Renal US to exclude obstruction. Foley catheter for suspected bladder outlet obstruction.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Postrenal AKI', page_or_location: 'Section 3.3' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.KDIGO.AKI.2024.DC.01',
      display_id: 'KDIGO-AKI-DC1',
      name: 'KDIGO AKI Staging',
      components: [
        'Stage 1: Cr increase 1.5-1.9x baseline OR increase >=0.3 mg/dL within 48h OR UOP <0.5 mL/kg/h for 6-12h',
        'Stage 2: Cr increase 2.0-2.9x baseline OR UOP <0.5 mL/kg/h for >=12h',
        'Stage 3: Cr increase >=3.0x baseline OR Cr >=4.0 mg/dL OR initiation of RRT OR UOP <0.3 mL/kg/h for >=24h OR anuria >=12h',
      ],
      interpretation: 'AKI defined by any one criterion. Stage determines severity and guides management intensity.',
      normalized_claim: 'AKI staging: Stage 1 (Cr x1.5 or +0.3), Stage 2 (Cr x2), Stage 3 (Cr x3 or >=4 or RRT).',
      provenance: { section: 'Definition and Staging', page_or_location: 'Section 1.1' },
    },
    {
      criterion_id: 'PACK.KDIGO.AKI.2024.DC.02',
      display_id: 'KDIGO-AKI-DC2',
      name: 'Prerenal AKI Criteria',
      components: [
        'BUN/Cr ratio >20:1',
        'FENa <1%',
        'Urine Na <20 mEq/L',
        'Urine osmolality >500 mOsm/kg',
        'Bland urine sediment (no casts)',
        'Rapid improvement with volume repletion',
      ],
      interpretation: 'Prerenal AKI = kidney responding appropriately to decreased perfusion. Reversible with volume.',
      normalized_claim: 'Prerenal pattern: BUN/Cr >20, FENa <1%, urine Na <20, concentrated urine, bland sediment.',
      provenance: { section: 'Differential Diagnosis', page_or_location: 'Section 2.3' },
    },
    {
      criterion_id: 'PACK.KDIGO.AKI.2024.DC.03',
      display_id: 'KDIGO-AKI-DC3',
      name: 'ATN (Intrinsic AKI) Criteria',
      components: [
        'FENa >2%',
        'Urine Na >40 mEq/L',
        'Urine osmolality <350 mOsm/kg',
        'Muddy brown granular casts on UA',
        'BUN/Cr ratio <20:1',
        'Does NOT improve with volume repletion',
      ],
      interpretation: 'ATN = tubular damage with loss of concentrating ability. Supportive care; avoid further nephrotoxic insults.',
      normalized_claim: 'ATN pattern: FENa >2%, urine Na >40, isosthenuria, muddy brown casts, no volume response.',
      provenance: { section: 'Differential Diagnosis', page_or_location: 'Section 2.3' },
    },
    {
      criterion_id: 'PACK.KDIGO.AKI.2024.DC.04',
      display_id: 'KDIGO-AKI-DC4',
      name: 'Postrenal AKI Criteria',
      components: [
        'Hydronephrosis on renal ultrasound',
        'Elevated post-void residual',
        'Bilateral ureteral obstruction or solitary kidney with obstruction',
        'Improvement after catheter placement or stenting',
      ],
      interpretation: 'Postrenal AKI = obstruction. Relieve obstruction urgently to prevent irreversible damage.',
      normalized_claim: 'Postrenal = hydronephrosis on US. Foley or stent relieves obstruction.',
      provenance: { section: 'Postrenal AKI', page_or_location: 'Section 3.3' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.KDIGO.AKI.2024.T.01',
      display_id: 'KDIGO-AKI-T1',
      parameter: 'FENa',
      value: '1',
      unit: '%',
      clinical_meaning: 'FENa <1% suggests prerenal etiology (kidney avidly retaining sodium). FENa >2% suggests intrinsic renal disease (ATN).',
      normalized_claim: 'FENa <1% = prerenal. FENa >2% = intrinsic (ATN). 1-2% = indeterminate.',
      direction: 'below',
      provenance: { section: 'Urinary Indices', page_or_location: 'Section 2.2' },
    },
    {
      threshold_id: 'PACK.KDIGO.AKI.2024.T.02',
      display_id: 'KDIGO-AKI-T2',
      parameter: 'FEUrea',
      value: '35',
      unit: '%',
      clinical_meaning: 'FEUrea <35% suggests prerenal AKI. Useful when patient is on diuretics (FENa unreliable on diuretics).',
      normalized_claim: 'FEUrea <35% = prerenal (reliable even on diuretics, unlike FENa).',
      direction: 'below',
      provenance: { section: 'Urinary Indices', page_or_location: 'Section 2.2' },
    },
    {
      threshold_id: 'PACK.KDIGO.AKI.2024.T.03',
      display_id: 'KDIGO-AKI-T3',
      parameter: 'BUN/Cr ratio',
      value: '20',
      clinical_meaning: 'BUN/Cr >20:1 suggests prerenal AKI (urea reabsorbed disproportionately to creatinine in volume-depleted states).',
      normalized_claim: 'BUN/Cr >20:1 = prerenal pattern.',
      direction: 'above',
      provenance: { section: 'Diagnostic Studies', page_or_location: 'Section 2.2' },
    },
    {
      threshold_id: 'PACK.KDIGO.AKI.2024.T.04',
      display_id: 'KDIGO-AKI-T4',
      parameter: 'Urine sodium',
      value: '20',
      unit: 'mEq/L',
      clinical_meaning: 'Urine Na <20 mEq/L suggests prerenal AKI (kidney retaining sodium). Urine Na >40 mEq/L suggests ATN.',
      normalized_claim: 'Urine Na <20 = prerenal. Urine Na >40 = intrinsic.',
      direction: 'below',
      provenance: { section: 'Urinary Indices', page_or_location: 'Section 2.2' },
    },
    {
      threshold_id: 'PACK.KDIGO.AKI.2024.T.05',
      display_id: 'KDIGO-AKI-T5',
      parameter: 'Serum potassium for urgent RRT',
      value: '6.5',
      unit: 'mEq/L',
      clinical_meaning: 'K+ >=6.5 mEq/L with ECG changes (peaked T waves, widened QRS) is an indication for emergent RRT if medical management fails.',
      normalized_claim: 'K+ >=6.5 with ECG changes = emergent treatment; consider RRT if refractory.',
      direction: 'above',
      provenance: { section: 'Hyperkalemia', page_or_location: 'Section 4.1' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.KDIGO.AKI.2024.TX.01',
      display_id: 'KDIGO-AKI-TX1',
      action: 'Prerenal AKI: volume resuscitation',
      normalized_claim: 'IV isotonic crystalloid bolus (NS or LR). Reassess UOP and Cr. Improvement within hours confirms prerenal.',
      timing: 'Immediate',
      drug_details: { drug: 'Normal saline', dose: '500-1000 mL', route: 'IV bolus' },
      provenance: { section: 'Prerenal Management', page_or_location: 'Section 3.1' },
    },
    {
      step_id: 'PACK.KDIGO.AKI.2024.TX.02',
      display_id: 'KDIGO-AKI-TX2',
      action: 'ATN: supportive care',
      normalized_claim: 'No specific treatment for ATN. Supportive care: avoid nephrotoxins, maintain euvolemia, monitor electrolytes, adjust drug doses.',
      timing: 'Ongoing',
      provenance: { section: 'Intrinsic AKI', page_or_location: 'Section 3.2' },
    },
    {
      step_id: 'PACK.KDIGO.AKI.2024.TX.03',
      display_id: 'KDIGO-AKI-TX3',
      action: 'Postrenal AKI: relieve obstruction',
      normalized_claim: 'Foley catheter for bladder outlet obstruction. Ureteral stent or nephrostomy for upper tract obstruction.',
      timing: 'Urgent',
      provenance: { section: 'Postrenal Management', page_or_location: 'Section 3.3' },
    },
    {
      step_id: 'PACK.KDIGO.AKI.2024.TX.04',
      display_id: 'KDIGO-AKI-TX4',
      action: 'Hyperkalemia: emergent management',
      normalized_claim: 'Step 1: calcium gluconate (membrane stabilization). Step 2: insulin 10U + D50 (intracellular shift). Step 3: kayexalate or patiromer (GI removal). Step 4: RRT if refractory.',
      timing: 'Emergent when ECG changes present',
      drug_details: { drug: 'Calcium gluconate', dose: '1g', route: 'IV over 2-3 minutes' },
      escalation: 'RRT if K+ remains >6.5 despite medical management',
      provenance: { section: 'Hyperkalemia', page_or_location: 'Section 4.1' },
    },
    {
      step_id: 'PACK.KDIGO.AKI.2024.TX.05',
      display_id: 'KDIGO-AKI-TX5',
      action: 'RRT initiation',
      normalized_claim: 'Initiate RRT for: refractory hyperkalemia, severe acidosis (pH <7.1), uremic symptoms (pericarditis, encephalopathy, bleeding), refractory fluid overload, toxic ingestion (methanol, ethylene glycol).',
      timing: 'When medical management fails',
      condition: 'Life-threatening complications unresponsive to medical therapy',
      provenance: { section: 'RRT', page_or_location: 'Section 5.1' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.KDIGO.AKI.2024.RF.01',
      display_id: 'KDIGO-AKI-RF1',
      finding: 'Anuria: urine output <100 mL in 24 hours',
      implication: 'Suggests severe AKI (Stage 3) or complete obstruction. High risk of hyperkalemia and fluid overload.',
      action: 'Emergent renal US to exclude obstruction. Check K+, BGA. Prepare for possible RRT.',
      urgency: 'immediate',
      provenance: { section: 'Severe AKI', page_or_location: 'Section 5.1' },
    },
    {
      flag_id: 'PACK.KDIGO.AKI.2024.RF.02',
      display_id: 'KDIGO-AKI-RF2',
      finding: 'Rapidly rising creatinine (>0.5 mg/dL/day) with oliguria',
      implication: 'Aggressive intrinsic renal injury. Consider rhabdomyolysis, contrast nephropathy, or acute interstitial nephritis.',
      action: 'Check CK, eosinophils, urine eosinophils. Aggressive hydration if rhabdomyolysis. Stop offending drugs.',
      urgency: 'urgent',
      provenance: { section: 'Rapid Progression', page_or_location: 'Section 2.4' },
    },
    {
      flag_id: 'PACK.KDIGO.AKI.2024.RF.03',
      display_id: 'KDIGO-AKI-RF3',
      finding: 'Hyperkalemia with ECG changes: peaked T waves, widened QRS, sine wave pattern',
      implication: 'Risk of fatal arrhythmia (VF/asystole). Medical emergency.',
      action: 'IV calcium gluconate STAT, insulin + D50, continuous cardiac monitoring, prepare for RRT.',
      urgency: 'immediate',
      provenance: { section: 'Hyperkalemia', page_or_location: 'Section 4.1' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.KDIGO.AKI.2024.SEV.01',
      display_id: 'KDIGO-AKI-SV1',
      level: 'Stage 1',
      criteria: [
        'Cr increase 1.5-1.9x baseline',
        'OR Cr increase >=0.3 mg/dL within 48h',
        'OR UOP <0.5 mL/kg/h for 6-12h',
      ],
      management_implications: 'Monitor Cr and UOP closely. Optimize volume status. Avoid nephrotoxins.',
      provenance: { section: 'Staging', page_or_location: 'Section 1.1' },
    },
    {
      severity_id: 'PACK.KDIGO.AKI.2024.SEV.02',
      display_id: 'KDIGO-AKI-SV2',
      level: 'Stage 2',
      criteria: [
        'Cr increase 2.0-2.9x baseline',
        'OR UOP <0.5 mL/kg/h for >=12h',
      ],
      management_implications: 'Nephrology consultation. Assess for RRT need. Aggressive electrolyte monitoring.',
      provenance: { section: 'Staging', page_or_location: 'Section 1.1' },
    },
    {
      severity_id: 'PACK.KDIGO.AKI.2024.SEV.03',
      display_id: 'KDIGO-AKI-SV3',
      level: 'Stage 3',
      criteria: [
        'Cr increase >=3.0x baseline',
        'OR Cr >=4.0 mg/dL',
        'OR initiation of RRT',
        'OR UOP <0.3 mL/kg/h for >=24h',
        'OR anuria >=12h',
      ],
      management_implications: 'Urgent nephrology. Prepare for RRT. Monitor for life-threatening complications (hyperK, acidosis, uremia).',
      provenance: { section: 'Staging', page_or_location: 'Section 1.1' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-14',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 lightweight pack for AKI. Covers KDIGO staging, prerenal/intrinsic/postrenal differentiation, urinary indices, hyperkalemia management, and RRT indications. Evidence grounding per P4 (Jia et al. 2026).',

  all_item_ids: [
    'PACK.KDIGO.AKI.2024.REC.01', 'PACK.KDIGO.AKI.2024.REC.02', 'PACK.KDIGO.AKI.2024.REC.03',
    'PACK.KDIGO.AKI.2024.REC.04', 'PACK.KDIGO.AKI.2024.REC.05', 'PACK.KDIGO.AKI.2024.REC.06',
    'PACK.KDIGO.AKI.2024.REC.07', 'PACK.KDIGO.AKI.2024.DC.01', 'PACK.KDIGO.AKI.2024.DC.02',
    'PACK.KDIGO.AKI.2024.DC.03', 'PACK.KDIGO.AKI.2024.DC.04', 'PACK.KDIGO.AKI.2024.T.01',
    'PACK.KDIGO.AKI.2024.T.02', 'PACK.KDIGO.AKI.2024.T.03', 'PACK.KDIGO.AKI.2024.T.04',
    'PACK.KDIGO.AKI.2024.T.05', 'PACK.KDIGO.AKI.2024.TX.01', 'PACK.KDIGO.AKI.2024.TX.02',
    'PACK.KDIGO.AKI.2024.TX.03', 'PACK.KDIGO.AKI.2024.TX.04', 'PACK.KDIGO.AKI.2024.TX.05',
    'PACK.KDIGO.AKI.2024.RF.01', 'PACK.KDIGO.AKI.2024.RF.02', 'PACK.KDIGO.AKI.2024.RF.03',
    'PACK.KDIGO.AKI.2024.SEV.01', 'PACK.KDIGO.AKI.2024.SEV.02', 'PACK.KDIGO.AKI.2024.SEV.03',
  ],
  all_display_ids: [
    'KDIGO-AKI-R1', 'KDIGO-AKI-R2', 'KDIGO-AKI-R3', 'KDIGO-AKI-R4', 'KDIGO-AKI-R5', 'KDIGO-AKI-R6', 'KDIGO-AKI-R7',
    'KDIGO-AKI-DC1', 'KDIGO-AKI-DC2', 'KDIGO-AKI-DC3', 'KDIGO-AKI-DC4',
    'KDIGO-AKI-T1', 'KDIGO-AKI-T2', 'KDIGO-AKI-T3', 'KDIGO-AKI-T4', 'KDIGO-AKI-T5',
    'KDIGO-AKI-TX1', 'KDIGO-AKI-TX2', 'KDIGO-AKI-TX3', 'KDIGO-AKI-TX4', 'KDIGO-AKI-TX5',
    'KDIGO-AKI-RF1', 'KDIGO-AKI-RF2', 'KDIGO-AKI-RF3',
    'KDIGO-AKI-SV1', 'KDIGO-AKI-SV2', 'KDIGO-AKI-SV3',
  ],
};
