import type { SourcePack } from './types';

export const PACK_KDIGO_GN_2021: SourcePack = {
  source_pack_id: 'PACK.KDIGO.GN.2021',
  source_name: 'KDIGO 2021 Clinical Practice Guideline for the Management of Glomerular Diseases',
  canonical_url: 'https://kdigo.org/guidelines/gn/',
  publication_year: 2021,
  guideline_body: 'KDIGO',

  topic_tags: ['Glomerulonephritis', 'Nephrotic Syndrome', 'Nephritic Syndrome', 'IgA Nephropathy', 'Membranous Nephropathy', 'FSGS', 'MCD', 'RPGN', 'Nephrology'],
  allowed_decision_scopes: [
    'nephrotic vs nephritic syndrome classification',
    'nephrotic syndrome workup by histology',
    'nephritic syndrome workup and complement levels',
    'MCD treatment with steroids',
    'membranous nephropathy PLA2R-guided therapy',
    'IgA nephropathy management',
    'RPGN/crescentic GN emergency treatment',
    'ANCA and anti-GBM disease management',
    'lupus nephritis classification and treatment',
  ],
  excluded_decision_scopes: [
    'diabetic nephropathy management',
    'dialysis initiation criteria',
    'kidney transplant immunosuppression',
    'polycystic kidney disease',
    'tubulointerstitial nephritis',
  ],

  recommendations: [
    {
      rec_id: 'PACK.KDIGO.GN.2021.REC.01',
      display_id: 'KDIGO-GN-R1',
      statement: 'Minimal change disease in adults should be treated with high-dose prednisone (1mg/kg/day, max 80mg) for a minimum of 4 weeks, with taper over 6 months after achieving remission.',
      normalized_claim: 'MCD treatment: prednisone 1mg/kg/day (max 80mg) for >=4 weeks, then taper over 6 months. >90% response rate in adults.',
      strength: 'strong',
      evidence_quality: 'moderate',
      context: 'Adult MCD; children have even higher steroid response rates',
      provenance: { section: 'Minimal Change Disease', page_or_location: 'Section 3.1' },
    },
    {
      rec_id: 'PACK.KDIGO.GN.2021.REC.02',
      display_id: 'KDIGO-GN-R2',
      statement: 'In primary membranous nephropathy, anti-PLA2R antibody testing should guide treatment decisions. Rituximab is recommended as first-line immunosuppressive therapy for PLA2R-positive MN with persistent nephrotic-range proteinuria despite 6 months of supportive care.',
      normalized_claim: 'Membranous nephropathy: anti-PLA2R antibody guides therapy. Rituximab is first-line immunosuppression for PLA2R+ MN with persistent nephrotic proteinuria.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      provenance: { section: 'Membranous Nephropathy', page_or_location: 'Section 4.1' },
    },
    {
      rec_id: 'PACK.KDIGO.GN.2021.REC.03',
      display_id: 'KDIGO-GN-R3',
      statement: 'IgA nephropathy management should begin with optimized supportive care: maximum tolerated ACEi/ARB, blood pressure target <120/75 mmHg, and sodium restriction. Immunosuppression considered for persistent proteinuria >0.75-1 g/day despite 3-6 months of optimized supportive care.',
      normalized_claim: 'IgA nephropathy: ACEi/ARB first, BP <120/75, sodium restriction. Immunosuppression if proteinuria >0.75-1g/day persists despite 3-6 months supportive care.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'IgA Nephropathy', page_or_location: 'Section 5.1' },
    },
    {
      rec_id: 'PACK.KDIGO.GN.2021.REC.04',
      display_id: 'KDIGO-GN-R4',
      statement: 'ANCA-associated vasculitis with RPGN should be treated with pulse IV methylprednisolone (500-1000mg daily x 3 days) followed by oral prednisone plus cyclophosphamide or rituximab as induction therapy.',
      normalized_claim: 'ANCA vasculitis with RPGN: pulse methylprednisolone + cyclophosphamide or rituximab for induction. Rituximab non-inferior to cyclophosphamide.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'ANCA-Associated Vasculitis', page_or_location: 'Section 8.1' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.KDIGO.GN.2021.DC.01',
      display_id: 'KDIGO-GN-DC1',
      name: 'Nephrotic Syndrome',
      components: [
        'Proteinuria >3.5 g/day (or UPCR >3.5 g/g)',
        'Hypoalbuminemia (<3.0 g/dL)',
        'Peripheral edema',
        'Hyperlipidemia (elevated LDL, total cholesterol)',
        'Lipiduria (oval fat bodies, Maltese crosses)',
      ],
      threshold: 'Proteinuria >3.5 g/day defines nephrotic-range',
      interpretation: 'Classic pentad. Most common causes in adults: MCD (most steroid-responsive), FSGS (most common in African Americans), membranous nephropathy (most common primary cause in white adults), diabetic nephropathy (most common overall), amyloidosis in elderly.',
      normalized_claim: 'Nephrotic syndrome = proteinuria >3.5g/day + hypoalbuminemia + edema + hyperlipidemia. Key ddx: MCD, FSGS, membranous, diabetic, amyloid.',
      provenance: { section: 'Classification', page_or_location: 'Section 1.1' },
    },
    {
      criterion_id: 'PACK.KDIGO.GN.2021.DC.02',
      display_id: 'KDIGO-GN-DC2',
      name: 'Nephritic Syndrome',
      components: [
        'Hematuria (dysmorphic RBCs, RBC casts on UA)',
        'Mild-moderate proteinuria (usually <3.5 g/day)',
        'Hypertension',
        'Oliguria and rising creatinine',
        'Periorbital/peripheral edema',
      ],
      interpretation: 'RBC casts are pathognomonic for glomerulonephritis. Key ddx by complement levels: low C3/C4 (post-strep GN, lupus nephritis, MPGN, endocarditis, cryoglobulinemia); normal complement (IgA nephropathy, ANCA vasculitis, anti-GBM, Alport).',
      normalized_claim: 'Nephritic syndrome = hematuria with RBC casts + HTN + oliguria + mild proteinuria. Complement levels differentiate causes: low C3/C4 vs normal complement.',
      provenance: { section: 'Classification', page_or_location: 'Section 1.2' },
    },
    {
      criterion_id: 'PACK.KDIGO.GN.2021.DC.03',
      display_id: 'KDIGO-GN-DC3',
      name: 'Serologic Workup for Glomerulonephritis',
      components: [
        'Complement levels (C3, C4): Low in lupus, post-strep GN, MPGN, endocarditis, cryoglobulinemia',
        'ANA and anti-dsDNA: Lupus nephritis',
        'ANCA (c-ANCA/PR3, p-ANCA/MPO): GPA, MPA, EGPA',
        'Anti-GBM antibody: Goodpasture syndrome (linear IF on biopsy)',
        'Anti-PLA2R antibody: Primary membranous nephropathy',
        'ASO titer/anti-DNase B: Post-streptococcal GN',
        'Hepatitis B/C serology: Associated GN (HBV-membranous, HCV-cryoglobulinemia)',
        'Serum/urine protein electrophoresis: Amyloidosis, light chain disease',
      ],
      interpretation: 'Serologic panel narrows differential before biopsy. ANCA + anti-GBM = double-positive disease (worst prognosis). Complement pattern helps: low C3 alone (post-strep, C3 glomerulopathy) vs low C3+C4 (lupus, cryoglobulinemia).',
      normalized_claim: 'GN serologic workup: complement, ANCA, anti-GBM, anti-PLA2R, ANA/dsDNA, ASO, hepatitis panel. Complement pattern and antibody profile narrow differential before biopsy.',
      provenance: { section: 'Diagnostic Evaluation', page_or_location: 'Table 2' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.KDIGO.GN.2021.T.01',
      display_id: 'KDIGO-GN-T1',
      parameter: 'Proteinuria for nephrotic range',
      value: '3.5',
      unit: 'g/day',
      clinical_meaning: 'Proteinuria >3.5 g/day (or spot UPCR >3.5 g/g) defines nephrotic-range proteinuria and indicates glomerular pathology requiring biopsy in most adults.',
      normalized_claim: 'Proteinuria >3.5 g/day = nephrotic range; warrants kidney biopsy in most adults.',
      direction: 'above',
      provenance: { section: 'Definitions', page_or_location: 'Section 1.1' },
    },
    {
      threshold_id: 'PACK.KDIGO.GN.2021.T.02',
      display_id: 'KDIGO-GN-T2',
      parameter: 'IgA nephropathy proteinuria for immunosuppression',
      value: '0.75',
      unit: 'g/day',
      clinical_meaning: 'Persistent proteinuria >0.75-1 g/day despite 3-6 months of optimized ACEi/ARB and BP control is the threshold for considering immunosuppression in IgA nephropathy.',
      normalized_claim: 'IgA nephropathy: proteinuria >0.75-1g/day despite optimized supportive care triggers immunosuppression consideration.',
      direction: 'above',
      provenance: { section: 'IgA Nephropathy', page_or_location: 'Section 5.1' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.KDIGO.GN.2021.TX.01',
      display_id: 'KDIGO-GN-TX1',
      action: 'MCD: High-dose corticosteroids',
      normalized_claim: 'MCD: prednisone 1mg/kg/day (max 80mg) for >=4 weeks until remission, then taper over 6 months. For frequently relapsing/steroid-dependent: cyclophosphamide, calcineurin inhibitors, or rituximab.',
      timing: 'At biopsy-confirmed diagnosis',
      condition: 'Biopsy-proven minimal change disease',
      drug_details: { drug: 'Prednisone', dose: '1mg/kg/day (max 80mg)', route: 'PO', duration: '4+ weeks, then 6-month taper' },
      contraindications: ['Uncontrolled diabetes (relative)', 'Active infection'],
      escalation: 'Frequently relapsing: cyclophosphamide 2mg/kg x 8-12 weeks, or rituximab, or calcineurin inhibitor',
      provenance: { section: 'MCD Treatment', page_or_location: 'Section 3.1' },
    },
    {
      step_id: 'PACK.KDIGO.GN.2021.TX.02',
      display_id: 'KDIGO-GN-TX2',
      action: 'RPGN/crescentic GN: Pulse steroids + induction immunosuppression',
      normalized_claim: 'RPGN: IV methylprednisolone 500-1000mg daily x 3 days, then oral prednisone + cyclophosphamide or rituximab. Plasmapheresis for anti-GBM disease or severe pulmonary hemorrhage.',
      timing: 'Emergency — treat immediately, do not wait for biopsy results if clinical picture clear',
      condition: 'Rapidly progressive glomerulonephritis (doubling creatinine over days-weeks with active sediment)',
      drug_details: { drug: 'Methylprednisolone', dose: '500-1000mg IV daily x 3 days', route: 'IV' },
      escalation: 'Add plasmapheresis for anti-GBM disease or dialysis-dependent ANCA vasculitis',
      provenance: { section: 'RPGN Management', page_or_location: 'Section 8.1' },
    },
    {
      step_id: 'PACK.KDIGO.GN.2021.TX.03',
      display_id: 'KDIGO-GN-TX3',
      action: 'IgA nephropathy: Optimized supportive care first',
      normalized_claim: 'IgA nephropathy first-line: ACEi/ARB titrated to max tolerated dose, BP target <120/75, dietary sodium <2g/day. Immunosuppression only if proteinuria persists >0.75-1g/day after 3-6 months.',
      timing: 'At diagnosis',
      condition: 'Biopsy-proven IgA nephropathy',
      drug_details: { drug: 'ACEi or ARB', dose: 'Max tolerated dose', route: 'PO' },
      provenance: { section: 'IgA Nephropathy', page_or_location: 'Section 5.1' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.KDIGO.GN.2021.RF.01',
      display_id: 'KDIGO-GN-RF1',
      finding: 'Rapidly progressive glomerulonephritis: creatinine doubling over days to weeks with active urine sediment (RBC casts, dysmorphic RBCs), oliguria, and often pulmonary symptoms (hemoptysis in Goodpasture/ANCA vasculitis)',
      implication: 'Crescentic GN on biopsy. Without treatment, progresses to ESRD in weeks. Three main causes: ANCA vasculitis (pauci-immune), anti-GBM (linear), immune complex (granular).',
      action: 'Emergent serologies (ANCA, anti-GBM, complement, ANA). Start pulse methylprednisolone immediately. Kidney biopsy urgently. Plasmapheresis if anti-GBM or severe pulmonary hemorrhage.',
      urgency: 'immediate',
      provenance: { section: 'RPGN', page_or_location: 'Section 8.1' },
    },
    {
      flag_id: 'PACK.KDIGO.GN.2021.RF.02',
      display_id: 'KDIGO-GN-RF2',
      finding: 'Nephrotic syndrome with sudden flank pain, hematuria, and acute kidney injury suggesting renal vein thrombosis',
      implication: 'Nephrotic syndrome creates hypercoagulable state (loss of antithrombin III, protein C/S). Membranous nephropathy has highest thrombotic risk among nephrotic causes.',
      action: 'CT venography or Doppler US. Anticoagulation with heparin then warfarin. Treat underlying nephrotic syndrome.',
      urgency: 'urgent',
      provenance: { section: 'Complications of Nephrotic Syndrome', page_or_location: 'Section 2.3' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.KDIGO.GN.2021.SEV.01',
      display_id: 'KDIGO-GN-SEV1',
      level: 'RPGN / Crescentic glomerulonephritis',
      criteria: [
        'Rapid decline in GFR (creatinine doubling in days to weeks)',
        'Active urine sediment with RBC casts',
        'Crescents on kidney biopsy (>50% of glomeruli)',
        'Often accompanied by systemic vasculitis features (rash, pulmonary hemorrhage, neuropathy)',
      ],
      management_implications:
        'Renal emergency. Pulse methylprednisolone + induction immunosuppression (cyclophosphamide or rituximab). Plasmapheresis for anti-GBM or severe alveolar hemorrhage. Prognosis depends on percentage of crescents and initial creatinine. Dialysis-dependent at presentation = poor renal prognosis.',
      provenance: { section: 'RPGN Classification', page_or_location: 'Section 8.1' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for glomerulonephritis. Covers nephrotic/nephritic classification, serologic workup, MCD, membranous, IgA, and RPGN/crescentic GN management.',

  all_item_ids: [
    'PACK.KDIGO.GN.2021.REC.01', 'PACK.KDIGO.GN.2021.REC.02', 'PACK.KDIGO.GN.2021.REC.03',
    'PACK.KDIGO.GN.2021.REC.04',
    'PACK.KDIGO.GN.2021.DC.01', 'PACK.KDIGO.GN.2021.DC.02', 'PACK.KDIGO.GN.2021.DC.03',
    'PACK.KDIGO.GN.2021.T.01', 'PACK.KDIGO.GN.2021.T.02',
    'PACK.KDIGO.GN.2021.TX.01', 'PACK.KDIGO.GN.2021.TX.02', 'PACK.KDIGO.GN.2021.TX.03',
    'PACK.KDIGO.GN.2021.RF.01', 'PACK.KDIGO.GN.2021.RF.02',
    'PACK.KDIGO.GN.2021.SEV.01',
  ],
  all_display_ids: [
    'KDIGO-GN-R1', 'KDIGO-GN-R2', 'KDIGO-GN-R3', 'KDIGO-GN-R4',
    'KDIGO-GN-DC1', 'KDIGO-GN-DC2', 'KDIGO-GN-DC3',
    'KDIGO-GN-T1', 'KDIGO-GN-T2',
    'KDIGO-GN-TX1', 'KDIGO-GN-TX2', 'KDIGO-GN-TX3',
    'KDIGO-GN-RF1', 'KDIGO-GN-RF2',
    'KDIGO-GN-SEV1',
  ],
};
