import type { SourcePack } from './types';

export const PACK_KDIGO_CKD_2024: SourcePack = {
  source_pack_id: 'PACK.KDIGO.CKD.2024',
  source_name: 'KDIGO 2024 Clinical Practice Guideline for the Evaluation and Management of Chronic Kidney Disease',
  source_registry_id: 'REG.KDIGO.CKD',
  canonical_url: 'https://kdigo.org/guidelines/ckd-evaluation-and-management/',
  publication_year: 2024,
  guideline_body: 'KDIGO',

  topic_tags: ['Chronic Kidney Disease', 'CKD', 'Nephrology', 'Dialysis', 'Proteinuria', 'SGLT2 Inhibitor', 'Anemia of CKD', 'CKD-MBD'],
  allowed_decision_scopes: [
    'CKD staging by GFR and albuminuria',
    'ACEi/ARB for CKD with proteinuria',
    'SGLT2 inhibitor indications in CKD',
    'finerenone in diabetic kidney disease',
    'anemia management in CKD (iron, ESA)',
    'CKD-mineral bone disease management',
    'dialysis initiation indications',
    'blood pressure targets in CKD',
  ],
  excluded_decision_scopes: [
    'acute kidney injury management',
    'glomerulonephritis-specific immunosuppression',
    'kidney transplantation evaluation',
    'dialysis modality selection details (HD vs PD)',
    'polycystic kidney disease specific therapy',
  ],

  recommendations: [
    {
      rec_id: 'PACK.KDIGO.CKD.2024.REC.01',
      display_id: 'KDIGO-CKD-R1',
      statement: 'ACE inhibitor or ARB therapy is recommended for patients with CKD and severely increased albuminuria (A3: UACR >300 mg/g) with or without diabetes, titrated to maximum tolerated dose.',
      normalized_claim: 'CKD with UACR >300mg/g: ACEi or ARB at maximum tolerated dose, regardless of diabetes status.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Renin-Angiotensin System Blockade', page_or_location: 'Section 3.1' },
    },
    {
      rec_id: 'PACK.KDIGO.CKD.2024.REC.02',
      display_id: 'KDIGO-CKD-R2',
      statement: 'SGLT2 inhibitors are recommended for patients with CKD and eGFR >=20 mL/min/1.73m2 with UACR >=200 mg/g, or with type 2 diabetes and eGFR >=20 with any albuminuria, to reduce CKD progression and cardiovascular events.',
      normalized_claim: 'SGLT2i (dapagliflozin, empagliflozin) recommended for CKD with eGFR >=20 + UACR >=200, or T2DM with CKD, to slow progression.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'SGLT2 Inhibitors', page_or_location: 'Section 3.2' },
    },
    {
      rec_id: 'PACK.KDIGO.CKD.2024.REC.03',
      display_id: 'KDIGO-CKD-R3',
      statement: 'Finerenone is recommended for patients with type 2 diabetes, eGFR >=25, and UACR >=30 mg/g on maximally tolerated ACEi/ARB to reduce CKD progression and cardiovascular events.',
      normalized_claim: 'Finerenone for T2DM + CKD (eGFR >=25, UACR >=30) on max ACEi/ARB: reduces kidney and CV events. Monitor potassium.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Mineralocorticoid Receptor Antagonists', page_or_location: 'Section 3.3' },
    },
    {
      rec_id: 'PACK.KDIGO.CKD.2024.REC.04',
      display_id: 'KDIGO-CKD-R4',
      statement: 'In patients with CKD and anemia (Hb <10 g/dL), iron deficiency should be corrected before or alongside initiation of erythropoiesis-stimulating agents (ESAs). Target TSAT >20% and ferritin >100 ng/mL for non-dialysis CKD.',
      normalized_claim: 'CKD anemia: correct iron first (TSAT >20%, ferritin >100). ESA if Hb <10 after iron repletion. Do not target Hb >13.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Anemia Management', page_or_location: 'Section 4.1' },
    },
    {
      rec_id: 'PACK.KDIGO.CKD.2024.REC.05',
      display_id: 'KDIGO-CKD-R5',
      statement: 'Blood pressure target of <120 mmHg systolic is recommended for most CKD patients (using standardized office measurement), as tolerated.',
      normalized_claim: 'CKD blood pressure target: SBP <120mmHg (standardized measurement) when tolerated. Reduces CV events and CKD progression.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      provenance: { section: 'Blood Pressure Management', page_or_location: 'Section 2.1' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.KDIGO.CKD.2024.DC.01',
      display_id: 'KDIGO-CKD-DC1',
      name: 'CKD Staging by GFR (G stages) and Albuminuria (A stages)',
      components: [
        'G1: GFR >=90 mL/min/1.73m2 (normal or high)',
        'G2: GFR 60-89 (mildly decreased)',
        'G3a: GFR 45-59 (mildly to moderately decreased)',
        'G3b: GFR 30-44 (moderately to severely decreased)',
        'G4: GFR 15-29 (severely decreased)',
        'G5: GFR <15 (kidney failure)',
        'A1: UACR <30 mg/g (normal to mildly increased)',
        'A2: UACR 30-300 mg/g (moderately increased, formerly microalbuminuria)',
        'A3: UACR >300 mg/g (severely increased, formerly macroalbuminuria)',
      ],
      threshold: 'CKD defined as GFR <60 and/or UACR >=30 for >=3 months',
      interpretation: 'CKD is classified by both GFR category (G1-G5) and albuminuria category (A1-A3). Both independently predict progression, cardiovascular risk, and mortality. Higher G stage + higher A stage = worse prognosis.',
      normalized_claim: 'CKD staging: GFR G1-G5 + albuminuria A1-A3. CKD = GFR <60 or UACR >=30 for >=3 months. Both axes predict progression and CV risk.',
      provenance: { section: 'Definition and Classification', page_or_location: 'Table 1' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.KDIGO.CKD.2024.T.01',
      display_id: 'KDIGO-CKD-T1',
      parameter: 'eGFR for CKD definition',
      value: '60',
      unit: 'mL/min/1.73m2',
      clinical_meaning: 'eGFR <60 for >=3 months defines CKD even without albuminuria or structural abnormality. Corresponds to loss of approximately half of normal kidney function.',
      normalized_claim: 'eGFR <60 mL/min for >=3 months = CKD (G3a or worse).',
      direction: 'below',
      provenance: { section: 'Definition', page_or_location: 'Section 1.1' },
    },
    {
      threshold_id: 'PACK.KDIGO.CKD.2024.T.02',
      display_id: 'KDIGO-CKD-T2',
      parameter: 'UACR for moderately increased albuminuria (A2)',
      value: '30',
      unit: 'mg/g',
      clinical_meaning: 'UACR >=30 mg/g defines moderately increased albuminuria and is sufficient for CKD diagnosis even with normal GFR. Marker of glomerular injury.',
      normalized_claim: 'UACR >=30mg/g = moderately increased albuminuria (A2); sufficient for CKD diagnosis with normal GFR.',
      direction: 'above',
      provenance: { section: 'Albuminuria', page_or_location: 'Section 1.2' },
    },
    {
      threshold_id: 'PACK.KDIGO.CKD.2024.T.03',
      display_id: 'KDIGO-CKD-T3',
      parameter: 'Hemoglobin for CKD anemia workup',
      value: '10',
      unit: 'g/dL',
      clinical_meaning: 'Hb <10 g/dL in CKD triggers evaluation for iron deficiency and consideration of ESA therapy. Do not target Hb >13 g/dL with ESA (increased cardiovascular risk).',
      normalized_claim: 'CKD anemia: evaluate when Hb <10g/dL. ESA target Hb 10-11.5g/dL; do not exceed 13g/dL (CV risk).',
      direction: 'below',
      provenance: { section: 'Anemia', page_or_location: 'Section 4.1' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.KDIGO.CKD.2024.TX.01',
      display_id: 'KDIGO-CKD-TX1',
      action: 'First-line: ACEi/ARB for CKD with proteinuria',
      normalized_claim: 'CKD with UACR >=30: start ACEi or ARB, titrate to maximum tolerated dose. Monitor creatinine and potassium within 2-4 weeks.',
      timing: 'At CKD diagnosis with albuminuria',
      condition: 'CKD with UACR >=30 mg/g (A2 or A3)',
      drug_details: { drug: 'Lisinopril (or equivalent ACEi/ARB)', dose: 'Titrate to max tolerated', route: 'PO' },
      contraindications: ['Pregnancy', 'Bilateral renal artery stenosis', 'Hyperkalemia >5.5 mEq/L'],
      escalation: 'Add SGLT2i if eGFR >=20 and UACR >=200',
      provenance: { section: 'RAAS Blockade', page_or_location: 'Section 3.1' },
    },
    {
      step_id: 'PACK.KDIGO.CKD.2024.TX.02',
      display_id: 'KDIGO-CKD-TX2',
      action: 'Add SGLT2 inhibitor for CKD progression reduction',
      normalized_claim: 'Add SGLT2i (dapagliflozin or empagliflozin) to ACEi/ARB for CKD with eGFR >=20 + UACR >=200 (or T2DM with CKD). Initial eGFR dip of 10-30% is expected and acceptable.',
      timing: 'After ACEi/ARB optimization',
      condition: 'CKD with eGFR >=20 + significant proteinuria OR T2DM with CKD',
      drug_details: { drug: 'Dapagliflozin', dose: '10mg daily', route: 'PO' },
      contraindications: ['Type 1 diabetes', 'Recurrent UTI/genital mycotic infections (relative)'],
      provenance: { section: 'SGLT2 Inhibitors', page_or_location: 'Section 3.2' },
    },
    {
      step_id: 'PACK.KDIGO.CKD.2024.TX.03',
      display_id: 'KDIGO-CKD-TX3',
      action: 'Initiate dialysis for ESKD with indications',
      normalized_claim: 'Dialysis indicated for: uremic symptoms (encephalopathy, pericarditis, nausea/vomiting), refractory hyperkalemia, refractory metabolic acidosis, refractory volume overload, or eGFR <5-10 with progressive decline.',
      timing: 'When symptomatic ESKD develops or absolute indications present',
      condition: 'End-stage kidney disease (GFR <15) with symptoms or refractory complications',
      escalation: 'Kidney transplant evaluation for eligible patients',
      provenance: { section: 'Kidney Replacement Therapy', page_or_location: 'Section 5' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.KDIGO.CKD.2024.RF.01',
      display_id: 'KDIGO-CKD-RF1',
      finding: 'Rapid eGFR decline >5 mL/min/1.73m2 per year or sudden drop in eGFR',
      implication: 'Suggests superimposed AKI, new obstruction, renal artery stenosis, glomerulonephritis flare, or medication nephrotoxicity. Normal CKD progression is 1-2 mL/min/year.',
      action: 'Evaluate for reversible causes: urinalysis, renal ultrasound, review nephrotoxins (NSAIDs, contrast). Nephrology referral if not already established.',
      urgency: 'urgent',
      provenance: { section: 'CKD Progression', page_or_location: 'Section 2.3' },
    },
    {
      flag_id: 'PACK.KDIGO.CKD.2024.RF.02',
      display_id: 'KDIGO-CKD-RF2',
      finding: 'Uremic symptoms in advanced CKD: encephalopathy, asterixis, pericardial friction rub, intractable nausea/vomiting, or uremic frost',
      implication: 'Life-threatening uremic complications requiring emergent dialysis. Uremic pericarditis and encephalopathy are absolute indications for dialysis.',
      action: 'Emergent dialysis initiation. Temporary dialysis catheter placement if no permanent access.',
      urgency: 'immediate',
      provenance: { section: 'Dialysis Indications', page_or_location: 'Section 5.1' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.KDIGO.CKD.2024.SEV.01',
      display_id: 'KDIGO-CKD-SEV1',
      level: 'CKD G3-G4 (moderate to severe)',
      criteria: [
        'eGFR 15-59 mL/min/1.73m2',
        'May have complications: anemia, hyperphosphatemia, secondary hyperparathyroidism, metabolic acidosis',
        'Increased cardiovascular risk',
      ],
      management_implications:
        'Nephrology referral recommended (especially G4). Maximize RAAS blockade + SGLT2i if eligible. Monitor for anemia, bone mineral disease. Prepare for kidney replacement therapy if progressive. Avoid nephrotoxins. Adjust renally-cleared medications.',
      provenance: { section: 'CKD Management by Stage', page_or_location: 'Section 2' },
    },
    {
      severity_id: 'PACK.KDIGO.CKD.2024.SEV.02',
      display_id: 'KDIGO-CKD-SEV2',
      level: 'CKD G5 / ESKD (kidney failure)',
      criteria: [
        'eGFR <15 mL/min/1.73m2',
        'Accumulation of uremic toxins',
        'Unable to maintain fluid, electrolyte, and acid-base homeostasis',
        'May have uremic symptoms or remain asymptomatic',
      ],
      management_implications:
        'Prepare for kidney replacement therapy (dialysis or transplant). Vascular access planning (AV fistula preferred, create 6 months before anticipated dialysis). Absolute dialysis indications: uremic pericarditis, encephalopathy, refractory hyperkalemia/acidosis/volume overload.',
      provenance: { section: 'Kidney Replacement Therapy', page_or_location: 'Section 5' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for CKD. Covers staging (GFR + albuminuria), progression management (ACEi/ARB, SGLT2i, finerenone), anemia, and dialysis indications.',

  all_item_ids: [
    'PACK.KDIGO.CKD.2024.REC.01', 'PACK.KDIGO.CKD.2024.REC.02', 'PACK.KDIGO.CKD.2024.REC.03',
    'PACK.KDIGO.CKD.2024.REC.04', 'PACK.KDIGO.CKD.2024.REC.05',
    'PACK.KDIGO.CKD.2024.DC.01',
    'PACK.KDIGO.CKD.2024.T.01', 'PACK.KDIGO.CKD.2024.T.02', 'PACK.KDIGO.CKD.2024.T.03',
    'PACK.KDIGO.CKD.2024.TX.01', 'PACK.KDIGO.CKD.2024.TX.02', 'PACK.KDIGO.CKD.2024.TX.03',
    'PACK.KDIGO.CKD.2024.RF.01', 'PACK.KDIGO.CKD.2024.RF.02',
    'PACK.KDIGO.CKD.2024.SEV.01', 'PACK.KDIGO.CKD.2024.SEV.02',
  ],
  all_display_ids: [
    'KDIGO-CKD-R1', 'KDIGO-CKD-R2', 'KDIGO-CKD-R3', 'KDIGO-CKD-R4', 'KDIGO-CKD-R5',
    'KDIGO-CKD-DC1',
    'KDIGO-CKD-T1', 'KDIGO-CKD-T2', 'KDIGO-CKD-T3',
    'KDIGO-CKD-TX1', 'KDIGO-CKD-TX2', 'KDIGO-CKD-TX3',
    'KDIGO-CKD-RF1', 'KDIGO-CKD-RF2',
    'KDIGO-CKD-SEV1', 'KDIGO-CKD-SEV2',
  ],
};
