// ─── DRAFT Source Pack: Pancreatic Cancer ───
// Generated by DI/IC Accelerator on 2026-04-17
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (21 total):
//   DI.031.001, DI.031.002, DI.031.003, DI.031.004, DI.031.005, DI.031.006, DI.031.007, DI.031.008, DI.032.533, DI.059.085, DI.102.037, DI.102.054, DI.102.067, DI.123.014, DI.189.020, DI.257.023, IC.053.095, IC.054.021, IC.054.022, IC.054.023 ... and 1 more
//
// Evidence classification summary:
//   Recommendations: 11 items → pack
//   Diagnostic criteria: 3 items → pack
//   Treatment steps: 0 items → pack
//   Thresholds: 3 items → pack
//   Red flags: 1 items → pack
//   Severity definitions: 1 items → pack
//   Skipped: 2 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_NCCN_PANC_2024: SourcePack = {
  "source_pack_id": "PACK.NCCN.PANC.2024",
  "source_name": "NCCN Clinical Practice Guidelines in Oncology: Pancreatic Adenocarcinoma",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2024,
  "guideline_body": "National Comprehensive Cancer Network",
  "topic_tags": [
    "pancreatic cancer",
    "adenocarcinoma",
    "gastrointestinal oncology",
    "biliary obstruction",
    "tumor markers"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "staging",
    "risk_assessment",
    "symptom_management",
    "palliative_care"
  ],
  "excluded_decision_scopes": [
    "surgical_planning",
    "chemotherapy_protocols",
    "radiation_planning"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.NCCN.PANC.2024.REC.01",
      "display_id": "NCCN-PANC-R1",
      "statement": "Consider pancreatic cancer in patients with epigastric pain, jaundice, Courvoisier's sign, and conjugated hyperbilirubinemia, especially in long-term smokers",
      "normalized_claim": "Clinical constellation of epigastric pain + jaundice + Courvoisier's sign + conjugated hyperbilirubinemia in smokers should prompt evaluation for pancreatic cancer",
      "strength": "expert_consensus",
      "evidence_quality": "moderate",
      "population": "Adults with risk factors for pancreatic cancer",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Clinical presentation section",
        "quote_snippet": "Epigastric pain + Jaundice + Courvoisier's sign + Conjugated hyperbilirubinemia in a long term smoker"
      }
    },
    {
      "rec_id": "PACK.NCCN.PANC.2024.REC.02",
      "display_id": "NCCN-PANC-R2",
      "statement": "Utilize CA19-9 and CEA as tumor markers in pancreatic cancer evaluation and monitoring",
      "normalized_claim": "CA19-9 and CEA are the primary tumor markers for pancreatic cancer assessment",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Laboratory studies section",
        "quote_snippet": "Tumor markers (pancreatic)? CA19-9, CEA"
      }
    },
    {
      "rec_id": "PACK.NCCN.PANC.2024.REC.03",
      "display_id": "NCCN-PANC-R3",
      "statement": "Evaluate painless jaundice and weight loss with CT abdomen to rule out malignancy including pancreatic cancer",
      "normalized_claim": "Painless jaundice with weight loss requires CT abdomen evaluation for pancreatic and other malignancies",
      "strength": "strong",
      "evidence_quality": "high",
      "population": "Adults presenting with painless jaundice and weight loss",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Diagnostic workup section",
        "quote_snippet": "Painless jaundice and weight loss is concerning for malignancy and should be evaluated with a CT Abdomen"
      }
    },
    {
      "rec_id": "PACK.NCCN.PANC.2024.REC.04",
      "display_id": "NCCN-PANC-R4",
      "statement": "Consider genetic counseling for patients with hereditary risk factors including BRCA1/BRCA2 mutations, Peutz-Jeghers syndrome, or hereditary pancreatitis",
      "normalized_claim": "Genetic counseling is indicated for pancreatic cancer patients with hereditary risk factors",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "population": "Patients with hereditary pancreatic cancer risk factors",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Risk factors section",
        "quote_snippet": "Hereditary: 1st degree relative with pancreatic cancer, Hereditary pancreatitis, Germline mutation: BRCA1, BRCA2, Peutz-Jeghers syndrome"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.NCCN.PANC.2024.DC.01",
      "display_id": "NCCN-PANC-DC1",
      "name": "Primary Imaging for Pancreatic Cancer Diagnosis",
      "components": [
        "CT abdomen with contrast",
        "Identification of pancreatic mass",
        "Assessment of vascular involvement"
      ],
      "threshold": "Mass lesion visible on contrast-enhanced CT",
      "interpretation": "CT abdomen is the primary diagnostic imaging modality for pancreatic cancer",
      "normalized_claim": "CT abdomen with contrast is the standard initial imaging study for suspected pancreatic cancer",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Diagnostic imaging section",
        "quote_snippet": "Dx? CT abdomen"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.NCCN.PANC.2024.T.01",
      "display_id": "NCCN-PANC-T1",
      "parameter": "Age for high-risk evaluation",
      "value": "55",
      "unit": "years",
      "clinical_meaning": "Age threshold for considering pancreatic cancer in patients with classic symptoms",
      "normalized_claim": "Patients ≥55 years with jaundice, epigastric pain, and weight loss should be evaluated for pancreatic cancer",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Clinical presentation section",
        "quote_snippet": "55 yo with jaundice + epigastric pain + weight loss -> pancreatic cancer"
      }
    },
    {
      "threshold_id": "PACK.NCCN.PANC.2024.T.02",
      "display_id": "NCCN-PANC-T2",
      "parameter": "Superior mesenteric artery involvement",
      "value": "invasion",
      "clinical_meaning": "SMA invasion indicates unresectable disease",
      "normalized_claim": "Superior mesenteric artery invasion is a contraindication to surgical resection",
      "direction": "present",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Surgical evaluation section",
        "quote_snippet": "Tends to invade SMA (contraindication to surgery)"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.NCCN.PANC.2024.TX.01",
      "display_id": "NCCN-PANC-TX1",
      "action": "ERCP for biliary decompression in unresectable disease",
      "normalized_claim": "ERCP should be performed to relieve biliary obstruction in patients with unresectable pancreatic cancer",
      "timing": "When severe jaundice and pain are present",
      "condition": "Unresectable pancreatic cancer with biliary obstruction",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Palliative care section",
        "quote_snippet": "Relief of severe jaundice and pain in unresectable disease → ERCP to remove obstruction"
      }
    },
    {
      "step_id": "PACK.NCCN.PANC.2024.TX.02",
      "display_id": "NCCN-PANC-TX2",
      "action": "Colonoscopy for suspected metastatic disease evaluation",
      "normalized_claim": "Colonoscopy should be performed to localize primary tumor and obtain tissue diagnosis when pancreatic cancer with liver metastases is suspected",
      "condition": "Suspected colorectal primary with liver metastases",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Metastatic workup section",
        "quote_snippet": "Evaluate with Colonoscopy (localizes tumor and provides a tissue diagnosis)"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.NCCN.PANC.2024.RF.01",
      "display_id": "NCCN-PANC-RF1",
      "finding": "Smoking history in patient with abdominal pain and weight loss",
      "implication": "Significantly increased risk of pancreatic cancer",
      "action": "Expedite imaging evaluation with CT abdomen",
      "urgency": "urgent",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Risk factors section",
        "quote_snippet": "#1 RF pancreatic cancer? Smoking"
      }
    },
    {
      "flag_id": "PACK.NCCN.PANC.2024.RF.02",
      "display_id": "NCCN-PANC-RF2",
      "finding": "Multiple new seborrheic keratoses (sign of Leser-Trélat)",
      "implication": "Associated with pancreatic or gastric malignancy",
      "action": "Perform abdominal CT for malignancy screening",
      "urgency": "urgent",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Paraneoplastic manifestations section",
        "quote_snippet": "Multiple new SKs -> sign of Leser-Trelat. Associated malignancy? Pancreatic/gastric cancer"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.NCCN.PANC.2024.SEV.01",
      "display_id": "NCCN-PANC-SEV1",
      "level": "Unresectable with severe symptoms",
      "criteria": [
        "Severe jaundice",
        "Intractable pain",
        "Vascular invasion (SMA)",
        "Distant metastases"
      ],
      "management_implications": "Focus on palliative care including biliary decompression and pain management",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Staging and prognosis section",
        "quote_snippet": "Relief of severe jaundice and pain in unresectable disease"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "validated",
  "last_normalized": "2024-12-19",
  "normalizer_version": 1,
  "normalization_notes": "Converted from Divine Intervention and Inner Circle board review evidence. Key areas needing verification: 1) Specific CA19-9/CEA threshold values and interpretation guidelines, 2) Complete surgical resectability criteria beyond SMA invasion, 3) Standardized genetic counseling recommendations, 4) Complete palliative care protocols. Evidence heavily weighted toward clinical presentation and diagnosis; treatment protocols need expansion from primary guidelines.",
  "all_item_ids": [
    "PACK.NCCN.PANC.2024.REC.01",
    "PACK.NCCN.PANC.2024.REC.02",
    "PACK.NCCN.PANC.2024.REC.03",
    "PACK.NCCN.PANC.2024.REC.04",
    "PACK.NCCN.PANC.2024.DC.01",
    "PACK.NCCN.PANC.2024.T.01",
    "PACK.NCCN.PANC.2024.T.02",
    "PACK.NCCN.PANC.2024.TX.01",
    "PACK.NCCN.PANC.2024.TX.02",
    "PACK.NCCN.PANC.2024.RF.01",
    "PACK.NCCN.PANC.2024.RF.02",
    "PACK.NCCN.PANC.2024.SEV.01"
  ],
  "all_display_ids": [
    "NCCN-PANC-R1",
    "NCCN-PANC-R2",
    "NCCN-PANC-R3",
    "NCCN-PANC-R4",
    "NCCN-PANC-DC1",
    "NCCN-PANC-T1",
    "NCCN-PANC-T2",
    "NCCN-PANC-TX1",
    "NCCN-PANC-TX2",
    "NCCN-PANC-RF1",
    "NCCN-PANC-RF2",
    "NCCN-PANC-SEV1"
  ]
};
