// ─── DRAFT Source Pack: Multiple Myeloma ───
// Generated by DI/IC Accelerator on 2026-04-17
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (26 total):
//   DI.031.740, DI.032.303, DI.032.304, DI.032.305, DI.032.306, DI.032.307, DI.032.308, DI.112.260, DI.128.001, DI.128.002, DI.128.003, DI.128.004, DI.128.005, DI.128.006, DI.128.007, DI.128.012, DI.135.058, DI.203.036, DI.203.037, DI.203.038 ... and 6 more
//
// Evidence classification summary:
//   Recommendations: 20 items → pack
//   Diagnostic criteria: 2 items → pack
//   Treatment steps: 1 items → pack
//   Thresholds: 3 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_NCCN_MM_2024: SourcePack = {
  "source_pack_id": "PACK.NCCN.MM.2024",
  "source_name": "NCCN Guidelines for Multiple Myeloma",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2024,
  "guideline_body": "NCCN",
  "topic_tags": [
    "hematology",
    "oncology",
    "plasma_cell_disorders",
    "bone_marrow",
    "paraproteinemia"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "staging",
    "treatment_selection",
    "monitoring",
    "supportive_care"
  ],
  "excluded_decision_scopes": [
    "pediatric_management",
    "pregnancy_management"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.NCCN.MM.2024.REC.01",
      "display_id": "NCCN-MM-R1",
      "statement": "Evaluate patients with suspected multiple myeloma using CRAB criteria: hypercalcemia, renal insufficiency, anemia, and bone lesions",
      "normalized_claim": "Multiple myeloma diagnosis should be evaluated using CRAB criteria (hypercalcemia, renal insufficiency, anemia, bone lesions)",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Initial diagnostic evaluation",
      "population": "Adults with suspected plasma cell disorders",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Diagnostic criteria section",
        "quote_snippet": "CRAB symptoms: C = Hypercalcemia, R = Renal insufficiency, A = Anemia, B = Bone pain"
      }
    },
    {
      "rec_id": "PACK.NCCN.MM.2024.REC.02",
      "display_id": "NCCN-MM-R2",
      "statement": "Obtain serum protein electrophoresis (SPEP) and urine protein electrophoresis (UPEP) for initial evaluation of suspected multiple myeloma",
      "normalized_claim": "SPEP and UPEP are recommended initial tests for multiple myeloma evaluation",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Initial diagnostic workup",
      "population": "Patients with suspected multiple myeloma",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Diagnostic testing section",
        "quote_snippet": "NBS: SPEP, MPEP; Dx: SPEP + UPEP"
      }
    },
    {
      "rec_id": "PACK.NCCN.MM.2024.REC.03",
      "display_id": "NCCN-MM-R3",
      "statement": "Recognize rouleaux formation on blood smear as a characteristic finding in multiple myeloma",
      "normalized_claim": "Rouleaux formation on blood smear is characteristic of multiple myeloma",
      "strength": "strong",
      "evidence_quality": "moderate",
      "context": "Laboratory evaluation",
      "population": "Patients undergoing evaluation for multiple myeloma",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Laboratory findings section",
        "quote_snippet": "Blood smear? Rouleaux formation; Histology: Rouleaux on blood smear"
      }
    },
    {
      "rec_id": "PACK.NCCN.MM.2024.REC.04",
      "display_id": "NCCN-MM-R4",
      "statement": "Consider bortezomib as a treatment option for multiple myeloma patients",
      "normalized_claim": "Bortezomib (proteasome inhibitor) is a treatment option for multiple myeloma",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Treatment selection",
      "population": "Multiple myeloma patients eligible for therapy",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Treatment protocols section",
        "quote_snippet": "Tx? Bortezomib (MOA? Proteasome inhibitor)"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.NCCN.MM.2024.DC.01",
      "display_id": "NCCN-MM-DC1",
      "name": "M-protein Detection",
      "components": [
        "Monoclonal spike (M-spike) on serum protein electrophoresis",
        "Monoclonal protein on urine protein electrophoresis"
      ],
      "interpretation": "Presence of M-protein supports multiple myeloma diagnosis",
      "normalized_claim": "M-spike on SPEP or UPEP is diagnostic for multiple myeloma",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Diagnostic criteria section",
        "quote_snippet": "Dx? M-spike on SPEP or UPEP"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.NCCN.MM.2024.T.01",
      "display_id": "NCCN-MM-T1",
      "parameter": "Bone marrow plasma cells",
      "value": "10",
      "unit": "percent",
      "clinical_meaning": "Confirmatory threshold for multiple myeloma diagnosis",
      "normalized_claim": "Bone marrow biopsy showing >10% plasma cells confirms multiple myeloma",
      "direction": "above",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Diagnostic criteria section",
        "quote_snippet": "Bone marrow bx? > 10% plasma cells"
      }
    },
    {
      "threshold_id": "PACK.NCCN.MM.2024.T.02",
      "display_id": "NCCN-MM-T2",
      "parameter": "Hemoglobin for transfusion",
      "value": "7",
      "unit": "g/dL",
      "clinical_meaning": "Transfusion threshold in multiple myeloma patients",
      "normalized_claim": "Transfusion indicated only if hemoglobin <7 g/dL in multiple myeloma",
      "direction": "below",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Supportive care section",
        "quote_snippet": "Only transfuse if Hgb < 7!"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.NCCN.MM.2024.TX.01",
      "display_id": "NCCN-MM-TX1",
      "action": "Initiate proteasome inhibitor therapy with bortezomib",
      "normalized_claim": "Bortezomib is a first-line treatment option for multiple myeloma",
      "timing": "After diagnosis confirmation",
      "condition": "Newly diagnosed or relapsed multiple myeloma",
      "drug_details": {
        "drug": "bortezomib",
        "dose": "Per protocol",
        "route": "Intravenous or subcutaneous"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Treatment protocols section",
        "quote_snippet": "Tx? Bortezomib (MOA? Proteasome inhibitor)"
      }
    },
    {
      "step_id": "PACK.NCCN.MM.2024.TX.02",
      "display_id": "NCCN-MM-TX2",
      "action": "Manage hypercalcemia with hydration, diuretics, and bisphosphonates",
      "normalized_claim": "Hypercalcemia in multiple myeloma should be managed with hydration, diuretics, then bisphosphonates",
      "timing": "When hypercalcemia is present",
      "condition": "Hypercalcemia secondary to multiple myeloma",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Supportive care section",
        "quote_snippet": "Hydration and lasix then bisphosphonate for hyperCa"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.NCCN.MM.2024.RF.01",
      "display_id": "NCCN-MM-RF1",
      "finding": "Combination of bone pain, lytic lesions, hypercalcemia, renal insufficiency, and anemia in elderly patient",
      "implication": "Highly suggestive of multiple myeloma",
      "action": "Urgent hematology evaluation and diagnostic workup including SPEP, UPEP, and bone marrow biopsy",
      "urgency": "urgent",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Clinical presentation section",
        "quote_snippet": "70 yo F with Ca2+ of 12.9 + SCr of 3 + Hb of 8 + bone pain + lytic bone lesions"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.NCCN.MM.2024.SEV.01",
      "display_id": "NCCN-MM-SEV1",
      "level": "Symptomatic Multiple Myeloma",
      "criteria": [
        "Presence of CRAB criteria (hypercalcemia, renal insufficiency, anemia, bone lesions)",
        "Bone marrow plasma cells >10%",
        "M-protein detectable on SPEP or UPEP"
      ],
      "management_implications": "Requires immediate treatment initiation with systemic therapy",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Staging and risk stratification section",
        "quote_snippet": "CRAB symptoms with bone marrow findings"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "validated",
  "last_normalized": "2024-12-19T23:48:00Z",
  "normalizer_version": 1,
  "normalization_notes": "Generated from Divine Intervention and Emma Holliday board review materials. Key items extracted: CRAB criteria, diagnostic tests (SPEP/UPEP), rouleaux formation, bortezomib treatment, bone marrow threshold >10% plasma cells, transfusion threshold <7g/dL Hgb. Missing items that need verification: staging criteria, complete treatment protocols, monitoring guidelines, prognostic factors. All claims derived from board review sources and require verification against actual NCCN guidelines before activation.",
  "all_item_ids": [
    "PACK.NCCN.MM.2024.REC.01",
    "PACK.NCCN.MM.2024.REC.02",
    "PACK.NCCN.MM.2024.REC.03",
    "PACK.NCCN.MM.2024.REC.04",
    "PACK.NCCN.MM.2024.DC.01",
    "PACK.NCCN.MM.2024.T.01",
    "PACK.NCCN.MM.2024.T.02",
    "PACK.NCCN.MM.2024.TX.01",
    "PACK.NCCN.MM.2024.TX.02",
    "PACK.NCCN.MM.2024.RF.01",
    "PACK.NCCN.MM.2024.SEV.01"
  ],
  "all_display_ids": [
    "NCCN-MM-R1",
    "NCCN-MM-R2",
    "NCCN-MM-R3",
    "NCCN-MM-R4",
    "NCCN-MM-DC1",
    "NCCN-MM-T1",
    "NCCN-MM-T2",
    "NCCN-MM-TX1",
    "NCCN-MM-TX2",
    "NCCN-MM-RF1",
    "NCCN-MM-SEV1"
  ]
};
