// ─── DRAFT Source Pack: Esophageal Cancer ───
// Generated by DI/IC Accelerator on 2026-04-17
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (14 total):
//   DI.030.559, DI.030.560, DI.030.561, DI.030.562, DI.030.563, DI.030.564, DI.030.565, DI.030.566, DI.030.567, DI.102.046, EH.003.029, IC.050.059, IC.050.060, IC.050.061
//
// Evidence classification summary:
//   Recommendations: 10 items → pack
//   Diagnostic criteria: 1 items → pack
//   Treatment steps: 0 items → pack
//   Thresholds: 2 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 1 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_NCCN_EC_2024: SourcePack = {
  "source_pack_id": "PACK.NCCN.EC.2024",
  "source_name": "NCCN Guidelines for Esophageal and Esophagogastric Junction Cancers",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2024,
  "guideline_body": "NCCN",
  "topic_tags": [
    "esophageal cancer",
    "adenocarcinoma",
    "squamous cell carcinoma",
    "Barrett's esophagus",
    "dysphagia",
    "oncology"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "staging",
    "risk_stratification",
    "screening"
  ],
  "excluded_decision_scopes": [
    "surgical_technique",
    "radiation_planning",
    "chemotherapy_protocols"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.NCCN.EC.2024.REC.01",
      "display_id": "NCCN-EC-R1",
      "statement": "Barrett's esophagus is the primary risk factor for esophageal adenocarcinoma",
      "normalized_claim": "Barrett's esophagus increases risk of esophageal adenocarcinoma",
      "strength": "expert_consensus",
      "evidence_quality": "high",
      "context": "Risk factor identification",
      "population": "All patients",
      "provenance": {
        "section": "Risk Factors",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "RF esophageal adenocarcinoma: Barrett's esophagus"
      }
    },
    {
      "rec_id": "PACK.NCCN.EC.2024.REC.02",
      "display_id": "NCCN-EC-R2",
      "statement": "Smoking, alcohol use, and achalasia are primary risk factors for esophageal squamous cell carcinoma",
      "normalized_claim": "Smoking, alcohol, and achalasia increase risk of esophageal squamous cell carcinoma",
      "strength": "expert_consensus",
      "evidence_quality": "high",
      "context": "Risk factor identification",
      "population": "All patients",
      "provenance": {
        "section": "Risk Factors",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "RF esophageal squamous cell carcinoma: Smoking, Drinking, Achalasia"
      }
    },
    {
      "rec_id": "PACK.NCCN.EC.2024.REC.03",
      "display_id": "NCCN-EC-R3",
      "statement": "Esophageal adenocarcinoma typically occurs in the lower third of the esophagus",
      "normalized_claim": "Adenocarcinoma predominantly affects lower esophagus",
      "strength": "expert_consensus",
      "evidence_quality": "high",
      "context": "Anatomical distribution",
      "population": "Patients with esophageal adenocarcinoma",
      "provenance": {
        "section": "Epidemiology",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Location esophageal adenocarcinoma: Lower 1/3"
      }
    },
    {
      "rec_id": "PACK.NCCN.EC.2024.REC.04",
      "display_id": "NCCN-EC-R4",
      "statement": "Esophageal squamous cell carcinoma typically occurs in the upper two-thirds of the esophagus",
      "normalized_claim": "Squamous cell carcinoma predominantly affects upper esophagus",
      "strength": "expert_consensus",
      "evidence_quality": "high",
      "context": "Anatomical distribution",
      "population": "Patients with esophageal squamous cell carcinoma",
      "provenance": {
        "section": "Epidemiology",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Location esophageal squamous cell carcinoma: Upper 2/3"
      }
    },
    {
      "rec_id": "PACK.NCCN.EC.2024.REC.05",
      "display_id": "NCCN-EC-R5",
      "statement": "Adenocarcinoma is the most common type of esophageal cancer in the United States",
      "normalized_claim": "Adenocarcinoma is predominant esophageal cancer type in US",
      "strength": "expert_consensus",
      "evidence_quality": "high",
      "context": "Epidemiology",
      "population": "US population",
      "provenance": {
        "section": "Epidemiology",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "MC US: Adenocarcinoma"
      }
    },
    {
      "rec_id": "PACK.NCCN.EC.2024.REC.06",
      "display_id": "NCCN-EC-R6",
      "statement": "Staging should include CT scan or esophageal ultrasound",
      "normalized_claim": "CT or EUS required for esophageal cancer staging",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Initial staging workup",
      "population": "Patients with confirmed esophageal cancer",
      "provenance": {
        "section": "Staging",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Staging: CT scan or esophageal US"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.NCCN.EC.2024.DC.01",
      "display_id": "NCCN-EC-DC1",
      "name": "Esophageal Cancer Diagnosis",
      "components": [
        "Upper endoscopy with biopsy"
      ],
      "interpretation": "Tissue diagnosis required for esophageal cancer",
      "normalized_claim": "EGD with biopsy establishes diagnosis of esophageal cancer",
      "provenance": {
        "section": "Diagnosis",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Dx: EGD"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.NCCN.EC.2024.T.01",
      "display_id": "NCCN-EC-T1",
      "parameter": "GERD duration with distal esophageal mass",
      "value": "longstanding",
      "clinical_meaning": "Suggestive of esophageal adenocarcinoma",
      "normalized_claim": "Longstanding GERD with distal esophageal mass suggests adenocarcinoma",
      "direction": "present",
      "provenance": {
        "section": "Clinical Presentation",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Pt with longstanding GERD + mass in distal esophagus -> esophageal adenocarcinoma"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.NCCN.EC.2024.TX.01",
      "display_id": "NCCN-EC-TX1",
      "action": "Perform upper endoscopy with biopsy for tissue diagnosis",
      "normalized_claim": "EGD with biopsy is first step for suspected esophageal cancer",
      "timing": "Initial evaluation",
      "condition": "Suspected esophageal cancer",
      "provenance": {
        "section": "Diagnosis",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Dx: EGD"
      }
    },
    {
      "step_id": "PACK.NCCN.EC.2024.TX.02",
      "display_id": "NCCN-EC-TX2",
      "action": "Obtain staging studies with CT scan or esophageal ultrasound",
      "normalized_claim": "CT or EUS required for staging confirmed esophageal cancer",
      "timing": "After tissue diagnosis",
      "condition": "Confirmed esophageal cancer",
      "provenance": {
        "section": "Staging",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Staging: CT scan or esophageal US"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.NCCN.EC.2024.RF.01",
      "display_id": "NCCN-EC-RF1",
      "finding": "Progressive dysphagia from solids to liquids",
      "implication": "Suggests mechanical obstruction, concerning for esophageal malignancy",
      "action": "Urgent upper endoscopy",
      "urgency": "urgent",
      "provenance": {
        "section": "Clinical Presentation",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Presentation: Dysphagia to solids → dysphagia to liquids"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.NCCN.EC.2024.SEV.01",
      "display_id": "NCCN-EC-SEV1",
      "level": "Early stage with high-risk molecular features",
      "criteria": [
        "TP53 mutation present"
      ],
      "management_implications": "May require more aggressive treatment approach",
      "provenance": {
        "section": "Molecular Markers",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "TP53 mutation early stages"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-12-19",
  "normalizer_version": 1,
  "normalization_notes": "Generated from Divine Intervention and Inner Circle board review materials. Key clinical pearls converted to structured recommendations focusing on risk factors, epidemiology, diagnosis, and staging. Limited treatment information available in source material. All claims need verification against actual NCCN guidelines before activation. Missing: detailed treatment protocols, surgical criteria, radiation planning, chemotherapy regimens.",
  "all_item_ids": [
    "PACK.NCCN.EC.2024.REC.01",
    "PACK.NCCN.EC.2024.REC.02",
    "PACK.NCCN.EC.2024.REC.03",
    "PACK.NCCN.EC.2024.REC.04",
    "PACK.NCCN.EC.2024.REC.05",
    "PACK.NCCN.EC.2024.REC.06",
    "PACK.NCCN.EC.2024.DC.01",
    "PACK.NCCN.EC.2024.T.01",
    "PACK.NCCN.EC.2024.TX.01",
    "PACK.NCCN.EC.2024.TX.02",
    "PACK.NCCN.EC.2024.RF.01",
    "PACK.NCCN.EC.2024.SEV.01"
  ],
  "all_display_ids": [
    "NCCN-EC-R1",
    "NCCN-EC-R2",
    "NCCN-EC-R3",
    "NCCN-EC-R4",
    "NCCN-EC-R5",
    "NCCN-EC-R6",
    "NCCN-EC-DC1",
    "NCCN-EC-T1",
    "NCCN-EC-TX1",
    "NCCN-EC-TX2",
    "NCCN-EC-RF1",
    "NCCN-EC-SEV1"
  ]
};
