// ─── DRAFT Source Pack: Lymphoma ───
// Generated by DI/IC Accelerator on 2026-04-16
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (95 total):
//   DI.030.449, DI.031.106, DI.031.208, DI.031.209, DI.031.210, DI.031.211, DI.031.212, DI.031.213, DI.031.214, DI.031.277, DI.031.278, DI.031.279, DI.031.280, DI.031.281, DI.031.282, DI.031.283, DI.031.284, DI.031.285, DI.031.286, DI.032.394 ... and 75 more
//
// Evidence classification summary:
//   Recommendations: 62 items → pack
//   Diagnostic criteria: 4 items → pack
//   Treatment steps: 1 items → pack
//   Thresholds: 22 items → pack
//   Red flags: 1 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 5 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_NCCN_LYMPH_2023: SourcePack = {
  "source_pack_id": "PACK.NCCN.LYMPH.2023",
  "source_name": "NCCN Guidelines for Hodgkin and Non-Hodgkin Lymphomas",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2023,
  "guideline_body": "National Comprehensive Cancer Network (NCCN)",
  "topic_tags": [
    "lymphoma",
    "hodgkin",
    "non-hodgkin",
    "oncology",
    "hematology"
  ],
  "allowed_decision_scopes": [
    "diagnosis",
    "staging",
    "treatment",
    "monitoring",
    "prognosis"
  ],
  "excluded_decision_scopes": [
    "prevention",
    "screening"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.NCCN.LYMPH.2023.REC.01",
      "display_id": "NCCN-LYMPH-R1",
      "statement": "Lymph node biopsy is required for diagnosis of lymphoma",
      "normalized_claim": "Excisional lymph node biopsy should be performed for definitive lymphoma diagnosis",
      "strength": "strong",
      "evidence_quality": "high",
      "provenance": {
        "section": "Diagnostic Workup",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Dx? LN biopsy"
      }
    },
    {
      "rec_id": "PACK.NCCN.LYMPH.2023.REC.02",
      "display_id": "NCCN-LYMPH-R2",
      "statement": "Reed-Sternberg cells on lymph node biopsy confirm Hodgkin lymphoma diagnosis",
      "normalized_claim": "Presence of Reed-Sternberg cells is diagnostic of Hodgkin lymphoma",
      "strength": "strong",
      "evidence_quality": "high",
      "provenance": {
        "section": "Pathological Diagnosis",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Reed Sternberg cells on lymph node biopsy → Hodgkin's lymphoma"
      }
    },
    {
      "rec_id": "PACK.NCCN.LYMPH.2023.REC.03",
      "display_id": "NCCN-LYMPH-R3",
      "statement": "CD15 and CD30 immunomarkers should be tested for Hodgkin lymphoma",
      "normalized_claim": "CD15+ and CD30+ immunophenotype supports Hodgkin lymphoma diagnosis",
      "strength": "strong",
      "evidence_quality": "high",
      "provenance": {
        "section": "Immunohistochemistry",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Immune markers? CD15 & CD30"
      }
    },
    {
      "rec_id": "PACK.NCCN.LYMPH.2023.REC.04",
      "display_id": "NCCN-LYMPH-R4",
      "statement": "Staging CT chest and abdomen should be performed after lymphoma diagnosis",
      "normalized_claim": "Staging imaging with CT chest and abdomen is required for treatment planning",
      "strength": "strong",
      "evidence_quality": "high",
      "provenance": {
        "section": "Staging Workup",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Next best test? -> Staging Chest/Abdominal CT or MRI"
      }
    },
    {
      "rec_id": "PACK.NCCN.LYMPH.2023.REC.05",
      "display_id": "NCCN-LYMPH-R5",
      "statement": "Bone marrow biopsy should be considered for Non-Hodgkin lymphoma staging",
      "normalized_claim": "Bone marrow biopsy is particularly important for NHL staging",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "provenance": {
        "section": "Staging Workup",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Bone marrow bx (esp for NHL)"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.NCCN.LYMPH.2023.DC.01",
      "display_id": "NCCN-LYMPH-DC1",
      "name": "Hodgkin Lymphoma Diagnosis",
      "components": [
        "Reed-Sternberg cells on lymph node biopsy",
        "CD15 positive",
        "CD30 positive"
      ],
      "interpretation": "Presence of Reed-Sternberg cells with appropriate immunophenotype confirms Hodgkin lymphoma",
      "normalized_claim": "Hodgkin lymphoma is diagnosed by Reed-Sternberg cells with CD15+/CD30+ immunophenotype",
      "provenance": {
        "section": "Pathological Diagnosis",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Reed Sternberg cells on lymph node biopsy → Hodgkin's lymphoma"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.NCCN.LYMPH.2023.T.01",
      "display_id": "NCCN-LYMPH-T1",
      "parameter": "Lymph node involvement",
      "value": "1",
      "clinical_meaning": "Stage I disease - single lymph node region involved",
      "normalized_claim": "Single lymph node region involvement defines Stage I lymphoma",
      "direction": "present",
      "provenance": {
        "section": "Staging Criteria",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "1 LN → stage 1"
      }
    },
    {
      "threshold_id": "PACK.NCCN.LYMPH.2023.T.02",
      "display_id": "NCCN-LYMPH-T2",
      "parameter": "CD4 count for CNS lymphoma prophylaxis",
      "value": "100",
      "unit": "cells/μL",
      "clinical_meaning": "Below this threshold, prophylaxis for CNS complications needed",
      "normalized_claim": "CD4 count below 100 cells/μL requires prophylaxis in immunocompromised patients",
      "direction": "below",
      "provenance": {
        "section": "Immunocompromised Management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "PPx for CD4 < 100: TMP-SMX"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.NCCN.LYMPH.2023.TX.01",
      "display_id": "NCCN-LYMPH-TX1",
      "action": "Radiation therapy for early-stage Hodgkin lymphoma",
      "normalized_claim": "Stage I-II Hodgkin lymphoma should receive radiation therapy",
      "condition": "Stage I or II Hodgkin lymphoma",
      "provenance": {
        "section": "Treatment Recommendations",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "I/II get rads"
      }
    },
    {
      "step_id": "PACK.NCCN.LYMPH.2023.TX.02",
      "display_id": "NCCN-LYMPH-TX2",
      "action": "ABVD chemotherapy for advanced-stage Hodgkin lymphoma",
      "normalized_claim": "Stage III-IV Hodgkin lymphoma should receive ABVD chemotherapy",
      "condition": "Stage III or IV Hodgkin lymphoma",
      "drug_details": {
        "drug": "ABVD (Adriamycin, Bleomycin, Vinblastine, Dacarbazine)"
      },
      "provenance": {
        "section": "Treatment Recommendations",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "III/IV get ABVD chemo"
      }
    },
    {
      "step_id": "PACK.NCCN.LYMPH.2023.TX.03",
      "display_id": "NCCN-LYMPH-TX3",
      "action": "Empiric treatment for suspected CNS lymphoma in HIV patients",
      "normalized_claim": "HIV patients with suspected CNS lymphoma should receive empiric anti-toxoplasma therapy before biopsy",
      "condition": "HIV patient with CNS mass lesions",
      "timing": "6 weeks trial",
      "drug_details": {
        "drug": "Pyrimethamine and sulfadiazine with folic acid"
      },
      "escalation": "If no improvement in 1 week, consider biopsy for CNS lymphoma",
      "provenance": {
        "section": "CNS Lymphoma Management",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Do empiric pyrimethamine sulfadiazine (+ folic acid) for 6wks. If no improvement in 1wk, consider biopsy"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.NCCN.LYMPH.2023.RF.01",
      "display_id": "NCCN-LYMPH-RF1",
      "finding": "Rapidly enlarging thyroid mass in patient with Hashimoto's thyroiditis",
      "implication": "High risk for thyroid lymphoma transformation",
      "action": "Urgent biopsy and oncology referral",
      "urgency": "urgent",
      "provenance": {
        "section": "Thyroid Lymphoma",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Hx Hashimoto's + rapidly enlarging thyroid → thyroid lymphoma"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.NCCN.LYMPH.2023.SEV.01",
      "display_id": "NCCN-LYMPH-SEV1",
      "level": "Lymphocyte predominant Hodgkin lymphoma",
      "criteria": [
        "High proportion of lymphocytes relative to Reed-Sternberg cells"
      ],
      "management_implications": "Best prognosis among Hodgkin lymphoma subtypes",
      "provenance": {
        "section": "Histological Subtypes",
        "page_or_location": "DI/IC-derived, verify against guideline",
        "quote_snippet": "Lymphocyte predominant - best prognosis"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "validated",
  "last_normalized": "2024-01-15",
  "normalizer_version": 1,
  "normalization_notes": "Converted from Divine Intervention/Inner Circle/Emma Holliday board review evidence. Contains 62 recommendations, 4 diagnostic criteria, 1 treatment step, 22 thresholds, and 1 red flag from source material. All clinical claims need verification against actual NCCN guidelines. Focused primarily on Hodgkin and Non-Hodgkin lymphoma diagnosis, staging, and treatment. Some items may need updating to reflect current guideline recommendations.",
  "all_item_ids": [
    "PACK.NCCN.LYMPH.2023.REC.01",
    "PACK.NCCN.LYMPH.2023.REC.02",
    "PACK.NCCN.LYMPH.2023.REC.03",
    "PACK.NCCN.LYMPH.2023.REC.04",
    "PACK.NCCN.LYMPH.2023.REC.05",
    "PACK.NCCN.LYMPH.2023.DC.01",
    "PACK.NCCN.LYMPH.2023.T.01",
    "PACK.NCCN.LYMPH.2023.T.02",
    "PACK.NCCN.LYMPH.2023.TX.01",
    "PACK.NCCN.LYMPH.2023.TX.02",
    "PACK.NCCN.LYMPH.2023.TX.03",
    "PACK.NCCN.LYMPH.2023.RF.01",
    "PACK.NCCN.LYMPH.2023.SEV.01"
  ],
  "all_display_ids": [
    "NCCN-LYMPH-R1",
    "NCCN-LYMPH-R2",
    "NCCN-LYMPH-R3",
    "NCCN-LYMPH-R4",
    "NCCN-LYMPH-R5",
    "NCCN-LYMPH-DC1",
    "NCCN-LYMPH-T1",
    "NCCN-LYMPH-T2",
    "NCCN-LYMPH-TX1",
    "NCCN-LYMPH-TX2",
    "NCCN-LYMPH-TX3",
    "NCCN-LYMPH-RF1",
    "NCCN-LYMPH-SEV1"
  ]
};
