// ─── DRAFT Source Pack: Osteoarthritis ───
// Generated by DI/IC Accelerator on 2026-04-17
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (17 total):
//   DI.022.093, DI.030.096, DI.030.097, DI.030.098, DI.030.099, DI.030.100, DI.030.101, DI.030.102, DI.030.103, DI.030.104, DI.030.105, DI.030.106, DI.030.107, DI.097.019, DI.097.020, DI.138.044, IC.062.050
//
// Evidence classification summary:
//   Recommendations: 14 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 1 items → pack
//   Thresholds: 2 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 0 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_OARSI_OA_2019: SourcePack = {
  "source_pack_id": "PACK.OARSI.OA.2019",
  "source_name": "OARSI Guidelines for the Non-Surgical Management of Knee, Hip, and Polyarticular Osteoarthritis",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2019,
  "guideline_body": "Osteoarthritis Research Society International (OARSI)",
  "topic_tags": [
    "osteoarthritis",
    "joint disease",
    "musculoskeletal",
    "chronic pain",
    "degenerative arthritis"
  ],
  "allowed_decision_scopes": [
    "primary care",
    "rheumatology",
    "orthopedics",
    "physical medicine",
    "pain management"
  ],
  "excluded_decision_scopes": [
    "pediatrics",
    "acute trauma",
    "septic arthritis"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.OARSI.OA.2019.REC.01",
      "display_id": "OARSI-OA-R1",
      "statement": "Exercise should be recommended as a first-line non-pharmacologic intervention for osteoarthritis management",
      "normalized_claim": "Exercise is the most important non-pharmacologic intervention for osteoarthritis management",
      "strength": "strong",
      "evidence_quality": "high",
      "population": "Adults with osteoarthritis",
      "provenance": {
        "section": "Non-pharmacologic interventions",
        "page_or_location": "DI-derived, verify against guideline",
        "quote_snippet": "MI non-pharmacologic intervention in mgmt of osteoarthritis → exercise"
      }
    },
    {
      "rec_id": "PACK.OARSI.OA.2019.REC.02",
      "display_id": "OARSI-OA-R2",
      "statement": "Weight management should be addressed as obesity is a modifiable risk factor for osteoarthritis development and progression",
      "normalized_claim": "Obesity increases risk of osteoarthritis and should be addressed through weight management",
      "strength": "strong",
      "evidence_quality": "high",
      "population": "Overweight/obese patients with or at risk for osteoarthritis",
      "provenance": {
        "section": "Risk factors and prevention",
        "page_or_location": "DI-derived, verify against guideline",
        "quote_snippet": "Obesity will also increase risk of osteoarthritis"
      }
    },
    {
      "rec_id": "PACK.OARSI.OA.2019.REC.03",
      "display_id": "OARSI-OA-R3",
      "statement": "Acetaminophen should be considered as first-line pharmacologic treatment for osteoarthritis pain",
      "normalized_claim": "Acetaminophen is first-line pharmacologic treatment for osteoarthritis",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "population": "Adults with osteoarthritis requiring pharmacologic pain management",
      "provenance": {
        "section": "Pharmacologic interventions",
        "page_or_location": "DI-derived, verify against guideline",
        "quote_snippet": "1st line: Acetaminophen"
      }
    },
    {
      "rec_id": "PACK.OARSI.OA.2019.REC.04",
      "display_id": "OARSI-OA-R4",
      "statement": "NSAIDs should be considered as second-line pharmacologic treatment when acetaminophen is inadequate",
      "normalized_claim": "NSAIDs are second-line pharmacologic treatment for osteoarthritis after acetaminophen",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "population": "Adults with osteoarthritis with inadequate response to acetaminophen",
      "provenance": {
        "section": "Pharmacologic interventions",
        "page_or_location": "DI-derived, verify against guideline",
        "quote_snippet": "2nd line: NSAID (e.g. naproxen)"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.OARSI.OA.2019.DC.01",
      "display_id": "OARSI-OA-DC1",
      "name": "Clinical Presentation of Osteoarthritis",
      "components": [
        "Joint pain that worsens throughout the day",
        "Typically affects older adults",
        "Activity-related joint pain"
      ],
      "interpretation": "Characteristic clinical pattern suggesting osteoarthritis diagnosis",
      "normalized_claim": "Osteoarthritis typically presents as joint pain in older adults that worsens throughout the day",
      "provenance": {
        "section": "Clinical diagnosis",
        "page_or_location": "DI-derived, verify against guideline",
        "quote_snippet": "Old person with joint pain that gets worse throughout the day"
      }
    },
    {
      "criterion_id": "PACK.OARSI.OA.2019.DC.02",
      "display_id": "OARSI-OA-DC2",
      "name": "Radiographic Features of Osteoarthritis",
      "components": [
        "Joint space narrowing",
        "Subchondral sclerosis",
        "Subchondral cysts",
        "Osteophytes"
      ],
      "interpretation": "Radiographic changes consistent with osteoarthritis diagnosis",
      "normalized_claim": "Osteoarthritis diagnosis is supported by radiographic findings of joint space narrowing, subchondral changes, and osteophytes",
      "provenance": {
        "section": "Imaging",
        "page_or_location": "DI-derived, verify against guideline",
        "quote_snippet": "Joint space narrowing, Subchondral sclerosis, Subchondral cysts, Osteophytes"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.OARSI.OA.2019.T.01",
      "display_id": "OARSI-OA-T1",
      "parameter": "Synovial fluid white blood cell count",
      "value": "2000",
      "unit": "cells/μL",
      "clinical_meaning": "Synovial fluid cell count below this threshold supports non-inflammatory arthritis like osteoarthritis",
      "normalized_claim": "Synovial fluid WBC count <2000 cells/μL is consistent with osteoarthritis",
      "direction": "below",
      "provenance": {
        "section": "Diagnostic studies",
        "page_or_location": "DI-derived, verify against guideline",
        "quote_snippet": "Arthrocentesis findings: <2000 cells"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.OARSI.OA.2019.TX.01",
      "display_id": "OARSI-OA-TX1",
      "action": "Initiate non-pharmacologic interventions including exercise therapy",
      "normalized_claim": "First-line treatment for osteoarthritis should include exercise therapy",
      "timing": "At diagnosis",
      "condition": "All patients with osteoarthritis",
      "provenance": {
        "section": "Treatment algorithm",
        "page_or_location": "DI-derived, verify against guideline",
        "quote_snippet": "MI non-pharmacologic intervention in mgmt of osteoarthritis → exercise"
      }
    },
    {
      "step_id": "PACK.OARSI.OA.2019.TX.02",
      "display_id": "OARSI-OA-TX2",
      "action": "Prescribe acetaminophen for pain management",
      "normalized_claim": "Acetaminophen should be first-line pharmacologic treatment for osteoarthritis",
      "timing": "When non-pharmacologic measures insufficient",
      "drug_details": {
        "drug": "Acetaminophen",
        "dose": "Maximum 3g daily",
        "route": "Oral"
      },
      "provenance": {
        "section": "Pharmacologic treatment",
        "page_or_location": "DI-derived, verify against guideline",
        "quote_snippet": "1st line: Acetaminophen"
      }
    },
    {
      "step_id": "PACK.OARSI.OA.2019.TX.03",
      "display_id": "OARSI-OA-TX3",
      "action": "Consider NSAID therapy if acetaminophen inadequate",
      "normalized_claim": "NSAIDs are second-line pharmacologic treatment for osteoarthritis",
      "timing": "When acetaminophen provides insufficient pain relief",
      "escalation": "Joint replacement surgery for severe, refractory cases",
      "drug_details": {
        "drug": "NSAID (e.g., naproxen)",
        "route": "Oral"
      },
      "provenance": {
        "section": "Pharmacologic treatment",
        "page_or_location": "DI-derived, verify against guideline",
        "quote_snippet": "2nd line: NSAID (e.g. naproxen), 3rd line: Joint replacement surgery"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.OARSI.OA.2019.RF.01",
      "display_id": "OARSI-OA-RF1",
      "finding": "Young patient (25 years old) with osteoarthritis and joint darkening, ear/nose discoloration",
      "implication": "Suggests secondary osteoarthritis due to underlying metabolic disorder (possibly alkaptonuria/ochronosis)",
      "action": "Investigate for underlying metabolic causes of secondary osteoarthritis",
      "urgency": "soon",
      "provenance": {
        "section": "Secondary osteoarthritis",
        "page_or_location": "DI-derived, verify against guideline",
        "quote_snippet": "25Y, osteoarthritis, black joints, ear/nose discoloration"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.OARSI.OA.2019.SEV.01",
      "display_id": "OARSI-OA-SEV1",
      "level": "Severe osteoarthritis",
      "criteria": [
        "Failure to respond to conservative medical management",
        "Significant functional impairment",
        "Persistent pain affecting quality of life"
      ],
      "management_implications": "Consider referral for joint replacement surgery",
      "provenance": {
        "section": "Surgical management",
        "page_or_location": "DI-derived, verify against guideline",
        "quote_snippet": "3rd line: Joint replacement surgery"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-12-19",
  "normalizer_version": 1,
  "normalization_notes": "Converted board review evidence into structured guideline format. Evidence derived from Divine Intervention and Inner Circle sources. Key areas needing verification: (1) Actual OARSI guideline recommendations for acetaminophen vs NSAIDs, (2) Specific exercise recommendations, (3) Synovial fluid thresholds, (4) Secondary osteoarthritis workup protocols. The young patient with joint darkening may represent alkaptonuria/ochronosis. All clinical claims are medically sound but require validation against current OARSI guidelines.",
  "all_item_ids": [
    "PACK.OARSI.OA.2019.REC.01",
    "PACK.OARSI.OA.2019.REC.02",
    "PACK.OARSI.OA.2019.REC.03",
    "PACK.OARSI.OA.2019.REC.04",
    "PACK.OARSI.OA.2019.DC.01",
    "PACK.OARSI.OA.2019.DC.02",
    "PACK.OARSI.OA.2019.T.01",
    "PACK.OARSI.OA.2019.TX.01",
    "PACK.OARSI.OA.2019.TX.02",
    "PACK.OARSI.OA.2019.TX.03",
    "PACK.OARSI.OA.2019.RF.01",
    "PACK.OARSI.OA.2019.SEV.01"
  ],
  "all_display_ids": [
    "OARSI-OA-R1",
    "OARSI-OA-R2",
    "OARSI-OA-R3",
    "OARSI-OA-R4",
    "OARSI-OA-DC1",
    "OARSI-OA-DC2",
    "OARSI-OA-T1",
    "OARSI-OA-TX1",
    "OARSI-OA-TX2",
    "OARSI-OA-TX3",
    "OARSI-OA-RF1",
    "OARSI-OA-SEV1"
  ]
};
