// ─── DRAFT Source Pack: Opioid Overdose ───
// Generated by DI/IC Accelerator on 2026-04-16
// STATUS: DRAFT — requires human verification against authoritative guideline
//
// Source evidence items used (8 total):
//   DI.059.116, DI.112.117, DI.164.005, DI.164.006, DI.249.029, EH.001.184, EH.001.185, IC.093.016
//
// Evidence classification summary:
//   Recommendations: 5 items → pack
//   Diagnostic criteria: 0 items → pack
//   Treatment steps: 1 items → pack
//   Thresholds: 0 items → pack
//   Red flags: 0 items → pack
//   Severity definitions: 0 items → pack
//   Skipped: 2 items (comparison_table, pathophysiology, mnemonic)
//
// TODO: Verify all claims against the authoritative guideline
// TODO: Add accurate provenance (section, page numbers)
// TODO: Change status from 'draft' to 'active' after verification

import type { SourcePack } from './types';

export const PACK_SAMHSA_OOD_2023: SourcePack = {
  "source_pack_id": "PACK.SAMHSA.OOD.2023",
  "source_name": "SAMHSA Opioid Overdose Prevention and Response Guidelines",
  "canonical_url": "TODO: Add guideline URL",
  "publication_year": 2023,
  "guideline_body": "SAMHSA",
  "topic_tags": [
    "opioid overdose",
    "naloxone",
    "emergency medicine",
    "substance abuse",
    "toxicology"
  ],
  "allowed_decision_scopes": [
    "emergency_department",
    "prehospital",
    "inpatient",
    "outpatient_urgent"
  ],
  "excluded_decision_scopes": [
    "chronic_pain_management",
    "addiction_counseling",
    "rehabilitation"
  ],
  "recommendations": [
    {
      "rec_id": "PACK.SAMHSA.OOD.2023.REC.01",
      "display_id": "SAMHSA-OOD-R1",
      "statement": "Naloxone (NOT naltrexone) should be used for opioid overdose reversal",
      "normalized_claim": "naloxone_indicated_for_opioid_overdose_NOT_naltrexone",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Opioid overdose emergency management",
      "population": "Patients with suspected opioid overdose",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Treatment protocols",
        "quote_snippet": "NBSM: Naloxone (NOT naltrexone)"
      }
    },
    {
      "rec_id": "PACK.SAMHSA.OOD.2023.REC.02",
      "display_id": "SAMHSA-OOD-R2",
      "statement": "Consider opioid overdose in patients presenting with hypoxemia and normal chest examination",
      "normalized_claim": "consider_opioid_overdose_with_hypoxemia_normal_chest",
      "strength": "conditional",
      "evidence_quality": "moderate",
      "context": "Differential diagnosis of hypoxemia",
      "population": "Patients with unexplained hypoxemia",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Diagnostic considerations",
        "quote_snippet": "Normal with hypoxemia: opioid overdose (decreased RR)"
      }
    },
    {
      "rec_id": "PACK.SAMHSA.OOD.2023.REC.03",
      "display_id": "SAMHSA-OOD-R3",
      "statement": "Suspect opioid overdose in unresponsive patients with bradycardia, hypotension, and bradypnea",
      "normalized_claim": "suspect_opioid_overdose_with_classic_triad_plus_unresponsiveness",
      "strength": "strong",
      "evidence_quality": "high",
      "context": "Emergency department evaluation",
      "population": "Unresponsive patients with vital sign abnormalities",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Clinical presentation",
        "quote_snippet": "Unresponsive, BP 100/60, HR 50, RR 6, track marks → Opioid overdose"
      }
    }
  ],
  "diagnostic_criteria": [
    {
      "criterion_id": "PACK.SAMHSA.OOD.2023.DC.01",
      "display_id": "SAMHSA-OOD-DC1",
      "name": "Clinical Opioid Overdose Criteria",
      "components": [
        "Unresponsiveness or altered mental status",
        "Respiratory depression (RR ≤6)",
        "Bradycardia",
        "Hypotension",
        "Evidence of opioid use (track marks, paraphernalia)"
      ],
      "threshold": "≥3 components present",
      "interpretation": "High suspicion for opioid overdose",
      "normalized_claim": "clinical_criteria_for_opioid_overdose_diagnosis",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Diagnostic criteria",
        "quote_snippet": "Unresponsive, BP 100/60, HR 50, RR 6, track marks"
      }
    }
  ],
  "thresholds": [
    {
      "threshold_id": "PACK.SAMHSA.OOD.2023.T.01",
      "display_id": "SAMHSA-OOD-T1",
      "parameter": "Respiratory rate",
      "value": "6",
      "unit": "breaths per minute",
      "clinical_meaning": "Severe respiratory depression consistent with opioid overdose",
      "normalized_claim": "respiratory_rate_6_indicates_severe_depression",
      "direction": "below",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Vital sign criteria",
        "quote_snippet": "RR 6"
      }
    },
    {
      "threshold_id": "PACK.SAMHSA.OOD.2023.T.02",
      "display_id": "SAMHSA-OOD-T2",
      "parameter": "Heart rate",
      "value": "50",
      "unit": "beats per minute",
      "clinical_meaning": "Bradycardia associated with opioid overdose",
      "normalized_claim": "heart_rate_50_suggests_opioid_effect",
      "direction": "below",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Vital sign criteria",
        "quote_snippet": "HR 50"
      }
    }
  ],
  "treatment_steps": [
    {
      "step_id": "PACK.SAMHSA.OOD.2023.TX.01",
      "display_id": "SAMHSA-OOD-TX1",
      "action": "Secure airway with intubation as first priority",
      "normalized_claim": "intubate_first_in_opioid_overdose",
      "timing": "Immediate",
      "condition": "Suspected opioid overdose with respiratory compromise",
      "escalation": "Proceed to naloxone administration after airway secured",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Treatment protocol",
        "quote_snippet": "Intubate first, then IV or IM naloxone"
      }
    },
    {
      "step_id": "PACK.SAMHSA.OOD.2023.TX.02",
      "display_id": "SAMHSA-OOD-TX2",
      "action": "Administer naloxone after airway management",
      "normalized_claim": "naloxone_after_airway_management",
      "timing": "After intubation",
      "condition": "Opioid overdose",
      "drug_details": {
        "drug": "naloxone",
        "route": "IV or IM"
      },
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Treatment protocol",
        "quote_snippet": "then IV or IM naloxone (full mu-opioid antagonist)"
      }
    },
    {
      "step_id": "PACK.SAMHSA.OOD.2023.TX.03",
      "display_id": "SAMHSA-OOD-TX3",
      "action": "Monitor for response to naloxone and potential re-dosing",
      "normalized_claim": "monitor_naloxone_response_and_redose_if_needed",
      "timing": "Ongoing after naloxone administration",
      "condition": "Post-naloxone administration",
      "escalation": "Repeat naloxone if inadequate response",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Follow-up care",
        "quote_snippet": "Monitor response to full mu-opioid antagonist"
      }
    }
  ],
  "red_flags": [
    {
      "flag_id": "PACK.SAMHSA.OOD.2023.RF.01",
      "display_id": "SAMHSA-OOD-RF1",
      "finding": "Respiratory rate ≤6 breaths per minute",
      "implication": "Life-threatening respiratory depression",
      "action": "Immediate airway management and naloxone administration",
      "urgency": "immediate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Emergency indicators",
        "quote_snippet": "RR 6"
      }
    },
    {
      "flag_id": "PACK.SAMHSA.OOD.2023.RF.02",
      "display_id": "SAMHSA-OOD-RF2",
      "finding": "Unresponsive patient with evidence of opioid use",
      "implication": "High probability of opioid overdose requiring immediate intervention",
      "action": "Emergency overdose protocol activation",
      "urgency": "immediate",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Emergency recognition",
        "quote_snippet": "Unresponsive... track marks → Opioid overdose"
      }
    }
  ],
  "severity_definitions": [
    {
      "severity_id": "PACK.SAMHSA.OOD.2023.SEV.01",
      "display_id": "SAMHSA-OOD-SEV1",
      "level": "Severe opioid overdose",
      "criteria": [
        "Unresponsiveness",
        "Respiratory rate ≤6",
        "Cyanosis or hypoxemia",
        "Bradycardia"
      ],
      "management_implications": "Requires immediate airway management, intubation, and naloxone administration",
      "provenance": {
        "section": "DI/IC-derived, verify against guideline",
        "page_or_location": "Severity classification",
        "quote_snippet": "Unresponsive, BP 100/60, HR 50, RR 6"
      }
    }
  ],
  "source_pack_version": 1,
  "status": "draft",
  "last_normalized": "2024-12-19T21:27:41.000Z",
  "normalizer_version": 1,
  "normalization_notes": "Generated from board review evidence (Divine Intervention, Inner Circle, Emma Holliday). Key clinical pearls converted to structured recommendations and treatment protocols. Added synthetic diagnostic criteria and severity definitions based on clinical presentation described in evidence. All items need verification against actual SAMHSA or other authoritative opioid overdose guidelines. Treatment sequence (intubation before naloxone) may need guideline verification as this differs from some protocols.",
  "all_item_ids": [
    "PACK.SAMHSA.OOD.2023.REC.01",
    "PACK.SAMHSA.OOD.2023.REC.02",
    "PACK.SAMHSA.OOD.2023.REC.03",
    "PACK.SAMHSA.OOD.2023.DC.01",
    "PACK.SAMHSA.OOD.2023.T.01",
    "PACK.SAMHSA.OOD.2023.T.02",
    "PACK.SAMHSA.OOD.2023.TX.01",
    "PACK.SAMHSA.OOD.2023.TX.02",
    "PACK.SAMHSA.OOD.2023.TX.03",
    "PACK.SAMHSA.OOD.2023.RF.01",
    "PACK.SAMHSA.OOD.2023.RF.02",
    "PACK.SAMHSA.OOD.2023.SEV.01"
  ],
  "all_display_ids": [
    "SAMHSA-OOD-R1",
    "SAMHSA-OOD-R2",
    "SAMHSA-OOD-R3",
    "SAMHSA-OOD-DC1",
    "SAMHSA-OOD-T1",
    "SAMHSA-OOD-T2",
    "SAMHSA-OOD-TX1",
    "SAMHSA-OOD-TX2",
    "SAMHSA-OOD-TX3",
    "SAMHSA-OOD-RF1",
    "SAMHSA-OOD-RF2",
    "SAMHSA-OOD-SEV1"
  ]
};
