import type { SourcePack } from './types';

export const pack: SourcePack = {
  source_pack_id: 'PACK.SSC.SEPSIS.2021',
  source_name: 'Surviving Sepsis Campaign: International Guidelines for Management of Sepsis and Septic Shock 2021',
  source_registry_id: 'REG.SSC.SEPSIS',
  canonical_url: 'https://doi.org/10.1097/CCM.0000000000005337',
  publication_year: 2021,
  guideline_body: 'Society of Critical Care Medicine / European Society of Intensive Care Medicine',

  topic_tags: ['Sepsis', 'Septic Shock', 'Critical Care', 'Fluid Resuscitation', 'Vasopressors', 'Source Control'],
  allowed_decision_scopes: [
    'sepsis recognition and screening',
    'septic shock diagnosis',
    'fluid resuscitation strategy',
    'vasopressor selection and escalation',
    'empiric antibiotic selection',
    'blood culture timing',
    'source control',
    'corticosteroid use in septic shock',
    'lactate-guided resuscitation',
    'MAP targets',
  ],
  excluded_decision_scopes: [
    'specific antibiotic regimens by infection site',
    'ventilator management and ARDS protocols',
    'renal replacement therapy initiation',
    'nutrition in critical illness',
    'DVT prophylaxis protocols',
    'ICU sedation and analgesia',
  ],

  recommendations: [
    {
      rec_id: 'PACK.SSC.SEPSIS.2021.REC.01',
      display_id: 'SSC-SEPSIS-R1',
      statement: 'For adults with suspected sepsis or septic shock, we recommend administering antimicrobials immediately, ideally within 1 hour of recognition.',
      normalized_claim: 'Sepsis/septic shock: administer broad-spectrum IV antibiotics within 1 hour of recognition. Every hour of delay increases mortality.',
      strength: 'strong',
      evidence_quality: 'moderate',
      context: 'Each hour delay in antibiotic administration is associated with measurable increase in mortality',
      provenance: { section: 'Antimicrobial Therapy', page_or_location: 'Section 4.1' },
    },
    {
      rec_id: 'PACK.SSC.SEPSIS.2021.REC.02',
      display_id: 'SSC-SEPSIS-R2',
      statement: 'We recommend obtaining blood cultures before administering antimicrobials in patients with suspected sepsis and septic shock, provided this does not substantially delay antibiotic administration.',
      normalized_claim: 'Obtain blood cultures (2 sets, aerobic + anaerobic) before antibiotics if it does not delay treatment. Do not delay antibiotics for cultures.',
      strength: 'strong',
      evidence_quality: 'low',
      provenance: { section: 'Diagnosis', page_or_location: 'Section 3.1' },
    },
    {
      rec_id: 'PACK.SSC.SEPSIS.2021.REC.03',
      display_id: 'SSC-SEPSIS-R3',
      statement: 'For adults with sepsis-induced hypoperfusion or septic shock, we suggest administering at least 30 mL/kg of IV crystalloid fluid within the first 3 hours of resuscitation.',
      normalized_claim: 'Sepsis/septic shock: 30 mL/kg IV crystalloid within first 3 hours. Balanced crystalloids (LR) preferred over normal saline.',
      strength: 'conditional',
      evidence_quality: 'low',
      context: 'Reassess fluid responsiveness frequently; avoid fluid overload',
      provenance: { section: 'Fluid Resuscitation', page_or_location: 'Section 5.1' },
    },
    {
      rec_id: 'PACK.SSC.SEPSIS.2021.REC.04',
      display_id: 'SSC-SEPSIS-R4',
      statement: 'We recommend norepinephrine as the first-line vasopressor for septic shock.',
      normalized_claim: 'Norepinephrine is first-line vasopressor for septic shock. Target MAP >=65 mmHg.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Vasopressors', page_or_location: 'Section 6.1' },
    },
    {
      rec_id: 'PACK.SSC.SEPSIS.2021.REC.05',
      display_id: 'SSC-SEPSIS-R5',
      statement: 'For adults with septic shock on norepinephrine with inadequate MAP, we suggest adding vasopressin (up to 0.03 units/min) rather than further escalating norepinephrine dose.',
      normalized_claim: 'Add vasopressin (up to 0.03 U/min) as second vasopressor when norepinephrine alone insufficient for MAP >=65. Typically added at norepi 0.25-0.5 mcg/kg/min.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      provenance: { section: 'Vasopressors', page_or_location: 'Section 6.2' },
    },
    {
      rec_id: 'PACK.SSC.SEPSIS.2021.REC.06',
      display_id: 'SSC-SEPSIS-R6',
      statement: 'We suggest using IV corticosteroids (hydrocortisone 200mg/day) for adults with septic shock and an ongoing requirement for vasopressor therapy.',
      normalized_claim: 'IV hydrocortisone 200mg/day (50mg q6h or continuous infusion) for refractory septic shock requiring ongoing vasopressors despite adequate fluids.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      provenance: { section: 'Corticosteroids', page_or_location: 'Section 7.1' },
    },
    {
      rec_id: 'PACK.SSC.SEPSIS.2021.REC.07',
      display_id: 'SSC-SEPSIS-R7',
      statement: 'We recommend using lactate levels to guide resuscitation in sepsis over relying solely on physical examination or capillary refill.',
      normalized_claim: 'Lactate-guided resuscitation: target lactate normalization or decrease of >=20% every 2 hours. Serial lactate more reliable than CVP or ScvO2.',
      strength: 'conditional',
      evidence_quality: 'low',
      provenance: { section: 'Resuscitation Targets', page_or_location: 'Section 5.3' },
    },
    {
      rec_id: 'PACK.SSC.SEPSIS.2021.REC.08',
      display_id: 'SSC-SEPSIS-R8',
      statement: 'We recommend emergent source control within 6-12 hours of identification for patients with sepsis requiring source control interventions (e.g., abscess drainage, debridement of infected tissue, removal of infected devices).',
      normalized_claim: 'Source control (drain abscess, debride necrotic tissue, remove infected device) within 6-12h of identification. Definitive source control reduces mortality.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Source Control', page_or_location: 'Section 4.3' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.SSC.SEPSIS.2021.DC.01',
      display_id: 'SSC-SEPSIS-DC1',
      name: 'Sepsis-3 Definition',
      components: [
        'Suspected or documented infection',
        'Acute increase in SOFA score >=2 points from baseline',
        'SOFA components: respiration (PaO2/FiO2), coagulation (platelets), liver (bilirubin), cardiovascular (MAP/vasopressors), CNS (GCS), renal (creatinine/urine output)',
      ],
      threshold: 'SOFA score increase >=2 from baseline',
      interpretation: 'Sepsis = life-threatening organ dysfunction caused by dysregulated host response to infection. SOFA >=2 represents organ dysfunction with in-hospital mortality >10%. Replaces older SIRS-based definition.',
      normalized_claim: 'Sepsis-3: infection + SOFA increase >=2. SOFA assesses 6 organ systems. Replaces SIRS criteria for sepsis definition.',
      provenance: { section: 'Definitions', page_or_location: 'Section 1.1' },
    },
    {
      criterion_id: 'PACK.SSC.SEPSIS.2021.DC.02',
      display_id: 'SSC-SEPSIS-DC2',
      name: 'qSOFA (Quick SOFA) Screening',
      components: [
        'Respiratory rate >=22 breaths/min',
        'Altered mentation (GCS <15)',
        'Systolic blood pressure <=100 mmHg',
      ],
      threshold: '>=2 of 3 criteria',
      interpretation: 'qSOFA >=2 identifies patients outside the ICU at high risk for poor outcomes from sepsis. Prompts further evaluation for organ dysfunction (full SOFA). Not a diagnostic criterion for sepsis; used as a bedside screening tool.',
      normalized_claim: 'qSOFA (RR >=22, altered mentation, SBP <=100): >=2/3 criteria = screen positive. Bedside screening tool, not diagnostic. Triggers full SOFA assessment.',
      provenance: { section: 'Screening', page_or_location: 'Section 1.2' },
    },
    {
      criterion_id: 'PACK.SSC.SEPSIS.2021.DC.03',
      display_id: 'SSC-SEPSIS-DC3',
      name: 'Septic Shock Definition',
      components: [
        'Sepsis (infection + SOFA >=2)',
        'Persisting hypotension requiring vasopressors to maintain MAP >=65 mmHg',
        'Serum lactate >2 mmol/L despite adequate volume resuscitation',
      ],
      interpretation: 'Septic shock is a subset of sepsis with circulatory and cellular/metabolic dysfunction associated with higher mortality (>40%). Both vasopressor requirement AND lactate >2 must be present.',
      normalized_claim: 'Septic shock = sepsis + vasopressors needed for MAP >=65 + lactate >2 mmol/L despite adequate resuscitation. Mortality >40%.',
      provenance: { section: 'Definitions', page_or_location: 'Section 1.3' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.SSC.SEPSIS.2021.T.01',
      display_id: 'SSC-SEPSIS-T1',
      parameter: 'Mean arterial pressure (MAP) target',
      value: '65',
      unit: 'mmHg',
      clinical_meaning: 'Target MAP >=65 mmHg with vasopressors in septic shock. Higher targets (80 mmHg) have not shown benefit and may increase atrial fibrillation risk.',
      normalized_claim: 'MAP target >=65 mmHg in septic shock. No benefit from targeting MAP >65; higher targets increase arrhythmia risk.',
      direction: 'above',
      provenance: { section: 'Hemodynamic Targets', page_or_location: 'Section 5.2' },
    },
    {
      threshold_id: 'PACK.SSC.SEPSIS.2021.T.02',
      display_id: 'SSC-SEPSIS-T2',
      parameter: 'Serum lactate',
      value: '2',
      unit: 'mmol/L',
      clinical_meaning: 'Lactate >2 mmol/L indicates tissue hypoperfusion. Lactate >2 mmol/L combined with vasopressor requirement defines septic shock. Serial lactate trending guides resuscitation adequacy.',
      normalized_claim: 'Lactate >2 mmol/L = tissue hypoperfusion. Part of septic shock definition when combined with vasopressor need. Serial trending guides resuscitation.',
      direction: 'above',
      provenance: { section: 'Resuscitation Targets', page_or_location: 'Section 5.3' },
    },
    {
      threshold_id: 'PACK.SSC.SEPSIS.2021.T.03',
      display_id: 'SSC-SEPSIS-T3',
      parameter: 'Crystalloid fluid bolus volume',
      value: '30',
      unit: 'mL/kg',
      clinical_meaning: 'At least 30 mL/kg IV crystalloid within the first 3 hours for sepsis-induced hypoperfusion or septic shock. Reassess fluid responsiveness after initial bolus. Further fluids guided by dynamic measures (pulse pressure variation, passive leg raise).',
      normalized_claim: '30 mL/kg IV crystalloid within 3 hours for septic shock. Reassess responsiveness after; use dynamic measures for further fluid decisions.',
      direction: 'above',
      provenance: { section: 'Fluid Resuscitation', page_or_location: 'Section 5.1' },
    },
    {
      threshold_id: 'PACK.SSC.SEPSIS.2021.T.04',
      display_id: 'SSC-SEPSIS-T4',
      parameter: 'Lactate level indicating severe hypoperfusion',
      value: '4',
      unit: 'mmol/L',
      clinical_meaning: 'Lactate >=4 mmol/L indicates severe tissue hypoperfusion and is an independent predictor of mortality. Mandates aggressive resuscitation regardless of blood pressure.',
      normalized_claim: 'Lactate >=4 mmol/L = severe hypoperfusion. Independent mortality predictor. Mandates aggressive resuscitation even if BP is normal.',
      direction: 'above',
      provenance: { section: 'Resuscitation Targets', page_or_location: 'Section 5.3' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.SSC.SEPSIS.2021.TX.01',
      display_id: 'SSC-SEPSIS-TX1',
      action: 'Hour-1 bundle: cultures, antibiotics, fluids, lactate, vasopressors',
      normalized_claim: 'Hour-1 bundle: (1) measure lactate, (2) obtain blood cultures, (3) administer broad-spectrum IV antibiotics, (4) begin 30 mL/kg crystalloid for hypotension or lactate >=4, (5) start vasopressors if MAP <65 during or after fluids.',
      timing: 'Within 1 hour of sepsis recognition',
      condition: 'Sepsis or septic shock',
      provenance: { section: 'Hour-1 Bundle', page_or_location: 'Section 2.1' },
    },
    {
      step_id: 'PACK.SSC.SEPSIS.2021.TX.02',
      display_id: 'SSC-SEPSIS-TX2',
      action: 'Vasopressor initiation and escalation',
      normalized_claim: 'Vasopressor ladder: (1) norepinephrine first-line, target MAP >=65. (2) Add vasopressin 0.03 U/min if norepinephrine insufficient. (3) Add epinephrine as third agent if needed. Dopamine NOT recommended (more arrhythmias).',
      timing: 'If MAP <65 despite initial fluid resuscitation',
      condition: 'Septic shock with persistent hypotension',
      drug_details: { drug: 'Norepinephrine', dose: 'Start 0.1 mcg/kg/min, titrate to MAP >=65', route: 'IV central line preferred' },
      escalation: 'Add vasopressin 0.03 U/min as second agent. If still refractory, add epinephrine. Consider IV hydrocortisone 200mg/day for refractory shock.',
      provenance: { section: 'Vasopressors', page_or_location: 'Section 6.1' },
    },
    {
      step_id: 'PACK.SSC.SEPSIS.2021.TX.03',
      display_id: 'SSC-SEPSIS-TX3',
      action: 'Corticosteroid therapy for refractory septic shock',
      normalized_claim: 'IV hydrocortisone 200mg/day (50mg q6h) for septic shock requiring escalating vasopressors. Do not use dexamethasone (no mineralocorticoid activity). Taper when vasopressors discontinued.',
      timing: 'When vasopressor requirements are escalating despite adequate fluids',
      condition: 'Refractory septic shock',
      drug_details: { drug: 'Hydrocortisone', dose: '50mg IV q6h', route: 'IV', duration: 'Until vasopressors weaned, then taper' },
      contraindications: ['Uncontrolled fungal infection (relative)'],
      provenance: { section: 'Corticosteroids', page_or_location: 'Section 7.1' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.SSC.SEPSIS.2021.RF.01',
      display_id: 'SSC-SEPSIS-RF1',
      finding: 'Lactate >=4 mmol/L with or without hypotension',
      implication: 'Indicates severe tissue hypoperfusion ("cryptic shock" if normotensive). Mortality >30% even with aggressive treatment. Mandates ICU-level care.',
      action: 'Immediate Hour-1 bundle execution. ICU admission. Aggressive fluid resuscitation. Early vasopressors if MAP <65. Serial lactate monitoring q2h.',
      urgency: 'immediate',
      provenance: { section: 'Resuscitation Targets', page_or_location: 'Section 5.3' },
    },
    {
      flag_id: 'PACK.SSC.SEPSIS.2021.RF.02',
      display_id: 'SSC-SEPSIS-RF2',
      finding: 'Refractory hypotension: MAP <65 despite 30 mL/kg crystalloid and norepinephrine escalation',
      implication: 'Suggests severe distributive or combined shock. Consider uncontrolled source, adrenal insufficiency, or cardiogenic component.',
      action: 'Add vasopressin. Start hydrocortisone 200mg/day. Reassess source control. Point-of-care echocardiography to evaluate cardiac function. Consider epinephrine if cardiac dysfunction suspected.',
      urgency: 'immediate',
      provenance: { section: 'Refractory Shock', page_or_location: 'Section 6.3' },
    },
    {
      flag_id: 'PACK.SSC.SEPSIS.2021.RF.03',
      display_id: 'SSC-SEPSIS-RF3',
      finding: 'Multi-organ dysfunction: new-onset acute kidney injury + coagulopathy + altered mental status in setting of infection',
      implication: 'SOFA score likely >=4-6. Mortality exceeds 50%. Indicates severe sepsis with multi-organ failure.',
      action: 'Maximally aggressive sepsis management. ICU with continuous monitoring. Consider renal replacement therapy if indicated. Reassess antibiotic adequacy and source control. Goals of care discussion.',
      urgency: 'immediate',
      provenance: { section: 'Organ Dysfunction', page_or_location: 'Section 1.1' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.SSC.SEPSIS.2021.SEV.01',
      display_id: 'SSC-SEPSIS-SEV1',
      level: 'Sepsis (without shock)',
      criteria: [
        'Suspected or documented infection',
        'SOFA score increase >=2 from baseline',
        'Hemodynamically stable or responsive to fluids alone',
        'Lactate <=2 mmol/L or normalizing with resuscitation',
        'No vasopressor requirement',
      ],
      management_implications: 'Hour-1 bundle still applies. IV antibiotics within 1 hour. Fluid resuscitation if hypoperfusion present. Serial lactate monitoring. May be managed in step-down unit if improving. Reassess antibiotic spectrum at 48-72h based on cultures. In-hospital mortality approximately 10%.',
      provenance: { section: 'Definitions', page_or_location: 'Section 1.1' },
    },
    {
      severity_id: 'PACK.SSC.SEPSIS.2021.SEV.02',
      display_id: 'SSC-SEPSIS-SEV2',
      level: 'Septic shock',
      criteria: [
        'Meets sepsis criteria (infection + SOFA >=2)',
        'Persistent hypotension requiring vasopressors to maintain MAP >=65 mmHg',
        'Serum lactate >2 mmol/L despite adequate volume resuscitation',
        'Both vasopressor requirement AND elevated lactate must be present',
      ],
      management_implications: 'ICU admission mandatory. Norepinephrine first-line vasopressor. Add vasopressin if norepinephrine insufficient. Consider hydrocortisone if refractory. Central venous access. Arterial line for continuous BP monitoring. Serial lactate q2-4h. Source control within 6-12h if applicable. In-hospital mortality >40%.',
      provenance: { section: 'Definitions', page_or_location: 'Section 1.3' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 pack for sepsis. Covers Sepsis-3 definitions, Hour-1 bundle, fluid resuscitation, vasopressor escalation, corticosteroids, and lactate-guided therapy for question generation.',

  all_item_ids: [
    'PACK.SSC.SEPSIS.2021.REC.01', 'PACK.SSC.SEPSIS.2021.REC.02', 'PACK.SSC.SEPSIS.2021.REC.03',
    'PACK.SSC.SEPSIS.2021.REC.04', 'PACK.SSC.SEPSIS.2021.REC.05', 'PACK.SSC.SEPSIS.2021.REC.06',
    'PACK.SSC.SEPSIS.2021.REC.07', 'PACK.SSC.SEPSIS.2021.REC.08',
    'PACK.SSC.SEPSIS.2021.DC.01', 'PACK.SSC.SEPSIS.2021.DC.02', 'PACK.SSC.SEPSIS.2021.DC.03',
    'PACK.SSC.SEPSIS.2021.T.01', 'PACK.SSC.SEPSIS.2021.T.02', 'PACK.SSC.SEPSIS.2021.T.03', 'PACK.SSC.SEPSIS.2021.T.04',
    'PACK.SSC.SEPSIS.2021.TX.01', 'PACK.SSC.SEPSIS.2021.TX.02', 'PACK.SSC.SEPSIS.2021.TX.03',
    'PACK.SSC.SEPSIS.2021.RF.01', 'PACK.SSC.SEPSIS.2021.RF.02', 'PACK.SSC.SEPSIS.2021.RF.03',
    'PACK.SSC.SEPSIS.2021.SEV.01', 'PACK.SSC.SEPSIS.2021.SEV.02',
  ],
  all_display_ids: [
    'SSC-SEPSIS-R1', 'SSC-SEPSIS-R2', 'SSC-SEPSIS-R3', 'SSC-SEPSIS-R4', 'SSC-SEPSIS-R5', 'SSC-SEPSIS-R6', 'SSC-SEPSIS-R7', 'SSC-SEPSIS-R8',
    'SSC-SEPSIS-DC1', 'SSC-SEPSIS-DC2', 'SSC-SEPSIS-DC3',
    'SSC-SEPSIS-T1', 'SSC-SEPSIS-T2', 'SSC-SEPSIS-T3', 'SSC-SEPSIS-T4',
    'SSC-SEPSIS-TX1', 'SSC-SEPSIS-TX2', 'SSC-SEPSIS-TX3',
    'SSC-SEPSIS-RF1', 'SSC-SEPSIS-RF2', 'SSC-SEPSIS-RF3',
    'SSC-SEPSIS-SEV1', 'SSC-SEPSIS-SEV2',
  ],
};
