import type { SourcePack } from './types';

export const PACK_USPSTF_SCREEN_2024: SourcePack = {
  source_pack_id: 'PACK.USPSTF.SCREEN.2024',
  source_name: 'USPSTF A and B Grade Screening Recommendations (2024 Compendium)',
  source_registry_id: 'REG.USPSTF.SCREEN',
  canonical_url: 'https://www.uspreventiveservicestaskforce.org/uspstf/recommendation-topics/uspstf-a-and-b-recommendations',
  publication_year: 2024,
  guideline_body: 'USPSTF',

  topic_tags: ['Screening', 'Preventive Medicine', 'Cancer Screening', 'Infectious Disease Screening', 'USPSTF'],
  allowed_decision_scopes: [
    'colorectal cancer screening',
    'breast cancer screening',
    'cervical cancer screening',
    'lung cancer screening',
    'AAA screening',
    'HIV screening',
    'HCV screening',
    'depression screening',
    'diabetes screening',
    'osteoporosis screening',
    'STI screening',
    'intimate partner violence screening',
  ],
  excluded_decision_scopes: [
    'prostate cancer screening (PSA is Grade C)',
    'thyroid cancer screening',
    'pancreatic cancer screening',
    'ovarian cancer screening (Grade D)',
    'testicular cancer screening',
  ],

  recommendations: [
    {
      rec_id: 'PACK.USPSTF.SCREEN.2024.REC.01',
      display_id: 'USPSTF-SCR-R1',
      statement: 'Screen for colorectal cancer in adults aged 45-75 years (Grade A for 50-75; Grade B for 45-49). Acceptable methods include colonoscopy every 10 years, FIT annually, or stool DNA (Cologuard) every 1-3 years.',
      normalized_claim: 'Colorectal cancer screening ages 45-75: colonoscopy q10y, FIT annually, or stool DNA q1-3y. Grade A (50-75), Grade B (45-49).',
      strength: 'strong',
      evidence_quality: 'high',
      population: 'Average-risk adults aged 45-75',
      provenance: { section: 'Colorectal Cancer', page_or_location: 'May 2021 Update' },
    },
    {
      rec_id: 'PACK.USPSTF.SCREEN.2024.REC.02',
      display_id: 'USPSTF-SCR-R2',
      statement: 'Screen for breast cancer with mammography every other year in women aged 40-74 (Grade B).',
      normalized_claim: 'Biennial mammography for women aged 40-74 (Grade B). Decision for 75+ individualized.',
      strength: 'strong',
      evidence_quality: 'moderate',
      population: 'Women aged 40-74 at average risk',
      provenance: { section: 'Breast Cancer', page_or_location: 'April 2024 Update' },
    },
    {
      rec_id: 'PACK.USPSTF.SCREEN.2024.REC.03',
      display_id: 'USPSTF-SCR-R3',
      statement: 'Screen for cervical cancer in women aged 21-65. Ages 21-29: Pap smear every 3 years. Ages 30-65: Pap every 3 years, hrHPV every 5 years, or co-testing every 5 years.',
      normalized_claim: 'Cervical cancer screening: Pap q3y (21-29); Pap q3y, hrHPV q5y, or co-test q5y (30-65). Stop at 65 if adequate prior screening.',
      strength: 'strong',
      evidence_quality: 'high',
      population: 'Women aged 21-65 with a cervix',
      provenance: { section: 'Cervical Cancer', page_or_location: 'August 2018' },
    },
    {
      rec_id: 'PACK.USPSTF.SCREEN.2024.REC.04',
      display_id: 'USPSTF-SCR-R4',
      statement: 'Screen for lung cancer with annual low-dose CT (LDCT) in adults aged 50-80 who have a 20+ pack-year smoking history and currently smoke or quit within the past 15 years (Grade B).',
      normalized_claim: 'Annual LDCT lung cancer screening: ages 50-80, >=20 pack-year history, current smoker or quit <15 years ago.',
      strength: 'strong',
      evidence_quality: 'moderate',
      population: 'Adults 50-80 with >=20 pack-year history',
      provenance: { section: 'Lung Cancer', page_or_location: 'March 2021' },
    },
    {
      rec_id: 'PACK.USPSTF.SCREEN.2024.REC.05',
      display_id: 'USPSTF-SCR-R5',
      statement: 'One-time screening for abdominal aortic aneurysm (AAA) with ultrasonography in men aged 65-75 who have ever smoked (Grade B).',
      normalized_claim: 'One-time AAA ultrasound screening: men 65-75 who have ever smoked.',
      strength: 'strong',
      evidence_quality: 'moderate',
      population: 'Men aged 65-75 with any smoking history',
      provenance: { section: 'AAA', page_or_location: 'December 2019' },
    },
    {
      rec_id: 'PACK.USPSTF.SCREEN.2024.REC.06',
      display_id: 'USPSTF-SCR-R6',
      statement: 'Screen for HIV infection in all adolescents and adults aged 15-65 (Grade A). Screen all pregnant persons (Grade A).',
      normalized_claim: 'Universal HIV screening ages 15-65 and all pregnant persons (Grade A).',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'HIV', page_or_location: 'June 2019' },
    },
    {
      rec_id: 'PACK.USPSTF.SCREEN.2024.REC.07',
      display_id: 'USPSTF-SCR-R7',
      statement: 'Screen for hepatitis C virus (HCV) infection in all adults aged 18-79 (Grade B).',
      normalized_claim: 'Universal HCV screening for all adults aged 18-79 (Grade B). One-time screening.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'HCV', page_or_location: 'March 2020' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.USPSTF.SCREEN.2024.DC.01',
      display_id: 'USPSTF-SCR-DC1',
      name: 'USPSTF Grade Definitions',
      components: [
        'Grade A: High certainty of substantial net benefit. Offer/provide this service.',
        'Grade B: High certainty of moderate benefit OR moderate certainty of moderate-to-substantial benefit. Offer/provide.',
        'Grade C: Moderate certainty of small net benefit. Offer selectively based on individual circumstances.',
        'Grade D: Moderate-to-high certainty of no net benefit or harms outweigh benefits. Discourage.',
        'Grade I: Insufficient evidence to assess balance of benefits and harms.',
      ],
      interpretation: 'Grade A and B recommendations should be offered to all eligible patients. Grade C requires shared decision-making.',
      normalized_claim: 'USPSTF Grade A/B = recommend for all eligible. Grade C = selective/shared decision. Grade D = do not screen.',
      provenance: { section: 'Methods', page_or_location: 'USPSTF Grade Definitions' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.USPSTF.SCREEN.2024.T.01',
      display_id: 'USPSTF-SCR-T1',
      parameter: 'Pack-year threshold for lung cancer screening',
      value: '20',
      unit: 'pack-years',
      clinical_meaning: 'Patients with >=20 pack-year smoking history (current or quit <15 years ago) qualify for annual LDCT lung cancer screening.',
      normalized_claim: '>=20 pack-years smoking history is threshold for LDCT lung cancer screening eligibility.',
      direction: 'above',
      provenance: { section: 'Lung Cancer', page_or_location: 'March 2021' },
    },
    {
      threshold_id: 'PACK.USPSTF.SCREEN.2024.T.02',
      display_id: 'USPSTF-SCR-T2',
      parameter: 'Osteoporosis screening age threshold',
      value: '65',
      unit: 'years',
      clinical_meaning: 'Screen all women >=65 with DEXA. Younger postmenopausal women screen if 10-year fracture risk equivalent to 65-year-old white woman (FRAX tool).',
      normalized_claim: 'DEXA screening for all women >=65. Postmenopausal women <65 if FRAX risk equivalent to 65-year-old.',
      direction: 'above',
      provenance: { section: 'Osteoporosis', page_or_location: 'June 2018' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.USPSTF.SCREEN.2024.TX.01',
      display_id: 'USPSTF-SCR-TX1',
      action: 'Depression screening with PHQ-2/PHQ-9',
      normalized_claim: 'Screen all adults for depression (Grade B). PHQ-2 as initial screen; if positive (>=3), follow with PHQ-9. Ensure systems for diagnosis, treatment, and follow-up are in place.',
      condition: 'All adults in primary care settings',
      provenance: { section: 'Depression Screening', page_or_location: 'January 2016' },
    },
    {
      step_id: 'PACK.USPSTF.SCREEN.2024.TX.02',
      display_id: 'USPSTF-SCR-TX2',
      action: 'Diabetes screening in overweight/obese adults',
      normalized_claim: 'Screen for prediabetes/type 2 diabetes in adults aged 35-70 who are overweight or obese (Grade B). Fasting glucose, HbA1c, or OGTT.',
      condition: 'Adults aged 35-70 with BMI >=25',
      provenance: { section: 'Diabetes', page_or_location: 'August 2021' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.USPSTF.SCREEN.2024.RF.01',
      display_id: 'USPSTF-SCR-RF1',
      finding: 'Positive screening result requiring urgent follow-up: positive FIT/stool DNA, suspicious mammographic lesion (BIRADS 4-5), or Lung-RADS 4 nodule on LDCT',
      implication: 'Positive screening tests require timely diagnostic workup. Delays in follow-up reduce screening benefit and worsen outcomes.',
      action: 'Expedited diagnostic evaluation: colonoscopy for positive stool test, tissue biopsy for suspicious breast/lung lesion. Close loop on all positive screens.',
      urgency: 'urgent',
      provenance: { section: 'Follow-up', page_or_location: 'General Recommendations' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.USPSTF.SCREEN.2024.SEV.01',
      display_id: 'USPSTF-SCR-SEV1',
      level: 'High-risk patient requiring enhanced screening',
      criteria: [
        'Family history of cancer in first-degree relative (breast, colon, lung)',
        'Known genetic mutation (BRCA1/2, Lynch syndrome, Li-Fraumeni)',
        'Prior personal history of cancer or precancerous lesion',
        'Immunosuppression or HIV-positive status',
        'Environmental/occupational exposures (asbestos, radiation)',
      ],
      management_implications:
        'USPSTF recommendations apply to average-risk populations. High-risk patients may need earlier screening initiation, shorter intervals, or additional modalities (e.g., breast MRI for BRCA carriers). Refer to specialist guidelines (NCCN) for high-risk protocols.',
      provenance: { section: 'Applicability', page_or_location: 'General Limitations' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Phase 1 preventive medicine pack. Covers USPSTF A/B grade screenings for cancer, infectious disease, depression, diabetes, osteoporosis, IPV.',

  all_item_ids: [
    'PACK.USPSTF.SCREEN.2024.REC.01', 'PACK.USPSTF.SCREEN.2024.REC.02', 'PACK.USPSTF.SCREEN.2024.REC.03',
    'PACK.USPSTF.SCREEN.2024.REC.04', 'PACK.USPSTF.SCREEN.2024.REC.05', 'PACK.USPSTF.SCREEN.2024.REC.06',
    'PACK.USPSTF.SCREEN.2024.REC.07', 'PACK.USPSTF.SCREEN.2024.DC.01', 'PACK.USPSTF.SCREEN.2024.T.01',
    'PACK.USPSTF.SCREEN.2024.T.02', 'PACK.USPSTF.SCREEN.2024.TX.01', 'PACK.USPSTF.SCREEN.2024.TX.02',
    'PACK.USPSTF.SCREEN.2024.RF.01', 'PACK.USPSTF.SCREEN.2024.SEV.01',
  ],
  all_display_ids: [
    'USPSTF-SCR-R1', 'USPSTF-SCR-R2', 'USPSTF-SCR-R3', 'USPSTF-SCR-R4', 'USPSTF-SCR-R5', 'USPSTF-SCR-R6', 'USPSTF-SCR-R7',
    'USPSTF-SCR-DC1',
    'USPSTF-SCR-T1', 'USPSTF-SCR-T2',
    'USPSTF-SCR-TX1', 'USPSTF-SCR-TX2',
    'USPSTF-SCR-RF1',
    'USPSTF-SCR-SEV1',
  ],
};
