import type { SourcePack } from './types';

export const PACK_WSES_ABD_2020: SourcePack = {
  source_pack_id: 'PACK.WSES.ABD.2020',
  source_name: 'WSES 2020 Guidelines — Acute Diverticulitis and Acute Mesenteric Ischemia',
  canonical_url: 'https://doi.org/10.1186/s13017-020-00313-4',
  publication_year: 2020,
  guideline_body: 'WSES',

  topic_tags: ['Diverticulitis', 'Mesenteric Ischemia', 'Acute Abdomen', 'Hinchey Classification', 'Surgery'],
  allowed_decision_scopes: [
    'acute diverticulitis diagnosis and classification',
    'uncomplicated vs complicated diverticulitis management',
    'Hinchey classification and surgical indications',
    'acute mesenteric ischemia diagnosis (CT angiography)',
    'mesenteric ischemia treatment (embolectomy vs anticoagulation)',
    'diverticulitis antibiotic indications',
  ],
  excluded_decision_scopes: [
    'chronic diverticular disease',
    'diverticular bleeding (GI bleeding pack)',
    'chronic mesenteric ischemia',
    'sigmoid volvulus management',
    'colonic pseudo-obstruction (Ogilvie syndrome)',
  ],

  recommendations: [
    {
      rec_id: 'PACK.WSES.ABD.2020.REC.01',
      display_id: 'WSES-ABD-R1',
      statement: 'CT with IV contrast is the imaging modality of choice for acute diverticulitis. It confirms the diagnosis, grades severity (Hinchey classification), and identifies complications (abscess, perforation, fistula).',
      normalized_claim: 'CT with IV contrast is gold standard for acute diverticulitis diagnosis. Enables Hinchey grading and complication assessment.',
      strength: 'strong',
      evidence_quality: 'high',
      provenance: { section: 'Diverticulitis Diagnosis', page_or_location: 'Section 2' },
    },
    {
      rec_id: 'PACK.WSES.ABD.2020.REC.02',
      display_id: 'WSES-ABD-R2',
      statement: 'Uncomplicated acute diverticulitis (Hinchey 0) can be managed without antibiotics in immunocompetent patients with mild symptoms per AGA guidelines. Outpatient management with clear liquid diet and close follow-up is appropriate.',
      normalized_claim: 'Uncomplicated diverticulitis (Hinchey 0): antibiotics not routinely necessary in immunocompetent patients. Outpatient management with clear liquids and follow-up.',
      strength: 'conditional',
      evidence_quality: 'moderate',
      context: 'AGA 2015 and multiple RCTs support selective antibiotic use',
      provenance: { section: 'Uncomplicated Diverticulitis', page_or_location: 'Section 3' },
    },
    {
      rec_id: 'PACK.WSES.ABD.2020.REC.03',
      display_id: 'WSES-ABD-R3',
      statement: 'Complicated diverticulitis with abscess >3-4cm (Hinchey Ib/II) should be managed with CT-guided percutaneous drainage plus IV antibiotics. Smaller abscesses can be treated with IV antibiotics alone.',
      normalized_claim: 'Diverticular abscess >3-4cm (Hinchey Ib/II): CT-guided percutaneous drainage + IV antibiotics. Abscess <3cm: antibiotics alone may suffice.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Complicated Diverticulitis', page_or_location: 'Section 4' },
    },
    {
      rec_id: 'PACK.WSES.ABD.2020.REC.04',
      display_id: 'WSES-ABD-R4',
      statement: 'Acute mesenteric ischemia should be suspected in patients with acute severe abdominal pain out of proportion to physical examination findings, especially with atrial fibrillation, recent MI, or hypercoagulable state. CT angiography is the diagnostic modality of choice.',
      normalized_claim: 'Mesenteric ischemia: "pain out of proportion to exam" + risk factors (Afib, MI, hypercoagulable). CT angiography is diagnostic standard.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Mesenteric Ischemia', page_or_location: 'Section 6' },
    },
    {
      rec_id: 'PACK.WSES.ABD.2020.REC.05',
      display_id: 'WSES-ABD-R5',
      statement: 'Acute SMA embolism confirmed on CTA should be treated with embolectomy or catheter-directed thrombolysis. SMA thrombosis may be managed with surgical revascularization or endovascular techniques. Anticoagulation with heparin should be started immediately upon diagnosis.',
      normalized_claim: 'Acute SMA embolism: embolectomy or catheter-directed thrombolysis. SMA thrombosis: surgical or endovascular revascularization. Start heparin immediately.',
      strength: 'strong',
      evidence_quality: 'moderate',
      provenance: { section: 'Mesenteric Ischemia Treatment', page_or_location: 'Section 7' },
    },
  ],

  diagnostic_criteria: [
    {
      criterion_id: 'PACK.WSES.ABD.2020.DC.01',
      display_id: 'WSES-ABD-DC1',
      name: 'Hinchey Classification of Diverticulitis',
      components: [
        'Hinchey 0: Uncomplicated — colonic wall thickening with pericolic fat stranding',
        'Hinchey Ia: Confined pericolic inflammation or phlegmon',
        'Hinchey Ib: Pericolic or mesocolic abscess',
        'Hinchey II: Pelvic, distant intra-abdominal, or retroperitoneal abscess',
        'Hinchey III: Generalized purulent peritonitis (ruptured abscess)',
        'Hinchey IV: Generalized fecal peritonitis (free perforation)',
      ],
      interpretation: 'Hinchey 0-Ia = non-operative management. Hinchey Ib-II = percutaneous drainage if abscess >3-4cm. Hinchey III-IV = emergent surgical intervention.',
      normalized_claim: 'Hinchey 0-Ia: conservative. Ib-II: drainage if abscess >3cm. III (purulent peritonitis): surgery (lavage or resection). IV (fecal peritonitis): emergent Hartmann procedure or resection with primary anastomosis.',
      provenance: { section: 'Classification', page_or_location: 'Section 2' },
    },
    {
      criterion_id: 'PACK.WSES.ABD.2020.DC.02',
      display_id: 'WSES-ABD-DC2',
      name: 'CTA Findings in Acute Mesenteric Ischemia',
      components: [
        'SMA occlusion (embolism: typically at branch point 3-8cm from ostium; thrombosis: at ostium)',
        'Absent bowel wall enhancement in affected segment',
        'Bowel wall thickening or paper-thin wall',
        'Mesenteric fat stranding',
        'Pneumatosis intestinalis (transmural necrosis)',
        'Portal venous gas (late, ominous finding)',
        'Free fluid',
      ],
      interpretation: 'CTA has >95% sensitivity for mesenteric ischemia. Embolic occlusion typically 3-8cm from SMA origin. Thrombotic occlusion at the ostium. Pneumatosis/portal gas = likely bowel necrosis.',
      normalized_claim: 'CTA for mesenteric ischemia: look for SMA occlusion, absent wall enhancement, pneumatosis. Embolism at branch point vs thrombosis at ostium.',
      provenance: { section: 'Mesenteric Ischemia Diagnosis', page_or_location: 'Section 6' },
    },
  ],

  thresholds: [
    {
      threshold_id: 'PACK.WSES.ABD.2020.T.01',
      display_id: 'WSES-ABD-T1',
      parameter: 'Diverticular abscess size for percutaneous drainage',
      value: '3-4',
      unit: 'cm',
      clinical_meaning: 'Diverticular abscesses >3-4cm benefit from CT-guided percutaneous drainage plus antibiotics. Smaller abscesses may resolve with IV antibiotics alone.',
      normalized_claim: 'Diverticular abscess >3-4cm: percutaneous drainage + antibiotics. <3cm: IV antibiotics alone.',
      direction: 'above',
      provenance: { section: 'Complicated Diverticulitis', page_or_location: 'Section 4' },
    },
    {
      threshold_id: 'PACK.WSES.ABD.2020.T.02',
      display_id: 'WSES-ABD-T2',
      parameter: 'Lactate level in suspected mesenteric ischemia',
      value: '2.0',
      unit: 'mmol/L',
      clinical_meaning: 'Elevated lactate (>2.0 mmol/L) in the setting of acute abdominal pain raises suspicion for mesenteric ischemia but is a late and non-specific finding. Normal lactate does not exclude early mesenteric ischemia.',
      normalized_claim: 'Lactate >2.0 mmol/L supports but does not confirm mesenteric ischemia (late finding). Normal lactate does not exclude early ischemia.',
      direction: 'above',
      provenance: { section: 'Laboratory Evaluation', page_or_location: 'Section 6' },
    },
  ],

  treatment_steps: [
    {
      step_id: 'PACK.WSES.ABD.2020.TX.01',
      display_id: 'WSES-ABD-TX1',
      action: 'Outpatient management of uncomplicated diverticulitis',
      normalized_claim: 'Uncomplicated diverticulitis (Hinchey 0): outpatient clear liquid diet → advance as tolerated. Antibiotics optional in immunocompetent patients. Follow-up in 2-3 days. Colonoscopy in 6-8 weeks to exclude malignancy.',
      timing: 'Outpatient; follow-up in 2-3 days',
      condition: 'Uncomplicated acute diverticulitis in immunocompetent patient',
      provenance: { section: 'Uncomplicated Management', page_or_location: 'Section 3' },
    },
    {
      step_id: 'PACK.WSES.ABD.2020.TX.02',
      display_id: 'WSES-ABD-TX2',
      action: 'Emergent surgery for Hinchey III/IV diverticulitis',
      normalized_claim: 'Hinchey III (purulent peritonitis): laparoscopic lavage and drainage (controversial) OR sigmoid resection. Hinchey IV (fecal peritonitis): emergent sigmoid resection — Hartmann procedure (colostomy) or primary anastomosis with diverting ileostomy.',
      timing: 'Emergent',
      condition: 'Hinchey III or IV complicated diverticulitis with generalized peritonitis',
      provenance: { section: 'Surgical Management', page_or_location: 'Section 5' },
    },
    {
      step_id: 'PACK.WSES.ABD.2020.TX.03',
      display_id: 'WSES-ABD-TX3',
      action: 'Embolectomy or revascularization for acute mesenteric ischemia',
      normalized_claim: 'SMA embolism: open embolectomy or catheter-directed thrombolysis/thrombectomy. SMA thrombosis: surgical bypass or endovascular stenting. Assess bowel viability; resect frankly necrotic bowel. Second-look laparotomy at 24-48h.',
      timing: 'Emergent — within hours of diagnosis',
      condition: 'Acute mesenteric ischemia confirmed on CTA',
      drug_details: { drug: 'Unfractionated heparin', dose: 'Bolus 80 U/kg then 18 U/kg/h', route: 'IV' },
      provenance: { section: 'Mesenteric Ischemia Treatment', page_or_location: 'Section 7' },
    },
  ],

  red_flags: [
    {
      flag_id: 'PACK.WSES.ABD.2020.RF.01',
      display_id: 'WSES-ABD-RF1',
      finding: 'Acute severe abdominal pain "out of proportion" to examination findings in a patient with atrial fibrillation',
      implication: 'Classic presentation of acute mesenteric ischemia (SMA embolism). Delayed diagnosis leads to bowel necrosis, peritonitis, and death. Initial exam may appear benign.',
      action: 'Emergent CT angiography. Start IV heparin immediately. Surgical consultation. Do not attribute to other diagnoses without excluding mesenteric ischemia.',
      urgency: 'immediate',
      provenance: { section: 'Mesenteric Ischemia', page_or_location: 'Section 6' },
    },
    {
      flag_id: 'PACK.WSES.ABD.2020.RF.02',
      display_id: 'WSES-ABD-RF2',
      finding: 'Diffuse peritonitis with pneumoperitoneum on CT in patient with diverticulitis',
      implication: 'Hinchey IV — free perforation with fecal peritonitis. High morbidity and mortality without emergent surgical intervention.',
      action: 'Emergent sigmoid resection (Hartmann procedure). Broad-spectrum IV antibiotics. Aggressive fluid resuscitation.',
      urgency: 'immediate',
      provenance: { section: 'Surgical Indications', page_or_location: 'Section 5' },
    },
  ],

  severity_definitions: [
    {
      severity_id: 'PACK.WSES.ABD.2020.SEV.01',
      display_id: 'WSES-ABD-SEV1',
      level: 'Uncomplicated Diverticulitis (Hinchey 0)',
      criteria: [
        'LLQ pain with localized tenderness',
        'CT showing colonic wall thickening and pericolic fat stranding',
        'No abscess, free air, or free fluid',
        'No systemic toxicity (afebrile or low-grade fever)',
      ],
      management_implications:
        'Outpatient management in immunocompetent patients. Antibiotics may not be necessary (AGA). Clear liquid diet advancing as tolerated. Follow-up colonoscopy in 6-8 weeks to exclude colorectal cancer.',
      provenance: { section: 'Classification', page_or_location: 'Section 2' },
    },
    {
      severity_id: 'PACK.WSES.ABD.2020.SEV.02',
      display_id: 'WSES-ABD-SEV2',
      level: 'Acute Mesenteric Ischemia with Bowel Necrosis',
      criteria: [
        'SMA occlusion on CTA',
        'Absent bowel wall enhancement',
        'Pneumatosis intestinalis or portal venous gas',
        'Peritoneal signs on exam',
        'Elevated lactate with metabolic acidosis',
        'Hemodynamic instability',
      ],
      management_implications:
        'Emergent laparotomy for bowel resection. Revascularization if feasible (embolectomy or bypass). Resect all frankly necrotic bowel; leave questionable bowel for second-look at 24-48h. Massive fluid resuscitation. Broad-spectrum antibiotics. High mortality (60-80%).',
      provenance: { section: 'Mesenteric Ischemia', page_or_location: 'Section 7' },
    },
  ],

  source_pack_version: 1,
  status: 'active',
  last_normalized: '2026-04-16',
  normalizer_version: 1,
  normalization_notes: 'Surgery pack: Acute abdomen — diverticulitis (Hinchey classification, antibiotic debate, surgical indications) and acute mesenteric ischemia (CTA diagnosis, embolectomy, second-look laparotomy).',

  all_item_ids: [
    'PACK.WSES.ABD.2020.REC.01', 'PACK.WSES.ABD.2020.REC.02', 'PACK.WSES.ABD.2020.REC.03',
    'PACK.WSES.ABD.2020.REC.04', 'PACK.WSES.ABD.2020.REC.05',
    'PACK.WSES.ABD.2020.DC.01', 'PACK.WSES.ABD.2020.DC.02',
    'PACK.WSES.ABD.2020.T.01', 'PACK.WSES.ABD.2020.T.02',
    'PACK.WSES.ABD.2020.TX.01', 'PACK.WSES.ABD.2020.TX.02', 'PACK.WSES.ABD.2020.TX.03',
    'PACK.WSES.ABD.2020.RF.01', 'PACK.WSES.ABD.2020.RF.02',
    'PACK.WSES.ABD.2020.SEV.01', 'PACK.WSES.ABD.2020.SEV.02',
  ],
  all_display_ids: [
    'WSES-ABD-R1', 'WSES-ABD-R2', 'WSES-ABD-R3', 'WSES-ABD-R4', 'WSES-ABD-R5',
    'WSES-ABD-DC1', 'WSES-ABD-DC2',
    'WSES-ABD-T1', 'WSES-ABD-T2',
    'WSES-ABD-TX1', 'WSES-ABD-TX2', 'WSES-ABD-TX3',
    'WSES-ABD-RF1', 'WSES-ABD-RF2',
    'WSES-ABD-SEV1', 'WSES-ABD-SEV2',
  ],
};
